### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by han3388** [daumPostcode/QnA#10]
안녕하세요.
알려주신 내용으로도 해결이 어렵다고 하네요.
혹시 메일주소 좀 알려주시면 안되나요?
저희 홈피 ftp 정보를 알려드릴테니 한번 봐 주시면 안되겠습니까?
여기에는 공개글이라 못올려서요.
notifications@github.com 메일로는 연락을 드렸더니 확인을 안하셨네요. 사용하지 않는 주소인지...

**Comment by daumPostcode** [comment]
네~ 현재 제가 답변을 달고 있는 이계정의 프로필을 들어가 보시면(아이디부분을 누르시면 될겁니다) 메일이 있습니다 ^^ 그 계정으로 보내주시면 됩니다.
그런데 ftp라는 것이 전체 소스코드를 알려주신다는 것인가요? 
그리고 오류가 그 보트라우저에서만 발생하는 것인가요 아니면 일반적인 크롬이나 기존브라우저에서 발생하는 오류인가요?

단순한 오류는 쉽게 대응이 되는데 전체 코드를 보고 확인하는것은 제가 오늘 휴가라 시간이 좀 걸릴것 같습니다;;;;;

그리고 노티피케이션 메일은 여기에 이슈나 코멘트 달면 깃허브에서 자동으로 가는 발신전용이라 저희껀 아니에요 ^^
