### ISSUE TITLE
우편번호 찾기 자바스크립트 오류 문의 드립니다.

### ISSUE THREAD

**Issue by zephome** [daumPostcode/QnA#100]
안녕하세요. 
우편번호 서비스 이용 중 몇몇 고객분께서 우편번호 찾기가 안된다는 말씀을 듣고 테스트해보았는데 자바스크립트 오류가 발생되어 문의드립니다.

### 오류 내역
- 오류 브라우저
   - Windows7, IE 11.0.9600.18349
   - Windows7, IE 11.0.9600.17959
- 방식: 팝업을 이용한 우편번호 찾기
- 내용
   - 자바스크립트 오류가 항상 발생되는건 아니고 제PC에서는 10번중 4~5회 정도 발생되고, 고객 PC에서는 계속 발생 됩니다.
   - 팝업창에 아무것도 표시되지 않습니다.
   - 샘플 사이트 http://postcode.map.daum.net/guide 에서도 동일한 오류가 발생됩니다.
   - 현재 크롬에서는 정상 작동이 되어서 크롬으로 사용중입니다.
   - 오류 내역 (170111.js)
   SCRIPT5007: 정의되지 않음 또는 null 참조인 'write' 속성을 가져올 수 없습니다.
파일: 170111.js, 줄: 1, 열: 17030
   [![daum_zipcode.png](https://s28.postimg.org/l0f3tlob1/daum_zipcode.png)](https://postimg.org/image/7ji5aqdzd/)

**Comment by daumPostcode** [comment]
@zephome 
네~ 안녕하세요~

일단 현재 저희가 보유한 Windows 7 + IE11(11.0.9600.18537) 에서는 재현이 안되네요;;
아무런 프로그램이 깔려있지 않은 순수 윈도우7에 IE만 11인 상태로 테스트를 하였습니다.

일단 오류는 write속성을 가져올 수 없다는 것은 document가 null이라는 것인데, document의 경우,
open()함수를 이용해서 실행을 할경우, var popup = window.open(...);으로 부터 받은 popup객체의 popup.window.document객체 입니다. 즉 window.open함수가 정상적으로 실행이 되지 않아서 발생한 문제로 보입니다.

예전에 비슷한 문제가 있었습니다만, 원인은 해당 PC의 MS Office 97 관련하여 발생한 문제였으며, 조금 복잡하긴 하지만 해결가능한 방법이 있었습니다. (다만 현재의 원인과 100% 맞다고는 확답을 못드리겠네요;;)

일단 당시의 해결방법을 아래에 적어 드리겠습니다.
----------------------------------
"태그가 틀립니다" "The tag is invalid" 에러에 대한 해결책을 찾았습니다. MS Office 97 관련 소프트웨어를 설치하면 생기는 문제였네요. dll 등록될 때 window.open 명령어를 막는 모양입니다.

해결방법은 , 64비트 윈도우일 경우를 예를 들면

1. C:\Windows\SYSWOW64\DOCOBJ.DLL     위치에 있는 DOCOBJ.DLL 을 unregister 시킵니다.
         해당 위치에서 regsvr32 docobj.dll -u

2. IE 가 위치한 곳에 있는 ieproxy.dll 을 등록합니다.
예를 들어 C:\Program Files\Internet Explorer\ieproxy.dll 있는
ieproxy.dll 을 regsvr32 ieproxy.dll 시킵니다.

참고:
https://social.msdn.microsoft.com/Forums/ie/en-US/e4828bed-a97b-4812-b919-e67f3438e8f8/windowopen-with-documentwrite-error-in-windows-7-with-ie-807600-the-tag-is-invalid?forum=iewebdevelopment  
----------------------------------

한번 확인 부탁드립니다. 일단 저희가 가지고 있는 PC에서는 재현이 되지 않아 오류를 확인이 불가능 한데요, 혹시 적용한 사이트의 URL을 알 수 있을까요? 

추가적으로 간단히 확인해 보실려면

var popup = window.open('','_blank');
popup.window.document.write('<iframe src="팝업창에 보여줄 페이지 URL"></iframe>')으로 해보시면 확인 가능 하십니다.

**Comment by zephome** [comment]
원인 파악에 대해 시간이 소요될것으로 판단되어 우편번호 찾기 방식을 변경하였습니다.

팝업 -> iframe을 이용한 레이어로 변경하니 문제가 발생하는 컴퓨터에서 정상작동 되네요 ^^

답변 감사드리고, 즐거운 하루 되세요~

**Comment by daumPostcode** [comment]
@zephome 
넵;

윈도우 IE계열에서 window.open의 오류가 정말 가끔 들어오는 문제인데요. 이게 해결하기가 좀 쉽지가 않은 상황이긴 합니다;; 

말씀하신 것처럼 이를 layer모드를 이용하면 대부분 해결이 가능하시며,

추가적으로 처음 댓글에 제가 popup.window.document.write를 해서 팝업의 내부화면을 그린다고 했는데요,
이 방법에서 오류가 나고, 이외 window.open('도메인')을 했을때 오류가 나지 않는다면,
팝업을 직접 만드시고, 그 팝업내부에 저희 서비스를 embed로 페이지에 꽉차게 띄우시는 방식으로도 활용 가능 하십니다.

참고 부탁드려요;

감사합니다.
