### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by lovelyjoy** [daumPostcode/QnA#101]
![20170112_180535](https://cloud.githubusercontent.com/assets/25075975/21883514/eaaba5ce-d8f2-11e6-935d-bbbf20cb349a.png)

http://www.dollstory.kr/

이 사이트 회원 가입을 하려고 하는데
주소 찾기 창을 누르면 v1 서비스가 곧 종료된다
서비스는 2월 6일에 종료될 예정이라는 공지글만 뜨고
주소 찾기가 안 됩니다. 당연히 주소 입력도 안 되구요.
주소 입력이 안 되니 가입도 안 됩니다.

주인한테 문의를 하려고 해도 회원 가입을 해야 문의가 됩니다.
주인한테 연락해서 문의할 길도 없고 회원가입은 해야겠고 답답한 상황인데
서비스가 6일에 종료되는 거면 그때까지는 해당사이트에서 주소 찾기를 
사용할 수 있게 해주셔 야하는 거 아닌지요?
이러지도 못하고 저러지도 못하고 답답해서 이곳에 글 씁니다.

**Comment by daumPostcode** [comment]
@lovelyjoy 
네; 안녕하세요;;

말씀해 주신 사이트에 접속해보니; 말씀해주신 것과 같이 V1을 사용하고 있는데요.
저희 서비스 가이드에 적혀 있는 것처럼 해당 종료에 대해서는 2016년 8월부터 공지를 하였습니다. 다만 쇼핑몰들이 직접 개발보다는 외주를 맡겨서 하는 경우가 많아 개발에 소요되는 시간이 좀 길 수 있어요;; (실제 변경 의사가 있는 쇼핑몰에서는 연락도 오고 CS도 들어오고 있습니다.)

해당 사이트에는 로그인해서 질문을 남기시는 것보다, 사이트 아랫부분에 연락처와 메일이 있는데; 그쪽으로 직접 연락을 해보시는게 좋을 것 같습니다.

그리고 올려주신 스샷에서 검정색 박스의 우하단을 보시면 X버튼이 있는데 해당 버튼을 누르면 검색바가 보이니 검색을 하실 수 있을거에요; 닫기 버튼의 경우에는 스샷을 보니 잘 안보이는 것 같아; 다음 주 업데이트때 조금 키우도록 하겠습니다; 

불편을 드려 죄송합니다;
