### ISSUE TITLE
도로명, 건물번호  항목

### ISSUE THREAD

**Issue by bigonekim** [daumPostcode/QnA#1010]
주소를 해외 주소처럼 3개 항목으로 구분해서 관리할려고 합니다.

경기 성남시 분당구 판교역로 235

위의 주소의 경우, 아래와 같이 관리해야 하는데

경기, 성남시 분당구, 판교역로 235 

반환하는 데이타는 아래와 같네요.

sido=경기,  sigungu='성남시 분당구',  roadname='판교역로'

위와 같이 도로상의 건물위치번호인 235 가 빠져 있는데요.

어떻게 하면 '판교역로 235'  를 반환받을 수 있나요?

**Comment by daumPostcode** [comment]
@bigonekim 
안녕하세요~

아뇨 현재 해당 데이터만 내리는 변수는 없습니다.

전체 full 주소에서 공백에 따라 구분을 지으셔야 될것 같습니다.
아니면 sido, sigungu, bname1 등의 정보를 가지고 판단하셔야 될것 같습니다.

"동"에 포함된 주소는 sigungu다음에 도로명이 나오지만, "읍면"에 속한 주소는 "읍,면" sigungu 다음에 bname1 이 들어간 후 도로명이 붙기 때문에 이러한 케이스를 구분하셔서 작업 하셔야 합니다.
