### ISSUE TITLE
일부사용자 빈페이지 오류

### ISSUE THREAD

**Issue by ohjungsuk** [daumPostcode/QnA#102]
![default](https://cloud.githubusercontent.com/assets/25096173/21920238/205ee3e2-d9a3-11e6-9d45-fe402c2788ba.png)
저희싸이트사용중인 고객중에 한분이 주소창이 뜨질않아서 문의가왔었습니다.
원격으로 확인한결과 윈도우7 익스11 이었고 설정 초기화도 하였으나 동일하였습니다.
크롬으로 설치하고 진행시엔 정상작동하였습니다.
의심스러웠던점은 세콤ps보안프로그램이 유저pc에 설치되어있던점입니다.
혹시위와같은 증상에대해 보고된바가 있나요?

**Comment by daumPostcode** [comment]
@ohjungsuk 
안녕하세요~

아뇨 현재 위와 같은 문제는 보고된바 없습니다.
세콤PS보안프로그램이라는게 IE에서 특정 스크립트가 호출되는 것을 막는지 확인이 필요해 보이네요;
저렇게 하얗게 렌더링 된다는 것은 popup객체에 document.write를 하는데; 이부분이 실행이 되지 않아서 발생하는 문제입니다.

예전에 세콤PS보안프로그램의 설치유무는 알수 없었지만, 비슷하게 popup쪽 코드를 사용할때 오류가 났던 사용자분이 계셨는데요, 저희는 재현이 되지 않아 해결을 할 수가 없었는데, 유저분께서 찾아주신 내용이 있습니다. 참고가 되실 수 있으니 여기에 적어 드리겠습니다

-----------

"태그가 틀립니다" "The tag is invalid" 에러에 대한 해결책을 찾았습니다. MS Office 97 관련 소프트웨어를 설치하면 생기는 문제였네요. dll 등록될 때 window.open 명령어를 막는 모양입니다.

해결방법은 , 64비트 윈도우일 경우를 예를 들면

C:\Windows\SYSWOW64\DOCOBJ.DLL 위치에 있는 DOCOBJ.DLL 을 unregister 시킵니다.
해당 위치에서 regsvr32 docobj.dll -u

IE 가 위치한 곳에 있는 ieproxy.dll 을 등록합니다.
예를 들어 C:\Program Files\Internet Explorer\ieproxy.dll 있는
ieproxy.dll 을 regsvr32 ieproxy.dll 시킵니다.

참고:
https://social.msdn.microsoft.com/Forums/ie/en-US/e4828bed-a97b-4812-b919-e67f3438e8f8/windowopen-with-documentwrite-error-in-windows-7-with-ie-807600-the-tag-is-invalid?forum=iewebdevelopment

-----------

전혀 쌩뚱맞게 MS Office 문제였고;; 일단은 해당 현상은 이전에 보고된적이 없어서 정확히 무슨 이유인지 알기가 힘드네요 ;;;;;

**Comment by zephome** [comment]
저와 비슷한 케이스같네요. #100 
저는 정확한 해결방법은 아닌거 같지만 급한데로 iframe을 이용한 레이어 띄우기로 해결하였습니다.
