### ISSUE TITLE
ios webview에서 onComplete 동작이 작동하지 않습니다.

### ISSUE THREAD

**Issue by mango906** [daumPostcode/QnA#1030]
안녕하세요. react-native에서 웹뷰를 통해 daum-postcode를 통해 주소 검색 기능울 구현하였습니다.
안드로이드는 잘 작동하는데 ios에선 잘 작동하지 않더라구요.

비슷한 사례로 구글링을 해보니 file:// 로 시작하는 경우 onComplete 가 동작하지 않다고 확인했습니다.
하지만 제 경우에는 https:// 로 시작하는데도 작동하지 않습니다.

<img width="1000" alt="Untitled (1)" src="https://user-images.githubusercontent.com/38802280/232953699-e5749bad-6ed5-4830-85bd-4c79a84e5ed5.png">

웹 서버에 저희 페이지를 올렸는데 별도로 뭔가 처리해야할게 있을까요 ?

**Comment by daumPostcode** [comment]
@mango906 
안녕하세요~
음 iOS만 문제가 생기거나 하진 않을 것인데; 해당 플랫폼에서 postMessage에 대한 사항을 한번 검색해 보시는게 어떠실까 합니다.
react-native를 제가 이용해본 경험이 없어서 정확한 사용법을 알지 못하는데;

서로 이종도메인 통신을 해야하는데, 뭔가 제약에 걸린다던가 설정이 잘못된다던가 하는게 아닐까 합니다;

현재 올려주신 내용으로는 해결책을 말씀드리긴 어려워보입니다.
