### ISSUE TITLE
안녕하세요 :) 하이브리드앱에  api 사용 문의드립니다. 

### ISSUE THREAD

**Issue by Taxtripe** [daumPostcode/QnA#105]
현재 ionic 프레임워크를 사용하고 있으며 검색 api를 사용하고자 합니다. 
웹을 통한 테스트로는 정상작동을 합니다만 실제 앱에서는 원하는 주소를 클릭후 아무런 변화가 일어나지 않습니다. 
FAQ 14번을 참고하여 oncomplete 내부에서 로그를 찍어도 로그가 나오지 않습니다 ㅜㅜ . 혹시 해결방안이나 ionic 에서 사용법 등 관련 조언을 얻고싶습니다. 
감사합니다 :)

**Comment by daumPostcode** [comment]
@Taxtripe 

네~ 안녕하세요~
먼저 [FAQ 10번](https://github.com/daumPostcode/QnA#10-iosandroid에서-webview를-이용하여-사용할-수-있나요)을 참고해주시기 바라며,

기본적으로 저희 서비스는 웹서비스이며, 데이터 전송의 경우 이종 도메인간 데이터를 전송하는 방식을 사용하고 있습니다.
이를 사용시 필수적인 부분이 바로 이용하시는 사이트의 domain값입니다.

아마 웹에서는 정상적이라는 것인 브라우저를 통해 실행하시기 때문에 이 도메인값이 있어서 정상 동작하는 것인데,
ionic을 통해 빌드해서 패키징이 되면, 이 도메인값이 없기 때문에 정상 동작하지 않습니다. 
(ionic도 cordova플랫폼을 이용하는 것으로 아는데 이게 내부적으로 webview에서 정적으로 스크립트들을 가져와서 실행하는 구조라고 알고 있습니다)

그래서 이용하시려면, 우편번호가 입력이 필요한 페이지에 진입할때 따로 webview를 실행시켜서 거기서 우편번호 입력이 필요한 페이지를 URL로 호출한 후, 사용하셔야 합니다.

이 방법이 조금 난해하기 때문에, 개인적으로는 juso.go.kr에서 REST API를 제공하는 것 같아보이니 데이터만 가져올 수 있는 API를 이용하시는게 좀 더 개발이 편하실 것 같아요;;;;

**Comment by kumquat0601** [comment]
#97를 한 번 확인해주세요!

아니면 [여기](http://blog.naver.com/PostView.nhn?blogId=blackbagsoft&logNo=220724007943)를 참고하셔도 좋을 것 같아요!

**Comment by daumPostcode** [comment]
@Taxtripe 추천 드립니다.
