### ISSUE TITLE
간헐적으로 팝업 종료시 나타나는 문제

### ISSUE THREAD

**Issue by mucsiza** [daumPostcode/QnA#106]
크롬 55.0 버전에서 주소 검색후 결과값 선택후

script 에 self.close() 명령을 넣어서 팝업창을 닫습니다.

하지만 다른컴퓨터 같은 버젼 브라우져 에서 선택시에는 

자기 자신만 닫기는게 아니라 부모창까지 닫아 버리는 현상이 발생하고 있습니다.

혹시 이것에 대해 의견이나 해결방안이 있는지 궁금합니다.

--source

$("#SearchStartAddress, #SearchEndAddress, #StartAddress, #EndAddress").click(function(){
                    var GetID = $(this).attr("id");

                    new daum.Postcode({
                        oncomplete: function(data) {
                            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                            // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.
                            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                            var fullRoadAddr = data.roadAddress; // 도로명 주소 변수
                            var extraRoadAddr = ''; // 도로명 조합형 주소 변수

                            // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                            // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                            if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                                extraRoadAddr += data.bname;
                            }
                            // 건물명이 있고, 공동주택일 경우 추가한다.
                            if(data.buildingName !== '' && data.apartment === 'Y'){
                                extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                            }
                            // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                            if(extraRoadAddr !== ''){
                                extraRoadAddr = ' (' + extraRoadAddr + ')';
                            }
                            // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.
                            if(fullRoadAddr !== ''){
                                fullRoadAddr += extraRoadAddr;
                            }

                            // 우편번호와 주소 정보를 해당 필드에 넣는다.
                            if(GetID == "SearchStartAddress" || GetID == "StartAddress"){
                                $("#StartAddress").val(fullRoadAddr);
                            }else if(GetID == "SearchEndAddress" || GetID == "EndAddress"){
                                $("#EndAddress").val(fullRoadAddr);
                            }

                            self.close();
                        }
                    }).open();

**Comment by daumPostcode** [comment]
@mucsiza 
네~ 안녕하세요~

일단, 저희 API에서는 따로 close를 할 수 있는 메소드는 제공하고 있지 않습니다.
또한 실행을 하실때 실행 함수에 autoClose:false를 임의로 넣지 않는한, oncomplete함수 실행이 끝난 후에 팝업이 자동으로 닫힙니다.

아마 제가 생각하기로, self.close()에서 self는 팝업창이 아니라 부모창입니다. 왜냐하면 서비스 팝업은 부모페이지에 데이터만 보내면 모든게 끝납니다. 이때 부모페이지에서 이벤트를 받아 oncomplete을 실행 한후, 오류없이 실행이 끝나면 팝업객체를 이용하여 close를 시킵니다. 다만 self.close()를 할 경우에는 이 self가 window인데, 부모페이지가 팝업이 아니라면 꺼지지 않고 "Scripts may close only the windows that were opened by it" 라는 메세지가 콘솔에 뜹니다. 
해당 문제의 경우에는 크롬의 버그일 수도 있고, 바인딩 오류일 수도 있는데요. 정확한 이유는 아직 잘 모르겠네요;

결론은, 크롬의 버그인지 아닌지 확실하지 않지만, 분명히 말씀드릴 수 있는건 저 self는 저희 서비스팝업을 가리키는 변수는 아닙니다.

**Comment by mucsiza** [comment]
해결했습니다.
감사합니다.

**Comment by chans1999** [comment]
안녕하세요 혹시 클로즈 안되는 문제를 어떻게 해결했는지 알 수 있을까요?

**Comment by daumPostcode** [comment]
@chans1999 
자동으로 클로즈가 안되는 현상은 보통

- open함수의 옵션으로 autoClose를 false로 준경우
- oncomplete함수내에서 오류가 발생했을경우
ㄴ 단 하나의 오류라도 발생하면, 닫히지 않습니다. 개발자 도구(팝업창에도 개발자 도구를 여시고, 부모페이지에서도 열어서 확인해 보셔요)
- 부모페이지가 특정 조건에 의해 같은 페이지로 submit되서 발생하는 착시현상
ㄴ 이전에 이와 비슷한 이슈가 있었습니다. 우편번호검색버튼을 눌러서 팝업창이나 레이어를 띄웠는데, 개발자 분께서 코드레벨에서 해당 버튼이 submit기능을 하는 역할을 해서 자기도 모르는 사이에 같은 페이지로 submit이 되서, 발생한 문제로, 화면이 아주 잠깐 깜빡이기만 하기 때문에 모르고 넘어가셨던 문제가 있었습니다. 

한번 확인 부탁드립니다.
체크한 이후에도 계속 문제가 발생하시면 따로 이슈 등록해 주시면 감사하겠습니다~
