### ISSUE TITLE
축약형 주소 버그 관련

### ISSUE THREAD

**Issue by HelloSolsol** [daumPostcode/QnA#107]
안녕하세요 축약형 주소 버그 관련해서 밑에글에 9일전 댓글을 한번 달았었는데요

이후에 데이터가 또 이렇게 들어오네요 
-- 경상북도 1/17, 1/19
-- 인천광역시 1/18

최근 6개월간 축약형 버그가 발생한적이 단 한건도 없었는데 최근에 종종
이렇게 발생하는데 혹시 아직 해결중인지 궁금합니다.

**Comment by daumPostcode** [comment]
@HelloSolsol 

네~ 안녕하세요.
우선 불편을 드려 매우 죄송합니다.

지난 1월 9일 패치에서 js API에서 서버로 보내는 파라미터의 명칭이 몇가지가 변경되었습니다.
즉 API에서도 서버에서도 이제 새로 변한 파라미터로 대응을 하고 있습니다.

그리고 내부망 테스트시 문제가 발견되지 않아 배포를 진행했는데, 간혹 몇몇분들에게 축양형 버그가 발생하였습니다.
그 이유는 https프로토콜을 사용하고 spi.maps.daum.net 도메인을 이용해서 JS API를 사용하시는 분들께 발생하였으며, 문제가 해당 서버의 캐시 기간 문제였습니다. 
다만, 해당 서버의 캐시를 임의로 저희가 제어를 할 수 없는 상태이기 때문에, 
부득이하게 저번 댓글에서도 말씀드린 것과 같이 도메인을 추가 연결(다른 서버)하여 알려드리게 되었습니다.

그래서 https환경을 이용하시고 아직까지 도메인을 spi.maps.daum.net/imap을 사용하신다면

ssl.daumcdn.net/dmaps로 변경해 주시면 감사하겠습니다.
바꾸시지 않더라고 해당 사이트에 접속하는 사용자가 브라우저 캐시 정보를 모두 삭제하면 되긴 하지만, 실질적으로 이게 불가능 하기 때문에, 원 코드를 변경해 주시면 감사하겠습니다.

자세한 내용은 저희 가이드 페이지 https://spi.maps.daum.net/postcode/guidessl 를 참고 부탁드립니다.

추가적으로 현재 JS API의 최신버전은 170118 버전입니다.

ps. 1월 18일에 저희 카카오톡 yellowID공지 채널로 https프로토콜을 사용하시는 분들은 api의 도메인을 모두 변경해달라는 메세지를 보내드렸습니다. 아마 이 메세지를 받아보셨는지 모르나, 못받으셨다면, 저희 가이드 페이지 맨 하단에 카카오톡에 친구추가 하는 방법이 적혀 있으니 참고 부탁드립니다. 앞으로 버그수정이나 기능 추가의 경우 해달 채널로 계속 공지 예정입니다.

**Comment by HelloSolsol** [comment]
@daumPostcode 
답변감사합니다.
