### ISSUE TITLE
주소 검색할 때 placeholder가 사라지지 않습니다.

### ISSUE THREAD

**Issue by yjp9603** [daumPostcode/QnA#1073]
script url을 통해 팝업창을 띄워서 주소를 검색할 때, 아래 사진처럼 placeholder 텍스트가 사라지지 않습니다.
검색창에 입력 후 다른 영역을 클릭하거나, 검색버튼을 눌렀을 때는 placeholder의 기본텍스트가 사라지는데, 입력하고 있을 때는
사라지지 않아서 입력하고 있는 글자를 보기가 어렵습니다.

![image](https://github.com/kmsbernard/react-daum-postcode/assets/108462305/4e07eca7-dbcb-43cc-af88-a2474088978e)

카카오 홈페이지에서도 같은 현상이 발생하던데, 라이브러리의 문제일까요..?
![image](https://github.com/daumPostcode/QnA/assets/108462305/9f502ee6-1a0a-425b-9902-4ed2597c42eb)
 

좋은 라이브러리 만들어주셔서 감사합니다.

**Comment by daumPostcode** [comment]
@yjp9603 
재현되는 케이스 제공 부탁드립니다.

현재 말씀하신 상황은 제가 테스트하는 환경에서는 재현이 되지 않습니다.

OS 종류 및 버전
브라우저 종류 및 버전

확인 부탁드립니다. 너무 낮은 버전의 브라우저를 사용해야 되는 환경이 아니라면, 최신 브라우저 환경으로 올려 주시는걸 적극 권장합니다.

**Comment by yjp9603** [comment]
> @yjp9603 재현되는 케이스 제공 부탁드립니다.
> 
> 현재 말씀하신 상황은 제가 테스트하는 환경에서는 재현이 되지 않습니다.
> 
> OS 종류 및 버전 브라우저 종류 및 버전
> 
> 확인 부탁드립니다. 너무 낮은 버전의 브라우저를 사용해야 되는 환경이 아니라면, 최신 브라우저 환경으로 올려 주시는걸 적극 권장합니다.

OS 종류 및 버전: 윈도우 11 Home / 10.0.22621 버전
브라우저 종류 및 버전: 크롬 / 117.0.5938.89(공식 빌드) 최신 버전

제가 확인해본 결과 윈도우 11 크롬에서만 이런현상이 일어나고 있습니다.
윈도우 11 MS 엣지, 윈도우 10 크롬에서는 같은 현상이 재현되지 않네요.

**Comment by daumPostcode** [comment]
@yjp9603 
현재 win11 (항상 최신 업데이트), 그리고 크롬브라우저에서 확인해 봤을대 별다른 이슈가 발생하지 않습니다.
가이드 페이지에서도 발생을 하니 원인 찾기가 수월할 것 같긴한데,

가이드페이지에서 개발자도구를 여신다음에, 위와 같은 오류가 뜰때, 스크립트 오류가 발생하고 있는지 확인 부탁드립니다.
