### ISSUE TITLE
축약형 주소에서 제주특별자치도 제외 문제 

### ISSUE THREAD

**Issue by gofeel** [daumPostcode/QnA#108]
다른 주소는 모두 정상적인 반면, 제주는 '제주'가 아닌 '제주특별자치도'로 표기됩니다.

**Comment by gofeel** [comment]
세종특별자치시 도 축약되지 않습니다.

**Comment by daumPostcode** [comment]
@gofeel 
네~ 안녕하세요~

'제주특별자치도','세종특별자치시'의 경우 지자체의 요청에 따라 축약형을 제공하지 않습니다.

해당 주소를 축약하고 싶으시다면, 저희가 제공하기 어려워, 직접 줄여서 사용하셔야 될것 같아요.

해당 설명이 가이드 페이지에 없는 것으로 확인되어, 다음번 업데이트에 추가해 두도록 하겠습니다;

감사합니다.
