### ISSUE TITLE
vue-daum-postcode - 검색어 초기화 기능

### ISSUE THREAD

**Issue by Ahngbeom** [daumPostcode/QnA#1086]
`vue-daum-postcode`에서 검색어를 초기화시킬 수 있는 방법이 있을까요?

프로젝트에서 모달을 통해 `vue-daum-postcode` 컴포넌트를 띄우고 있는데, 모달이 닫히거나 주소 선택을 완료했을 때, 
검색어를 초기화시켜주는 기능을 추가하고 싶습니다.

참고 문서에서는 `onclose` 이벤트가 존재하지 않는 것 같아 문의드립니다.
`onclose` 이벤트를 제어할 수 있다면 해결이 가능하지 않을까 싶습니다.

Vue3 & TypeScript 기반 프로젝트입니다.

**Comment by daumPostcode** [comment]
@Ahngbeom 

안녕하세요~
저희는 기본 네이티브 자바스크립트(바닐라 JS)로만 서비스를 제공하고 잇으며, 
이외 React, Vue 등의 랩핑버전은 다른 일반 개발자분들께서 제공을 하는 것으로 생각해 주시면 되십니다.

그래서 이부분에 대해서는 제가 답변을 드릴 수 없고,
해당 vue-daum-postcode 개발자분의 깃헙 이슈로 등록해 보시는게 어떠실까 합니다.
