### ISSUE TITLE
특정 주소가 검색되지 않습니다..

### ISSUE THREAD

**Issue by cocoma123** [daumPostcode/QnA#109]
주소: **경기도 파주시 광탄면 마장리 406**

행정자치부에서는 검색하면 잘 나오나 

현재 다음주소API에서는 나오지 않습니다. 하루정도 더 기달려야 하는건지요??

확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@cocoma123 
안녕하세요~

해당 주소는 행자부에서 검색해 보시면, 지도 마크가 없습니다. 이러한 주소는 기본적으로 저희쪽에 내려줄때 좌표정보를 제거하고 내려줍니다.(즉 저희가 좌표값을 몰라요;;) 이에 따라 현 시스템상 지번 주소와 도로명 주소의 매핑이 불가능하여, 현재로써는 우편번호 서비스에 해당 주소를 보여드릴 수가 없습니다. 

또한 두번째 이유로 행자부 측에서 좌표정보를 가린 이유는 보통 보안주소일 가능성이 있습니다.

그래서 현재는 시스템적 문제와 정책적 문제로, 해당 주소를 표시할 수 있는 방법이 없어, 노출이 불가능한 점 양해 부탁드립니다.

해당 이슈는 지속적으로 접수하고 있으며, 추후 개선할 수 있지만, 이 일정은 아직 불확실 합니다;; 불편을 드려 죄송합니다.
