### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by leeeunhong** [daumPostcode/QnA#11]
인터넷이 차단된 환경에서 열어줘야하는 주소들이 필요합니다.

**Comment by daumPostcode** [comment]
@leeeunhong 
네~ 안녕하세요~
개인적인 사정이 있어 답변이 늦었습니다.

방화벽에서 예외처리 하실 도메인 리스트를 말씀하시는 것이죠?
저희가 IP는 왠만하면 바뀔일은 없지만, 바뀔수도 있는 여지가 있어 도메인리스트만 말씀드릴께요

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://i1.daumcdn.net 
- http://m1.daumcdn.net 
- http://apis.daum.net 
- http://stlog1.local.daum.net 
- http://sug.api.search.daum.net 

HTTPS 환경 
- https://spi.maps.daum.net 
- https://s1.daumcdn.net 
- https://i1.daumcdn.net 
- https://m1.daumcdn.net 
- https://apis.daum.net 

위와 같이 되고, 혹시 적용시 오류가 발생하면 말씀해 주시기 바랍니다.
