### ISSUE TITLE
주소검색이 되지않습니다.

### ISSUE THREAD

**Issue by parknohwan** [daumPostcode/QnA#110]
제주특별자치도 제주시 애월읍 납읍리 1602-1

지번만 있는 주소 입니다. 도로명은 없습니다. 그래서 검색이 되지 않는 상태입니다. 

어떻게 해야되나요 ?

**Comment by daumPostcode** [comment]
@parknohwan 

네~ 안녕하세요~

해당 사항은 [FAQ 1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)을 참고하시기 바랍니다.

좋은 하루 보내세요~
