### ISSUE TITLE
iframe 관련 문의드립니다.

### ISSUE THREAD

**Issue by lime3** [daumPostcode/QnA#111]
iframe을 이용해서 우편번호 찾기 버튼을 누르지 않고 바로 화면에 띄우려고 하는데

$(document).ready()에 sample 펑션을 넣으면 크롬에서 계속 뭔가 로딩 중인 상태가 됩니다.

파이어폭스나 IE에서는 이러한 증상이 나오지 않는데 유독 크롬에서만 이런 증상이 나오고 있어서

문의드립니다.

**Comment by daumPostcode** [comment]
@lime3 
네~ 안녕하세요~

실제 내부적으로 데이터처리를 하거나 무언가를 요청하거나 하는 것은 아닙니다.
다만, 저희도 해당 문제점이 정확히 어떤 현상때문에 발생하는지 또는 해결책이 무엇인지 확실하지 않아요;

일단 짐작가는 것으로는, 우편번호 서비스가 뜨면 img태그를 이용하여 서버에 로그를 보내게 됩니다.
그런데 크롬에서만 iframe으로 띄울경우, iframe로딩과 iframe내부에서 동작하는 페이지에서 img를 호출하는 것과 관련하여 크롬이 이상동작을 하는 것으로만 추측하고 있습니다.

현재 저희 가이드 페이지에서도 가끔 그렇게 동작을 하기도 합니다.
다만 저희는 페이지 로딩 후에, setTimeout으로 일정 시간 후에 iframe이 삽입되도록 하였기 때문에 해당 현상이 좀 적습니다. 

이부분은 현재로써는 해결방법이 없어, setTimeout을 이용하여 조금더 지연시키는 방법으로 해결하시는게 좋아보입니다.
정확한 해결책을 드리지 못해 죄송합니다.

**Comment by lime3** [comment]
아닙니다. 친절한 답변 감사합니다.

**Comment by charles9306** [comment]
window.onload = function(){
 이 안에다가는 실행이 되더라구요
}
