### ISSUE TITLE
이 콘텐츠는 차단되어 있습니다. 문제를 해결하려면 사이트 소유자에게 문의하세요. 라는 메시지가 나옵니다.

### ISSUE THREAD

**Issue by iatomyang** [daumPostcode/QnA#1119]
일반적인 우편번호 찾기인데- https없이 쓰다가 이번에 인증서 구매하면서 https 를 달았는데

이 콘텐츠는 차단되어 있습니다. 문제를 해결하려면 사이트 소유자에게 문의하세요. 라는 메시지가 나옵니다.

해당 문구 노출 되며 우편번호 찾기 기능이 동작하지 않습니다.

**Comment by daumPostcode** [comment]
@iatomyang 
안녕하세요~

늦게 답장을 드려 죄송합니다. 
휴가 중이여서 확인이 늦었습니다;;

알려주신 사이트에 접속하여 확인해보니, 일단 접속시에는 해당 오류가 뜨지 않는데;
로그인페이지로 리다이렉트가 되서 가입을 하려고 보니;; "동의하기" 페이지에서 넘어가지 않아서 확인이 어렵네요;

혹시 콘솔에 어떤 오류가 뜨는지 스크린샷, 그리고 위 내용이 뜨는 화면을 스크린샷 찍어서 공유해 주시기 바랍니다.

감사합니다

**Comment by iatomyang** [comment]
https://www.jjdreamlib.or.kr/tool/test.jsp
테스트 가능한 주소 전달 드립니다.
