### ISSUE TITLE
행정동이 표기되지 않는 지번에 대해서...

### ISSUE THREAD

**Issue by mydustblue** [daumPostcode/QnA#112]
안녕하세요. 새해 복 많이 받으셔요.

좋은 API 만들어주셔서 대단히 감사히 쓰고 있습니다.

그리고 얼마 전에 showMoreHName:true 업데이트 해주셔서 감사합니다.

그런데 제가 살고 있는 법정동명 마산합포구 신흥동 같은 경우는 지번까지 넣으면 거의 다 행정동 표기가 비어 있어서 문의를 올립니다.

https://github.com/daumPostcode/QnA/issues/69

위 글에서 도로명이 메인주소일 때는 연관된 지번주소의 행정동이 비어있는 경우가 있다고 하셨는데

혹시... 전체의 대략 몇 퍼센트 정도가 비어있는지 알 수 있을까요?

법정동과 행정동 둘 다 필요한 작업을 하고 있어서요.

다시 한 번 깊은 감사를 드립니다. 너무 좋은 것 같아요♡

**Comment by daumPostcode** [comment]
@mydustblue 
네~ 안녕하세요~. 설 연휴가 껴있어서 답변이 늦었습니다. 죄송합니다.

네; 현재 확인해 보니, 
"경상남도 창원시 마산합포구 고운로 97-1"로는 행정동 정보가 나오는데
"경상남도 창원시 마산합포구 신월동 42-56"으로 검색시에는 나오지가 않는군요..

해당 문제는 데이터 매핑 문제로 보이는데, 이는 담당자분께 확인을 요청 드리도록 하겠습니다.

그리고 전체의 몇%의 경우에는 산출이 시간이 좀 걸릴것 같긴합니다. 이 또한 담당자분께 말씀드리도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@mydustblue 
안녕하세요. 답변이 늦어서 죄송합니다.

현재 지번주소에 대한 행정동 매핑 비율에 대해서는, 다른 서비스에서도 쓰이기 때문에 항상 거의 100%를 맞추고 있다고 합니다. 다만, 몇몇 주소의 경우 업데이트시 누락이 될 수 있다고 하는데요. 해당 주소의 경우 이건에 해당이 되며, 현재 처리 중이시라고 하시네요. 

현재 데이터 처리에 대한 다른 이슈들이 좀 많아서 처리에 시간이 걸리는 점 양해 부탁드립니다;

감사합니다.

**Comment by mydustblue** [comment]
친절한 대응 대단히 감사합니다! 사랑해요! :)
