### ISSUE TITLE
플레스홀더 내용 바꾸려면...

### ISSUE THREAD

**Issue by Adonis640320** [daumPostcode/QnA#113]
현재 팝업창에  **예) 판교역로 235, 분당 주공, 삼평동 681** 이 플레스홀더에 디폴트로 되어있는데 이걸 바꾸고 싶어요.
어떻게 해야 바꿀수 있는지?

**Comment by daumPostcode** [comment]
@Adonis640320 
네 안녕하세요~ 설연휴가 껴있어서 답변이 늦었습니다. 죄송합니다.

네 현재 placeholder를 변경할 수 있는 옵션은 제공하고 있지 않습니다.
위 placeholder는 사용자가 제일 먼저 바라보는 곳이기도하고, 저희 시스템에서 placeholder처럼 검색시 검색결과가 제일 정확하게 떨어지기 때문에 해 놓은 것이라, 아직까지 변경 옵션을 추가할 계획은 없습니다.
