### ISSUE TITLE
bcode 문의

### ISSUE THREAD

**Issue by jun02** [daumPostcode/QnA#1137]
안녕하세요 
궁금한게 문의 드립니다.

이전에 bcode를 테이블화 해놓은게 있는거 같은데 
코드를 테이블화된 코드와 내려주는 코드가 틀린게 몇 보여 문의 드립니다.

https://business.juso.go.kr/addrlink/CommonPageLink.do?link=/sportPolicy/standard/intrlStd/info_etc8
여기까진 어찌 찾앗는데 

저희한테 누락되거나 변경된 bcode를 바르고 싶은데 
혹시 bcode로 검색 할수 잇는 API나 
bcode가 정리된 자료가 있을까요 ??

위 행안부 주소검색 사이트에 뒤적이다가 
혹시나 하고 문의 남깁니다.

항상 잘쓰고 있습니다 감사합니다 ( _ _)

**Comment by daumPostcode** [comment]
@jun02 
안녕하세요~

아뇨; 현재 우편번호서비스API에서는 해당 bcode의 정보만 내릴 수 있는 기능은 없습니다.
의심되는 주소에 대한 값을 확인하고 싶을때는
https://developers.kakao.com/docs/latest/ko/local/dev-guide

여기에 있는 API를 이용해 볼 수는 있으나, 말씀하신 bcode테이블만 내릴 수 있는 API나 자료는 별도로 정리된게 없습니다.

행안부측에서 별도로 데이터를 모두 받을 수 있는 것으로 아는데, 한번 행안부API를 찾아보시는건 어떠실까 합니다.

**Comment by jun02** [comment]
네 감사합니다 ~!
