### ISSUE TITLE
더샾아파트 주소명

### ISSUE THREAD

**Issue by ttochi3** [daumPostcode/QnA#114]
02825 구 우편번호 (136-892) 아래에서 주소 선택 도로명
서울 성북구 아리랑로5길 85 (돈암동더아파트) 
주소에 위와 같은 아파트명이 the # 아파트일 경우 알 수 없는 특수문자로 반환됩니다.
위의 사항을 수정해 주세요.

**Comment by daumPostcode** [comment]
@ttochi3 
네~ 안녕하세요. 연휴가 껴있어서 답변이 늦었습니다. 죄송합니다.

넵. 간혹 주소정보에 특수문자가 있을때 발생하는 문제인데, 버그 제보 감사드립니다. 해당 문제는 조속히 해결하도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@ttochi3 
안녕하세요. 답변이 늦어서 죄송합니다.

이전에 '샾'과 같은 몇몇 글자에 따라 텍스트가 깨지던 현상이 있어서 전체 패치를 하였지만, 아마 해당건이 누락됬었거나, 신규 업데이트로 인해서 빠진것 같습니다.

현재 정상 처리 완료 되었습니다.

감사합니다.
