### ISSUE TITLE
해당 시간대에 일부 접속이 원할하지 않았는데 원인이 궁금합니다.

### ISSUE THREAD

**Issue by sinbom-howser** [daumPostcode/QnA#1143]
안녕하세요!
09월 07일 06:25 ~ 07:25 즈음 시간대에 일부 요청에서 지연(1m 이상)이 발생한 것으로 확인되었는데 혹시 해당 시간대에 배포나 작업이 있었던건지 궁금합니다.

**Comment by daumPostcode** [comment]
@sinbom-howser 
안녕하세요~

현재 해당 시간대에 발생한 오류는 딱히 확인이 안되는 상태입니다.
당시에 서비스 배포는 없었으며, 전사플랫폼에서 오류가 발생하거나 한 상태는 아니였습니다.
예전에 전사플랫폼 오류나, 서비스 오류가 아닌 경우엔 통신사와 연관된 오류일때도 있었는데요.
이 부분은 현재 정확히 알 수가 없습니다.
일정 시간 이상 이슈 발생시 저희 시스템에 보고가 되는데; 현재로써는 그러한 오류는 확인되지 않았습니다.
참고 부탁드립니다.
