### ISSUE TITLE
iframe 내 min-width 비활성화 문의

### ISSUE THREAD

**Issue by mchewry** [daumPostcode/QnA#1145]
모바일 레이아웃 작업 시, min-width가 300px 로 고정되어있어, 뷰포트가 300px 이하인 디바이스에서 레이아웃이 틀어지게 되는데, min width를 비활성화 할 수 있는 방법이 있나요?

**Comment by daumPostcode** [comment]
@mchewry 
안녕하세요~

네; 현재 내부 컨텐츠의 최소 width의 겨웅 300으로 고정되어 있는 상태입니다.
지금까지 몇년간 요청사항이 없어서 현재까지 300으로 고정된 값이 적용되어 있는 상태로,
이용자분께서 변경할 수 있는 옵션은 현재 없습니다.

해당 옵션의 경우 테스트 후에 배포를 나갈 수는 있는데; 이번주에 바로배포를 나가는 것은 어렵습니다. (현재 다른 업무가 밀려있어서요;;)
빠르면 10월초 이후에 가능할 것으로 보입니다.
테스트가 완료되면 말씀드리겠습니다.

**Comment by daumPostcode** [comment]
@mchewry 
안녕하세요~

해당 이슈의 경우는, 수정되는 코드량이 적고, 연관된 모듈에 영향을 주는 부분이 적어서
좀 빨리 적용되었습니다.

현재 가이드 문서는 업데이트가 안된 상태로, 이는 추후에 반영이 될거에요.

먼저 이용하시려면
Postcode객체의 생성자 옵션에

{
   oncomplete: function(data){....}
   minWidth: 200 
}

minWidth 라는 속성으로 변경 가능합니다.
기본값은 300이며, 0 ~ 300사이의 값으로 설정 가능합니다.
단위는 자동으로 'px'로 맞춰지며, 숫자값만 입력하시면 되십니다.

참고해 주시기 바랍니다.

**Comment by daumPostcode** [comment]
@mchewry 
안녕하세요~
iframe으로 끼워넣기 방식에서 동작이 안되는 것일까요?

**Comment by mchewry** [comment]
> @mchewry 안녕하세요~ iframe으로 끼워넣기 방식에서 동작이 안되는 것일까요?

정상동작 확인했습니다 감사합니다.
