### ISSUE TITLE
주소가 검색되지 않습니다. 

### ISSUE THREAD

**Issue by 3pi010** [daumPostcode/QnA#115]
행정자치부에서는 검색하면 잘 나오나
현재 다음주소 API에서는 나오지 않습니다. 

아래 주소 확인 부탁 드립니다. 

주소 :  경기 구리시 갈매동 147-8

**Comment by daumPostcode** [comment]
@3pi010 
네~ 안녕하세요.

아직 데이터 담당자분께 연락을 받지 못하여 정확한 이유를 설명드리진 못하지만,
![2017-02-01 1 27 00](https://cloud.githubusercontent.com/assets/20675065/22495265/29d35d02-e882-11e6-919f-0bbe7b48113c.png)

행자부 사이트에서 검색해 보시면, 해당 도로명 주소에 "미고시"라고 되어 있습니다.
미고시 부분에 마우스를 올려보시면 "도로명 주소는 고시가 된 후 효력이 발생하며, 고시되기 까지 5일 이상 소요가 될 수 있다"라고 되어 있는 것으로 보아, 주소가 등록은 되었지만 아직 고시가 안된상태로, 행자부가 저희쪽에 데이터를 내려줄때 제외하고 내려주는 것 같아요.

추후 담당자분께서 말씀해 주시면 추가 댓글 달도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@3pi010 
안녕하세요.  답변이 늦어서 죄송합니다.

신규주소의 경우 미고시 형태로 행자부사이트와 저희 서비스와의 싱크가 안맞을 수 있다고 합니다.
미고시 주소의 경우 2가지가 있는데,
하나는 보안지역 : 이 경우에는 저희에게 데이터를 제공하지 않습니다. (일반적으로 행자부 사이트에서 검색시 지도 마크가 업습니다.)
하나는 신규주소 : 이 경우에는 일정 시간이 지난 후 저희쪽에 데이터가 전달됩니다.

즉 해당건의 대해서는 신규주소라 반영이 느린 것이었고, 현재는 반영되어 있는 점 참고 부탁드립니다.

감사합니다.
