### ISSUE TITLE
iframe 내부 값 가져오기

### ISSUE THREAD

**Issue by eunjisim** [daumPostcode/QnA#1156]
![image](https://github.com/user-attachments/assets/09c91e74-8040-4118-b32e-ef2dc125dd79)

안녕하세요
iframe을 이용해서 페이지에 끼워 넣는 방식을 사용하려고 합니다
주소를 검색했을 때, 위 사진처럼 결과가 나오면 data-addr_type 값을 확인해서 data-addr 값을 가져오고 싶은데요
아래처럼 코드를 작성했는데 작동하지 않아 문의 드립니다
해당 값을 가져올 방법이 있을까요?

`$('#__daum__viewerFrame_1').contents().find('.txt_address[data-addr_type="R"]').data('addr')`

**Comment by daumPostcode** [comment]
@eunjisim 
안녕하세요~

그렇게 사용하는것은 권장하는 방법이 아닙니다. 해당 방식은 페이지 크롤링과 같은 방법인데;
저희는 검색뷰와, 검색어를 선택했을때 별도의 콜백함수로 데이터를 내리고 있습니다.

크롤링에 대한 부분은 저희가 말씀드릴 수 있는 사항이 없는점 참고 바랍니다.

만약 REST API와 같이 데이터만 필요하다면, developers.kakao.com에서 제공하는 로컬API를 이용해 주시기 바랍니다.
