### ISSUE TITLE
일부 사용자 접속 안되는 문제.

### ISSUE THREAD

**Issue by acacia07** [daumPostcode/QnA#117]
잘 사용하고 있는데 몇몇 사용자가 접속이 되지 않아 문의 드립니다.
대부분 잘 되서 신경을 안쓰고 있다가
한 사용자를 보니 postcode.map.daum.net 자체에 접속이 안되더라구요...

postcode.map.daum.net/search가 안되는 것은 물론이고
postcode.map.daum.net/guide조차 접속이 안되니...

어떤 문제인지 알 수 있을까요??
daum.net은 접속이 잘 됩니다.
답변 부탁드립니다... ㅠ_ㅠ

**Comment by daumPostcode** [comment]
@acacia07 
네~ 안녕하세요.

우선 말씀드릴 수 있는 것은, 저희가 임의로 사용자를 막거나 하진 않습니다.

해당 도메인이 아예 접근이 안된다면,
직장에서 사용하신다면 네트워크 인프라팀에서 뭔가 조치가 있었던지, 
개인 사용자라면, 공유기 설정 문제 또는, PC에 설치된 다른 프로그램이 접근을 막고 있을 수 있습니다.

예전에도 한동안 접속 안되신다고 하시다가 공유기 재부팅으로 해결이 되신 분도 계셨으며, PC의 불필요한 보안프로그램, 또는 브라우저의 익스텐션 같은 것을 초기화 한 후에 접속이 되신 분도 계셨습니다.

워낙에 변수가 많아 직접적인 해결 방법은 현재로써는 딱히 없네요;;;
특정브라우저에서만 안되고 다른 브라우저에서 된다면, 특정브라우저의 설정 문제같고, 모든 브라우저에서 안되면 인터넷 CP또는 공유기쪽 문제일 수 있으니, 확인 부탁드립니다.
