### ISSUE TITLE
https 로 접속할수는 없나요?

### ISSUE THREAD

**Issue by bluerain0909** [daumPostcode/QnA#118]
안녕하세요

스크립트를 https로 로딩을 하려고 하니 블록이 되네요.

'http://dmaps.daum.net/map_js_init/postcode.v2.js'. This request has been blocked; the content must be served over HTTPS.

크롬에서 보여지는 메세지 입니다.

https는 지원되지 않는 건가요?

-- 자답입니다.

찾았네요. 제가 검색을 덜 해봤습니다..ㅎㅎ

https://spi.maps.daum.net/postcode/guidessl

혹시 저 같은 분을 위해 남깁니다

**Comment by daumPostcode** [comment]
@bluerain0909 

넵~ 안녕하세요~

네; 해당 가이드 페이지의 기본사용법을 보시면 https용 도메인이 있으니 그걸 이용하시면 됩니다~

감사합니다~
