### ISSUE TITLE
iframe으로 열었을때 빈화면만 뜨네요.

### ISSUE THREAD

**Issue by skynow01** [daumPostcode/QnA#119]
실서버는 https, 테스트 서버는 http 입니다.
embed 방식으로 적용하였구요.
한달~두달 전쯤에 작업해서 실서버에 적용했을 때 잘 되는 것을 확인하였었는데

오늘 확인했을때 border만 있고 안에 내용은 흰 색으로 빈화면만 뜨더라구요.
크롬 개발자 모드로 iframe 내용을 봤을 때 src 부분이 about blank로만 되어있었습니다.
개발자 모드의 network에서는 preview로 해당 소스들이 받아와진것 같이 보이긴 하는데 실제 화면에는 about:balnk로만 뜨네요.

https환경일 때 아파치 서버 설정에 따로 해줘야하는 건지, 아니면 한달 사이에 뭔가 바뀐건지 궁금합니다.
테스트 서버는 지금도 잘 되네요.

아래 소스는  new daum.Postcode 소스 부분 입니다.

function sample2_execDaumPostcode() {
    new daum.Postcode({
        oncomplete: function(data) {
            // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

            // 각 주소의 노출 규칙에 따라 주소를 조합한다.
            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
            var fullAddr = data.address; // 최종 주소 변수
            var extraAddr = ''; // 조합형 주소 변수
            // 기본 주소가 도로명 타입일때 조합한다.
            if(data.addressType === 'R'){
                //법정동명이 있을 경우 추가한다.
                if(data.bname !== ''){
                    extraAddr += data.bname;
                }
                // 건물명이 있을 경우 추가한다.
                if(data.buildingName !== ''){
                    extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                }
                // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
            }

            // 우편번호와 주소 정보를 해당 필드에 넣는다.
            document.getElementById('companyZipCode').value = data.zonecode; //5자리 새우편번호 사용
            document.getElementById('companyAddress1').value = fullAddr;
         // 커서를 상세주소 필드로 이동한다.
            document.getElementById('companyAddress2').focus();
            // iframe을 넣은 element를 안보이게 한다.
            // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)
            element_layer.style.display = 'none';
            closeDaumPostcode();
        },
        width : '100%',
        height : '100%'
    }).embed(element_layer);

    // iframe을 넣은 element를 보이게 한다.
    element_layer.style.display = 'block';

    // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.
    initLayerPosition();
}

**Comment by daumPostcode** [comment]
@skynow01 
네~ 안녕하세요~

네; 우선 한달 사이에 변경된 점은 몇몇 기능이 추가된 부분은 있습니다.
다만 이는 데이터에 관련된 내용이며 open, embed시 화면을 그리는 부분은 변경되지 않았습니다.

일단 올려주신 코드는 저희 샘플과 매우 흡사한데, 그냥 보기에는 따로 문제는 없어보입니다.
그리고 말씀하신 iframe에 about:blank로 뜨는 것은 맞는 동작입니다. (2중 iframe입니다. 실제 도메인은 안쪽 iframe에 들어갑니다)

음.. 
우선 [FAQ 13번](https://github.com/daumPostcode/QnA#13-팝업창이-비어-있는-채로-뜹니다)을 체크 부탁드려요, 페이지가 조합이 되어 렌더링이 되던, 한페이지로 렌더링이 되던, 최종 브라우저에서 보여지는 화면에 document.domain값이 셋팅되어 있으면 동작하지 않습니다. 현재 이 문제는 기술적으로 해결이 불가능한 부분이므로 체크해 주시기 바랍니다.

그리고 저희가 추가적으로 확인을 하려면, 오류가 발생하는 OS platform, 그리고 사용하시는 브라우저 와 버전이 필요합니다.
혹시 모바일브라우저면 이또한 적어 주세요. 그리고 혹시 저희 가이드페이지(http://postcode.map.daum.net/guide)
에서 iframe이용한 샘플도 안되는지 확인 부탁드립니다. 그리고 저희가 직접 접근할 수 있는 URL이 있다면 알려주시면 오류 확인에 더 도움이 될것 같아요.

감사합니다.
