### ISSUE TITLE
문의 드립니다.

### ISSUE THREAD

**Issue by Datawords-Daniel** [daumPostcode/QnA#12]
해외 개발자를 통해 주소 검색 기능을 개발하려 합니다.
혹시 우편번호 서비스에 대한 하기 페이지 설명이 영문으로 작성된 자료가 있을 지 문의 드립니다.
http://postcode.map.daum.net/guide

**Comment by daumPostcode** [comment]
@Datawords-Daniel 
네~ 안녕하세요~

네 현재 우편번호서비스는 영문으로 된 가이드 문서가 없습니다.

해외개발자를 통해서 국내향 서비스를 개발하신다면, 저희 가이드 문서를 가지고, Datawords-Daniel님께서 중간에 커뮤니케이션 하셔야 될 것 같습니다.
