### ISSUE TITLE
https + iOS 환경에서 포커스 오류

### ISSUE THREAD

**Issue by highca** [daumPostcode/QnA#120]
안녕하세요.

https://onuku.imweb.me/ 에서 회원가입 (우측 상단 사람 아이콘 클릭)을 누르고
회원정보 입력 중 주소검색을 iOS 환경에서 진행하게 되면 커서가 엉뚱한 곳에 표시되는 등 이벤트를 제대로 잡지 못하는듯 합니다.

그러나 동일한 사이트인 http://onuku.co.kr/ 에서 동일한 동작을 했을 때 문제 없이 잘 됩니다.

https 접속 + iOS 환경에서 뭔가 문제가 있는 듯 한데 조치 부탁드립니다.

**Comment by daumPostcode** [comment]
@highca 
안녕하세요~

PC 크롬 및 iOS단말에서 확인을 해보았는데요. 정상적으로 동작하는 것처럼 보이는데 어떤 문제일까요?
한가지 집자면, 이미 주소가 입력이 된 상태에서 입력된 주소의 중간 부분에 커서가 되어 있는 상태에서 저희 팝업이 열리면, 이때 커서가 앞이 아닌 중간에 위치하고 있긴 한데, 이 문제일까요?

일단 저희 우편번호 서비스 단독으로 테스트를 진행할때는 문제가 발생 되진 않네요. 그리고 워낙에 클라이언트마다 사용하시는 방법이 달라서 모든 부분을 테스트를 할 수는 없습니다.

제 생각엔 제가 파악한 문제가 맞다면, 이미 주소가 입력된 상태에서 다시 한번 선택시에 입력된 주소를 삭제(또는 백업)하신 후 저희 서비스를 열어주시면 해결이 될 것 같은데 어떠실까요? 그리고 저희서비스를 그냥 닫으면 백업한 주소를 복구하고 주소검색 후 선택을 하면 선택한 것으로 바꿔주고 하시면 될 것 같아요.
현재 같은 input창이 위치가 겹쳐서 발생한 버그라고 보여지고, 이는 예전부터 ios단말에서 input 커서는 여러가지 케이스로 버그가 많아서 해결이 쉽지 않아 보이긴 합니다.

만약 다른 문제라면 좀 더 구체적으로 말씀해 주시면 감사하겠습니다. 스샷도 올려주시면 더더욱 좋습니다.

**Comment by highca** [comment]
답변에 감사드립니다.

테스트 환경: iOS + Safari 환경 (최신 버전)
문제 상황 설명
1. https://onuku.imweb.me/ 에서 우측 상단 사람 아이콘 클릭
2. 회원가입 누름
3. 약관 동의 후 가입하기 버튼 누름
4. 주소 입력 부분에서 주소를 검색하면 첨부한 스크린샷처럼 표시됩니다.

아래는 문제 발생 스크린샷입니다.

https://www.dropbox.com/s/t0txg3h8y37lu31/post_search.png?dl=0
https://www.dropbox.com/s/ib4n97o34vpa4kf/post_search2.png?dl=0

**Comment by daumPostcode** [comment]
@highca 
네! 안녕하세요~

스크린샷과, 알려주신 방법대로 테스트해 보았습니다. 말씀하신 오류가 잘 재현이 되는데요.
우선 현재 커서 버그의 경우에는 모든 상황에서 발생하는게 아니라서 highca님의 홈페이지 구조를 따라서 구축한 뒤에 테스트를 진행해봐야 될 것 같습니다. 

다만 layer모드의 특성상 부모페이지의 style과 DOM구조에 따라 매우 많은 영향을 받는 다는 점을 미리 말씀드리며,
iOS단말에서 position:fixed DIV에 inner scroll이용시 키보드가 올라오면서 어느정도 버그가 있다는 것도 알고 계실거라 생각됩니다. API제공자 입장에서 사용자 DOM구조에 영향을 받지 않고 잘 동작하도록 만들어야 되나, 웹의 특성상 변수가 너무나 다양해서 100% 대응을 못드린 점 죄송합니다.

해당 오류는 fixed로 고정된 DIV에서 inner scroll, 그리고 그안에 iframe으로 inner scroll이 되면서 위치가 정확히 잡히지 않는 문제같아 보입니다. 이부분은 솔직히 말씀드리면 저희 서비스라면 어떤 꼼수를 쓰던간에 해결을 할 수 있겠지만, 외부 사이트에 임베딩되는 방식이라, 해결이 가능할지(현재와 똑같은 상태에서 버그만 수정) 아니면 해결이 불가능 할지 알 수가 없는 상황입니다. ㅜ.ㅜ

일단 해당 오류를 회피하는 방법으로는, 현재 저희 서비스가 띄워지는 부분이 300x337정도 되는 사이즈의 box안에 들어가게 되는데, 우편번호 서비스의 새로 사이즈가 기본적으로 337보다 크기 때문에 내부에서 스크롤이 발생이 됩니다. 일단 스크롤이 발생이 안되면 어느정도 문제가 해결될것 으로 보이는데요.
저희 API의 생성자에 onresize라는 콜백함수를 정의 하실 수 있습니다. 이 콜백함수가 실행시 매개변수로 size라는 객체를 넘겨주는데, 이 size.height정보를 이용하여 add_container의 height를 늘려주신다면 스크롤이 사라져서 현재 발생하는 문제는 없어질 것도 같아요.
예제는 저희 가이드 페이지 (http://postcode.map.daum.net/guide)의 iframe으로 페이지에 끼워넣기를 참고 바라며, 콜백함수 설명은 가이드 페이지(http://postcode.map.daum.net/guide#attributes)속성 부분에 설명이 되어 있으니 참고 부탁드립니다.

이외에 말씀하신 버그는 환경 구축후에 추가적으로 더 확인해 보도록 하겠습니다.
감사합니다.
