### ISSUE TITLE
특정 주소들이 검색되지 않습니다.

### ISSUE THREAD

**Issue by aulmana** [daumPostcode/QnA#122]
행정자치부에서는 검색하면 잘 나오고, 지도 마크도 있으나

현재 다음주소API에서는 나오지 않습니다. (우편번호등록불가)

확인 부탁드립니다.

주소

1. 경기도 성남시 수정구 위례광장로 311 위례35단지아파트 3514동 306호 

2. 인천 서구 연희동 796-7 

3. 서울 대학로 328 

4. 경남 통영시 도산면 오산길 90

**Comment by daumPostcode** [comment]
@aulmana 
안녕하세요~

넵~ 
말씀해주신 주소들을 확인해본 결과, 현재 DB상, 그리고 서비스 노출상 3번의 주소를 제외하고 정상 노출되고 있는 것으로 확인이 됩니다.

그리고 말씀해주신 주소중 3번 주소는 행자부사이트에서도 등록되지 않은 주소라서 검색이 되지 않네요.
만약 '서울대학로 328' 주소라면 -> 경기도 시흥시 서울대학로 328 로 등록이 되어 있습니다. 

혹시 저희가 감지하지 못한 오류가 있을 수도 있으니, 검색이 되지 않았던 시점을 말씀해 주시면 추후 업데이트나 데이터 확인시에 추가 확인해 보도록 하겠습니다.

추가적으로 3번을 제외한 나머지 3개의 주소는 최근업데이트는 아니고 기존에 이미 들어가 있던 주소들이며, 
만약 주소가 신규 업데이트 주소일 경우에는 행자부에서 검색되는 시점에 1일, 타이밍에 따라 늦어도 2일 정도 후에 저희 시스템에 등록 지연이 발생할 수 있으니 참고 부탁드립니다.

감사합니다.

**Comment by aulmana** [comment]
답변 감사드립니다!

재 질문드립니다.

1.경기도 성남시 수정구 위례광장로 311 위례35단지아파트 3514동 306호

2.인천 서구 연희동 796-7

3.서울 대학로 328

4.경남 통영시 도산면 오산길 90

위의 주소들 검색은 잘되는데, 우편번호 클릭시 우편번호 창에 반영이 되지 않습니다.

혹시 저희 쪽 개발상 문제인지, 다음 api쪽 문제인지 또 다음 api 문제라면 해결이 가능한지

문의드립니다!

**Comment by daumPostcode** [comment]
@aulmana 
네~ 안녕하세요~

저희 가이드페이지에서 확인결과 현재 정상 동작을 하고 있습니다.
![2017-02-23 2 37 56](https://cloud.githubusercontent.com/assets/20675065/23246280/bfb66fa8-f9d5-11e6-9e56-a16193fbdfa5.png)
![2017-02-23 2 38 04](https://cloud.githubusercontent.com/assets/20675065/23246282/c27019b0-f9d5-11e6-8aa0-3d88e40640f4.png)

일단 말씀해 주신 내용으로 이해하기에는 고객님 서비스 페이지의 input창이나 다른 곳에 반영이 안된다는 것 같은데요.
이는 oncomplete쪽 함수의 구현부를 한번 확인해 보시기 바랍니다. 이 함수의 구현은 고객님께서 하시는 부분이기 때문에 직접 어떤 오류가 있는지 확인하시면 될것 같습니다. 데이터 스키마는 http://postcode.map.daum.net/guide#attributes <- 여기에 들어가시면 확인 가능하시고, 가이드 페이지를 보시면 각 데이터 변수에 어떻게 값이 들어가고, 어떤 의미인지도 서술되어 있기 때문에 읽어보시는 것을 추천드립니다.

만약 이 오류가 아니라면, 저희가 확인 할 수 있는 페이지와 소스코드, 테스트 환경(OS, 브라우저 등)을 알려주시면 추가 확인해 보도록 하겠습니다.

**Comment by aulmana** [comment]
다시 한번 확인결과

저희 쪽에서는 우편번호가 6자리 구 우편번호 사용중입니다. 

1.경기도 성남시 수정구 위례광장로 311 위례35단지아파트 3514동 306호

2.인천 서구 연희동 796-7

3.서울 대학로 328

4.경남 통영시 도산면 오산길 90

확인 결과 DAUM측에서 해당 주소에 한해 구 우편주소를 제공하지 못하는 문제인것 같습니다.

구 우편주소가 제공 된다면 해결 될 것 같습니다!

다시 한번 확인 요청드립니다~!

**Comment by daumPostcode** [comment]
@aulmana 
네~ 안녕하세요~

우선 말씀해주신 구우편번호 지원은 어렵습니다.
해당 내용은 : https://github.com/daumPostcode/QnA#3-6자리-구우편번호가-필요합니다 <- FAQ에도 적혀 있으며, 구우편번호가 없어지는 것은 저희 결정이 아닌 구우편번호 생산 주체인 우정국에서 공식 공지를 통해 2015년 8월 1일 부터 더이상 생산 업데이트가 되지 않습니다.
실제 행자부에서 받는 데이터에는 구우편번호가 존재하지 않으며, 그렇기 때문에 신규 또는 갱신되는 주소에는 구우편번호는 없습니다. 또한 아직 현재 저희 서비스에서 몇몇 주소에 구우편번호가 있는 것은 2015년 8월 1일 이후에 업데이트가 되지 않은 주소(구우편번호와 새우편번호가 병행되던 시절)입니다. 

또한 저희가 가진 내부데이터를 통해 매핑작업을 진행 할 수도 있습니다만, 현재 대한민국 주소체계 자체가 5자리로 생산 관리되고 있는 현시점에 임의 매핑은 오히려 혼란만 불러올 수 있고, 관리되지 않는 데이터를 임의로 다시 살리는 것은 데이터 정확도에도 악영향을 미치는 점 때문에, 현재는 고려하고 있지 않습니다.

그래서 현시점에서 최선의 방법은 5자리 새우편번호로 바꾸시는 방법말고는 없어보입니다.

감사합니다.
