### ISSUE TITLE
nodejs에서 우편번호로 조회한 결과데이터만 받아올수 있게 가능한가요?

### ISSUE THREAD

**Issue by smoonh22** [daumPostcode/QnA#123]
html형태가 아닌 우편번호로 검색된 주소 데이터를 사용하고 싶어서 서버사이드(nodejs)에서 해당 서비스를 사용하고싶은데 가능할까요?

**Comment by daumPostcode** [comment]
@moonhyucksong 
안녕하세요~

네 현재 우편번호 서비스는 클라이언트에서 팝업형태의 API를 제공하지 서버사이드용 REST API는 제공하지 않습니다. 

도움을 드리지 못해 죄송합니다.
