### ISSUE TITLE
주소는 나오는데 우편번호 등록이 되지 않습니다

### ISSUE THREAD

**Issue by dlgmlwn334** [daumPostcode/QnA#124]
경기도 용인시 처인구 낙은로 59 주소에 해당되는 우편번호가 매치가 안되서 주소 등록이 안된다고 뜨네요 
빠른 등록 부탁드립니다!!!!

**Comment by daumPostcode** [comment]
@dlgmlwn334 

네 안녕하세요~

현재 말씀하신 주소가 저희 서비스에서 검색이 되고 있는데, 우편번호 매치가 안된다는게 어떤 말씀이실까요?
![2017-03-08 10 19 40](https://cloud.githubusercontent.com/assets/20675065/23685704/e592dd8e-03e8-11e7-9f7c-d9ea9da465c0.png)

주소가 검색이 되고 선택이 되는데, 고객님 사이트에서 등록이 안되는 것이면, oncomplete콜백 함수의 수정을 해주세요. 이 콜백함수는 저희는 API 인터페이스만 제공할 뿐, 실제 구현은 고객님의 몫입니다.

또는 좀 더 자세한 설명을 해주시면 감사하겠습니다. (만약 새우편번호-5자리, 구우편번호-6자리 문제라면 구우편번호는 정부에서 6자리 구우편번호를 다시 살리지 않는한, 추가될 계획이 없는 점 말씀드립니다)

**Comment by dlgmlwn334** [comment]
우편번호 검색 후 클릭시 우편번호 창에 반영이 되지 않습니다!!

**Comment by daumPostcode** [comment]
@dlgmlwn334 
네~

제가 위에 말씀드린 것처럼 검색된 주소를 클릭하는 순간, oncomplete함수가 실행되고, 저희가 내릴 수 있는 모든 데이터는 oncomplete함수의 매개변수인 data변수를 통해 모두 내립니다. 여기서 oncomplete함수를 재정의 하여 필요한 데이터를 고객님의 사이트에 넣는 것은, 저희가 담당하는 것이 아닌, 고객님의 몫이에요. 즉, 변수가 홈페이지의 우편번호창에 반영이 안된다는 것은, 이 oncomplete함수에서 잘못 처리가 되고 있는 것으로, 이부분을 확인해주세요.

oncomplete함수는 각각 사이트에 맞게 재구현이 되기 때문에, 저희는 안쪽이 어떻게 되어 있는지 알 수가 없습니다.
실제 API로직에도 oncomplete은 인터페이스만 있지, 내부 구현체는 없습니다. 바로 저희가 구현하는게 아니기 때문이죠.
만약 저희가 제공하는 샘플코드를 이용하신 경우에도 저희 샘플은 저희 가이드페이지에 맞게 적용이 되어 있는 거라서, 저희 가이드페이지에서만 유효한 코드인 점 말씀드립니다. oncomplete에서 주소 데이터를 가공하는 것은 공용으로 이용하실 수도 있지만, 실제 홈페이지에 주소 데이터를 넣는 부분은 모든 홈페이지가 다르므로, 이부분을 확인해 보시기 바랍니다.

제가 이렇게 밖에 답변 드릴 수가 없는 점은, 우편번호 창에 반영이 되지 않는다는 내용밖에 모르기 때문에, 이 오류에 해당하는 가이드를 제공할 수밖에 없는 것이구요. 다른 이유일 때는 소스코드와, 제가 접근할 수 있는 URL을 제공해 주시기 바랍니다. 또한 OS, 브라우저 명과 버전 (브라우저에 따라 특정 코드들이 동작을 안할 수도 있기 때문)도 알려주시기 바랍니다.

감사합니다.
