### ISSUE TITLE
Angular2 에서 활용하는 방법이 궁금함.

### ISSUE THREAD

**Issue by skyjich** [daumPostcode/QnA#125]
안녕하세요. 
제가 아직 초보라.. angular2로 웹앱을 만들고 있는데..
이래저래 다음주소 검색을 사용할려는데.. 잘 안되네요...
혹시 참고할 만한 샘플 등이 있을런지요.. 
부탁드립니다.

**Comment by daumPostcode** [comment]
@skyjich 
네~ 안녕하세요!

넵;; 아쉽지만; 다른 참고할만한 샘플은 없습니다.
동작을 하지 않는 원인을 설명해 주시면, 해결책에 대해서 100%는 아니더라도 어느정도는 답변이 가능할 것 같습니다.
저또한 앵귤러2를 해본적이 없는 사람으로써 앵귤러2의 동작방식은 모르며, 단지 우편번호 서비스에서 오류가 발생을 했을시, 왜 오류가 발생하는지 정도는 답변이 가능할 것 같아요;;

좀 더 구체적으로 질문해 주시면 감사하겠습니다.

**Comment by brendaniel** [comment]
@skyjich @daumPostcode 
https://github.com/brendaniel/ng2-daum-address

**Comment by skyjich** [comment]
@brendaniel 
와우.. 뜻밖의 행운이.. google place api 보고 한참 해메고 있었는데.. ㅋㅋ.  감사합니다. 
예제까지..친절하게.. 복받으실거에요..

**Comment by daumPostcode** [comment]
@brendaniel 
어이쿠!! 저도 이런 뜻밖의 행운이!!
도움 주셔서 감사드립니다 ^^

@skyjich 
참고하시면 되실 듯해요.~ 다만 모바일 환경의 웹앱이라면, 팝업보다는 레이어 모드로 띄우셔야 웹뷰 및 기타 브라우저에서 정상동작을 보장합니다. 팝업형은, window.open의 모든 기능적인 구현을 하지 않은 웹뷰에서(거의 대부분, facebook도 그래요..) 팝업창이 뜨지 않기 때문에, 레이어 모드 또는 [끼워넣기-예제탭의 아랫부분](http://postcode.map.daum.net/guide#sample)을 참고하시기 바랍니다.

감사합니다.

**Comment by brendaniel** [comment]
@daumPostcode iframe 형태의 옵션을 만들고 있는데, 시간이 좀 걸릴것 같네요.
inline iframe이랑 popup iframe 두개다 필요하겠죠?

**Comment by daumPostcode** [comment]
@brendaniel 
아 ㅎㅎ inline과 popup iframe이라 하시길래 햇갈렸네요 ㅎㅎ
제가 이해한게 inline은 끼워넣기 예제구, popup iframe은 DOM layer형태를 말씀하신게 맞죠?

제가 Anguler2를 잘 몰라서 답변을 드릴 순 없지만;;; 일단, 끼워넣기 방식이나 DOM Layer방식이나, 우편번호 서비스 입장에서는 embed()함수를 이용하는 것으로 같습니다.
다른점은 embed함수의 인자로 들어가는 element변수에 DIV(다른 태그도 상관없습니다.)태그로 position:absolute나 fixed처리가 된 노드가 들어갈건지, 아니면 일반 노드가 들어가는것에 따라 다른 것입니다. 
이는 우편번호 JS API차원에서 제공하는 기능이 아니라, 개발자 분들께서 작성하시는 부분의 코드라서; 저희는 이렇게도 사용가능하다 라는 샘플을 제공하는 것일 뿐이라서요 ㅎㅎ

아마 Anguler2 모듈로 더 사용하기 쉽게 만드실려면, 옵션에 따라 저 두개를 각각 띄울 수 있는 기능을 만드셔도 괜찮을 것 같아요  ㅎㅎ

추가적으로 layer모드의 자주 발생하는 오류에 대해서 설명을 드리면,
우편번호 검색창을 position:fixed로 된 DIV태그에 넣으면 키보드가 올라올시 제 위치를 못잡는 현상이 존재하고 있고,
-webkit-overflow-scrolling  스타일 변수의 셋팅을 안해주면 inner scroll이 안되는 현상도 있습니다. 주로 아이폰에서 발생을 하며, 그래서 저희가 가이드 드릴때 왠만하면 페이지에 끼워넣는 방식으로 처리하는 것을 추천드리고 있습니다.

현재 iframe을 중첩으로 사용하고 있어서(CORS문제와, 저버전의 브라우저 대응때문에;;) 모바일에서 대응시 손이 좀 더 가게 되는데요. 이를 바꾸고 싶은데 요새 시간이 나지 않아서 바꾸기가 힘드네요;; 죄송하게 생각합니다.
다만, 개발자 분들께서 조금 예외처리 해주시면 처리가 되니; 참고부탁드립니다.
