### ISSUE TITLE
시/도, 구군, 법정동 만 검색은 따로 제공되는게 없는지요?

### ISSUE THREAD

**Issue by swogjs** [daumPostcode/QnA#126]
시/도 선택 -> 구/군 선택 -> 동 선택 
이런 UI를 서비스 하려고 하는데 제공되는 API는 없는지요?
계획도 없는지요?

**Comment by daumPostcode** [comment]
@swogjs 
네~ 안녕하세요~

네 현재 말씀하신 기능을 하는 API는 제공하고 있지 않습니다.
또한 향후에도 지원할 계획은 아직 없는 상태입니다.

도움을 드리지 못해 죄송합니다;
