### ISSUE TITLE
특정 주소의 도로명 주소 값 리턴 문제

### ISSUE THREAD

**Issue by skout90** [daumPostcode/QnA#127]
안녕하세요.
다른 주소들은 문제가 없는데.
"만송동 694" 에서 "지번주소"를 클릭했을 경우,
다른 값들은 정상 리턴되지만
roadAddress:""
roadAddressEnglish:""
위와 같이 도로명 주소값이 리턴되지 않습니다.

혹시 다른 주소도 비슷한 케이스가 있을 수 있나요?

**Comment by daumPostcode** [comment]
@skout90 
네~ 안녕하세요~~

네! 비슷한 케이스가 충분히 있습니다.
현재 지번주소와 도로명 주소는 1:1 매핑이 아닙니다. 때에따라 1:N, N:N, N:1도 가능합니다.
이런 이유로. 말씀해주신 주소는 지번:도로명 주소가 1:N의 케이스로
이 경우에는 연관되어 있는 도로명 주소를 선택하지 않는한, 자동으로(기본값 autoMapping:true) autoRoadAddress라는 변수에 들어가게 되어 있습니다.

즉, 거의 항상 autoRoadAddress(지번의 경우에는 autoJibunAddress)를 체크해보고 roadAddress(jibunAddress)를 체크하시는게 좋습니다.

**자세한 설명은 
저희 [가이드 페이지 속성탭](http://postcode.map.daum.net/guide#attributes)에서 스크롤을 아래로 좀 내리시면, oncomplete데이터 시트 아래에, autoRoadAddress, autoJibunAddress에 대한 설명이 있습니다. 이부분을 읽어보시면 됩니다.**

추가적으로 각 주소를 다 분리하지 않고 1:N처럼 UI를 설계한 이유는, 말씀하신 주소는 1:2 정도라 괜찮아 보이지만, 1:10, 20은 흔하고, 1:100 이상도 꽤 있습니다... 이런 이유때문에 위처럼 설계를 해야 한페이지에 여러 주소를 최대한 많이 보여줄 수 있어서 그런 것이니 양해 부탁드립니다.

감사합니다.
