### ISSUE TITLE
V1에서 V2로 이전한 후 에러문제입니다.

### ISSUE THREAD

**Issue by cali2000** [daumPostcode/QnA#128]
그누보드4에 사용중인 다음주소 버전을..

//기존 버전
<script src="http://dmaps.daum.net/map_js_init/postcode.js"></script>
//신규 버전
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>

위 설명대로 변경을 하니 우편번호는 6자리 입력이 되는데.. 밑의 주소와 상세주소는 undefined로 나옵니다.

![image](https://cloud.githubusercontent.com/assets/8732653/24025083/8a04c576-0afb-11e7-899a-fdfce92ed841.png)

그누보드 common.js 파일-------

// 도로명 우편번호 창
    function win_zip(frm_name, frm_zip1, frm_zip2, frm_addr1, frm_addr2, frm_addr3, frm_jibeon)
    {
        url = g4_path + "/" + g4_bbs + "/zip.php?frm_name="+frm_name+"&frm_zip1="+frm_zip1+"&frm_zip2="+frm_zip2+"&frm_addr1="+frm_addr1+"&frm_addr2="+frm_addr2+"&frm_addr3="+frm_addr3+"&frm_jibeon="+frm_jibeon;
        //win_open(url, "winZip", "left=50,top=50,width=616,height=460,scrollbars=1");
        win_open(url, "winZip", "left=50,top=50,width=483,height=600,scrollbars=1");
    }

    /*
    // 우편번호 창
    function win_zip(frm_name, frm_zip1, frm_zip2, frm_addr1, frm_addr2)
    {
        url = g4_path + "/" + g4_bbs + "/zip.php?frm_name="+frm_name+"&frm_zip1="+frm_zip1+"&frm_zip2="+frm_zip2+"&frm_addr1="+frm_addr1+"&frm_addr2="+frm_addr2;
        win_open(url, "winZip", "left=50,top=50,width=616,height=460,scrollbars=1");
    }
    */

oncomplete 콜백 함수의 인자로 전달되는 항목을 수정해야 하는것 같은데.. 어디에서 수정을 해야 하는건지 모르겠습니다.

**Comment by daumPostcode** [comment]
@cali2000 
네~ 안녕하세요~

제가 금요일에 휴가라서 지금 확인했네요;; 답변이 늦어 죄송합니다.

일단 올려주신 질문 내용에 oncomplete구현체가 없어서 정확한 말씀은 드리기 어려우나, 

기존 v1을 사용하던 코드에서는 address1, address2라는 항목을 사용한 것 같네요. v2에서는 address1, address2가 deprecated되었습니다. 해당 내용은 저희 [가이드페이지 이전버전에서 옮기기](http://postcode.map.daum.net/guide#upgrade) 부분에서 확인 가능하시니 참고 부탁드립니다.

또한 6자리 우편번호가 잘 들어간다고 하셨는데요. 이는 v1, v2모두 발생하는 문제로 2015년 8월 1일 부터 우정국에서 더이상 6자리를 생성/유지를 하지 않기 때문에, 계속 6자리를 쓰시면, 대한민국의 반 이상의 주소에서 우편번호를 받으실 수 없습니다. 현재 새로 생성 및 기존 주소의 업데이트의 경우 6자리 구 우편번호는 들어오지가 않고 5자리 새 우편번호만 들어오니, 향후 몇년 안에 전체 주소의 구우편번호가 사라질 예정입니다. 이 점 참고 부탁드립니다.

추가 질문을 댓글 주시면 다시 답변 드리도록 하겠습니다. 추가적으로 그누보드 플랫폼에 대해서는 따로 검색을 해보셔야 될것 같아요;;(저도 잘 몰라서;;)
