### ISSUE TITLE
about:blank 이슈

### ISSUE THREAD

**Issue by eunx0916** [daumPostcode/QnA#132]
주소검색을 팝업으로 사용하려고 하는데 about:blank가 뜨는데요 
스크립트를 직접 작성한게 아니면 팝업시 about:blank가 뜬다는데 
제거할 수 있는 방법은 없을까요 ? 

![aboutblank](https://cloud.githubusercontent.com/assets/26758728/24439568/fec5e7cc-1489-11e7-997f-7861b2d75a80.png)

**Comment by daumPostcode** [comment]
@eunx0916 
네~ 안녕하세요~

일단 저희 api에서 제공하는 open메소드로는 해당 about:blank글자를 지우는 방법은 없습니다.

다만, 우회처리할 수 있는 방법이 있는데요.
enux님게서 직접 window.open을 이용해서 페이지를 띄우신 후, 그 팝업페이지에 저희 API의 embed함수를 이용해서,  삽입하는 방법이 있습니다. (embed함수의 페이지 끼워넣는 예제는 가이드페이지 참고)

이렇게 할경우, 저희 API에서 주소 검색후 값을 받으실땐, enux님게서 만드신 팝업페이지로 전달하게 되는데, 본페이지로  데이터를 전달하기 위해선 enux님게서 해당 데이터를 받아 직접 본페이지로 데이터를 보내주시면 됩니다.

한번 해보시면 쉽게 가능하실 겁니다. 

감사합니다.
