### ISSUE TITLE
https 환경에서 작동을 하지 않습니다.

### ISSUE THREAD

**Issue by moonlitangel** [daumPostcode/QnA#133]
`https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js`의 접근이 되지 않고 있어서, 정상적으로 작동을 하지 않습니다.

**Comment by asklsd** [comment]
동일증상 1인 추가입니다..ㅠㅠ

**Comment by 10mini** [comment]
저도 그러네요. 전부 그런가보네요 . 빠른해결 부탁드려요~

**Comment by mshyun** [comment]
저도 그러네요. 빠른 해결 부탁드려요!!

**Comment by moonlitangel** [comment]
이제 접근 되네요. 무슨 이유였는지 좀 궁금하네요

**Comment by daumPostcode** [comment]
@moonlitangel @asklsd @10mini @mshyun 

넵, 제가 상황파악을 하고 난 후에 정상화가 되었네요;;

우선 답변이 늦어 죄송합니다. 장애 조치를 진행한 팀에서 장애원인을 듣기까지 시간이 조금 걸린점 양해 부탁드립니다.

금일 ssl.daumcdn.net 장애의 경우, 저희 서비스 서버 자체의 장애는 아니며, HTTPS를 프록시 해주는  로드밸런서 쪽에서 발생한 장애입니다. 현재 해당 팀에서 오후 4시쯤에 장애 복구를 완료하였고, 현재 이 도메인에 엮인 서비스가 꽤 많아, 추후에 이런 장애가 발생하지 않도록 개선 적용을 할 예정입니다.

불편을 드려 죄송합니다.

다음에는 장애 파악을 더 빠르게 하여, 옐로 아이디로 발송해 드리겠습니다;;
