### ISSUE TITLE
아이폰에서 다음지도 호출 시, 주소가 유효하지 않음.

### ISSUE THREAD

**Issue by seukjin** [daumPostcode/QnA#134]
아이폰에서 모바일 웹 페이지의
다음 주소 API를 호출 시, 
레이어는 열리나, 
페이지를 열 수 없음
주소가 유효하지 않기 때문에 Safari가 해당 페이지를 열 수 없습니다. 
라고 얼럿창이 나옵니다.
해결 방법이나 증상을 아시는 분은 알려주시기 바랍니다.

참고로 iframe을 이용하여 레이어 띄우기 로 적용해 둔 상태입니다.

![image](https://cloud.githubusercontent.com/assets/12150280/24598259/76582e36-1885-11e7-947d-5b190d42c803.png)

**Comment by daumPostcode** [comment]
@seukjin 
네~ 안녕하세요~

먼저 우편번호 서비스에서는 해당 얼럿창처럼 메세지를 띄우는 것은 없습니다.
해당 오류는 사파리에서 띄우는것 같은데요.
먼저 가이드 페이지를 지금 확인해본결과 재현이 되지 않네요.
혹시 우편번호 검색버튼을 누를때 페이지를 submit한다던지 하는 로직이 있을까요?
또는 우편번호를 띄우면서 다른 호출하는 링크가 있는지두요.

가이드페이지에서는 재현이 되지 않기 때문에 오류확인을 하기가 어려운 점 약해 부탁드립니다.

제가 좀 더 확인을 하려면, 문제가 발생하는 테스트페이지나, 전체 코드가 필요합니다.
한번 확인하시고 답변 부탁드립니다.

**Comment by seukjin** [comment]
해결했습니다.
<a href 태그에 javascript:void(0); 이 있었습니다.
제거하니 사파리에서 잘 작동 합니다.

**Comment by seukjin** [comment]
해결했습니다.
<a href 태그에 javascript:void(0); 이 있었습니다.
제거하니 사파리에서 잘 작동 합니다.
