### ISSUE TITLE
우편번호 API 참조 시 문의사항

### ISSUE THREAD

**Issue by HyunSeokLee** [daumPostcode/QnA#136]
안녀하세요.
우편번호 API를 사용해서 C/S 프로그램으로 운영 중인데, 저희가 폐쇄망 기반이라 우편번호 API에 대해서 IP기반으로 허용 신청을 하려고 합니다.
IP기반으로 허용신청을 하려다보니..
허용 정보를 여쭤봐야되는데 여쭤보는 방법이 없어 이렇게 글을 남기게 되었습니다.
확인 부탁 드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@HyunSeokLee 

안녕하세요~

네 저희 API는 기본적으로 폐쇄망이 아닌 인터넷이 연결된 오픈된 환경에서 사용이 가능합니다.
왜냐하면 주소 검색 자체를 저희쪽 서버에 접속을 해야되기 때문입니다. 따라서 현재 폐쇄망에서의 사용은 공식적 지원은 하지 않고 있으며, 필요에 따라 이용자분께서 리스크를 감수하시고 이용하셔야합니다.

IP의 경우에는 잘 바뀌진 않지만, 그래도 변경이 되기 때문에 말씀드리기는 어려우며,
서비스에서 사용하는 전체 도메인 목록을 알려드릴테니; 해당 도메인으로부터 IP를 알아내서 이용하셔야 될것 같습니다;;

```
HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://apis.daum.net 
- http://stlog1.local.daum.net 
- http://sughub.search.daum.net (v1,v2)
- http://t1.daumcdn.net

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://s1.daumcdn.net 
- https://apis.daum.net 
- https://sughub.search.daum.net (v1,v2)
- https://t1.daumcdn.net
```

감사합니다.
