### ISSUE TITLE
우편번호 찾기 기능이 활성화되지 않습니다. 

### ISSUE THREAD

**Issue by one-moment** [daumPostcode/QnA#139]

**Comment by daumPostcode** [comment]
@one-moment 
네~ 안녕하세요~

현재까지 저희 서비스 장애로 인해 팝업창이 안뜬다는 제보는 없습니다.

그리고 스샷 올려주신것을 참고하여 사이트에 들어가보니, 브라우저의 문제가 맞긴 합니다.

팝업형의 경우 일부 모바일 브라우저의 window.open 미대응으로 인해 오작동을 하는 경우가 있어서 embed모드를 사용하시는 것을 추천드립니다. (http://postcode.map.daum.net/guide 저희 가이드 페이지의 예제에서 팝업을 이용한 예제에 빨간색으로 표기되어 있습니다.)

즉, PC에서는 팝업형이 아무런 문제가 되지 않으나, 모바일 브라우저의 경우, 오작동을 하는 경우가 많습니다. 특히 사파리 크롬은 괜찮더라도, 안드로이드의 각 벤더사 브라우저(삼성 엘지 브라우저 등), 카카오톡, 라인, 페이스북 같은 앱에 들어가 있는 웹뷰가 이에 해당됩니다. 이는 현재 기술적인 방법으로 해결이 좀 오래 걸려서, 가이드로 풀고 있는 점 양해 부탁드립니다.

이외 다른 이슈라면, 1moment사이트의 실행 로직도 봐야 됩니다. 저희 서비스가 단독으로 저희 도메인에서 실행되는게 아니라, 남의 사이트에 임베딩 되는 것이기 때문에, 간혹 해당 사이트의 코드가 문제가 될때도 있습니다. 실제 이런 이슈가 과거 종종 들어 왔었습니다. 일단 embed모드를 이용하는 방식중에, 레이어 방식보다는 끼워넣는 방식으로 수정 개발을 하시는 것을 추천드립니다.

현재 의심해 볼 수 있는 사항은 위 2개 정도이며, 내부적으로도 확인해 보도록 하겠습니다.
불편을 드려 죄송합니다.
