### ISSUE TITLE
자동완성기능

### ISSUE THREAD

**Issue by wwweojin** [daumPostcode/QnA#14]
사당로 272 을 검색하는데 
사당로 272를 넣으면 아래에 검색결과가 없는것처럼 나오고 검색버튼을 클릭하면 검색은 되긴 합니다.

그리고 다음검색에서 "한국가이드스타" 는 검색되는데

우편번호 API에서는 검색결과가 없는것으로 나오네요 ?

**Comment by daumPostcode** [comment]
@wwweojin 
네~ 안녕하세요~
자동완성(이하 서제스트)의 경우, 실제 검색버튼을 눌러 검색하는 것과는 이용하는 데이터가 조금 다릅니다.
서제스트의 경우에는 검색쿼리를 완성하는데 도움을 줄려고 하는 것이지, 지금 검색할 쿼리에 대한 정보가 있다 없다를 표시하는 것은 아닙니다. 그리고 말씀하신 **"사당로 272"**의 경우에는 도로명+건물번호로 된 하나의 주소이며, 서제스트에 나오는 것들은 도로명 또는 읍/면 까지만 나오는 점 참고 부탁드려요~

두번째 한국가이드스타의 경우, 삼보빌딩이라는 건물에 속한 하나의 업체로써, 이부분은 우편번호 검색기에서 포함하는 영역은 아닙니다. 저희가 알수 있는 것은 **삼보빌딩**이라는 건물이며, 주소는 이 삼보빌딩에 의해 도로명 주소가 만들어 집니다. 즉 삼보빌딩안에 어떤 업체가 있는지는 주소체계상 알 수 없습니다. 예를 들어, 삼보빌딩안에 수많은 업체가 있을 건데요, 이 업체들의 주소(도로명, 지번 모두)는 모두 같습니다. 다만 하나의 구역을 확정하기 위해 추가적으로 **X층 XX회사 누구누구**를 쓰는 것이죠. 

저희는 다음 검색처럼 전체 상호+주소를 모두 포함하는 검색서비스가 아니며, 지금까지 홈페이지 가입이나 이런걸 해보시면 아시듯이, 단순 하나의 건물(또는 영역)에 대한 기본적인 주소를 제공하는 서비스입니다. 실제 이용하실려는 상세한 주소는 저희 서비스를 이용해서 기본 정보를 받으신 후, 추가 입력을 해주시면 됩니다.

그리고 저희 검색은 다음 또는 네이버의 통합검색과는 다르며, 제일 비슷하게 검색되는 것은 [행자부 도로명 검색 시스템](http://juso.go.kr)입니다. 왜냐하면 여기서 데이터를 받기 때문에죠. 자세한 사항은 [QnA README](https://github.com/daumPostcode/QnA)와 [공식 가이드 페이지](http://postcode.map.daum.net/guide)를 한번 읽어보시길 추천합니다.
