### ISSUE TITLE
js 파일 다운로드 오류 문제

### ISSUE THREAD

**Issue by sehunone** [daumPostcode/QnA#140]
https로 다음 우편번호 검색 서비스를 사용하고 있는데, 몇 주전 부터 postcode.v2.js 파일이 다운로드되지 않는 경우가 있습니다. 
해당 문제가 저희 쪽에서 추가로 설정해야 하는 문제인지 아니면 다음cdn 쪽에서 문제가 있는 건지 확인 좀 해주실 수 있을까요?
그리고 동일한 문제가 있을 경우 어떻게 처리하는 것이 좋을 지 가이드 좀 부탁드립니다.
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

**Comment by daumPostcode** [comment]
@sehunone 
네~ 안녕하세요~
현재 저번주에 cdn서버 장애로 인하여 약 2시간 정도 문제가 발생하긴 했습니다.
그 이후 복구되어 현재는 정상 서비스 중인데요. 
혹시 외부 인터넷이 단절된 내부망에서 서비스 중이신가요? 현재 다운로드가 되지 않는 다는 문제는 보고된게 없어서요;

저번 오류시에는 제가 YellowID발송을 하지 않았는데; 추후 오류 발생시에는 카톡메세지로 오류를 보내드릴 예정입니다. 물론 오류가 발생을 안하게 하도록 최대한 노력하겠지만, 만에하나 발생한다면 메세지를 보내드릴 예정이니, 저희 가이드페이지 맨 하단을 참고하셔서 카톡 플러스 친구를 등록해 주시면 감사하겠습니다.
