### ISSUE TITLE
주소 검색후 도로명 선택이 안됩니다.

### ISSUE THREAD

**Issue by AnSeungMuk** [daumPostcode/QnA#141]
올림픽로 715 검색 후 
두번째 강원도 평창군 대관령면 올림픽로 715(유스호스텔) 더보기 후 13개 주소 중 아무것도 선택이 안됩니다.

**Comment by daumPostcode** [comment]
@AnSeungMuk 
네~ 안녕하세요~
해당 현상은 정상 동작입니다.
http://postcode.map.daum.net/guide#attributes 저희 가이드 페이지 속성탭의 중간쯤에 autoMapping관련한 부분이 있습니다. 이부분 읽어보시기 바랍니다.

기본적으로 autoMapping은 true입니다. 아마 autoMapping을 false로 실행하신 것 같은데요.
이 옵션을 일부로 true로 한 이유가, 바로 사용자 선택권이 더 많기 때문입니다. 
도로명 주소 특성상, 같은 주소인데 건물명이 여러개인 경우가 있고(해당케이스), 하나의 도로명 주소에 엄청나게 많은 지번주소가 매핑되어 있을 수도 있습니다. 그렇기 때문에 사용자가 어떤걸 선택했는지 확신할 수 없고, 최대한 도로명 주소와, 지번주소 한세트를 내릴 수 있게 하기 위해 autoMapping이 true로 설정되어 있는 것입니다.

저희 가이드 페이지의 속성 부분 전체를 확인해 보시면, 아실 수 있는 내용이며, 샘플도 몇개 확인해 보시기 바랍니다.
