### ISSUE TITLE
도로명 코드가 안넘어 와요

### ISSUE THREAD

**Issue by kyeongjin** [daumPostcode/QnA#142]
안녕하세요,
다음 api 쇼핑몰에 적용하여 사용하고 있습니다.

이전의 문의 드렸을 경우
지번 주소로 검색하였을 경우 도로명 코드가 넘어 오지않아,
추가적으로 개발 완료 하였다고 해주신 것으로 기억 합니다.

그런데, 지번 주소로 검색 하였을 경우 아직 도로명 코드가 넘어오지 않는 경우가 
있는 것으로 보여 문의 드립니다.

주소1 : 울산 중구 남외동 390-8 
주소2 : 익산시 영등동 538-289    

이 두 주소 뿐 아니라
검색을 해보니 도로명 코드가 안넘어 오는 경우가 많은 거 같습니다

빠른 확인 부탁 드리겠습니다

**Comment by daumPostcode** [comment]
@kyeongjin 

네~ 안녕하세요~

음.. 저희 가이드 페이지에서 확인해본 결과
말씀해 주신 

주소1 : 울산 중구 남외동 390-8
![1](https://cloud.githubusercontent.com/assets/20675065/25220281/47b8ea56-25ec-11e7-83b7-1f9b547671f6.png)

주소2 : 익산시 영등동 538-289
![2](https://cloud.githubusercontent.com/assets/20675065/25220288/4ed1644e-25ec-11e7-8901-b94dcb5749b5.png)


이 두개 주소의 roadnameCode가 정상적으로 내려가고 있는 것으로 확인이 됩니다.

만약 나오지 않는 주소가 있다면, 말씀해 주시면 최대한 빠르게 조치를 취하도록 하겠습니다.

실제 내려가는 데이터의 확인은 http://postcode.map.daum.net/guide#attributes
저희 가이드 페이지의 속성 부분의 "반환되는 데이터 확인하기"를 눌러서 확인하시면 쉽게 확인 가능한 점 참고 부탁드립니다.

감사합니다.
