### ISSUE TITLE
 경기 용인시 처인구 이동면 백옥대로 687-20

### ISSUE THREAD

**Issue by 1025co1p** [daumPostcode/QnA#144]
주소 검색시 기존 가맹점 상호 나옴  (삼수갑산) 삭제 요청 합니다.

**Comment by daumPostcode** [comment]
@1025co1p 
네~ 안녕하세요~

해당 건물명 삭제는 행정자치부 도로명주소검색사이트의 고객센터를 통해 처리 바랍니다.
-> https://www.juso.go.kr/help/QABoardList.do

위 URL에서 요청하시어 처리가 되면, 저희 서비스에도 반영이 됩니다.
저희 [FAQ](https://github.com/daumPostcode/QnA/blob/master/README.md#1-주소가-없습니다--검색되지-않습니다)에도 명시되어 있으니 확인 바랍니다
