### ISSUE TITLE
경남 거제시 장목면 외포리 894번지 남광토건

### ISSUE THREAD

**Issue by kimseokjong** [daumPostcode/QnA#145]
우편번호 API 에서 검색이 안됩니다.
추가해 주세요.

**Comment by daumPostcode** [comment]
@kimseokjong 
네~ 안녕하세요

문의 주신 주소는 도로명 주소가 발급되지 않은 주소입니다.

![2017-04-28 4 52 33](https://cloud.githubusercontent.com/assets/20675065/25519539/32665cf4-2c33-11e7-9370-482c3ce20726.png)

현재 행자부 시스템에도 검색이 되지 않아, 등록 요청을 해주셔야 합니다.
주소 등록은 저희가 대행해 드리지 않으며, 
[FAQ1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)을 참고하여 
행자부 사이트에서 등록해주시기 랍니다.

행자부사이트에 등록이 되면, 저희는 익일 등록됩니다. 다만 보안주소라면 저희 시스템에서는 검색이 되지 않는점 참고부탁드립니다.
