### ISSUE TITLE
외부 방화벽이 다 차단되어있을 경우, 허용시켜야 하는 URL이 어떤것들이 있나요??

### ISSUE THREAD

**Issue by zooxop** [daumPostcode/QnA#146]
안녕하세요. 현재 제가 테스트중인 프로그램에서 다음 우편번호 api를 이용해서 주소검색을 하고 있습니다.
그런데.. 현재 작업중인 환경이, 외부망이 전부 막혀있어서 그런지.. 실행시키면 바로 스크립트 에러가 발생하네요.

통신사에 문의해서 다음 우편번호 api에서 사용하는 url을 차단규칙에 허용으로 추가하도록 하려고 하는데요.
https://github.com/daumPostcode/QnA/issues/62 
위 링크의 글을 참조하여,

·         http://postcode.map.daum.net
·         http://dmaps.daum.net
·         http://s1.daumcdn.net
·         http://i1.daumcdn.net
·         http://m1.daumcdn.net
·         http://apis.daum.net
·         http://stlog1.local.daum.net
·         http://sughub.search.daum.net
위 url들을 전부 규칙에 추가하였습니다.

그런데도 계속 동일하게 스크립트 에러가 발생하고 있네요.. 
혹시 위 url 말고도 다른 url을 추가해줘야하는건지..
아니면 다른 문제가 있는건지 모르겠네요 ㅜ.ㅜ
외부망 차단하기 전까지는 잘 작동하던건데, 망 차단하자마자 스크립트 에러가 발생해서.. 망이 차단된것때문에 발생한 문제라고 생각되는데..

답변 부탁드립니다 ㅜ.ㅜ

**Comment by daumPostcode** [comment]
@zooxop 
네~ 안녕하세요~

연휴가 길어서 답변이 늦었네요;; 죄송합니다.
네; 현재 저희 서비스는 인터넷 기반 환경이라 내부방은 공식적으로 지원하진 않는점 양해 부탁드리며,
요청해주신 분들에 한해서 도메인 리스트만 제공하고 있습니다.

다만; 이 또한 저희 내부적인 개발 이슈에 의해서 도메인이 변경되는 경우가 간혹 있는데요, 이때마다 말씀드리기가 좀 어려운 상황입니다.

일단 현재 위에 적은 리스트 중에서

apis.daum.net의 경우 우편번호가 아닌 Daum 오픈API를 사용할 경우 필요한 도메인이라 사용하지 않는다면 제거하셔도 되며 m1.daumcdn.net, i1.daumcdn.net도 사라진 도메인입니다.
새로 추가된 도메인은 http://t1.daumcdn.net 도메인으로써, 스크립트보다 이미지 리소스를 관리하는 도메인입니다.

다만, 어떤 스크립트 에러가 발생하는지 구체적으로 적어주시면 좀 더 확인해 보도록 하겠습니다.

감사합니다.

**Comment by zooxop** [comment]
안녕하세요~ 우선 답변 감사합니다! 별로 늦지 않았어요 ㅎㅎ
우선 문제는 해결하였습니다. 방화벽 규칙에 *.daum.* 을 추가해버렸거든요 ㅎㅎ..
통신사측이랑 계속 문제해결을 위해서 이것저것 시도해본 결과.. 위 url들을 각각 방화벽 규칙에 추가하려면 URL이 아니라 IP로 등록을 해야한다고 하더군요.
그런데, 통신사측에서 확인해본 결과, 그 IP가 계속 바뀌는것으로 보인다~~ 라고..
그래서 어쩔 수 없겠구나 싶어서 그냥 daum URL 자체를 규칙에 추가해버렸습니다. 그래서 우편번호 api도 잘 작동되고, 웹서핑도 신나게..ㅋㅋㅋ

아무튼 성의있는 답변 감사합니다 ㅎㅎ 수고하세요~~

**Comment by daumPostcode** [comment]
@zooxop 

아 그러셨군요 ㅎㅎ 다행이네요 ^^

네; 저희도 IP가 자주 변하진 않더라도, 가끔 변하기 때문에 IP로 알려드릴 수 없어서 도메인 리스트만 제공을 하고 있었습니다. 물론 공식 지원이 아니기 때문이기도 했지만요 ㅎㅎ

아무튼 잘 해결되서 다행입니다 ^^

오늘도 즐거운 하루 보내세요~~
