### ISSUE TITLE
iframe 레이어 띄우기 방식의 iOS bug issue 관련

### ISSUE THREAD

**Issue by drmccy** [daumPostcode/QnA#147]
http://postcode.map.daum.net/guide 의 "iframe을 이용하여 레이어 띄우기" 방식의 설명에  아래와 같이 iOS의 bug issue에 대해 설명되어 있고 
실제 적용한 서비스에서 검색을 위한 입력시 입력창이 보이지 않는영역으로 사리지고 
자동완성 결과목록이 보여지는 현상이 나타납니다.

아래 설명에서 얘기하는 "자신의 페이지에 맞게 위치값을 조정.." 하려 해도 iframe안의 input의 입력순간의 event가 없어 위치 조정 시점을 알수가 없습니다.

제공하시는 guide page의 예제를 iOS에서 실행해 봐도 마찬가지 증상이 나타납니다

Q1. iOS에서 해당 bug issue를 fix할 방법이 있는지요?

Q2. 있다면 iOS에서 잘 동작하는 iframe layer 방식의 sample을 제공해 주실 수 있는지요?

답변 부탁드립니다...

[guide page의 bug issue 관련 설명]
(현재 iOS 8.x ~ 10.x, Safari, webview 브라우저에서 input필드를 터치하면(키보드 또는 액션시트가 올라올때) position:fixed된 엘리먼트가 페이지의 최상단으로 올라가는 버그가 있습니다. 해당 샘플 코드를 이용하시는 분들께서는 자신의 페이지에 맞게 위치값을 조정하여 사용하시길 권장합니다.)

**Comment by daumPostcode** [comment]
@drmccy 

네~ 안녕하세요~

연휴가 길어서 답변이 늦은점 죄송합니다;;

네 해당 이슈의 경우 여러가지 케이스가 있을 수 있습니다. 
현재 ios업데이트로 인한 fixed 엘리먼트가 페이지의 최상단으로 사라지는 버그는 수정이 된것 같네요;; 
최상단으로 올라가는 버그는 fixed의 top속성이 적용되지 않아 본문 우편번호 레이어를 띄우는 버튼이 본문 아래쪽에 있을때 스크롤을 해서 내리게 되는데, 이때 키보드가 올라오면서 우편번호 레이어가 최상단으로 올라가버려, 검색영역, 검색결과 상관없이 안보이게 되는 버그였습니다.
(추후 업데이트시 문구는 제거될 예정)

말씀해주신 이슈는
layer는 정상적인 위치에 존재하는데, 검색 영역에 마우스를 터치하고 검색을 하면, 검색어에 따라 서제스트를 보이게 되는데 이 서제스트의 양에 따라 검색바가 위쪽으로 올라가 버리는 현상(즉, 레이어 안쪽으로 들어가서 안보이는 현상)으로 보입니다.

스크린샷을 넣어 주셨으면 좀 더 정확하게 판단가능한데;; 일단 제가 테스트시 이런 문제가 발생하는군요.
이 부분도 추후 샘플을 좀 수정하도록 하겠습니다.

해결방법으로는
- 샘플코드에 보시면 initLayerPosition이라는 함수가 있는데 이 함수가 우편번호 서비스가 들어간 layer 엘리먼트의 크기를 조정합니다. 즉 여기서 height값을 좀 크게 잡으시면 됩니다. 500정도 잡으시면 될것 같습니다.

추가적으로 샘플코드는 샘플코드일뿐, 저희 우편번호 서비스의 기본 API의 규칙만 지킨다면 굳이 샘플코드처럼 안만드셔도 되고, 마음대로 구조 변경을 하셔도 되는점 참고바랍니다.

만약 이 이슈가 아니라면 스샷을 첨부하셔서 다시 질문해 주시면 좀 더 확인해 보도록 하겠습니다.
감사합니다.

**Comment by drmccy** [comment]
안녕하세요...

빠른 답변 감사드립니다..

현재 문의드리는 현상은 답변에서 iOS버그 수정되었다고 말씀주시는 popup된 layer자체가 상단으로 사라지는 현상은 아닙니다.. 
추정으로 언급하신 검색어 입력시 서제스트 목록이 발생하며 이에 따라 레이어 안쪽으로 scroll되어 올라가는 현상이며 스샷 첨부드립니다

현상을 확인하실 수 있는 url은
1. http://mwsout.menupan.com/korex/korex_req.asp (저희서비스 입니다)
2.  http://postcode.map.daum.net/guide (다음제공 iframe을 이용하여 레이어 띄우기 예제)
저의 테스트 환경은 iPhone 5 (4") / iOS 10.3.1 / 사파리브라우져(최신버전) 입니다

첨부하는 이미지는 2번(daum sample)을 기준으로 한 스샷입니다.
1. 예제초기화면
![1_img_3129](https://cloud.githubusercontent.com/assets/28527244/25885620/70c5bc5a-3594-11e7-8990-df82ba47515d.png)
2. [우편번호 찾기]버튼을 눌러 layer를 띄운화면
![2_img_3130](https://cloud.githubusercontent.com/assets/28527244/25885642/99e32b04-3594-11e7-8797-d21e489bbe8e.png)
3. 검색입력창에 focus를 주어 키보드layer가 올라온화면
![3_img_3131](https://cloud.githubusercontent.com/assets/28527244/25885671/b667bbfa-3594-11e7-8f7f-89f0148bbaba.png)
4. input에 '서' 를 입력한 화면 (문제의 현상 -> input영역이 popup layer위로 사라짐)
![4_img_3132](https://cloud.githubusercontent.com/assets/28527244/25885685/d79414b8-3594-11e7-8b51-a3df28cb3053.png)

4-1. 가끔씩 입력상황에 따라 input이 노출되는 장면
검색을 위해 문자를 입력하다보면 불규칙적으로 가끔 입력창이 정상적으로 내려오는 경우도 있습니다.
'서현동' 입력후 back키를 누르며 지우는 방식으로 확인 가능 합니다
![5_img_3133](https://cloud.githubusercontent.com/assets/28527244/25885702/f5616dc4-3594-11e7-93c4-3b353dfce5f9.png)

해결방법으로 주신 height를 500정도 잡는 방법은 아마도 서비스하시는 검색목록의 height가 500 정도 이기 때문에 그만큼 scroll되어 사라지는 영역이 줄어드는 효과는 있기는 합니다
(저희서비스는 UI상 320px로 설정되어 있습니다.)
저희서비스도 500정도로 높이를 변경하면 그래도 많이 문제에 대한 보완이 되긴 합니다만
500의 높이는 iPhone5 + 사파리 기준으로는 화면에 꽉차게 되는 크기이고
사파리는 scroll시에 주소창과 하단 tab버튼이 자동으로 올라오므로 popup layer를 가리게 됩니다
(크롬도 마찬가지 현상 입니다)

또한가지 현상은 서제스트 목록이 출력된 상태에서 키보드 창을 내리고 touch scroll을 시도할때
layer 창안쪽이 scoll되는것이 아니고 뒤의 body영역이 scroll되기도 하는데 scroll을 시도할때마다
안,밖으로 scroll 영역이 일정치 않은현상이 보입니다

현상 검토 부탁드리고 
제시 주신 height 증가 이외에 다른 대안 마련해 주시면 좋겠습니다

혹시 더 자세한 내용 확인이 필요하시면 회신 가능한 메일주소를
drm@menupan.com 로 알려주시기 바랍니다

감사합니다

**Comment by daumPostcode** [comment]
@drmccy 
네;

먼저 죄송하게 생각합니다.

말씀해 주신 이슈중에 내부 스크롤시 본문이 스크롤되는 이슈는, 예전부터 발생하던 문제이긴 하나 사용에 큰 문제가 없다라고 판단되어 현재 배포가 되어 있는 상태입니다.
저희가 테스트 해본 결과 항상 발생은 아니고 대략 20~30프로확률로 어디를 터치해서 움직이냐, 우편번호 서비스가 스크롤 중인가 유무에 따라 발생하고 있는 것으로 보이는데, 해당 이슈는 현재로써는 잡는게 좀 어려울것 같습니다. iframe을 2중으로 겹쳐 쓰면서 발생하는 사이드이펙트 중 하나로 해당 이슈는 구조변경을 통해서 해결을 봐야 될것 같아요; 다만 현재 일정잡기가 어려워 바로 수정이 어려운점 양해 부탁드립니다. 그래서 짬짬이 시간날때 하고 있긴 한데 좀 걸릴 것 같아요;;

두번째, 기존에 문의 주신 이슈인 서제스트 목록이 나올때의 이슈의 경우, 저희 API를 이용하시는 분께서 잡는건 어렵다고 판단이 되고, 제가 수정을 해야하는 사항인데, 현재 검색창에 focus가 갈때 overflow hidden속성을 통해 보이지 않는 부분을 막는 방법(다만 blur가 됬을때 다시 위로 올라가 버릴 수도 있는;;)과 서제스트를 사용하지 않게 하거나 갯수, 높이 등을 수정하는 옵션을 추가하는 방법 현재 떠오르는 방법이고 한번 개발해서 테스트를 해봐야 될 것 같습니다. focus로 쉽게 처리가 되지 않으면 후자의 방식으로 처리가 될 확률이 높습니다.

이런 CS의 경우 height를 늘리는 것과, 저희 샘플에 있는 본문에 끼워넣는 방식을 사용하여 내부스크롤이 동작하도록 쓰는게 아닌 검색 결과의 양에 따라 높이를 flexible하게 조절하여 사용하는 방식으로 가이드를 드렸는데요. 현재 drmccy님의 홈페이지에는 맞지 않는 것 같네요;;

일단 이슈들이 제가 수정을 진행해야 되는 것들이라; 금방 적용이 어렵기 때문에; 쓰기 불편하신 경우
- https://www.poesis.org/postcodify/
- http://www.juso.go.kr/addrlink/main.do

위 두개를 참고해서 다른 API를 이용하시는 것도 방법이니 참고 부탁드립니다.

도움을 드리지 못해 죄송합니다;

**Comment by drmccy** [comment]
점점 더 빨라지는 답변 감사드립니다.. ^^

스크롤 이슈는 생각보다 복잡한 문제인가 봅니다.. 
말씀 주신대로 확률적 오류동작이고 기능사용에 치명적 문제는 아니어서
기다려 보도록 하겠습니다..

두번째 issue는 답변 주신 내용 이해 하였습니다..
구체적 해결 방안에 대해서는 얘기드릴 입장이 아닙니다만..
말씀주신 옵션설정으로 특정 환경에서 발생되는 minor 오류를 우회할 수 있게 
되면 좋겠습니다..

개선이전까지 저희도 외부적으로 불편을 감소시킬 수 있는 방안을 
계속 찾아 봐야 겠습니다

다른 유사 API 서비스에 대한 소개 고맙습니다만
제작/운영해주시는 서비스가 맘에들어 일단 사양합니다..^^;

일정되시는 데로 빠른 개선 부탁드립니다..

수고하세요~

**Comment by daumPostcode** [comment]
@drmccy 

ㅎㅎ 네 아닙니다.
아이폰 safari inner scroll이슈는 예전부터 많이 존재했던 문제이긴 한데,
제가 하나의 코드로 모바일부터 IE6~edge, PC 모던브라우저 까지 모두 대응하려고 하다보니 iframe을 2개나 중첩해서 사용하고 있는데요;; 약간 스스로 무덤을 판 것도 있긴 합니다 ㅜ.ㅜ;;;

초기 개발할 당시의 대응 플랫폼과; 현시점의 대응 플랫폼이 조금씩 달라지며, 각 플랫폼들도 업데이트를 통해 기존 버그가 사라지기도 하고, 쌩뚱맞은 새로운 버그가 생기기도 합니다. 그래서 점점 대처가 늦어지고 있는데요;

네 말씀드린대로, 첫번째 이슈는 언제가 될지 모르나 구조변경으로 수정을 노리고 있으며;;
두번째 이슈는 그래도 빠른 시일안에 테스트를 해보고 정 수정이 힘들면 옵션을 추가하는 방법으로 해결을 하도록 하겠습니다. 수정이 완료되면 이 이슈에 댓글 드리도록 하겠습니다.

그럼 오늘도 하루 마무리 잘 하시고~ 즐거운 저녁 보내시기 바랍니다~
감사합니다

**Comment by daumPostcode** [comment]
@drmccy 

안녕하세요~~ 9일만에 답변을 드리네요 ㅎㅎ
yellowID를 등록해 두셨다면 알림을 받으셨겠지만, 해당 버그를 회피하는 방법을 적용한 버전이 배포되어 공유드립니다.

현재 해당 버전은 iOS 10.3.x 대에서 발생한 버그로 확인이 되며, 본문의 스크롤 위치에 영향을 받는 것으로 확인이 됩니다.
즉 본문의 최상위 에서 우편번호 서비스를 열면 해당 이슈가 발생하지 않으나, 본문을 내린후 (스크롤 위치 조정) 우편번호 서비스를 열면 재현이 가능해 지네요..(테스트 케이스가 이런 경우가 없어서 미처 확인을 못했었습니다 ;;) 
보통 맨 위 상단에 주소 입력이 있기 보다 본문 중앙 쯤에 있기 때문에 대다수의 iOS단말에서 버그가 발생할 거라고 생각이 들어 금일 배포처리가 완료되었습니다.

일단 현재 버전은, iOS에서 레이어모드로 이용시, 검색바를 터치하여 focus가 발생하면; 검색바를 제외한 모든 본문 내용을 숨겨서 스크롤을 안생기게 하는 방법으로 패치하였으며, 실제 검색을 하는 행동을 할시 아래의 본문은 서제스트를 통해 가려지기 때문에 이용에 큰 차이가 없다고 판단되어 수정 적용하였습니다 (JS로 스크롤 제어가 원하는 동작을 하지 않음)

또한 같이 업데이트된 maxSuggestItems라는 옵션이 생성자에 추가가 되었는데요. (가이드 페이지 속성 부분 참고)
이 옵션 또한 해당 오류를 잡기 위해서 적용되었습니다.
이유는 본문을 다 가린다 해도, 서제스트가 나오면 스크롤이 생기기 때문에 이슈가 또 발생하기 때문인데요.

drmccy님의 페이지 처럼 height를 매우 작게 유지하는 서비스에서는 서제스트 목록의 최대 갯수를 1~3개 정도로만 설정하시면 스크롤도 생기지 않고 검색도 다 되는 방식으로 처리가 될 것 같습니다.

한번 적용해 보시고 궁금한 점 있으시면 언제든 댓글 주시기 바랍니다.

그럼 즐거운 저녁 보내세요~~
