### ISSUE TITLE
영문 가이드 있나요?

### ISSUE THREAD

**Issue by JisunHwang** [daumPostcode/QnA#148]
다음 우편번호 서비스를 사이트에 구현하려 하는데, 영문 가이드가 필요한 상황입니다.
답변 부탁 드리겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@JisunHwang 

네~ 안녕하세요~

연휴가 길어서 답변이 늦은점 죄송합니다;;
네 현재 저희 서비스의 영문 가이드는 별도 제공하고 있지 않습니다.

실제 프로그램 코드보다, 대한민국의 주소체계를 설명하는게 쉽지 않기도 하고, 국내향 서비스다 보니 외국어 버전은 없습니다.

주소체계의 설명은 https://www.juso.go.kr/openEngPage.do <- 여길 참고부탁드리며,
저희 API는 번역기를 이용하시는게 최선의 방법같네요;;

도움을 드리지 못해 죄송합니다.
