### ISSUE TITLE
우편번호 검색이 안되는 2건 추가요청

### ISSUE THREAD

**Issue by goodboys100** [daumPostcode/QnA#149]
1. 창원시 의창구 북면 감계로 233
2. 경기도 고양시 덕양구 서오릉로500번길 141-7

다음우편번호 검색시 조회가 안되는 건입니다. 행정 우편번호 검색은 됩니다.

**Comment by daumPostcode** [comment]
@goodboys100 

네~ 안녕하세요~

데이터 확인에 시간이 걸려 답변이 늦은 점 죄송합니다.

1. 창원시 의창구 북면 감계로 233
-> 해당 주소는 내부적으로 DB이관시 누락된 주소로써, 내일 적용될 예정입니다. 불편을 드려 죄송합니다.

2. 경기도 고양시 덕양구 서오릉로500번길 141-7
-> 해당 주소는 내부적으로 판단할때 좌표값이 없는 보안주소로써, 이는 여러가지 경우가 있을 수 있습니다.
대표적으로 국가에서 지정한 보안구역일때와, 아직 건물이 없는데 미리 발급이 된 도로명주소의 경우가 있습니다.
해당 주소는 현재 저희가 확인하기로는 건물이 없는데 발급된 주소로써, 좌표정보가 없어, 저희 서비스처럼 지번+도로명 매핑을 기준으로 검색결과를 표출하는 시스템에서 검색결과 매핑이 불가능 하기 때문에 제외된 상태입니다.
이를 확인 하실 수 있는게 자세한 확인은 안되더라도 저희 서비스에서 검색이 안되는 주소의 경우, 행자부 사이트에서 검색할때 지도마크가 없는 경우가 있는데 이러한 주소는 저희 서비스에서 검색이 되지 않습니다.

결론적으로 해당 주소는 행자부만 가지고 있고, 저희에겐 좌표값을 주지 않기 때문에 표출이 어려우며,
다만, 건물이 없는 상태에서 미리 발급된 주소로 보이기에 추후 추가가 될 순 있습니다.

현재 보안주소(좌표값을 주지 않는 주소)의 경우 전체 주소 중에 0.03% 정도 비율을 차지하고 있으니 참고 바랍니다.

감사합니다.
