### ISSUE TITLE
다중 Ajax 사용시

### ISSUE THREAD

**Issue by lys6115** [daumPostcode/QnA#15]
주소검색이 필요한 위치가 이미 ajax를 통해 Layer를 호출한 페이지에 놓여있습니다.
그 상태에서 우편번호 API를 호출하면 주소검색까지 잘 되나.. 클릭하면 데이터가 옮겨가지 않습니다.
스크립트를 인식하지 못한다 생각되어, 다른 방법으로 진행중이나 많이 부족한지라 안되네요..

1. 버튼 클릭시 주소리스트가 Layer 로 호출됩니다.(Ajax 사용)
2. 주소리스트에서 '주소검색(Daum 에서 제공한 기본 API)' 버튼을 누를경우, 주소검색창이 호출됩니다.
3. 주소를 클릭시 주소데이터가 넘어가지 않습니다..

**Comment by daumPostcode** [comment]
@lys6115 
네~ 안녕하세요~~

말씀하신 내용으로 보아, 일단 저희쪽 스크립트(postcode.v2.js 와 core스크립트인 1608XX.js)는 모두 정상적으로 호출 된 것으로 확인됩니다.(검색화면이 뜨기 때문에.)

일단 문제가 되는 우편번호 서비스의 검색결과에서 주소를 클릭시 주소데이터가 넘어가지 않는 문제는, 보통 oncomplete부분에서의 오류라고 판단 가능합니다.

여기서 oncomplete관련된 오류라고 하는것은 여러가지가 있습니다. 부모페이지에 있는 DOM레퍼런스들이 모두 사라졌거나, 또는 오타로 인해서 문법적 오류가 발생했거나 등, 여러가지 원인이 있을 것 같은데요. 

저희 API를 embed()를 이용한 레이어모드로 이용시에는 크롬에서 테스트할때 개발자도구를 여시고 확인하시면 오류를 쉽게 잡으실 수 있습니다. 만약 오류가 뜨지 않는 다면 논리적 오류인데, 이부분은 현재 말씀해 주신 내용으로는 파악이 불가능하며, 저희가 접근할 수 있는 URL이나 코드를 알려주시면 고맙겠습니다.
