### ISSUE TITLE
우편번호 검색이 안되는 건지 이상하게 검색이됩니다.

### ISSUE THREAD

**Issue by nosgi** [daumPostcode/QnA#150]
"충청남도 논산시 취암동 145-1" 검색시

"충남 논산시 화지동 145-1 (행정동:취암동)" 으로 검색이되는데

data.bname 값도 화지동으로 옵니다.

확인해주세요

**Comment by daumPostcode** [comment]
@nosgi 
네~ 안녕하세요

먼저! 검색결과에서 "충남 논산시 화지동 145-1"로 검색이 되는 경우, 주소는 법정동 기준이기 때문에, bname이 화지동으로 나오는게 맞습니다. 취암동은 hname에 들어가게 되며 hanme에 표출 정책은 http://postcode.map.daum.net/guide#attributes 저희 가이드 페이지의 showMoreHName 옵션 사용법을 참고하시기 바랍니다.

일단 동작방식은 맞긴하나;;
말씀해 주신 주소는 저희가 DB이전에 따른 문제로 인해, 업데이트 반영이 누락된 주소로써, 잘못된 주소가 맞습니다.
충남 논산시 취암동 145-1은 법정동이 취암동인데 잘못 들어가 있는 거네요;; 내일 반영 됩니다;;

불편을 드려 죄송합니다;;

**Comment by daumPostcode** [comment]
@nosgi 

안녕하세요.
금일 말씀하신 취암동 145-1 주소의 법정동명이 정상적으로 반영되었습니다.

기다려 주셔서 감사합니다.
