### ISSUE TITLE
우편번호 검색이 안됩니다!!

### ISSUE THREAD

**Issue by peterpark5** [daumPostcode/QnA#151]
경기도 성남시 수정구 위례대로 83 검색이 안돼요.
행자부랑 다음지도에서는 검색 되는데 우편번호 서비스에선 검색되지 않아요

그리고 지번도 둘이 다르더군요 한번 확인해주셔요!!

좋은하루되셔요!!!

**Comment by daumPostcode** [comment]
@peterpark5 

네~ 안녕하세요~

"경기도 성남시 수정구 위례대로 83"주소의 경우 저희쪽 판단기준으로 "보안주소"입니다.
이런 주소는 행자부에서 저희쪽으로 데이터를 보내줄때 좌표값을 제거하고 내려줍니다. 좌표값이 없으면 현재 저희 시스템상 지번주소와 매핑을 시킬 수가 없기 때문에 저희 서비스에서는 노출이 불가능합니다.

이러한 데이터는 전체 주소데이터중 0.03% 정도 차지하고 있으며, 질문주신 주소가 이 케이스에 해당됩니다 ㅜ.ㅜ

그리고 다음지도에서 검색이 됬다는 것은 주소가 아니라 장소검색 결과로써
장소에 매핑되어 있는 주소들이 표시가 되는 것입니다. 즉 행자부와 지번주소가 다르다는 것은 장소에 매핑된 주소가 다른 것으로 이건 해당 부서에 요청 넣어 두도록 하겠습니다.

<장소검색결과>
![2017-05-11 5 42 40](https://cloud.githubusercontent.com/assets/20675065/25940523/5fb179e4-3671-11e7-8b67-8d2e94d79bf5.png)
<주소검색결과> - 데이터 없음
![2017-05-11 5 42 47](https://cloud.githubusercontent.com/assets/20675065/25940527/61bc13b6-3671-11e7-84c7-4cb693623e58.png)

감사합니다.
