### ISSUE TITLE
주소 확인 요청

### ISSUE THREAD

**Issue by bird3325** [daumPostcode/QnA#152]
안녕하세요.

주소 : 경기 화성시 청계동 510-60

위의 주소로 다음 페이지에서 검색하면 확인이 되는데..

우편주소 api 에서 검색을 하면 노출되지 않습니다.

확인 바랍니다.

**Comment by daumPostcode** [comment]
@bird3325 

네~ 안녕하세요~

다음포탈의 검색은 주소 검색이며, 우편번호 api는 우편번호 검색입니다.
우편번호는 2015년 8월에 갱신된 5자리 기초구역번호를 우편번호라 지칭하며, 해당 기초구역번호는 도로명 주소가 발급된 주소에만 발급이 됩니다.

현재 행자부 사이트에서 검색해본결과
![2017-05-12 5 54 07](https://cloud.githubusercontent.com/assets/20675065/25990842/2cda70fe-373c-11e7-82ba-8b4d272918e3.png)

검색 결과가 없네요. 고객지원 들어가셔서 등록 요청이 필요할듯 합니다
(등록은 저희가 해드리지 못하며, 로그인이 필요한 페이지이므로 직접 하셔야 합니다)

추가적으로 행자부에서 검색이 된다하더라도, 행자부에서 저희쪽으로 데이터를 줄때, 저희가 보안주소라고 부르는 주소가 있는데, 이는 행자부사이트에서 검색시 지도마크가 없습니다. 이런 주소는 좌표값이 없어 저희가 지번주소와 매핑이 불가능 하여, 저희 서비스에서는 제외됨을 말씀드립니다. 이러한 주소는 대한민국 전체 주소중 0.03%정도 되니 참고 부탁드립니다.

감사합니다.
