### ISSUE TITLE
감계로 233 우편번호 추가요청

### ISSUE THREAD

**Issue by goodboys100** [daumPostcode/QnA#153]
도로명주소 : 경상남도 창원시 의창구 북면 감계로 233 (창원 감계 힐스테이트 4차)
지번 : 경상남도 창원시 의창구 북면 감계리 225-1 창원 감계 힐스테이트 4차

창원시 의창구 북면 감계로 233 이전글에서 추가되었다고 회신받았는데 현재 검색이 안되고있습니다.

재확인부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@goodboys100 

네~ 안녕하세요

넵; 해당 주소의 경우에도 이번 DB이관시 누락된 주소중에 하나입니다.
담당 부서에서 처리 진행 중에 있으니 잠시만 기다려 주세요..
불편을 드려 죄송합니다;

**Comment by daumPostcode** [comment]
@goodboys100 
안녕하세요~

금일부로 해당 주소 정상 반영되었습니다.

기다려 주셔서 감사합니다.
