### ISSUE TITLE
우편번호 검색창이 비어있는체로 뜹니다.

### ISSUE THREAD

**Issue by LeoSeongYongKim** [daumPostcode/QnA#154]
안녕하세요.
지금 사이트에서 daum 우편번호API 를 사용하고 있습니다. 
좀전에 사용자가 우편번호 검색창이 비어 있는체로 뜬다는 이슈를 보냈었습니다. 
개발 환경에서 재현하기 어려운 상황이라 조금이나마 도움이 되는 해결 방법을 알수 있는지 해서 문의 드립니다. 
팝업 호출 방식은 js: new daum.Postcode({}) 방식 이구요 
참조된 js 파일은"http://dmaps.daum.net/map_js_init/postcode.v2.js"   입니다. 

duam  개발자 게시판에서 "document.domain" 에 대한 답변 봤습니다. 
document.domain 을 임의로 셋팅 한다는 게 무슨 뜻인가요 ? 
사이트에서는 document.domain 을 셋팅하긴 했습니다. 
@daumPostcode 

답변 부탁 드립니다. 
감사합니다.

**Comment by daumPostcode** [comment]
@LeoSeongYongKim 
네~ 안녕하세요~

document.domain값을 셋팅하더라도, 일부 IE계열 말고는 정상적으로 동작이 됩니다. 그래서 확인이 어려웠던 것인데요.
저희 [FAQ 13번](https://github.com/daumPostcode/QnA#13-팝업창이-비어-있는-채로-뜹니다)에 적혀 있습니다.

현재 저희는 이종도메인간 통신을 위해 postMessage를 이용하는데요. postMessage함수의 Cross-Browsing 문제를 해결하기 위해 도입한 iframe객체의 window.document.write함수를 이용하고 있습니다.
다만 이 함수를 사용할때 부모페이지의 document.domain값이 공백이나 다른 값으로 셋팅을 하면(실제 도메인과 같은 값으로 해도 마찬가지) 저 함수를 접근할 수 없다는 오류메세지와 함께 화면에 아무 것도 그려지지 않아, 힌색으로 나오게 됩니다. 
현재 해당 이슈는 기술적으로 해결이 불가능 하여, 이용하시는 고객님의 사이트 페이지에서 저희 우편번호 서비스를 이용하시려면 document.domain을 셋팅하는 코드를 주석처리 또는 제거하셔야 합니다.

도움이 되셨으면 하네요;;

**Comment by LeoSeongYongKim** [comment]
빠른 답변 감사합니다. ~
