### ISSUE TITLE
감천로 55-57 우편번호 추가 요청

### ISSUE THREAD

**Issue by re245** [daumPostcode/QnA#155]
도로명: 감천로 55-57 충경마을 2단지 / 구:감성리 523-1

행정자치부 검색시스템에서는 등록이 되어있으며
이 부분 추가 요청드립니다.

등록되면 회신 가능할까요?

**Comment by daumPostcode** [comment]
@re245 
네~ 안녕하세요

말씀해주신 주소의 경우 저희에게 행자부가 데이터를 줄때 좌표값을 주지 않는 주소로
해당 주소는 매핑이 불가능하여 우편번호 서비스에서는 제외되고 있는 주소입니다.

보통 좌표값을 주지 않는 주소의 경우, 국가 보안 시설이거나, 도로명 주소는 발급되어 있지만 건물이 없는 상태 등 예외 케이스들이 있습니다. 

이러한 주소는 대한민국 전체 주소중 0.03%정도 차지하고 있는데요, 저희 CS로 이러한 주소의 등록 요청이 자주 들어오지만, 현재 저희 우편번호와 주소 검색 시스템 상에서는 해당 주소를 보여드리기가 힘든 점 말씀드립니다;;

도움을 드리지 못해 죄송합니다.

덧붙혀 이러한 주소는 행자부사이트에서 검색해 보시면, 검색 결과의 새우편번호 우측에 지도마커 버튼이 없습니다.
