### ISSUE TITLE
 여수시 봉강서3길 7-1 추가 요청

### ISSUE THREAD

**Issue by epan0824** [daumPostcode/QnA#156]
도로명주소 : 전라남도 여수시 봉강서3길 7-1(봉강동) 
지번 : 전라남도 여수시 봉강동 576-14 

행자부에서 확인 가능한 주소 입니다.
빠른 확인 부탁드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@epan0824 
네~ 안녕하세요~

해당 주소의 경우 이전 DB이전시  누락된 주소로써, 현재 담당 부서에서 복구 중입니다.

초기 예상한 것과 다르게 시일이 좀 걸리고 있는데요;; 잠시만 기다려 주세요 ㅜ.ㅜ

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@epan0824 
안녕하세요

금일부로 말씀하신 주소 정상 반영 되었습니다.

기다려 주셔서 감사합니다.
