### ISSUE TITLE
익스에서 빈창 뜨는데요

### ISSUE THREAD

**Issue by truckmania** [daumPostcode/QnA#157]
팝업창이 비어 있는 채로 뜰때 document.domain 을 쓰지 않나 확인하라 되있는데 그런거 안쓰고 있습니다.
현재 익스 버전은 11입니다.
사무실내 다른 pc에서도 익스에선 안뜹니다.
또 한가지 http://postcode.map.daum.net/guide  이 페이지도 스크립트 소스 부분이 안보입니다.
즉 서버특성을 가리는게 아니라 api나 css문제일 가능성이 많아 보입니다.
엣지나 크롬 파복등 익스 이외의 다른 브라우저에서는 http://postcode.map.daum.net/guide 에서의 소스도 다 보이고 api창도 잘 되는데 익스에서만 안되는 상황입니다.
익스에서 http://postcode.map.daum.net/guide 열어보시면 바로 확인되실꺼라 보여집니다.

![- -1](https://cloud.githubusercontent.com/assets/21230823/26383321/126da814-406d-11e7-9cc3-1329e77b2069.jpg)

**Comment by daumPostcode** [comment]
@truckmania 
네 안녕하세요~~

IE 11, (이하 익스)에서 가이드 페이지의 오류 및, 팝업창 오류를 말씀해 주셨는데요.
음.. 말씀하신 것처럼 IE11에서 현재 확인을 해봤지만 딱히 다른 오류가 보이지 않습니다.

![2017-05-24 10 34 43](https://cloud.githubusercontent.com/assets/20675065/26383276/deb025ec-406c-11e7-8273-d4fbbbf7a9cf.png)
![2017-05-24 10 35 20](https://cloud.githubusercontent.com/assets/20675065/26383280/e2348154-406c-11e7-89f7-53a7f228ca8c.png)
![2017-05-24 10 35 44](https://cloud.githubusercontent.com/assets/20675065/26383288/ea2bf7de-406c-11e7-9ad9-2eea3eff4715.png)
![2017-05-24 10 37 48](https://cloud.githubusercontent.com/assets/20675065/26383320/123e1b26-406d-11e7-9100-89679319e273.png)

위 스샷처럼, 현재 IE11에서 모두 정상 동작하고 있는 것으로 확인이 되는데요.
혹시 IE에서 테스트 할시, 개발자 도구를 열어서 오류메세지가 출력된다면 알려주실 수 있으실까요?
느낌으로는 현재 스타일보다는 스크립트를 로딩하지 못한 것 같은데요. 
혹시  dmaps.daum.net이나 s1.daumcdn.net 도메인이 블락된게 아닌가 싶네요;; 혹시 인트라넷 환경이신가요??

아무튼 오류메세지가 뜬다면 오류메세지를 캡쳐해서 올려주시면 좀더 확인이 될것 같습니다.

**Comment by truckmania** [comment]
헐....광고때문에 daumcdn.net 을 차단한게 있는게 그거 때문에 스크립트 실행이 안되었네요
스크립트가 daumcdn.net 에서 돌아가는게 있나봅니다

**Comment by daumPostcode** [comment]
@truckmania

아;; 넵; 그럼 혹시 말씀하신 부분을 해결하면 처리가 되는 사항일까요? ㅎㅎ

다른 문제가 있으시면 댓글 주시면 확인하도록 하겠습니다~

즐거운 하루 보내세요~~
