### ISSUE TITLE
주소추가요청

### ISSUE THREAD

**Issue by goodboys100** [daumPostcode/QnA#159]
- 도로명주소지 : 경기도 의정부시 평화로 125
 - 지번주소지 : 경기도 의정부시 호원동 468-8

주소추가요청드립니다. 
행자부에서는 조회되고있습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@goodboys100 
네~ 안녕하세요~

해당 주소는 미고시 상태로, 오로지 행자부 사이트에서만 검색이 되는 주소이며, 고시가 안된 주소이기 때문에 저희 시스템에선 검색이 안되는게 맞습니다. 검색결과의 "미고시" 부분에 마우스 올려보시면 설명이 나오며, 추후 고시가 될경우, 저희 시스템에 자동으로 등록 됩니다. 이점 참고해주시기 바랍니다.

![2017-05-30 10 18 57](https://cloud.githubusercontent.com/assets/20675065/26564902/6bed34d2-4521-11e7-925c-ac930929cf1e.png)

감사합니다.
