### ISSUE TITLE
"용두리 752"에 매칭되는 도로명데이터가 없습니다.

### ISSUE THREAD

**Issue by palbook27** [daumPostcode/QnA#16]
안녕하세요. 다음 API를 잘 쓰고있는 사용자중 한명입니다.
사용중에 이상한 데이터가 있어 문의글 올립니다.

-다음API이용 결과값
![default](https://cloud.githubusercontent.com/assets/16376797/18259374/522ea564-741e-11e6-8676-e5842935a79d.JPG)
-다음API이용 검색
![default](https://cloud.githubusercontent.com/assets/16376797/18259376/5230e950-741e-11e6-9154-bc994d836519.JPG)
-도로명새주소검색
![default](https://cloud.githubusercontent.com/assets/16376797/18259375/522f944c-741e-11e6-8489-2d07ff8fe200.JPG)

위에보시는것처럼 용두리 752로 검색을 한 후에
[경기 안성시 공도읍 용두리]를 클릭할 경우
도로명(roadAddress)데이터가 없습니다.
혹시 도로명이없는 주소인가 해서 도로명새주소에서 검색을 해보니
그곳에서는 데이터가 있더군요..

유저입장에서는 다음 검색에 결과값이 나오는 부분이 다 같다라고 판단하고
지번을 누르던 도로명을 누르던 도로명이 입력되도록 설정을 해놔서 결과값이
위와같이 누락이 될경우 곤란한 부분이 있습니다.

이렇게 검색한 결과에서 지번과 도로명이 묶음으로 있는 경우에도 도로명주소가
안올경우 어떻게 처리해야할지.... 문의드립니다.

**Comment by daumPostcode** [comment]
@palbook27 
네~ 안녕하세요~

저희 FAQ와 가이드 페이지를 참고해 보시는게 좋을 것 같아요~ 

지번:도로명 주소가 1:N인 경우에; 이용자가 지번주소를 선택을 하면 도로명 주소가 roadAddress에 무조건 들어가지 않습니다. 말그대로 도로명을 선택안하고 지번을 선택했기 때문에 roadAddress에 들어가지 않는 것이구요, 다만 이용자가 선택하지 않은 주소라도 도로명 주소가 필요한 경우, 1:N일때 첫번째 매핑된 도로명 주소의 경우 auroRoadAddress라는 변수에 들어가게 됩니다. (이와 반대 격인 autoJibunAddress도 있습니다.)

이부분은 저희 FAQ와 가이드페이지에 상세히 설명되어 있기 때문에 참고해 주시면 감사하겠습니다.

[가이드 페이지 상세 설명](http://postcode.map.daum.net/guide#attributes) 속성 부분 설명 중에 스크롤을 조금 내려보시면 autoRoadAddress, autoJibunAddress에 관한 설명이 있으니 참고 부탁드립니다.

또한 

[FAQ 16번](https://github.com/daumPostcode/QnA#16-사용자가-지번도로명-중-어떤-것을-선택하더라도-무조건-도로명-주소만-이용하고-싶은데-어떻게-해야되나요) 를 읽어보시면 이용하는 방법도 아실 수 있을 거에요~

**Comment by palbook27** [comment]
아 새로 업데이트가 된 내용이였군요 감사합니다!

**Comment by daumPostcode** [comment]
@palbook27 
ㅎㅎ 도움이 되셨다니 다행이네요 ^^ 그런데 최근에 업데이트 된건 아니구,, 작년 초부터 있었던 기능인데 홍보가 부족했나 보군요 ㅜㅜ

아무튼 저희 API를 이용해 주셔서 감사합니다 ^^
