### ISSUE TITLE
해당 지번이 다르게 나옵니다.

### ISSUE THREAD

**Issue by Happy2You** [daumPostcode/QnA#160]
**역삼동 735-3으로 검색**을 하게 되면..

data.buildingCode 값이 
1168010100107350005028032 이렇게 나오는데요..

중간게..  지번이 나오는 구간인..
0735 0005 이렇게 나옵니다. 

분명 735-3 이니까.... 0735 0003 나와야 하는데 말이죠..
신기하게 테스트 해보는 지번에 문제가 있네요.. -_-;

수고하세요~~

**Comment by daumPostcode** [comment]
@Happy2You 

네~ 안녕하세요~~

데이터 이슈의 경우 제가 바로 확인이 어려워, 데이터 담당자 분께 전달드리도록 하겠습니다~

처리 결과는 이 이슈의 댓글로 알려드리도록 할께요~

제보 감사드립니다^^

**Comment by daumPostcode** [comment]
@Happy2You 
안녕하세요~~
데이터 담당자 분께 답변을 받았는데요~~

말씀하신 buildingCode의 경우 건물관리번호로 각 건물을 구분하는 고유의 값입니다.
그리고 최초 건물관리번호가 생성될때는 해당 지번주소를 참고하여 생성이 되지만,
이후 지번이 변경되거나 할때는 건물관리번호에 반영이 되지 않습니다.

즉 해당 주소는 최초에 buildingCode가 생성될당시 735-5였을 것으로 보이며, 이후에 주소가 변경된 것으로 보입니다.

그렇기 때문에 건물관리번호의 지번 부분을 추출하여 사용하시면, 실제 지번과 다를 수 있으니 참고하시기 바랍니다.

그럼 즐거운 하루 보내세요~

**Comment by Happy2You** [comment]
아쉽네요.... 
앞으로도 건물관리번호 사용이 어렵겠지요? 
일반 지번주소에서 가져오는 방법으로 해봐야 겠네요.. 

빠른 답변 감사합니다.
