### ISSUE TITLE
카카오톡 및 일부 앱 인앱 브라우저에서 팝업이 열리지 않는 문제

### ISSUE THREAD

**Issue by itsnothingg** [daumPostcode/QnA#161]
안녕하세요.
모든 issue들에 친절하게 답변 남겨주시는 것 같아서 저도 하나 남깁니다. ㅎㅎ

제목처럼 카카오톡 및 일부 앱 인앱 브라우저에서 팝업이 열리지 않는 문제가 발생하고 있는데요 (특히 IOS),
QnA 9,10 번에서 설명해주신 것처럼 웹 페이지가 아니라 네이티브 웹뷰 쪽에서 액션을 취해야 하는 문제라고 이해하고 있습니다.
이와같이 webview 쪽에 소스에 손을 댈 수 없는 상황이라면 기존 popup 사용이 불가하고, iframe 방식으로 변경하는 것이 맞나요?

**Comment by daumPostcode** [comment]
@itsnothingg 
안녕하세요~

워크샵 및, 개인 사정때문에;; 이슈 확인이 늦었네요;; 죄송합니다 ㅜ.ㅜ

네; 맞습니다. 안드로이드도 마찬가지 입니다만, iOS에서 유독 더 심한데, 네, 웹뷰를 커스터마이징 하기가 어려운 상태라면, popup사용은 어려우며, iframe방식을 사용하시는게 좋아보입니다.

모바일 환경의 경우, safari나 chrome에서의 사용보다, 앱에서의 웹뷰를 통한 접근도 많은데, 현재 window.open의 경우 webview에서 이에 대한 처리를 해주지 않는이상 팝업이 열리질 않다보니 발생하는 문제입니다.

그래서 모바일 환경에서는 iframe을 이용한 레이어나 끼워넣는 방식 (가이드 페이지 샘플 참고)을 더 추천드립니다.

이외 다른 질문 있으시면 댓글 부탁드려요~
