### ISSUE TITLE
redux에서는

### ISSUE THREAD

**Issue by kiseok04111** [daumPostcode/QnA#162]
어떤식으로 써야할까요?

**Comment by daumPostcode** [comment]
@kiseok04111 
네~ 안녕하세요~

네. 특정 프레임워크 위에서 동작하게끔 하는 것은 직접 테스트를 해보셔야 되는데요..
일단 제가 redux를 그렇게 많이 사용한 것은 아니나, redux는 어플리케이션의 데이터 흐름에 관련된 일련의 프로토콜 같은 개념으로 알고 있는데요.(이게 맞나요?) 라이브러리나 그런것은 이런 프로토콜을 구현한 구현체일 뿐이라고 알고 있습니다.

그리고 우편번호 서비스가 npm module 형식을 따르지 않기 때문에, 별도로 스크립트 로딩 부분을 페이지에 삽입하시고,
redux의 경우 react와 연동을 많이 하기 때문에 동적 렌더링 방식이므로, 저희 가이드페이지의 사용법중, "동적 로딩" 방식을 이용하시는 것을 추천드립니다.

이렇게 셋팅을 한뒤, 사용자가 우편번호 버튼을 클릭을 하면 특정 action이 발생할거고, 그에 따른 핸들러가 실행이 될건데요. 그 핸들러안에서 우편번호 서비스를 실행하고(팝업보다 embed를 통한 layer방식을 추천), 사용자로부터 받은 데이터를 다시 다른 action을 통해 넘겨주면 될 것 같네요. redux를 좀 예전에 건들다 보니 기억이 가물가물 해서 정확히 맞는 설명인지는 모르나, redux의 흐름에 맞게 데이터만 전달을 잘 시키면 되실 듯 합니다.

잘 적용되면 좋겟네요;;
