### ISSUE TITLE
웹으로 호스팅하지 않고 안드로이드와 데이터 통신이 가능한가요?

### ISSUE THREAD

**Issue by LeeSagoo** [daumPostcode/QnA#163]
html 로 다음 주소찾기를 만들고 안드로이드에서 이 html 을         wvAddress.loadUrl("file:///android_asset/address.html"); 이렇게 띄우는데 잘뜨긴하는데 
주소 선택했을때 안드로이드에서 JavascriptInterface 에 선언된 메서드를 호출하기로 되어있거든요? 
웹 호스팅할때는 되는데 html 파일만 읽어들일때는 호출이 안됩니다. 
원래 안되는건가요?

**Comment by daumPostcode** [comment]
@LeeSagoo 
네. 안녕하세요~

원래 그런게 맞습니다.
저희 서비스 자체가 웹 기반서비스이며, 별도의 standalone방식으로 띄우는 것은 지원을 하지 않습니다.
이는 내부적으로 CORS통신을 하다보니 사용된 API때문에 발생한 문제로, 현재 static하게 파일을 읽어서 실행을 하는 방식을 공식 지원할 생각은 없습니다.

불편하시더라도 웹호스팅을 사용하시거나, 아니면, postcodify나 행정자치부에서도 데이터를 제공하는데, 이렇게 데이터만 받고 직접 뷰를 제작하시는게 좋아보입니다.

**Comment by wonsuc** [comment]
서버리스 클라이언트앱들이 늘어나는 추세에서 지도API를 위해서 호스팅 서버를 연동해야 한다는건 모바일 클라이언트 개발자 입장에서 그렇게 매력적으로 느껴지지는 않네요. URL parameter 형식으로 웹뷰에서 바로 로드에서 사용할 수 있다면 정말 좋을거 같은데 feature request는 따로 안받으시나요?

**Comment by daumPostcode** [comment]
@wonsuc 

네. 안녕하세요~

초기 오픈때도 그랬지만, 현재까지도 우편번호 서비스는 웹서비스로만 제공을 할 계획입니다.

서비스 목적이 매일 매일 업데이트 되는 도로명주소를 직접 관리하지 않으셔도, 홈페이지(PC,mobile web)에 주소 검색기능을 쉽게 붙힐 수 있도록 하는 것에 초점을 두고 개발을 하고 운영을 하고 있습니다. 말씀하신 기능은 현재 공식적으로 지원할 계획은 없습니다.

말씀하신. URL parameter로 실제 검색 페이지를 띄우는 것은 지금이라도 개발자분이시라면 쉽게 가능하실거에요. 왜냐하면 따로 인증키도 존재하지 않고, JS API의 경우 실제 서비스 화면을 띄우는 역할과 데이터 통로 역할만 할뿐, 검색 화면은 다른 페이지거든요. 

다만 공식지원 사항이 아니고 권장하는 방법이 아니므로 
이렇게 검색화면에 직접 접근하면 어뷰징으로 기록될 요소가 크며, 또한 클라이언트 페이지에 주소 데이터가 전달되지 않습니다.(물론 제가 앱개발자가 아니라 다른 방법이 있을 수도 있지만요..)

그래서, 모바일앱에서 이용하실 분께서는 저희 서비스는 아니지만, 저희가 데이터를 받고 있는 행자부 도로명 검색 시스템(juso.go.kr)의 REST API나 postcodify(https://www.poesis.org/postcodify/)를 이용해서 개발하시는게 더 좋아 보입니다.

지원해 드리지 못해 죄송합니다.
