### ISSUE TITLE
우편번호 서비스 접속하는 주소 확인부탁드립니다.

### ISSUE THREAD

**Issue by songhc** [daumPostcode/QnA#164]
페쇠망에서 우편번호 서비스만 사용하기 위해 방화벽에 추가할 예정입니다.

해당 서비스에 접속하기 위해 필요한 도메인주소나 IP주소 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@reedfim 
네~ 안녕하세요~

폐쇄망에서 사용하시는 것은 저희가 공식적으로 안내해 드리는 사항은 아닙니다.
실제 도메인의 경우, 외부에 다 노출되어 있기 때문에, 편의를 드리고자 정리만 해서 드리는 것이구요.

IP는 직접 알아보셔서 하셔야 합니다. 또한 IP는 중간에 바뀔 수도 있으며, 도메인의 경우도 추가 및 변경이 될 수도 있습니다. 또한 현재 http://sughub.search.daum.net <- 이 도메인의 경우 변경 예정에 있으며, 변경이 완료되면 이 이슈에 추가 댓글로 알려드리도록 하겠습니다.

다만, 이후에 변경되거나 추가되는 건에는 바로바로 알려드리기가 어려운점 양해 부탁드립니다.

아래는 도메인 리스트입니다.

```
HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://stlog1.local.daum.net 
- http://sughub.search.daum.net
- http://t1.daumcdn.net

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://s1.daumcdn.net 
- https://sughub.search.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net
```

**Comment by daumPostcode** [comment]
@songhc 
그제 댓글을 봐보니 멘션을 잘못 달았네요;;

http/https환경 모두 도메인이 변경되어 공유 드립니다.
```
sughub.search.daum.net -> suggest-bar.daum.net
```
으로 변경되었습니다. 참고 부탁드립니다.
