### ISSUE TITLE
콤보박스 형태로 나오게 할 수 는 없을까요??

### ISSUE THREAD

**Issue by elfin21c** [daumPostcode/QnA#165]
도로명이나 동이름을 입력폼에 입력하면 
조건에 맞는 지역이 리스트로 나오고 있는데요..

시도 , 시군구, 동 을  콤보박스 형태로 나오게 해서 3단계를 선택하면 나머지 상세주소에 해당되는
지역이 리스트로 나오게 할 수는 없을까요?

**Comment by daumPostcode** [comment]
@elfin21c 
네~ 안녕하세요~

네; 현재 시도/시군구/동 을 선택하여 필터링을 하거나, 검색을 하는 기능은 없습니다;
또한 말씀하신 타이밍 단계에서 나오는 서제스트의 경우도 마찬가지로 현재는 기능이 없습니다.

아쉽지만, 행자부에서 데이터를 직접 받으셔서 UI를 직접 개발을 하시는 방법이 제일 좋아보이며,

저희껄 이용하는 방법으로는, 시도/시군구/동과 상세주소를 elfin님 사이트에서 입력받고,
저희 API를 띄울때 open({q:"xxxx"}), embed({q:'xxxx'})를 이용하여 실행시 쿼리를 바로 보낼 수 있는 기능을 이용하시는 방법이 있으나, 검색화면에서 필터링이 되는 것은 아니므로 반쪽짜리 사용같긴 하네요;;;

도움을 드리지 못해 죄송합니다;;
