### ISSUE TITLE
우편번호와 주로를 return 하고 싶습니다.

### ISSUE THREAD

**Issue by KimBoHyeon** [daumPostcode/QnA#166]
안녕하세요. 
웹프로그램 초보 입니다. 
다름이 아니라 함수로 만들어서 호출해서 사용자가 선택한 값을 리턴하고 싶은데... 잘 안되네요.
제가 아직 실력이 많이 부족하가 봐요 ㅠㅠ 
아래 처럼 함수로 만들어서 s_Addr 에 값을 할당해서 리턴하고 싶습니다. 

감사합니다.

		    function DaumPostcode() {
		    	
		    	var s_Addr = "";
		    	
		    	new daum.Postcode({
		            oncomplete: function(data) {
		                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

		                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
		                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
		                var fullAddr = ''; // 최종 주소 변수
		                var extraAddr = ''; // 조합형 주소 변수

		                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
		                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
		                    fullAddr = data.roadAddress;

		                } else { // 사용자가 지번 주소를 선택했을 경우(J)
		                    fullAddr = data.jibunAddress;
		                }

		                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
		                if(data.userSelectedType === 'R'){
		                    //법정동명이 있을 경우 추가한다.
		                    if(data.bname !== ''){
		                        extraAddr += data.bname;
		                    }
		                    // 건물명이 있을 경우 추가한다.
		                    if(data.buildingName !== ''){
		                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
		                    }
		                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
		                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
		                }

		                // 우편번호와 주소 정보를 해당 필드에 넣는다.
//		                data.zonecode; //5자리 새우편번호 사용
//		                fullAddr;			                
		                		                
		            }
		        } ).open();			        
		        
		        return s_Addr;
		    }

**Comment by daumPostcode** [comment]
@KimBoHyeon 
네~ 안녕하세요~ 

해당 방식은 서로 실행되는 타이밍이 달라 어렵습니다 ㅎ
쉽게 설명드리면

```
function a() {
   
   var temp = 10;
   setTimeout(function() {
      temp = 100;
   }, 1000);
   
   return temp;
}

a();  //  10이 출력됨
```

위 코드처럼 함수 a와 내부의 setTImeout의 인자로 실행되는 함수는 서로 생명주기가 다릅니다. 그렇기 때문에 setTimeout에 들어가 있는 함수에서 temp에 값을 할당해도 a함수는 이전에 실행을 끝냈기 때문에 값을 정상적으로 받을 수 없습니다.

즉, 저희 API에서도 oncomplete함수느 위 코드의 setTimeout에 들어가 있는 익명함수와 같다고 보시면 되는데요.
oncomplete함수는 유저가 주소를 선택할때 실행이 되기 때문에 언제 실행 될지 알 수 없습니다.

이런 경우에는 여러가지 방법이 존재하나 제일 쉬운 해결책 중 하나가 콜백함수를 사용하는 것으로, 이벤트 핸들러를 등록해 보셨으면 바로 아실거에요~ 그렇게 이용하시면 됩니다.

```
function daumPostcode( cb ) {

   new daum.Postcode({
       oncomplete : function (data) {
            ............
            var s_addr = fullAddr;
            cb(s_addr); // 따로 바인딩 객체가 필요하다면 cb.call or cb.apply 사용
       }
   };
}


//사용시
daumPostcode(function(s_addr){
    
   //우편번호 서비스에서 사용자가 주소를 선택한 순간, 이 익명함수가 실행이 됩니다.
   var address = s_addr;
   .....................
   // 즉, 이 함수가 실행될때 s_addr변수에 담겨진 주소를 활용하여 실제 하고 싶은 작업을 여기서 하시면 됩니다.
});
```

위 코드가 제일 쉬운 해결책이며, promise관련된 부분을 참고해서 만드셔도 됩니다.

참고해 보세요~~~ 그럼 즐거운 하루 보내세요~~
