### ISSUE TITLE
우편번호 api 서비스가 중단 될수도 있나요?

### ISSUE THREAD

**Issue by sgkim81** [daumPostcode/QnA#167]
다음API 쪽 서버 문제라든지, 어떤 특수한 상황 때문에 API를 이용 못하는 경우가 생길수 있을까요?

**Comment by daumPostcode** [comment]
@sgkim81 

네~ 안녕하세요~

넵;; 최대한 1년 365일 장애 없이 유지를 하려고 최대한 노력하고 있습니다만, 데이터와 검색엔진 api서버 등이 얽혀 있어서; 가끔, 장애가 발생할 수는 있습니다.
사람이 만드는거라 이해해 주셨으면 좋겠구요;;

다만, 장애가 발생하더라도, 최대한 빠르게 수정 복구 할 것을 약속 드리며, 장애 발생시; 제가 카톡 플러스친구로 발송해 드리니 참고 하시면 될 것 같습니다. (플러스 친구 등록방법은 가이드 페이지 하단 참고)

현재 4년간 운영중이지만, 장애상황은 정확히 기억이 안납니다만 3번 정도 있었던 것 같아요;; 
만약 3번이라도, 장애 한번에 sgkim81님의 서비스가 큰 손실을 얻을 수도 있기 때문에, 이런 장애에 민감하시거나, 해당 장애나 기타 예외처리도 직접 컨트롤 하고 싶으시다면, 저희 API보다는 직접 행자부에서 데이터를 받아서 구성하시는게 더 좋아보입니다. 개발자로써,, 장애가 터졌을때 직접 컨트롤 하지 못하는 것도 참 힘든일임을 알기에;;

아무튼 최대한 안정적으로 서비스가 될 수 있도록 노력하겠습니다.

감사합니다.
