### ISSUE TITLE
API에서 가져온 주소와 상세주소사이에 공백 삽입

### ISSUE THREAD

**Issue by seoswan** [daumPostcode/QnA#168]
API에서 가져온 주소와 상세주소사이에 공백 삽입 방법 부탁드립니다.
자바스크립트로 해결해야 하는데..어렵네요.

기존 사이트에 db구조로 인해,  api에서 가져온 주소값과 상세주소를 합해서 db에 넣어야 해서 form 태그 하나 추가하고
 <input  TYPE="hidden" name="homeaddr"   type="text" id="homeaddr" value="">

api에서 가져온 값을 합하기위해 스크립트 삽입

	  var f = document.form; 
          f.homeaddr.value = f.homeaddr1.value + f.homeaddr2.value;
 	form.submit();

여기까지는 잘되는데.. 두 값 사이에 공백을 넣으려니.... 실력이 안됩니다. 좋은 방법있을까요?

**Comment by daumPostcode** [comment]
@seoswan 

네~ 안녕하세요~

f.homeaddr1.value <- 이게 저희 서비스에서 가져온 주소 데이터
f.homeaddr2.value <- 이게 사용자가 입력한 상세 주소라면

f.homeaddr1.value + ' ' + f.homeaddr2.value <- 이렇게 하면 공백이 들어갈 것 같긴합니다......

17시간전에 질문 주신건데;; 메일이 이상한지 푸시가 좀 늦게 왔네요;;;

이미 해결하셨을 것 같은데, 다른 이슈라면 질문 또 주세요~~

**Comment by seoswan** [comment]
감사합니다. 아주 간단한걸 초보는 힘겨워하네요..
API 쓰는 분들중 몇몇 분은... 이미 제작된 쇼핑몰의 주소입력을 도로명 주소로 바꾸려고 시도하겠지요..
저같이 말입니다.(저는 프로그램이 전문이 아니라... 기획쪽이라.. ㅎ)

8~9년전 이런 API를 만들어 사업해보면 좋겠다고... 사업계획서를 썻던 기억이 나네요.
당시에 이런 서비스를 필요로 하는 쇼핑몰/웹사이트가 상당히 많아...임대형으로 돌리기만 해도 해볼만하겠다 싶었지요.
당시 조사했을때는 도로명 주소의 DB가 지번DB와는 많이 달라 DB잘못짜면 쿼리 응답에 상당한 무리가 갈것으로 생각했지요..ㅎㅎ 어쨋든..

좋은 서비스 해주셔서 감사드립니다.

**Comment by daumPostcode** [comment]
@seoswan 
ㅎㅎ 별말씀을요~
잘 해결되셨다니 다행입니다~^^

저희가 서비스 한지 4년째인데, 8~9년전에 고민하셨다니 ㅎㅎ 선배님이시네요 ㅎㅎ

아무튼 운영하시는 서비스에 차질이 발생하지 않게, 최선을 다해 운영하겠습니다.

감사합니다~.

즐거운 하루 보내세요~~
