### ISSUE TITLE
해외IP도 접속이 가능한가요?

### ISSUE THREAD

**Issue by ghost** [daumPostcode/QnA#169]
웹 서버가 해외에 있는 경우에도 사용이 가능한가요?

**Comment by daumPostcode** [comment]
@Tkdlajs 

네; 따로 네트워크 제한을 걸진 않습니다.
인터넷 접속만 가능하다면 이용 가능하십니다.

만약 안되시면 댓글 달아주세요. 확인해 보도록 하겠습니다.
