### ISSUE TITLE
문의 및 건의(title관련)

### ISSUE THREAD

**Issue by palbook27** [daumPostcode/QnA#17]
안녕하세요 추가적으로 문의하나 드립니다.

![default](https://cloud.githubusercontent.com/assets/16376797/18299767/763342fe-74fe-11e6-83cf-d2a1db3c9b29.jpg)

위에 보시는바와 같이 다음검색창을 오픈 했을경우
URL이 노출이 되는 부분이 있는데
이를 수정하고싶어 문의글 올립니다.

저희 사이트경우 유저가 직접적으로 주소를 입력하지 않고
창구에서 손님의 주소를 듣고 입력한 후에 검색을 하는 방식이라
지번주소:도로명주소가 1:N 일경우 간접적으로 주소를 알고있는 유저가
주소를 선택하는 방식이여서 주소검색 후 도로명을 클릭해주세요 라는
내용을 명시해줘야하는데 팝업창을 제어할 수 없어 타이틀을 활용하려고합니다.

타이틀을 수정 할 수 있는지 문의드립니다.

**Comment by daumPostcode** [comment]
@palbook27 
네~ 안녕하세요~

일담 답변을 드리자면, open()을 이용한 팝업형식의 경우 타이틀을 수정할 수 없습니다.

올려주신 스샷처럼 주소가 뜨는 경우도 있지만, 브라우저마다 표현되는 형식이 다릅니다.
예를 들어 크롬은 아래와 같습니다.
![2016-09-07 1 44 18](https://cloud.githubusercontent.com/assets/20675065/18300118/41f480ae-7501-11e6-8b80-aade6a2048f9.png)

또한 팝업창의 주소가 표시되는 것은 브라우저 자체의 보안적인 측면입니다. 사용자로 하여금, 현재 이 팝업의 소스가 어디인지 확인할 수 있게끔 해주는 최소한의 장치라고 알고 있어요~ 또한 실제 스크립트를 통해 title을 수정한다해도 IE버전에 따라 표시가 되는 버전이 있고 그렇지 않은 버전도 있습니다.

일단 palbook27님게서 타이틀을 제어하고 싶으신 경우에는 저희 API를 살짝 응용하셔야 합니다.
팝업자체는 palbook27님께서 만드시고, 그 팝업안에서 저희 우편번호 서비스를 embed()를 이용한 레이어 형태로 꽉차는 형태로 띄웁니다. 그리고 주소검색 후 선택을 하면, 팝업쪽에서 데이터를 받게 되는데, 이 데이터를, opener를 통해서 부모페이지로 보내는 방식으로 처리하시면 됩니다.

**Comment by palbook27** [comment]
넵 감사합니다 ^^
