### ISSUE TITLE
flex와 연동되나요

### ISSUE THREAD

**Issue by ten2ng** [daumPostcode/QnA#170]
flex랑 주소검색api가 연동되나요??
시도해봤는데 파라메타 넘기는 과정에서 잘안되네요 ㅠㅠ

**Comment by daumPostcode** [comment]
@ten2ng 
네~ 안녕하세요~

flex가 CSS관련 라이브러리인가요?? 
아니면 adobe flex?
아니면 react의 데이터 흐름을 정의하는 flux?

정확히 어떤 것인지 모르나,, 위 3개를 이용해서 응용 프로그램을 만들어 본적이 없어서 확답을 드리기가 어렵네요;;

말씀드릴 순 있는것은 우편번호JS API는 웹에서의 javascript를 사용하는 기본적인 사용방법을 따르고 있으며
script태그를 이용해서 api를 로딩한 후, new daum.Postcode생성자를 통해서 실행하실 수 있습니다.
다만 저희 가이드 페이지를 보시면, 기본 사용법에, 정적로딩 방식과 동적로딩 방식이 있는데,
보통 웹앱을 만드시는 경우를 생각해보면 SPA로 동적로딩 방식을 사용하기 때문에 정적로딩 방식보다, 동적로딩 방식을 사용하심이 좋을 것 같습니다.

;;;동문서답 같지만 좀 더 자세히 적어주시면 좋을 것 같습니다.
