### ISSUE TITLE
주소가 축약형으로 나오지 않습니다.

### ISSUE THREAD

**Issue by chadolie** [daumPostcode/QnA#171]
안녕하세요

업무 시스템이 있습니다. 주소 입력을 다음API 이용하고 있구요

DB에 데이터가 이상하여 확인해보니

같은 화면의 주소API 파업을 오픈 하여

금오15길 29 로 검색하면 저희쪽은 경남으로 나오는데

다른곳에서는 경상남도로 나오는곳도 있습니다.

무슨 차이 인지요?

**Comment by daumPostcode** [comment]
@chadolie 

네~ 안녕하세요~

먼저 저희 가이드 페이지에 - http://postcode.map.daum.net/guide#attributes
shorthand라는 옵션이 있습니다. 이 옵션의 활성화 유무를 확인 부탁드립니다. 기본값은 true입니다.

또한 한가지 더 확인해 주셔야 될것이 있는데;
올해 초에 https용 JS API가, 캐싱 문제로 인하여, 도메인을 바꾸었습니다.
만약 적용하신 페이지의 스크립트 주소가 https://spi.maps.daum.net 으로 되어 있는지 확인 부탁드려요; 현재 https://ssl.daumcdn.net으로 변경되었으며, 이또한 저희 가이드페이지에서 확인 가능하십니다.

API주소를 변경후에 카톡으로 발송을 해드렸는데, 만약 못 받으셨다면, 저희 가이드 페이지 하단에 있는 안내사항을 참고하여 친구 등록을 해주시면 감사하겠습니다. 기능 추가 및 사용성에 관련된 버그픽스의 경우 발송해 드리고 있으니 참고 부탁드립니다.

그리고 마지막으로 접속하고 있는 브라우저의 캐시를 한번 삭제해주시면 좋을 것 같습니다.

불편을 드려 죄송합니다. 

위 해결책으로 한번 시도해 보시고, 해결이 되지 않는다면 다시 댓글 주시면 감사하겠습니다.
