### ISSUE TITLE
ie9에서 인식이 안됩니다.

### ISSUE THREAD

**Issue by kwakyeonbok** [daumPostcode/QnA#172]
ie9에서 daum이 정의되지 않았습니다.가 뜨는데
방법이 없을까요?
http://devmain.istockmall.com/member/regist_form.asp

**Comment by daumPostcode** [comment]
@kwakyeonbok 
안녕하세요~~

출근해서 확인해 보니;; 현재는 수정이 되신것 같네요;;

이외 다른 문제가 발생하면 언제든지 댓글 주세요~~

감사합니다

**Comment by kwakyeonbok** [comment]
제가 테스트는 하는 ie9에서만 그러나요.
아직 해결안됐는데 ㅠㅠ
오류: 'daum'이(가) 정의되지 않았습니다.  이와 같이 스크립트 오류 메시지가 뜨며
new daum.Postcode({ <- 이라인에서 에라가 뜹니다.

**Comment by daumPostcode** [comment]
@kwakyeonbok 
아 그래요?
제가 IE9으로 확인해봤을때 정상적으로 작동해서요;

'daum'이 정의 되지 않았다는 것은
```
http://dmaps.daum.net/map_js_init/postcode.v2.js
```
위 스크립트가 제대로 로딩이 되지 않았다는 것을 의미합니다. 
우편번호 JS API는 2단계로 스크립트를 불러옵니다.

위 URL로 한번, 이때 window.daum을 정의하게 됩니다
두번째로 실제 우편번호 서비스를 띄울 수 있는 core스크립트를 불러오게 됩니다. - 이게 불러온 후 daum.Postcode가 생기게 되죠.

다만 알려주신 오류에서는 daum 자체가 불러와지지 않았기 때문에, 위 스크립트 자체가 로딩이 안된 것이죠.

만약 다른 IE9에서는 동작하는데; kwakyeonbok 님의 컴터에서만 안된다면, IE를 전체 초기화 및 캐시를 지워보시기 바랍니다.;;;

![2017-06-27 11 14 17](https://user-images.githubusercontent.com/20675065/27567912-ccfc0ca8-5b29-11e7-94e6-cf0b13880e16.png)

보통 위 스크립트를 로딩하기 전에 스크립트 오류가 발생해서, 로딩이 블락됬을 수도 있는데;; 님 PC에서만 발생하는 것은 좀 이상하네요;;;;

일단 캐시와 초기화를 해보시길 권장합니다;;

**Comment by kwakyeonbok** [comment]
우선 캐시삭제와 "원래대로"를 해봤는데도 안되더라구요.
브라우저를 삭제 후 다시 해봐야겠습니다.
답변 감사합니다.
