### ISSUE TITLE
예제들에 대해서..

### ISSUE THREAD

**Issue by nappeni** [daumPostcode/QnA#173]
예제에 있는 코드를 복사하여 id값과 모든 값들을 예제 소스코드와 같게하여 사용했습니다.
그런데 선택한 주소가 텍스트박스에 들어가지지도 않고, 팝업창이 사라지지도 않습니다..

크롬과 네이버 웨일브라우저를 사용하고 있는데 둘다 같은 현상이 발생합니다.

혹시 브라우저 지원 문제인가요? 아니면 다른 코드를 더 추가해야합니까??

주소를 입력해서 검색하는 것 까지는 잘되는데
선택후 나가는 것이 안되네요..;;

**Comment by daumPostcode** [comment]
@nappeni 
네; 안녕하세요~

말씀해 주신 내용만 보면, 저희 [FAQ12](https://github.com/daumPostcode/QnA#12-팝업창에서-검색-후-결과를-클릭해도-반응이-없습니다) 번의 오류 같네요. 로컬 서버라도 띄우셔서 테스트 하셔야 하며, html 파일을 브라우저에서 정적으로 실행하실 경우 host정보를 알 수 없기 때문에 데이터 전달이 되지 않습니다.

이게 아니라면, 

가능한 실제 전체 코드 블럭과,
오류메세지를 첨부해 주시면 좋을 것 같습니다.

크롬으로 하신다면 개발자 도구가 잘 되어 있으니, 이걸로 확인하셔도 되나, 팝업형의 경우, 부모창과 팝업창 각각 확인해야하니, 테스트를 하실땐 레이어모드를 이용해서 테스트 하시는게 편하실 수 있습니다.
