### ISSUE TITLE
신촌세브란스 검색시 다음지도 서비스의 검색결과와 다른이유?

### ISSUE THREAD

**Issue by jeenmanbae** [daumPostcode/QnA#174]
신촌세브란스 라고 검색을 하면 "다음지도"에서는 연세대학교 세브란스병원이 나오는데
주소검색api 에서는 "신촌세브란스 어린이 집" 만 검색됩니다. 이외에도 "서울대"를 검색하거나
"인천대학교"등을 검색해도 결과가 상이한데요... 다른게 검색되는 이유가 있는지 알고싶습니다.

**Comment by daumPostcode** [comment]
@jeenmanbae 
네~ 안녕하세요~

그 차이는 검색 DB의 차이입니다.
다음 지도의 경우에는 위 말씀하신 신촌세브란스, 서울대 등으로 검색을 하면, 장소를 위주로 검색을 하게 됩니다.
즉 주소와는 별개로, 해당 쿼리가 들어간 장소를 위주로 검색을 하게 되는 것이죠.

반대로 저희 우편번호 서비스의 경우, 주소위주의 검색이며, 말씀하신 신촌세브란스, 서울대 등은 주소에 매핑된 건물명에 해당 쿼리가 들어가 있으면 검색이 되는 것이라고 보시면되요. 
장소DB에 있는 장소들의 이름이, 모든 주소의 건물명과 같지 않거든요. 

서로 검색하고자 하는 목표가 달라서 그렇다고 생각하시면 될거에욤~

다른 질문이 있으시면 언제든지 이슈 등록 해주세요~ 감사합니다.
