### ISSUE TITLE
팝업창의 결과값중 첫번째를 자동으로 선택되게하는방법

### ISSUE THREAD

**Issue by 1989v** [daumPostcode/QnA#175]
new daum.Postcode({
		.open({
			q : "143-210"
		});
})

이런식으로 검색결과값을 넘겨준뒤 우편번호 팝업창의 조회목록 중 첫번째 결과값을 자동으로 클릭되게하고싶은데 opener접근해서 해보려고해도 잘 안됩니다.
혹시 방법이 없을까요?

**Comment by daumPostcode** [comment]
@1989v 
네~ 안녕하세요~

네 해당 방법은 지원되지 않습니다.
opener로 접근이 안되는 이유는, 1989v님의 사이트와 우편번호 검색창의 도메인이 서로 다르기 때문에 보안적인 이슈로 인해 서로 제어할 수 없습니다.

저희는 사용자가 선택을 할 수 있는 뷰를 제공하는 것으로, 만약 쿼리에 대한 데이터만 필요하시다면, 저희 API보다는 도로명검색시스템(행자부 juso.go.kr)에서 제공하는 rest API를 이용하시는게 더 좋아 보입니다.

이외 다른 질문이 있으시면 언제든 이슈 등록해 주세요.~

감사합니다.
