### ISSUE TITLE
주소검색 문의입니다.

### ISSUE THREAD

**Issue by sh1006** [daumPostcode/QnA#176]
"세종시 삼성당2" 검색시 결과가 1개 나오는데,
"세종시 삼성당2길" 검색시엔 결과가 20개 나옵니다.

오히려 "세종시 삼성당2"를 검색했을때 결과가 더 많이 나와야 하는거 아닌가요?

수고스러우시겠지만, 
확인해 주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@sh1006 
네~ 안녕하세요~

제가 검색엔진을 만든 사람은 아니나, 예전에 회의때 들은 내용을 바탕으로 설명을 드리면,

삼성당2 와 삼성당2길 은 서로 다른 것을 나타냅니다.

삼성당2는 -> 삼성당 2로 해석이 되며, 도로명에 삼성당이 들어가고 건물번호에 2가 들어간 주소가 나오게 되고
삼성당2길 은 도로명에 삼성당2길 이 들어가는 주소가 나오게 됩니다.

도로명 주소의 경우, 검색 쿼리에 따라 제한을 걸 수 밖에 없는 것이, 제한을 걸 지 않으면, 어떤 쿼리던 너무 많은 검색 결과가 나와서, 주소를 선택하기가 너무 어려워지는 것에 기반을 둡니다.

즉, 쿼리를 분석할때, 기본적으로 도로명 주소의 형태 "도로명 + 건물번호" 형태로 판단을 하게 되며, 
삼성당2의 경우 삼성당2라는 도로명은 없으므로 "삼성당"과 건물번호 "2"로 해석을 할 수 밖에 없습니다.

이점 참고 하시어 검색하시면 될 것 같습니다.
