### ISSUE TITLE
iOS Webview에서 우편번호 검색 후 리스트 항목 선택 시 오류

### ISSUE THREAD

**Issue by dyyeom** [daumPostcode/QnA#177]
안녕하세요!
iOS에서 Webview를 통해 iframe을 활용해서 띄우는 방식을 사용하고 있습니다.
겪고 있는 문제가 하나 있어서 여쭤봅니다.
재현 스텝은 아래와 같습니다.

1. 검색창을 선택해서 주소를 입력하고 검색을 한다.
(키보드의 '이동' 버튼, 검색창의 돋보기 버튼 중 어느 것으로 해도 상관 없음)

2. 다시 한 번 검색창을 선택해서 자동완성리스트 중에 하나를 선택하거나 돋보기 버튼을 누른다.
(키보드의 '이동' 버튼으로 하면 재현되지 않음)

3. 뷰에서 모든 요소들이 다 사라진듯하게 나오지만, element들은 모두 해당 위치에 있어서 클릭이 되는 현상이 발생.

혹시 이 부분에 대해서 해결할 수 있는 방법이 있을까요?

**Comment by daumPostcode** [comment]
@dyyeom 
네~ 안녕하세요~

말씀해 주신 이슈가, 서제스트(자동완성 리스트)가 UI상 사라져 있는데도 불구하고 클릭이 되서 해당 서제스트로 검색이 되서 그러신 것인가요? 아니면; 보이지 않는 서제스트 리스트 때문에 실제 주소 영역을 클릭하기 어려워서 그러신 것인가요?

일단 iOS 10.3.2 Daum App 웹뷰에서 저희 가이드페이지 예제로 해본결과, 말씀하신 스텝을 따라가더라도, 서제스트 리스트가 선택이 되는 일이 발생하지 않았습니다;;;;;;

즉 재현이 안되서; 현재 해결 방법을 찾는게 좀 어려운데, 일단 해당 이슈는 최초 등록된 이슈라서 재현해서 확인하는데 까지만 시간이 좀 소요가 될 것 같아요;

iOS의 자세한 버전, 그리고 이용하신 웹뷰 (직접 만드신 거라면, 한번 범용앱(페이스북이나 다음앱 네이버앱 등)의 웹뷰에서도 한번 해보셔서 알려주시면 제가 확인하는데 도움이 될 것 같습니다;;

아니면 제가 스텝별로 하는 행동을 잘못 이해한 것일 수도 있는데; 혹시 동영상 링크가 가능할까요?
깃허브 이슈에 동영상이 안되면 메일로 보내주셔도 됩니다. 메일은 이 답변 계정 클릭하시면 보실 수 있습니다;;

일단 현재로써는 도움을 드리지 못해 죄송합니다;;

**Comment by dyyeom** [comment]
빠른 피드백 감사드립니다!
저의 설명이 부족했던 것 같네요...

동영상 기록해서 링크 올려드립니다.
https://goo.gl/59XJSf

동영상에서 보여주는 html 페이지는
http://postcode.map.daum.net/guide 페이지에 있는
'iframe을 이용하여 레이어 띄우기' 항목의 샘플코드입니다.

**Comment by daumPostcode** [comment]
@dyyeom 
음... 보여주신 동영상을 따라서 해봐도 재현이 되지가 않네요;
일단 저랑 다른 부분이, 검색영역을 선택을 하면, 화면이 깜빡이는데; 이때부터 약간 렌더링 버그가 있는 것 같아보이긴 합니다;
검색영역을 선택할때는 페이지이동이 아니라 스크립트로 결과영역을 display:none하는 것이라서; 검색바는 영향이 없습니다. 실제 검색버튼을 눌렀을때 화면이 깜빡이는것은 맞을 수 있으나(페이지 이동이므로) 이또한 iOS브라우저에서는 거의느끼기 힘든만큼의 깜빡임이 발생하는데;

일단 제가 테스트 하는 웹뷰는 
<img width="1077" alt="2017-07-06 11 35 11" src="https://user-images.githubusercontent.com/20675065/27893191-455d7dfa-623f-11e7-8ba3-64805d01d5cd.png">
```
NSString *strURL = @"http://테스트 페이지";
NSURL *url = [NSURL URLWithString:strURL];
    NSURLRequest *urlRequest = [NSURLRequest requestWithURL:url];
    [self.webview loadRequest:urlRequest];
```
이렇게 아무런 커스터마이징이 되어있지 않은 기본적인 웹뷰입니다.
(일단 제가 앱 개발자가 아니라 이 이상의 코딩을 하기가 어렵기도 하구요;;)

혹시, 만드신 웹뷰 말고, 기본적인 사파리, 다음앱, 네이버앱 등 이런 웹뷰에서도 혹시 동일하게 발생하실까요??

웹뷰의 경우, 사람마다 워낙 개발방법이 달라서; 예외케이스가 많거든요;;

한번 확인 부탁드립니다.

**Comment by dyyeom** [comment]
프로젝트 새로 만들어서
App Transport Security Settings > Allow Arbitrary Loads 값 YES로 설정,
스토리보드에서 View 위에 WebView 얹고,
주신 코드대로 그대로만 입력했는데도 제대로 표시되지가 않습니다. ㅜㅜ

원래 Swift로 구현했었고, 주신 코드가 Objective-C라서 여기서 해봐도 동일한 결과가 발생했습니다.

사파리, 다음앱, 네이버앱 등에서는 같은 주소 호출했을 때 정상적으로 작동하구요~

혹시 iOS 앱 또는 html파일에 설정해야하는 것이 이외에 따로 있을까요? 번거롭게 해드려 죄송합니다;;

혹시 몰라 html 파일 내용 첨부합니다!

```
<html>
<head>
    
</head>
<body>
<input type="text" id="sample2_postcode" placeholder="우편번호">
<input type="button" onclick="sample2_execDaumPostcode()" value="우편번호 찾기"><br>
<input type="text" id="sample2_address" placeholder="한글주소">
<input type="text" id="sample2_addressEnglish" placeholder="영문주소">

<!-- iOS에서는 position:fixed 버그가 있음, 적용하는 사이트에 맞게 position:absolute 등을 이용하여 top,left값 조정 필요 -->
<div id="layer" style="display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;">
<img src="//t1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>


<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
<script>
    // 우편번호 찾기 화면을 넣을 element
    var element_layer = document.getElementById('layer');

    function closeDaumPostcode() {
        // iframe을 넣은 element를 안보이게 한다.
        element_layer.style.display = 'none';
    }

    function sample2_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = data.address; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수

                // 기본 주소가 도로명 타입일때 조합한다.
                if(data.addressType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('sample2_postcode').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('sample2_address').value = fullAddr;
                document.getElementById('sample2_addressEnglish').value = data.addressEnglish;

                // iframe을 넣은 element를 안보이게 한다.
                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)
                element_layer.style.display = 'none';
            },
            width : '100%',
            height : '100%',
            maxSuggestItems : 5
        }).embed(element_layer);

        // iframe을 넣은 element를 보이게 한다.
        element_layer.style.display = 'block';

        // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.
        initLayerPosition();
    }

    // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는
    // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,
    // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.
    function initLayerPosition(){
        var width = 300; //우편번호서비스가 들어갈 element의 width
        var height = 400; //우편번호서비스가 들어갈 element의 height
        var borderWidth = 5; //샘플에서 사용하는 border의 두께

        // 위에서 선언한 값들을 실제 element에 넣는다.
        element_layer.style.width = width + 'px';
        element_layer.style.height = height + 'px';
        element_layer.style.border = borderWidth + 'px solid';
        // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.
        element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth) + 'px';
        element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth) + 'px';
    }
</script>
</body>
</html>
```

**Comment by daumPostcode** [comment]
@dyyeom 
네;; 제가 다른것 좀 하느라 답변이 늦었습니다;;

네; HTML파일은 딱히 문제가 있진 않습니다. 또한 말씀해 주신 설정 부분도 저두 다 되어 있는 상태구요(App Transport .... 이부분)

저희 샘플을 가져다가 이용하셨으면 따로 문제가 발생될 여지는 없고,
검색 버튼을 눌렀을때는 form 전송을 통해, 새로운 페이지가 로딩이 되는 것이므로, 이 새로운 페이지가 네트워크 문제나, 아니면 알 수 없는 다른 문제로 렌더링이 안되는 가능성이 있습니다.

혹시 safari inspector로 시뮬레이터를 찍어 보셨을때, 내부에 DOM이 살아 있을까요?
아니면 어떤 오류가 발생할까요?
힌색 배경으로 나온것으로 보면, body안의 모든 태그가 표시가 안되는 것 같거든요;

body안의 내용물이 살아 있는데, display:none처리가 된건지, 아니면 페이지가 로딩이 안된건지, 한번 확인 부탁드립니다;;; 아니면 모두 살아 있는데 레이어가 화면영역 밖에 위치해 있는지;

음.. 어려운 문제네요 ㅜ.ㅜ

**Comment by dyyeom** [comment]
내부 DOM은 살아있는 것으로 보입니다.
실제로 해당 영역을 선택하면 주소가 선택도 되구요~
safari inspector 스크린샷을 첨부합니다.
신경써주셔서 감사합니다!

<img width="1294" alt="2017-07-06 4 40 31" src="https://user-images.githubusercontent.com/6406608/27900664-3b252934-626a-11e7-98c2-4d6a09236a6f.png">

**Comment by daumPostcode** [comment]
@dyyeom 
음.. 그렇군요. 그럼 정말 단순하게, 페이지가 새로 불러왔는데(리프레쉬) 웹뷰가 iframe을 렌더링을 못한다는 것인데요;
시뮬레이터가 아니라, 실제 아이폰에서 확인 가능 하실까요?

저도 앱 개발자가 아니라;; 확인을 못하는 부분이라서요;;
웹뷰쪽 문제같은데; 정확히 어떤 문제인지는 알 수가 없네요;; ㅜ.ㅜ

실제 디바이스에서 동작한다면 시뮬레이터 문제라고도 볼 수가 있기 때문에 디바이스에 넣어서 확인 부탁드립니다.

**Comment by dyyeom** [comment]
실제 디바이스에서도 같은 현상이 일어나고 있습니다.^^;;

**Comment by daumPostcode** [comment]
@dyyeom 
엇;; 정말 어려운 이슈네요;;
일단 재현이 안되다 보니;; 정확한 원인 진단이 어렵고;; 제가 앱개발자가 아니라서 코드레벨에서 어떻게 해보시라는 가이드도 어렵고;; 다른 이용자 분들에게 발생한 이슈가 아니라서 특정상황에서 발생하는 것 같은 예외 케이스인데;;

ㅜ.ㅜ 일단 저녁에는 제가 일이 있어서 더이상 확인이 불가하여; 내일 다시 진행하도록 하겠습니다;;
일단 렌더링 및 web view repaint, redraw문제로 한번 알아보시는 것도 좋을 것 같아요;;

**Comment by daumPostcode** [comment]
@dyyeom 
다른 웹뷰에서 정상 동작을 하는것으로 보아, 뭔가 웹뷰 설정 문제 같긴 한데요; 
아무런 설정을 하지 않은 제가 만든 코드에서도 동작을 하는 것으로 보면, 디바이스나 시뮬레이터 문제일 수도 있어 보이고, 혹시 테스트 하시는 폰이 아니라, 불특정 다수의 핸드폰에서도 발생하는지 확인해 보셔야 하실 것 같아요.

일단 현재로써는 제가 도움을 드릴 수 있는게 거의 없을 것 같긴 합니다;
만들고 계시는 웹뷰에서 동작하도록 코드를 수정하거나 할 수는 없기 때문에, 웹뷰를 맞추시는게 좋아 보이며,
일단은 재현불가 && 특정 단말에서만 발생하는 이슈라서, 기록은 해두고 모니터링은 하겠지만 표본자체가 명확하지가 않아서 현재로써는 해결이 좀 어려울 것 같습니다;;

또한 정확한 iOS버전과 Xcode버전, target SDK등의 세부적인 정보를 알려주시면 더 좋을 것 같습니다;;

**Comment by dyyeom** [comment]
네 확인해보겠습니다~
iOS 버전 10.3.1
Xcode 버전 8.3.3
targetSDK는 (Deployment Target을 말씀하신다면) 10.3 입니다.

저희쪽에서 테스트 했던 모든 단말기에서는 해당 현상이 일어났습니다.
follow up은 더 안해주셔도 될 것 같고 제가 더 확인해보고 해결이 된다면 다시 말씀드리도록 하겠습니다.
빠른 피드백 감사드립니다.
혹시나 하여 어제 해봤던 시도에 대해서 남겨드립니다.

어제 테스트하면서 로그를 보는 와중에
`
2017-07-06 19:58:53.602 webviewtest[11154:377004] *** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x61000001d3b0
`
이런 exception log가 있었고, 검색해보니 아래와 같은 케이스가 있었습니다.
https://stackoverflow.com/questions/25894173/uiwebview-throwing-exception-for-webactiondisablingcalayerdelegate-setbeingremo
webkit과의 연동에서 문제가 있는 것으로 보입니다.

답변 중에 `-webkit-overflow-scrolling: touch;` 항목을 삭제하면 된다는 내용이 있어서 해봤더니 우선 화면은 정상적으로 출력되지만 스크롤이 되지 않아서 이것이 해결방법은 아니었습니다.
참고만 부탁드립니다. 해결 된다면 다시 comment 달도록 하겠습니다~

**Comment by daumPostcode** [comment]
@dyyeom 
넵!
혹시나 만드시는 어플리케이션의 UI에 문제가 되지 않는다면, 레이어모드가 아닌, 저희 예제 샘플에 있는 페이지에 끼워넣기를 참고해 보시면 모든 검색결과가 보이게끔 height를 늘릴 수 있는 방법이 있으니, 이 또한 참고하셨으면 좋겠네요;

그럼 아무쪼록 잘 해결 되시면 좋겠습니다.

오늘도 즐거운 하루 보내세요~

**Comment by Kuniz** [comment]
저희도 동일한 이슈가 발생했는데요. `-webkit-overflow-scrolling: touch;` 관련해서 지우면 스크롤이 안되었었는데, 위에 말씀하신대로  onresize로 iframe의 크기를 변경하는 식으로 사용하니 이슈가 발생하지 않아서 해결됬습니다.

**Comment by dyyeom** [comment]
@Kuniz 님 코멘트 보고 나서야 저도 이 방법 적용했네요. 이 방법으로 하니 저희도 해결되었습니다. 감사드립니다.
적극적으로 comment 해주신 @daumPostcode 께도 감사드립니다!
