### ISSUE TITLE
주소검색문의입니다

### ISSUE THREAD

**Issue by gmlss** [daumPostcode/QnA#179]
인천 송도 에듀포레푸르지오를 검색하고 주소를 클릭하면 우편번호가 입력되지 않습니다 급히 처리할 일이 있는데 어떡해야하죠

**Comment by daumPostcode** [comment]
@gmlss 
네~ 안녕하세요~


먼저 FAQ12번 14번 참고바랍니다. (https://github.com/daumPostcode/QnA#12-팝업창에서-검색-후-결과를-클릭해도-반응이-없습니다)

보통 주소가 입력인 안되는 문제는 개발시의 12번의 문제거나, oncomplete 함수 내의 오류 (저희 샘플코드를 이용하셨을 경우, 실제 gmlss님의 홈페이지 상황에 맞게 변경작업을 진행해야 합니다) 로 나눌 수 있습니다.

말씀해주신 내용가지고는 제가 어떤 답변을 드릴 수 없으며, 제가 접근 할 수 있는 URL을 알려주시면 좋을 것 같습니다. 또한 상황이 재현되는 브라우저,OS 등의 버전도 알려주시면 좋을 것 같네요
