### ISSUE TITLE
이용 후기...

### ISSUE THREAD

**Issue by han3388** [daumPostcode/QnA#18]
안녕하세요.
이제 이런 저런 문제점을 수정완료하고 현재는 잘 사용하고 있습니다.
구버전을 사용하면서 새버전의 검색방법에 대한 몇몇 문제때문에 사용하지 않고 있다가 그 부분들에 대한 
문제점을 [메인 부분 검색방법 안내와 가이드문구 강조기능]을 잘 적용해 주셔서 망설임 없이 
얼마전부터 새버전으로 적용해서 사용하고 있습니다.

현재 1주일정도 사용하면서 주소검색때문에 불편함이 있다는 소리는 없는 상태입니다.
저 또한 수동으로 고객분과 상담하면서 주소를 찾고 작성할때 기존 구버전보다 빠르고 정확하게
더욱더 잘 사용하고 있습니다.

앞으로 잘 사용하겠습니다. (얼마전 건의드린 부분만 조만간 적용이 되면 좋겠네요.)
감사합니다.

**Comment by daumPostcode** [comment]
@han3388 
네~ 안녕하세요~

잘 적용되어서 다행입니다 ^^
얼마전에 건의해 주신 내용중, 

첫번째 질문에 대한 내용은, 이전에 답변 드렸던 것과 같이, 저희가 내려드리는 데이터를 가공하셔서 이용하셔야 합니다. 일반적으로 bname을 내리는 이유는 도로명 주소(지번 주소)와 같은 형식을 표시 하려는게 아닌, 도로명 주소 표기 법령에 따라 표시를 하는데 도움을 드리고자 내리는 것이기 때문이에요~

두번째 내용에 대해서는
도로명 : 지번이 1:1 매핑인 경우에는 적용해보려고 하고 있습니다. 다만 다른 일정때문에 들어가진 못하고 있는데 이부분에 대해선 긍정적으로 답변을 드릴 수 있을 것 같아요, 다만 도로명:지번이 1:N이거나, N:1, N:M인 경우에는 해결방법이 딱히 없어 고민이긴 합니다. 추후에 정책상 변경이 되면 이 게시글에서 댓글로 멘션 보내도록 하겠습니다.

세번째 동의어 관련 부분은 현재 적용이 되었으며 "행정리"와 "행정동"의 차이는 이전 댓글에서 설명 드린바와 같습니다. 즉, 행정리의 경우에는 동의어 처리로 해결을 해야되기 때문에, 추후 다른 주소라도 말씀해 주시면 추가하도록 할께요~

이번에 좋은 건의사항을 많이 주셔서 서비스적으로 한층 더 발전한 것 같고, 다시한번 저희 서비스에 지속적인 관심과 이용 감사드립니다 ^^
