### ISSUE TITLE
하이브리드 앱에서 오류 문의

### ISSUE THREAD

**Issue by rayeteu** [daumPostcode/QnA#181]
안녕하세요.

cordova 하이브리드 앱에서 다음 주소 검색 api를 사용하려고 하는데 오류가 있어서 문의드립니다.
iframe 예제를 사용하였습니다.

1. 닫기  아이콘이 표시되지 않습니다.(그림이 없을 때 뜨는 아이콘이 대신 뜹니다.)
2. 검색창을 띄우면 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'http://' in a call to 'postMessage'. 라는 오류 메시지가 출력됩니다. 검색창은 정상출력되고 검색도 됩니다. 
3. 검색하고 나서 주소를 클릭하면 위와 동일안 오류 메시지가 출력되고 주소가 삽입되지 않습니다.

혹시 짐작가시는 부분이라도 있으시면 답변 부탁드립니다.
감사합니다. 수고하세요.

**Comment by rayeteu** [comment]
아이콘 문제는 로컬로 저장하여 해결해도 될것 같아서 크게 상관은 없습니다. 정확한 증상을 설명드려야 될것 같아서 넣은 것이니 신경쓰시지 않으셔도 됩니다.

**Comment by daumPostcode** [comment]
@rayeteu 
네~ 안녕하세요~

[FAQ 12번](https://github.com/daumPostcode/QnA#12-팝업창에서-검색-후-결과를-클릭해도-반응이-없습니다) 이슈로 짐작되네요.

코르도바와 같은 웹앱은 실제 HTML,JS,CSS를 직접 패키징 하여 웹뷰에 띄우는 것으로 알고 있습니다. (PC에서 브라우저에 파일을 드래그하여 정적으로 실행하는 거랑 같다고 볼 수 있죠)

다만 우편번호 서비스의 경우 이렇게 실행하면 웹서버를 통해서 띄우는게 아니라서 도메인 정보를 알 수가 없게 되어, 검색까지는 되지만 데이터 전달은 불가합니다.

이는 이종도메인간의 통신 방법인 postMessage를 이용할때 필수적으로 도메인을 체크하기 때문이며, 현재로써는 코르도바를 이용하시더라도, 우편번호 서비스를 이용하시는 부분은 웹서버를 두어 페이지를 호출하여 이용하셔야 합니다.

이렇게 하는게 상황적으로 어려우시다면, juso.go.kr에서 제공하는 REST API를 직접 이용해서 개발하시는게 좋아 보입니다.

감사합니다;
