### ISSUE TITLE
지번주소 입력후 도로명주소 선택안되는 증상

### ISSUE THREAD

**Issue by hyunsik7548** [daumPostcode/QnA#183]
안녕하세요.

항상 빠른처리에 감사드리며

 주소검색시 지번 주소를 검색하면 도로명 주소와 지번주소 2개가 검색이 되는데

지번주소만 선택이 가능하고 도로명 주소는 선택이 안됩니다.

반대로 도로명 주소로 검색시 마찬가지로 지번주소는 선택이 안되는 증상이 나타납니다.

원래 이런건지.. 문의드립니다.

**Comment by daumPostcode** [comment]
@hyunsik7548 

네~ 안녕하세요~

혹시 autoMapping옵션을 false로 하신 건 아니신지요.
해당 옵션이 false이면 1:N 주소의 경우 메인주소(1)는 선택이 안되며 연관주소(N)만 선택이 됩니다.

해당 옵션의 자세한 설명은
http://postcode.map.daum.net/guide#attributes
가이드 페이지의 속성 부분에서 중간쯤에 내려보시면, autoRoadAddress, autoJibunAddress와 관련된 설명 박스가 있습니다. 해당 박스의 내용을 읽어 보시는 것을 추천드립니다.

기본 값은 true입니다.

다른 의도의 질문인데 제가 잘못 이해했거나, 다른 질문이 있으시면 댓글 주세요~

**Comment by hyunsik7548** [comment]
Iframe을 이용하여 페이지에 끼워 넣기 
예제에서도 
우편번호 찻기 -> 주소 경북 경산시 압량면 압량리 169   검색시
지번    경북 경산시 압량면 압량리 169 
도로명  경북 경산시 압량면 대학로 498-10 (주삼원) 
2개 주소가 나오는데 
도로명주소를 선택하여도 지번주소로 선택이 됩니다.
도로명주소도 선택이 가능하게 하려면 어떻게 해야할까요?

**Comment by daumPostcode** [comment]
@hyunsik7548 

네~

해당 이슈는 [FAQ 16](https://github.com/daumPostcode/QnA#16-사용자가-지번도로명-중-어떤-것을-선택하더라도-무조건-도로명-주소만-이용하고-싶은데-어떻게-해야되나요)번을 참고해 주시기 바라며

저희 가이드 페이지의 http://postcode.map.daum.net/guide#attributes 속성부분의 oncomplete의 데이터로 내려오는 부분을 확인해 보시면, 선택한 데이터에 대한 여러가지 상태 값들이 있습니다.

userSelectedType, addressType등, 해당 속성을 활용하시면 처리 가능하십니다~
