### ISSUE TITLE
iframe 출력 이후 사이즈 조절

### ISSUE THREAD

**Issue by jungkiLee** [daumPostcode/QnA#184]
안녕하세요, 현재 다음 우편번호를 사용중인데 한 가지 궁금한 점이 생겨서 이렇게 문의 드립니다.
원래 iframe 관련 글만 적으려고 했는데 추가로 문의 사항이 생겨 수정합니다.
 - 텍스트 드래그 후 클릭 시 무반응
오픈된 다음 주소검색 사용 시 텍스트 등을 드래그하고 주소를 검색 할 경우 oncomplete가 호출이 되지 않습니다.

 - iframe 출력 이후 사이즈 조절 부분
일반 pc 말고 모바일에서 iframe 이용 시 x자 이미지 버튼이 너무 작게 나와서 불편함이 있습니다.

그렇다고 해당 버튼 크기를 키우자니 검색 필드의 검색 버튼을 가리는 경향이 있어 그 부분을 조절하려 했으나 검색 버튼의 경우 제가 컨트롤 할 수 없는 영역에서 생성 및 style 수정을 하는 듯하여 수정이 불가능 하더라구요.

혹시 iframe상 검색 필드만이라도 style 수정이 가능할런지요?

**Comment by daumPostcode** [comment]
@jungkiLee 
네~ 안녕하세요~

저희 샘플을 이용하신 듯 하네요~
저희 샘플은 그냥 샘플일뿐; 마음대로 수정해서 사용하시면 됩니다.
샘플중에 new daum.Postcode()를 이용하여 실행하여 띄우는 실제 검색 화면은 유저가 임의 적으로 수정이 불가능합니다
다만 레이어 모드(iframe)사용시 테두리나, 닫기 버튼 이런것은 잘 보시면, 우편번호 서비스 API가 제공하는 영역이 아닙니다. 샘플코드내에서 단순히 이렇게도 할 수 있다 수준으로 구현되어 있는 것일뿐, 마음대로 고쳐서 사용하시면 됩니다.

샘플에는 검색버튼 쪽에 닫기 버튼이 있지만, embed(target)을 실행할때 이 target을 감싸고 있는 wrapper를 하나 만들어서 이 wrapper에 닫기 버튼이나 기타 다른 버튼들을 구성하시면 될것 같아요~

**Comment by jungkiLee** [comment]
답변에 감사드립니다.
질문 하나가 더 추가되어 해당 질문에도 답변 부탁드리겠습니다.

**Comment by daumPostcode** [comment]
@jungkiLee 
네~

텍스트 드래그 후 클릭시 무반응
-> 현재 해당 이슈는 코드 상 정상적인 반응입니다.
다만 코드 상이라고 말씀드린 부분은, 특정 단말기에서의 사이드 이펙트 때문에 잠궈 놓은 기능인 것으로 판단이 됩니다만, 주석이 없어서; 현재 정확한 이슈를 확인해 봐야 될 것 같아요.

즉 현재 실서비스로 나가 있는 버전은 주소 텍스트가 드래그하여 선택이 되어 있는 경우에, 클릭시 이벤트가 작동하지 않도록 되어 있습니다.

정상 동작으로, 해당 사용성 문제에 대해서는 원인을 파악한 후에 개선하도록 하겠습니다.

해당 원인이 파악되거나, 원인이 파악되지 않더라도 기존에 개발(2015년)할때의 사이드이펙트가 발생하지 않을 경우, 사용성 개선 측면에서 제거하도록 하겠습니다.
해당 이슈의 완료처리는 이 이슈 댓글로 달아드리도록 할께요~

감사합니다.
