### ISSUE TITLE
팝업창 사용일때, OnClose 콜백함수 관련 질문드립니다.

### ISSUE THREAD

**Issue by chd3wkd** [daumPostcode/QnA#185]
팝업창 예제코드를 보며 테스트 해보던 도중, 

주소검색후 클릭해서 닫힐경우엔 ,  onclose가 실행은 되지만 내부로직에는 들어오지 못하고
팝업창을 그냥 닫는 경우엔 onclose가 반응이 없습니다.

혹 제가 실수한 부분이 있을까요?

답변달아주시면 감사하겠습니다.

<script src='https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js'></script>              
script>
   new daum.Postcode({
    onclose: function(state) {

        if(state === 'FORCE_CLOSE'){
            alert('x버튼닫기')

        } else if(state === 'COMPLETE_CLOSE'){
			alert('검색닫기')
        }
    }
	});

   ..........
</script>

**Comment by daumPostcode** [comment]
@chd3wkd 
네~ 안녕하세요~

개인적인 문제가 있어 답변이 늦은 점 죄송합니다.

먼저 제가 테스트 코드를 작성해서, onclose 콜백 함수가 이상이 있는지 확인해 보았는데요. 현재 정상적으로 동작을 하고 있습니다.
적어주신 코드는 샘플코드인데, 이 코드 말고, 실제 사용하신 코드를 적어 주시면 감사하겠습니다.

혹시 open()을 이용한 팝업형이 아닌, embed()를 이용한 레이어 모드를 사용중이실까요?
embed()모드를 사용한 레이어 모드에서는 FORCE_CLOSE가 작동하지 않습니다.

**Comment by chd3wkd** [comment]
답변감사합니다~
테스트환경은 윈도우7 / 익스플로러11 입니다.

저의 테스트코드 정보는 http://drbit.kr/Address/httpsFindAddressLog.html 입니다!

코드가 길어서 주소정보를 남겨놓았습니다.

**Comment by daumPostcode** [comment]
@chd3wkd 
네~ 올려주신 코드는 확인하였습니다.

코드를 봐보니, 코드 문제라서 크롬에서 확인하였습니다.
스크립트 상단에 new daum.Postcode({ ... }); 라고 하나 실행되어 있고,
그 아래 sample4_execDaumPostcode()함수내에서 하나가 더 있네요.

그리고 우편번호 찾기 버튼을 눌렀을대 실행되는 것은 sample4_execDaumPostcode 함수 내에 정의되어 있는 것으로 실행이 되구요. 즉 스크립트 상단에 정의하신 new daum.Postcode 이부분의 코드는 저희 우편번호 서비스 객체만 생성하고, 변수에 할당도 안했기 때문에 그냥 버려지는 객체이며, 이 객체에 onclose를 정의하셔도 아무런 동작도 하지 않습니다.
저희 예제 코드를 가지고 오신 것 같은데요. 가이드 페이지 예제 부분을 제외한 다른 부분에 있는 코드는 인터페이스에 대한 설명일 뿐, 완벽히 실행되는 코드는 아닙니다. 이부분 참고하세요.

결론은 상단에 있는 더미 객체는 불필요하니 삭제하시고,
sample4_execDaumPostcode이 안에 있는 생성자에 onclose를 정의 하시면 정상 동작합니다.

다만, oncomplete하단에 location.href를 설정하시더라구요? 

oncomplete함수는 실제로 바인딩되는 영역은 팝업창이 아니라, 본문 부모페이지에 바인딩 됩니다. console을 찍어 보시면 팝업창 콘솔에서 뜨지 않고 부모페이지에서 콘솔이 실행되는 것을 확인 하실 수 있습니다. 
그렇기 때문에 oncomplete에서 location.href를 설정하면, 부모페이지의 주소를 변경하는 것이기 때문에 
onclose의 'COMPLETE_CLOSE'상태는 받을 수가 없습니다. 이유는 설명에도 써있는 것처럼 oncomplete함수의 실행이 끝난 다음에 onclose가 실행되기 때문입니다. 즉 oncomplete마지막 부분에 location.href를 설정하면 부모페이지가 바뀌어 버리기 때문에, 기존의 스크립트실행 부분이 모두 초기화 되므로, 아무런 실행도 되지 않습니다.

콘솔을 찍어 보시면서 또는 크롬에서 디버깅을 하시면서 흐름을 참고 하시면 수정이 쉬우실 것 같습니다.
이외 다른 부분이 궁금하시면 댓글 부탁드립니다~

**Comment by chd3wkd** [comment]
친절한 답변 너무나 감사합니다!!!
