### ISSUE TITLE
행정자치부에서는 나오지만, daum우편번호 서비스에서는 나타나지 않는 주소.

### ISSUE THREAD

**Issue by kskang9** [daumPostcode/QnA#186]
안녕하세요.
다음 우편번호 서비스를 이용하는데, 행정자치부에서는 검색되지만, 다음 우편번호에서는 나타나지 않는
주소가 있습니다. 
서울시 강남구 밤고개로 26길 50 입니다.
저희 대학 홈페이지의 문제가 아니고, 다음 서비스 측의 에러라면 조치를 부탁드리겠습니다.
감사합니다.
강경식 드림

**Comment by daumPostcode** [comment]
@kskang9 
네~ 안녕하세요~~

해당 주소는 현재 정상 검색이 되고 있습니다.
- 다음 우편번호 서비스
![2017-07-24 10 38 00](https://user-images.githubusercontent.com/20675065/28505175-3a4fe008-705c-11e7-9fde-d5b5cde6e7bb.png)
- 행자부 도로명검색 시스템
![2017-07-24 10 38 08](https://user-images.githubusercontent.com/20675065/28505177-3dacea34-705c-11e7-81b2-ddfb4f27dca5.png)
(추가적으로 정식 도로명은 "밤고개로26길"입니다. 띄어쓰기 문제로 검색 결과가 약간씩 달라질 수 있습니다. 다만 건물 번호까지 입력이 되면 거의 정확히 검색이 됩니다)

추측컨데, 행자부와 저희시스템과의 동기화가 되는 기간은 대략 1~2일이 소요됩니다. 보통 1일이 수행되나 간혹 특정 이슈로 인해 이틀 정도까지 미뤄질 수는 있습니다. 해당 주소가 새로 생긴 주소라던지, 변경이 된 주소라면, 행자부에서 변경이 된후 1~2일 후에 저희 시스템에 반영됩니다.

추가적으로 행자부에서 검색은 되나, 저희 시스템에서 검색이 되지 않는 주소에 대해 말씀드리면,
일명 보안주소라고 부르고 있는 주소인데요.
실질적으로는 좌표가 없는 주소입니다. 이는 행자부에서 검색을 하면 주소 목록에 지도 마크가 없는 주소가 있는데; 해당 주소는 보통 국가안보시설이나 외부에 노출이 되면 안되는 장소로써, 저희에게 좌표값을 주지 않습니다. 그래서 주소 매핑이 불가능하여 저희 시스템에서는 반영이 되지 않습니다. (문의 주신 주소는 이 케이스는 아닙니다.)

이외 추가적인 문제가 있으시면 언제든 이슈 등록 부탁드립니다. 감사합니다.

**Comment by kskang9** [comment]
안녕하세요. 
제가 더 구체적으로 말씀드렸어야 하는데, 죄송합니다.
우편번호가 검색이 안되는게 아니라, 검색은 되지만, 검색된 주소를 클릭했을 때, 우편번호 창에 입력이 안되고 있습니다. 다른 우편번호들은 입력이 잘 되지만, 밤고개로26길 50은 입력이 안되고 있습니다..
![26](https://user-images.githubusercontent.com/30396350/28506129-0ab34eae-7064-11e7-9717-5b6f76ab02fb.JPG)

**Comment by daumPostcode** [comment]
@kskang9 
네~

입력이 안되는 이슈는 거의 99% oncomplete함수내의 오류 문제입니다.
크롬에서 부모페이지에서 개발자 도구를 연 후에,
한번 확인해 주세요. 어떤 부분에서 어떤 오류가 뜨는지 확인 부탁드립니다.

아니면 저에게 제가 접속 할 수 있는 URL을 알려주시면 확인해 드리도록 하겠습니다.

감사합니다.
