### ISSUE TITLE
주소가 깨지는현상 있었는지?

### ISSUE THREAD

**Issue by gomtang93** [daumPostcode/QnA#187]

**Comment by gomtang93** [comment]
가끔가다 주소가 아래와 같이 깨져서 들어오는대 혹시 이런 증상 다른곳에선 없었나요?
寃쎄린 ?⑹???泥??援????硫????濡?05踰?만 9-3 (???由?

**Comment by daumPostcode** [comment]
@gomtang93 
해당 이슈는 인코딩 문제로,
현재 저희 시스템은 UTF-8인코딩을 사용합니다.

만드시는 페이지의 파일 자체가 UTF-8인코딩셋을 사용하는 파일이 아니거나, 페이지의 인코딩 타입이 UTF-8로 셋팅해 보세요.

인코딩 문제는 제가 컨트롤 할 수 있는 문제가 아니라서; 만드시는 분께서 페이지의 인코딩셋을 맞춰주셔야 합니다;
