### ISSUE TITLE
iframe을 이용하여 레이어 띄우기 시 내용이 나오지않음

### ISSUE THREAD

**Issue by verysoo** [daumPostcode/QnA#189]
제목 그대로의 문제입니다..
![error](https://user-images.githubusercontent.com/30423202/28551165-1d7fcaf4-7121-11e7-8a2e-e6ce66087b10.png)
이렇게 닫기 버튼만 보이네요..

소스는

<div id="layer" style="display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;">
<img src="//t1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>

<script src="https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js"></script>
<script>
var element_layer = $("#layer");

function closeDaumPostcode() {
	// iframe을 넣은 element를 안보이게 한다.
	$('#layer').css("display","none");
}

function fn_showZipCode(){
	// iframe을 넣은 element를 보이게 한다.
	$('#layer').css("display", "block");
	
	new daum.Postcode({
		oncomplete: function(data) {
				// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

				// 각 주소의 노출 규칙에 따라 주소를 조합한다.
				// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
				var fullAddr = ''; // 최종 주소 변수
				var extraAddr = ''; // 조합형 주소 변수

				// 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
				if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
						fullAddr = data.roadAddress;

				} else { // 사용자가 지번 주소를 선택했을 경우(J)
						fullAddr = data.jibunAddress;
				}

				// 사용자가 선택한 주소가 도로명 타입일때 조합한다.
				if(data.userSelectedType === 'R'){
						//법정동명이 있을 경우 추가한다.
						if(data.bname !== ''){
								extraAddr += data.bname;
						}
						// 건물명이 있을 경우 추가한다.
						if(data.buildingName !== ''){
								extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
						}
						// 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
						fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
				}
				// 우편번호와 주소 정보를 해당 필드에 넣는다.
				document.getElementById('zip_code').value = data.zonecode; //5자리 새우편번호 사용
				document.getElementById('addr1').value = fullAddr;

				// 커서를 상세주소 필드로 이동한다.
				document.getElementById('addr2').focus();
				
				// iframe을 넣은 element를 안보이게 한다.
				// (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)
				$('#layer').css("display","none");
			},
			width : '100%',
			height : '100%',
		}).embed(element_layer);
	
	// iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.
	initLayerPosition();
}

function initLayerPosition(){
	var width = 500; // 우편번호서비스가 들어갈 element의 width
	var height = 600; // 우변번호서비스가 들어갈 element의 height
	var borderWidth = 3; // 사용하는 border의 두께
	
	// 위에서 선언한 값들을 실제 element에 넣는다.
	$('#layer').css({width: 500, height: 600, border: 1});
//	element_layer.style.width = width + 'px';
//	element_layer.style.height = width + 'px';
//	element_layer.style.borderWidth = width + 'px solid';
	// 실행되는 순간의 화면 너비와 높이 값들 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.
	$('#layer').css('left',(((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth));
	$('#layer').css('top',(((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth));
//	element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth) + 'px';
//	element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth) + 'px';
}
</script>

이렇습니다. 왜 이런지 잘모르곘네요..

**Comment by daumPostcode** [comment]
@verysoo 
네~ 안녕하세요~

일단 
spi.maps.daum.net 도메인은 사용하시면 안됩니다. 해당 도메인은 서비스는 계속 되지만, 지금도 그렇고 나중에도 캐시 문제로 인하여 업데이트 분이 반영이 안되는 현상이 있습니다.
현재 저희 가이드 페이지에서도 해당 도메인은 삭제된 상태이며
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js
이렇게 변경되어 있습니다. 위 도메인을 사용하시기 바랍니다.

음 올려주신 코드는 저희 우편번호 서비스 샘플코드인데; 샘플코드는 해당 현상을 확인하기엔 적합하지 않습니다.
샘플코드의 경우 저희 가이드페이지에서는 100%동작을 확인하고 만든 코드이기 때문에, 이 코드가 verysoo님의 사이트에서 정상동작을 하는 것은 verysoo님이 적당히 커스터마이징을 하셔야 합니다. 저희는 JS API로 new daum.Postcode라는 생성자와 함수들을 제공하며 관리하지, 샘플코드는 이런식으로 응용가능하다 라는 것을 보여주는 것일 뿐이거든요.

즉, 해당 현상을 제가 확인을 하려면, 전체 코드가 필요하며(제가 실행가능한, html로 된 파일) 또는 제가 접근할 수 있는 URL정보가 필요합니다.

이슈로 등록하시기 어려우시면, 메일로 보내주셔도 됩니다~

**Comment by verysoo** [comment]
소스 긁어서 보내드리면되나요..??  메일주소 알려주세요

**Comment by daumPostcode** [comment]
@verysoo 
네~ 메일 주소는 답변다는 이 계정 클릭해서 계정페이지로 들어가보시면 있습니다.
https://github.com/daumPostcode <- 여기 들어가보시면 있습니다~

**Comment by verysoo** [comment]
var element_layer = $("#layer"); 이런식으로 잡은걸 var element_layer = document.getElementById('layer');으로 수정했더니 해결했습니다.. 별거 아닌거로 시간끌었네요 ㅠㅠ 답변들 감사합니다..

**Comment by daumPostcode** [comment]
@verysoo 
아 ㅎㅎ
$('#layer')로 받아온 객체는 실제 DOM Element가 아니라 Jquery객체라서 그럴 거에요~
jQuery는 사용자의 취향에 맞게 쓰는 라이브러리라, 일반적으로 api만들때는 plain javascript만 이용하거든요 ㅎㅎ
아무튼 잘 해결 되셨다니 다행입니다 ^^

jQuery를 이용해서 하실땐
$('#layer')[0] 이렇게 전달하시면 될거에요~~

그럼 즐거운 하루 보내세요~~
