### ISSUE TITLE
도로명 주소 등록 부탁드립니다.

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#19]
기존에 
경기 파주시 조리읍 당재봉로 16 (오산리, 시대고시기획출판센터)
라는 주소가 등록되어있으나

거주자는 시대고시기획출판센터 라는 건물명이 제외되어야 우편물을 정상적으로 받아볼 수 있다고 합니다.
따라서 
경기 파주시 조리읍 당재봉로 16 (오산리)
라는 주소로 추가등록 해주실 수 있으신지요?

**Comment by daumPostcode** [comment]
@dysong1 

네~ 안녕하세요~
저희 [FAQ 1번 2번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)을 참고해 주세요. 

오타와 같은 단순 수정에 대해서는 수정을 할 수 있지만, 말씀하신 것처럼 존재하는 데이터를 제거하는 것은, 행자부 사이트에서 사용자가 직접 수정요청을 해야합니다.

행자부 사이트에서 업데이트가 되면, 저희는 익일 적용됩니다.
