### ISSUE TITLE
document.write 개선

### ISSUE THREAD

**Issue by divinespear** [daumPostcode/QnA#190]
크롬 55 부터는 네트워크 연결속도가 느릴 경우 `document.write`로 추가된 스크립트를 로드하지 못하는 문제가 보고되어 있습니다. (참고: https://www.chromestatus.com/feature/5718547946799104, https://developer.mozilla.org/en-US/docs/Web/API/Document/write)

우리나라에서는 대체로 큰 문제가 없을 것으로 보이지만, 모바일 웹 같은 만약을 대비해서 `document.createElement`로 좀 더 안전하게 스크립트를 우겨넣는 방법을 시험해보심이 좋을 듯 합니다.

**Comment by daumPostcode** [comment]
@divinespear 
네~ 안녕하세요~~

넵 제안 감사드립니다 ^^ 해당 이슈는 알고 있는 이슈인데요. 코어 스크립트 로딩 및 파싱 타이밍을 정적 로딩시 완벽히 잡기 위해서 현재 어쩔 수 없이 쓰고 있긴 합니다. 이를 해결하는 방법은 createElement외에도 서버에서 api를 조합하는 방식도 생각해 볼 수 있는데요. 현재로써는 약간 어렵긴 합니다. 이점 양해 부탁드리구요.

그리고 말씀하신 createElement를 쓰는 방식은
?autoload=false
를 붙혀서 로딩하면, 동적 로딩 방식으로 document.write를 사용하지 않습니다. 해당 방식은 angular나 react같은 프레임워크를 사용할때 동적으로 페이지를 생성하는 경우가 많은데, 이런 곳에 쓰실때에 보통 권장하는 방식입니다.
해당 사용법은 저희 가이드페이지 상단의 기본 사용법에 있으니 참고해주세요~

아무튼 제안 감사드립니다 ^^
