### ISSUE TITLE
도로명이 존재하나 roadname값이 없습니다

### ISSUE THREAD

**Issue by JunHyoungMin** [daumPostcode/QnA#191]
문수동 163-1로 검색했을때 
도로명이 문수로4길로 검색되나 
리턴되는 roadname에는 빈값이 들어있습니다.
이 특정주소뿐 아닌 다른주소들도 같은 현상이 있는 주소들이 많이 존재합니다. 해당 문제가 api의 문제인지 행자부 문제인지 알려주시길바랍니다

**Comment by daumPostcode** [comment]
@JunHyoungMin 
네~ 안녕하세요~

해당 문제는, 검색 쿼리의 타입에 따라 검색하는 방식이 달라서 발생하는 문제인데요;
왠만한 주소가 픽스가 되었는데, 시간이 지남에 따라 처리가 안된 주소가 발생하는 것 같네요;

해당 문제는 데이터 담당자 분께 전달하여 확인해 보도록 하겠습니다.

제보 주셔서 감사합니다.

추가로 해당 주소는 "전남 여수시 문수4길 14-1" 처럼 도로명주소 타입으로 검색하면 roadname값을 얻으실 수 있습니다.

**Comment by daumPostcode** [comment]
@JunHyoungMin 
안녕하세요~

해당 오류는 서버 검색엔진 문제로 확인이 되어, 어제 보고 후, 금일 처리 되었습니다.
현재 몇몇 주소로 제가 확인해본 결과 정상적으로 값이 리턴이 되고 있는데요;
혹시나 값이 나오지 않는 주소가 있으면 댓글 주시면 확인하도록 하겠습니다.

제보 주셔서 감사합니다.

즐거운 금요일 보내세요~
