### ISSUE TITLE
질문: 주소 데이터의 고유 Key를 알 수 있나요?

### ISSUE THREAD

**Issue by devbada** [daumPostcode/QnA#193]
안녕하세요. ^^

특정 주소 (A)를 입력한 시점과 현재 시점을 비교하여 
변경된 부분이 있을 경우 특정 주소를 업데이트 할 수 있도록 하거나, 업데이트를 하라고 안내할 수 있도록 하려고 합니다.

그러다보니 제공해주시는 API의 데이터 key (각 주소데이터별 PK와 같은) 를 인지하고 확인할 수 있도록 제공 중이신지 알고 싶습니다. ^^

그럼 수고하세요. 👍

**Comment by daumPostcode** [comment]
@devbada 
안녕하세요~

해당주소의 데이터상의 고유값은 따로 내리거나 하지 않습니다.
즉 말씀하신 데이터의 최신화 유지에 필요한 key값은 현재는 존재하지 않으며, 앞으로도 추가할 계획은 없습니다.

그리고 말씀하신 기능은, 저희 API를 이용하는 것보다 행자부 REST API를 이용하시는게 구현상 더 간편할 것 같습니다.

도움을 드리지 못해 죄송합니다;

**Comment by devbada** [comment]
답변 감사합니다. :-)
