### ISSUE TITLE
아이폰에서 우편번호 검색시 오류

### ISSUE THREAD

**Issue by yyyyy519** [daumPostcode/QnA#194]
먼저 안드로이드, 아이폰 모두 테스트해 본 결과 아이폰에서만 발생하는 현상임을 알려드립니다.

우편번호 검색하기 위해 지역명을 입력할 때 텍스트박스가 위로 올라가서 안보이는 현상이 발생합니다.
이해하기 쉽게 사진을 첨부하고 싶은데 첨부하는 기능이 어디에 있는지 몰라서 사진 링크로 남겨드릴게요

[  https://drive.google.com/open?id=0B4Mzp7zX6nPuVkJMQ0sxaGhpbG8  ](url) 입력하는 과정에서 일어나는 현상입니다. 
[  https://drive.google.com/open?id=0B4Mzp7zX6nPudThKaUgxNFBHdkk  ](url) 모두 입력하고 나면 정상적으로 텍스트박스가 보입니다.

얼마 전까지 이런 현상이 없었던 걸로 기억하는데 갑자기 이런 현상이 생겼어요. 무엇때문에 이런 현상이 일어났는지, 어떻게 수정하는지 알고싶습니다. 
감사합니다.

**Comment by daumPostcode** [comment]
@yyyyy519 

네~ 안녕하세요~
해당 이슈는 ios 10.3.x버전에서(현재 오류가 발생하는 주요버전) 발생되는 이슈로, 추후 애플에서 수정이 될지는 확실하지 않습니다.
말씀하신 이슈로 올해 5월달에. CS가 들어왔으며 (참고 - https://github.com/daumPostcode/QnA/issues/147)
해당 이슈는 해결이 어렵고, 회피하는 방식으로 처리를 하였습니다.

- 키보드가 올라올때의 버그
- 키보드가 올라올때 본문 스크롤 위치와, 레이어의 inner scroll버그가 중첩된 이슈로. 

회피 방식으로는 생성자에 maxSuggestItems <- 이 속성 값을 대략 5정도 (레이어의 height가 400정도인 경우 5입니다. 더 작다면 더 작은 값으로 설정)로 설정하여 테스트 해주시기 바랍니다. 해당 샘플은 저희 가이드 페이지의 "iframe을 이용하여 레이어 띄우기"예제에 있으며, 속성의 자세한 설명은 "http://postcode.map.daum.net/guide#attributes" 속성 부분의 하단부분에 자세히 설명되어 있으니 참고 부탁드립니다.

한번 테스트 해보신 후 답변 주시면 감사하겠습니다~
