### ISSUE TITLE
주소에 대해 문의사항이 있습니다.

### ISSUE THREAD

**Issue by ritachoibbk** [daumPostcode/QnA#195]
안녕하세요 

도로명 주소/구 주소의 최대 byte를 알고 싶습니다,

그리고 시/도명만 따로 받는 게 가능한가요?

빠른 답변 부탁드립니다. 

감사합니다 :)

**Comment by daumPostcode** [comment]
@ritachoibbk 
네~ 안녕하세요~~

최대 byte까지는 제가 알 수는 없습니다만, 제일 긴 주소를 알려드릴 순 있습니다

도로명 : 제주특별자치도 서귀포시 안덕면 중산간서로1615번길 214-31
지번 : 경상남도 창원시 마산합포구 진전면 오서리 1711-112

다만, 주소 데이터는 추후 업데이트에 따라 최대 길이는 달라질 수 있습니다.
2017년 8월 4일 기준 제일 긴 주소이지, 이후에도 그럴 것이라는 보장은 없으니, 사이즈를 좀 크게 잡으시는게 좋아보입니다.

저희 가이드 페이지의
속석 부분 oncomplete부분에서 내려주는 데이터에 대한 정보 참고 부탁드립니다
"sido"라는 변수로 제공중입니다.

감사합니다.
