### ISSUE TITLE
도로명 주소 클릭시 지번주소도 자동 입력되게 하려면?

### ISSUE THREAD

**Issue by nightkarld** [daumPostcode/QnA#196]
지번주소 클릭시에는 도로명주소를 자동으로 넣어주는데
도로명 주소를 클릭하면 도로명 주소만 들어가고 마네요.
도로명 주소를 클릭하면 지번주소도 자동으로 넣어주려면 어떻게 해야 하나요?

**Comment by daumPostcode** [comment]
@nightkarld 
네~ 안녕하세요~

저희 API에서는 지번주소 클릭시 자동으로 night님의 홈페이지의 input박스에 들어가게 해주는 기능은 없습니다.
oncomplete함수의 내부 구현사항은 오로지 이용하시는 개발자의 몫입니다.

저희 샘플은 단순히 저희 가이드페이지에 맞춰서의 샘플만 제공할뿐, 모든 홈페이지에 적용되는 사항이 아닙니다.

저희 가이드페이지의 oncomplete부분의 내려주는 데이터항목 부분을 참고하여, 직접 구현하시면 됩니다.
userSelectedType과 addressType부분을 참고하셔서 테스트 해보시면 구현 가능하실거에요~

가이드 페이지를 참고해 주세요.
