### ISSUE TITLE
웹애플리케이션 프레임워크를 사용하는 서버에 api 에라

### ISSUE THREAD

**Issue by fh20** [daumPostcode/QnA#197]
서버쪽에 Express 프레임워크에 node js 로  http 서비스를 사용하고 있는데
서버에 아이피로 접속해서는 잘 사용하고 있었는데 아이피 대신 ***.***.co.kr로 변경했더니
서비스를 띠우지 못하고 있습니다.
어떻게 해야 할까요?

**Comment by daumPostcode** [comment]
@fh20 
네~ 안녕하세요~

저희 우편번호 서비스를 말씀하시는 건가요?
저희 우편번호 서비스는 client단에서 실행되는 js api라서 어떤 서버를 사용하는지와는 무관합니다.
서비스를 띄우지 못하고 있다는 말이 너무 포괄적이라 답변을 드리기가 예매하네요;;
스샷이나, 정확한 현상을 설명해 주시면 고맙겠습니다;;
