### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by cocus00** [daumPostcode/QnA#198]
주소검색시 내부 데이터 활용을 위해서
읍면동일련번호 와 도로명일련번호가 필요합니다.
변환 제공 되는 항목에 추가해서 받을수 있을까요?

**Comment by daumPostcode** [comment]
@cocus00 

네~ 안녕하세요~

현재로써는 저희가 내리고 있는 roadnameCode, bcode, buildindCode외에 추가적으로 데이터를 내리진 않습니다.
이는 원하시는 데이터가 정확히 어떤 것인지 (범용적인 이름과 예시포함) 알아야 하며, 또한 저희 내부적으로 논의를 해서 결정을 해야하는데요, 이는 데이터부터 검색엔진, 서비스 서버, JS API까지 모두 수정이 되어야 되는 상황으로써 현재로써는 좀 힘들 것 같습니다;;

저희 가이드 페이지에서 제공하는 데이터 리스트가 있는데, 이를 보시고 확인 하신 후에, 필요한게 없으시다면, 행자부REST API를 이용하시는게 더 좋은 선택이 될 것 같습니다.

도움을 드리지 못해 죄송합니다.
