### ISSUE TITLE
부산광역시 기장군 기장읍 대라리 911번지 주소추가

### ISSUE THREAD

**Issue by hwangmoa** [daumPostcode/QnA#199]
다음 지역 검색시에 검색되는데요.
주소 검색되게 적용 부탁드립니다.

**Comment by daumPostcode** [comment]
@hwangmoa 
네~ 안녕하세요~

저희 우편번호 서비스는 도로명 검색 시스템이며,
도로명이 할당된 주소만 검색이 됩니다.

저희 다음지도 서비스는 통합 주소 검색 서비스이며,그래서 도로명이 없는 주소도 검색이 되는거라서, 저희와 목적이 좀 다릅니다.

말씀해 주신 "부산 기장군 기장읍 대라리 911" 이 주소는 현재 도로명 주소가 발급되지 않은 주소입니다.
![2017-08-08 12 30 38](https://user-images.githubusercontent.com/20675065/29055124-8e1470a2-7c35-11e7-8490-b345748c8af4.png)
<위 그림은 행자부 도로명검색 시스템 검색결과>

위 그림처럼 행자부 사이트에서도 검색이 되지 않습니다.
행자부 사이트의 고객센터에 들어가셔서 말씀하신 주소의 도로명 주소 발급 신청을 하셔서 정식 발급이 되면, 저희 서비스에도 반영이 되니 참고바랍니다.
저희 [FAQ 1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)에도 해당 내용이 적혀져 있으니 확인 부탁드립니다.

감사합니다.
