### ISSUE TITLE
도로명 주소 검색이 안돼요

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#2]
경기도 군포시 대야미동 233

도로명 주소 확인 부탁드립니다.

현재 경기 군포시 대야미동 231-10
         경기 군포시 대야미동 231-11
만 검색됩니다.

**Comment by daumPostcode** [comment]
@dysong1 
dysong1님 안녕하세요~
네~ 먼저 **경기 군포시 대야미동 231-10, 경기 군포시 대야미동 231-11**의 경우에는 **경기 군포시 호수로 334-13** 라는 도로명 주소로 발급이 되어 있는 상태입니다. 그래서 검색이 되는 것이구요.
![s1](https://cloud.githubusercontent.com/assets/20675065/17847336/6b862178-6888-11e6-83fb-fcb09c91070c.png)

주소가 없다고 말씀해 주신 **경기도 군포시 대야미동 233** 주소의 경우, 현재 
![s2](https://cloud.githubusercontent.com/assets/20675065/17847395/b4bf2470-6888-11e6-96f8-52381089573c.png)
위 스샷과 같이 행자부 도로명검색 시스템에도 검색이 되지 않습니다.

이 경우에는 저희 [FAQ 1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다) 을 참고하여 주시기 바랍니다.

감사합니다.
