### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by kimclber** [daumPostcode/QnA#20]
Daum의 우편번호 API를 잘 사용하고 있습니다,
좋은 API 제공에 매우 감사합니다.

현재 서비스중인 페이지가 다국어를 지워해야할 상황에 놓여 문의드립니다.

한글주소 검색후 영문변환은 가능하나, 영문으로 주소를 조회하는 기능은 지원되지 않는것갑습니다.
제가 미처 알지 못한부분이 있는것인지, 아니라면 차후 지원가능성에 대하여 문의드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@kimclber 
네~ 안녕하세요.
네 아쉽게도 영문으로 조회하는 기능은 없습니다. 
현재로써는 차후 영문 지원이 가능할지는 확실하지 않은 상황이라 추후 지원여부에 대해서도 말씀드리기 어려울 것 같습니다;
