### ISSUE TITLE
장애가 생긴듯합니다.

### ISSUE THREAD

**Issue by khs711** [daumPostcode/QnA#200]
카카오친구도 등록했는데 특별한 얘기가 없길래

혹시하는 마음에 글 남겨봅니다.

확인 부탁드려요!

**Comment by daumPostcode** [comment]
@khs711 
네~ 안녕하세요~

네; 금일 11시 40분부터 검색엔진쪽에 장애가 발생했습니다;;
검색엔진은 저희쪽 관할이 아니다 보니; 이슈 확인 및 처리에 시간이 걸린점 양해부탁드립니다.
현재는 서비스 정상 복구 되었습니다.

그래서 현재 1:1채팅 기능을 활성화 하였습니다. 이후 장애관련 이슈에 대해서는 1:1채팅으로 알려주시면 더 빨리 대응을 하도록 하겠습니다.

아무튼 불편을 드려 죄송합니다.
