### ISSUE TITLE
우편번호 서비스 장애생겼습니다. 빨리 복구해주세요.

### ISSUE THREAD

**Issue by hanna0056** [daumPostcode/QnA#201]
우편번호 서비스 장애생겼습니다. 빨리 복구해주세요.
언제쯤이나 복구 될까요?
지난번에도 한번 그러더니 이번에 또 그렇네요.

**Comment by daumPostcode** [comment]
@hanna0056 
네~ 안녕하세요~

네; 금일 11시 40분부터 검색엔진쪽에 장애가 발생했습니다;;
검색엔진은 저희쪽 관할이 아니다 보니; 이슈 확인 및 처리에 시간이 걸렸는데요.
현재는 서비스 정상 복구 되었습니다.

그래서 현재 1:1채팅 기능을 활성화 하였습니다. 이후 장애관련 이슈에 대해서는 1:1채팅으로 알려주시면 더 빨리 대응을 하도록 하겠습니다.

아무튼 불편을 드려 죄송합니다.
