### ISSUE TITLE
현재 검색 데이터 베이스가 모두 날라 간건가요? 

### ISSUE THREAD

**Issue by Davincl** [daumPostcode/QnA#202]
주소 어느 곳이든 되지 않습니다...

**Comment by daumPostcode** [comment]
@Davincl 
네~ 안녕하세요~

우려하시는 데이터베이스가 모두 삭제가되는 장애는 아닙니다.
11시 40분 정보부터 통합검색 검색엔진쪽에서 오류가 발생했으며, 저희 서비스 역시 백단에서 통합검색 검색엔진을 사용하기 때문에 연결되서 장애가 난걸로 확인됩니다.

현재로써는 정상 복구 되었고, 기존과 동일하게 이용가능 하십니다.

그래서 현재 1:1채팅 기능을 활성화 하였는데요.
이후 장애관련 이슈에 대해서는 1:1채팅으로 알려주시면 더 빨리 대응을 하도록 하겠습니다.

아무튼 불편을 드려 죄송합니다.
