### ISSUE TITLE
바이바이

### ISSUE THREAD

**Issue by ilovenaver** [daumPostcode/QnA#203]
터짐..

**Comment by daumPostcode** [comment]
@ilovenaver 

네~ 안녕하세요~

11시 40분 경에 15분 정도 검색엔진쪽 장애가 발생하였습니다.
해당 검색엔진을 사용하는 모든 서비스에서 연관되어 장애가 발생하였는데요.
엔진이 저희쪽 관할이 아니다보니 이슈확인 및 처리에 시간이 걸린점 죄송합니다;;

앞으로 더욱 더 빠른 대응을 위해 1:1 채팅을 활성화 하였으니,
장애 관련 문의는 카카오톡으로 보내주시면 감사하겠습니다.
플러스친구는 가이드페이지 하단에 적혀 있으니 참고부탁드립니다.
