### ISSUE TITLE
주소 검색이 안됩니다...

### ISSUE THREAD

**Issue by pkt0310** [daumPostcode/QnA#204]
전국 주소가 검색되지 않습니다... 빨리 복구해주세요 ㅠㅠ

**Comment by daumPostcode** [comment]
@pkt0310 
네; 안녕하세요~

네 11시 40분경 검색엔진 오류가 발생하여 해당 검색엔진을 사용하는 연관된 서비스들 모두 장애가 발생을 하였습니다.
대략 15분 정도 지속됬고, 현재는 서비스 정상화 되었습니다.
불편을 드려 죄송하게 생각하며

좀 더 빠른 대응을 하고자 1:1 채팅을 활성화 하였습니다.
가이드페이지 하단에서 플러스 친구를 등록하시면 이용가능 하며,
장애 발생시 카톡으로 채팅을 보내주시면 될 것 같아요;;

아무튼 불편을 드려 죄송합니다 ㅜ.ㅜ
