### ISSUE TITLE
주소 검색이 안됩니다.

### ISSUE THREAD

**Issue by euglove3** [daumPostcode/QnA#205]
빨리 복구 부탁드립니다.
서비스 하는 업체 여러군데 사용 중입니다.

**Comment by daumPostcode** [comment]
@euglove3 
네! 현재 11시 40분부터 약 15분 정도 장애가 발생하였습니다.

저희쪽 서버 문제는 아니고, 타 팀 검색엔진의 오류로 확인이 되었고, 현재 정상 복구 되었습니다.
장애 발생 후, 이슈 확인 및 처리하느라 플러스 친구로 장애알림을 보내드리지 못한 점 죄송하게 생각합니다;;

앞으로 서비스 안전성을 위해 최선을 다하겠습니다.

그래서 앞으로는 장애와 관련 서비스 안전성 이슈는 플러스 친구(공식 가이드페이지 하단의 플러스친구를 카톡으로 등록해주세요)로 1:1채팅을 보내 주시면 됩니다.

다시한번 불편을 드려 죄송합니다.
