### ISSUE TITLE
서비스 장애 시 즉시 응대를 위한 카톡 1:1 채팅 허용 요청

### ISSUE THREAD

**Issue by milkoo00** [daumPostcode/QnA#206]
안녕하세요.
금일(8월 8일) 오전 11시 40분 쯤 우편번호 찾기 서비스에 장애가 잇었습니다.
다음 고객센터로 문의를 해도 본 QnA를 통해서만 문의 해 달라고 하는데...
카카오톡 플러스 친구에서 1:1 채팅이 가능하도록 해주세요.
서비스를 이용하는 입장에서 답답합니다.

**Comment by khs711** [comment]
1:1문의를 봇 처리하여 장애발생 안내 등이 자동으로 처리되면 더 좋을 듯 합니다.
장애발생 공지, 복구 공지도 안뜨고... 저도 많이 답답했습니다. ㅠㅠ

**Comment by daumPostcode** [comment]
@milkoo00 
네; 현재 해당 지연 문제 확인되어, 1:1 채팅을 활성화 하였습니다. 
기존과 이슈는 동일하게 이 게시판에 적어주시면 되고, 장애와 관련된 서비스 안전성 문제는 1:1채팅으로 보내주시면 바로 대응 하도록 하겠습니다.

@khs711 
네; 추후 해당 기능에 대해서 개발을 해보도록 해보겠습니다;; 전사에서 지원해 주는것은 채팅만 지원되서; 제가 만들어야 될것 같아요;; 아무튼 장애가 난 시간동안 대응을 해드리지 못한점 죄송합니다 ㅜ.ㅜ


-----------
11시 40분경 발생한 장애는, 저희쪽 서버문제는 아니고, 타 팀 검색엔진의 오류였습니다.
이슈 확인 및 처리에 시간이 걸려서; 제가 옐로아이디를 보내야 된다는걸 깜빡 잊어버렸네요;;

오전부터 불편을 드려 죄송하고, 앞으로 서비스 안전성을 위해 최선을 다하겠습니다;

**Comment by khs711** [comment]
장애발생 시각이 20분경부터 38분까지입니다.
빠른 대응 감사드립니다. ^^

**Comment by daumPostcode** [comment]
@khs711 
내부에서 제가 연락 받고, 장애 체크했던 시간이 40분이었는데;;

20분 부터 였군요... ;; 앞으로 장애가 발생하면; 채팅으로 보내주시면 바로 대응해 드리도록 하겠습니다.

감사합니다.

**Comment by milkoo00** [comment]
답변 감사드립니다.
