### ISSUE TITLE
정상화 된건가요?

### ISSUE THREAD

**Issue by banminseok** [daumPostcode/QnA#207]
정상화 된건가요?

**Comment by daumPostcode** [comment]
@banminseok 
네 안녕하세요

현재 12시 경에 정상화 되었습니다.
만약 정상적으로 검색이 되지 않는다면, 브라우저의 캐시를 한번 삭제하신 후에 이용해 보시면 정상 동작 할거에요.

불편을 드려 죄송합니다.
