### ISSUE TITLE
안드로이드 웹뷰에서 팝업방식 작동하지 않는 문제

### ISSUE THREAD

**Issue by ubfspringx** [daumPostcode/QnA#208]
좋은 서비스 무료로 사용할 수 있도록 해주셔서 감사합니다.

xe로 제작된 홈페이지와 연동되는 xe푸시앱 솔루션 개발자인데, 
xe가 자체적으로 다음의 우편번호 서비스를 이용하기 때문에 이 오류는 꼭 해결되어야 하는 오류입니다.

이전 이슈내용들을 보니, 웹뷰의 경우에는 팝업방식을 사용하지 않는 것이 좋다고 권하셨지만, xe코어쪽에서는 모바일에서 여전히 팝업방식을 고집하고 있기 때문에, 부득이하게 여기에 문의하게 되었습니다.

중요한 것은 웹뷰에서 주로 구버전, 저성능 폰에서는 문제없이 잘 동작한다는 것입니다.

그런데 정상적으로 onCreateWindow 메소드를 통해 javascript -> window.open 이 정상적으로 동작하게끔 했음에도 불구하고 최신의 고성능 폰에서만 자주 빈화면으로 팝업이 뜨고 있습니다. (아주 가끔씩 정상적으로 동작합니다.)

확인하시는 방법은 구글플레이에 'xe푸시앱' 검색하셔서 설치하시고 회원가입누르시고 아래쪽에, 주소 버튼 누르시면 이 문제를 확인하실 수 있습니다. 

아마도 제생각에는 웹뷰에서 새창을 띄워서 처리하는 과정하고 자바스크립트처리과정하고 뭔가 엇박자가 나고 있는 것이 아닌가 추측해봅니다.

답변 기다릴게요. 감사합니다. ^^

**Comment by ubfspringx** [comment]
원인을 찾았습니다.
onCreateWindow에서 
childview webview를 생성하고, childview webview를 root view에 add하는 과정이 있게 되면 빈화면이 나오네요.
다른 분들을 위해 해결방법을 알려드리자면,  onCreateWindow에서 childeview = new Webview(context); 이런식으로 생성하지 마시고, 앱실행시 onCreate에서 childview를 생성하고, 웹뷰관련 모든 초기 셋팅을 끝낸다음에 root view에 미리 추가해놓습니다. 그리고 메인뷰를 bringtoFront를 사용하여 최상단에 둠으로써 그 밑에 childview가 숨어있어서 안보이게 합니다.
onCreateWindow에서는 그저 childview를 bringtoFront 하시든지 가리고 있던 메인뷰를 setVisibility(View.GONE); 하든지 해서, 숨어있던 childview가 그대로 나오도록 해야 합니다.

**Comment by daumPostcode** [comment]
@ubfspringx 
네~ 안녕하세요~

앱의 웹뷰같은 경우에는 제가 잘 아는 분야가 아니라; 어떻게 답변을 드리면 좋을지 생각하고 있었는데요;
해결책까지 제공해 주셔서 감사드립니다.

추후 비슷한 이슈 등록시 참고하도록 하겠습니다.
도움을 주셔서 감사드립니다 ^^ 즐거운 한주 보내세요~

**Comment by pleasantlife** [comment]
@ubfspringx 
혹시 이 문제 해결법에 대해 조금 자세하게 알려주시거나
해결된 소스코드를 볼 수 있을까요..

embed 메소드로 해결하려고 했으나 도저히 깔끔하게 해결이 되질 않네요..ㅠㅠ
