### ISSUE TITLE
검색 후 리턴값에 대해 질문 드립니다 :)

### ISSUE THREAD

**Issue by ritachoibbk** [daumPostcode/QnA#209]
리턴값을 따로 받아올 수 있는지 여부에 대해서 질문 드립니다.

아니면 언제나 전체 주소만으로 리턴되는지, 각각 받아올 수 있는지 알고 싶습니다. 후자가 가능하다면 각 값에 해당되는 리턴값 중에서 예외가 발생하는 경우가 있는지도 알고 싶습니다. 

더 자세히 설명을 덧붙이자면,
Province
City
District
Street/block
와 같이 나눠서 반드시 상황이라면 리턴값이 일정하게 받아올 수 있는 방법을 제시해 주신다면 감사하겟습니다. 

감사합니다. :)

**Comment by daumPostcode** [comment]
@ritachoibbk 

내리는 데이터 속성은
https://spi.maps.daum.net/postcode/guidessl#attributes
저희 가이드 페이지에 있는 oncomplete부분에 명시되어 있습니다. 해당 값 외에는 따로추가적으로 내리는 값은 없습니다.

제가 영문주소의 표기법에 대해서는 정확히 잘 몰라서 아래 답변이 이상할 수 있습니다.
province는 저희 데이터중 sido 부분이 맞을 수도 있을 것 같고
city는 sido 또는 sigungu 데이터가 맞을 수 있습니다. 광역시/특별시/특별자치시(도)/일반도시 에 따라 서로 내려가는 데이터가 다릅니다.
district의 경우 이게 bname이 맞을 것 같기도 한데; 정확하진 않네요;
street의 경우엔 roadname 인 것 같으나, 건물번호는 따로 분리해서 내리지 않습니다. 원본 주소에서 split하셔야 합니다.

가이드 페이지를 봐보시고 직접 확인해 보시는게 좋을 것 같습니다;;

**Comment by ritachoibbk** [comment]
건물번호가 제주특별자치도 서귀포시 안덕면 중산간서로1615번길 214-30 인 경우에 뒤에 따라오는 214-30을 의미하는 게 맞나요?

**Comment by daumPostcode** [comment]
@ritachoibbk 
네~ 맞습니다. 
지번주소로 비교하면 번지 부분이 도로명주소의 건물번호 입니다.
