### ISSUE TITLE
우편번호 api만 로딩 불가

### ISSUE THREAD

**Issue by as977606** [daumPostcode/QnA#21]
http://dmaps.daum.net/map_js_init/postcode.v2.js

이것을 로딩해서 쓰는데, 저희 페이지가 안열려서 보니 해당 PC에서는 
위 스크립트를 아예 못가져오고
따로 익스에서 주소치고 들어가면 페이지를 표시할수 없다라고 나오네요

물론 https://postcode.map.daum.net/guide 여기도 접속이 안되구요

하지만 다음 메인페이지나 다른 웹싸이트 네이버 등등은 접속이 잘됩니다.

왜 유독 위 주소들만 접속이 안되어서 스크립트를 가져오지 못할까요?

특별히 보안상에 문제가 있는것도 아닙니다.

어느부분을살펴봐야 할까요?

win7 한글 ie11 / 크롬에서도 접속안됩니다.

저희 아이피 주소는 58.239.228.202 입니다.

답변을 주시면 감사드리겠습니다

**Comment by daumPostcode** [comment]
@as977606 
네~ 안녕하세요~

저희 우편번호 서비스의 경우 http용 서비스 URL과 https 용 서비스 URL이 서로 다릅니다.

일단 가이드 페이지의 경우 
http : [http://postcode.map.daum.net/guide](http://postcode.map.daum.net/guide)
https : [https://spi.maps.daum.net/postcode/guidessl](https://spi.maps.daum.net/postcode/guidessl)

이며 해당 사이트에 접속하시면 저희 api의 호출 URL도 변경됩니다.

http : [http://dmaps.daum.net/map_js_init/postcode.v2.js](http://dmaps.daum.net/map_js_init/postcode.v2.js)
https : [https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js](https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js)

이며, 아마 따로 익스에서 주소치고 들어갔을때 표시할 수 없다는 것이 https://dmaps.daum~~~ 이렇게 입력하셔서 그런게 아닐까 합니다;;

http용과 https용 가이드페이지의 경우 가이드 페이지의 상단 프리뷰 부분의 왼쪽 부분에 글로 설명되어 있는데, 잘 안보이셨나 보네요; 가이드페이지에서 해당 문구를 좀 강조하도록 하겠습니다.

그럼 즐거운 추석 보내시구요~ 다른 문의사항 있으시면 언제든 이슈등록 부탁드립니다~

감사합니다.

**Comment by as977606** [comment]
http://dmaps.daum.net/map_js_init/postcode.v2.js

이렇게 등록하였습니다.

ㅜㅜ
![guest 7 58 239 228 202 d_20160913172439](https://cloud.githubusercontent.com/assets/22167654/18466527/039f953e-79d7-11e6-9414-52cc5c79a1b2.jpg)

다른곳은 다 들어가지나 여기에만 못들어가는 이유가 무엇일까요?

빠른 답변감사드립니다 ㅠㅠ

**Comment by as977606** [comment]
아 참고로 저희 프로그램을 쓰는 고객중에 여러분은 접속이 되나 이 고객한분만 접속이 안됩니다 ㅡㅡ

**Comment by daumPostcode** [comment]
@as977606 
저희 쪽에서 따로 제한을 할 수도 없고, 어떠한 처리도 하지 않았는데 이상하네요, 만약 저 도메인만 접속이 안되는 것이라면, 혹시 http://map.daum.net 서비스에서도 지도가 뜨지 않을 건데요. 
이부분도 혹시 확인 가능하실까요?

**Comment by as977606** [comment]
아 그럽습니다.
![guest 7 58 239 228 202 d_20160913173211](https://cloud.githubusercontent.com/assets/22167654/18466790/134e0dde-79d8-11e6-9d17-12c4a828195d.jpg)


이렇게 지도가 표시되지를 않습니다.... 흠..

**Comment by daumPostcode** [comment]
@as977606 
엇;;; 쉽게 해결하기 어려운 이슈가 나타났군요 ㅜ.ㅜ
일단, 브라우저 초기화 (캐쉬나 불필요한 쿠기)를 진행해 주시고, 따로 보안프로그램이나 툴바같은 것이 있다면, 혹시나 해당 프로그램들이 dmaps.daum.net을 블락하고 있을 수도 있습니다.

또한 예전에 흡사한 CS가 들어 왔었는데요. 공유기를 이용할 경우 공유기에서 먼가 문제가 생겨서 dmaps.daum.net을 불러오지 못한 경우도 있었는데요, 이부분 또한 공유기 재시작을 통해 해결이 되긴 했습니다.

정확히 어떻게 저런 현상이 생기는가에 대해선 원인을 알아내진 못했지만, 위와 같이 해결이 된 적이 있으니, 한번 진행해 주시면 감사하겠습니다.

**Comment by as977606** [comment]
넵 답변 너무나도 감사드립니다. 늦은시간에 이렇게 답변주셔서 컴퓨터 문제인지 공유기인지

한번 확인해보도록 하겠습니다. 감사합니다 ㅠㅠ

**Comment by daumPostcode** [comment]
@as977606 
네 ㅎㅎ 아닙니다. ^^

제가 컴퓨터 앞에 계속 있으면 부족하지만 대응을 계속 해드릴 순 있는데, 이제 곧 시골을 내려가야 되서,, 만약 처리가 안된다면, 이슈 등록 해주시면 확인해 보도록 할께요~; 다만 명절이라;;;; 확인이 좀 오래 걸릴 수 있는 점은 양해 부탁드립니다;;;

그럼 즐거운 추석 보내세요~~
