### ISSUE TITLE
SSL 스크립트 로딩이 너무 느립니다.

### ISSUE THREAD

**Issue by imjanghyuk** [daumPostcode/QnA#210]
동적 로딩과 보안 연결을 위해 아래의 URL을 사용하고 있습니다.
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false
그런데 현재 스크립트 로딩이 너무 느립니다. 1분이 넘게 걸리고 있습니다.
LTE를 통해서도 로딩을 해 봤는데 마찬가지인 것을 보면 인터넷 회선의 문제만은 아닌 것 같습니다.
확인 부탁 드립니다.

**Comment by daumPostcode** [comment]
@imjanghyuk 
넵~ 안녕하세요~

해당 이슈는 제가 인지하기전에 서버측 담당자 분께서 처리를 완료를 하여; 제가 따로 알림을 보내진 않았습니다.

저희가 사용하는 ssl.daumcdn.net이 전사 공용인데요.
이 공용서버에 문제가 생겨서 일시적으로 로딩이 지연된 것으로 확인이 됩니다.

해당 서버는 저희뿐만 아니라 카카오 대부분의 서비스에서도 많이 사용하고 있어서 같이 오류가 발생했네요;; 다만 저희 서비스에 대한 오류는 바로 안들어오고, 타 서비스 장애로 등록되어 제가 확인이 좀 늦었습니다.

현재는 모두 완료디어 정상 이용 가능하십니다.

다시한번 불편을 드려 죄송합니다.
