### ISSUE TITLE
아이폰에서 iframe으로 검색창을 띄워 검색시... 결과가 표시되지 않습니다.

### ISSUE THREAD

**Issue by yellowin** [daumPostcode/QnA#211]
아이폰에서 iframe으로 검색창을 띄워 검색을 시도하면 아래 이미지처럼 결과과 표시되지 않고...
전체 회색으로 아무것도 표시되지 않는현상이 발생됩니다.
확인결과 검색결과는 나오는데... 결과위에 레이어가 있는것 같습니다. 아무곳이나 터치하면 주소가 선택되어 지거든요. T.T

아래 이미지처럼 회색으로 뜨구요. 결과가 나오긴 나온겁니다. 아무것이나 잘터치하면 주소가 선택되고 레이어팝업창이 닫힙니다.
참고로 cordova inappbrowser에서 띄운화면입니다.
버그에 대한 해결방안이 있다면 알려주세요.

![aaa](https://user-images.githubusercontent.com/8730963/29604145-86d39e7e-8821-11e7-9cb1-02b7ffa24028.png)

**Comment by yellowin** [comment]
참고로... cordova로 패키징한 하이브리드앱이구요.
inappbrowser에서 띄운겁니다.
해당서비스는 도메인url이 있는 웹서비스이구요.

**Comment by daumPostcode** [comment]
@yellowin 
네~
인앱브라우저에서 띄운거라면, 도메인 관련 문제는 아니군요.
그렇다면, 저 페이지에 접속 할 수 있는 도메인이 있을 것인데; 이를 일반브라우저에서도 확인해 보셨나요??
현재 오류가 뜨고 있다던지 위에 겹쳐있는 추가 레이어가 있다던지, 아니면 렌더링 오류로 reapint가 안된것인지 코르도바 패키징 화면보다는 확인이 쉬우실 거에요.
대략 느낌으로는 렌더링 오류 같아 보이며, 일반브라우저에서 정상동작한다면; 코르도바 인앱브라우저의 버그 일 확률이 큽니다. iframe관련 버그일 수 있습니다.

지금은 추정밖에 할 수가 없는데;
혹시 제가 접근 할 수 있는 도메인이 있으시다면; ftdev5@daum.net 으로 메일로 보내주셔도 되고, 일부 코드를 보여 주셔도 됩니다. 다만 런타임 오류의 경우에는 제가 실행을 할 수 있어야 확인이 더 빠르니 일부코드라도 실행이 되는 정도의 코드를 보내 주시면 감사하겠습니다.

**Comment by yellowin** [comment]
빠른답변 감사합니다.
pc나 아이폰의 모바일웹브라우져(사파리)에서는 정상인데... cordova로 패키징된 하이브리드앱에서만 발생하는 현상입니다.
근데 희한한건... 해당 주소검색팝업에서 다음우편번호검색 api 가이드화면으로 이동이 가능한데요.
그 화면에서는 또 정상입니다.

렌더링될때 html 내에 먼가 문제가 발생되는 부분이 있는것 같은데요.
제가 웹쪽 개발자가 아니라서~ 직접 소스를 수정하면서 확인할 수가 없는 상황입니다. TT
일단 도메인은 ftdev5@daum.net  메일로 보내드리겠습니다.

참고로 사용된 cordova 및 인앱브라우져 버전입니다.(모두 최신버전입니다.)
cordova 버전 : 7.0.1
inappbrowser 버전 : 1.7.1

혹시 모르니 인앱브라우져 버전을 다운시켜 적용해보고 잘 되면 다시 코멘트달겠습니다.

**Comment by daumPostcode** [comment]
@yellowin 
아 저두 앱개발자가 아니라 정확히 코르도바 인앱브라우저에서 해당 오류를 발생시키는지는 모르겠네요;;
대부분 repaint 오류는 position, iframe 등의 스타일속성이나 태그 사용시 간혹 발생하는데요, 말씀하신 것처럼 인앱브러우저의 알려진 버그인지 확인하시고 버전을 바꿔 보시는 것을 추천드립니다;;

웹브라우저에서도 안되면; 제가 잡아볼려고 했는데;; 코르도바 안에서 발생한 문제는 좀 어려울 것 같아요;;

**Comment by daumPostcode** [comment]
@yellowin 
아마 해결이 안될 확률이 높은데; 레이어로 position:fixed로 띄우지 마시고, 끼워넣기 예제를 참고하여 본문에 바로 삽입을 해보실 수 있으실까요?

**Comment by yellowin** [comment]
네 답변 감사합니다.
일단 인앱브라우져 버전을 다운시켜 여러가지 버전으로 적용해봤지만 마찬가지 현상이 발생했습니다.
이상한점은 제대로된 주소로 검색을 하면 제대로 표시될 확률이 높구요~ 이상한주소로 검색결과가 없다면 아예 표시되지 않는현상이 발생합니다.

말씀해주신대로 position:fixed 말고... 끼워넣기로 적용을 해보도록 하겠습니다.
