### ISSUE TITLE
Windows 10 에서 C# Windows Form에 WebBrowser에서 API를 사용하려고 합니다.

### ISSUE THREAD

**Issue by Zerglrisk** [daumPostcode/QnA#212]
inner html로 html 파일을 만들어 webbrowser에 navigate하여 보여주고 있습니다. html에 
팝업을 이용하여 도로명 주소와 지번 주소 모두 보여주기 에제 소스를 넣었고, open()의 형태에서는 팝업으로 IE로 열리며 주소 검색 후 나오고 주소를 클릭하면 꺼지지도 않고, 값이 들어가지지도 않습니다. 그래서 embed쪽 형태로 페이지를 끼워넣기로 열어보아도 여전히 값이 안들어갑니다. 
new daum.Postcode({ 내부 html파일에서 부분코드가 breakpoint에서 멈추질 않습니다. 
방법이 있나요?

스크립트를 동적으로 로딩해야 하는 경우의 부분의 코드도 써보았지만 안되네요

**Comment by daumPostcode** [comment]
@Zerglrisk 
네~ 안녕하세요~

저희 서비스는 CORS 기능중에 하나인 postMessage를 사용하여 이종 도메인간에 데이터를 전달하는 방식을 이용합니다.
검색화면은 저희쪽 postcode.daum.net이고, 이용하시는 사이트는 모두 다르기 때문이죠.
웹서버 기반의 서비스이며, html파일을 임베딩하여 동작하는 프로그램에서는 동작하지 않습니다.

저희 [FAQ 9번](https://github.com/daumPostcode/QnA#9-모바일앱에서도-사용할-수-있나요)과 10번을 참고하시기 바랍니다.

이 문제가 아니라면 oncomplete 콜백함수 부분에서 에러가 나는 상황으로, 이 함수 내부 구현은 개발자분의 몫이기 때문에 오류를 찾아서 수정하시면 될 듯 합니다.

**Comment by Zerglrisk** [comment]
postcode.v2.js파일  확인해보니 로컬로 있으면 url이 어긋나게 값을 내부 170517.js파일로 전달해버려서 동작하지를 않는거군요. 
guide 창에 있는 예제 우편 검색을 이용해서 검색 후 돌아오면 바로 값넘겨줄 수 있는 자바스크립트가 있었으면 편하겠네요. iframe으로 해당 페이지 열어서 파싱하는게 답일듯 합니다.
