### ISSUE TITLE
로고 관련 문의드립니다

### ISSUE THREAD

**Issue by ritachoibbk** [daumPostcode/QnA#213]
안녕하세요

혹시 주소 검색 사용 시 로고를 가릴 경우 어떤 제약이 있나요?

![image](https://user-images.githubusercontent.com/30692139/29607090-173c290a-882b-11e7-9adf-a3d8d6e2f7ff.png)

구찌 사이트를 확인해 보니까 로고 없이 주소 API를 사용 중인 걸로 보여서 api 사용 시에 유료로 전환하여 사용하는 것인지 알고 싶습니다

그리고 만약에 로고를 가리는 경우에 제약이 따른다면 유료로 전환하여 제약 없이 사용하는 방법이 있다면 그 부분 또한 확인해주시면 감사하겠습니다

감사합니다 :)

**Comment by daumPostcode** [comment]
@ritachoibbk 
네~ 안녕하세요~

로고의 경우 저희 쪽 자사 서비스이기 때문에 최소한의 표시를 한 것일 뿐입니다.
가이드 페이지에 보시면, 사용제한이 발생할 수 있는데요.
이부분은 제가 이 댓글에서 언제 어느때 발생한다고 확답드리긴 어렵고, 예를들어 특정 사이트가 서비스 안정성을 해치는 이슈를 발생 시키는 경우, 이용하는 사이트의 도메인을 확인하게 되는데 이때 로고가 가려져 있거나 하면 제약이 발생할 수 있습니다.(저희 서비스에 접속이 안되는 제약이라고 생각하시면 됩니다)
하지만 아직까지 이런 이슈가 발생하지 않았고, 서비스 제약을 가한 도메인은 없습니다.

추가적인 유료모델은 없습니다.

그리고 말씀해주신 구찌사이트에서는 스크린샷만 봐서는 저희쪽 API를 사용하고 있지는 않아 보입니다.
행자부나 다른 업체의 REST API를 이용해서 구현한 것으로 생각이 되네요~
