### ISSUE TITLE
도로명/지번 선택시 무조건 지번으로 입력

### ISSUE THREAD

**Issue by cgrking2** [daumPostcode/QnA#214]
자주묻는 FAQ 16번에 위 제목처럼 도로/지번 선택시 무조건 도로명이 넘어가게하는건 있더라구요

혹시 반대로 도로/지번 선택시 무조건 지번으로 입력되게하는것도 있을까요?

**Comment by daumPostcode** [comment]
@cgrking2 
네~ 안녕하세요~

저희 서비스에서 내리는 데이터는 지번주소와 도로명주소가 한쌍입니다.
가이드 페이지 oncomplete함수 설명 부분에 내리는 데이터가 정리되어 있습니다,

FAQ16번을 읽어 보셨다면, 거기에는 roadAddress, autoRoadAddress가 언급되어 있죠?
이를 jibunAddress autoJibunAddress로 바꿔서 해석하시면 됩니다.
