### ISSUE TITLE
220-800 조회문의

### ISSUE THREAD

**Issue by goodboys100** [daumPostcode/QnA#215]
안녕하세요.
우편번호 220-800 
강원 원주시 문막읍이 다음우편번호에서는 조회가 안되는데
확인부탁드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@goodboys100 
네~ 안녕하세요~

주소의 범위가 아닌, 정확한 주소를 적어주셔야 확인이 될것 같습니다. 문막읍의 어떤 주소가 조회가 안되는지 확인이 어렵네요;;

다만 느낌상, 새우편번호가 할당이 되어 있지 않아서 검색이 안되는것 같은데요.
www.juso.go.kr 행자부 도로명 검색 시스템에 들어가셔서 원하시는 주소를 검색해 보신후, 결과가 나오는지 확인 부탁드립니다. 해당 사이트에서 검색이 되지 않으면, 저희 우편번호서비스에서도 검색이 되지 않습니다.

저희 서비스는 도로명주소 검색시스템으로 도로명주소가 할당되어 있지 않은 주소는 검색에저 제외됩니다.

다음 지도는 주소검색시스템으로써, 도로명/지번 상관없이 검색이 되는 것이구요.

참고 부탁드립니다.
