### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by ws12345159057** [daumPostcode/QnA#216]
아파트주소를할때 아파트를치면 결과가 나오나 동과호를 같이입력하면 안나옵니다.
해결가능하신지요??

**Comment by daumPostcode** [comment]
@ws12345159057 

네~ 안녕하세요~

아파트의 동과 호의 경우에는 상세주소라고 볼 수가 있을 것 같습니다.
도로명주소를 생성할때 아파트 건물 하나하나마다 주소를 부여하는게 아니므로, 해당 기능은 현재로써는 어려울 것 같아요. 또한 행자부에서 저희쪽으로 주는 동/층/호 정보가 매우 불확실하여; 서비스에 녹일 수가 없어서 현재까지는 해결이 어려울 것 같습니다.
