### ISSUE TITLE
모바일에서 레이어창에 주소가 잘립니다.

### ISSUE THREAD

**Issue by hooseung** [daumPostcode/QnA#218]
모바일에서 레이어로 검색시 주소가 긴 경우 크기가 고정되어 있어 아래로 떨어지지 않습니다.

해결방법이 있을까요?

**Comment by daumPostcode** [comment]
@hooseung 
네~ 안녕하세요~

답변이 늦어서 죄송합니다.

현재 저희 우편번호 서비스는 주소가 길어지면 짤리지 않고 두줄로 표시가 되도록 되어 있는데요; 현재 제일 긴 주소로 확인을 해봐도 두줄로 표시시 모두 잘 나오고 있습니다.

혹시 폰트 크기를 변경하셨을까요? 

스크린샷을 추가 가능하시면; 오류 화면을 보여주시면 좀 더 확인이 될것 같습니다.
답변 부탁드립니다.

**Comment by hooseung** [comment]
모바일에서 주소창 레이어팝업 잘림현상 첨부파일 보내드립니다.
![screenshot_2017-09-04-12-01-15](https://user-images.githubusercontent.com/31527864/30010371-3b3f2a4e-916a-11e7-8f40-e21811aa254f.png)

![default](https://user-images.githubusercontent.com/31527864/30010367-3158ae24-916a-11e7-8a10-22b6e485a131.jpg)

![default](https://user-images.githubusercontent.com/31527864/30010363-2c98fd76-916a-11e7-9d6f-ba455d9145ea.jpg)

**Comment by daumPostcode** [comment]
@hooseung 

네~ 감사합니다.
target이 되는 layer의 width가 500으로 되어 있네요;
그리고 그안에 들어가는 저희 서비스는 width:100%로 되어 있구요.
target layer의 width값을 좀 줄여주시면 될것 같습니다.

저희 공식 페이지 샘플중, 레이어 띄우기를 참고해 보시기 바랍니다.

또한 우편번호 서비스 생성자 옵션에 width/height를 %가 아닌 명확한 수치값으로도 입력이 가능하니 이부분도 참고해 주시기 바랍니다.

**Comment by hooseung** [comment]
그부분은 저희가 준게 아닌데요... 샘플에서도 모바일로 바꿔놓고 보면 위의 댓글 마지막 첨부한 이미지처럼 잘립니다.
<button type='button' class="gray" onclick="goZipOpenEvent();">주소찾기</button>
<div id="daumLayer" style="display:none;position:fixed;  overflow:hidden;z-index:198780;-webkit-overflow-scrolling:touch; word-wrap: break-word; white-space:normal">
	<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
	<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;bottom:0px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>
요렇게 불러왔을때 주소창크기가 소스 올린것처럼 잡히던데 어디에 크기를 지정할 수 있는지 알려주세요. 고맙습니다.

**Comment by hooseung** [comment]
그부분은 저희가 준게 아닌데요... 샘플에서도 모바일로 바꿔놓고 보면 위의 댓글 마지막 첨부한 이미지처럼 잘립니다.

> <button type='button' class="gray" onclick="goZipOpenEvent();">주소찾기</button>
<div id="daumLayer" style="display:none;position:fixed;  overflow:hidden;z-index:198780;-webkit-overflow-scrolling:touch; word-wrap: break-word; white-space:normal">
	<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
	<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;bottom:0px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>


요렇게 불러왔을때 주소창크기가 소스 올린것처럼 잡히던데 어디에 크기를 지정할 수 있는지 알려주세요. 고맙습니다.

**Comment by hooseung** [comment]
답변 감사합니다.

target이 되는 layer의 width가 500은 저희가 준게 아니구요 다음에서 서비스하는 부분이라 저희쪽에서 수정이 불가합니다. 

저희쪽에서 넣는 소스는 
<button type='button' class="gray" onclick="goZipOpenEvent();">주소찾기</button>
<div id="daumLayer" style="display:none;position:fixed;  overflow:hidden;z-index:198780;-webkit-overflow-scrolling:touch; word-wrap: break-word; white-space:normal">
	<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
	<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;bottom:0px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>

이렇습니다.

다시한번 확인 부탁드립니다.
