### ISSUE TITLE
 embed 함수를 콜해서 사용하는경우 style 적용문의

### ISSUE THREAD

**Issue by owensim** [daumPostcode/QnA#22]
iframe이 알아서 삽입되다보니,웹뷰로 우편번호가 연동된 화면에서 가로로 길어져서

크롬으로 소스를 보니 width:500px,height:500px;로 잡혀있더라구요

실제 저희 웹에서 코딩상으로는 <div id=schaddr"name=schaddr"></div>밖에없지만

아래는 크롬에서 검사로 본 소스입니다.

<div id="schaddr" name="schaddr"><div id="__daum__layer_3" style="position: relative; width: 500px; height: 500px; background-color: rgb(255, 255, 255); z-index: 0; overflow-x: hidden; overflow-y: auto; min-width: 300px; margin: 0px; padding: 0px;"><iframe frameborder="0" src="about:blank" style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%; border: 0px none; margin: 0px; padding: 0px; overflow: hidden; min-width: 300px;"></iframe></div></div>

**Comment by daumPostcode** [comment]
@owensim 

네~ 안녕하세요

저희 생성자 옵션중에

width, height라는 것이 있습니다. 이 속성을 이용하시면 될 것 같고, 자세한 설명은 저희 가이드 페이지 속성의 중간 부분에 적혀져 있습니다.[가이드 페이지 속성](http://postcode.map.daum.net/guide#attributes)

300px, 400px 과 같이도 적용가능하며, 100% 이렇게도 적용가능한데요. %로 입력시 embed(target)에서 target 노드의 크기에 맞춰지게 됩니다. 

한번 확인 부탁드려요~

**Comment by owensim** [comment]
new daum.Postcode({
            width: '100%',
            height: 300,
            oncomplete: function(data) { 
 
적용하였는데 안됩니다 ㅠㅠ 확인부탁드립니다!
 
 
-----Original Message-----

**Comment by daumPostcode** [comment]
@owensim 
width를 100%로 했을 경우에는 위에 제가 썼던 것처럼 embed(target)을 할때 target 노드의 width크기에 따라 우편번호 서비스의 가로 크기가 결정됩니다.
혹시 target 노드의 width가 가로로 넓은 것은 아닌지 확인 부탁드려요;; 

저희 예제들을 보셔도, embed를 이용한 예제들은 모두 width,height는 100%로 되어 있으며, target 노드의 width와 height를 조절하여 이용하고 있습니다. 이렇게 하시면 실제 적용하시는 페이지에서 저희 우편번호 서비스의 화면크기를 좀 더 쉽게 컨트롤 하실 수 있기 때문입니다.

한번 예제를 참고하셔서 수정 부탁드립니다.

**Comment by owensim** [comment]
타겟 노드도 100%로 해놓은 상태라서 ㅠㅠ..
 
&lt;div id="schaddr" name="schaddr" style="width:100%;"&gt;&lt;/div&gt; 
 
예제를 다시 보겠습니다. 이게 모바일 웹뷰에 들어가는 영역은 처음해본지라 ㅠㅠ..
 
-----Original Message-----

**Comment by daumPostcode** [comment]
@owensim 
네;; target 노드도 100%해두면, 그 target노드 또한 dom tree구조에 따라 상위 노드의 width를 상속받아 사이즈가 결정될 거에요;; 그렇기 때문에; 최상위 노드의 사이즈가 크면, 우편번호 서비스의 크기도 커질 수밖에 없습니다.

target노드의 width를 고정하셔도 되며, 그게 안되면, target노드의 상위 노드의 크기를 고정하시는게 좋을 것 같아요;
만약 가로/세로 오리엔테이션에 따른 가변적인 크기를 원하시면, 

orientation이벤트를 받아서 자바스크립트로 처리하셔도 되며, 구글링 해보시면 모바일 페이지에서의 width를 가변으로 잡는 방법이 있을 것 같아요 ^^(현재 owensim님의 사이트 구조를 모르니 추가적인 설명은 어려울 것 같네요;;)

일단 예제를 참고하시어 한번 수정 부탁드려요~ 

(이 시간 이후로는 제가 운전을 하기 때문에;(추석인지라;;;;) 답변이 좀 늦을 수 있는 점 양해 부탁드립니다 ㅜ.ㅜ)

**Comment by owensim** [comment]
옙ㅎ ㅎ 명절 잘 보내세요!!!
 
다 해보고 안되면 그때 질문드릴게요 ㅎ
 
-----Original Message-----
