### ISSUE TITLE
팝업창에서 도로명주소 선택시 지번주소 데이터를 받아오지 못하는건가요?

### ISSUE THREAD

**Issue by psyksm4818** [daumPostcode/QnA#220]
['태평샹베르'](url) 로 검색후, 도로명 주소 선택했더니,
api호출하는 자바스크립트 함수에서 data.jibunAddress를 alert창 띄워보니 데이터가 안나오네요~
지번주소 선택시에는 데이터가 나와요

사용자가 팝업창에서선택한 데이터가 무엇이든지 지번주소와 도로명주소를 모두 받고 싶습니다.
data.roadAddress 와 data.jibunAddress를 가져와서 사용하고 있는데, 혹시 제가 놓치고 있는 부분이 있는지 알고싶습니다.

![image](https://user-images.githubusercontent.com/31690365/30104856-c69812cc-9331-11e7-9079-5b5529195493.png)

**Comment by daumPostcode** [comment]
@psyksm4818 
네~ 안녕하세요~

저희가 내리는 데이터는 jibun/roadAddress를 비롯하여 더 많습니다 ㅎㅎ
저희 가이드 페이지의 속성 부분의 oncomplete 부분의 설명과 아래의 파란색 박스부분의 설명을 참고하시면 됩니다.

그리고 [FAQ 16](https://github.com/daumPostcode/QnA#16-사용자가-지번도로명-중-어떤-것을-선택하더라도-무조건-도로명-주소만-이용하고-싶은데-어떻게-해야되나요)번을 보시면, 어떤 주소를 선택하던 도로명 주소를 넣는 방법이 있는데; 이 방법을 살짝 응용하셔도 가능합니다.

확인부탁드립니다.
