### ISSUE TITLE
문의합니다.

### ISSUE THREAD

**Issue by moonjeong-kim** [daumPostcode/QnA#221]
c++ 이나 mfc 로 된 예제는 없나요?

**Comment by daumPostcode** [comment]
@moonjeong-kim 
네~
저희가 공식적으로 지원하는 플랫폼은 웹기반 서비스이며 Javascript API형태로 배포를 하고 있습니다.
그래서 C++, MFC 를 비롯하여, iOS, Android의 폰갭이나 코르도바와 같은 패키징을 통해 앱을 만드는 서비스도 공식 지원 대상은 아닌점 참고 부탁드립니다.

다만 웹뷰를 통해 저희 서비스를 띄우실 수 있는 곳에서는 사용이 가능하나, 이슈 발생시 제가 테스트가 불가능하여 대응을 해드리기가 어려운점 양해 부탁드립니다.
