### ISSUE TITLE
autoJibunaddress로 진행하는데 지번 정보가 정상으로 들어오지 않습니다.

### ISSUE THREAD

**Issue by Paranoidkr** [daumPostcode/QnA#222]
도로명 주소를 선택하거나 지번주소를 선택해도 지번 주소로 입력이 되게끔 설정해 두었습니다.
(jibunaddress 사용)

그런데 최근 "강서메트로칸"으로 검색을 하니 지번 정보를 받아오지 못해서,
검색 후 autoJibunaddress으로 정보를 받아서 진행하니 지번이 입력이 되었습니다.

그래서 잘 쓰던 중, "마곡사이언스파크뷰"로 검색을 해서 클릭을 하니 다시 지번 정보를 받아오지 않네요.
이건 어떤 이슈일까요?

**Comment by daumPostcode** [comment]
@Paranoidkr 

네~ 안녕하세요~

사용자가 어떤 데이터를 선택하던 한가지 타입만 이용을 하시려면
autoJibunAddress, jibunAddress를 둘다 사용하셔야 합니다.

[FAQ16](https://github.com/daumPostcode/QnA#16-사용자가-지번도로명-중-어떤-것을-선택하더라도-무조건-도로명-주소만-이용하고-싶은데-어떻게-해야되나요)을 참고해 주시기 바라며, 저희 가이드 페이지에 보시면 autoJibunAddress에 대한 설명이 적혀 있으니 참고 해주시기 바랍니다. oncomplete설명 아래의 하늘색 박스를 클릭하시면 보실 수 있습니다.

또는 해당 분기를 타는 코드를 적어주시면 가이드 해드리겠습니다~
