### ISSUE TITLE
영문/한글주소가 한 화면에 같이 출력되는 옵션이 있으면 좋겠습니다. 

### ISSUE THREAD

**Issue by kch2456** [daumPostcode/QnA#225]
안녕하세요. 좋은 API 제공해주셔서 손쉽게 주소검색을 처리하고있습니다. 감사합니다^^

저희는 한글주소,영문주소를 동시에 보며 참고해야 하는 시스템을 제공하고있습니다.
일일히 한글보기,영문보기를 눌러가며 주소를 확인하기에 많은 불편함이 있습니다.
한글주소 밑에 영문주소가 같이 출력되도록 할 수 있는 옵션을 만들어주실 수 없는지 여쭙습니다.

**Comment by daumPostcode** [comment]
@kch2456 
네~ 안녕하세요~~

먼저 저희 서비스를 이용해 주셔서 감사드립니다 ^^
해당 기능의 경우, 구현 자체가 어렵지는 않습니다. 단순 뷰잉에 이미 데이터도 다 존재하니까요.
다만 UI상 높이가 매우 길어질 수가 있어서, 혹시나 모를 사이드이펙트(특정브라우저 깨짐 등) 확인 작업이 필요한 정도가 있겠네요.
다만 제일 큰 이슈가 제가 아직 다른 일정 때문에 우편번호 서비스에 기능을 추가하는 것이 어려운데, 이번주에는 좀 어렵고, 다음주 중에 제가 최대한 추가해서 댓글로 말씀드리도록 하겠습니다..

일정에 대해서는 확답을 못드리는 점 죄송하게 생각합니다.., 최대한 빨리 추가할 수 있는 방향으로 노력해 보겠습니다.

의견 감사드립니다 ^^

**Comment by kch2456** [comment]
우와~ 빠른 답변 감사합니다!!
넵 기다릴께요오~ㅎㅎ

**Comment by daumPostcode** [comment]
@kch2456 
안녕하세요~

금일 요청하신 기능이 추가되어 공유 드립니다. 기다려 주셔서 감사드립니다.

해당 기능은 생성자 옵션으로 alwaysShowEngAddr 옵션의 설정으로 이용가능 하시며, 기본값은 false 입니다. 해당 기능은 true로 설정하면 항상 검색결과에서 영문주소와 한글주소가 같이 노출됩니다. 다만 이때 "영문보기" 버튼은 사라집니다.

이용에 참고해 주시기 바라며. 앞으로도 많은 이용 부탁드립니다.

혹시나 이용하시다가 이상한 점이나 개선사항이 있으시면 말씀해 주시기 바랍니다. 

감사합니다.
