### ISSUE TITLE
 행정자치부에서 검색되는 주소가 다음 우편번호 api에는 검색이 되지 않습니다.

### ISSUE THREAD

**Issue by jeaeunMyeong** [daumPostcode/QnA#226]
가양동 407-3번지 검색이 되지않습니다.

추가부탁드리겠습니다.

**Comment by daumPostcode** [comment]
@jeaeunMyeong 
네~ 안녕하세요~

해당 주소 확인 후 조치하도록 하겠습니다.

추가적으로 행자부와 저희시스템 상의 데이터는 1일에서 최대 3일 정도 차이가 날 수는 있으나, 저희도 일일 업데이트를 하기 때문에 보통 행자부에서 업데이트 후 그 다음날 적용이 된다고 보시면 됩니다.

감사합니다.

**Comment by jeaeunMyeong** [comment]
우와 빠른 답변감사합니다^^
