### ISSUE TITLE
넥사크로 관련 가이드

### ISSUE THREAD

**Issue by dih90** [daumPostcode/QnA#227]
혹시 다음 주소 api에서 제공하는 넥사크로 관련 가이드 혹은 사례 등이 있나요???

**Comment by daumPostcode** [comment]
@dih90 
네~ 안녕하세요~

현재 넥사크로 관련된 가이드는 없으며, 사례 또한 아직까지 듣진 못하였습니다.
예전에 Express나 Wordpress 플랫폼 또한 개인 개발자 분들이 응용하여 적용하신 것으로 알고 있습니다.

저희는 제일 기본적인 라이브러리 활용방법만 제공하여, 이외 다른 플랫폼의 플러그인 제공은 예정되어 있지 않은점 참고 부탁드립니다.

**Comment by dih90** [comment]
네 감사합니다~
