### ISSUE TITLE
폐쇄망 환경에서 API를 사용하고자 합니다.

### ISSUE THREAD

**Issue by dih90** [daumPostcode/QnA#228]
저희가 현재 폐쇄망 환경에서 [다음 우편번호 API]를 사용하려고합니다.
폐쇄망이다보니 방화벽OPEN을 하려면 IP 정보를 알아야하는데,
API를 사용하기 위한 URL 정보 및 IP 정보 최신 목록을 알려주셨으면 합니다.

**Comment by daumPostcode** [comment]
@dih90 

네~ 안녕하세요~

폐쇄망 환경에서의 사용은 공식적으로 지원하는 환경은 아니나, 유저분들의 요청에 의해서 필요하신 분들께만 도메인 리스트를 제공합니다.
폐쇄망이던 아니던 서비스적 차이는 없지만, 저희쪽도 개발이슈나 이관이슈로 인해 IP가 변경될 수 있다는 점 참고해 주시기 바랍니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net

HTTPS 환경 
- https://ssl.daumcdn.net
- https://s1.daumcdn.net 
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net

감사합니다.
