### ISSUE TITLE
Request for the support in English

### ISSUE THREAD

**Issue by anjalidudeja** [daumPostcode/QnA#23]
Hello team, 

I had one question regarding  DAUM, we are using this free webservice . Wanted to ask that if there is an issue we face going forward. Can you provide us the support in English?

Regards, 
Anjali
(M) - +91 9711004641

**Comment by daumPostcode** [comment]
@anjalidudeja 

Hello anjalidudeja

First of all, i can't speak english well, please understand.

I can provide regarding to only technical issue in English And the API description and examples, please look at this [site](http://postcode.map.daum.net/guide) has been provided in Korean, translated it into English. 

In addition, For the Republic of Korea address system, please refer to this [site](http://www.juso.go.kr/openEngPage.do).

Thanks for your attention to our service.
