### ISSUE TITLE
shorthand 값을 false설정 했습니다.

### ISSUE THREAD

**Issue by visualp** [daumPostcode/QnA#230]
안녕하세요 ^^

shorthand 값을 false 로 지정하고 사용을 하려고 합니다.

api 설명에 보면 다음과 같이 되어 있더라구요 .. 
검색된 주소와 내려가는 데이터의 '시','도' 부분을 축약 표시합니다(한글 주소만 해당). 기본값은 true로 설정되어 있습니다. 
(서울특별시 -> 서울, 광주광역시 -> 광주, 전라북도 -> 전북, 단, '세종특별자치시' '제주특별자치도'는 지자체의 요청에 의해 제외)
true : 광주광역시 -> 광주
false:광주->광주광역시
이렇게 출력 될거라고 생각 하고 . false값으로 설정을 했습니다.
하지만 .. true 값이나 false 값 어떤것으로 설정을 해도 축약(광주)로 출력이 됩니다.

혹 제가 api를  잘못 이해하고 있는 걸까요? ~ 
답변 부탁 드립니다.
그럼 수고하세요 ~~^^

**Comment by daumPostcode** [comment]
@visualp 
네~ 안녕하세요~

현재 테스트 해본결과 정상적으로 동작을 하는 것으로 확인이 됩니다.

혹시 어떻게 이용하셨을까요?
해당 속성값 설정은 생성자에 하셔야 합니다.

new daum.Postcode({
   oncomplete: function(data){....},
   shorthand : false
}).open()

이렇게 생성자에 적용을 시켜야 동작을 합니다. (가이드 페이지에서도 속성 부분에 정의되어 있습니다)

한번 확인해 보시겠어요??
