### ISSUE TITLE
간헐적으로 스크립트가 실행이 안되는문제

### ISSUE THREAD

**Issue by fallindev** [daumPostcode/QnA#231]
안녕하세요

쇼핑몰에서 다음주소 API를 사용중인데요

주말부터 갑자기 주소검색이 안된다는 문의가 많이 접수되서요

제가 직접 확인해본결과 

`<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>`

`<script charset="UTF-8" type="text/javascript" src="http://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1505975449403/170921.js"></script>`

첫번째 스크립트가 로딩된후 실행되면 두번째 소스가 생겨야 하는데
간헐적으로 두번째 소스가 생성이 안되는 경우가 있더라구요
그래서 주소검색 버튼을 눌러도 아무 반응이 없어요..
저희쪽 소스는 수정한게 없습니다..

저번 주말부터 갑자기 문의가 들어오고있는데 혹시 뭔가 수정된게 있다던가

스크립트 실행 순서와 관련해서 제가 뭔가 수정해볼만한게 있을까요?

**Comment by daumPostcode** [comment]
@hamsky1 

네~ 안녕하세요~

저번 주 중에 기능 추가가 되어 배포가 된 건이 있습니다. 
다만, 두번째 코어스크립트가 로딩이 안된다면, 기능추가로 인한 코어 스크립트 오류라기 보다, 저희 회사 CDN서버에 이상이 생긴거라고 볼 수 있습니다.
현재 공식 보고된 문제는 없습니다만, 해당 서버 관리하는 팀에 문의 넣어 보도록 하겠습니다.

이외 추가적으로 다른 이유일 수도 있는데요.
http://postcode.map.daum.net/guide#usage
저희 가이드페이지의 첫번째 정적로딩방식이 아닌 동적로딩 방식을 이용해 보시는 것도 하나의 방법입니다.
정적로딩 방식은 document.write를 통해 페이지를 블락 걸고 쓰는 기능인데, 현재까지 보고된 문제는 없지만 예상치 못한 오류가 있을 수도 있습니다

추가로 혹시 오류가 났을때의 오류메세지 캡쳐가 가능하실까요?

**Comment by daumPostcode** [comment]
@hamsky1 
안녕하세요~

CDN서버 관련된 팀에서 답변이 왔는데, 따로 서버알림이 있지는 않다고 합니다.
다만, 카카오 전체 서비스에서 사용하는 서버여서, 로그가 상당히 많아서 혹시 발생한 시간대를 대략 알려 주실 수 있으실까요?

발생한 시간대에 한해서 로그 분석을 할 수 있다고 하시네요. 댓글 확인하시면 답변 부탁드립니다.

**Comment by hamsky1** [comment]
안될때의 상태를 조금 자세히 말씀드리자면

http://dmaps.daum.net/map_js_init/postcode.v2.js
위 소스는 정상적으로 받아왔구요
![1506313427460](https://user-images.githubusercontent.com/13057433/30792372-ce1faf7e-a1f4-11e7-8784-0203cbdfb2a0.jpg)

콘솔창에 어떤 에러메세지도 없었습니다

정상적으로 동작을 한다면 아래사진처럼 되야하지만
![1506313021956](https://user-images.githubusercontent.com/13057433/30792253-d97ce0d6-a1f3-11e7-8906-63e05082b7a8.jpg)
안될때는 두번째 스크립트가 추가가 안되어있습니다
스크립트를 추가하는 document.write가 동작이 안된것 같습니다

그리고 주소검색을 누르면 아래의 오류가 나옵니다
![1506306863888](https://user-images.githubusercontent.com/13057433/30792185-4fa70fa8-a1f3-11e7-890e-0489b30d1e3c.jpg)
코어 스크립트가 없으니..


위 동작을 봤을때 CDN문제는 아닌것 같습니다
첫번째 스크립트는 잘 받아지고
두번째는 document.write가 동작을 안해서 아에 받을 시도를 못하니까요


일단 동적로딩방법을 적용해서 테스트 해보도록 하겠습니다

답변감사합니다!

**Comment by daumPostcode** [comment]
@hamsky1 
네~ 안녕하세요~

네 정상적으로 로딩을 한다면, document.write로  170921.js 파일을 받아 파싱이 완료가 되어야 되는데,
이 작업이 수행이 안되서 생성자 오류가 발생 한 것 같습니다.
해당 오류가 현재도 발생하고 있는 것인가요?

일단 CDN쪽에서
09시 41~44분,
14시 55~58분 대에 s1 캐시군의 부하상승이 있었다고 하시네요. CDN쪽 오류라면 해당 시간대에 주로 발생을 했을 거라는 추측입니다.
즉 코어스크립트를 요청한 다음에 정상적인 코어스크립트를 받아야 하는데, 빈 파일이나, 요청 자체가 안와서 발생한 문제일 수도 있습니다. 또는 말씀하신 것처럼 document.write는 페이지 로딩시 loader파일을 다운 받고 나면 바로 동작되는 코드라, 이 부분에서 문제가 될 수도 있겠지요.

일단 저희 가이드페이지에 있는 동적로딩 방식으로 구현을 하시면, 서비스 팝업을 요청할때 core스크립트는 1회에 한해서 호출하는 것으로, 페이지 초기화할때 다수의 스크립트를 받아서 파싱하는 것과 분리되기 때문에 좀 더 안전성이 올라가긴 하실 거에요.

일단 불편을 드려 죄송하며, 추가 문의나 CDN쪽 답변이 더 들어오면 공유해 드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@hamsky1 
네~ 답변 사항 공유드립니다.

현재 리소스 로딩 문제는 저희쪽 문제일 수도 있지만, cdn쪽 문제일 가능성이 더 높아서, 대안책이 마련되었습니다.

현재는 core스크립트는 s1.daumcdn.net으로 호출을 하는데, 이 URL을 변경할 예정입니다.

URL만 변경을 해도 거치는 서버가 3단계에서 1단계로 줄어들어, 리퀘스트 문제가 많이 줄어들 것이라고 하시네요.

해당 URL변경작업은 저희쪽에서 진행하는 것으로 따로 수정을 하실 것은 없습니다.

아무튼 불편을 드려 죄송하며, 앞으로도 비슷한 이슈가 발생하시면 언제든지 이슈 주시기 바랍니다. 감사합니다.

**Comment by hamsky1** [comment]
네 감사합니다

변경이 완료되면 답글 한번 부탁드리겠습니다~

**Comment by daumPostcode** [comment]
@hamsky1 
안녕하세요~

현재 core스크립트에 한해서; 임시로 URL변경이 완료되었습니다.

추후 서비스팝업에도 연결된 모든 javascript, css파일들도 모두 변경될 예정입니다.
해당 변경 작업은, 추석 연휴 후에 작업이 진행 될 것 같아요.
참고 부탁드립니다.

감사합니다

**Comment by hamsky1** [comment]
@daumPostcode 

넵 확인했습니다

실행방식도 동적로딩으로 변경해서 계속 테스트 중인데 잘 되는 것으로 보입니다

빠른 조치 감사합니다!
