### ISSUE TITLE
사용자의 주소 선택없이 자동적으로 임의의값 (정렬순서에서 1번째)의 주소를 선택할수없나요?

### ISSUE THREAD

**Issue by jslion** [daumPostcode/QnA#233]
안녕하세요~
도로명주소 daum API를 너무나 감사히 잘사용하고있는 개발자입니다.

다름이 아니라 기존 지번주소 데이터로 도로명 주소 데이터로 컨버팅작업을 하려고하는데,
DB를 이용해서 쿼리로 처리하자니 시간이 오래걸릴것같아 daum API를 이용하여
배치를 돌려 각각 변환하여 insert해주려는 작업을 하고있습니다.

즉, 사용자가 검색하는 방식이 아닌 어플리케이션단에서 자동적으로 지번 주소를 입력하여
검색된 결과를 자동으로 선택해줄수 있도록 (검색된 결과가 하나일 경우에만) 해야 하는데
특정 검색어(q: 검색어)까지 넘겨서 주소검색은 해주는데 그 이후
사용자가 반드시 주소선택을해야 콜백함수가 실행되는 구조로 되어있어
이부분을 자동적으로 선택할수 있도록 해주는 기능이 있는지 여쭙고자 이렇게 문의 드립니다.
(ex: autocomplete와 같은 콜백함수가 있는지.. 없다면 추후 추가 계획은 없으신지..)
답변 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@jslion 
네~ 안녕하세요~

네 현재 말씀하신 기능은 추가 계획이 없습니다;;
저희는 사용자 UI를 제공을 하지 아직 RESTful한 API를 제공할 계획이 아직 없기도 하고, 해당 기능은 비 정상적인 어뷰징으로 기록이 될 수도 있습니다;

컨버팅 작업은 저희 API보다 행자부 측에서 제공하는 REST API나 https://www.poesis.org/postcodify/ 에서 제공하는 API를 참고하시는게 더 좋은 선택일 것 같습니다 ^^

문의 주셔서 감사드립니다~
즐거운 추석 보내세요~
