### ISSUE TITLE
행정자치부에서 검색되는 주소가 다음 우편번호 api에는 검색이 되지 않습니다. 

### ISSUE THREAD

**Issue by djdan1234** [daumPostcode/QnA#234]
경기도 양주시 옥정동 1024 

경기도 양주시 화합로1710번길 125

확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@djdan1234 

네 안녕하세요~

말씀해주신 주소의 경우 저희에게 행자부가 데이터를 줄때 좌표값을 주지 않는 주소로
해당 주소는 매핑이 불가능하여 우편번호 서비스에서는 제외되고 있는 주소입니다.

보통 좌표값을 주지 않는 주소의 경우, 국가 보안 시설이거나, 도로명 주소는 발급되어 있지만 건물이 없는 상태 등 예외 케이스들이 있습니다.

이러한 주소는 대한민국 전체 주소중 0.03%정도 차지하고 있는데요, 저희 CS로 이러한 주소의 등록 요청이 자주 들어오지만, 현재 저희 우편번호와 주소 검색 시스템 상에서는 해당 주소를 보여드리기가 힘든 점 말씀드립니다;;

도움을 드리지 못해 죄송합니다.

추가적으로 행자부 도로명 검색 시스템에서 검색시, 보안 주소의 경우 검색 결과 우측에 마커버튼이 없습니다
(스크린샷 참고 - 마커가 있는 주소와 없는 주소의 차이비교)

<img width="1003" alt="2017-10-12 2 27 19" src="https://user-images.githubusercontent.com/20675065/31480639-e706ebde-af59-11e7-8df7-5fd6f9342166.png">
<img width="1011" alt="2017-10-12 2 27 32" src="https://user-images.githubusercontent.com/20675065/31480649-ecbaf156-af59-11e7-910e-3552e0fa5158.png">
