### ISSUE TITLE
추가되거나 변경된 도메인 주소 최신 목록 부탁드립니다.

### ISSUE THREAD

**Issue by songhochul** [daumPostcode/QnA#235]
저희가 현재 폐쇄망 환경에서 [다음 우편번호 API]를 사용하고 있습니다.
폐쇄망이다보니 IP 정보 및 도메인 주소를 방화벽 정책에 넣어 사용 중인데 
최근 접속도 느리고 정상적으로 싸이트가 잘 열리지 않는 문제가 발생하고 있습니다.
변경되거나 추가된 도메인 주소가 있으면 최신 목록 부탁드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@songhochul 
네~ 안녕하세요

최근 서버들의 데이터센터 이관이 있었으며, 이에 따라 몇몇 도메인의 아이피가 변경됬을 수 있습니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://s1.daumcdn.net 
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net

현재 이용하는 도메인은 위와 같으며, IP정보는 직접 확인하여 작업을 하셔야 합니다.

감사합니다.
