### ISSUE TITLE
주소 검색결과를 "동"까지만 받을 수 있는 방법이 있는지 문의드립니다.

### ISSUE THREAD

**Issue by ssonsh** [daumPostcode/QnA#236]
현재 다음 api를 활용하여 주소검색 서비스를 개발중에 있습니다.

전체 주소를 가져오는 이슈가 아닌
시, 군, 구, 동 까지의 주소만 가져오도록 처리를 하고 있으나

"동" 으로 검색하는 경우 검색결과에 노출되는 리스트가 많다보니
"동" 까지만 검색결과로 받을 수 있는 별도의 옵션이 있는지 여쭤봅니다.

**Comment by daumPostcode** [comment]
@ssonsh 
네~ 안녕하세요~

검색결과에 "동" 까지만 표출되는 옵션이 있는지 말씀이시죠?
현재 해당 옵션은 없습니다.

저희 서비스는 도로명 주소 검색 시스템이며, 동까지만 표시되게 하는 기능은 백단부터 새로운 기능을 위해 다시 만들어져야 되는 기능인지라, 앞으로도 추가할 계획은 없습니다.

데이터를 직접 처리를 원하시면, 행정자치부 도로명 검색 시스템에서 데이터를 직접 받아서; 가공을 하여 처리하시는게 좋아 보입니다.

지원해 드리지 못해 죄송합니다.

**Comment by ssonsh** [comment]
답변 감사드립니다^^
