### ISSUE TITLE
다음 측에서 특별히 추가한 주소가 있는지 문의드립니다.

### ISSUE THREAD

**Issue by devellany** [daumPostcode/QnA#237]
안녕하세요, 다음API를 활용하고 있는 개발자입니다.
다음 측에서 사용 용이하게 만들어주셔서 편리하게 이용하고 있는데요.

'사서함'과 같이 행자부에서 검색되지 않으나,
다음API에서 검색되는 예외사항이 더 있는지 궁금해서 문의드립니다.

또한 '사서함'의 경우 도로명주소라기보다 지번주소에 가까운 형태를 보이고 있는데,
도로명주소로 분류시킨 사유 또한 궁금하네요.
사서함의 경우 동/읍/면 은 존재할 수 있어도 도로명을 가지고 있지는 않은 것 같거든요.
그저 우편번호 때문인가요?

이와 같이 도로명으로 분류되어 있는데 도로명이 존재하지 않는 케이스가 더 있을까요?
저희 사이트에 적용함에 있어서
추가적으로 예외적인 처리를 잡아줘야 할게 있나 싶어 문의드립니다.

**Comment by daumPostcode** [comment]
@devellany 
네~ 안녕하세요~

사서함을 도로명으로 잡은 이유는 말씀하신 것처럼, 기초구역번호의 존재이유가 큽니다.
기초구역번호가 도로명주소가 발급된 주소에만 매핑이 되어 내려가기 때문에 도로명 타입으로 잡았었습니다.

이외 아래 스샷처럼
![2017-10-16 6 05 00](https://user-images.githubusercontent.com/20675065/31603890-91c924ca-b29c-11e7-993b-75afb5246837.png)
하나의 도로명주소에 여러개의 건물이 있을 경우, 행자부와 다르게 건물별로 쪼개어 선택할 수 있도록 하였습니다. 각 주소의 기초구역번호와 주소는 모두 동일합니다. 다만 건물명과 건벌코드가 다르게 내려가게 됩니다.

또한 주소는 기본적으로 법정동으로 표기가 되나 행정동으로 검색시, 주소 옆에 괄호로 행정동명을 표기합니다. 이는 저희가 받는 주소 데이터의 좌표로 미리 해당 주소의 법정동과 행정동 매핑해두어 가능한 것으로 추가된 정보라고 보셔도 됩니다.

그리고 제일 중요한 점은, 오히려 행자부 데이터보다 검색 결과가 적을 수 있습니다. 그 이유는 일명 보안주소(국가 발전시설, 보안시설)라고 판단하는 주소들의 경우 저희에게 좌표정보를 내려주지 않습니다. 즉, 저희의 도로명-지번의 매핑과 부가정보를 매핑하는데 필수적인 데이터가 좌표이나, 이 좌표가 없기 때문에 몇몇 주소의 경우 저희 시스템에서는 검색이 되지 않습니다. 이점은 양해 부탁드립니다.

마지막으로 업데이트 관련 사항은 https://github.com/daumPostcode/QnA의 README.md파일을 보시면 확인 가능하시며, 질문 하신 내용처럼 추가적인 데이터를 내리게 된다면 여기에 적어드리며, 플러스맵 친구 카톡으로 메세지 보내드리도록 하겠습니다.

감사합니다.

**Comment by devellany** [comment]
아하, 넵 빠른 답변 감사합니다.-
