### ISSUE TITLE
폐쇄망 환경에서 API를 사용하고자 합니다.

### ISSUE THREAD

**Issue by songhochul** [daumPostcode/QnA#238]
몇일전 동일한 제목으로 문의드려서변경된 도메인주소 정보 받았는데 
오늘부터 다시 접속이 원활하지 않습니다.
추가로 변경된 도메인 주소정보 확인부탁드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@songhochul 
네~ 안녕하세요~

현재 서비스차원에서의 도메인 변경은 없습니다.

접속이 원할하지 않다는게; 특정 리소스가 다운이 안받아지는 것인지; 팝업이 뜨지 않는 것인지, 이미지만 안나오는 것인지 알 수 있을까요?

도메인 리스트는 이전에 드린 목록 그대로 입니다.
