### ISSUE TITLE
폐쇄망 환경에서 API를 사용하고자 합니다. (재문의)

### ISSUE THREAD

**Issue by songhochul** [daumPostcode/QnA#239]
추가된 도메인 목록이 없다고 답변답았는데
다음우편번호 서비스에 접속하면 스크립트 오류뜨면서 접속이 되지 않았습니다.

방화벽에서 확인하여 (163.171.0.0/16) 대역이 막히는것이 확인되어
해당 IP대역 추가하였더니 정상적으로 접속이 잘되었습니다.

추가로 변경된 도메인이 없는 것이 맞는것인지 확인 부탁드립니다

**Comment by daumPostcode** [comment]
@songhochul 
스크립트 오류가 뜨면서 접속이 안되는 현상이라면 저희 cdn 서버에 올라가 있는 javascript 파일이 로딩이 안되는 것 같은데요

자바스크립트 파일은 사내 공통 CDN서버에 올라가며, 
t1.daumcdn.net / s1.daumcdn.net 이 2가지만 사용합니다.

이외 다른 도메인은 사용하지 않으며, 서비스 화면에서의 스크립트 뿐만 아니라, 저희 팝업을 띄워주는 core스크립트 170925.js 파일 또한 t1.daumcdn.net을 사용합니다. 

한가지 다른점이라면 JS API로더 스크립트(postcode.v2.js)파일의 경우 http환경에서는 dmaps.daum.net 을 https 환경에서는 ssl.daumcdn.net 을 사용하고 있습니다.

해당 CDN서버는 1개의 서버가 아닌 다수의 서버로 구성되어 있다고 알고 있으며 관리 하는 팀도 독립적으로 구성되어 있습니다.

즉, 도메인이 변경되고 하는 이슈는 저희쪽으로 변경 작업 요청이 들어오며, 특히 JS API의 경우엔 변경이 될때 플러스맵친구로 모두 메세지를 보내드립니다. 이외 도메인이 아닌 IP의 변경의 경우 저희쪽으로 들어오는 정보는 없습니다.
그리고 IP의 경우 자주는 아닐지라도 충분히 변경이 될 수 있습니다.

저희 서비스는 공식적으로 폐쇄망 환경을 대응하지 않습니다. 다만 웹서비스 특성상 이용할 수 있는 방법이 있기에 최소한으로 도메인만 제공을 하며, IP및 IP대역의 정보는 제공을 하지 않는점 참고 바랍니다.
