### ISSUE TITLE
주소 문의드립니다.

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#24]
대전광역시 동구 가양동 147-9 

대전광역시 동구 가양동 147-9를 네이버에 검색하면 나오는데
다음api 시스템에서는 검색되지 않습니다.
확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@dysong1 

안녕하세요~ dysong1님~

해당 주소는 도로명 주소가 발급되지 않은 주소입니다.

말씀하신 주소는, 네이버, 다음 검색에서 검색해보시면 모두 나옵니다. 왜냐하면 해당 서비스에서는 대한민국에 존재하는 모든 주소를 다루기 때문입니다.

이와 다르게 우편번호 서비스는, 우편번호(새우편번호)가 있는 주소, 즉 도로명주소가 발급이 된 주소만 검색이 되는 시스템 입니다. 쓰이는 데이터도 행자부 도로명검색 시스템에 존재하는 주소데이터를 이용합니다.

http://juso.go.kr에서 검색해 보시면, 해당 주소는 검색이 안되고 있으며, 이는 도로명 주소가 발급되지 않은 주소이기 때문에 검색이 안되는 것이 맞습니다.

해당 내용은 저희 [FAQ 1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)에 자세히 적혀져 있으니, 확인 부탁드리며, 신규 주소 신청의 경우 개별적으로 행자부 사이트에서 신청 하셔야 합니다.

그럼 즐거운 저녁 보내세요~
