### ISSUE TITLE
윈도우10 버전에서 보안되지 않은 컨텐츠로 분류됩니다.

### ISSUE THREAD

**Issue by pjs1249** [daumPostcode/QnA#241]
윈도우10 버전에서 인터넷 익스플로어로 우편번호 찾기를 누를경우, 보안되지 않은 컨텐츠로 분류됩니다.
때문에 익스창 하단에 경고문구가 뜨게되며, 모두보기를 눌러야만 우편번호검색 버튼을 눌렀을 때 검색창이 나타나게 됩니다.
저희가 사용중인 방법은 아이프레임으로 인한 끼워넣기입니다.

저기서 문제점은, 모두보기를 했을 때 창 중간에 경고창이 뜨며 다시시도를 눌러야만 한다는 번거로움이 있습니다. 처음엔 인터넷 보안과 관련된 문제인가 했는데, 저희 회사에서 사용하는 컴퓨터는 모두 윈7에 문제가 없었고 윈10 버전인 노트북과 데탑에서만 같은 경고문구가 떴습니다. 이 부분은 수정/보완이 될 수 없는건가요?

**Comment by daumPostcode** [comment]
@pjs1249 
네~ 안녕하세요~

혹시 https 환경에서 저희 서비스를 구동하시나요?
아마 https페이지에서 저희 서비스중 http용 서비스를 이용해서 그런것 같네요.

http용은 dmaps.daum.net으로 도메인이 시작하며
https용은 ssl.daumcdn.net 으로 도메인이 시작됩니다.

https://spi.maps.daum.net/postcode/guidessl <- 이게 https용 가이드 페이지 입니다. JS API로더 스크립트가 다르므로 참고하시기 바랍니다. 가이드 페이지 상단에 잘 읽어보시면 환경에 따른 가이드 페이지에 대한 링크가 있으니 참고하세요.

**Comment by pjs1249** [comment]
답변 감사합니다.
그런데, 저희가 이미 https용으로 사용하고 있는데 불구하고 윈도우10 사양에서만 그런 문구가 뜨고있습니다. 윈도우7에서는 그런 문구가 뜨지 않구요. 이 부분 확인 부탁드려도 될까요?

**Comment by daumPostcode** [comment]
@pjs1249 
음 그러시군요..

실제 사용자 페이지에서 저희쪽 서비스를 이용하실땐 postcode.v2.js 스크립트만 사용을 하면 되는데; 현재 해당 스크립트는 모두 https 처리가 되어 있거든요.

혹시 해당 오류 스크린샷을 알려주실 수 있으신가요? 아니면 제가 접속할 도메인을 알려주시면 감사하겠습니다.
현재 제쪽에서는 보안 오류와 같은게 안뜨거든요;;

확인 부탁드립니다.
