### ISSUE TITLE
사파리 브라우저에서 oncomplete 가 호출되지 않음

### ISSUE THREAD

**Issue by neo4elf** [daumPostcode/QnA#243]
다음 주소를 적용해서 잘 사용해오고 있습니다.

모바일 사용자가 조금씩 늘어나면서 사파리 브라우저 사용 시 오류가 난다는 문의를 받았습니다.
확인해보니 여타 브라우저에서는 문제없이 잘 동작 하는데 사파리에서만 콜백이 호출이 되지 않습니다.

new daum.Postcode({
    oncomplete : function(data){ alert("called oncomplete"); },
    onclose: function(stat){ alert("called onclose"); },
    onresize: function(size){ alert("called onresize");},
    이하 생략
});

상기와 같이 정의 한후 주소를 검색해 보면 onresize 콜백은 정상적으로 호출이 되는데
oncomplete, onclose 는 호출이 되지 않습니다.

심지어 주소검색을 하고 검색된 주소를 선택 한경우 팝업이 닫히기는 하나 콜백은 호출 되지 않습니다.
테스트는 사파리가 윈10을 지원하지 않아 윈7 PC에 Windows용 사파리를 설치하고 테스트 했습니다.

빠른 답변 부탁드립니다.

**Comment by daumPostcode** [comment]
@neo4elf 
안녕하세요~ 어제 워크샵이어서 답변이 늦은점 죄송합니다.

현재 iOS 11.0.3 버전 모바일 사파리
Mac용 Safari 11.0 버전에서는 말씀하신 오류가 발생하지 않습니다.

모바일 사용자라 하면 아이폰 사용자이고 safari 최신버전(또는 그에 준하는 아랫 버전)을 이용하고 있을 것이라 생각이 됩니다. 그래서 윈도우용 사파리로 테스트 하는 것은 버전이 매우 다를 것으로 생각이 되네요.(윈도우용 사파리는 5.x버전으로 알고 있습니다)

현재 오류가 나는 상황이 PC window 구버전 safari인지 아이폰 사파리인지 확인이 필요한 상황이고, 구버전 window 사파리의 경우 기술적인 문제로 인해 지원이 안될 가능성도 있는점 참고바랍니다.

또한 oncomplete 콜백의 경우에는 유저가 검색결과를 선택했을때, 
onclose 콜백은 창이 닫힐때(레이어 모드에서는 검색결과 선택해서 닫히는 경우에만 발생)
onresize콜백은 페이지가 새로고침(또는 최초로딩)될때 발생하며 open()을 사용하여 팝업으로 띄운상태에서는 발생하지 않습니다. (해당 제약 사항은 가이드 페이지 참고)

또한 콜백 순서는 보통 onresize->onclose->oncomplete 순으로 발생을 하게 됩니다.

즉 위 콜백함수들 내부에서 오류가 발생을 하면 그 이후 동작이 정지 됩니다.
현재 코드를 이하생략처리로 알려주셨는데,
오류가 발생하는 full code를 제공해 주실 수 있으신지요. 또는 브라우저 개발자 도구를 통해 어느 부분에서 오류가 나는지까지 캡쳐를 해주시면 더 빠른 확인이 될 것 같습니다. 또는 저희가 접근할 수 있는 URL이 있으면 제가 접속해서 확인해 보도록 하겠습니다. 그리고 브라우저의 버전명을 정확히 명시해 주시면 좋을 것 같습니다.

제가 테스트한 코드는 아래와 같습니다
           new daum.Postcode({
                oncomplete: function (data) {
                    element_layer.style.display = 'none';
                    alert('complete');
                },
                onresize: function(size) {
                    alert(size);
                },
                onclose: function(stat) {
                    alert(stat)
                }
            }).embed(element_layer);
            element_layer.style.display = 'block';

확인해 보시고 댓글 부탁드립니다.

**Comment by neo4elf** [comment]
답변 감사합니다.
주위에 아이폰을 갖고 있는 사람이 없어 PC에 사파리를 설치 한건데 버전차이가 생기는 군요
이 부분은 다시 확인해 보겠습니다.

라이브 서비스는 SSL 환경에서 합니다. 그러나 테스트는 NONE-SSL 에서 합니다.
질문1. 현재 SSL 모듈로 "https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js" 를 사용하고 있습니다. "https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js" 이것과 차이가 있나요?
하나는 CDN 인거 같은데 동일한 모듈인가요?

질문2. 테스트 환경에서 SSL 스크립트를 사용해도 문제 없을까요?
    - 테스트 및 라이브에서 모두 "https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js" 사용해도 문제 없을까요?

확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@neo4elf 
네~ 안녕하세요~

네 되도록이면 spi.maps.daum.net 보다는 ssl.daumcdn.net으로 이용해 주시기 바랍니다.
둘다 CDN에 있는 같은 리소스를 바라보는 것은 맞지만, spi의 경우 리소스외에도 여러가지 용도로 사용하는 것이라 캐시 문제로 인하여 리소스가 제때 업데이트가 되지 않습니다. 그래서 올해 초에 spi에서 ssl로 바꾼 것이기도 합니다.

넵. 테스트/라이브 모두 https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js 를 이용해 주시면 됩니다.

추가 질문이 있으시면 언제든 댓글 부탁드려요~~
