### ISSUE TITLE
행정동코드는 알 수 없나요?

### ISSUE THREAD

**Issue by blue4313** [daumPostcode/QnA#244]
행정동코드가 필요합니다.
법정동은 bname, bcode 둘 다 있는데.
행정동은 hname만 있고, hcode는 없네요?
주소검색 시, 행정동코드를 알 수 없나요?

**Comment by daumPostcode** [comment]
@blue4313 
네~ 안녕하세요~

주소의 경우 모든 주소는 법정동으로 내려가기 때문에 행정동 코드값을 따로 내리진 않습니다.
(주소 자체가 법정동이 기본이며 행정동은 행정 편의때문에 나눈 것이라서요)

다만 현재 행정동명도 유저분들의 요청에 의해 추가가 된 상태인데요. 해당 데이터 또한 내부 검토 후에 추가가 가능하면 추가하도록 하겠습니다.

즉, 현 시점에서는 행정동 코드를 받을 수 있는 방법은 없으며, 다른 API와 같이 사용하셔야 합니다.
현재 주소 변환이나 코드값을 활용하여 무언가를 하실때에는 
https://developers.kakao.com/docs/restapi/local
http://apis.map.daum.net/web/documentation/#services_Geocoder_addressSearch

이 두 API를 참고하셔야 합니다. (둘다 같은 것인데 실행 방법이 다릅니다)

만족스런 답변을 드리지 못해 죄송합니다.

**Comment by blue4313** [comment]
var geocoder = new daum.maps.services.Geocoder(); 부분에서 오류가 발생합니다.
현재 //apis.daum.net/maps/maps3.js?apikey= 관련 키는 가지고 있는데, 
다른 뭔가가 더 필요한가요?

**Comment by daumPostcode** [comment]
@blue4313 
네~

현재 지도 API는 Daum Developers에서 Kakao Developers로 이관되었습니다.

제가 드린 링크도 kakao developers사이트 입니다. 또한 이관하면서 몇몇 API의 인터페이스가 변경되었기 때문에 발생한 이슈 같습니다.

http://apis.map.daum.net/web/guide/
<- 지도 API 공식 레퍼런스 사이트의 가이드 페이지를 참고해 보시면 좋을 것 같습니다~

**Comment by blue4313** [comment]
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=**************&libraries=services"></script>
<script>
	var geocoder = new daum.maps.services.Geocoder();

	var coord = new daum.maps.LatLng(37.566826, 126.9786567);
	var callback = function (result, status) {
		if (status === daum.maps.services.Status.OK) {

			console.log('지역 명칭 : ' + result[0].address_name);
			console.log('행정구역 코드 : ' + result[0].code);
		}
	};

	geocoder.coord2RegionCode(coord, callback);
</script>

geocoder.coord2RegionCode(coord, callback);

이 부분에서 다음과 같은 오류가 발생합니다.

GET http://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x=(37.566826%2C%20126.9786567)&y=function%20(result%2C%20status)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(status%20%3D%3D%3D%20daum.maps.services.Status.OK)%20%7B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%27%EC%A7%80%EC%97%AD%20%EB%AA%85%EC%B9%AD%20%3A%20%27%20%2B%20result%5B0%5D.address_name)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%27%ED%96%89%EC%A0%95%EA%B5%AC%EC%97%AD%20%EC%BD%94%EB%93%9C%20%3A%20%27%20%2B%20result%5B0%5D.code)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D 400 (Bad Request)
services.js:6 Uncaught TypeError: c is not a function
    at services.js:6
    at Object.onerror (services.js:6)
    at XMLHttpRequest.a.onreadystatechange (services.js:5)

* 카카오에서 새로 키도 발급받았는데.. 어떻게 해야 하나요? ㅠㅜ

*  발급받은 appkey 는 보안상 *로 표시했습니다.

**Comment by blue4313** [comment]
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=**************&libraries=services"></script>
<script>
	var geocoder = new daum.maps.services.Geocoder();

	var coord = new daum.maps.LatLng(37.566826, 126.9786567);
	var callback = function (result, status) {
		if (status === daum.maps.services.Status.OK) {

			console.log('지역 명칭 : ' + result[0].address_name);
			console.log('행정구역 코드 : ' + result[0].code);
		}
	};

	geocoder.coord2RegionCode(coord, callback);
</script>

geocoder.coord2RegionCode(coord, callback);

이 부분에서 다음과 같은 오류가 발생합니다.

GET http://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x=(37.566826%2C%20126.9786567)&y=function%20(result%2C%20status)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(status%20%3D%3D%3D%20daum.maps.services.Status.OK)%20%7B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%27%EC%A7%80%EC%97%AD%20%EB%AA%85%EC%B9%AD%20%3A%20%27%20%2B%20result%5B0%5D.address_name)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%27%ED%96%89%EC%A0%95%EA%B5%AC%EC%97%AD%20%EC%BD%94%EB%93%9C%20%3A%20%27%20%2B%20result%5B0%5D.code)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D 400 (Bad Request)
services.js:6 Uncaught TypeError: c is not a function
    at services.js:6
    at Object.onerror (services.js:6)
    at XMLHttpRequest.a.onreadystatechange (services.js:5)

* 카카오에서 새로 키도 발급받았는데.. 어떻게 해야 하나요? ㅠㅜ

*  발급받은 appkey 는 보안상 *로 표시했습니다.

**Comment by daumPostcode** [comment]
@blue4313 
네~

먼저 불편을 드려 죄송합니다.
해당 오류는 지도 JS API담당자 분께 전달하였구요.

daum->kakao로 이관하면서 API명세가 변경되었는데; 인터페이스만 변경되고 그 아래 설명되어 있는 샘플코드가 변경이 안된 것이었습니다.

coord2RegionCode(x, y, callback, options)
함수가 이렇게 되어 있는데, 현재 샘플로는 (coords, callback, options)로 넘어가서 발생하는 문제입니다.

x - longitude(경도), y = latitude(위도)
즉, coords객체를 생성하지 마시고, geocoder.coord2RegionCode(126.9786567, 37.566826, callback);
이렇게 넣어주시면 됩니다.

샘플코드는 빠른 시일내에 수정하도록 하겠습니다.
