### ISSUE TITLE
react native webview ios에서 daum.postcode.load가 실행되지 않습니다.

### ISSUE THREAD

**Issue by njustice4all** [daumPostcode/QnA#245]
react native webview로 http프로토콜을 통해 페이지를 호출하는 방법으로 사용하고있습니다.
(예: <Webview source={{ uri: 'http://example.com' }} />)

android에서는 문제없이 잘 되는데

ios에서 daum.postcode.load가 실행되지 않아서 iframe창을 로드하지 못하는것 같습니다.

[ 위의 example.com의 스크립트 로드부분 ]
![2017-11-07 2 16 13](https://user-images.githubusercontent.com/13092695/32478140-48af10a2-c3c6-11e7-8d9a-ed8a867c33bf.png)

**Comment by daumPostcode** [comment]
@njustice4all 
네~ 제가 react native를 잘 몰라서 답변을 드리기 어려운 상황인데요.
코드상으로는 다른 문제는 없어보입니다.

혹시 어떤 오류가 뜨는지 확인 가능 하실까요? postcode.v2.js 파일이 제대로 로드 됬는지 확인이 필요합니다.
또는 postcode.v2.js 파일은 로드가 되었지만 core 스크립트가 로드가 되지 않아서 발생한 문제일 수도 있는데 오류 메세지 캡쳐를 제공해 주실 수 있으면 올려주시면 감사하겠습니다. 

이외 제가 react native로 테스트를 해봐야 되는데 시간이 좀 걸릴 것 같아요; 양해 부탁드립니다.;;

**Comment by njustice4all** [comment]
해결했습니다.

ios NSAppTransportSecurity 문제였습니다. 저의 실수입니다. 제가 초보라서 죄송합니다 ㅠㅠ

**Comment by daumPostcode** [comment]
@njustice4all 
넵. 다행입니다 ^^
리액트 네이티브는 저는 더 초보라서;; 해결방법을 알려드리기가 어려웠을 것 같은데; 잘 해결되서 다행입니다 ^^

즐거운 수요일 되세요~~
