### ISSUE TITLE
영문으로 조회 할수는 없는건가요?

### ISSUE THREAD

**Issue by allin1987gg** [daumPostcode/QnA#246]
안녕하세요.혹시 영문 주소를 입력해서 조회 할수는 없는건가요?
감사합니다.

**Comment by daumPostcode** [comment]
@allin1987gg 
네~ 해당 기능은 검색엔진 단에서 부터 아직 지원하지 않습니다.

엔진이 개선이 되면 적용가능하리라 생각이 들지만 서비스가 국내향 서비스라 니즈에 따른 개발이 가능할지는 확실히 모르겠네요;;
