### ISSUE TITLE
http://apis.daum.net/local/geo/addr2coord

### ISSUE THREAD

**Issue by blue4313** [daumPostcode/QnA#247]
안녕하세요.
해당 url은 주소검색 시 좌표를 검색하는 api 입니다. (* json 형태의 리스트 형식으로 콜백함수로 리턴)
현재 운영중에 사용중이고요. 
먼저 기존 샘플코드를 확인하고  싶고,
최종적으로는 //dapi.kakao.com/v2/maps/sdk.js 로 바꾸고 싶습니다.
http://apis.daum.net/local/geo/addr2coord를 대체할 수 있는 api는 어디를 봐야 하나요?

현재 이런식으로 사용하고 있습니다.

var s = document.createElement('script');
	s.type ='text/javascript';
	s.charset ='utf-8';
	s.src = api_url + '?apikey=' + api_key + '&output=json&callback=callbackFunc&q=삼성동;
	document.getElementsByTagName('head')[0].appendChild(s);

**Comment by daumPostcode** [comment]
@blue4313 
네~ 안녕하세요~

해당 API의 문의 의 경우 
https://devtalk.kakao.com/ <- 여기에 문의를 주시는게 더 빠를 것 같습니다.

이전의. API명세의 경우 저는 찾질 못했는데요;;
http://apis.map.daum.net/web/documentation/#services_Geocoder_addressSearch
https://developers.kakao.com/docs/restapi/local#주소-검색

위 두개 API를 참고해보시면 현재 이용하고 계시는 API의 대안이 되지 않을까 합니다.

말씀하신 방식은 jsonp 방식인데; 현재 이 jsonp방식을 지원하는지는 확실하지 않습니다. 아마 access-allow-control이 *로 되어 있는거 보니 굳이 jsonp 방식 쓰지 마시고 Ajax 콜로 요청을 해도 데이터가 전송되어 올것 같네요.
