### ISSUE TITLE
콘솔창에서 실행시

### ISSUE THREAD

**Issue by blue4313** [daumPostcode/QnA#248]
콘솔창에서 실행시, 

데이터가 있는데 없다고 나오네요.

* 웹에서 실행하면 결과가 잘 나옵니다.

* Authorization 는 발급받은 REST API  key 키로 했습니다.

curl -v -X GET "https://dapi.kakao.com/v2/local/search/address.json" --data-urlencode "query=전북 삼성동 100" -H "Authorization: KakaoAK kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
*   Trying 211.231.99.209...
* TCP_NODELAY set
* Connected to dapi.kakao.com (211.231.99.209) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: D:\curl-7.56.1\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=KR; ST=Jeju-do; L=Jeju-si; O=Kakao Corp.; CN=*.kakao.com
*  start date: Oct 11 00:00:00 2017 GMT
*  expire date: Dec 10 23:59:59 2018 GMT
*  subjectAltName: host "dapi.kakao.com" matched cert's "*.kakao.com"
*  issuer: C=US; O=thawte, Inc.; CN=thawte SSL CA - G2
*  SSL certificate verify ok.
> GET /v2/local/search/address.json HTTP/1.1
> Host: dapi.kakao.com
> User-Agent: curl/7.56.1
> Accept: */*
> Authorization: KakaoAK kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
> Content-Length: 45
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 45 out of 45 bytes
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 15 Nov 2017 07:47:59 GMT
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Request-Id: 4cc1b960-c9d9-11e7-829d-7958710f4ae1
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: Authorization, KA, Origin, X-Requested-With, Content-Type, Accept
<
{"meta":{"is_end":true,"total_count":0,"pageable_count":0},"documents":[]}* Connection #0 to host dapi.kakao.com left intact

**Comment by daumPostcode** [comment]
@blue4313 

네~ 안녕하세요~

올려주신 예제를 보니 kkkkkkk~~~ <- 이 부분이 보이는데요.

GET /v2/local/search/address.{format} HTTP/1.1
Host: dapi.kakao.com
Authorization: KakaoAK {app_key}

kkkkkkk~~ 이부분에 blue님께서 할당받은 API KEY를 넣으셔야 합니다. 
해당 예제는 샘플이라 저렇게 표시되어 있는 것이며,  한번 바꿔 보시겠어요?

구체적인 답변을 원하시면 https://devtalk.kakao.com/ 에 남겨주시는게 좋을 것 같습니다.
해당 API는 제가 관리하거나 하는 API가 아니라서 답변에 한계가 있거든요;;

확인 부탁드립니다.

**Comment by blue4313** [comment]
네 당연히 발급받은 키로 넣어서 했죠.
kkk는 보안상 저렇게 표시한것 뿐입니다. ㅎ

**Comment by daumPostcode** [comment]
@blue4313 
아하 그러시군요..

위에 적은 것처럼 데브톡에 문의 주시는게 좋을 것 같습니다. 해당 API는 제가 답변을 드리기가 좀 어려워서; 
번거로우시겠지만 데브톡의 문의 부탁드립니다;
