### ISSUE TITLE
모바일 삼성브라우저 이슈 공유드립니다.

### ISSUE THREAD

**Issue by devellany** [daumPostcode/QnA#249]
안녕하세요, QA 중 모바일 삼성브라우저에서 특이증상이 나타나 공유드립니다.
해당 증상에 대한 원인은 다음과 같은데요.

a 태그 href="javascript:;"로 되어 있는 부분을 길게 누르고 있을 경우
삼성 브라우저에서는 href의 값이 링크 주소라 판단하여 해당 값(javascript;)을 그대로 출력해줍니다.

다음우편번호API의 경우
주소를 검색 후 뜨는 리스트에 있는 주소에 전부 a태그가 저렇게 걸려있는데요.
마우스포인터 때문에 a태그를 쓴 것이라면 css로 처리하면 어떨까 싶은 생각이 들었습니다.

a태그 속성인 href에 javascript를 호출하는건
ECMA에서도 비표준으로 사용하지 말라는 권고가 있었으니 개발에 참고하시면 좋을 것 같네요.

감사합니다.

**Comment by daumPostcode** [comment]
@devellany 
네~ 안녕하세요~

이슈 제보 감사드립니다. 해당 a 태그는 습관에 의해서 쓰여졌다고 보셔도 됩니다.;;;; 이슈 확인하였고 초기에 왜 이렇게 구성을 하였는지는 몇년 지나다 보니 기억이 잘 나진 않네요; 말씀하신 것처럼 접근성 부터 해서, a 태그의 의미에 맞지 않는 사용방법이라고 생각이 됩니다.

해당 이슈는 조만간 수정 작업을 하여 처리하도록 하겠습니다.
제보 감사드립니다 ^^

**Comment by daumPostcode** [comment]
@devellany 
안녕하세요~ 

금일 패치로 인해 anchor태그와 관련한 의미에 맞지 않는 몇몇 태그의 변경이 되었습니다.

제보 감사드리며. 앞으로 이용시에도 불편한 점이 있으시면 언제든 이슈 주시면 감사하겠습니다~

즐거운 하루되세요~
