### ISSUE TITLE
크롬 CORS 보안이슈.

### ISSUE THREAD

**Issue by minias** [daumPostcode/QnA#25]
![image](https://cloud.githubusercontent.com/assets/4125264/18701643/b49df050-8018-11e6-9886-bc9a851e3409.png)

다음코드의 document.write 에서 크롬 CORS 보안 정책에 걸립니다. 
document.write('&lt;script charset="UTF-8" type="text/javascript" src="'+(i+l[a])+'">&lt;/script>');

reason:
https://developers.google.com/web/updates/2016/08/removing-document-write
solution:
https://docs.google.com/forms/d/e/1FAIpQLSdMQ7PfoVMob5OTXSgodoG5V1eNC5CyQ_qo4skbN62RDSEPcg/viewform

**Comment by daumPostcode** [comment]
@minias 

네~ 안녕하세요~

해당 오류는 CORS오류라기 보다 네트워크가 느린 환경에서 문제가 될 수 있다는 오류로 확인이 됩니다.

document.write를 쓰는 이유가 loader스크립트가 core스크립트를 부를때 동기화를 하기 위해서, 즉 본문에서 바로 저희 우편번호 서비스를 이용하려 할때 객체가 없다는 오류를 막기 위해, 페이지를 블락하고 core스크립트를 불러오게 하기위해 이용하고 있습니다.
또한 하위 브라우저 (IE6 이상 모든 모던브라우저) 대응을 위해서도 현재 이용하고 있는데요, 

문제가 되는 부분은 네트워크가 느릴때, head안에 저희 스크립트를 넣어두시면 페이지가 블락되어 안나올 수 있다는 오류 입니다. 현재 해당 문제에 대해 여러가지 해결책이 있지만, 현시점에서는 적용하기 힘들어 고민 중입니다;;

일단 사용하실때 오류메세지를 안뜨게 하실려면, "동적로딩" 방법을 이용하시면 되실 듯 합니다. 이 방법은 저희 가이드 페이지에서 확인 가능합니다.

아무튼 제보 감사드리며, 해당 이슈는 enhancement로 남겨두도록 하겠습니다.

감사합니다.

**Comment by minias** [comment]
우선 POSTCODE 공개해주신 구다음/현카카오측에 감사드립니다. 

브라우져단의 클라이언트의 네트워크 속도가 느리다기엔 응답속도가 (TTFB포함) 상당히 빠른편입니다. 
캐싱된걸 기준으로 300~500ms 정도이고 non cashing 일때 7~800ms 정도 나옵니다. 

말씀하신 네트워크가 느릴때 생기는오류는 아닌듯 싶습니다. 

해결방안이 2개정도 있는데 "구글크롬쪽 권고안은 가급적 CORS를 지켜라"가 원칙이고, 
정안되면 CDN을 등록하고 < 구글크롬에서 확인된 리소스인경우 오류처리에서 제외시켜주겠다로 
저는 이해했습니다. 

감사합니다.

**Comment by minias** [comment]
크롬 M55 버전부터는 해당이슈계속 생길듯 합니다. 
이에 대한 토론 Post 링크로 남겨드립니다. 

https://github.com/WICG/interventions/issues/17#issuecomment-245522052

**Comment by minias** [comment]
우선 POSTCODE 공개해주신 구다음/현카카오측에 감사드립니다.

async="async" 앨리먼트로 해결하였습니다.

**Comment by daumPostcode** [comment]
@minias 
네~ 맞습니다~ 저도 처음에 네트워크 관련된 오류인줄 알았는데; 확인해 보니 아니더라구요,

말씀해주신 것처럼 크롬 M55버전 이후부터는 계속 발생할 거라고 생각하고 있구요, 기본적으로 사용하는데 이상은 없지만, 약간 꺼림찍한게 사실입니다.

현재 core스크립트 호출의 경우, 불러오는 것과 실제 사이트의 비지니스 로직에 영향을 주지 않기 위해 일부러 lock을 걸기 위해 document.write를 사용하고 있으나, 말씀해 주신 것처럼 동적로딩 기능을 활용하면 해결할 수 있습니다. (이 부분은 저희 가이드 페이지에도 서술 되어 있습니다.
또는 google처럼, API로딩을 할시 서버에서 core스크립트 chunk를 모두 합쳐서 내려주는 방안도 생각중이지만, 현재 여건상 도입이 조금 힘듬 점 양해 부탁드립니다.

저희 API뿐만 아니라 지도 API포함 javascript API의 호출관련하여 전체적으로 발생하고 있는 이슈라서 이 부분에 대해서는 계속 확인해 보도록 하겠습니다.

의견 감사드립니다 ^^

**Comment by minias** [comment]
> 동적로딩 기능을 활용하면 해결할 수 있습니다. 
이부분으로는 해결이 되지 않고 
위에 언급한 엘리먼트를 이용해야지만 크롬M55 이상에서 CORS 경고가 뜨지 않습니다.

**Comment by daumPostcode** [comment]
@minias 
네~ minias님

자세한 확인 감사드립니다. 다음번 업데이트때 가이드 페이지에 추가하도록 하겠습니다.
감사합니다~
