### ISSUE TITLE
같은 페이지에서 해당 필드에 입력이 안됩니다

### ISSUE THREAD

**Issue by hongjin-park** [daumPostcode/QnA#250]
같은 페이지에
quform을 사용중이고, 탭 등으로 2개 이상의 폼이 들어가 있습니다
(qufom 사용시 document.getElementsByName으로 사용해야 입렵이 된다고 합니다)
검색우편번호 검색시 해당 주소 클릭시 해당 폼에 주소가 들어가지 않고,
마지막 폼의 필드에 입력이 됩니다
[1번 ]탭에서 검색 후 클릭하면 [1번 탭] 에 입력이 안되고, [2번 탭] 으로 값이 입렵 됩니다

해결방법이 없나요?

예)
[1번 탭]
document.getElementsByName('quform_7_15')[0].value = data.zonecode;
document.getElementsByName('quform_7_17')[0].value = fullAddr;
document.getElementsByName('quform_7_18')[0].focus();

[2번 탭]
document.getElementsByName('quform_11_15')[0].value = data.zonecode;
document.getElementsByName('quform_11_17')[0].value = fullAddr;
document.getElementsByName('quform_11_18')[0].focus();

**Comment by daumPostcode** [comment]
@hongjin-park 
네~ 안녕하세요~

알려주신 코드로는 말씀하신 이슈를 확인할 수가 없네요;
oncomplete함수의 구현내용과, 실제 페이지에서 어떻게 우편번호 서비스를 호출 하고 있는지 확인이 필요합니다.
quform은 처음 들어본 것인긴 한데요. 
일단, oncomplete함수 내에서 콘솔을 찍거나 디버깅을 통해 data.zoncode의 값을 넣는 타겟이 되는 변수가 어떤걸로 되어 있는지 확인해주세요. 자바스크립트 동적 바인딩 문제로 인한 문제같아 보이는데 전체 코드를 알 수 없어 확인할 수가 없네요;;

또는 저희가 접근 가능한 페이지를 알려주시면 좋을 것 같습니다.

우편번호 서비스의 문제라기 보다 서비스를 사용하는 부분의 오류로 보입니다.
