### ISSUE TITLE
우편번호와 다음지도 연동 문의

### ISSUE THREAD

**Issue by ghost** [daumPostcode/QnA#251]
다음 우편번호 클릭했을때 다음 지도에서 마커가 표시되는건 했는데

반대로 지도를 더블클릭하는함수를 실행하고 위치값을 가지고 주소명을 가져오는것까지는했는데

우편번호 검색창 #region_name 으로 접근하려고 합니다. 저 아이디가 있는곳이 세번째 iframe인데

$('#__daum__viewerFrame_').contents().find('#region_name').val(주소);

이렇게 접근하면 안되더라구요 무슨 좋은 방법이 있을까요?

**Comment by daumPostcode** [comment]
@charles9306 

음.. 제가 이해한게 맞다면,

가져온 주소값을 가지고, 저희 우편번호 서비스를 띄우고 싶으신 것일까요?
아니면 우편번호 서비스는 띄워진 상태인데 input박스 (서비스내 검색바 영역 #region_name 부분)에 스크립트로 동적 삽입을 하고 싶으시다는 것일까요?

전자는 가능합니다만, 후자는 불가능합니다.

후자의 경우에는 저희 우편번호 서비스는 내부에 저희쪽 도메인으로 연결된 사이트가 뜨는 개념이므로, javascript로는 내부 DOM에 접근 및 제어가 보안상 불가능합니다.

전자의 경우에는 주소값을 가져 오셨다면, open또는 embed함수의 파라미터 중에 q 라는 파라미터가 있는데, 이 파라미터에 해당 주소값을 넣어서 실행을 시키면, 해당 주소로 검색된 결과페이지로 바로 로딩을 시킬 수 있습니다.
이 방법을 이용해 보시는게 어떨까 합니다.

자세한 사항은 저희 공식 가이드 페이지 http://postcode.map.daum.net/guide 페이지를 참고하시기 바랍니다.

**Comment by charles9306** [comment]
지도랑 우편번호랑 같은 div에 있어서요ㅜㅜ 
지도 더블클릭하면 주소가 우편번호 검색창에 들어가서 바로 결과 가져오게 하고싶었는데 아쉽네요...
다음카카오 이미 구현해놓으신거 다 너무 좋아요 가져다 쓰는 기분이라 일 별로안하는 느낌..

**Comment by daumPostcode** [comment]
@charles9306 
ㅎㅎ 넵; 잘 이용해 주신다면 제가 더 감사할 따름이지요.

charles님께서 이용하시려는 방법은 응용부분인 것으로, 제가 구조가 어떻게 되어 있는지는 잘 모르겠지만; 제가 위에 설명한 방법 외에는 저희 우편번호 서비스안에 뽑아낸 주소값을 넣는 방법은 따로 없습니다.. 이는 보안상 저희가 막은게 아니라 브라우저가 막는 거라서요;;;

잘 해결 되시길..

**Comment by charles9306** [comment]
우편번호 생성시 embed에 q : "주소값" 을 주면 검색을 하는데
지도를 더블클릭했을때  우편번호가 autoClose=true인 경우 
우편번호 리스트중 하나를 선택한것처럼  없어지고 카워드를 주고 새로 생성할수는없나요?

**Comment by daumPostcode** [comment]
@charles9306 
네~ 현재 해당기능은 없습니다.
자동 셀렉팅을 원하시는 유저분들이 간혹 계시는데요; 해당 기능은 저희 API가 아닌 다른 REST API를 이용하시는게 맞는 방법 같아요. 저희 API는 유저 검색 화면을 제공을 하는 것으로, data convert 용도로는 적합하지 않습니다.

REST API의 경우에는 행정자치부 도로명주소검색 시스템에서도 제공을 하는 것으로 알고 있으며, Postcodify서비스에서도 제공하는 것으로 알고 있습니다.

일단 저희는 현재 우편번호서비스처럼 데이터를 제공해주는 REST API는 공개가 된 상태가 아니라; 다른 API를 추천드릴 수 밖에 없는 점 죄송합니다.

**Comment by charles9306** [comment]
감사합니다..휴
