### ISSUE TITLE
어제부터 웹 접근성에 위배되고 있습니다.

### ISSUE THREAD

**Issue by hayashidahyea** [daumPostcode/QnA#252]
안녕하세요, 저는 장애인 이용자입니다. 어제부터 Daum 우편번호 서비스가 적용된 모든 웹사이트에서 발생하고 있습니다. 키보드 내비게이션이 작동하지 않습니다. 그제까지만 하더라도 키보드의 탭으로 검색 결과에서 주소를 선택할 수 있었습니다만, 어제부터 불가한 상황입니다. 저와 같은 장애인 이용자에게는 중대한 문제인지라 조속한 개선 부탁드립니다. 감사합니다.

**Comment by daumPostcode** [comment]
@hayashidahyea 
네~ 안녕하세요~

먼저 죄송합니다.
어제 검색결과에서 링크가 아닌데 anchor태그를 쓰는 부분을 모두 다른 태그로 치환을 하였는데; 그래서 발생한 문제 같습니다. 해당 이슈는 조속히 수정하여 재배포 하도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by hayashidahyea** [comment]
신속한 회신에 진심으로 감사드립니다. 협력업체들이 모두 자사 전산에 Daum 우편번호 서비스를 적용한 상태인지라 업무에 어려움이 너무나도 큽니다. 조속한 개선 부탁드립니다.

**Comment by daumPostcode** [comment]
@hayashidahyea 
안녕하세요~

과거 히스토리를 잊고 있어서 발생한 제 실수였습니다.
제보해 주셔서 금일 11시 30분 실서버 배포 되었습니다.

다시한번 불편을 드려 죄송합니다.

앞으로도 다른 문제가 있으시면 언제든 제보 부탁드립니다. 감사합니다.
