### ISSUE TITLE
주소 검색 결과 화면에서 스크롤이 되지 않습니다.

### ISSUE THREAD

**Issue by mkkimbbb** [daumPostcode/QnA#253]
안녕하세요.
안드로이드 웹뷰로 주소 검색을 연동하였습니다. 
최초 검색하여 검색이 많은 경우에는 스크롤이 되지 않습니다.
(다른 동작들(X버튼, 검색버튼 등등)은 모두 정상 동작 됩니다.)
그 단어를 다시 검색하면 스크롤이 정상적으로 동작이 됩니다.
혹시 이 문제에 대해서 해결 할 수 있는 방법이 있다면 알려주시면 감사하겠습니다.
(검색 단어로 치킨, 커피, 서울 이런것들로 검색하면 됩니다.)

**Comment by daumPostcode** [comment]
@mkkimbbb 
네~ 안녕하세요~

제가 개인적인 일이 있어서 답변을 너무 늦게 드린점 죄송합니다.

일단 해당 현상은 보고 된적이 없는 이슈이네요.
스크롤 문제는 iOS, Android 그리고 네이티브 브라우저와 웹뷰의 경우에 따라 작동하는 방식이 미묘하게 다릅니다.
특히나 웹뷰의 경우 셋팅하는 방법에 따라 매우 다른 차이를 보이고 있습니다.

일단, 해당 서비스를 기본 웹브라우저나 크롬으로 띄웠을때도 그런지 확인해 주시고, 만약 웹뷰에서만 그렇다면, 스크롤링 관련해서 테스트를 해보셔야 될것 같습니다.

웹뷰의 경우 개발자마다 구현방식이 달라서 재현이 어렵고, 앱내의 웹뷰에서 이용하실때의 이슈는 제가 100% 케어를 해드릴 수 없는 점 양해 부탁드립니다.

**Comment by mkkimbbb** [comment]
안녕하세요. 
답변 주셔서 감사합니다.

크롬에서는 발생하지 않지만 웹브라우저에서도 동일 발생합니다. 
혹시 브라우저 버전에 따라서 발생되는 것인지도 몰라서 User-Agent 일부를 알려드립니다.

User-Agent:
Mozilla/5.0 (Linux; Android 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

혹시 브라우저의 해당 버전으로 테스트가 가능하다면 재현이 될 것으로 판단됩니다.
바쁘시겠지만 다시 한번 확인 부탁 드립니다.

**Comment by daumPostcode** [comment]
@mkkimbbb 
넵~ 감사합니다. Android 5.1 일반 웹브라우저로 현상 확인해서 말씀드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@mkkimbbb 
추가 질문 드립니다.
UserAgent말고, 해당 현상이 발생하는 단말기 정보를 정확히 알 수 있을까요?
벤더사, 모델명, 안드로이드 버전, 이슈가 발생하는게 공식 가이드 문서 페이지 인지, 또는 개발중인 페이지라던지, 또한 Open함수를 이용하여 팝업을 띄워서 사용하시는지 embed를 통해 레이어모드로 사용하는지도 필요합니다. 특히나 layer모드를 사용하게 되면 삽입이 되는 주면 DOM 노드의 스타일에 영향을 매우 많이 받게 됩니다. 이럴 경우 해당 창을 띄우는 주변 코드도 필요합니다.

빠른 테스트를 위해서 좀 더 많은 정보를 제공해 주시면 좋겠습니다.

**Comment by daumPostcode** [comment]
@mkkimbbb 
안녕하세요~

해당 이슈를 확인해보니, 해결이 시간이 좀 걸릴 것으로 보입니다. 일단 디버깅이 안되서 감으로 추적을 하고 잡아야 하는데,
일단 재현이 되는 케이스가

레이어 모드로 실행하고 검색버튼을 누르면 저희 서비스는 form.submit()으로 자신의 페이지로 서브밋을 하게 됩니다. 그럼 이때 페이지가 새로고침이 되어야 하는데, 간혹, 또는 특정 검색어에 따라 새로고침이 안되고, 꼭 ajax로 데이터를 불러와서 렌더링 하는 것처럼 렌더링이 될때가 있습니다. 그럼 거의 90%이상 스크롤이 블락이 되더라구요.

이 문제는 아래 여러가지 이슈가 섞여있을 수 있습니다.
- Android 5.1의 일반 브라우저의 버그
- 키보드 버그
- iframe렌더링 버그, 특히 레이어 모드의 경우 2중 iframe이라 브라우저에 따라 버그가 좀 많이 발생합니다.
- 검색어에 따른 재현 비율은 현재 추측 불가

최대한 브라우저 체크를 통해 맞추긴 했는데, 검색어에 따라 재현이 되고 안되고는 확실히 알 수가 없네요.

이슈를 재현해 보고, 처리 방법을 고민해봤는데요, 좀 더 봐봐야 되겠지만, Android 5.1 버전을 위해 전체 코드에 영향을 주는 수정을 하는 것은 리스크가 더 크다 판단되어, 5.1의 경우에만 예외 처리를 하는 방식으로 될 것 같습니다.
그래서 5.1에서만 다소 불편할 수 있는 점은 양해 부탁드립니다;;

일단 금방 처리가 될 줄 알았는데; 생각외로 시간이 좀 걸릴 것 같아요; 처리가 되면; 이 이슈에 추가 댓글로 공유 드리도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@mkkimbbb 
안녕하세요~ 오래 걸려서 죄송합니다.

현재 해당 버전 수정된 버전이, 내일 12월 12일 오후에 배포가 될 예정입니다.

해당 오류는 말씀해주신 안드로이드 5.1 버전 웹뷰(+기본브라우저)의 아이프레임 repaint버그로 인해 발생한 문제로, 해당 플랫폼에서만 우회처리 하였습니다.

늦게 수정하여 죄송합니다.

내일 배포후에 다시 한번 말씀드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@mkkimbbb 
안녕하세요~

금일 13시 30분 실서버에 정상 배포 되었습니다. 확인 부탁드립니다.

감사합니다.

**Comment by mkkimbbb** [comment]
안녕하세요.
재현도 쉽지 않고 수정도 쉽지 않았을텐데~ 수정해주셔서 감사합니다.
정상동작을 확인하였습니다.
감사합니다.
