### ISSUE TITLE
다음우편번호에서 조회가 되지않습니다

### ISSUE THREAD

**Issue by dofofond** [daumPostcode/QnA#254]
왕지4길 29-7 추가부탁드립니다

**Comment by dofofond** [comment]
행자부사이트에서는 검색이됩니다

**Comment by daumPostcode** [comment]
@dofofond 
안녕하세요~

내부 확인이 시간이 좀 걸려서 답변이 늦었던 점 죄송합니다.

현재 내부 시스템 오류로  저번 주 말부터 행자부에서 내려주는 새로운 또는 변경된 도로명 주소가 저희 시스템에 반영이 안되고 있었습니다. 현재 해당 오류 확인되어, 업데이트가 정지된 부분부터 순차 적용 중에 있습니다.

현재 해당 담당자분에게 오전 중으로 완료되고 오후에 적용 될 것이라고 전달 받았으며, 적용이 완료되면, 다시 댓글 드리도록 하겠습니다.

불편을 끼쳐드려 죄송합니다.

**Comment by daumPostcode** [comment]
@dofofond 

안녕하세요~ 현재 누락된 주소 반영작업이 완료되어 공유 드립니다.

말씀 하신 주소는 정상 반영되었습니다. 문의 주셔서 감사드립니다.

즐거운 하루 되세요~

**Comment by dofofond** [comment]
감사합니다

**Comment by dofofond** [comment]
m
