### ISSUE TITLE
행정동주소가  없는 경우

### ISSUE THREAD

**Issue by blue4313** [daumPostcode/QnA#255]
/v2/local/search/address.json을 통해서 행정동 주소를 검색하고 있는데요.
없다고 조회가 안 되는 경우도 있어서..
이런 경우는 어떤 경우인지 자세히 알고 싶어서요.

ex) 
경기 수원시   영통구 매탄동 <- 주소로 검색 시 
h_code 와region_3depth_h_name이 없는 경우에 대해서 
답변 부탁드려요.

"road_address": null,
      "address_name": "경기 수원시 영통구 매탄동",
      "address": {
        "b_code": "4111710100",
        "region_3depth_h_name": "",
        "main_address_no": "",
        "h_code": "",
        "region_2depth_name": "수원시 영통구",
        "main_adderss_no": "",
        "sub_address_no": "",
        "region_3depth_name": "매탄동",
        "address_name": "경기 수원시 영통구 매탄동",
        "y": "37.27042560112431",
        "x": "127.0403402865589",
        "mountain_yn": "N",
        "zip_code": "",
        "region_1depth_name": "경기",
        "sub_adderss_no": ""

**Comment by daumPostcode** [comment]
@blue4313 
네~ 안녕하세요~

해당 API는 제가 담당하고 있는 API가 아니라서 정확하고 자세한 답변을 드리진 못하는점 양해 부탁드립니다.
또한 해당 API는 https://devtalk.kakao.com/ <- 여기에 질문을 주셔야 답변이 가능할 것으로 보입니다.

다만 우편번호 서비스를 담당하고 있는 저의 개인적인 생각을 적어보면,

"경기 수원시 영통구 매탄동" <- 이 주소의 경우에는 법정동으로써의 주소입니다.
참고 : http://map.daum.net/?map_type=TYPE_MAP&map_usedistrict=bboundary&q=%EA%B2%BD%EA%B8%B0+%EC%88%98%EC%9B%90%EC%8B%9C+%EC%98%81%ED%86%B5%EA%B5%AC+%EB%A7%A4%ED%83%84%EB%8F%99&urlX=514945&urlY=1045917&urlLevel=5

위 링크를 들어가 보시면 법정동 경계가 보이는데, 공유가 완벽하게 되진 않지만 좌측 주소 부분을 선택하시면 매탄동 영역이 강조되어 보실 수 있습니다.

이와 반대로 행정동으로써의 주소는 매탄동이 아닌 "매탄1,2,3,4동" 입니다.
참고 : http://map.daum.net/?map_type=TYPE_MAP&map_usedistrict=bboundary%2Chboundary&q=%EA%B2%BD%EA%B8%B0+%EC%88%98%EC%9B%90%EC%8B%9C+%EC%98%81%ED%86%B5%EA%B5%AC+%EB%A7%A4%ED%83%84%EB%8F%99&urlX=514945&urlY=1045917&urlLevel=5

확대를 좀 해서 보시면 법정동인 매탄동이 4개의 행정동으로 구분되어 있는 것을 확인 가능하실 겁니다.

이와 같은 이유로, address.json REST API로 "경기 수원시 영통구 매탄동" 쿼리를 던지면,
총 5개의 결과가 나오는데, 첫번째께 법정동으로써의 주소정보이고, 나머지 4개가 행정동으로써의 주소정보로 보입니다.
그래서 첫번째 법정동으로써의 주소정보에는 hcode및 region_3depth_h_name 정보가 있을 수가 없죠.
이외 1번째부터 5번째의 주소는 행정동 주소로써, 반대로 bcode와 region_3depth_name 정보가 없는 것을 확인 가능하실 수 있을 거에요.

즉 주소의 타입에 따라 데이터가 있고 없고의 차이가 있는 것으로 보입니다.

추가적으로 매탄동의 경우에는 법정동 경계에 행정동이 잘 들어가 있는데, 모든 주소가 이렇지 않으며, 법정동과 행정동이 전혀 다른 주소도 있고, 서로 겹쳐져 있는 지역도 있습니다.
예를 들어 제주시 도남동의 경우에는 법정동으로는 도남동이지만, 행정동으로는 이도2동 입니다;;

도움이 되셨을지 모르겠네요;

이외 더 궁금한 점이 있으시면 맨 위에 적은 링크(데브톡)로 들어가셔서 질문 남겨보시는게 좋을 것 같습니다~

감사합니다.

**Comment by blue4313** [comment]
ex) 경기 남양주시 진건읍 다산순환로 325 (배양리, 다산신도시 아이파크 상가)
ex) 경기 남양주시 진건읍 다산중앙로146번길 7 (배양리, 다산신도시 자연&amp; 롯데캐슬)

위 주소 등으로 검색했을 경우 h_code가 없는 경우도 있을 수 있나요?
모든 법정동 주소에는 행정동 주소가 있는게 아닌가요?

참고로 주소검색 테스트는 
https://developers.kakao.com/docs/restapi/tool
에서 해봤습니다.

**Comment by daumPostcode** [comment]
@blue4313 

네~ 
우선 데브톡에 글을 남겨주시기 바라며, 해당 사항에 대해서는 내부 담당자 분께 한번 여쭤보도록 하겠습니다.
(제가 담당자가 아니라서 정확한 답변을 못드리겠네요)

담당자분 답변이 오면 제가 댓글로 말씀드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@blue4313 

안녕하세요~ 담당자분께 답변이 와서 추가 공유 드립니다.

일단 첫번째 질문인 "경기 수원시 영통구 매탄동" <- 이렇게 특정 상세주소(도로명 본본/부번, 지번 등)가 없는 3뎁스(동/리 지역) 주소의 경우 주소를 특정할 수 없기 때문에, 법정동 정보와 행정동 정보가 따로 분리되어 내려가기 때문에, 데이터의 타입에 따라 hcode/hname이 있거나 없거나 할 수 있습니다.

그리고 댓글을 지우시긴 했지만, 
"경기 남양주시 진건읍 다산순환로 325" 이 주소와 같이 특정 주소의 상세주소까지 입력된 구체화된 주소의 경우 매핑이 안되는 주소를 제외하고는 모두 hcode hname이 있어야 됩니다. 다만, 해당 API의 경우 실시간 매핑이 아닌, 미리 데이터를 매핑시켜놓는 시스템으로써, 현재 몇몇 주소가 파악이 안된 오류로 인해 매핑 정보가 빠져있다고 합니다.

현재 해당 담당자 분께서 버그인지 정책인지 확인하여 수정중에 있습니다. 추후 수정이 완료되면 말씀드리도록 하겠습니다.
