### ISSUE TITLE
The SSL certificate used to load resources from https://ssl.daumcdn.net will be distrusted

### ISSUE THREAD

**Issue by miraten** [daumPostcode/QnA#256]
지난 주 후반부터 JavaScript console 창에 다음과 같은 메시지가 나옵니다. 어쩌면 그 이전부터 나왔는지도 모르겠는데요. 제가 이 메시지를 보게 된 것은 지난 주 후반부터입니다.

https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js

이 파일을 로드할 때 나오는데요.

무슨 문제인지요?

특별하게 오동작하거나 하지는 않지만, 이런 메시지가 나오니 좀 찜찜하네요.

The SSL certificate used to load resources from https://ssl.daumcdn.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by daumPostcode** [comment]
@miraten 
네~ 안녕하세요~

답변이 늦어서 죄송합니다.
인증서와 관련된 부분은 다른 팀에서 담당을 해서 답변 받는데 시간이 좀 걸렸습니다.

해당 이슈는 말씀하신 것과 같이 API 사용에는 문제가 없으나, 크롬이 제가한 시만텍 인증서에 대한 부정발급 이슈 때문에, 구글에서 크롬의 인증서 신뢰 기준이 변경되서 그렇습니다.

해당 이슈는 회사 전사적으로 교체 plan을 가지고 있어서 단계적으로 진행이 될 예정입니다.

구글이 제시한 기간에 맞추어 인증서가 미리 교체가 될 예정이며, 결과적으로 사용하는데 지장이 없도록 하겠습니다.

감사합니다.

**Comment by ewheelerinc** [comment]
You should check your site to see if it is affected:
  https://www.linuxglobal.com/chrome-symantec-website-check/
If it is, re-issue or re-order your SSL certificate.

**Comment by daumPostcode** [comment]
@miraten 

Hello

Symantec-chrome issue is known issue.
Currently, it is on schedule at company level.

Thank you.

**Comment by daumPostcode** [comment]
@ewheelerinc 
Hello

Symantec-chrome issue is known issue.
Currently, it is on schedule at company level.

Thank you.

**Comment by okdonga** [comment]
안녕하세요. 위와 동일한 이슈 때문에 문의드립니다. 

크롬 안내문(https://security.googleblog.com/2018/03/distrust-of-symantec-pki-immediate.html) 에 따르면 2018년 7월 20일 이전에 인증서 교체가 이뤄지지 않으면 Chrome 70 베타 버전 부터 서비스 영향이 있을 것이라고 안내되어 있는데요. 

시간이 얼마 남지 않은 것 같아 여쭤봅니다. 사용자 입장으로써 미리 대응할 부분 있다면 안내 부탁드립니다.

**Comment by daumPostcode** [comment]
@okdonga 
네, 해당 인증서 관련 이슈는
전사 차원에서 plan을 가지고 진행을 하고 있습니다. (저희 뿐만 아니라 전사 대부분의 서비스들도 같은 이슈가 있어서요.)

그래서 사용자 입장에선 추가적으로 미리 대응하실 필요는 없으실것 같습니다.

현재 인증서는 이번달에 구매 예정이고 각 서버 담당자가 교체 작업을 진행한다고 하니; 잠시만 기다려 주세요.
