### ISSUE TITLE
도로명 주소는 확인 되었으나 다음에서 확인되지 않습니다.

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#257]
경기도 광주  태전동 99(태전동로 50) 힐스테이트

확인부탁드립니다!

**Comment by daumPostcode** [comment]
@dysong1 
안녕하세요.~
도로명 주소 검색 사이트에서 확인해보니 말씀해 주신 주소랑 다르네요
![2017-12-13 10 22 15](https://user-images.githubusercontent.com/20675065/33917093-9432b76e-dfef-11e7-8261-50594eeefd04.png)
![2017-12-13 10 22 28](https://user-images.githubusercontent.com/20675065/33917095-9742c6ba-dfef-11e7-970d-86fdaa936b79.png)

현재 정상 반영되어 있는 것으로 확인이 됩니다.

확인 부탁드립니다.
