### ISSUE TITLE
듀얼 모니터인 경우 화면 중앙에 팝업 띄울수가 없네요

### ISSUE THREAD

**Issue by ahnyg** [daumPostcode/QnA#258]
듀얼 모니터를 쓰고 있고 밑에가 주모니터 위에가 서브모니터인 경우 
서브모니터에서 팝업 호출시 서브모니터 하단에 팝업창이 뜹니다.
일반적으로 팝업 띄울때 top 좌표를 마이너스로 주면 위로 뜨는데 
다음 도로명 주소는 마이너스인 경우 값에 상관없이 무조건 서브모니터 하단에서만 뜨네요
확인 부탁드려요~

**Comment by daumPostcode** [comment]
@ahnyg 
네~ 안녕하세요~

open함수를 통해 띄우는 팝업창의 경우 현재 음수값은 받지 않도록 설정이 되어 있네요; 아마 Mac에서는 음수값을 입력을 해도 0으로 입력된 것과 같은 현상이 발생해서 코드적으로 예외처리를 해둔것 같습니다(개발 당시에요;;;)

방금 13일 10시 40분에 음수값도 받을 수 있도록 수정되어 배포 되었습니다.

숫자 값의 제한은 없으며 Integer형식으로만 입력하셔야 합니다.

감사합니다.
