### ISSUE TITLE
A few questions regarding version number and time out.

### ISSUE THREAD

**Issue by ABahukhandi** [daumPostcode/QnA#259]
Hi Team DAUM,

- What is the current version of Daum Postal Code Service ?
- Is there any way to know if Daum service is down ? **Scenario**: The javascript loaded successfully but after some time for some reason DAUM Postal Code service is down. The pop-up or iframe will be blank/not open. Is their any way to handle this ?

**Comment by daumPostcode** [comment]
@ABahukhandi  

hi~


1. The current version is v2 and the internal version is automatically updated. You do not have to care.

2. Please refer to the [guide](http://postcode.map.daum.net/guide) document and [FAQ](https://github.com/daumPostcode/QnA). (Use the Chrome translation service, or just look at the code.)

And this service is a web-based service and only works on the web server.
so if your testing, you need to have domain information (at least http: // localhost)
Do not execute with file: //
also does not work if you set the document.domain to the parent page.

For more information, please provide your code snippet
