### ISSUE TITLE
IOS에서 인베드 처리시 스크롤

### ISSUE THREAD

**Issue by owensim** [daumPostcode/QnA#26]
IOS에서 인베드 처리시 해당영역에 스크롤이 안먹고 전체페이지에서 스크롤이 됩니다..

안드로이드에서는 이상이없는데 IOS에서는 이런 현상이 발생하네요

**Comment by daumPostcode** [comment]
@owensim 
네~ 안녕하세요~

저희 샘플을 보시면 later DOM 노드에 -webkit-overflow-scrolling:touch 라는  속성이 추가가 되어 있는데요~
iOS, Android가 inner scroll기능이 약간 상이하게 동작하는 현상이 있어, 저희 샘플에는 모두 추가가 되어 있는 속성입니다. 한번 이 속성을 추가해 보시겠어요? (샘플코드나 확인가능한 정보가 없기 때문에 일단 이 문제라고 추측됩니다)

링크는 [가이드 페이지](http://postcode.map.daum.net/guide#sample)에서 "iframe을 이용하여 레이어 띄우기" 부분의 샘플 코드를 참고 해주시기 바라며, webkit-overflow-scrolling에 관해서는 구글링을 해보시면 더 많은 자료가 나오기 때문에 한번 확인 부탁드립니다~
