### ISSUE TITLE
망분리 PC에서 사용 

### ISSUE THREAD

**Issue by masterK-m** [daumPostcode/QnA#260]
저희가 정보보안(ISMS) 때문에 망분리 PC에서만 고객 정보를 조회 및 수정을 할 수가 있는데요

저번에 다음 우편번호 검색 쪽 js에 포함된 도메인들을 대상으로만 방화벽 허용을 하고 사용을 하고 있었는데 이번 js 보니까 17년 12월 13일에 한번 수정이 있고 난 후에 
또 ip들이 변경이 된건지 망분리 PC에서 조회가 안되더라구요 

지금 183.110.194.17(//t1.daumcdn.net/cssjs/postcode/1513129253770/171213.js) 은 방화벽을 허용을 해놓은 상태인데 또 다른게 있는거 같아서요 

http://t1.daumcdn.net/cssjs/postcode/1513129253770/171213.js 이 js 안에 있는 도메인을 확인할 예정이긴한데 
여기서 얻는 답변이 더 정확할거같네요 

도메인 서비스들 변경하신적이 있는지 ip 변경된게 있는지 확인부탁드려요

**Comment by masterK-m** [comment]
아 참고로 지금 저희 방화벽에서 허용된 목록은 

http://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1495012223804/170517.js

https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1495012223804/170517.js

http://postcode.map.daum.net

http://spi.maps.daum.net/postcode/search

https://spi.maps.daum.net/postcode/search

http://t1.daumcdn.net/cssjs/postcode/1513129253770/171213.js

https://t1.daumcdn.net/cssjs/postcode/1513129253770/171213.js

**Comment by daumPostcode** [comment]
@masterK-m 

네~ 안녕하세요~

음. 일단 제가 API의 버전을 올려서 배포하는 것은 버그 수정 및 기능추가에 관한 건이라, IP주소 변경과는 별개입니다.
t1,s1, 이런 도메인들은 저희 CDN서버이고, 해당 팀에서 따로 관리를 하게 됩니다. (변경건에 대해 저희에게 통보를 해주거나 하진 않습니다.)

자주 변경되지는 않지만, 충분히 변경될 여지가 있기 때문에 내부망에서 사용하시는 분들은 주기적으로 체크를 해주셔야 합니다.

저흰 공식적으로 내부망을 지원하진 않지만,  웹서비스이므로 사용할 방법이 있기 때문에 따로 막거나 하진 않을거에요.
다만 지속적으로 체크해 주셔야 합니다.

저희가 내부에서 사용하는 도메인 리스트를 다시 적어 드리겠습니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net
- https://apis.daum.net (v3 maps api 사용시)

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://s1.daumcdn.net 
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net
- https://apis.daum.net (v3 maps api 사용시)

감사합니다.

**Comment by masterK-m** [comment]
답변 감사합니다 

저희가 방화벽에서 ip로 예외처리를 하는데 
t1.daumcdn.net 은 ip로 예외처리 하는데에 있어서 한계가 있더라구요 (너무 방대한 ip가 찍혀가지구요)
도메인으로는 어찌 할 방법이 없어서
망분리 PC에서는 우편번호 서비스를 사용하지 않고 수동으로 input 박스에 입력하는 방식으로 결정이 났습니다.

저와 같은 환경에서 작업하시는 분들이 있으시다면 
참고 부탁드립니다.

수고하세요.

**Comment by daumPostcode** [comment]
@masterK-m 
네. 알겠습니다.

초기 기획시 인터넷이 연결된 환경에서, 주소데이터를 관리 및 처리하기 힘든 분들에게 제공하고자 하는 목표로 개발이 진행된 것이라, 현재까지는 망분리가 된 곳에는 공식적으로 가이드를 드리지 않습니다.

다만 시간이 지남에 따라 망분리가 된 곳에서도 저희 API를 사용하시는 분들이 좀 있으신데요, 해당건에 대해서 논의가 깊게 들어가진 못한 상황입니다. 또한 오류 발생시 저희가 접근해서 처리하는 것에도 좀 어려움이 있어서 현재로서는 고려하지 않고 있는 점 양해 부탁드리구요.

한번 더 고민해 보도록 하겠습니다.

그럼 즐거운 하루 보내세요.
감사합니다.
