### ISSUE TITLE
다음주소API와 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by inzaghi111** [daumPostcode/QnA#262]
다음 주소 API를 사용하고자 하는데요.
다음주소 API와 관련한 안내 내용에 아래와 같이 다음에서 검색결과를 수집하는 것으로 나옵니다.

"더 나은 검색결과를 제공하기 위해, 사용처 도메인(referrer) 정보와 검색된 결과들을 log로 남기고 있습니다. 사용자의 개인정보는 전혀 수집하지 않으므로 안심하셔도 됩니다. "

이와 관련해서,
검색결과로 log로 수집하는 정보중에 검색한 사용자의 IP주소 나, MAC address로 수집하는지요?

**Comment by daumPostcode** [comment]
@inzaghi111 

네~ 안녕하세요~

서버 엑세스 로그로 IP까지는 남습니다. 다만 맥어드레스는 수집하지 않습니다.
이외 실제 저희가 로그를 쌓는 부분에서는 도메인을 받고 있습니다.
