### ISSUE TITLE
주소 api 관련 질문입니다.

### ISSUE THREAD

**Issue by kht777** [daumPostcode/QnA#263]
안녕하세요? 
다음주소 api 호출시 region_name의 값을 자동으로 넣어주고 싶습니다.
가능한지 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@kht777 
네~ 안녕하세요~

저희 [공식 가이드 페이지](http://postcode.map.daum.net/guide#methods)

의 함수 부분을 보시면 open/embed 함수의 파라미터로 q 파라미터를 넘길 수 있습니다.
예제도 있으니 보시고 참고하시면 될것 같습니다.

감사합니다.

**Comment by kht777** [comment]
가이드에 정확하게 나와있는걸 못봐서 한참 해맸네요 ㅠㅠ

정말 감사합니다!!
