### ISSUE TITLE
IE에서 주소 검색시 IE가 멈춥니다.

### ISSUE THREAD

**Issue by rlxodus1** [daumPostcode/QnA#264]
안녕하세요.
우편번호서비스 이용중 오류가 발생하여 문의드립니다.

네이버웨일, 구글크롬등으로는 잘되는데

IE에서만 주소검색을하면 (주소검색결과가 많을경우 스크롤바가 줄었다 늘었다 반복하면서) IE자체가 멈춰 버립니다.

테스트 환경은
window 7 / window 10 OS환경에서
IE 8버전과 11버전 두쪽다 이상있습니다
(예시 고리울로 39 )

아래 다음 우편번호서비스 오픈하는 jsp 소스입니다.

`<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

 <div id="layer" style=" display:none;border:5px solid;position:fixed;width:320px;height:500px;left:50%;margin-left:-155px;top:50%;margin-top:-235px;overflow:hidden;-webkit-overflow-scrolling:touch;">
<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="ë«ê¸° ë²í¼">
</div>

<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
<script>

var element = document.getElementById('layer');
//Old_Post1 구주소1,Old_Post2 구주소2,New_Post1 신주소,Addr1 데이터를 넣을 id,Addr1 데이터를 넣을 id,old_new_addrgubun 신주소 구주소 구분 코드 0 구주소 1 신주소
function newaddressOpen2(target,Old_Post1,Old_Post2,New_Post1,Addr1,Addr2,old_new_addrgubun){
	
 	document.getElementById("target_address").value = target ;
	//url = "/scr/customer?request=customerOldAddressPOP";
/*	winPopup = window.open(url,"address", "scrollbars=yes,toolbar=no,status=no,width=820,height=580");
	winPopup.focus();
	 */

		new daum.Postcode({
	        oncomplete: function(data) {
			if(old_new_addrgubun =="0"){
				//구주소 6글자
				document.getElementById(Old_Post1).value = data.postcode1;
	            document.getElementById(Old_Post2).value = data.postcode2;
			}else if(old_new_addrgubun =="1"||old_new_addrgubun == null){
				//신주소 5글자
				document.getElementById(New_Post1).value = data.zonecode;
			}
			
			
            //document.getElementById(Addr1).value = data.address.replace(/(\s|^)\(.+\)$|\S+~\S+/g, '');
            if(data.userLanguageType=='K'){//한글
            	if(data.userSelectedType =='R'){//도로명
    				
                	document.getElementById(Addr1).value = data.roadAddress.replace(/(\s|^)\(.+\)$|\S+~\S+/g, '');
    			}else if(data.userSelectedType =='J'){//지번
    				document.getElementById(Addr1).value = data.jibunAddress.replace(/(\s|^)\(.+\)$|\S+~\S+/g, '');	
    			}
            }else if(data.userLanguageType=='E'){//영어
				if(data.userSelectedType =='R'){//도로명
    				
					document.getElementById(Addr1).value = data.roadAddressEnglish.replace(/(\s|^)\(.+\)$|\S+~\S+/g, '');
    			}else if(data.userSelectedType =='J'){//지번
    				document.getElementById(Addr1).value = data.jibunAddressEnglish.replace(/(\s|^)\(.+\)$|\S+~\S+/g, '');	
    			}
            	
            }
            document.getElementById(Addr2).focus();
	      
                       element.style.display = 'none';
                  },
	        width : '100%',
	        height : '100%'
	    }).embed(element);
	
	  	element.style.display = 'block';  

}

function closeDaumPostcode() {
       element.style.display = 'none';
}

</script>`

**Comment by rlxodus1** [comment]
테스트 환경은
window 7 / window 10 OS환경에서
IE 8버전과 11버전 두쪽다 이상있습니다
(예시 고리울로 39 )

**Comment by daumPostcode** [comment]
@rlxodus1 
안녕하세요~

올려주신 코드에서는 딱히 특이점은 없네요;
oncomplete함수는 아무리 복잡하더라도, 검색결과에서 주소를 선택했을때 실행되는 것으로, 검색자체를 했을때 스크롤이 움직이면서 멈추는 것이랑은 관계가 없습니다.

그래서 코드를 줄여서 보면

var element = document.getElementById('layer'); 
function newaddressOpen2(target,Old_Post1,Old_Post2,New_Post1,Addr1,Addr2,old_new_addrgubun){ 
    document.getElementById("target_address").value = target ; //url = "/scr/customer?request=customerOldAddressPOP"; 
    new daum.Postcode({ 
        oncomplete: function(data) { 
            
        }, 
        width : '100%', 
        height : '100%' 
    }).embed(element); 
    element.style.display = 'block'; 
} 
function closeDaumPostcode() { 
    element.style.display = 'none'; 
} 

이 코드랑 같은데요. 
혹시 테스트 하는 환경(윈도우, IE)에서 저희 가이드 페이지의 'iframe을 이용하여 레이어 띄우기' 샘플을 이용해 보시겠어요?

해당 샘플에서도 오류가 발생하면 우편번호 서비스 문제일 수도 있습니다만, 그게 아니라면, 저희 서비스를 이용하는 페이지(rlxodus1님이 관리하시는 페이지)의 오류일 가능성이 있습니다.

그리고 저희가 접속 할 수 있는 URL을 알려주시면 더 좋을 것 같습니다.

외부 사이트에 임베딩되어 돌아가는 형식이고 JS특성상 외부 js에 영향을 매우 많이 받기 때문에 이용하시는 사이트에서 직접 확인해야 될것 같습니다. 현재 저희 테스트 환경 WIn10, IE11(11.1770.14393)의 가이드 페이지에서는 재현이 되지 않네요.

조금 더 정보를 주셔야 될 것 같습니다.

**Comment by rlxodus1** [comment]
@daumPostcode 
네 jsp 소스내에서 검색함수는 따로없었지만 혹시 몰라 첨부한정도구요
테스트페이지를 알려드리고싶은데 깃헙에 비밀댓글 기능이 있는지를 잘모르겠네요 ^^;
ftdev5@daum.net 여기로 메일 주고 받을수있을까요?

**Comment by daumPostcode** [comment]
@rlxodus1 
네~ 해당 메일로 보내주시면 됩니다.

소스코드 형태는 제가 JSP를 구동할 수 있는 환경이 아니라서;; 웹페이지로 주시면 좋을 것 같아요~

**Comment by rlxodus1** [comment]
@daumPostcode 지금봤네요 ㅠㅠ
메일 보냈으니 확인부탁드립니다!!

**Comment by daumPostcode** [comment]
@rlxodus1 
안녕하세요~

네 사내의 윈도우 테스트 환경이 원할하지 못해서 확인에 시간이 좀 걸리는 점 양해 부탁드립니다.

오전부터 테스트를 좀 해봤는데;
검색결과가 한페이지 15개(최대)일때는 문제가 없고 오히려 이보다 더 적고, 화면 height가 작을때 재현이 되는 것 같더라구요. 알려주신 쿼리가 테스트 케이스에 딱 알맞네요;

다만 현재 정확한 원인은 발견하지 못했으며, IE의 호환성 모드로 인해 렌더링 방식이 바뀌면서 생기는 버그 또는 우편번호 서비스의 코드 이상동작일 수 있겠다는 의심만 있네요;

보통 doctype을 html5모드로 하거나 호환성 모드를 사용하지 않으면 발생하지 않는 오류인데; 알려주신 페이지를 보니 호환성 모드를 IE8을 이용하고 계시는데, 혹시나 IE8이 아닌 IE9 이상을 이용하셔도 된다면, X-UA-Compatible을 IE9이나 Edge로 변경해 주시면 일단 해결은 됩니다.

오류를 잡는데 시간이 좀 걸릴 것 같아서 변경이 가능하시다면 변경해 주시는게 좋을 것 같습니다.
(참고 문서 https://docs.microsoft.com/ko-kr/internet-explorer/ie11-deploy-guide/deprecated-document-modes)

**Comment by daumPostcode** [comment]
@rlxodus1 
해당 코드의 원인이 되는 부분이 확인되어. 금일 배포 예정입니다.

제가 전 댓글에 요청드린 X-UA-Capatible을 변경 안하셔도 정상 동작하게 수정 조치될 예정이나,
가능하시다면 해당 호환성 모드는 안쓰시는 것을 추천드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@rlxodus1 
금일 15시 40분에 실서버에 정상 배포 되었습니다.

한번 확인 부탁드립니다~ 캐시를 한번 날리고 확인해 주시면 감사하겠습니다.

IE의 호환성모드 + 프레임의 높이와 검색 결과의 양에 따른 컨텐츠의 실제 높이에 따라 간혈적으로 발생하는 버그라서
이전 테스트에서 확인이 안됬었네요;;
불편을 드려 죄송합니다.

다른 버그가 있으시면 언제든 댓글 부탁드립니다. 감사합니다.

**Comment by rlxodus1** [comment]
@daumPostcode 
이제 정상적으로 잘되네요! 감사합니다!
