### ISSUE TITLE
일부 핸드폰에서 주소가 제대로 보이지 않고 있습니다.

### ISSUE THREAD

**Issue by 76069884** [daumPostcode/QnA#265]
https://goo.gl/YLCWgy
해당 위치를 가게 되면 우편번호 검색 버튼을 누를경우 제대로 동작하지 않고 있습니다.
확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@76069884 
안녕하세요~

해당 사이트에서 스마트폰에서 접속해서 이용시; 우편번호 검색 버튼을 누르면 힌색화면으로 바뀌는걸 말씀하시는거죠?

해당 이슈는 해당 사이트 관리자분께 말씀하셔야 합니다.
저희는 우편번호를 검색할 수 있는 뷰 페이지를 제공할뿐, 이를 띄우고 조작하고 하는 모든 방법과 책임은 해당 사이트 개발자분에게 있습니다.

우편번호 서비스자체의 검색오류나, 클릭오류 등은 저희쪽의 관할이지만, 해당 오류처럼, 사이트 자체의 오류는 저희가 해결해 드릴 수 없는 점 참고해 주시기 바랍니다.
