### ISSUE TITLE
지번은 같은데 도로명이 다릅니다.

### ISSUE THREAD

**Issue by raidyth1** [daumPostcode/QnA#266]
다음 지도에서는 주소가 
지번이 대구 중구 봉산동 169-9 인 경우 
도로명이 대구 중구 봉산문화1길 24-1 와 대구 중구 봉산문화1길 28-2 두개가 나오는데 
다음 주소에서는 도로명이 대구 중구 봉산문화1길 24-1 만 나옵니다.
대구 중구 봉산문화1길 28-2 를 따로 검색하면  
대구 중구 봉산문화1길 28-1과 대구 중구 봉산문화1길 28-3 만 나오고 대구 중구 봉산문화1길 28-2는 안나옵니다. 
정확하게 하고 싶어서 우체국사이트 들어가서 검색하니 대구 중구 봉산문화1길 24-1만 나오고, 
네이버에서는 대구 중구 봉산문화1길 28-2 만 나오고 대구 중구 봉산문화1길 24-2는 없는 주소로 나오네요.
어떤게 맞는 건가요.. 그냥 다음 주소 검색을 신뢰하면 될까요?

**Comment by daumPostcode** [comment]
@raidyth1 
네~ 안녕하세요~

말씀해 주신 사항에 대해 설명을 드리겠습니다.
다음 지도에서 검색을 하면 나오는 정보에는 주소정보와 장소정보가 있습니다.
![2018-01-03 3 50 26](https://user-images.githubusercontent.com/20675065/34511302-d685048c-f09d-11e7-9804-f281880ad393.png)

여기서 정확한 주소 정보를 확인하고 싶으실땐, 주소 탭의 정보를 확인하시면 됩니다. 장소에 매핑된 주소의 경우에는,
행자부에서 업데이트 되는 시기와, 장소 데이터(CP와 직접관리 데이터)의 업데이트는 차이가 발생합니다. 보통 장소의 정보 수정은 해당 업체의 요청, 유저의 신고, 또는 주기적입 데이터 업데이트 주기에 따라 업데이트가 되어, 실제 주소와 다를때가 존재하게 됩니다.

추가로 주소의 경우에는 매일 업데이트가 됩니다.

즉, 다음 지도에서 주소가 봉산문화1길 24-1, 봉산문화1길 28-2가 나오지만, 실제 주소 탭에는 봉산문화1길 24-1만 있으므로, 해당 지번주소에서 매핑이 맞는 것은 24-1 주소가 맞습니다.

현재 본문에 적어주신 봉산문화1길 28-2, 봉산문화1길 24-2는 없는 주소가 맞습니다.
![2018-01-03 3 58 27](https://user-images.githubusercontent.com/20675065/34511446-08e72c7e-f09f-11e7-8966-7041d95c6c80.png)
![2018-01-03 3 58 36](https://user-images.githubusercontent.com/20675065/34511447-0b9ae42e-f09f-11e7-880c-5188e30be5bd.png)

저희쪽 서비스(다음지도, 다음우편번호서비스)의 결과가 약간 신뢰가 안가실 경우,

www.juso.go.kr 행정자치부 도로명검색 시스템에서 검색해 보시면 확실한 답을 확인 하실 수 있습니다.
또한 저희 우편번호 서비스의 원데이터는 행자부에서 매일 업데이트 됨을 말씀드립니다.
![2018-01-03 3 58 51](https://user-images.githubusercontent.com/20675065/34511450-0f91f45a-f09f-11e7-93d6-4029b3f3f53c.png)


감사합니다. 추가 질문이 있으시면 댓글 주세요~
