### ISSUE TITLE
행자부 도로명주소 사이트에는 등록이 되어있는데 조회가 안됩니다.

### ISSUE THREAD

**Issue by HyereeKim** [daumPostcode/QnA#267]
안녕하세요.
매뉴얼을 보니 행자부 도로명주소 사이트에 등록된 주소의 경우
1일의 업데이트 기간을 거쳐 Daum 우편번호서비스에 반영된다는 내용을 봤는데요.
행자부 사이트에서는 조회되는 주소가 몇일이 걸려도 daum 서비스에서는 조회가 되지 않습니다.
저희가 이용하는 프로그램 상에서의 주소 등록 서비스가 daum 과 연동이 되어있는데,
이 문제 때문에 특정 주소를 등록할 수가 없네요.
빠른 반영 부탁드리겠습니다. 참고로 해당 주소는 경기도 성남시 위례대로 83 입니다.
감사합니다.

**Comment by daumPostcode** [comment]
@HyereeKim 
네~ 안녕하세요~

답변이 늦어서 죄송합니다.

해당 주소의 경우 보안주소로 행자부측에서 저희에게 데이터를 내려주지 않습니다;

도로명검색사이트에서 검색을 해보시면 검색결과에 지도 마크가 없는데요. 이런 주소들은 저희에게 내려줄때 제외를 하고 내려주고 있습니다.

그래서 현재 저희 다음지도 서비스에서도 검색이 되지 않네요;

해당 사항은 README.md 파일에 이미지 첨부하여 수정해 두도록 하겠습니다.

감사합니다.
