### ISSUE TITLE
TLS 버전 지원 문의 

### ISSUE THREAD

**Issue by kiwon5** [daumPostcode/QnA#268]
안녕하세요!

저희 쇼핑몰 사이트에서 다음 우편번호 서비스를 이용하고 있으며 글로벌 정책에 따라 TLS 1.0 사용을 중지할 예정입니다!

혹시 TLS1.0 제거 이후 다음 우편 번호 서비스 이용에 문제되는 부분이 없을지 TLS 버전 지원은 몇버전 까지 가능한지 문의 드립니다!

감사합니다.

**Comment by daumPostcode** [comment]
@kiwon5 
네~ 안녕하세요~

현재 저희 우편번호 서비스는 https://spi.maps.daum.net 과 https://ssl.daumcdn.net
이렇게 2개의 도메인을 이용하고 있으며

말씀하신 TLS는 1.2 버전을 사용하고 있습니다.

해당 정보는 크롬에서 - 개발자도구를 여신다음에 security 탭에서 확인 가능하십니다.

감사합니다.
