### ISSUE TITLE
주소검색 확인요청드립니다.

### ISSUE THREAD

**Issue by sibi81** [daumPostcode/QnA#271]
아래 주소 행정자치부 도로명주소 검색시스템에서 검색되지만
다음 우편번호 서비스에서 검색안되고 있습니다. 확인부탁드립니다.

경기도 화성시 수노을1로 235(새솔동, 더 펠리체 휴먼빌 아파트)

**Comment by daumPostcode** [comment]
@sibi81 

네~ 안녕하세요~


해당 이슈 주소 데이터 담당자분께 말씀드리도록 하겠습니다.
업데이트 주기 문제일 수도 있으니, 한번 내일까지 기다려 주시면 감사하겠습니다.

최대한 빨리 처리하도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@sibi81 
안녕하세요~
주소데이터 담당자분께 답변이 와서 추가 댓글 드립니다.

--------------------
경기도 화성시 새솔동이 1월 22일자로 신설되었습니다.
도로명주소 생성시 법정동코드를 참조하는데, 데이터 처리당시 이 부분이 누락되어 있었습니다.
현재 조치완료하여, 내일 오전에 새솔동 도로명주소가 검색될 예정입니다. (_ _)
참고부탁드리겠습니다.
--------------------


위와 같이 답변이 왔으며, 내일 업데이트 될 것으로 보입니다.
불편을 드려 죄송합니다.
