### ISSUE TITLE
정기점검 같이 중단되는 경우도 있나요?

### ISSUE THREAD

**Issue by ddonglee** [daumPostcode/QnA#272]
안녕하세요, 주소API를 사용하려고 하는데요.
서버점검 등으로 인하여 사용하지 못하는 시간이 발생하는지 궁금합니다.
감사합니다.

**Comment by daumPostcode** [comment]
@ddonglee 

네~ 안녕하세요~

현재 저희 서비스는 서버이전, 업데이트와 같은 이슈에도 무중단 운영을 원칙으로 하고 있습니다. 카카오의 포탈서비스 들을 보시면 API성격을 가지는 서비스는 중단되는 일은 거의 없죠.

다만 저희 서비스또한 카카오 인프라 자산을 이용하는 만큼, 여러 이슈로 인해 장애가 발생할 수는 있습니다.
다만 이때는 전사적으로 대응을 하기도 하고 저희가 인지하는 즉시 플러스맵 친구로 장애관련 메세지를 보내드리며, 장애가 길어질 경우엔 추가 메세지를 드리고 있습니다.

즉 공식적이고 계획적인 이슈로 인해서 서비스가 잠시나마 중단되는 경우는 없으며,
장애에 따라서는 일시적으로 중단이 될 수는 있으나, 이는 최대한 빠르게 해결할 수 있게 노력하고 있습니다.

감사합니다.
