### ISSUE TITLE
https환경에서 

### ISSUE THREAD

**Issue by tndyddldi** [daumPostcode/QnA#273]
The SSL certificate used to load resources from https://ssl.daumcdn.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
이런메세지와 
postcode.v2.js:1 A parser-blocking, cross site (i.e. different eTLD+1) script, https://t1.daumcdn.net/cssjs/postcode/1513129253770/171213.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
이런메세지가 콘솔창에 찍히는데 이런경우는 어떠한 경우인가요??

**Comment by daumPostcode** [comment]
@tndyddldi 

네~ 안녕하세요~

우선 첫번째 이슈에 대해서 설명을 드리면,

구글에서 제시한 이슈로 시만텍 인증서에 대한 부정발급 이슈 때문에, 구글 크롬의 인증서 신뢰 기준이 변경되서 그렇습니다.
해당 이슈는 회사 차원으로 교체 plan을 가지고 있어서 단계적으로 진행이 될 예정입니다.
구글측에서는 추후 제한이 될 수 있으니 교체를 하라고 알림을 주는 것이라 실제 사용하는데 문제는 없으십니다.

두번째 이슈는
저희 API가 javascript API를 정적로딩 즉 loader와 core스크립트를 sync하기 위한 방법으로 document.write를 사용하고 있습니다
이는 다른 페이지 렌더링을 멈추게 한후, 저희쪽 core스크립트를 먼저 내려받고 파싱하기 위해서이며, <script src='....'></script> 이 코드 이후 new daum.Postcode를 실행할때 객체가 없다는 문제를 피하기 위한 방법입니다.
(스크립트 태그를 통한 리소스 로딩은 페이지 파싱과 다르게 비동기라서요)
즉, 이 이슈도 실제 서비스를 이용하는데 문제는 없으며, 크롬에서 document.write를 이용하면 페이지 렌더링이 블락되므로 사용자의 사용성을 저하시킬 수 있으니 조심하라는 메세지 입니다. 실제 이 문제는 페이지 중간에 document.write를 통해서 불러오는 내용이 용량이 크거가, 네트워크 속도가 느릴 경우에는 문제가 되긴 합니다만, 저희 코어 스크립트의 용량이 매우 작기 때문에 문제를 일으킬 정도는 아닙니다.

또한 이 페이지 렌더링 블락을 해결하기 위한 방법으로, 저희 postcode.v2.js를 로딩하는 코드를 </body>바로 위에(페이지 맨 하단) 정의 한후 이 이후에 저희 API를 사용하는 코드를 넣으면 페이지 렌더링 블락이 된다해도 모두 렌더링이 끝난후에 로딩하므로 큰 문제가 되지 않습니다(개발 트릭)
추가적으로 저희 가이드 페이지에 있는 동적로딩 방식을 이용하시면 해당 오류메세지를 피할 수 있으니 참고하시기 바랍니다.

감사합니다.
