### ISSUE TITLE
주소에 포함된 특수문자(・) 관련 문의

### ISSUE THREAD

**Issue by oh4851** [daumPostcode/QnA#274]
아래에 전달드린 주소에 포함된 `・` 특수문자 인코딩 이슈로 저희 서비스에서 알 수 없는 문자로 인식하는 이슈가 있습니다.

__49430 (604-762)__ 부산 사하구 하신번영로 233 (가락타운2・3단지)

이전에 동일(유사)한 이슈가 있는지 확인해보니 이전에 다음과 같은 이슈가 있었는데,
혹시 이와 관련해서 진행된 사항이 있을까요?

__#130 가운데 점(・) 인코딩문제__

**Comment by daumPostcode** [comment]
@oh4851 
네~ 안녕하세요~

링크해 주신 130번 이슈와 같은 이슈이실까요?
일단 해당 이슈의 경우 당시에 내부 데이터 담당자 분들께 공유를 드렸지만, 저희쪽에서는 변경하지 않는 것으로 결정을 하였습니다. 
당시 해당 문자의 인코딩을 바꿨을때의 각 서비스에 파생될 수 있는 문제점과, 원본 데이터로써의 관리 문제, 그리고 보편적인 대다수의 시스템에서 발생하는게 아닌 특정 인코딩을 사용하는 곳에서 발생하는 문제로 인해, 이 문제가 발생하는 곳에서 예외처리를 해주시는 방향으로 이슈를 풀었던 것으로 기억합니다.

즉 해당 이슈는 해당 이슈를 제기해 주신 개발자분께서 예외처리를 하는 방향으로 정리되었고, 저희쪽에서는 따로 이후로 진행을 하지는 않았습니다.

**Comment by oh4851** [comment]
@daumPostcode 
아 답변 감사합니다.
저희쪽에서 `・`에 대한 처리를 별도로 진행해야겠네요. 감사합니다.
