### ISSUE TITLE
Daum Developers 종료

### ISSUE THREAD

**Issue by designode** [daumPostcode/QnA#276]
안녕하세요, 카카오입니다.

그동안 Daum Developers를 이용해 주셔서 감사합니다.

2017년 7월 18일부터 Kakao API 및 Daum API가 Kakao Developers로 통합되어 제공되고 있습니다.

2017년 8월 18일부터 Daum Developers에서 신규 앱 생성이 불가함을 2017년 8월 1일 공지 드린 바 있습니다.

2018년 3월 31일부로 Daum Developers 사이트 서비스 종료, 2018년 12월 31일부로 Daum Developers 사이트에서 제공되었던 v1 Daum API 요청도 종료하게 되어 추가 공지드립니다.

즉, 2018년 3월 31일부터 developers.daum.net에 접속이 불가하고, 2018년 12월 31일부터는 apis.daum.net으로의 모든 요청도 불가합니다.

종료 전에 Kakao Developers로 이관하여 더 다양한 서비스를 즐겨보시기 바랍니다.

* 검색/뉴톤/로컬/지도 v1 Daum API : Kakao Developers에서 v2 Kakao API로 이용 가능

* 로그인/블로그/프로필 v1 Daum API : 카카오로그인 강화를 위한 API 종료

메일이 왔는데

다음 우편번호 서비스와는 상관이 없는건가요???

<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>

**Comment by daumPostcode** [comment]
@designode 
네~ 안녕하세요~

저희 우편번호 서비스 API를 이용하실때, developer사이트에 가입하시거나, apikey를 받거나, 트래픽 관리를 한다거나 하는 것을 안하셨지요? 네. 맞습니다. 저희 우편번호 서비스는 developer사이트와 별개로 운영됩니다.

(4년전 첫 출시시, 개발자사이트에서 안받아 줬어요..... 성격이 애매모호해서;; ㅜ.ㅜ)
즉 첫 출시 이후부터 독립 운영중에 있으며, 그래서 CS도 깃허브로 받고 있는 것이에요~

즉 저희 우편번호 서비스랑은 별개이며, 하나 연관되는 거라면, 저희 가이드 페이지에 보시면 지도 API랑 연동하는 부분이 있는데; 현재 이부분도 kakao developer이용하게 변경해 두었지만 혹시아 예전에 daum developer로 되어 있을때 참고하셨거나 현재 지도 API도 같이 이용중이시라면 이것만 저 메일에서 안내한것처럼 이전하시면 될것 같습니다.

우편번호 서비스는 걱정안하셔도 됩니다.
