### ISSUE TITLE
검색이 되지 않는 주소가 있어 문의 드립니다.

### ISSUE THREAD

**Issue by miyeong** [daumPostcode/QnA#277]
안녕하세요. 다음우편번호 서비스를 이용중인 사용자입니다.

다음 지도에서는 검색이 되는 주소인데 다음지도우편번호에서는 조회가 되지 않습니다.
**경기 이천시 마장면 회억리 산 46** 

도로명 주소가 다음에 없어서 그런것 같은데 업데이트가 가능한지 확인 부탁드립니다. 
도로명 주소 : 경기 이천시 마장면 억만리로137
우편번호 : 17382

**Comment by daumPostcode** [comment]
@miyeong 
네~ 안녕하세요~

말씀해주신 주소는 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)에 해당하는 주소로, 저희 시스템에는 반영되기가 어려워 보입니다.

해당 주소 데이터는 행자부 사이트에서만 검색이 되고, 행자부가 직접 제공하는 API에만 내려줄뿐, 저희에게는 데이터를 내려주지 않습니다.

그래서 해당 주소를 서비스 하지 못하는 점 양해 부탁드립니다.
