### ISSUE TITLE
주소의 최대길이는 어떻게 되나요?

### ISSUE THREAD

**Issue by aceofmath** [daumPostcode/QnA#278]
address, addressEnglish 최대길이는 어떻게 되나요?

**Comment by daumPostcode** [comment]
@aceofmath 
안녕하세요~


35     제주특별자치도 서귀포시 안덕면 중산간서로1615번길 251-24
93     Dangjin Yeongdeok Expressway, Munui-myeon, Sangdang-gu, Cheongju-si, Chungcheongbuk-do

이며, 공백 포함의 길이 입니다.

다만 이 정보는 주소가 업데이트됨에 따라 변할 수 있습니다. (도로명 주소는 1일 업데이트 됩니다)
