### ISSUE TITLE
IE에서 주소검색 후 결과값에 마우스를 올려도 반응이 없습니다.

### ISSUE THREAD

**Issue by djdan1234** [daumPostcode/QnA#279]
안녕하세요. 다음우편번호 서비스를 이용중인 사용자입니다.

Chrome에서는 주소검색 후 나오는 결과값에 마우스를 올리면 밑줄이 생기면서 마우스가 화살표에서 손가락모양으로 바뀌는데, IE에서는 이러한 Action이 나타나지가 않습니다.

아마 windows update 후 해당 부분에서 호환이 맞지 않아 발생하는 것으로 추측되는데 확인을 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@djdan1234 
네~ 안녕하세요~

해당 현상 확인해 보도록 하겠습니다.
다만 IE의 경우 버전이 파편화 되어 있고, 윈도우 또한 업데이트 이후에 발생한다고 하셨는데, OS버전도 알려주셨으면 합니다. 어떤 윈도우의 IE인지에 따라 같은 IE버전이라도 동작이 다르거든요..

원할한 테스트를 위해 OS버전, IE브라우저 버전을 알려주시면 감사하겠습니다.

한가지 더 궁금한 것이, UI변화는 없는데 기능적으로 클릭을 했을때 정상 동작 유무도 알려주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@djdan1234 
안녕하세요~

현재 회사의 Windows10 가상머신이 동작하지 않아, 윈10에서는 확인을 못해봤지만,
일단 Windows7의 IE11(버전 11.0.9600.18893, 업데이트 버전 11.0.50) 에서 정상동작을 합니다. 번거로우시겠지만 이슈가 발생하는 OS와 브라우저 버전을 알려주시면 확인이 더 정확하게 될 것 같습니다. 

감사합니다.
