### ISSUE TITLE
도서산간 정보를 리턴 받을 수 있을까요?

### ISSUE THREAD

**Issue by i2801** [daumPostcode/QnA#28]
현재는 서비스 안되고 있는것으로 알고 있습니다.
검토 부탁드립니다.

**Comment by daumPostcode** [comment]
@i2801 
네~ 안녕하세요~

일단 결론부터 말씀드리면, 제공해 드리기 어려울 것 같습니다.

저희가 행자부로부터 받는 데이터 중 *도서산간* 관련된 정보는 없으며, 도서.산간 지역은 공식적으로 관리하는 것이 아닌, 택배사나 쇼핑몰에서 자체적으로 관리하는 것으로 알고 있습니다. 

좀더 자세히 말씀드리면, 주소DB상에 "SAN"이란 필드가 있지만 이 필드 또한 "0:토지, 1:산" 과 같이 토지의 구분만 하는 것으로 도서산간을 나타내지는 않습니다 실 예로 "서울대학교 - 서울 관악구 대학동 산 56-1" 주소의 경우 주소에 SAN이 들어가고 DB필드에서도 1이 지만, 도서산간지역이 아닙니다.

이와 같이 도서산간지역은 택배사나 기타 다른 서비스를 통해 직접 데이터를 만드셔야 할 것 같아요.

아래는 행자부 도로명주소검색시스템의 Q&A에 있는 질문 답변 내용인데요.
[행자부 Q&A 질문 답변 내용 링크](https://www.juso.go.kr/help/QABoardDetail.do?mgtSn=11065&currentPage=1&searchType=subject&keyword=%EB%8F%84%EC%84%9C%EC%82%B0%EA%B0%84)

위와 같은 내용이 있는데요. 한번 확인 부탁드려요~

**Comment by i2801** [comment]
상세한 답변 감사드립니다.
