### ISSUE TITLE
아이폰에서 주소 검색시 오류건

### ISSUE THREAD

**Issue by sosim13** [daumPostcode/QnA#280]
ssl용 api로 다음 주소 검색을 div팝업으로 사용하고 있는데

이번에 아이폰 안드로이드 어플을 만들게 되어 웹뷰방식으로 작업을 했습니다.

안드로이드에서는 잘 작동이 되는데

아이폰에서 검색시 동입력하고 키보드로 입력 하면 주소가 잘 검색이 되는데

동입력할때 밑에 추천검색어를 클릭시 흰화면만 노출되는 현상이 발생 됩니다.

이거 해결할 수 있는 방법이 있으면 알려주시면 감사하겠습니다.

**Comment by sosim13** [comment]
아이폰 주소검색 질문

**Comment by daumPostcode** [comment]
@sosim13 
안녕하세요~

혹시 해당현상이 웹뷰가 아닌 일반 브라우저(사파리)에서도 발생하는지,
또한 저희가 확인을 할때 필요한 기본적인 정보가 있는데요, IOS의 버전과, 웹뷰로 여시기 때문에 혹시 저희가 접근 할 수 있는 URL또는 코드 조각이 필요합니다. 
추가로 해당 현상의 기본적인 스샷을 제공해 주시면 좀 더 빠른 확인이 될 것 같습니다.

일단 사파리에서도 오류가 발생하는지 확인 가능하실까요? 저희가 테스트 할때 웹뷰의 경우에는 만드시는 개발자마다 모두 코드가 다르므로 저희가 환경셋팅이 불가능하여, 사파리에서만 확인을 할 수 있습니다. 또한 공식 지원도 웹뷰가 아닌 일반 브라우저이기 때문에 일반 브라우저에서도 발생하는지 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@sosim13 
일단, 제가 가이드 페이지에서, 레이어로 띄우기(div 팝업을 이용한 것이 이 샘플이 비슷할 것이라 생각됩니다)로 아이폰 사파리에서 확인결과, 화면이 하얗게 되는 현상은 발생되지 않습니다.

의심가는 사항으로는 아이폰에서는 키보드 관련하여 내재된 버그가 상당히 있는데, 그 문제가 아닐까 합니다. 현재 이 문제는 코드레벨에서 해결이 어려워 유저분들에게 회피하는 방식으로 가이드를 하고 있습니다.

혹시 추천검색어(서제스트)의 갯수 설정을 안해두셨다면, 생성자에 maxSuggestItems 의 갯수를 작게 셋팅해 보시는 것을 추천드립니다. 아이폰 특히나 웹뷰에서 잘 발생하는 버그로, DIV크기가보다 내부 컨텐츠(우편번호 서비스 화면)가 더 길어질 경우 화면에 안보이는 영역으로 스크롤이 이동되어 버리는 현상이 있습니다. 이는 키보드가 떠 있을때나 올라올때 주로 발생합니다. 이 경우에는 현재 위에 말씀드린 maxSuggestItems 옵션으로 추천검색어의 갯수를 줄여서 우편번호 서비스 화면의 세로 길이보다 작게 유지하는 것이 현재로써의 해결책입니다. 

저희 가이드 페이지를 보시면 레이어로 띄우기 예제는 maxSuggestItems 값이 5로 셋팅되어 있으며, 이는 div의 세로 길이를 넘지 않는 선에서 셋팅된 값입니다. 이를 적절히 이용해 보심이 어떨까 합니다.

자세한 사항은 가이드 페이지 참고 부탁드립니다.

이외 다른 이슈라면, 기본적인 오류가 발생하는 환경과 코드 조각, 그리고 가능하시다면 재현되는 단말의 영상이나 스크린샷을 제공해 주시면 오류 확인이 더 수월할 것 같습니다.

한번 확인 부탁드립니다.

**Comment by sosim13** [comment]
https://www.youtube.com/watch?v=OB40f33R2OY

영상 확인 부탁드립니다.

사파리에서는 잘 됩니다.

오류나는 현상먼저 찍고 그뒤에 키보드 정상적으로 넘어가는 부분까지 봐주세요.

앞부분에 상품 선택하는 부분은 스킵하셔도 됩니다.

감사합니다.

**Comment by daumPostcode** [comment]
@sosim13 
네~ 영상 감사드립니다.

일단 저도 
NSURL *url = [NSURL URLWithString:strURL];
NSURLRequest *urlRequest = [NSURLRequest requestWithURL:url];
[self.webview loadRequest:urlRequest];
이런 코드로 웹뷰 하나 만들어서 테스트를 해봤지만; 해당 현상이 발생하지 않았습니다. (제가 앱 개발자가 아니라 구글에서 검색해서 나온 단순한 코드밖에 테스트가 안되는점 양해 부탁드립니다)

해당 영상으로는 원인을 알기가 어렵네요; 일단 
검색바의 검색 버튼
키보드의 검색(완료) 버튼
추천리스트(서제스트)의 클릭

모두 최종적으로는 같은 함수를 실행하게 되며 검색은 form submit으로 이루어 집니다.
즉 서로 다른 방식으로 검색을 하진 않습니다.

그래서
- 사파리의 웹인스펙터를 이용해서 실제 DOM이 사라지는지, 이상한 곳으로 스크롤이 이동되어 있는지 확인 (xcode로 개발하고 빌드해서 테스트 하시는 거라면 이용 가능합니다 - 구글 검색 참고)
- wrapper(DIV) 의 position관련 문제 (이또한 웹 인스펙터를 통해 변경하면서 테스트 가능)
- 서제스트의 검색갯수 줄이기
- DIV로 레이어 띄우는 방식이 아닌 중간에 삽입 방식(카카오톡의 선물하기 에서 저희 우편번호 서비스를 이용하지만 삽입 모드로 이용하고 있으며 해당 현상이 발생하지 않습니다) 실제 모바일 웹뷰의 경우 이 방식을 더 추천드립니다. 

정도의 해결책이 있을 것 같습니다.

죄송하게도 웹뷰의 경우에는 셋팅방법 및 재현 테스트가 어려워 이 이상 확인이 어려운 점 양해부탁드립니다.
추가로 사파리에서 정상 동작한다면 그건 웹뷰의 고유 버그일 수 있으니(사파리와 웹뷰는 버전부터 동작 방식이 좀 많이 다릅니다) 사파리 인스펙터를 통해 해결책을 찾으시면 좋을 것 같습니다.

해결책을 드리지 못해 죄송합니다.

**Comment by sosim13** [comment]
아무리 해봐도 도저히 안되네요.

하얀화면 떳을때 화면 눌러보니까 안에 데이터는 있는지 클릭인 되더라고요.

혹시 추천검색어 안뜨게 하는 방법은 없을까요?

정안되면 추천검색어만이라도 아에 안뜨게 하고 싶은데 방법이 있다면 알려주세요. 

감사합니다.

**Comment by daumPostcode** [comment]
@sosim13 
네; 해결이 안되시는군요 ㅜ.ㅜ

말씀해 주신 기능은 외부 오픈이 안된 옵션이라, 살짝 코드를 건드려야 합니다.
잠시 후에 제가 배포 한 이후에 댓글 드리도록 하겠습니다.

옵션은 생성자에 넣으시면 됩니다.
useSuggest : false

감사합니다.

**Comment by daumPostcode** [comment]
@sosim13 
코어스크립트 버전  180226으로 13시 52분부터 실서버 배포되었습니다.
캐시를 한번 지우시고 확인 부탁드립니다. 옵션명은 위에 설명 드린 것과 같습니다.

불편을 드려 죄송합니다.

**Comment by sosim13** [comment]
정말 감사드립니다.

추가로 검색하던 도중 2017년에도 동일한 오류로 문의 하신분들이 있더라고요

-webkit-overflow-scrolling: touch 부분을 제거 하라 하셔서 제거 하니 하얀화면이 나오는 부분은 수정됐습니다.

다만 스크롤이 안되는 문제가 발생하네요.

아이폰인경우 -webkit-overflow-scrolling: touch 부분도 한번 봐주시면 감사하겠습니다.
