### ISSUE TITLE
주소 검색창이 안 나타나는 경우가 있어서 도움을 요청드립니다.

### ISSUE THREAD

**Issue by friziek** [daumPostcode/QnA#281]
안녕하세요. daumPostcode를 제공 해 주셔서 감사드립니다. 덕분에 쉽게 주소 관련 기능을 만들었습니다. : )
사용을 하는데, 한 가지 문제점이 있어서 도움을 요청드립니다. 
아마도 제가 만든 코드 어딘가가 문제겠지만. ;; (사실 제가 react를 잘 몰라서...;;)

환경은 윈도우와 맥의 크롬이고 react를 이용하고 있습니다. 
현상은 이래요. 
처음에 진입해서 주소(DaumPostcode)를 요청하면 잘 불려집니다. 
![2018-02-23 11 35 08](https://user-images.githubusercontent.com/5343634/36579736-12f8587e-18a8-11e8-989a-432318a45d5b.png)

![2018-02-23 1 33 34](https://user-images.githubusercontent.com/5343634/36578101-8049dd62-189e-11e8-9d10-e878e497cff0.png)

그리고, 해당 화면에서 정보를 저장 후 다른 화면으로 갔다가, 다시 주소 설정이 있는 화면으로 와서 요청을 하면
화면이 나타나지를 않습니다. 이동하지 않고 같은 화면에 있을 때는 문제가 없습니다.
![2018-02-23 11 35 31](https://user-images.githubusercontent.com/5343634/36579748-1cf57d7a-18a8-11e8-994f-0c7680361d28.png)

HTML을 보면 위의 코드와는 다르게 아무런 내용이 없습니다. ;;;;;
![2018-02-23 1 32 34](https://user-images.githubusercontent.com/5343634/36578108-89aae84c-189e-11e8-9c7a-1c4a6feee834.png)

react 에서는 아래와 같이 사용했습니다. 
![2018-02-23 1 27 46](https://user-images.githubusercontent.com/5343634/36578133-abb86748-189e-11e8-96af-e1ce7a3b7e1c.png)

![2018-02-23 11 34 14](https://user-images.githubusercontent.com/5343634/36578142-bb2447ec-189e-11e8-8d76-4ff8e9469f11.png)

페이지 이동을 위해서 아래와 같이 push를 이용하고 있구요. 
![2018-02-23 2 35 57](https://user-images.githubusercontent.com/5343634/36579551-fb4718b0-18a6-11e8-83c5-c38395baeda9.png)

창을 새로 연다던지 캐쉬를 삭제하고 다시 하면 잘 불려지는데, push를 이용해서 다른 url로만 갔다오면 이러네요. 
해결 방법에 대해 조언을 구해봅니다. : )

아..근데, push를 하지 않고, "window.location.href"를 이용하면 이런 문제가 안 생겨요. ;;;

**Comment by daumPostcode** [comment]
@friziek 
안녕하세요~

네;; 음... 저도 리엑트를 몰라서 답변을 드리기 어려운 상황이긴 하네요;;

history.push라는 메소드는 리엑스의 props에 들어가 있는 따로 구현된 객체인것 같긴해요; 기본적으로는 pushState함수가 있는 것으로 알고 있거든요.

즉, 리엑트 다큐먼트를 참고해서 뷰의 상태들이 변경이 되는지 등을 확인해 보셔야 될것 같습니다;;

window.location.href의 경우 페이지 자체를 변경하여 document 객체 자체를 변경시키는데; history API는 그렇진 않는 것으로 알고 있습니다.

제가 모르는 내용이라 답변을 드리기 어려운점 참고 부탁드립니다;;

**Comment by friziek** [comment]
@daumPostcode 
감사합니다~ : )
아무래도 뷰 상태변경을 하면서 다른 곳에 묶여있다던지..할 것 같긴하네요. daumPostcode의 내부에서 render까지 타는 것은 확인이 되거든요. ㅠㅠ 
말씀해주신 부분을 좀 더 봐야겠네요. 

답변 감사드립니다~ : )

**Comment by kimminsik-bernard** [comment]
안녕하세요. (아마도) 사용하고 계신것으로 예상되는 `react-daum-postcode` wraper 의 개발자입니다.

**Comment by friziek** [comment]
@kimminsik-bernard 
안녕하세요~
업데이트하고 나니 잘 되네요. 감사합니다~ : )

**Comment by daumPostcode** [comment]
@kimminsik-bernard 
오오오!! 개발자님 안녕하세요~
react wrapper를 개발해주시고 답변도 달아주셔서 감사드립니다 ^^ 

@friziek 
잘 해결되서 다행이네요 ㅎㅎ
우편번호서비스에 대한 문의가 있으시면 언제든 답변주세요~ 감사합니다.
