### ISSUE TITLE
검색되지 않는 주소가 있어 문의 드립니다.

### ISSUE THREAD

**Issue by manner4na2** [daumPostcode/QnA#283]
안녕하세요.
검색되지 않는 주소가 있어 문의 드립니다.

행자부 주소시스템에는 검색이 되나 API호출시 호출이 안되는 주소가 있어 확인 요청 드립니다.

주소: 봉은사로 461

1. 구주소 삼성동 45-9 검색 시 응답값

{
  "meta": {
    "same_name": {
      "region": [],
      "keyword": "삼성동 45-9",
      "selected_region": ""
    },
    "pageable_count": 0,
    "total_count": 0,
    "is_end": true
  },
  "documents": []
}

2. 신주소 봉은사로 461 검색 시 응답값

{
  "meta": {
    "same_name": {
      "region": [],
      "keyword": "",
      "selected_region": "서울 강남구 봉은사로"
    },
    "pageable_count": 0,
    "total_count": 0,
    "is_end": true
  },
  "documents": []
}

확인 부탁 드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@manner4na2 
네~ 안녕하세요~
해당  API는 https://developers.kakao.com/docs/restapi/local#%EC%A3%BC%EC%86%8C-%EA%B2%80%EC%83%89

여기에 있는 REST API로 보이는데요;

먼저 이 이슈 게시판은 http://postcode.map.daum.net/guide 에 있는 우편번호서비스JS API에 해당하는 문의만 답변을 드릴 수가 있습니다. (해당 API는 개발주체도 다르고 부서도 달라서요;; 일단 제가 모르는 분야라서요..)

해당 이슈에 대해서는 https://devtalk.kakao.com/
여기에 문의를 남겨주시는게 좋을 것 같습니다.

**Comment by daumPostcode** [comment]
@manner4na2 

https://developers.kakao.com/docs/restapi/local#%EC%A3%BC%EC%86%8C-%EA%B2%80%EC%83%89
여기에 있는 예제 코드로 curl로 확인해 보니; 말씀하신 주소가 정상적으로 출력이 됩니다.
일단 담당자분께 말씀은 드리겠지만, 트래픽 제한이 걸렸거나 API key가 잘못됬는지 확인 부탁드립니다.

제가 드릴 수 있는 답변은 여기까지라 https://devtalk.kakao.com/ <- 여기에 질문을 올리시는게 더 좋아보입니다.
