### ISSUE TITLE
placeholder 문구 변경이 가능한가요?

### ISSUE THREAD

**Issue by sohat** [daumPostcode/QnA#284]
제공되는 props 에서 placeholder  문구를 변경하는 부분이 보이질 않는데 제가 혹시 있는 데 못찾은 걸까요??

아래의 스크린샷과 같이 span 으로 삽입되어 있는 문구가 수정 가능한지 문의 드립니다.

![image](https://user-images.githubusercontent.com/19400518/36702854-35f93ca2-1b9c-11e8-89ca-f6c6964a9004.png)

**Comment by daumPostcode** [comment]
@sohat 
네~ 안녕하세요~

말씀하신 기능은 현재 지원하고 있지 않습니다.
해당 플레이스 홀더는 저희서비스를 이용할때 검색이 제일 잘되는 방식을 가이드 하고 있는 것이라, 아직 수정을 할 수 있는 기능을 추가할 계획은 없는 점 참고부탁드립니다.
