### ISSUE TITLE
검색시 응답 항목 관련

### ISSUE THREAD

**Issue by SkyHigh113** [daumPostcode/QnA#285]
마산 으로 질의를 하면 

postcode: "631-871" , postcode1: "631" , postcode2: "871" , postcodeSeq: "001" , zonecode: "51751"
address: "경남 창원시 마산합포구 가포로 1"
addressEnglish: "1, Gapo-ro, Masanhappo-gu, Changwon-si, Gyeongsangnam-do, Korea"
addressType: "R" , bcode: "4812515800" , bname: "해운동" , bname1: "" , bname2: "해운동"
sido: "경남" , sigungu: "창원시 마산합포구" , sigunguCode: "48125", userLanguageType: "K"
query: "마산", buildingName: "대경상가", buildingCode: "4812515800100050038046442"
apartment: "N" ,jibunAddress: "경남 창원시 마산합포구 해운동 5-37"
jibunAddressEnglish: "5-37, Haeun-dong, Masanhappo-gu, Changwon-si, Gyeongsangnam-do, Korea"
roadAddress: "경남 창원시 마산합포구 가포로 1"
roadAddressEnglish: "1, Gapo-ro, Masanhappo-gu, Changwon-si, Gyeongsangnam-do, Korea"
autoRoadAddress: "" ,autoRoadAddressEnglish: "" ,autoJibunAddress: "" ,autoJibunAddressEnglish: ""
userSelectedType: "J" , hname: "" , roadnameCode: "3329001" , roadname: "가포로"

로 결과를 받습니다.
경남이면 경상남도 
전남이면 전라남도 

위와 같은 처리는 개발자가 직접 수정해야하는 건가요?
추가로 만약에 DB로 있다면 그 DB를 받을 수 있을 까요?

**Comment by daumPostcode** [comment]
@SkyHigh113 
네~ 안녕하세요~

저희 우편번호서비스의 공식 가이드 문서를 참고해 주시기 바랍니다
[공식 가이드 생성자 속성](https://spi.maps.daum.net/postcode/guidessl#attributes)

이 문서의 속성 부분을 살펴보시면 생성자 옵션으로 shorthand라는 옵션이 있으며 기본값이 true입니다.
그래서 경상남도가 경남으로 표시가 되는 것이며, 이를 false로 하면 경상남도라는 풀네임으로 표시됩니다.

제약사항도 있으니 한번 읽어보시는게 좋을 것 같습니다.

감사합니다.
