### ISSUE TITLE
주소 검색 결과 클릭시 history.length 증가

### ISSUE THREAD

**Issue by HeyKJ** [daumPostcode/QnA#286]
안녕하세요
현재 iframe을 이용하여 레이어 띄우기를 사용하고 있는데
주소를 검색한 후 검색된 결과를 클릭하여 받아온 주소 정보를 input 태그에 넣고 있습니다 
여기까진 무난한데 문제는 검색된 결과를 클릭하면 history.length 개수가 증가하여 
뒤로가기나 location.replace를 사용하는데 어려움을 겪고 있습니다
제가 수정할 수 있는 방법이 있을까요?

**Comment by daumPostcode** [comment]
@HeyKJ 
네~ 안녕하세요~

음. 말씀해 주신 history 가 쌓이는 문제는 iframe내부에서 검색시마다 form.submit을 통해 페이지를 새로 부르기 때문입니다. 현재 해당 이슈의 경우 쉽게 해결이 될지 확인이 좀 필요합니다. 

현재 딱히 해결방법이 떠오르진 않는데; 좀 더 찾아보도록 하겠습니다.. 시간이 좀 걸릴 것 같아요;;

**Comment by daumPostcode** [comment]
@HeyKJ 
안녕하세요~

해당 현상에 대해서 좀 알아보니;
현재의 form.submit을 통해 페이지를 redirect시키는 방법 자체를 변경시켜야 되는 작업이라. 시간이 좀 많이 소요될것 같습니다. 
비동기 처리 or location.replace를 통해 페이지를 변경해야하는데(팝업모드와 레이어 모드에 따라 다르게 가야되는지 정책결정 필요), 개발보다 테스트가 좀 걸릴 것 같아, 미리 공유 드립니다. 

완료일정의 경우 확답드릴 수는 없으며, 버그가 아니기 때문에 긴급패치는 하진 않고, 일정 확인 후에 작업에 들어 갈 것 같습니다. 

완료가 되면 댓글 드리도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@HeyKJ 
중간 결과 말씀드립니다.
현재 말씀해주신 내용에 해당하는 기능을 개발중이며, 옵션 추가로 개발을 진행하고 있습니다.

생성자의 옵션에 설정하는 방식이며, 현재 기능개발은 거의 완료되었으며 테스트 중입니다.
다음주 중에 배포가 가능할 것으로 보이며, 옵션은 이 이슈의 댓글로 말씀드리도록 하겠습니다.

현재 바꾼 방식의 모든 브라우저, 모든 모바일 단말의 브라우저 및 웹뷰에 대한 테스트가 현실적으로 어렵기 때문에,
대표 케이스에만 테스트를 진행하며, 이용하시다가 문제가 있으시면 문제가 발생하는 단말기 정보와 브라우저 정보를 알려주시면 추가 확인하도록 하겠습니다.

감사합니다.

**Comment by HeyKJ** [comment]
수고가 많으십니다
정말 기쁜소식이네요!

**Comment by daumPostcode** [comment]
@HeyKJ 
안녕하세요~

배포시스템에 문제가 있어 배포가 좀 늦어졌네요. 죄송합니다.

말씀하신 기능 추가되어 배포되었습니다.
해당 옵션은 가이드페이지에 공개하지 않을 예정이며, 요청하신 분들에게만 제공할 계획입니다.

생성자의 옵션으로 
submitMode : false

설정시, form submit을 사용하지 않는 모드로 변경이 되며, 그럼 문의 주신 크롬의 iframe내 페이지 이동시 부모페이지의 history에 영향을 주는 문제가 해결되실 거에요.

한번 확인해 보시고 말씀해 주시면 감사하겠습니다.

그럼 즐거운 하루 보내세요~

**Comment by HeyKJ** [comment]
확인해보았는데 정상 작동하네요!
정말 감사합니다 <3

**Comment by Eunsu-Joo** [comment]
감사합니다 덕분에 같은 문제 쉽게 해결했습니다!!! 🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by leedabin** [comment]
감사합니다. [react-daum-postcode](https://github.com/kmsbernard/react-daum-postcode)에서도 submitMode={false}로 해결 했습니다.

**Comment by gkongs** [comment]
감사합니다. 덕분에 해당 문제 쉽게 해결 하였습니다.

**Comment by dohyung4934** [comment]
감사합니다~

**Comment by ryu9663** [comment]
감사합니다!
