### ISSUE TITLE
검색결과가 없을때 tip 제거 문의

### ISSUE THREAD

**Issue by neoamuro** [daumPostcode/QnA#287]
![image](https://user-images.githubusercontent.com/10465358/37272283-8b2075f6-2619-11e8-82bb-06d5b5a18e1b.png)

위와 같이 검색결과가 없을때 자동으로 tip이 나오면서 다음 지도에서 검색하기가 나오는데... 이거 없앨 수 있는 방법이 있을까요?

앱에 임베디드 해서 쓰는데 아이폰에서 **다음 지도에서 검색하기** 누르면 뒤로 갈수가 없어서 그렇습니다;;;
하이브리드형태라 뒤로가기 버튼 만들기도 애매하고 문제가 있네요;;;

**Comment by daumPostcode** [comment]
@neoamuro 
네~ 안녕하세요.

현재로써는 해당링크를 제거하는 기능은 없습니다.
다만 hideMapBtn 이라는 옵션으로 검색결과에서의 "지도"버튼을 제거하는 옵션이 있는데, 해당 옵션 활성화시 팁에 있는 링크도 제거되도록 수정 배포를 하도록 하겠습니다.
수정 배포에 시간이 좀 소요가 되고, 바로 아래 CS와 같이 나갈 수도 있는데요;;

우선은 앱이라면, 웹뷰에서 링크클릭시 랜딩페이지를 확인해서(또는 확인을 안해도 됩니다) 이동을 막을 수 있으니 한번 확인해 주시기 바랍니다.

감사합니다.

**Comment by neoamuro** [comment]
아... 정말 감사합니다~~~~~~~
배포본 기다리겠습니다 ㅠㅠ;

**Comment by daumPostcode** [comment]
@neoamuro 
안녕하세요~ 중간 결과 공유드립니다.

현재 해당 기능은 개발이 완료되었습니다.

해당 기능 배포는 바로 아래에 있는 검색모드 변경기능과 같이 배포가 될 예정으로 다음주 초정도 예상하고 있습니다.

잠시만 기다려 주시면 감사하겠습니다.

**Comment by neoamuro** [comment]
아.. 빠른 개발 감사드립니다~~!!
그냥 혹시나 하고 여쭤본건데... 이렇게 대응을 잘 해주시니까 너무 고맙네요 ㅠㅠ;

**Comment by daumPostcode** [comment]
@neoamuro 
안녕하세요~
답변이 늦어 죄송합니다.

배포시스템에 문제가 생겨서 좀 늦어졌네요.

현재 말씀하신 기능 추가되어 배포되었습니다.
가이드 페이지에 설명이 되어 있는데요
"hideMapBtn" 옵션을 true로 설정하면 검색 결과가 없는 페이지의 지도 이동 링크도 제거 됩니다.

추후에 궁금하신 사항 있으면 언제든 이슈 부탁드려요~

좋은 하루 보내세요~

**Comment by neoamuro** [comment]
정말 감사 드립니다~~~~~~~~~~~~~~~~~~~~ㅜㅜ
