### ISSUE TITLE
행자부 도로명주소 사이트에는 등록이 되어있는데 조회가 안됩니다. 

### ISSUE THREAD

**Issue by crash1230** [daumPostcode/QnA#288]
제주시 조천읍 선흘리 2239
위 주소가 행자부 사이트에서는 조회가 되는데 다음 우편번호찾기에서 조회가 안됩니다.
확인 부탁합니다.

**Comment by daumPostcode** [comment]
@crash1230 
네~ 안녕하세요~

답변이 늦어져서 죄송합니다.

해당 주소를 주소 담당자분께 여쭤보니;
요 몇일간 주소 연동이 알수없는 오류로 인해 멈춰있었다고 합니다;; 먼저 불편을 드려 죄송하구요. 
현재 연동되도록 조치하였으니 저녁쯤에 반영이 될꺼라고 하시네요.

불편을 드려 죄송합니다.

다음에도 데이터상 문제가 있으면 언제든지 이슈 부탁드립니다. 감사합니다.
