### ISSUE TITLE
다음 우편 번호 서비스 API를 이용할 때, 안드로이드 4.4.2에서 WebView를 불러올 때의 Error

### ISSUE THREAD

**Issue by behindname** [daumPostcode/QnA#29]
Daum 우편번호 서비스의 자바 스크립트를 이용해서
우편번호 검색이 가능하도록 Dialog를 만들었습니다 - 

WebView에서 loadUrl을 실행해 js를 실행하도록 했는데요 - 
다 잘 되는데 KITKAT에서만 잘 안 되네요...
KITKAT에서 WebView를 불러오는데 문제가 있다는 소리가 좀 들리긴 하는데요, 
해결책이 잘 검색되지 않습니다. 
혹시 해결책이 있다면 알려주셨으면 합니다 - 

---

webView.loadUrl("javascript:execDaumPostcode();");

자바스크립트는 iframe이용하는 걸 사용했습니다 - 
왜 KITKAT만 안 될까요...?
이 코드에 해당하는 Err 메세지는 아래와 같습니다 - 
일단 chromium WebView자체에 문제가 있는 것 같고, 
## 그래서 loadUrl로 js쿼리를 실행하는데 계속 에러가 뜨네요...

W/AwContents: nativeOnDraw failed; clearing to background color.
W/AwContents: nativeOnDraw failed; clearing to background color.
I/chromium: [INFO:simple_index_file.cc(397)] Simple Cache Index is being restored from disk.
I/chromium: [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
I/chromium: [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
V/FA: Inactivity, disconnecting from AppMeasurementService
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'document' of null", source: https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1471501634021/160818.js (1)
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'document' of null", source: https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1471501634021/160818.js (1)
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'document' of null", source: https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1471501634021/160818.js (1)
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'document' of null", source: https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1471501634021/160818.js (1)
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'document' of null", source: https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1471501634021/160818.js (1)
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'document' of null", source: https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1471501634021/160818.js (1)

**Comment by daumPostcode** [comment]
@behindname 
네~ 안녕하세요~ 답변이 늦어 죄송합니다;;

우선 저희 서비스를 앱내에서 웹뷰를 이용하여 이용함에 따른 발생하는 이슈에 대해서는 100% 대응을 해드릴 수 없는 점 알려드립니다.(웹뷰는 커스터마이징을 어떻게 하느냐에 따라 너무 달라;; 현재 1:1 대응은 불가능합니다)

일단 현재까지 4.4.2 킷켓에서 사용할때 오류가 발생한다는 제보는 없는 상태입니다.(웹브라우저, 웹뷰 포함)

적어주신 오류메세지를 통해 알 수 있는 것은 160818.js파일이 실제 저희 우편번호 서비스가 실행되는 core스크립트 인데요.  해당 오류는 document객체를 가져오는 iframeNode.contentWindow 객체가 null이라는 것입니다.

이는 저희 서비스가 삽입되는 DOM노드가 DIV-iframe(1)-iframe(2) 인데, 이중 첫번째 iframe(1)이 생성이 안됬거나, DIV안에 삽입이 안됬을때 발생하는 것인데요. 일단 이 iframe(1)이 정상적으로 생성이 되는지 확인 부탁드립니다.

간단히 테스트를 하시려면, div태그를 하나 만들어서 삽입을 하고, iframe태그를 하나 만들고 여기에 src를 "about:blank"로 해주신 후에, div의 child로 iframe을 삽입해 주세요. 그리고 iframe객체를 가져와 contentWindow가 있는지 확인해 보시면 되실 것 같아요. 

일단 설명은 웹브라우저에서 태그 생성하는 방법으로 말씀드렸지만, 실제 @behindname 님께서 만드신 웹뷰에 맞게 테스트 하시면 될 듯합니다.(웹뷰는 저도 잘 몰라서;;)

이후 추가적인 이슈가 발생하면 댓글 주세요~ (지금 글처럼 스크립트내에서 발생하는 오류메세지를 적어주시면 제가 파악하기가 좀 더 수월합니다.)

**Comment by zeallat** [comment]
webView.getSettings().setDomStorageEnabled(true);
추가하시면됩니다.

**Comment by daumPostcode** [comment]
@behindname 
참고해주세요~

@zeallat 
감사합니다 ^^
