### ISSUE TITLE
영문 주소 검색

### ISSUE THREAD

**Issue by myf0691** [daumPostcode/QnA#290]
영문 주소 결과를 볼 수 있는데 검색은 안되나요?

**Comment by daumPostcode** [comment]
@myf0691 
네~ 안녕하세요~

네 현재 영문주소의 경우에는 한국어로 검색한 후 보기 기능과 데이터로 내리는 것 까진 제공하나,
영문 자체의 검색은 지원하지 않습니다.

감사합니다.
