### ISSUE TITLE
최신 데이터 미반영

### ISSUE THREAD

**Issue by devflow** [daumPostcode/QnA#291]
# 문제
관련조례:

[충북 단양군 리의 명칭 과 구역에 관한 조례 (시행 : 18. 3.1 )](http://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=62167)

검색예:
```
단양군 매포읍 응실리 => 검색불가
단양군 매포읍 응실길 99 => 지번이 조례 개정전인 '어의곡리'로 검색됨
```

최신의 데이터를 행정안전부에서 받는다고하였는데, 받는주기가 따로있는지, 시행일이 꽤 되었음에도 반영이 왜 안됐는지 알고싶습니다.

그렇다면 주소 검색뿐만아니고 행정코드, 법정코드에도 실제 시행중인 조례코드와는 다를 수 있으려나요?

**Comment by daumPostcode** [comment]
@devflow 
네~ 안녕하세요

주소 데이터 담당자 분께 문의 전달하였으며 각 케이스별로 달라서 확인이 필요하다고 하시네요. 
회신이 오면 추가 답변 드리도록 하겠습니다.

일단 주소 데이터와, 행정구역의 업데이트가 같진 않습니다. 그리고 각 행정구역의 업데이트는 지자체와 저희와 받는 데이터 시점에 따라 좀 다르게 작업이 되며, 이때도 여러가지 예외사항이 있어, 바로 적용되는 곳이 있는가 하면 좀 시간이 있는 곳도 있는 것으로 알고 있습니다.
자세한 사항은 담당자 분께 회신이 오는대로 답변을 드리도록 할께요.

잠시만 기다려 주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@devflow 

안녕하세요~

답변이 늦어져서 죄송합니다.
주소 데이터 담당자분께 오늘 답변을 받았는데요.

보통 행정구역 정보는 변동후에 일주일 이내로 저희쪽 시스템에 반영이 되는데,
이번에는 다른 대량 작업때문에 밀려 있어서 그렇다고 합니다. 저희쪽 반영 이슈이며, 해당 행정구역은 이번주에 업데이트가 될 예정이라고 하네요.

불편을 드려 죄송합니다.

**Comment by devflow** [comment]
@daumPostcode 

아직도 반영이 안돼있네요.

**Comment by daumPostcode** [comment]
@devflow 
네; 먼저 불편을 드려 죄송합니다;

주소데이터를 관리하는 부서 담당자 분께 여쭤보니; 말씀하신 지역의 업데이트가 4월달 반영분까지 포함하여 어제 업데이트가 되었다고 합니다.

그래서 현재 map.daum.net에서는 정상적으로 적용이 되었는데요. 문제는 현재 말씀하신
"단양군 매포읍 응실길 99" 이 주소를 포함한 몇몇 주소의 이전 행정구역이 소각이 되어야 되는데 안된 문제가 있고(지번 주소가 2개가 나오고 있을 거에요;),

다음지도에서의 주소섹션에서는 검색이 되나 저희 우편번호서비스에서는 검색자체가 안되는 문제가 있는데, 이는 검색엔진 부분까지 확인을 해봐야 될것 같습니다;;

불편을 드려 죄송합니다. 조속히 해당 부서에 문의하여 해결하도록 하겠습니다.

**Comment by daumPostcode** [comment]
@devflow 
안녕하세요~

금일 말씀하신 주소의 검색결과가 정상적으로 표출이 되도록 수정되었습니다.
해당 주소의 경우 데이터 처리와 다른 업데이트 일정과 맞물려 원래 일정보다 늦게 반영이 되었는데요.
이부분에 대해서 죄송하게 생각합니다.

실제 조례 개정과 데이터 수급에서 차이가 있어서 이런일이 종종 발생하는데요; 앞으로 이 딜레이를 줄이기 위해 최선을 다하겠습니다.

문의 주신 주소 한번 확인 부탁드립니다. 감사합니다.

**Comment by devflow** [comment]
@daumPostcode 

감사합니다.
