### ISSUE TITLE
주소검색시

### ISSUE THREAD

**Issue by hysook502** [daumPostcode/QnA#292]
우편번호 주소검색시
'광주광역시' 주소가 '광주'로 표기되어  경기도 광주와 혼돈됩니다.
주소표기시 '광주'를 '광주광역시'로 수정하여 주십시오.

**Comment by hysook502** [comment]
우편번호 주소검색시
'광주광역시' 주소가 '광주'로 표기되어 경기도 광주와 혼돈됩니다.
주소표기시 '광주'를 '광주광역시'로 수정하여 주십시오.

**Comment by daumPostcode** [comment]
@hysook502 
안녕하세요~

해당 기능은 생성자 옵션에서 shorthand: false  로 설정해 주시면, 전체 이름으로 표기를 바꿉니다.
해당 기능을 이용하시면 될것 같아요~

자세한 사항은 가이드 문서 참고해주세요~
