### ISSUE TITLE
팝업 차단 관련

### ISSUE THREAD

**Issue by ksbgenius** [daumPostcode/QnA#293]
프런트는 Vue를 사용중입니다.

페이지가 처음 로딩된 이후에

버튼 클릭으로 팝업을 띄우는데

첫번째 클릭하면

팝업이 차단되고

그 상태에서 다시 버튼을 클릭하면

정상적으로 팝업을 띄우기는 하는데

저만 그러는 것인지....

이건 크롬에서..
![default](https://user-images.githubusercontent.com/26054754/37814304-a194cf80-2eac-11e8-8ee1-bfc7b89a2397.png)

이건 파이어폭스에서..
![default](https://user-images.githubusercontent.com/26054754/37814319-b0a31afe-2eac-11e8-9c07-9e871239cb58.png)

감사합니다.

**Comment by daumPostcode** [comment]
@ksbgenius 
네~ 안녕하세요~

해당 현상은 var p = window.open 함수를 실행하여 객체를 가지고 오게 되는데, 이때 파이어폭스에서 
이때 p에 null 값이 바인딩 되어 발생하는 문제입니다.

팝업 차단 설정이 활성화 되면서 해당 객체의 값을 open 함수가 리턴을 안하는 경우일 수 있어,
팝업 차단 메세지가 뜰때,  open함수의 리턴값을 가지고 오지 못할 경우, alert창을 띄워서 이후 프로세스를 막을려고 합니다.
팝업이 차단되면, 아예 안뜨는게 정상일 것인데, 두번째 클릭시엔 뜨는 것은 또 이상하네요;;

아무튼 오류가 발생하지 않고, 이용자가 인지할 수 있게 경고 창을 띄우는 방향으로 패치를 하도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@ksbgenius 
금일 13시 15분. JS API 버전 180326버전으로 해당 오류메세지가 뜨지 않고, 사용자에게 알림을 줄 수 있도록 수정되어 배포 되었습니다.

즉, 브라우저의 팝업창 제한 기능이 활성화 되어 있어서, 객체를 받아오지 못할 경우에는, 이후 처리가 불가능 하기 때문에 alert창을 띄워 사용자가 인지할 수 있도록 하였으며, 이후에 팝업 제한이 해제되거나, 한번 더 클릭시에는 기존과 동일하게 팝업이 뜨도록 처리되었습니다.

확인 부탁드립니다.~
