### ISSUE TITLE
explorer 오류 문의

### ISSUE THREAD

**Issue by imyoon** [daumPostcode/QnA#294]
iframe 형식 사용하고있고 크롬은 이상없는데 explorer에서
주소 변경하고 체크박스 변경하면
input text창이 비활성화됩니다

**Comment by daumPostcode** [comment]
@imyoon 
안녕하세요~

말씀해 주신 내용으로는 조건이 너무 광범위 하여 재현을 하기가 불가능합니다.

OS 버전, IE 버전, 재현되는 사이트 등의 정보가 필요합니다. 스크린샷도 추가해 주시면 좋습니다.
저희 서비스의 영역의 오류인지, 저희 api를 이용하는 사이트의 오류인지도 확인이 필요하기 때문에 좀 더 많은 정보를 주시면 좋겠습니다;
