### ISSUE TITLE
주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by SeungWonHa** [daumPostcode/QnA#297]
http://map.daum.net/에서 원당리 373-3을 검색하면 지역을 찾을 수 있습니다.
우편번호 api를 사용하면 검색이 되지 않습니다.
행정자치부에서 검색이 되지 않으면 안된다고 QA에서 확인했는데요

http://map.daum.net/ => 여기는 검색이 되는데
우편번호 api는 검색이 되지 못한 이유가 궁금합니다.

**Comment by daumPostcode** [comment]
@SeungWonHa 
네~ 안녕하세요~

그 이유는, 우편번호 서비스는 도로명 주소 검색 시스템이며, 기반되는 데이터가 juso.go.kr 에서 검색되는 도로명 주소를 기반으로 하기 때문입니다.

말씀하신 "원당리 373-3"의 경우 map.daum.net에서 검색을 했을때 모두 구 우편번호로 검색이 됩니다. 즉 지번만 있고, 5자리 새 우편번호가 할당된 도로명 주소는 없다는 것이죠. 이걸 확인해 볼 수 있는 것은 http://juso.go.kr 행자부 도로명 검색 시스템에서 해당 주소를 검색해 보시면 검색이 되지 않는 것을 확인하실 수 있습니다.
검색되지 않는 주소의 등록은 등록을 원하시는 분께서 행자부에 직접 고객센터를 통해 요청하셔야 하며, 행자부에 반영이 되면 저희측에도 반영이 됩니다.
다만 행자부에서 검색이 되도 저희쪽에선 검색이 안되는 주소가 있는데; 
해당 사항은 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)을 참고해 주세요.

일단 말씀하신 주소는 도로명 주소가 발급되지 않은 주소라 저희 시스템에서는 검색이 되지 않습니다.

확인 부탁드려요~
