### ISSUE TITLE
마이너 업데이트라도 업데이트 내역을 적어주셨으면 합니다.

### ISSUE THREAD

**Issue by devellany** [daumPostcode/QnA#298]
안녕하세요,
다음 우편번호 서비스를 쓰고 있어 꾸준히 QnA를 모니터링하고 있는 개발자입니다.

약 2주 전에 팝업창 관련 마이너 업데이트를 하셨는데요. [링크](https://github.com/daumPostcode/QnA/issues/293)
저희 같은 경우 이전부터 팝업을 띄우기 위해 다음과 같은 코드를 쓰고 있었습니다.

```javascript
daum.postcode.load(function () {
    try {
        new daum.Postcode({
            oncomplete: function () {}
        }).open({
        });
    } catch (e) {
        alert("메세지");
    }
});
```

제대로된 쓰임새는 아니었지만, try catch로 팝업을 처리하고 있었는데,
지난 업데이트로 불필요한 코드가 되었습니다.
2주 지난 시점에서 기획 측에서는 팝업 문구가 변경된 것을 눈치 못 챈 것으로 보이나,
개발자 입장에서는 불필요해진 코드를 제거해야만 하겠죠.

저희는 별도로 라이브러리 형식으로 구축하여 수정 사항이 얼마 되지 않는 부분이지만,
이와 같은 마이너한 부분을 QnA에 올리지 않고 자체적으로 처리하고 있는 개발자들이 있을겁니다.

'자체적으로 문제 해결을 위해 작성한 코드가 관련된 마이너 업데이트로 인하여
 **무조건** 충돌나지 않을 것이다'는 가정을 세우기는 힘들거 같고요.
마이너 업데이트일지라도 업데이트 내역은 별도로 적어주셨으면 합니다.

감사합니다.

**Comment by daumPostcode** [comment]
@devellany 
네~ 안녕하세요~

넵; 따끔한 충고 감사드립니다. 실무 환경에서 저희 API를 가지고 이용하시는 분들에 대한 고민이 부족했던 것 같습니다.
앞으로는 업데이트가 되는 사항이 있을 경우, 대다수의 개발자 분들에게 오픈이 필요한 경우엔 업데이트 소식에 적겠으며,  현재 이미 업데이트가 된 사항도 정리하여 올려두도록 하겠습니다.

조언 감사드립니다.

**Comment by daumPostcode** [comment]
@devellany 

말씀하신 내용을 토대로,
지난 배포된 버전까지 버그 픽스 및 추가된 기능들 정리하여 적어 두었습니다. 대부분 큰 업데이트가 아닌 마이너 업데이트라 소홀했던 것 같아요.
앞으로는 변경된 사항이 있으면 해당 md 파일에 계속 추가해 놓도록 하겠습니다.

감사합니다.

[업데이트 소식 페이지](https://github.com/daumPostcode/QnA/blob/master/PATCHNOTE.md)
