### ISSUE TITLE
현재 검색이 되지 않고 있습니다.

### ISSUE THREAD

**Issue by 76069884** [daumPostcode/QnA#299]
샘플페이지도 되지 않는 것으로 보아 서버점검으로 보이는데 빠른 확인 부탁드리겠습니다.

**Comment by Terrorboy** [comment]
저두요
[code]
The SSL certificate used to load resources from https://suggest-bar.daum.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
[/code]

**Comment by aaboo** [comment]
저두요. 이거 빨리 잡아주셔야 할 듯 싶네요

**Comment by eunsoo88kim** [comment]
살려주세요

**Comment by 76069884** [comment]
카카오톡으로 확인결과 검색엔진에 문제가 생겨 조치중이라고 하네요...

**Comment by Terrorboy** [comment]
@76069884 확인감사합니다.!

**Comment by 76069884** [comment]
@Terrorboy 현재 검색이 되고 있는바 해결이 되었을 듯 보입니다.
아니면 작업중에 일시적으로 열어주셨을지도..../먼산

**Comment by Terrorboy** [comment]
@76069884 검색이 됬다 안됬다 하는걸 보니 수정 중인듯 합니다 ㅠ.ㅠ

**Comment by daumPostcode** [comment]
@76069884 @Terrorboy @aaboo @eunsoo88kim 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ

**Comment by 76069884** [comment]
해당 이슈가 완료된 것으로 확인되어 닫습니다.

**Comment by Terrorboy** [comment]
@daumPostcode 수고하셨습니다.
