### ISSUE TITLE
도로명 주소 검색이 안됩니다. 확인 부탁드려요.

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#3]
경기도 고양시 일산서구 탄현동 121번지로 
검색을 하면, 

도로명주소 시스템에는 
1. 경기도 고양시 일산서구 일현로 140(탄현동, 큰마을대림아파트)
2. 경기도 고양시 일산서구 일현로 140(탄현동, 큰마을현대아파트)
3. 경기도 고양시 일산서구 일현로 140(탄현동)

세 가지가 검색이 되는데
다음과 연결된 저희 시스템에는 1,2번만 검색이 되고 3번은 보이지 않습니다.
추가 부탁드려요^^

**Comment by daumPostcode** [comment]
@dysong1 
네 안녕하세요~
** 경기도 고양시 일산서구 일현로 140** 해당 주소의 경우, 행자부 사이트에서는 "큰마을대림아파트","큰마을현대아파트"만 공동주택이라고 판단하여 법령에 따라(기본+추가적인 표기방식) 도로명 주소 오른쪽에 추가정보로 건물명이 들어가 있는 건데요. 

현재 저희 시스템의 경우, 도로명주소로 검색했을때 옆에 붙는 건물명은, 해당 도로명 주소에 매핑되어 있는 모든 건물을 표시해 주는 것입니다. 즉, 행자부처럼 공동주택 유무에 따라 건물명을 써주거나 하는 건 아닙니다
예로 "왕산로 214"로 검색하면 행자부에서는 도로명 주소부분에 아무런 건물명이 없지만, 저희쪽에는 모두 있는 것을 확인 하실 수 있습니다.

그래서 현재 말씀해 주신 일현로 140의 경우에는 행자부사이트에서 지번쪽을 보시면 모두 건물명이 매핑되어 있어 저희쪽에서 모든 주소에 각각 표시가 되어 있는 것인데요. 

현재 행자부 방식과 같이 공동주택의 경우에만 (동, 주택명)을 표기하는 것은 현재 저희 검색팝업의 UI, 데이터 관리적인 측면에서 바로 변경하기는 어렵습니다. 특히나 저희 서비스는 주소만 검색하고 끝나는게 아니라 해당 주소를 내려받아 실제 이용하는 사이트에서 사용하는 것을 목적으로 하기 때문에, 검색화면에 보여줄 수 있는 최대한의 정보를 표시하려고 했고, 주소 조합방식은 [가이드 페이지 첫번째 예제](http://postcode.map.daum.net/guide#sample)를 참고하시면 됩니다.

다만, 모든 정보를 표시하다보니, 오히려 건물명 때문에 이용자분들의 선택이 어려움을 줄 수도 있는 점이 있는 것 같아, 
건물명이 없는 순수 주소만 한번 더 나오도록 하는 방식 등으로 다음 업데이트에 반영해 보도록 하겠습니다.
