### ISSUE TITLE
카톡(모바일)에서 전달한 경로일 경우 우편번호 창이 뜨지 않음

### ISSUE THREAD

**Issue by bm4bw69** [daumPostcode/QnA#30]
PC에선 정상적으로 잘 이용하고 있습니다.
모바일 카톡에서 전달한 경로를 카톡에서 열어 우편번호 검색을 하면 창이 뜨지 않습니다.
피시버전 카톡의 경우엔 문제가 없는걸 보면 카톡 내장 브라우저와의 문제인거 같습니다.
우편번호 창을 띄울 방법이 없을까요..? 

http://smartplus.smartadmin.kr/order/order_form.php?pidx=622&ptype=12&seller=

**Comment by daumPostcode** [comment]
@bm4bw69 네~ 안녕하세요~

혹시 PC에서 open()함수를 이용한 팝업형식을 이용하시나요?

현재 카카오톡 인앱브라우저는 신규 웹뷰로 업데이트가 되기 전까진 팝업형식의 우편번호 서비스는 띄우질 못합니다;;

이 팝업의 문제는 대다수의 웹뷰를 사용한 서비스(ex. facebook)에서도 발생을 하며, 현재 해결책으로는 인앱브라우저 팀에서 새로운 API로 개발을 빨리하여 배포하거나, 저희쪽에서 내부 Node구조를 바꿔야 합니다. 다만 현재로써는 이 둘 모두 진행하기가 어려운 문제가 있어요;;

그래서 해결책으로는 UA를 체크하셔서 모바일에서 열릴 경우에는 embed()를 사용한 레이어모드(또는 본문에 삽입되는 끼워넣기 형식도 포함)로 전환되게끔 수정해 주시면 모바일 브라우저에서도 정상적으로 동작할 거에요;

알려주신 홈페이지를 확인해보니 레이어모드 보단 **검색**버튼을 누르면 그 아래 끼워넣기 방식으로 이용하시는게 좀 더 좋아 보입니다.(레이어 모드는 단말기에 따라서 위치-position 문제가 발생하는데 이부분 처리가 좀 까다롭습니다;)

한번 확인해 보시구 추가 궁금증이 있으시면 댓글 부탁드려요~

**Comment by bm4bw69** [comment]
빠른 답변 감사합니다.. 말씀해주신 방법으로 해결했습니다.
