### ISSUE TITLE
현재 모든 주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by epan0824** [daumPostcode/QnA#301]
안녕하세요.
다음 우편번호 api 를 사용 하고 있습니다.
그런데 현재 (4/10 오전 10시 40분 경) 모든 주소가 검색되지 않고 있습니다.
확인 부탁드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@epan0824 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
