### ISSUE TITLE
주소 검색에서 리스트 데이터가 뜨지 안습니다. 

### ISSUE THREAD

**Issue by lyonghwan** [daumPostcode/QnA#302]
![image](https://user-images.githubusercontent.com/12946007/38531620-b6398496-3cab-11e8-8fef-84b1c0d45f70.png)

**Comment by daumPostcode** [comment]
@lyonghwan 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
