### ISSUE TITLE
모든 주소가 검색이 되지 않습니다.

### ISSUE THREAD

**Issue by yanghodosa** [daumPostcode/QnA#304]
모든 주소가 검색이 되지 않습니다.

빠른 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@yanghodosa 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
