### ISSUE TITLE
다음 우편번호 api 주소검색이 안되고 있습니다.

### ISSUE THREAD

**Issue by pshoon** [daumPostcode/QnA#305]
주소 검색결과가 도로명과 지번주소가 같이 나오는 형식에서 도로명만 나오면서
주소를 클릭하였을 때 없는 주소라고 나옵니다.

빠른 조치 부탁드립니다.

**Comment by daumPostcode** [comment]
@pshoon 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
