### ISSUE TITLE
검색 결과가 없다고 나옵니다.

### ISSUE THREAD

**Issue by mynain** [daumPostcode/QnA#306]
저희 사이트만 그런줄 알았는데 다른분들도 그렇고
공식 사이트인 http://postcode.map.daum.net/guide 에서도 검색결과가 없는걸로 노출되고 있네요.
확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@mynain 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
