### ISSUE TITLE
주소 검색이 안되네요.

### ISSUE THREAD

**Issue by megadeth10** [daumPostcode/QnA#307]
서비스 운영이 안되요. 어서 고쳐주세요.

**Comment by daumPostcode** [comment]
@megadeth10 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
