### ISSUE TITLE
주소검색 불가

### ISSUE THREAD

**Issue by jpsfeel** [daumPostcode/QnA#308]
주소검색이 안되고있습니다.

빠른확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@jpsfeel 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
