### ISSUE TITLE
주소가 전혀 검색되지 않습니다.

### ISSUE THREAD

**Issue by enzy81** [daumPostcode/QnA#309]
예시로 든 주소들 조차도 검색되지 않고 있습니다. 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@enzy81 
안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
