### ISSUE TITLE
조회 되지 않는 주소 확인 요청 드립니다.

### ISSUE THREAD

**Issue by moozabi** [daumPostcode/QnA#31]
경기도 하남시 초일로 78

주소가 우편번호 서비스에서 조회 되지 않습니다.
행정자치부 도로명 사이트에서는 조회가 가능 한데 조회 되지 않는
특별한 이유가 있나요?

**Comment by daumPostcode** [comment]
@moozabi 
네~ 안녕하세요.

불편을 드려 죄송합니다.

해당 주소는 배치작업 중에 일시적인 오류로 인해서 주소가 disable되어 있었네요;; 현재 담당자분께서 원인을 파악 중이며, 말씀하신 주소는 살려두도록 하겠습니다.

다만 DB에서 살려도 검색엔진에 바로 붙는게 아니라서 약간의 시간(30분 내외)이 필요한 점 양해 부탁드립니다.

**Comment by moozabi** [comment]
아직 저리 되지 않았는데 이슈가 종료 처리 되어 다시 확인 요청 드립니다.

**Comment by daumPostcode** [comment]
@moozabi 
네~ 안녕하세요~

먼저 v2서비스에는 반영이 되었습니다.
<img width="407" alt="22" src="https://cloud.githubusercontent.com/assets/20675065/19189178/6e4febe2-8cd1-11e6-82fd-d494457a10ff.png">


그런데 혹시, v1서비스를 이용하시나요?
v1서비스의 경우 현재 저희가 유지보수 하고 있는 v2와는 데이터 체계가 전혀 다릅니다.
v2서비스의 경우 1일 업데이트 행자부 데이터이지만, v1서비스는 1달에 한번 업데이트이며 우정국 데이터를 이용합니다. 이또한 신규 주소의 경우 업데이트 시기에 따라 반영이 매우 느리게 됩니다. 무엇보다 5자리 기초구역번호가 없습니다(6자리 구 우편번호도 같이 없는 경우가 많습니다).

말씀하신 이슈는 질문주신 당일 처리되어 서비스에 반영이 되어서 close를 한건데, v2를 가정하고 질문답변을 하다보니, v1인 경우를 놓쳤네요... 죄송합니다;;
다만 말씀하신 주소의 경우 v1서비스에는 즉각적인 반영이 어려운점을 말씀드리며, 해당 주소의 반영에 대해서는 따로 담당자 분들의 확인이 필요하여 바로 답변을 드리기는 어려울 것 같습니다.

추가적으로 v1서비스는 올해 말 기준으로 더이상 유지 보수에 대한 지원을 하지 않으니, v2서비스로 이관을 부탁드립니다.

**Comment by moozabi** [comment]
v2 사용 중이고 정상 조회 됨을 확인 하였습니다.
검색어를  "초일로 78" 로 조회시에는 검색되지 않아 착각 했습니다.

지원 감사드립니다.
