### ISSUE TITLE
우편번호 검색이 안되네요 빨리 고쳐주세요 

### ISSUE THREAD

**Issue by mywhitedog** [daumPostcode/QnA#311]
상품구매 양식에 우편번호를 입력하려면 꼭 이 서비스를 이용해야지만 칸을 채울 수 있더라고요 
너무 답답합니다 
당장 사야하는데 구매를 못하고 있어요
빨리 고쳐주세요

**Comment by daumPostcode** [comment]
@mywhitedog 

안녕하세요 우편번호 서비스 담당자입니다.

금일 10시 27분 서비스 장애가 발생하였고, 11시 1분에 장애처리가 완료되었습니다.
서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
