### ISSUE TITLE
[장애공지] 서비스 장애에 따른 불편을 드려 죄송합니다.

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#313]
안녕하세요.

우편번호 서비스 담당자 입니다.

먼저, 금일 장애가 발생하여 서비스 이용에 불편을 드려 죄송합니다.

금일 2018년 4월 10일 오전 10시 27분에 검색엔진 장애가 발생하였고,
11시 1분에 장애 복구가 완료되었습니다.

원인은 오전 10시 20분쯤에 주소데이터 배포가 있었는데, 해당 배포본에 문제가 있어서 발생한 오류였습니다.

다시 한번 불편을 드려 죄송합니다.

앞으로도 서비스 이용에 차질이 없게 최선을 다하겠습니다.

감사합니다.

ps) 카카오톡 플러스 친구 대응 하느라 깃허브 이슈에 댓글을 못드린점 죄송합니다.

추가사항 (11시 36분) - 현재 긴급한 서비스 장애는 해결하였지만, 원인 자체가 주소데이터 배포 때문에 발생한 것이라 후속 처리를 진행 중에 있습니다. 만약 검색이 되지 않는 주소가 지속적으로 발생한다면 플러스맵 친구나 깃허브 이슈로 등록해 주시면 감사하겠습니다.

**Comment by webono** [comment]
감사합니다.

**Comment by daumPostcode** [comment]
@moderntasty 
3분전에 확인을 못해봤지만;;; 현재는 검색 잘 되는것 같습니다.

@flanoer 
좋은 말씀 감사드립니다 ^^

**Comment by jaymz9634** [comment]
수고하셨습니다..

**Comment by moderntasty** [comment]
![image](https://user-images.githubusercontent.com/13880615/38533019-51c5e714-3cb2-11e8-834c-c2c6cc87f441.png)
음 이상하네요 아직도 안나오는데..ㅜㅜ

**Comment by daumPostcode** [comment]
@moderntasty 

![2018-04-10 11 33 01](https://user-images.githubusercontent.com/20675065/38533157-f83bb920-3cb2-11e8-9a6c-836497fbbba5.png)
![2018-04-10 11 33 08](https://user-images.githubusercontent.com/20675065/38533161-fbe5f342-3cb2-11e8-91b4-94923a400c90.png)

현재 공식 가이드 페이지에서 검색이 되고 있으며, 혹시 브라우저 캐시를 한번 지워 보실 수 있으실까요??

**Comment by moderntasty** [comment]
@daumPostcode 캐시 지우고 다시하니 되네요 감사합니다!
