### ISSUE TITLE
일부 주소는 아직도 검색되지 않고 있습니다.

### ISSUE THREAD

**Issue by devellany** [daumPostcode/QnA#314]
안녕하세요, 우편번호 서비스 이용중인 개발자입니다.

1 누르고 자동완성에 뜨는
충청북도 청주시 상당구 1순환로 등 일부 주소의 경우 여전히 검색되지 않고 있습니다.

확인 부탁드립니다. 감사합니다.

**Comment by daumPostcode** [comment]
@devellany 

네!

아마 금일 발생한 문제가 주소데이터 배포에 따른 문제여서; 현재 급한 서비스 장애는 해결했지만, 후속조치를 계속 확인중에 있습니다.

해당 주소에 대해서도 한번 더 확인해 보도록 하겠습니다.

**Comment by daumPostcode** [comment]
@devellany 
안녕하세요 현재 다시 확인해보니 해당 주소 공식홈페이지에서는 검색이 되고 있습니다.

![2018-04-10 12 42 30](https://user-images.githubusercontent.com/20675065/38535052-aef2c0f6-3cbc-11e8-9df8-ca92880e85da.png)

혹시 브라우저의 캐시를 한번 지워보시고 확인해 보시겠어요?
