### ISSUE TITLE
https://t1.daumcdn.net 접속 문의

### ISSUE THREAD

**Issue by parkjihoon** [daumPostcode/QnA#315]
안녕하세요 API 이용중 다음 URL 접근시 문제가 발생하여 문의 드립니다.

문제 환경은 win xp /ie6/ie8 버전에서 문제가 발견되었으며 

문제 내용은 https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js 주소에는 
접근이 원활하지만 아래 주소 접근은 문제가 발생하고 있습니다.
https://t1.daumcdn.net/cssjs/postcode/1522037570977/180326.js 

chrome 접속은 양측다 정상적으로 접근되는 것으로 확인 되며
Telnet, fiddler 등의 프로그램으로 확인시에는 200 접속으로 확인되나 

ie 브라우저에서는 서버를 찾을수 없거나 DNS 오류입니다. 라는 에러 내용이 나옵니다.

환경문제로 보여 여러가지 방법을 시도해 보았으나 해결되지 않아 도움을 받을수 있을까 하여

문의 드립니다.

감사합니다.

**Comment by devflow** [comment]
@parkjihoon 

XP에서 IE8의 암호화등급은 128비트로 알고있습니다. 그런데 daumcdn의 SSL 인증서는 256이다보니 오류가 발생하는것같습니다.

아래 참고해보세요.

[t1.daumcdn.net SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=t1.daumcdn.net&s=174.35.5.133&latest)
[List of browsers that support 128-bit and 256-bit encryption](https://knowledge.symantec.com/support/ssl-certificates-support/index?page=content&id=SO12413&pmv=print&actp=PRINT&viewlocale=en_US)

**Comment by parkjihoon** [comment]
답변 감사드립니다.
