### ISSUE TITLE
시군구 코드 값 문의

### ISSUE THREAD

**Issue by drt0927** [daumPostcode/QnA#316]
안녕하세요.
주소 API를 사용하는 사용자입니다.

다름이 아니라 주소 API이용시 sigunguCode 값을 이용해서 프로그램을 만들었습니다.

기존에 도로명코드를 DB에 업로드 하여 사용하고있었는데,
41190 이라는 코드가 추가되어 인식하지 못하는 문제가 발생했습니다.
하여 최근 도로명코드를 업데이트 할 수 있는 사이트나 경로가 있다면 알려주시면 감사하겠습니다.

혹시 sigunguCode를 얻을 수 있는 사이트가 있나요?? (excel, xml, api 등등)

**Comment by daumPostcode** [comment]
@drt0927 
안녕하세요~

데이터 수급과 관련해서는 제가 정확히 알 수 없는 내용이라 답변이 어렵긴 한데요;
해당 코드를 얻을 수 있는 사이트가 있는지는 정확히는 알 수 없으나;
http://www.juso.go.kr/addrlink/main.do 행자부가 제공하는 API를 한번 확인해 보시는 것도 좋을 것 같네요;
데이터도 얻는 링크가 있는것 같으니 한번 확인해 보시는걸 추천드립니다.

저희도 데이터를 행자부에서 받긴 하지만, 정확한 공급 방식은, 주소데이터 담당자분들이 아시는 내용이라;;;; 

정확한 답변을 드리지 못해 죄송합니다;

**Comment by drt0927** [comment]
답변 감사합니다. 참고고 많이 되었습니다.
