### ISSUE TITLE
cross site issue와 ios에서 주소창 실행안됨

### ISSUE THREAD

**Issue by hyjjo123** [daumPostcode/QnA#318]
안녕하세요. 워드프레스를 통해 홈페이지를 만들고 있습니다.
결제 페이지에 postcode.v2.js?ver=2.0.0:1 A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/cssjs/postcode/1522037570977/180326.js, is invoked via document.write.
이런 이슈가 있습니다. 
저는 코스모스 팜 플러그인을 이용하여 다음 우편번호 서비스를 제공받고 있는데요, 아이폰 인스타그램이나 카카오톡의 링크를 통하여 snackingbox.co.kr 로 접속 시 결제 단계에서 주소팝업창 이 뜨지 않습니다.(안드로이드 정상 작동) 주소팝업층이 안되어서 뒷 단계인 결제까지 실행이 안되어 어려움을 겪고 있습니다. 도움을 주실 수 있는 방법이 있다면 알려주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@hyjjo123 
안녕하세요~

일단 기본모드에서의 parser-blocking.... document.write 관련 문제는, 네트워크가 느린 상태에서 document.write를 쓰면 페이지가 블락되서 사용자에게 화면이 로딩안되는 것과 같은 현상을 줄 수 있다는 이슈때문에 가급적 사용하지 말라는 경고인데요. 해당 경고의 경우 우편번호 서비스 스크립트 로딩을 < / body > 바로 위에 배치하거나 하는 방식으로 충분히 회피 가능합니다. 

이 경고를 아예 안뜨게 하는 방법으로는 저희 가이드 페이지의 기본사용법에 동적로딩 부분을 참고하시면 될것 같습니다.

추가로 아이폰의 인스타그램, 카톡의 웹뷰에서 이용하실때, open() 함수를 이용하여 팝업형태로 띄우시나요?
웹뷰의 경우 브라우저의 전체적인 기능을 구현하지 않은 버전이 매우 많습니다. 즉 제일 기본적인 기능만 구현해두고 실제 브라우저가 지원하는 복합적인 기능은 구현을 안한것들이 많아서 발생하는 문제입니다.

해당 모바일웹뷰에서의 팝업이슈는 open을 이용한 팝업모드가 아닌, embed를 이용한 레이어 모드를 추천드립니다.

첫번째로는 레이어팝업 형태로 DIV 랩퍼를 화면 전체로 잡아서 띄우는 방법이 있으며, 또는 레이어 팝업이 아니라 본문 페이지에 삽입을 시키는 방법이 있습니다. 이 삽입을 시키는 방법이 스크롤이 꼬이지 않아 더 안정적입니다.

두번째로는 조금 번거롭지만, 저희 open메소드가 일반적은 방식으로 window.open함수를 호출하는 것이 아니라서 문제가 되는 것이기(PC+mobile 호환성 때문에 어쩔 수가 없었습니다;) 때문에, 팝업은 직접 window.open을 이용해서 hyjjo123님의 페이지를 띄우시고 그 안에서 저희 우편번호 서비스를 embed를 이용해서 화면에 꽉차게 띄운다음에, oncomplete함수에서 데이터를 받으면, 팝업을 직접 띄우신 것이기 때문에 opener객체를 통해 부모페이지로 전달 시키시면 될것 같아요.
즉, 팝업으로 띄우실 페이지에 우편번호 서비스를 embed로 띄우고, 팝업이 데이터를 받으면 opener객체를 이용하여 데이터를 본페이지로 전달 시키는 방법입니다.

한번 확인 부탁드립니다.
