### ISSUE TITLE
행자부 결과랑 다음주소랑 달라요.

### ISSUE THREAD

**Issue by hwaan2** [daumPostcode/QnA#319]
산마루로 46 검색하면 행자부에선 갈매스타힐스로 나오는데 다음에서는 바뀐지오래되었는데 LH 4단지로 나옵니다.
행자부 자료를 다시 업데이트 하는 주기가 긴가요??

**Comment by daumPostcode** [comment]
@hwaan2 
안녕하세요~

데이터 담당자분께 연락이 와서 답변드립니다.
먼저 해당 주소의 건물명이 다른것은 CP사로부터 받는 데이터가 현행화가 안되어 있어서 발생한 문제로 수정되었습니다.

이외에 추가설명을 드리면
행자부측으로 부터 데이터를 받아 1일 업데이트를 하는 것은 맞습니다. 받는 데이터는
http://www.juso.go.kr/addrlink/addrlinkJusoDBUse.do?menu=match
여기에 나와있는 전부라고 보셔도 됩니다.

다만 100%행자부 데이터만 이용하는 것은 아니에요; 해당 도로명 주소 검색 엔진의 경우(저희 서비스 말고 백단) 저희 우편번호 서비스외에도 여러 서비스에서도 쓰이며, 저희가 수급받는 데이터가 행자부 말고도 회사차원에서 인증된 여러 CP사들이 있습니다. 이 CP사들로 부터도 데이터를 받아 특정 규칙에 맞게 처리하여, 저희만의 데이터를 만들게 됩니다.
이러한 데이터를 통해 현재 지도서비스에도 적용되고 다른 REST API로도 나가고 있는 것이죠.

다만 이 모든게 기계적으로 처리가 되므로 간혹 오류가 있을 수 있는데요; 해당 주소가 그런 케이스였다고 보시면 됩니다.

앞으로도 데이터가 다른 문제가 있으면 언제든 이슈 등록 부탁드리며, 데이터 최신화에 최선을 다하겠습니다.

감사합니다.
