### ISSUE TITLE
주소 검색후 나오는 학교명이 다르게 나와요

### ISSUE THREAD

**Issue by raikos0906** [daumPostcode/QnA#32]
안녕하세요

동문대로 50을 검색하면 리스트 제일 처음에 동강여자중학교라고 나오는데요

고객문의에 의하면 동강여자중학교가 아니고 동신여자중학교라고 합니다

www.juso.go.kr 여기에서도 동강여자중학교라고 검색되는데

이런건 어떻게 처리되는건지요..

**Comment by daumPostcode** [comment]
@raikos0906 
네~ 안녕하세요~

일단 저희 스스로 건물명을 수정할 수는 없습니다. juso.go.kr과 정보가 다를 경우(오타나, 명칭이 아예다르거나)에는 수정이 가능하나, 기본적으로는 행자부 도로명주소시스템에 나오는 데이터를 그대로 이용합니다. 이는 임의의 값이 아닌 주소라서 그런 것인데요.

해당 문제는 깃허브 README.md 파일에 상세히 적어 두었으니 확인 해보시면 될것 같아요~
[FAQ1번 2번 참고](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)

확인 부탁드려요~
