### ISSUE TITLE
http 개발환경과 https 운영환경에서 

### ISSUE THREAD

**Issue by leadnext** [daumPostcode/QnA#320]
아파치서버에 content-security-policy에 frame-src를 동일하게 개발(http),운영(https)에 반영하였는데 개발에서는 정상적으로 주소팝업이 열리는 반면 운영(https)환경에서는 오류가 발생하고 있습니다. 

conf파일에 추가된 내용

default-src 'self' 'unsafe-inline' 'unsafe-eval'; 
style-src 'self' 'unsafe-inline' 'unsafe-eval'; 
script-src 'self' https://ssl.daumcdn.net http://dmaps.daum.net http://t1.daumcdn.net 'unsafe-inline' 'unsafe-eval';
frame-src 'self' http://postcode.map.daum.net

**Comment by daumPostcode** [comment]
@leadnext 
네~ 안녕하세요~ 답변이 늦어서 죄송합니다.

현재 저희 우편번호 서비스는 HTTP, HTTPS가 서로 도메인이 다릅니다.
이는 가이드 페이지를 통해서도 확인하실 수 있으니 아래 주소를 참고해 주시기 바랍니다.

HTTP - http://postcode.map.daum.net/guide
HTTPS - https://spi.maps.daum.net/postcode/guidessl
