### ISSUE TITLE
크롬에서 주소 검색 창이 열리지 않아요

### ISSUE THREAD

**Issue by SJEstherKim** [daumPostcode/QnA#321]
안녕하세요, 크롬에서 daum 검색 화면이 열리지 않습니다. 한동안 잘 사용한 화면이고, 얼마전부터 발생하네요 혹시 dau에 변경 사항이 있는지 알 수 있을까요?

Refused to load the script 'https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js' because it viloates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'"

감사합니다.

**Comment by daumPostcode** [comment]
@SJEstherKim 
네~ 안녕하세요~

아뇨 변경된 사항은 없습니다.
Mac Chrome 66.0.3359.170(공식 빌드) (64비트) 버전에서 정상 동작을 하고 있는데요.
https오류라면, 혹시 저희 서비스를 이용하실때 스크립트 로딩을 어떤 도메인을 사용하실까요?

저희 서비스는 http와 https가 서로 도메인이 다릅니다.
내부에서 자동으로 프로토콜을 확인해서 결정하는 부분도 있지만 도메인을 직접 맞춰야 되는 부분도 있습니다.

https://spi.maps.daum.net/postcode/guidessl
http://postcode.map.daum.net/guide

위 두개의 가이드 페이지는 같은 내용이나 서로 프로토콜이 다르며, 들어가서 기본사용법을 봐보시면 스크립트 도메인도 다릅니다. (http, https 가이드페이지 링크는 가이드 페이지의 최상단 프리뷰 좌측 기능 목록 테스트 설명에 링크가 있습니다.)

이게 아니라면 SJE님께서 저희 우편번호 서비스를 이용하시는 페이지의 소스코드나, 저희가 확인할 수 있는 도메인을 알려주시면 감사하겠습니다.
