### ISSUE TITLE
인앱(WebView) 환경에서 history 관련 이슈 문의드립니다.

### ISSUE THREAD

**Issue by tries1** [daumPostcode/QnA#322]
안녕하세요
현재 인앱(WebView)에서 다음주소검색을 사용하고있습니다.

embed함수를 사용하여 레이어팝업 형식으로 띄워주고 있는데요
안드로이드 단말의 경우 물리적인 뒤로가기 버튼이 있어
뒤로가기 버튼 또는 history.back() 같은 함수를 호출시 다음주소검색 레이어를 닫아주고 싶습니다.

pushState와 popstate event를 이용해서 개발하여 사용중 아래와 같은 에러가 발생합니다.

```
Failed to execute ‘pushState’ on ‘History’: A history state object with URL '' cannot be created in a document with origin ‘{현재 사용중인 환경의  도메인 URL}’ and URL 'data:text/html;charset=utf-8;base64'.
```

원인을 파악하기위해 현재 location.href를 log를 찍어서 확인하던중
다음주소 검색 레이어를 띄운후에 URL이 'data:text/html;charset=utf-8;base64' 변경된것을 확인했습니다.

해당 이슈 확인이 가능한지 문의드립니다~

**Comment by daumPostcode** [comment]
@tries1 
네~ 안녕하세요~ 답변이 늦어서 죄송합니다;

음 일단 어떤 부분의 URL이 위와 같이 인코딩 되는지 잘 모르겠네요;
현재 우편번호 서비스에서 URL부분을 인코딩하여 넣는 부분은 없습니다. 

현재 의심되는 부분은 저희 우편번호 서비스의 경우 2중 iframe을 이용합니다.
저희  API의 embed함수를 이용하실때 DOM오브젝트나 id를 넣게 되는데, 만약 id=wrap 인 div태그에다가 넣는다고 가정하면
- div#wrap
   - div#__daum__layer__1
      - iframe src="about:blank"
         - iframe src="http://postcode.map.daum.net~~~"

위 처럼 id가 wrap인 div태그 밑으로 3단계로 태그가 생성되며, div#__daum__layer 밑으로 src가 about:blank를 주소로 갖는 빈 iframe을 만들며, 그 안에 다른 iframe으로 실제 저희 뷰가 렌더링될 URL이 들어가게 됩니다. 이렇게 한 이유는  도메인이 다를시에 낮은 버전의 브라우저에서도 데이터 전송을 이용하기 위해 사용한 방법입니다.

부모페이지(tries1님이 띄운 페이지)는 어떠한 경우가 있더라도 도메인 값이나 기타 다른 document나 window의 어떤 속성 값도 건들지 않습니다. 

혹시 일반브라우저(웹뷰말고)의 back 버튼을 가지고 테스트 할때도 같은 오류가 발생하신가요?
웹뷰의 경우엔 동일 환경을 셋팅하는게 어려워서 현재 테스트가 좀 어렵습니다. 일반 브라우저에서도 그렇다면, 제가 접근 할 수 있는 URL이나 소스 코드를 주시면 확인해 보도록 하겠습니다.

**Comment by tries1** [comment]
일반브라우저에서는 이상없습니다~
안드로이드 단말도 구형폰(갤럭시 노트2, 갤럭시3등)에서는 이상없는데
비교적 최신폰인  갤럭시S9, G6같은 폰에서 문제가 발생했습니다.

말씀하신대로 웹뷰환경의 문제일것이라 판단이 되고있어서
다른 오류발생원인을 찾게되면 다시 문의드리도록 하겠습니다~

**Comment by daumPostcode** [comment]
@tries1 
네 알겠습니다.
최신폰에서 그렇다니;; 최신폰도 믿을게 못되는군요;;; 아무쪼록 잘 해결이 되셨으면 좋겠네요.

제가 처리해야되는 이슈가 생긴다면 언제든 이슈 등록 해주시면 확인하도록 하겠습니다~

즐거운 하루되세요~

**Comment by webpro2** [comment]
갤럭시 S9 안드로이드 어플에서 레이어로 뜨게 만들었는데 버튼이 작동을 안하네요 
보안 문제인거같아요.
