### ISSUE TITLE
반환되는 데이타중에서 건물본번과 부번을 갖고오려면...

### ISSUE THREAD

**Issue by chodaehyun** [daumPostcode/QnA#323]
반환되는 주소데이타를 보면 건물본번과 부번에 대한 항목값이 가이드되어있지 않습니다.
해당 항목값이 어떻게 되는지 알려주세요.

**Comment by daumPostcode** [comment]
@chodaehyun 
네~ 안녕하세요~

현재 저희 시스템은 전체 주소를 내려주는 것이 기본이며,
주소의 뎁스에 따라 시도,시군구, 법정동, 도로명까지만 분리해서 내리고 있습니다.

현재 건물 본번 부번의 경우 따로 분리해서 내리지 않고 있으며, 이 데이터를 추출하실려면, 내려받는 전체 주소를 공백 분리하며, 마지막 정보를 이용하시면 되실것 같습니다.

현재 새로운 데이터를 추가할 계획은 없는 점 양해 부탁드립니다.
