### ISSUE TITLE
우편번호 서비스와함께 좌표값을 받고싶습니다.

### ISSUE THREAD

**Issue by jongbong** [daumPostcode/QnA#324]
다음 우편번호 서비스를 통해 주소지 통합검색을 활용하고
검색된 주소지에 해당하는 좌표값을 받아 서비스에 활용하고 싶습니다.
혹시 계약이나 협약을 통해 서비스 제공이 가능한지 문의 드립니다.
현재 일사용량이 3만건 정도 되며 자체 DB를 통해 지번/도로명 주소를 통한 서비스를
다음 우편번호 서비스를 통해 통합 검색을 활용하고
만약 좌표까지 제공 가능하다면 계약이나 협약을 통해서라도
활용하거나 다음 지도/로컬 API를 활용하는 방안을 고려중에있습니다.
혹시 우편번호 서비스를 통해 좌표까지 한번에 해결이 가능한지 문의 드립니다.
계약이나 협약을 통해 가능하다면 견젹또한 받아보고 싶습니다. 
게시판이나 cherrybong95@gmail.com 로 연락주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@jongbong 
안녕하세요~

네 문의 주신 내용에 답변을 드리면,
말씀해주신 내용중에, 우편번호서비스 자체에서 좌표를 내리는 기능은 현재 추가가 어렵습니다.
추가로 현재 저희 서비스는 API키나 이런걸로 사용자를 파악해서 제공하는 것이 아니므로, 별도의 계약이나 협약을 제공해 드리는 것도 어렵습니다.

가능한 방법으로는 말씀해주신 내용에도 있고, 저희 가이드 페이지(http://postcode.map.daum.net/guide) 에서도 제공하고 있는 샘플로 확인하실 수 있는데요. (샘플 중 마지막 "주소를 선택하면 지도도 함께 보여주기" 참고)

저희 우편번호 서비스API를 통해 주소 정보를 얻고,
[kakao developers](https://developers.kakao.com/)에서 제공하는 지도/로컬 API 중 javascript API를 통해 주소정보로부터 데이터를 얻을 수 있는 API를 이용하면 좌표 정보를 얻을 수 있습니다. 그 API의 다큐멘테이션은 (http://apis.map.daum.net/web/documentation/#services_Geocoder_addressSearch) <- 여길 참고하시면 쉽게 확인 하실 수 있습니다.

kakao developers에서 제공하는 API는 api key를 통해 컨트롤하기 때문에 말씀하신 트래픽 관련해서는 기본 제공량 외 더 필요할 시에는  개발자사이트의 데브톡 문의를 통해 확인 가능하실 것 같습니다.

감사합니다.

**Comment by daumPostcode** [comment]
추가로 저희 서비스의 제약사항에 대해서 설명을 더 드리면,

저희 서비스는 도로명주소가 발급되고, 5자리 기초구역번호(새우편번호)가 할당된 주소만 검색이 가능합니다. 
즉, 도로명 주소가 없는 일반 지번은 검색이 안됩니다(건물이 없는 나대지와 같은 곳)
이외 추가로 검색되는 사항은 사서함 정보가 있습니다.

그리고 행자부에서 제공하는 API와 제일 다른점은, 보안주소(군사시설, 국각발전시설 등)라고 불리우는 몇가지 타입의 주소가 있는데 해당 주소의 경우 저희에게 몇몇 중요 데이터를 빼고 내려주기 때문에 저희 시스템상 매핑이 불가능하여, 검색이 되지 않습니다. 보통 발전소, 군사시설, 비공개 국가주요기관 등이 이와 같습니다.
CS로 특정 발전소(또는 국가 보안시설)에서 근무하는데 택배주소를 입력하고 싶은데 입력이 안된다라는 CS가 종종 들어와서 말씀드립니다.

즉, 대한민국에 존재하는 모든 주소를 커버해야하는 시스템에서는 사용하는게 부적절 할 수 있기 때문에 이부분 확인해 보시는게 좋으실것 같아요~
