### ISSUE TITLE
안녕하세요. 우편번호 API사용을 위해 방화벽에서 허용해야할 도메인을 정확하게 알고싶습니다.

### ISSUE THREAD

**Issue by ghost** [daumPostcode/QnA#327]
안녕하세요. 제목그대로 방화벽에서 허용해야할 도메인이 필요한데요

검색결과 예전글에

HTTP환경
http://postcode.map.daum.net
http://dmaps.daum.net
http://s1.daumcdn.net
http://i1.daumcdn.net
http://m1.daumcdn.net
http://apis.daum.net
http://stlog1.local.daum.net
http://sughub.search.daum.net

로 나와있더라고요.

혹시 더 추가해야할 도메인이 있다면 답변해주시길 바랍니다.

수고하세요~

**Comment by daumPostcode** [comment]
@JzamesDean 

네~ 안녕하세요~

더 추가하실 건 없으시며, 오히려 몇개가 더 빠지거나 변경된 것이 있습니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net
- https://apis.daum.net (v3 maps api 사용시)

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://s1.daumcdn.net 
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net
- https://apis.daum.net (v3 maps api 사용시)


위와 같으며, 다음주 쯤에 모든 리소스 파일의 도메인이 t1.daumcdn.net 으로 변경될 예정이라, s1.daumcdn.net도 사라질 예정입니다. 참고해 주세요~
