### ISSUE TITLE
일부기종에서 주소검색 후 결과리스트 클릭시 반응없음.

### ISSUE THREAD

**Issue by smw0401** [daumPostcode/QnA#328]
대다수 기종은 정상동작하는데요

일부기종에서 우편번호 주소 검색 후 결과 클릭시 아무 반응이 없네요.

콜백함수 호출을 안하는거 같네요.

**Comment by daumPostcode** [comment]
@smw0401 
안녕하세요~

음.. 일부기종이란게... 너무 광범위 하네요;;
어떤 단말인지, 버전과, 어떤 브라우저(사파리나 크롬 등의 이름과 버전)를 이용하는지, 웹뷰환경인지, 
추가로 제가 접속 해서 확인 할 수 있는 URL을 제공해 주시면 좋을 것 같습니다.

현재 말씀해 주신 정보로는 사용자 개발 코드의 오류인지(API이기 때문에 개발자 분들의 오류도 자주 발생합니다), core스크립트의 오류인지, 알기가 힘드네요;;

좀 더 정보를 주셨으면 합니다.

**Comment by smw0401** [comment]
기종은 갤럭시s9이고 안드로이드 버전은 8.0입니다.
크롬을 사용하는 웹뷰 환경입니다. 크롬버전은 67.0.3396.87입니다.
 
http://postcode.map.daum.net/guide#sample

이 샘플을 실행해도 동일합니다.

주소 검색 후 결과 클릭시 아무런 반응이 없습니다.

**Comment by daumPostcode** [comment]
@smw0401 
안녕하세요~

![img_0782](https://user-images.githubusercontent.com/20675065/41836052-88eb1606-7894-11e8-8a22-4428105a4884.JPG)
위 스샷과 같은 단말말기에서 크롬 브라우저로 확인을 해보았습니다.
현재 가이드 페이지의 팝업모드와, 레이어 모드 정상동작으로 확인이 되는데요.

크롬앱으로 실행하는 크롬 브라우저가 아닌, 
크롬 웹뷰라면 FAQ 9~14번까지의 내용을 확인해 보신 후에, 직접 대응해 주셔야 합니다. 웹뷰의 경우 웹뷰를 어떻게 구성(코드 작업) 하느냐에 따라 기능이 천차만별이라 확인이 어렵습니다. 저희가 확인하고 직접 대응해 드리는 부분은 일반 웹브라우저(모든 기능이 구현된 브라우저)이며, 웹뷰의 경우에는 개발 콘솔에서 뜨는 로그를 한번 확인해 주시기 바랍니다.

발생하는 현상으로는 FAQ10번에 있는 현상과 비슷해 보이는데요, 제가 네이티브 앱 개발자가 아니라 정확한 기술적인 설명은 드리지 못하나, 일반적으로 웹뷰에서 팝업모드를 사용하게 되면, 부모페이지를 둔채로 자식페이지가 뜨는게 아니라, 부모페이지가 없어져 버립니다. 즉 대체가 되버리는 것이죠. 그래서 검색후에 검색결과를 선택해도 아무런 반응이 뜨지 않는 것이죠. 또한 저희 우편번호 서비스처럼 팝업을 띄울때 아무런 도메인 정보를 넣지 않고 띄우는 서비스의 경우에는 추가 개발을 하지 않는한 팝업으로 안뜨는 경우가 있습니다(이는 일반 브라우저의 크로스브라우징 처리 때문에 그렇습니다)

이부분 확인하시여 한번 확인 부탁드립니다.
네이티브 앱 안의 웹뷰에 대해서는 직접적인 도움을 드릴 수가 없는 점 양해 부탁드립니다.
