### ISSUE TITLE
react dom 관련 오류 문의

### ISSUE THREAD

**Issue by megadeth10** [daumPostcode/QnA#329]
![react](https://user-images.githubusercontent.com/921791/41955829-a770b480-7a1c-11e8-9117-50683b21939f.png)

React Component가 생성될 때, 우편번호 검색 script를 load 한 후 daum.Postcode 생성자 호출시에 오류가 발생하였습니다.  관련 오류 해결 할 수 있는 조언을 부탁드립니다.

참고로 이렇게 호출시 "https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false"
document에 검색화면이 load 됩니다.

위 이미지가 작성 코드이고 아래 이미지가 오류 log 입니다.
![error_log](https://user-images.githubusercontent.com/921791/41955804-8729372e-7a1c-11e8-9056-48005f1c7215.png)

**Comment by daumPostcode** [comment]
@megadeth10 
리엑트나 앵귤러와 같은 동적 타입 프레임워크에 사용하실 때에는 말씀하신 autoload=false를 통한 동적 로딩 방식을 추천드립니다. (가이드 페이지 참고)

저희 API의 경우에는 부르신 스크립트 외에도 추가로 core스크립트를 부르기 때문에 위 스크린샷(API정적로딩 방식)과 같이 작업을 하시면 코어 스크립트가 로딩되지 않아 발생하는 오류입니다.

또한 동적로딩의 경우에도 여러번 실행한다고 여러번 부르지는 않기 때문에 사용하시는게 좋습니다.

**Comment by megadeth10** [comment]
답변 감사합니다.
