### ISSUE TITLE
(하이브리드앱) 주소 검색 후 나오는 지도버튼 제거가능여부

### ISSUE THREAD

**Issue by mindf** [daumPostcode/QnA#33]
안녕하세요. 하이브리드앱 개발중입니다.

embed()로 적용하였습니다.

주소 검색 후 나오는 지도버튼을 누를경우에는 페이지 전체가 이동을 하는데, 서비스 특성상 필요하지 않은

기능이며 결정적으로 페이지 전체가 이동해버려 제어가 안되는 단점이 있습니다. 혹시 지도버튼을 제어(없애거나,,

혹은 api차원으로)가능한 방법이 있는지 문의드립니다.

감사합니다. 좋은하루되세요.

**Comment by daumPostcode** [comment]
@mindf 
네~ 안녕하세요~

현재로써는 UI 구성요소를 제거하는 옵션은 없습니다.
해당 옵션의 경우에는 추가 논의 중에 있으며, 아직 일정이 잡혀있진 않습니다.

하이브리드앱이면, 가능한 방법으로는 네이티브 코드에서 웹뷰에서 redirect를 막는 방법밖에는 없을 것같아요;;; 일단 "지도" 버튼을 선택했을때의 이동은 window.open을 이용하기 때문에 이부분을 체크하여 이용하시는 방법밖에는 없을 것 같습니다;;
