### ISSUE TITLE
시/군 단위로 결과 값을 받을 수 있는지 문의드립니다.

### ISSUE THREAD

**Issue by yhsang2** [daumPostcode/QnA#330]
안녕하세요. 다음 주소 api를 잘 사용하고 있는 초보 웹 개발자입니다.
개발을 열심히 하고 있는데, 하필 필요한 기능이 "서울특별시", "경기도 고양시", "경기도 가평군", "인천광역시", "부산광역시" 이렇게 시/군 단위네요. (업체 서비스 범위를 지정하는 기능이라, 시/군/구 단위로 하면 너무 작다고 하네요..) 불운하게도, 다음 guide문서에서 시/군 단위로 리턴 값을 받을 수 있는지 확인이 안되는데, 이 문제를 해결할 좋은 방법이 있을까요?

**Comment by daumPostcode** [comment]
@yhsang2 
안녕하세요~

말씀하신 기능이 검색시, 시/군 단위로 축소검색을 하길 원하시는 것일까요?
또한 시/군 단위로 리턴 값을 받을 수 있는지에 대한 질문이 어떤것을 의미하는지 잘 모르겠네요;;

현재 저희 서비스의 경우에는 각 사이트에서 사용자의 범용적인 주소를 내려주는 것에 초점이 맞춰져 있으며,
이외 특정 주소 검색 결과를 제한하거나, 특정 정보만 내리는 기능은 없습니다. 
(매일 업데이트 되는 도로명 주소 데이터의 관리를 저희가 담당하고 이용자분들의 경우 단순 주소값만 필요할 시 저희 서비스가 좋을 수 있습니다)

특정 주소데이터를 검색 또는 표출 정책 제한, 반환되는 데이터의 변환 등을 원하실 때는 행자부나 우정국에서 직접 데이터를 받으셔서 처리를 해주셔야 될것 같습니다.
