### ISSUE TITLE
농협인터넷뱅킹 접속 시, 주소  API 스크립트 실행 안됨

### ISSUE THREAD

**Issue by Mcv76** [daumPostcode/QnA#331]
작년에 개발해서 넣어둔 스크립트가 얼마전부터 실행이 안되서 확인해 보니 

농협인터넷뱅킹에 접속 후 보안프로그램이 작동하면 스크립트를 막는거 같습니다.

조치 부탁 드립니다.

**Comment by daumPostcode** [comment]
@Mcv76 
네~ 안녕하세요~

저희 우편번호 API의 경우, 사용자에게 API Key발급이나 이런걸 하지 않기 때문에, 사용자가 어떤 API를 쓰고 있고, 어떤 도메인에서 사용하고 있는지 알 수 없습니다.

말씀하신 정보로는 저희가 확인하기가 힘들며, 현재 저희 가이드 페이지를 비롯하여 정상적으로 서비스가 동작중이기 때문에, 해당 문제에 대해서는 직접 오류를 확인해 주시기 바랍니다. 말씀해 주신 사항으로는 원인 파악이 어렵습니다.

HTTPS용 서비스를 이용한다면 도메인이 한번 변경되었는데 이부분 확인 부탁드립니다. 또한 내부 인트라넷에서 사용하시는 경우라면, 포트가 막혀서 그런 것일 수도 있으니 이것도 확인해 보셔야 합니다.

http://postcode.map.daum.net/guide <- 여기 가이드 페이지에서 사용법과, API명세를 확인해 보시기 바랍니다.
