### ISSUE TITLE
웹취약점 점검 SRI(Subresource Integrity) 지원 검사 문의

### ISSUE THREAD

**Issue by hagi-kim** [daumPostcode/QnA#332]
웹 취약점점검에서 발생하는 SRI 적용에 대한 문의 드립니다.

작년에 해당 내용으로 문의한 건을 확인하였는데요. 현재 개선 여부와 개선이 되었다면
해당 점검 내용 조치를 위한 해결 방안은 어떤것이 있는지 문의 드립니다.

아래는 현재 사용중인 스크립트입니다.

<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

답변 부탁드립니다.

**Comment by daumPostcode** [comment]
@hagi-kim 
네~ 안녕하세요~

예전 문의 사항과 답변은 https://github.com/daumPostcode/QnA/issues/137
이 이슈인데요..

결론 부터 말씀드리면 이전과 같이 현재 SRI관련 integrity 키 값을 드리진 못합니다.
저희한테 들어온 문의 외에도 지도 API 쪽에도 비슷한 문의가 왔는데요, 당시에 논의 결과 현재 배포방식으로는 지원이 불가능 하다 였습니다. 
그리고 해당 취약성의 중간자 공격같은 경우에는 https 방식을 쓰면 해결이 되는 것으로 알 고 있습니다.

이 부분을 해결하려면 배포방식을 변경해야 하는데, 현재 이 부분이 현실적으로 어려운 상태입니다.
소스 관리 및 정책 변경, 그리고 노티 정책 등 확인해야될 사항이 많은데, 현재로써는 리소스상 진행이 어렵습니다.

추후 새로 배포되는 API의 경우에는 적용을 할 순 있겠지만, 기존 API의 경우에는 지원이 어려울 것 같습니다.

원하시는 답변을 드리지 못해 죄송합니다.
