### ISSUE TITLE
팝업이나 iframe 이용안하고 현재창에 입력, 출력하는 방법은 있나요

### ISSUE THREAD

**Issue by chang1111** [daumPostcode/QnA#333]
방법이 있는지 궁금합니다.

**Comment by daumPostcode** [comment]
@chang1111 
네 안녕하세요~

질문이 잘 이해가 안되네요;;;;
팝업(open), iframe(embed)모드를 이용안하고 현재창에 입력 출력이라고 말씀하시는게;;
혹시 REST API를 말씀하시는 걸까요????
