### ISSUE TITLE
영문 이용 가이드

### ISSUE THREAD

**Issue by VITAbai** [daumPostcode/QnA#334]
안녕하세요.

현재 미국 법인으로 자체 사이트 개발중인 회사입니다.

수주 업체가 인도에 위치한 회사라 
구글 번역기로는 해당 업체에서 관련 정보를 이해하기 어렵다고 하여
다음 주소 api 관련하여 참고할만한 영문 자료가 있는지 궁금하여 문의 드립니다.

빠른 답변 주시면 감사하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@VITAbai 
네~ 안녕하세요~

우선 우편번호 서비스는 영문가이드를 제공하고 있지 않습니다.

주소 시스템 자체의 경우에는 http://www.juso.go.kr/openEngPage.do  행자부 사이트의 영문가이드를 보고 이해를 할 수 있습니다.
또한 JS API의 경우에는 예제 샘플과 구글 번역기로도 서비스 적용하는데는 큰 무리는 없다고 판단되어서 영문가이드를 작성하지 않았으며, API자체가 단순하고 대부분 받은 데이터를 어떻게 사용할지에 대한 구현만 필요로 해서 실제 개발하시는 분들이 API자체로는 어려움은 없으신 것으로 압니다. 다만 주소체계에 대한 이해 때문에 어려움이 있으시다면 행자부 사이트에서 도움을 얻는 방법이 좋아 보입니다.
