### ISSUE TITLE
준공년월일 반환.

### ISSUE THREAD

**Issue by sleoqheo2** [daumPostcode/QnA#335]
다음지도를 이용하고 있는 플랫폼 입니다.
혹시 건물의 준공년월을 다른 응답과 같이 반환 받을 수 있는
방법이 있을까요?

준공년월을 데이터 베이스로 관리 하는데에는 무리가 있네요..

**Comment by daumPostcode** [comment]
@sleoqheo2 
네~ 안녕하세요~

현재 우편번호 서비스의 경우에는 주소정보를 조합하는데 필요한 정보만 내릴뿐; 준공년월 정보를 내리진 않습니다.
해당 정보의 경우에는 서비스 성격상 추후 추가도 예정되어 있지 않습니다. 

실제 행자부에서 일일 업데이트 받는 데이터 중에 준공년월 정보가 있는지는 담당자분 확인이 필요한데요. 
제 생각에는 부동산 쪽 팀에서는 가지고 있을 지라도, 저희쪽은 없을 것 같습니다.
(다음 지도 서비스는 여러 DB에서 데이터를 가져와서 뿌려주는 것이라, 우편번호 서비스와는 역할이 다릅니다)

지금은 담당자 분이 안계셔서 주소 데이터중에 해당 정보가 있는지 확인을 못하는데 내일 확인해서 추가 답변 드리도록 하겠습니다.
그런데 추가는 어려울 것 같아요;;;

**Comment by daumPostcode** [comment]
@sleoqheo2 
담당자 분께 여쭤본 결과, 현재 행자부에서 받는 데이터의 경우에는 준공년월은 없다고 합니다. 이외 데이터의 경우에는 다른 소스에서 가져와서 서로 연동하는 작업을 해야 진행이 가능한데, 위에 말씀드린 것처럼 우편번호 서비스에는 적용하기 어려울것 같습니다.

도움을 드리지 못해 죄송합니다.
