### ISSUE TITLE
주소 선택 시 "전북 전주시 덕진구 오공로" 누락

### ISSUE THREAD

**Issue by jhgan** [daumPostcode/QnA#336]
전북 전주시 덕진구 오공로 검색 > 도로명 주소 영역에 "전북 전주시 덕진구 오공로" 가 아닌 "중동 오공로" 로 표기되고 있습니다.
도로명 주소를 가지고 배송이 되고 있어, 시도/시/군/구가 정상적으로 노출될 수 있도록 수정 부탁 드립니다.

**Comment by sangyeul** [comment]
같은 증상이네요 수정 부탁 드립니다.

**Comment by daumPostcode** [comment]
@jhgan 
@sangyeul 

네~ 안녕하세요~

해당 이슈 데이터 담당자 분께 전달하여 확인하여 처리하도록 하겠습니다.
제보 감사드립니다.

**Comment by daumPostcode** [comment]
@jhgan @sangyeul 
안녕하세요~

현재 해당 주소 데이터 수정되어 배포 되었습니다.
원인은 해당 주소의 depth정보가 잘못 입력되어 발생한 문제로 데이터 수정으로 처리 완료되었습니다.

만약 검색결과가 계속 이상하다면; 캐시를 한번 지워주시면 정상 적용될 것으로 생각됩니다. (브라우저 캐시가 검색결과를 잡고 있네요;;)

불편을 드려 죄송합니다.
