### ISSUE TITLE
행자부 주소사이트에서는 조회되는데 다음에서는 조회가 되지 않습니다. 

### ISSUE THREAD

**Issue by likesunset** [daumPostcode/QnA#337]
서울특별시 송파구 동남로 341(오금동, 송파레미니스2단지) 의 경우 송파레미니스 2단지  또는 송파레미니스 로 검색하면 행자부주소사이트에서는 조회가 되는데 다음에서는 조회가 되지 않습니다. 확인부탁드립니다.

**Comment by daumPostcode** [comment]
@likesunset 
네~ 안녕하세요~

해당 이슈도 데이터 담당자 분에게 문의 넣도록 하겠습니다.
제보 감사드립니다.

**Comment by daumPostcode** [comment]
@likesunset 
담당자 분께서 확인해보니, 건물 정보가 누락되어 있어서 발생한 문제였습니다.
현재 수정되어 배포되었습니다.

불편을 드려 죄송합니다.

만약 이전과 같은 검색 결과가 나온다면 브라우저 캐시를 한번 삭제해 주시기 바랍니다.
