### ISSUE TITLE
CORS 오류

### ISSUE THREAD

**Issue by hhs9102** [daumPostcode/QnA#338]
Access to Imported resource at 'https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

오류가 발생합니다.

daumPostcode에서 접근을 막은것이 맞나요?

**Comment by daumPostcode** [comment]
@hhs9102 
네~ 안녕하세요~

현재 어떻게 사용하시고 계실까요?

localhost:8080으로 띄운 페이지에서 ajax를 통해서 위 스크립트를 호출 하고 계시나요?
만약 이렇게 호출하신다면 CORS 오류가 뜨는건 당연합니다. ssl.daumcdn.net은 해당 헤더 설정이 되어 있지 않습니다. 이용법은 저희 가이드 페이지에 있는 방식만 유효합니다. (브라우저의 ajax통신은 도메인이 다른 서버의 데이터를 가져오는건 기본적으로 막습니다)

이외 다른 이슈라면, 저희 코드를 사용하는 부분도 같이 공유해 주시면 좋을 것 같습니다. 현재 특정 도메인을 차단하거나 아이피를 임의로 막거나 하진 않습니다.
