### ISSUE TITLE
Uncaught TypeError: daum.Postcode is not a constructor 오류

### ISSUE THREAD

**Issue by hhs9102** [daumPostcode/QnA#339]
Uncaught TypeError: daum.Postcode is not a constructor

network를 통해
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js

postcode.v2.js 파일이 로드된 것을 확인했으나,
위와 같은 오류메시지가 출력됩니다.
무엇이 부족한 것 일까요?

**Comment by daumPostcode** [comment]
@hhs9102 
저희 서비스의 경우에는 postcode.v2.js를 로딩 한 후에, 실제  core스크립트를 한번 더 로딩합니다.
해당 오류는 현재 이 core스크립트가 로딩이 안되서 발생한 문제이며,

아주 기본적인 자바스크립트를 사용 (script 태그로 파일 추가하고, 그 아래에서 실행하는 방식)으로 할때는 문제가 되진 않지만, 만약 리엑트나 앵귤러나 이와 비슷한, 동적으로 DOM을 생성및 삭제하는 라이브러리들을 이용하실때에는 타이밍 문제가 발생합니다. 그런 경우엔 저희 가이드 페이지에 있는 동적로딩 방법을 이용해 보시면 해결 되실거에요~

**Comment by hhs9102** [comment]
매우 감사합니다. 드디어 해결됐습니다.
