### ISSUE TITLE
http://dmaps.daum.net/map_js_init/postcode.v2.js - https 지원관련

### ISSUE THREAD

**Issue by HelloSolsol** [daumPostcode/QnA#34]
안녕하세요

제목 그대로
http://dmaps.daum.net/map_js_init/postcode.v2.js 

https 지원 계획은 없으신가요?

https://dmaps.daum.net/map_js_init/postcode.v2.js

**Comment by daumPostcode** [comment]
@HelloSolsol 

네~ 안녕하세요~
해당 건은 현재 지원하고 있구요. 저희 가이드 페이지를 보시면 확인가능하십니다.
다른 사이트들과 다르게, 같은 도메인을 이용하고 있지 않고, http와 https가 서로 다른 도메인을 사용합니다.
자세한 사항은 가이드페이지를 확인해 주세요.

기본적으로 모든 설명은 [가이드 페이지](http://postcode.map.daum.net/guide)에 있으며, https관련해서는  메뉴바 바로 아래의 상단 설명 문구를 보시면 https가이드로 가는 링크가 있습니다. 여기서 확인해 주시면 됩니다.

[https용 API가이드 URL](https://spi.maps.daum.net/postcode/guidessl)

**Comment by HelloSolsol** [comment]
@daumPostcode 
빠른답변감사합니다~
