### ISSUE TITLE
주소검색에는 나오는데 등록이 되질 않습니다.

### ISSUE THREAD

**Issue by healim2** [daumPostcode/QnA#340]
언양읍 서부리 96-3번지가 주소지 등록이 안됩니다. 확인바랍니다.

**Comment by daumPostcode** [comment]
@healim2 
안녕하세요~

"언양읍 서부리 96-3" 행자부 도로명 검색 시스템에서 검색한 결과입니다
![image](https://user-images.githubusercontent.com/20675065/43057534-d70dce7e-8e7d-11e8-9cce-61a5b0885e65.png)

해당 주소는 현재 도로명이 발급되어 있지 않은것 같습니다. 도로명 주소가 발급되어 행자부 시스템에 등록되면, 이후 보안지역 주소가 아니면 저희 시스템에도 자동 등록됩니다 (보통 1일 소요)

행자부 사이트에서 주소등록을 먼저 해주시기 바랍니다.

감사합니다.
