### ISSUE TITLE
우편번호 서비스 서버의 ip를 알수 있을까요?

### ISSUE THREAD

**Issue by LimSuhgHo** [daumPostcode/QnA#341]
안녕하세요.
엘지화학 오창공장입니다.

다음의 우편번호 api 서비스를 이용하고자 합니다.
해당 서버의 ip 방화벽 오픈관련해서 혹시 해당 서비스 서버의 ip 정보를 알 수 있을까 해서
글 남깁니다.

답변 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@LimSuhgHo 

안녕하세요~

현재 인트라넷에서의 공식 지원은 하지 않고 있습니다.
그래서 저희가 알려드릴 수 있는 정보는

아래와 같이 서비스내에서 사용하는 도메인 정보밖에 없네요;; 도메인의 IP를 찾아서 직접 등록해 주셔야 합니다.
감사합니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net
- https://apis.daum.net (v3 maps api 사용시)

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net
- https://apis.daum.net (v3 maps api 사용시)
