### ISSUE TITLE
다음 검색창 주소 ui를 사용하지 않는 방법

### ISSUE THREAD

**Issue by hhs9102** [daumPostcode/QnA#342]
daum.postcode.load(function(){
                    new daum.Postcode({
                        oncomplete: function(data) {
                        	
                        }
                    }).open();

이것을 통해 검색하지않고,
 내부 팝업창을 이용하여 주소 검색 service를 날려 값을
리턴받는 형식은 제공하지 않나요?

**Comment by daumPostcode** [comment]
@hhs9102 
네~ 안녕하세요~

현재 REST  API방식은 지원 예정이 없습니다. 개발에 참고해 주시기 바랍니다.

REST API와 같은 형식을 원하신다면, 저희 API보단 아래 API들을 한번 확인해 보시는게 좋으실 것 같습니다~
- https://www.poesis.org/postcodify/
- http://www.juso.go.kr/addrlink/main.do

감사합니다.
