### ISSUE TITLE
http, https 사용

### ISSUE THREAD

**Issue by hhs9102** [daumPostcode/QnA#343]
안녕하세요.

클라우드 서버를 통해 프로토콜을 http, https를 동시에 사용하는데요.

이 경우에 어떤 스크립트를 import 해야할까요?

http 프로토콜을 사용한 도메인에서도 아래의 script 적용시에도 정상작동하는데,
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

http, https가 구분되어지지 않고 개발된다면 어떤 문제가 발생하나요?

**Comment by daumPostcode** [comment]
@hhs9102 
네~ 안녕하세요~

네~ hhs9102님께서 개발하시는 환경이 http, https 둘다 이용하신다면,
저희 서비스는 https용 (본문에 올리신 주소)을 이용하시면 됩니다.

추가로 어떤 문제가 발생하진 않아요~~
