### ISSUE TITLE
인천광역시 중구 운북동 1276-7  이 검색되지 않습니다.

### ISSUE THREAD

**Issue by buysun** [daumPostcode/QnA#344]
인천광역시 중구 운북동 1276-7  이 검색되지 않습니다.

**Comment by daumPostcode** [comment]
@buysun 
네~ 안녕하세요

![image](https://user-images.githubusercontent.com/20675065/43179704-37dc8474-900f-11e8-9234-e7e292fd0752.png)
해당 주소는 현재 행자부 사이트에서 검색이 되지 않습니다. 이러한 주소는 도로명 주소가 발급이 안된 주소일 가능성이 있습니다. 확인 부탁드립니다.

행자부에 등록되지 않은 주소의 경우 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)을 참고하시어 처리해 주시기 바랍니다.

감사합니다.
