### ISSUE TITLE
일부 사용자가 접속이 되지않습니다.

### ISSUE THREAD

**Issue by lkm14** [daumPostcode/QnA#345]
제 로컬이나 다른 피씨에서는 전부 접속이 되는데
일부 ip혹은 pc에서 접속이 되지않습니다. 
daum is not defined. 오류가 뜨기도하고 js파일을 넣어줘도 팝업창내에서 아무것도 보이지않네요
그 피씨에서 확인해보니

https://spi.maps.daum.net

여기로 접속자체가 안되는데 혹시 어떤 문제가 있는걸까요?

**Comment by daumPostcode** [comment]
@lkm14 
네~ 안녕하세요~

우선 말씀드릴 수 있는 것은, 저희가 임의로 사용자를 막거나 하진 않습니다.

해당 도메인이 아예 접근이 안된다면,
직장에서 사용하신다면 네트워크 인프라팀 등에서 뭔가 조치가 있었던지(특히 내부망에서 사용시),
개인 사용자라면, 공유기 설정 문제 또는, PC에 설치된 다른 프로그램이 접근을 막고 있을 수 있습니다. 또는 크롬브라우저의 경우 확장 프로그램이 막는 경우도 많습니다(이 부분을 확인해 보실려면 시크릿 창에서 이용해 보시면 됩니다)

예전에도 한동안 접속 안되신다고 하시다가 공유기 재부팅으로 해결이 되신 분도 계셨으며, PC의 불필요한 보안프로그램, 또는 브라우저의 익스텐션 같은 것을 초기화 한 후에 접속이 되신 분도 계셨습니다.

워낙에 변수가 많아 직접적인 해결 방법은 현재로써는 딱히 없네요;;;
먼저 접속이 안되는 몇몇 분들의 컴터의 브라우저 상태나 인터넷 뱅킹 보안 프로그램과 같이 원치 않는데 설치된 프로그램들을 삭제한 후, 공유기에 연결된 PC라면 공유기까지 재부팅을 한번 해보신 후 확인 부탁드립니다)

특정브라우저에서만 안되고 다른 브라우저에서 된다면, 특정브라우저의 설정 문제같고, 모든 브라우저에서 안되면 인터넷 CP또는 공유기쪽 문제일 수 있으니, 확인 부탁드립니다.

(해당 질문은 https://github.com/daumPostcode/QnA/issues/117 의 이슈와 거의 동일하여 답변의 내용이 중복되는점 참고바랍니다)

**Comment by imjusti** [comment]
저도 어제부터 동일한 증상이 있었습니다.
https://spi.maps.daum.net 으로는 접속이 안되더군요.

제 경우에는 dns를 1.1.1.1 로 설정하고 사용하고 있었습니다. 
저 상태에서 nslookup spi.maps.daum.net 을 해보면 아래와 같이 에러가 나왔었습니다.

*** spi.maps.daum.net에 사용할 수 있는 internal type for both IPv4 and IPv6 Addresses(A+AAAA) 레코드가 없습니다.

현재 '자동으로 DNS 주소 받기'로 변경후에는 위 문제가 사라졌습니다.

**Comment by daumPostcode** [comment]
@lkm14 @imjusti 

해당 이슈에 대해 인프라 팀에 문의한 결과 1차 답변이 와서 공유 드립니다.

해당 이슈는 저희 회사 설정에 문제가 있는 것은 아니며, 도메인 서버 1.1.1.1을 관리하는 NS쪽에 여쭤봐야 되는 문제로 보입니다.
그쪽에서 지원을 안하던지, 또는 다른 문제가 있는지 확인이 필요합니다.

현재 저희 내부에서도 1.1.1.1 NS에 문의를 준비중이며, 해당 답변에는 시간이 좀 소요될 것 같습니다.

**Comment by daumPostcode** [comment]
@lkm14 @imjusti 
현재 해당 현상 처리 되었습니다. 확인부탁드립니다~
