### ISSUE TITLE
주소 검색 스크립트 로딩 관련

### ISSUE THREAD

**Issue by millpoo** [daumPostcode/QnA#346]
사이트 내에서 주소검색 스크립트가 로딩이 안되서 문의 드립니다.

기존에 적용되어 있던 버전은
https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js
이 버전이고,

https://dmaps.daum.net/map_js_init/postcode.v2.js
링크를 변경하려고 합니다.
가이드 문서를 보니 위 링크가 최신인 것 같아서요.

로컬에서 작업할 땐 상관없었지만(http로 로딩),
서버에 반영하기 위해 https로 호출을하니 스크립트를 호출하지 못합니다.

가이드 사이트에 안내되어 있는
https://spi.maps.daum.net/postcode/guidessl
위 페이지도 뜨지 않는데 확인해 주세요.

**Comment by imjusti** [comment]
https이면 https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js 로 하셔야 합니다.

**Comment by daumPostcode** [comment]
@millpoo 
네~ 안녕하세요~

dmaps.daum.net의 경우에는 오직 http만 대응하기 때문에 https 환경에서는 사용하실 수 없습니다.

현재 말씀하신 가이드 페이지 https://spi.maps.daum.net/postcode/guidessl 는 정상 접근이 가능한데;; 이상하네요;; PC에서 안되신다면 핸드폰으로 LTE상태에서 접속해 보시겠어요?

일단 접속이 안되시니, HTTPS용 도메인의 경우엔
-> https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js
위 도메인을 이용하시면 됩니다. (http, https 환경모두 위 도메인을 이용하셔도 됩니다.)

감사합니다.

**Comment by millpoo** [comment]
@daumPostcode 

네 말씀하신 것처럼 PC에서는 접속이 안되고,
모바일로 접속 또는 모바일 핫스팟으로 네트워크 연결해서 접속하니 가이드 페이지가 호출되는 것을 확인했습니다.

추가 문의사항이 있는데,
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js
위 주소로 스크립트를 호출후 가이드 페이지에 나와있는 방식대로 iframe으로 주소검색 레이어를 띄워봤는데 로컬에서는 정상적으로 보이지만 마찬가지로 서버에 반영하였을 경우 iframe 화면이 표시되지 않습니다. 
iframe 영역에 

`spi.maps.daum.net의 서버 IP 주소를 찾을 수 없습니다.`

라는 안내 메세지가 표시되는데 이 부분 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@millpoo 

해당 이슈가 https://github.com/daumPostcode/QnA/issues/345
바로 아래에 등록된 이슈랑 매우 흡사한데요.한번 확인 부탁드립니다.

**Comment by millpoo** [comment]
@daumPostcode 

nslookup spi.maps.daum.net 1.1.1.1 은 안되고,
nslookup spi.maps.daum.net 8.8.8.8 은 됩니다.
dns server에 따라 spi.maps.daum.net을 접속하지 못하는 경우가 있는데 어떻게 해야 하나요?


![image](https://user-images.githubusercontent.com/8067749/43303603-6a0b97f8-91ab-11e8-9bed-eeb5fd130082.png)

![image](https://user-images.githubusercontent.com/8067749/43303620-7f790e40-91ab-11e8-8ad0-1d0dbde1cddf.png)

**Comment by daumPostcode** [comment]
@millpoo 
음.. 이슈가 아래와 같네요; 현재 해당 이슈는 서버개발자 및 네트워크 인프라팀에 문의 넣어둔 상태입니다.
답변이 오면 말씀드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@millpoo 
담당자 분께 1차 답변이 왔는데요.
저희 회사 설정에 문제가 있는 것은 아니며, 도메인 서버 1.1.1.1을 관리하는 NS쪽에 여쭤봐야 되는 문제로 보입니다.
그쪽에서 지원을 안하던지, 또는 다른 문제가 있는지 확인이 필요합니다.

현재 저희 내부에서도 1.1.1.1 NS에 문의를 준비중이며, 해당 답변엔 시간이 좀 소요될 것 같습니다.
확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@millpoo 
현재 해당 현상 처리 완료되었습니다. 확인 부탁드립니다.
