### ISSUE TITLE
Angular2 에서 사용하려고 하는데요

### ISSUE THREAD

**Issue by byunseonuk** [daumPostcode/QnA#347]
oncomplete 안에서 this를 사용해도 안되고 
angular는 document.getElementById를 못쓰는데 어떻게 값 바인딩 할 수 있나요

**Comment by daumPostcode** [comment]
@byunseonuk 
네 안녕하세요~

onComplete함수 내부의 구현사항은 오로지 개발자 분의 몫입니다.
우편번호 서비스 JS API의 역할은, 팝업창이나 iframe을 띄워서 검색을 하고, 결과 클릭시 oncomplete함수를 실행시키면서 인자로 데이터를 내리는 부분까지이며, 이후 데이터의 처리는 개발자분께서 프레임워크나 개발하시는 사이트의 구조에 맞게 적용하셔야 합니다.

해결책을 드리지 못해 죄송합니다.
