### ISSUE TITLE
영문주소 검색

### ISSUE THREAD

**Issue by nuri-jeong** [daumPostcode/QnA#351]
최초 주소 검색시 영문으로는 주소 검색이 안되는건 가요?

예) 서울시 양천구 목동서로 225 검색시 [목동서로 225] 검색 후 주소 선택
     [Mokdongdong-ro 225] 검색 후 주소 선택 이 가능한지 궁금합니다.

현재 제가 영어로 주소를 검색했을 때는 안되는데, 설정값을 변경하면 되는 부분인지 궁금합니다.

**Comment by daumPostcode** [comment]
@nuri-jeong 
네; 안녕하세요.

현재 검색엔진이 영문검색은 지원하고 있지 않아, 해당 사항은 지원해 드리기 어려울 것 같습니다.
도움을 드리지 못해 죄송합니다.
