### ISSUE TITLE
react-daum-postcode 리액트에서 사용시 에

### ISSUE THREAD

**Issue by dobdob2** [daumPostcode/QnA#352]
리액트 사용시 postcode 컴포넌트를 사용할시 다음과 같은 에러가 나옵니다

![image](https://user-images.githubusercontent.com/42020159/43713877-1b24bb8e-99b6-11e8-9a27-331e8c493f2e.png)

**Comment by daumPostcode** [comment]
@dobdob2 
네~ 안녕하세요~

react 컴포넌트의 경우에는 일반 개발자분께서 만들어서 배포하신 것인데요. 
그전에 stlog1의 경우에는 내부에서 로그를 보내는 도메인인데, 이 방식이 new Image()로 이미지객체를 만들어서 쓰는 방식입니다. 별다른 문제가 없어야 정상인데; 혹시 해당 stlog1만 오류가 발생하고, 이외 우편번호검색 서비스는 정상적으로 호출이 되실까요? 

제가 리엑트를 잘 몰라서, 이 부분은 확인해 보도록 하겠습니다.

**Comment by daumPostcode** [comment]
@dobdob2 

![2018-08-07 11 27 44](https://user-images.githubusercontent.com/20675065/43750791-fe77d14a-9a34-11e8-9be8-8dcba29cd13e.png)

react 테스트 페이지에서 위 샘플처럼 만들어서 작동시켜보니, 현재 정상동작합니다.
위 페이지는 기본이 https기반이라, spi.maps로 표시가 되지만, 이는 https proxy라 내부에서는 다시 stlog1 서버로 데이터를 쏘게 되어 있습니다.

대략 의심가는 것은 https환경에서 테스트 중이시거나 개발중이신데 우편번호 서비스를 http용으로 개발을 하셨거나,
두번째는 해당 이슈를 확인하셨을때 stlog1서버에 이상이 있었을 수도 있습니다. 대략적인 오류가 발생한 날짜와 시간대를 알려주시면 서버 오류가 언제 있었는지 확인이 가능할 것으로 보입니다.

추가로, 로그를 보내는 로직은 오류가 나더라도, 서비스가 멈추거나 하는 현상은 없으니, 큰 걱정은 안하셔도 될것 같아요~

테스트한 사이트 주소 : https://codesandbox.io/s/pk1ky23jqj

감사합니다.
