### ISSUE TITLE
주소검색이 안되네요.

### ISSUE THREAD

**Issue by blue4313** [daumPostcode/QnA#353]
충북 청주시 상당구 방서동232

Daum 우편번호 서비스 주소검색 창에서 해당 주소로 검색시 검색이 나오지 않네요.

그냥 다음사이트에서 주소검색하면 바로 나옵니다.

확인 부탁 드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@blue4313 
네~ 안녕하세요~

해당 이슈는 [FAQ1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 을 참고해 주시기 바랍니다.

현재 해당 주소는 행자부 도로명 시스템에서 검색이 안되며, 이 경우는 도로명 주소가 발급이 안된 케이스 입니다.
행자부 사이트에서 직접 발급 신청을 해주시기 바랍니다. FAQ1번을 읽어보시면 확인하실 수 있습니다.

이부분은 저희가 해드릴수 없는 부분이니 확인 바랍니다.
