### ISSUE TITLE
도로명코드에 관련하에 문의드립니다.

### ISSUE THREAD

**Issue by jtcha** [daumPostcode/QnA#354]
안녕하세요. 현재 다음주소 API를 사용하고 있습니다.

문의드릴것은 현재 행안부 api를 사용시 주소검색 결과에 도로명코드가 12자리로 출력되는데 

다음API 사용 시 7자리로 출력되는데 서로 다른 값인지 문의드립니다.

다음API 설명에 현재7자리 추후 7자리 이상으로 늘어날 수 있다고 명시되어있는데

행안부DB는 늘어난 것인데 서로 다른 값인지 혹은 아직 반영이 안된 것인지 반영 예정은 있는지 

문의드립니다. 

항상 유용하게 사용하고 있습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@jtcha 
네~ 안녕하세요~

도로명코드가 늘어날 수도 있다는 것은 추후 전국적으로 도로명 주소가 더 많이 생기고 하면 이때 자릿수가 변경될 수 있어서 그렇게 적어둔 것입니다.

7자리만 내리는 경우는 roadnameCode의 경우에는 딱 도로명 값에 대한 코드이며, 말씀하진 12자리로 이용하시려면 sigunguCode와 조합해서 쓰시면 됩니다.

sigunguCode + roadnamCode = 12자리 (의미  ex - 어느시 어느구에 있는 도로명)
과 같이 쓰실 수 있습니다.

감사합니다~

**Comment by daumPostcode** [comment]
추가로 행안부 도로명 코드 정보 사이트 첨부합니다.

http://www.juso.go.kr/info/RoadNameDataList.do?type=search&roadCd=&keyword=&city1=11&county1=680&town1=&searchType=0&extend=true

저희와 네이밍 규칙이 조금 달라서 그렇긴 한데 
행안부에서 도로명번호가 저희가 내리는 데이터상 roadnameCode와 같습니다. ~

이점 참고해 주세요~

**Comment by jtcha** [comment]
답변 감사드립니다. 
질문했던 내용 정확하게 해결되었습니다.
항상 빠른 답변해주셔서 감사드립니다~!
