### ISSUE TITLE
경상남도 창원시 마산회원구 3·15대로 주소 검색 값

### ISSUE THREAD

**Issue by snua10094** [daumPostcode/QnA#355]
행자부 자료 [경상남도 창원시 마산회원구 3·15대로] **가운뎃점**
다음 자료 [경남 창원시 마산회원구 3.15대로] **마침표**

행자부 자료가 '가운뎃점'으로 표시되어 있습니다.
매번 우체국에서 오류로 표시되는데
결과 값도 가운뎃점으로 수정 가능할까요?

**Comment by daumPostcode** [comment]
@snua10094 
안녕하세요!

데이터 담당자 분께 답변이 와서 답변드립니다.

해당 가운데 점의 경우 엔진쪽에서 해당 데이터를 저장할때 변환을 해서 저장을 한다고 합니다. 얼마전부터 한것은 아니고 2014년 이전부터 이렇게 저장이 되도록 정책이 결정되었다고 하네요.
해당 이슈는 엔진쪽 처리 문제, 사용자 입력문제 등에 따라 결정이 된것으로 보입니다.

현재로써는 소스 데이터 변경은 좀 어려울 것 같습니다.
변경을 원하시는 경우엔 저희가 내려주는 데이터를 입력하기 전에 onComplete함수 내에서 변환 처리를 하셔야 될것 같아요. 

도움을 드리지 못해 죄송합니다.
