### ISSUE TITLE
경기 안양시 동안구 시민대로327번길 55 주소의 값이 행안부와 다름.

### ISSUE THREAD

**Issue by mjchoi83** [daumPostcode/QnA#356]
경기 안양시 동안구 시민대로327번길 55 주소 검색시 

daum api
buildingCode: "4117310200107660002000001"
행안부
buildingCode: "4117310200107660002000002"
로 값이 서로 다름

행안부와 다음 서비스 사이에 주소 코드가 최신화 되어 있지 않은 것으로 추정 됨.

**Comment by daumPostcode** [comment]
@mjchoi83 
네~ 안녕하세요~

해당 이슈 확인하였고, 현재 데이터 담당자 분께 연락드렸습니다.
추후 답변이 오면 추가 댓글 드리도록 하겠습니다.

제보 감사드립니다.

**Comment by mjchoi83** [comment]
빠른 대응 감사 드립니다.
확인 결과 수정된 매핑정보로 정상 확인이 됩니다.

감사합니다.
