### ISSUE TITLE
GALAXY 7, 안드로이드 오레오 8.0 이상 iframe 오류

### ISSUE THREAD

**Issue by wdhv2007** [daumPostcode/QnA#357]
daum 우편번호 iframe을 이용하여 레이어 띄우기 사용중인데요 다른 기기에선 문제 없는데 갤럭시 7이상, 안드로이드 오레오 8.0 이상에선 iframe이 안되네여;;; 이거 원인을 알 수 있을까요?

**Comment by daumPostcode** [comment]
@wdhv2007 
현재 빌릴 수 있는 핸드폰이 
삼성 갤럭시  S9, Android 버전 8.0 에서
기본 크롬브라우저, Daum App 웹뷰에서 테스트 결과 정상 동작하고 있습니다.

혹시 갤럭시 7의 문제면 제가 빌릴 수 있을때 빌려서 바로 테스트해 보도록 하겠습니다.

이전에, HTTPS환경인데 HTTP API를 이용하신다던지,
PC 브라우저에 정상 동작하는지 (기본적으로 PC와 모바일 구분없이 동작해야합니다)

저희가 확인할 수 있는 사이트가 있다면 더 좋을 것 같습니다.
우선 앞서 말씀드린 것처럼 안되는 현상을 좀 더 구체적으로 적어주시면 감사하겠습니다.
