### ISSUE TITLE
응답결과로 pnu코드도 받을수 있을까요

### ISSUE THREAD

**Issue by yunjunseokzb** [daumPostcode/QnA#359]
안녕하세요. 다음 우편번호서비스를 잘 이용하고있습니다.

한 가지 필요한 기능이 있는데  응답결과 bcode처럼
pnu코드 (bcode + 산여부 + 지번코드)도 받을 수 있을까요?

이 기능이 있으면 정말 편할거 같습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@yunjunseokzb 
네~ 안녕하세요~

아쉽게도 해당 데이터는 현재로써는 내려드리기가 쉽지 않아 보입니다.
말씀하신 데이터 중에, 산여부에 대한 정보가, 현재 연관주소에는 들어가 있지 않습니다. 이는 데이터단의 문제라기 보다, 엔진에서 결과리스트를 만들때 추가해야 되는 것으로, 현 시점에서는 추가가 좀 어려울것 같아요;

추후 논의는 해볼 수 있을 수 있지만; 현재로써는 좀 어려울것 같아요. 
해당 이슈는 개선사항이라고 마크해 두도록 하겠습니다.

감사합니다.
