### ISSUE TITLE
IE9 강제 호환모드에서 IE브라우저가 프리징

### ISSUE THREAD

**Issue by dracokr** [daumPostcode/QnA#36]
`<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">`
태그를 사용한 페이지에서 2개이상의 우편번호 검색 버튼을 넣었을 경우,
첫번째 검색에서는 괜찮지만, 두번째 검색 버튼을 누르자 프리징되었다는 고객 문의를 6개월간 30여건 이상 받았습니다.

OS는 윈도우7,8,10등 다양하여 공통되지 않았으나 IE10이나 IE11을 사용했다는 점은 공통되었습니다.
모든 경우 두번째로 버튼을 누르자(첫번째를 누르고 두번째를 누르거나, 두번째를 누르고 첫번째를 누르거나, 첫번째 버튼을 두번 사용하거나 등등) 발생했고
우편번호 검색하는 흰창이 뜨면서 내용이 로드되지 않고, IE가 멈추어서 강제종료해야 했다고 합니다.
관리자인 저는 재현을 하지 못하였으나 직원중 한명의 컴퓨터에서 재현을 성공했으며, 따라서 아무래도 특정 액티브X이 설치되어 있다든지 조건이 있는 IE에서 발생하는 듯 합니다.
EmulateIE9를 빼버린 페이지에서는 한달간 문제가 보고되지 않았고, 유지한 페이지에서는 계속 같은 문제가 보고되었습니다.

우편번호 서비스를 이용한 방식은 iframe을 이용하여 레이어 띄우기, iframe을 이용하여 페이지에 끼워 넣기 였습니다. iframe 로딩하는 방식인데도 부모페이지의 호환모드가 영향을 끼친다는 점이 흥미롭습니다.

발생한 URL은 http://eleparts.co.kr/front/member_join.php 이며, 지금은 EmulateIE9를 빼버린 상태입니다.

**Comment by daumPostcode** [comment]
@dracokr 
넵~ 안녕하세요~
현재 저희에게 처음 보고된 오류로 확인됩니다. 말씀해 주신 대로, Windows, IE 버전별로 테스트 후, 말씀드리도록 할께요. 일단은, 오류가 발생하지 않는 EmulateIE9 코드를 제거한 상태로 서비스 제공이 가능하시다면, 당분간은 이렇게 부탁드리구요. 원인에 따라 해결책이 안나오는 경우도 있는데, 이부분은 확인 후에 말씀드리도록 하겠습니다;;

잠시만 기다려 주세요.

**Comment by daumPostcode** [comment]
@dracokr 
음... 일단 결론부터 말씀드리면 아직 해결책을 찾지 못하였습니다.
dracokr님께서 말씀하신 것처럼 저희또한 재현이 되지 않네요,, 회사 컴퓨터가 모두 맥이라서, 윈도우는 가상머신을 이용하는데요, 말씀하신 것처럼 액티브액스나 이런것들을 설치하지 않으니 재현이 안되는 것일 수도 있을 것 같아요;;

이부분은 확인이 조금 걸릴 것 같구요. 정확한 일정은 확인이 어렵습니다 ㅜ.ㅜ

만약 IE=EmulateIE9 속성을 넣으셔야 한다면, 이 속성을 넣고 embed가 아닌 open()을 이용하여 팝업으로 띄울때도 같은 이슈가 발생하는지 확인 부탁드립니다. 만약 발생하지 않다면, 번거로우시겠지만 UA를 체크하셔서 PC환경일땐 open으로, 모바일 환경에선 embed로 분기하시는 것도 하나의 해결책이니 참고 부탁드려요;;

아무튼 이것저것 참고하여 한번 알아보도록 하겠습니다. (원인을 못 밝힐 수도 있는 점 양해 부탁드립니다 ㅜ.ㅜ)
