### ISSUE TITLE
'경기도 성남시 수정구 위례대로' 전체가 검색되지 않습니다.

### ISSUE THREAD

**Issue by susemeee** [daumPostcode/QnA#360]
![image](https://user-images.githubusercontent.com/4835442/44776785-d83a5f80-abb3-11e8-83c9-1554f346690e.png)

첨부한 '위례대로 83' 이외의 위례대로 하위의 전체 주소가 검색되지 않는 현상을 발견하였습니다.
감사합니다.

**Comment by susemeee** [comment]
> 대부분의 모든 주소를 1일 업데이트 하지만, 몇몇 업데이트가 불가능한 주소가 있습니다. 행정자치부 도로명주소 검색시스템에서 검색은 되나, 저희 우편번호시스템에서는 검색이 안되는 경우가 있는데요. 이는 국가보안시설(주요 기관, 발전소 등)로 지정된 곳은 저희에게 데이터를 내려주지 않아 현재 업데이트가 불가능합니다. 해당 주소들은 도로명주소 검색시스템에서 검색시 아래와 같이 지도 마커가 없습니다. 

이 케이스임을 확인하였습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@susemeee 
안녕하세요~.
경기도 성남시 수정구 위례대로의 경우에는 검색결과가 1개만 존재하는데;
존재하는 주소는 "경기도 성남시 수정구 위례대로 83" 입니다. 다만 이 주소는 현재 보안주소로써; 정책상 노출을 할 수가 없는 상태입니다. 자세한 사항은 [FAQ1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 을 참고해 주시기 바랍니다.

행자부 시스템에서 검색을 해보시면 결과목록에 지도마크가 없습니다. 이러한 주소의 경우에는 현재 저희쪽 시스템에서는 정책상 노출이 불가능합니다.

다만 주소이기 때문에 해당 이슈는 정책팀에 문의해 보도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@susemeee 

안녕하세요~

보안주소의 경우 현재 시스템상 저희 우편번호 서비스에만 적용하는 것은 무리가 있다고 판단되어 공유 드립니다.
현재 행자부에서는 자사에 데이터를 내려줄때 보안주소의 경우 좌표정보를 빼고 내려주며, 이 주소는 지도서비스에 노출을 금지하는 것으로 되어 있습니다. 
다만, 현재 지도서비스에서 이러한 주소가 검색되는 것은 주소가 검색되는게 아닌 장소CP사에 제공된 장소가 검색되는 것입니다. 그래서 행자부 정책과 상관없이 뭔가 앞뒤가 안맞고 모호하지만 일단 주소정보 자체는 표시를 하면 안되므로 엔진 색인에서 제외 시킵니다.

현재 시스템 구조상 카카오내의 대다수의 서비스들이 이용하는 검색엔진은 한가지틑 타고 있으며 이는 저희 우편번호 서비스도 마찬가지며, 해당 몇몇 정보들이 빠진 보안주소를 추가 노출해야될때, 각 서비스 별로 가지는 사이드이펙트가  생각외로 커서 지금은 진행을 하지 않는 것으로 결정하였습니다.

그래서 어떻게 보면 제일 좋은 해결책인 행자부 측에, 보안주소의 노출과 관련한 문의를 넣어 보려고 하고 있습니다.

이부분 확인 부탁드리며, 지원을 해드리지 못한점 죄송하게 생각합니다.
감사합니다.
