### ISSUE TITLE
js 파일 받을 수 있나요?

### ISSUE THREAD

**Issue by wdhv2007** [daumPostcode/QnA#361]
cdn으로 script에 선언하는 것이 아닌 파일을 프로젝트에 내장하고 싶은데 혹시 라이브러리를 받을 수 있는 곳이 있나요?

**Comment by daumPostcode** [comment]
@wdhv2007 
네~ 안녕하세요~

현재 저희 스크립트를 받아서 이용하시는 것은 공식적으로 지원하지 않습니다.
기본적으로 웹서비스이기 때문에 브라우저를 통해 파일을 받으면 이용하실 수도 있으나, 이와 같은 방식은 공식적으로 지원하진 않습니다.

받을 수 있는 곳은 따로 존재하지 않으며, 스크립트를 다운받아 프로젝트에 내장을 하신다 하시더라도, 기본적인 검색+선택한 결과를 데이터를 내리는 기능은 로컬파일을 실행하는 것으로는 불가능 하고, 웹서비스여야 동작을 하는점 참고부탁드립니다. FAQ를 한번 참고해 보시면 좋을것 같아요~ 

감사합니다.
