### ISSUE TITLE
모바일에서 에러가 나요

### ISSUE THREAD

**Issue by handgoldking** [daumPostcode/QnA#363]
' 송파대로49길 52 ' 주소가 
PC에서는 잘 되는데 모바일에서는 
zip code 에러 메세지가 뜹니다.

**Comment by daumPostcode** [comment]
@handgoldking 
네~ 안녕하세요~

현재 저희 시스템은 모바일이나 PC나 모두 동일한 로직을 쓰며, 서로 데이터가 다르지 않습니다.
현재 저희가 내려주는 데이터에는 zip code라는 정보는 없는데요.

postcode/postcode1/postcode2 정보를 말씀하시는 걸까요? 해당 데이터는 말씀하신 주소에는 비어있는 데이터로 나옵니다. 

아마 오류가 나는 것은 PC브라우저와 모바일브라우저의 에러체크가 달라서 발생하는것 같아요. 정확히 어떤 오류가 나는지 스샷이나, 제가 접근할 수 있는 URL, 그리고 어떤 모바일인지(아이폰인지 안드로이드인지 버전은 무엇인지 어떤 브라우저인지) 등의 정보가 필요합니다.

한번 확인해 주세요.

**Comment by handgoldking** [comment]
![kakaotalk_20180904_085106040](https://user-images.githubusercontent.com/17694176/45031431-c6f8c380-b089-11e8-9226-5201f26dd308.jpg)


http://www.ineltree.co.kr/shop/main/index.php
사이트 주소이구요. 안드로이드, 아이폰 모두 에러가 납니다.
혹시 가능하실지 모르겠는데
제품을 아무거나 선택하여 결제하고
주소를 '  송파대로49길 52  ' 를 입력하여 결제하면
위와 같은 코드에러가 뜹니다.
꼭 확인 부탁드릴게요~
