### ISSUE TITLE
안드로이드 9.0 파이버전에서 스크립트 오류 납니다.

### ISSUE THREAD

**Issue by jihun83x** [daumPostcode/QnA#366]
아이프레임으로 다음지도 api 호출하는데 daum.postcode.load 시 
180619.js 파일에서 스크립트 오류 발생하여 화면이 출력되지 않습니다.

다른 안드로이드 버전에서는 정상작동 확인하였는데, 이 부분에 대해 확인부탁드립니다.

![_ _ 9 _](https://user-images.githubusercontent.com/42985860/45136121-a5a8ec00-b1dd-11e8-89d9-b1d5a0c96e6e.png)

**Comment by jihun83x** [comment]
안드로이드 기기에서 usb 꽂아 확인해본 로그입니다.
구글 레퍼런스 폰인데 9.0 버전이네요.
180619.js 에서 걸리는 것으로 보이는데 아직 상용화된 버전은 아니지만 추후 상용화 풀릴 시 이슈가 있을 것 같아 문의드렸습니다.

**Comment by daumPostcode** [comment]
@jihun83x 
아 그렇군요. 안드폰을 꽂아서 확인해 보셨다면,
올려주신 스샷의 네트워크 탭이 아닌 콘솔쪽 텝도 확인 가능하실텐데 콘솔쪽 로그가 필요해 보입니다.

**Comment by jihun83x** [comment]
음, 저는 웹개발자라 안드로이드 개발자분께 다시 요청드려야하는데...실제 9.0 버전 폰에서 테스트해보시는게 불가능하신가요..?

**Comment by daumPostcode** [comment]
@jihun83x 
프로세스가 좀 있어서;;; 저도 앱개발자가 아니라;; 장비대여가 쉽진 않아서요 ㅎㅎ;
로그만 잘 보인다면 왠만한 오류는 로그보고 제가 체크해 볼 수 있거든요; ㅎㅎ

넵 그러면 제가 대여요청해서 확인해 보도록 하겠습니다.

일단은 안드로이드 픽셀XL 9.0 버전으로 체크해보겠습니다 (단말이 이거밖에 없네욤;)

**Comment by jihun83x** [comment]
앗, 바쁘신 와중에 감사드립니다.

**Comment by daumPostcode** [comment]
@jihun83x 
안녕하세요~

지금 확인해보니;; 음;; 딱히 문제가 안보입니다.
![2018-09-06 4 54 16](https://user-images.githubusercontent.com/20675065/45143479-6a66e700-b1f6-11e8-91e2-9c8845b5a408.png)
![img_1084](https://user-images.githubusercontent.com/20675065/45143480-6a66e700-b1f6-11e8-81a3-e5e45101f526.JPG)
![img_1083](https://user-images.githubusercontent.com/20675065/45143481-6aff7d80-b1f6-11e8-8961-7044a52c152e.JPG)

위 스샷들은 제가 테스트하는 페이지, 맨처음 질문 주신것처럼 autoload=false로 동적로딩 으로 테스트 하였으며,
레이어 모드를 띄웠을때의 상황입니다. 현재 정상적으로 180619.js 파일이 로딩되었으며, 화면이 잘리긴 하지만 레이어도 노출되었습니다. 물론 팝업도 정상적으로 열립니다.

크롬 버전은 66.0 안드로이드 9.0, 픽셀 XL 입니다.

의심가는 것은, 일반 크롬이 아닌 웹뷰 환경이라던지, http/https 프로토콜이 맞지 않던지 하는 문제점이 있을 것 같습니다. 
올려주신 스샷에서는 코어스크립트(180619)가 cancel되는걸로 봐서, 브라우저(또는 웹뷰) 모듈이 연결을 끊어버리는 현상이 있는 것으로 보이는데요; 동적로딩 같은 경우에는 script태그를 동적으로 만들어서 document.getElementsByTagName('head')[0] 부분에 append시키는 것으로 동작을 하게 됩니다. 혹시 웹뷰라면 동적으로 DOM을 생성해서 넣는 부분을 무언가가 블락을 하거나, 문제가 있는지 확인해 보시면 좋을 것 같습니다.
(jihun83x 님께서 직접 크롬으로 디버깅 해보실때 잘되시면 웹뷰 문제일 가능성이 큽니다.)

웹뷰의 경우에는 개발방법이 개발사마다 모두 다른 관계로 제가 테스트하여 확인을 해드리기 어려운점 말씀드려요;;;

추가로 오류메세지가 필요한 이유는 오류가 발생한 부분은 코드레벨에서의 라인과 column 번호가 나오기 때문에 제가 역추적이 가능해서 그렇습니다.

**Comment by jihun83x** [comment]
답변 감사드립니다. 웹뷰 쪽 문제일 가능성이 크겟네요. 프로토콜 문제는 분기 태워놔서 문제가 없을 것 같네요~

**Comment by daumPostcode** [comment]
@jihun83x 
네. ㅎㅎ 부디 잘 해결 되기를 바랍니다.

그럼 즐거운 금요일 되세요~
