### ISSUE TITLE
기흥역로 검색시 누락건이 있습니다

### ISSUE THREAD

**Issue by airjongman** [daumPostcode/QnA#367]
검색어 : 기흥역로  

다음 하고  http://www.juso.go.kr 하고 차이가 있습니다.

http://www.juso.go.kr 에서는 총 6건이 나오는데 다음에서는 3건만 나옵니다.

수정요청드립니다.

**Comment by daumPostcode** [comment]
@airjongman 
안녕하세요~

해당 기능은 저희 엔진 특성으로, 행자부 사이트에서 검색해 보시면; 기흥역로의 경우 3건이 정상입니다.
나머지 3건은 기흥역로58번길 로; 이름만 비슷하지 코드가 다른 다른 도로명입니다.

해당기능은 검색엔진 정책에 관련된 부분이라 쉽게 변경이 어려운점 참고 부탁드립니다.
