### ISSUE TITLE
주소를 선택하면 oncomplete가 call 되지 않습니다. (error log 첨부)

### ISSUE THREAD

**Issue by Ikanny** [daumPostcode/QnA#369]
주소를 검색하고 선택해도 oncomplete가 call 되지 않습니다.

```javascript
[Error] SyntaxError: The string did not match the expected pattern.
	postMessage (service.v2.min.js:4:15248)
	b (service.v2.min.js:4:15248)
	c (service.v2.min.js:4:15330)
	(익명 함수) (service.v2.min.js:5:2696)
```

cordova를 통해서 hybrid app을 개발 하고 있습니다. 테스트는 iOS11 장비로 했습니다.

**Comment by Ikanny** [comment]
제 생각엔 cordova에서 application을 실행하면 origin이 null로 설정되기 때문에 `window.postMessage(...)`에서 exception을 rasing하는거 같습니다. 혹시 해결 방안이 있을까요?

**Comment by daumPostcode** [comment]
@Ikanny 
네~ 안녕하세요~

저희 서비스의 경우 웹환경에 맞춰서 제작된 프로그램이며,
FAQ에도 적혀 있듯이 웹뷰나 웹앱에서 사용할때도 기존 브라우저에서 동작시키는 것처럼 이용하셔야 합니다.
현재 postMessage에서는 도메인 값을 알 수 없으면 데이터 전달이 어렵습니다.

웹앱안에 내장을 시켜야 되는 경우에는 저희 API보다는 행자부사이트에서 직접 REST API를 요청하여 이용하시는게 개발에 더 편하실 거라 생각이 되네요.

**Comment by Ikanny** [comment]
네 답변 감사드립니다 :)
