### ISSUE TITLE
시군구까지 선택할수 있는 api 는 따로 없나요?

### ISSUE THREAD

**Issue by neoniceman** [daumPostcode/QnA#37]
현재 주소 API 는 잘사용하고 있습니다.

업무 요건상 시군구까지 콤보로 선택가능해야 하는데요. 뎁스형태로 순차적으로 주소 정보를
받을수 있는 방법은 없을까요?

**Comment by daumPostcode** [comment]
@neoniceman 
네~ 안녕하세요~

질문이 제가 이해한게 맞는지 확실하게 몰라서 여러케이스로 적을께요;;

1.
저희 우편번호서비스(API)의 경우에는 따로 "주소API"라고 부르지는 않습니다. 혹시 사용하시는 API가 http://developers.daum.net/services/apis/local/geo/coord2detailaddr <- 여기에서 제공하는 좌표->주소 변환 API인가요? 그런 것이면 http://cafe.daum.net/daumdna <- 이 dna 카페에 질문을 남겨주시면 될것 같아요~

2.
저희 우편번호서비스를 말씀하시는거라면, 말씀하시는 시/군/구를 선택할 수 있게끔 하는 UI를 제공하는 버전은 없습니다. 시/군/구 선택은 도로명주소가 생기면서 검색결과를 통제하기 위해 어쩔 수 없이 생긴 것이라서, 저흰 이것을 검색 키워드를 기반으로 검색엔진으로 푸는 것을 목표로 서비스를 개발/유지하고 있습니다.

3.
저희 우편번호 서비스에서 주소를 검색하고 선택할 경우, 내려가는 데이터에 대한 문의라면, oncomplete의 인자로 들어가는 데이터 객체에서 sido/sigungu 데이터가 있으니 이를 참고하시면 되실 듯합니다. 해당 내용은 저희 가이드 페이지의 [속성](http://postcode.map.daum.net/guide#attributes)(http://postcode.map.daum.net/guide#attributes) 부분을 참고하시면 될 것 같아요~

이외 추가적인 질문이 있으시면 언제든 댓글 부탁드립니다~

감사합니다.
