### ISSUE TITLE
도로명 주소로 검색 후 지와 번을 따로 분리가 가능한지요..

### ISSUE THREAD

**Issue by leekh4971** [daumPostcode/QnA#370]
도로명 주소로 검색 후 데이터 항목에 번과 지 또는 번지를 따로 분리하여 제공이 가능한지 여쭤봅니다.

**Comment by daumPostcode** [comment]
@leekh4971 
네~ 안녕하세요~

아뇨 현재로써는 주소의 모든 부분을 분리하여 제공하진 않습니다.
분리하여 특정 부분이 필요하신 경우, address(jibunAddress, roadAddress) 부분을 공백으로 분리하여 직접 분리하여 이용하셔야 합니다.
