### ISSUE TITLE
화성시 활초리와 화성시 오산동의 구 우편번호가 같습니다.

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#371]
화성시 활초리와 화성시 오산동의 구우편번호가 둘 다 445-150 으로 조회됩니다.
행안부 DB에는 오산동에 대한 우편번호가 없어서 혼란스러운데요,
구 우편번호는 어떻게 가져오는지 문의드립니다.

**Comment by daumPostcode** [comment]
@suseokpark 
안녕하세요~

구우편번호의 경우엔
도로명 주소 이전, 그리고 도로명주소의 기초구역번호와 구우편번호가 같이 사용될때 있었던 데이터 입니다. 실제 각 주소들이 행자부에서 새로 업데이트 되어 넘어오게 되면, 구우편번호가 빠지게 되어 점차 구우편번호는 사라지고 기초구역번호만 남게 됩니다.

아마 말씀하신 주소는 기초구역번호와 구우편번호가 같이 사용될때 업데이트된 주소이고 그 이후에 업데이트가 안되서 남아 있는 것 같습니다.

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 일단 말씀드릴 수 있는 사항은 6자리 구 우편번호는 업데이트가 안되며(우정사업본부에서도 업데이트를 안합니다.) 위에 적은 것처럼, 5자리 새우편번호(기초구역번호)와 6자리 구우편번호가 같이 있는 경우는 이전 과도기 시절에 데이터가 내려왔기 때문에 들어가 있는 것이며, 만약 말씀하신 주소의 도로명 주소가 업데이트가 된다면 구우편번호(6자리)는 사라지게 됩니다.
만약 6자리 구우편번호를 쓰고 계신다면; 5자리로 바꿔주시는게 좋습니다.
이는 예전에 제가 답변단 https://github.com/daumPostcode/QnA/issues/6 이 이슈에 있는 우정국 공지사항을 참고해 주시기 바랍니다.

일단 문의 주신 주소에 대해서는 구우편번호의 매핑이 잘못되어 있다면 삭제될 수가 있으며, 이상 현상에 대해서는 데이터 담당자 분께 문의하도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@suseokpark 
안녕하세요~

말씀 하신 주소의 구 우편번호가 삭제되어 답변드립니다.
앞서 말씀드린 것처럼 구우편번호는 현재 업데이트가 안되어 점차 삭제될 예정이니, 이점 참고 부탁드립니다. 

감사합니다.

**Comment by suseokpark** [comment]
빠르게 처리해주셔서 감사합니다.

**Comment by suseokpark** [comment]
![image](https://user-images.githubusercontent.com/39077176/46137330-586fe580-c284-11e8-8075-854ef8f8e5bd.png)
아직 API 검색하는 쪽에는 여전히 445-150이 검색이 됩니다.
혹시 업데이트 주기가 있을까요?

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 안녕하세요~

아 처음 말씀하신 주소에 대해서만 처리가 된것 같네요;;
그런데 데이터상 해당 지번의 모든 구우편번호를 지우는 것은 여러 부수효과 때문에 한번에 지우는 것은 어려울 것 같습니다.

일단 질문 주신 내용에 답변을 드리면
구우편번호는 업데이트가 되지 않습니다. 현재 이슈처럼 요청시에만 임의 삭제를 진행하며
자동으로 삭제가 되는 주소는 행자부에서 새로운 데이터가 내려올때 자동으로 삭제가 되서 내려오기 때문에 삭제가 되는 것입니다.
행자부에서의 도로명주소 업데이트 주기는 1일 업데이트이며, 행자부에서 업데이트가 되면, 저희측엔 익일 반영이 됩니다.

추가적으로 저번에 구우편번호 문제로 말씀해주신 "경기 화성시 동부대로 955" 이주소의 경우, 현재 사라졌으며, 이처럼 도로명 주소의 경우 매일 매일 지속 업데이트가 되기 때문에, suseokpark님의 시스템에서 구우편번호를 사용하신다면 빠른 시일안에 새우편번호(기초구역번호) 기반으로 바꾸시는 것을 추천드립니다.

**Comment by suseokpark** [comment]
확인 감사합니다.
번거로우시겠지만 혹시 아래 조회조건으로 검색되는 지역의 구우편번호를 삭제해주실 수 있을까요?

```
445-150 경기 화성시 남양읍 활초리
```

감사합니다.

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 안녕하세요~

해당 주소에 대해서 데이터 담당자분께 삭제 요청을 드렸으며, 최종 결과는 데이터 담당자분께서 확인하시고 조치를 취해주실것 같습니다. 삭제여부는 답변이 오면 말씀드릴께요~

추가로, 현재 구우편번호를 검색리스트에서 모두 안보이게 할 수 있는 옵션을 추가 개발중에 있고, 이 기능은 다음주에 업데이트가 될 예정입니다.

감사합니다.

**Comment by daumPostcode** [comment]
@suseokpark 
데이터 삭제에는 시간이 걸리는 만큼, 구 우편번호 노출을 제어할 수 있는 옵션이 추가되었습니다.

https://github.com/daumPostcode/QnA/blob/master/PATCHNOTE.md#2018-10-2
옵션명은 zonecodeOnly로 기본값은 false입니다. 생성자 옵션으로 zoncodeOnly:true 로 셋팅하면 구 우편번호가 모두 사라지니 확인 부탁드립니다.

테스트전 브라우저 캐시만 한번 삭제 부탁드려요~~

감사합니다.
