### ISSUE TITLE
[검색목록에 없음] 경기도 성남시 수정구 위례대로 83

### ISSUE THREAD

**Issue by Kaintino** [daumPostcode/QnA#372]
경기도 성남시 수정구 위례대로 83 (구주소 : 경기 성남시 수정구 창곡동 356-1)
우편번호 검색시 나오지 않는 주소입니다.
행안부 도로명주소 검색에는 나오고 있습니다.
확인 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@Kaintino 
[FAQ1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)

참고 부탁드립니다. 

위와 같은 주소는 현재 내부에서 논의 진행 중인 사항입니다(엔진과 데이터단을 비롯하여 각 서비스들과 엮여 있어서요;)
아직 결정된 부분이 없어 확답을 못드리는점 양해 부탁드립니다.

**Comment by Kaintino** [comment]
음... 저희는 취업포털사이트 인데 사실 위 주소는 다음커리어넷(다음이죠;;;) 주소입니다.
다음은 공고 등록이 불가능한 상황이 되는거네요 ;ㅁ;...

**Comment by daumPostcode** [comment]
@Kaintino 
네.
현재로써는 저희 시스템에서는 보이게 하는 방법이 없어서 죄송할 따름입니다.
이런 문의는 이전부터 종종 있었는데; 워낙 주소API자체는 오픈API를 비롯하여 여러군데 물려 있어서 정책을 다듬는데 시간이 좀 걸리네요;;

**Comment by daumPostcode** [comment]
@Kaintino 
안녕하세요~

해당 주소의 경우 현재 시스템상 저희 우편번호 서비스에만 적용하는 것은 무리가 있다고 판단되어 공유 드립니다.
현재 행자부에서는 자사에 데이터를 내려줄때 보안주소의 경우 좌표정보를 빼고 내려주며, 이 주소는 지도서비스에 노출을 금지하는 것으로 되어 있습니다. 
다만, 현재 지도서비스에서 이러한 주소가 검색되는 것은 주소가 검색되는게 아닌 장소CP사에 제공된 장소가 검색되는 것입니다. 그래서 행자부 정책과 상관없이 뭔가 앞뒤가 안맞고 모호하지만 일단 주소정보 자체는 표시를 하면 안되므로 엔진 색인에서 제외 시킵니다.

현재 시스템 구조상 카카오내의 대다수의 서비스들이 이용하는 검색엔진은 한가지틑 타고 있으며 이는 저희 우편번호 서비스도 마찬가지며, 해당 몇몇 정보들이 빠진 보안주소를 추가 노출해야될때, 각 서비스 별로 가지는 사이드이펙트가  생각외로 커서 지금은 진행을 하지 않는 것으로 결정하였습니다.

그래서 어떻게 보면 제일 좋은 해결책인 행자부 측에, 보안주소의 노출과 관련한 문의를 넣어 보려고 하고 있습니다.

이부분 확인 부탁드리며, 지원을 해드리지 못한점 죄송하게 생각합니다.
감사합니다.
