### ISSUE TITLE
지번은 있는데 도로명 주소는 없는 경우도 있나요?

### ISSUE THREAD

**Issue by myunghoonhan** [daumPostcode/QnA#373]
만약 지번주소는 존재하되 도로명이 없는 경우라면 화면에서 어떻게 출력되나요? autoMapping 또한 null 값으로 리턴 될 수도 있나요?

**Comment by daumPostcode** [comment]
@myunghoonhan 
네~ 안녕하세요~

지번주소는 존재하되 도로명이 없는 주소는 저희 시스템에서 검색이 되지 않습니다.
저희는 도로명주소 검색 시스템이며, 도로명주소가 발급되지 않은 주소는 노출이 되지 않는 점 참고부탁드립니다.

**Comment by daumPostcode** [comment]
@myunghoonhan 
안녕하세요~
아뇨 당시 해당 옵션을 만들때, 두개의 액션의 경우 선택버튼은 다르나, 의미는 같다고 판단하여 구분값을 주지 않았습니다.
지금까지 요청이 없어서 추가할 생각을 못하고 있었는데, 지금 확인해보니 개발사 측에서 해당 상태변수로 가이드문구 같은 것을 제공해 줄 수 있겠다는 생각이 드네요;

해당 옵션의 경우엔 빠르면 목요일 정도에 배포가 되어 나갈 예정입니다.

의견 감사드립니다.

**Comment by daumPostcode** [comment]
@myunghoonhan 
안녕하세요~
금일 13시 28분

내려가는 데이터에 noSelected라는 변수로 Y/N 값이 내려가도록 추가되었습니다.
해당 변수는 "XX주소 선택안함" 을 선택했을때만 Y값이 내려갑니다.

감사합니다.
