### ISSUE TITLE
[도로명 주소 누락] 창원시 성산구 공단로 67

### ISSUE THREAD

**Issue by junfe97** [daumPostcode/QnA#375]
"창원시 성산구 공단로 67" 주소에 대해서 행정안전부에는 등록되어 있는데 daum 주소에서 조회가 되지 않아 엄청 불편합니다. 확인 부탁드리겠습니다.

**Comment by daumPostcode** [comment]
@junfe97 
네~ 안녕하세요.

해당 주소의 경우 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)에 있는 내용에 해당하는 주소로써, 현재 저희 시스템상 데이터를 내려드릴 수 없는점 참고부탁드립니다.

현재 행자부측에서 저희쪽에 데이터를 내려줄때 해당 주소의 경우에는 보안주소라고 지도에 노출을 금지시키고 있습니다.
또한 저희 시스템에서 사용하는 주소데이터는 저희 시스템에 최적화된 데이터가 아닌 전사에서 사용하는 데이터로써, 최근에 해당 데이터에 대한 노출을 논의했었는데요. 여러 이해관계가 얽혀 있어서 현재로써는 저희 서비스만을 위해서 새롭게 데이터와 엔진을 수정하는게 어려운 상황입니다.

그래서 현재로써는 해당 데이터를 내려드릴 수 없는점 양해 부탁드립니다.
대한민국에 존재하는 모든 주소정보를 얻으실려면
행정자치부의 개발자 API를 통하거나 [오픈소스 도로명주소 검색 API - Postcodify](https://www.poesis.org/postcodify/)를 이용하시는게 좋아보입니다.

불편을 드려 죄송합니다.
