### ISSUE TITLE
X, Y 좌표로 우편번호 검색을 통한 결과정보를 받는 API가 있을까요?

### ISSUE THREAD

**Issue by leekh4971** [daumPostcode/QnA#376]
우편번호 서비스를 이용하요 XY좌표 정보를 받습니다. 좌표를 변경한 경우 변경된 XY 좌표를 이용하여

기존의 우편번호 결과정보(주소, 건물명 등)를 받을수있을까요?

**Comment by daumPostcode** [comment]
@leekh4971 
안녕하세요~

현재 좌표를 통해 주소정보를 받는 API는 저희 API가 아닌 카카오디벨로퍼스에서 제공하는 REST API는 존재합니다.
https://developers.kakao.com/docs/restapi/local#%EC%A3%BC%EC%86%8C-%EB%B3%80%ED%99%98

이외 현재 우편번호서비스에서는 좌표로 검색을 하는 기능은 없습니다.
