### ISSUE TITLE
roadAddressEnglish , autoRoadAddressEnglish 차이점 , 사용 가이드 요청

### ISSUE THREAD

**Issue by alabama3p** [daumPostcode/QnA#377]
안녕하세요. 

주소를 아래 처럼 입력 하고, 지번을 선택 했을 경우, 

전북 익산시 인화동1가 17-2

리턴 되는 데이터 중에 roadAddressEnglish , autoRoadAddressEnglish  가 있는데, 보통 다른 주소는 roadAddressEnglish에 value 가 있으나, 위의 해당 주소에는 roadAddressEnglish에 값이 없고, autoRoadAddressEnglish 에 값이 있는 현상이 있습니다. 

두가지 field 의 차이점과, 현재 저희 사이트 로직은 무조건 roadAddressEnglish 을 쓰도록 되어 있는데, roadAddressEnglish 이 빈값이 경우, autoRoadAddressEnglish  을 쓰도록 수정하면 될지도 가이드 부탁 드립니다.

**Comment by daumPostcode** [comment]
@alabama3p 
네~ 안녕하세요~
보통 주소를 검색하면 쿼리에 따라 도로명주소 우선으로 정렬이 되지만, 명확한 지번주소의 경우엔 지번주소 우선으로 정렬이 되어 데이터가 내려옵니다.
말씀하신 주소쿼리로 검색을 하면, 메인 주소가 "지번", 연관주소가 "도로명"으로 나오고 있으며,
해당 주소의 경우 메인주소와 연관주소가 1:1이 아닌 1:N구조입니다. 이때 autoRoadAddress(English)가 활성화 될 수 있습니다. (지번주소를 선택하거나, 연관주소를 펼친 후의 도로명주소 선택안함을 선택했을때)

해당 옵션의 추가 배경은 연관주소를 펼쳤을때의 "선택안함" 때문에 생겨났으면 이에 대한 설명은 [가이드 페이지 속성 부분의 데이터 스펙 설명 아래](https://spi.maps.daum.net/postcode/guidessl#attributes)에 기술되어 있습니다.
또한 [FAQ16](https://github.com/daumPostcode/QnA#16-%EC%82%AC%EC%9A%A9%EC%9E%90%EA%B0%80-%EC%A7%80%EB%B2%88%EB%8F%84%EB%A1%9C%EB%AA%85-%EC%A4%91-%EC%96%B4%EB%96%A4-%EA%B2%83%EC%9D%84-%EC%84%A0%ED%83%9D%ED%95%98%EB%8D%94%EB%9D%BC%EB%8F%84-%EB%AC%B4%EC%A1%B0%EA%B1%B4-%EB%8F%84%EB%A1%9C%EB%AA%85-%EC%A3%BC%EC%86%8C%EB%A7%8C-%EC%9D%B4%EC%9A%A9%ED%95%98%EA%B3%A0-%EC%8B%B6%EC%9D%80%EB%8D%B0-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC%EB%90%98%EB%82%98%EC%9A%94) FAQ17번을 참고해 보셔도 좋을 것 같습니다.

그리고 말씀하신 방법처럼 roadAddressEnglish를 쓰고 없으면 autoRoadAddressEnglish를 쓰셔도 괜찮습니다. 이 반대로 해도 무방하구요. 이외 userSelectedType, noSelected와 같은 상태변수도 있으니 확인하시고 적절히 이용하시면 좋을것 같습니다.

추가 문의가 있으시면 언제든 이슈 주세요~
