### ISSUE TITLE
경기 하남시 초일로 78 주소 buildingCode 상이의 건

### ISSUE THREAD

**Issue by mjchoi83** [daumPostcode/QnA#378]
경기 하남시 초일로 78 주소 검색시
daum api
buildingCode: "4145012200200640002010605"
행안부
buildingCode: "4145012200200640002018864"
로 값이 서로 다릅니다.
확인 및 조치 부탁 드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@mjchoi83 
안녕하세요~

해당 이슈 처리가 완료되어 공유 드립니다.

처리가 늦어진 점 죄송합니다.
