### ISSUE TITLE
주소가 없음(충남 아산시 풍기동 203-1)

### ISSUE THREAD

**Issue by GUMP-JAEWOO** [daumPostcode/QnA#38]
충남 아산시 풍기동 203-1
위 주소가 검색이 안됩니다.

![snap1926](https://cloud.githubusercontent.com/assets/22927755/19505808/bd6f00ea-9600-11e6-9d09-3816369ab7e5.jpg)
![snap1927](https://cloud.githubusercontent.com/assets/22927755/19505807/bd6ae0a0-9600-11e6-84cd-55c0916603c3.jpg)

**Comment by daumPostcode** [comment]
@GUMP-JAEWOO 
네~ 안녕하세요~

해당 주소는 현재 도로명주소가 발급되어 있지 않은 주소입니다.
저희 우편번호서비스 v2의 경우 도로명 주소 검색시스템으로, 도로명주소가 발급된 주소여야지 기초구역번호(새우편번호)가 존재하기 때문입니다.

그래서 지도서비스에서 검색이 되더라도 저희 서비스에서는 검색이 안될 수 있습니다. 왜냐하면 지도서비스는 대한민국에 존재하는 모든 주소를 다루고, 저흰 도로명주소가 발급된 주소만 다루기 때문이에요~

해당 내용은 저희 [FAQ 1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)과 [가이드페이지](http://postcode.daum.net/guide)에 모두 설명되어 있으며, 주소 등록방법은 저희 FAQ1번을 참고하시면 되실 듯 합니다.

또한 FAQ1번에 쓰여진 것처럼 행자부의 도로명검색시스템에서도 검색해보면 해당 주소는 검색이 되지 않습니다.
FAQ1번에 나온 내용대로 추가 요청을 도로명검색시스템에 하셔야 될것 같아요~

![empty](https://cloud.githubusercontent.com/assets/20675065/19509309/1c576440-9619-11e6-8c4c-7d99ca74f49b.png)
