### ISSUE TITLE
경기 안산시 단원구 원선1로 38 (주공4단지아파트) 삭제 요청

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#381]
이전에 올린 이슈가 지워졌네요.

`초지동 두산위브` 로 조회시

경기 안산시 단원구 원선1로 38 (두산위브아파트) => 정상
경기 안산시 단원구 원선1로 38 (주공4단지아파트) => 삭제 요청

2개의 주소가 나오는데 `경기 안산시 단원구 원선1로 38 (주공4단지아파트)` 는 잘못된 주소이기 때문에 삭제 요청드립니다.

**Comment by daumPostcode** [comment]
@suseokpark

네~ 안녕하세요~ 해당 이슈 데이터 담당자 분께 전달하도록 하겠습니다.

그런데 현재 깃허브가 이상한지, 어떤지 잘 모르겠지만;;; 이슈가 생겼다가 없어졌다 하네요;;;;

**Comment by suseokpark** [comment]
네 감사합니다.
깃헙 장애로 이슈가 두 번 등록됐네요. 
조금 더 자세한 내용은 아래 이슈에 있습니다.

https://github.com/daumPostcode/QnA/issues/381
해당 이슈는 닫아주셔도 됩니다.

**Comment by daumPostcode** [comment]
@suseokpark 
안녕하세요~

처리가 늦어져서 죄송합니다. 현재 말씀하신 주소의 잘못 매핑된 건물명이 삭제되어 공유드립니다.

제보 감사드립니다. 좋은하루 보내세요~

**Comment by suseokpark** [comment]
늘 잘 처리해주셔서 감사합니다!
