### ISSUE TITLE
주소 검색후 결과 선택 시 문의 드립니다.

### ISSUE THREAD

**Issue by suyoung1613** [daumPostcode/QnA#382]
안녕하세요.

다음 주소검색 api 서비스를 **'팝업을 이용하여 도로명 주소와 지번 주소 모두 보여주기'**  방식으로 사용하고 있습니다.

이슈가 발생한 주소는  '송우리 205-1'로 검색했을 시의 주소이며, 지번 주소를  선택했을 때 도로명 주소가 반환 되지 않는 현상 입니다.

현재 사용자가 검색 결과 화면에서 지번을 선택하던 도로명을 선택하던 무조건 도로명주소를 받아서 처리를 해야하는 상황입니다.

'http://postcode.map.daum.net/guide' 사이트의 '팝업을 이용하여 도로명 주소와 지번 주소 모두 보여주기' 테스트를 해보아도 동일한 현상이 발생함을 확인 했습니다. 

빠른 확인 부탁드립니다.

이상입니다.
감사합니다.

**Comment by daumPostcode** [comment]
@suyoung1613 
안녕하세요~

해당 이슈는 메인주소와 연관주소가 1:1이 아닌 1:N일때 발생하는 문제입니다.
이땐 여러 케이스를 대응하기 위해 매핑되는 변수가 케이스에 따라 다를 수 있습니다.

저희 깃허브 이슈의  README.md파일을 보면 FAQ가 있고(https://github.com/daumPostcode/QnA) 16번 17번 FAQ를 확인해 보시면 좋을 것 같아요.

추가로 가이드페이지의 속성부분을 좀 스크롤을 내리다 보면
<img width="890" alt="2018-11-02 1 10 27" src="https://user-images.githubusercontent.com/20675065/47893532-b5247880-dea0-11e8-86bd-3e0b07594bd5.png">
위와 같은 박스가 보이는데요 이부분을 참고해 보시면 좋을 것 같습니다.

말씀하신 "팝업을 이용한 도로명/지번 모두 보여주기"샘플의 경우엔 현재 의도한 대로 동작중이며,
말씀해주신 주소를 검색을 해서 지번주소를 선택하면, 지번주소 우측에 *예상 도로명 주소*라고 해서 표시가 되고 있습니다. 이는 메인주소와 연관주소가 1:N일때의 활용방법의 예를 기술한 것으로, 이렇게만 이용해야 한다는 정답셋은 아닙니다. onComplete()함수를 통해 들어오는 데이터를 로그 찍어보시면 쉽게 확인 가능하실 거라 생각됩니다.

한번 확인해 보시고 추가로 궁금한 사항이 있으시면 댓글 주시기 바랍니다~ 
감사합니다.
