### ISSUE TITLE
react native webview 에서 로딩이 안됩니다 (안드로이드 4.4.4 Api 19)

### ISSUE THREAD

**Issue by clwhite** [daumPostcode/QnA#383]
react native webview를 사용하여 구현중인데,

IOS에서는 문제 없고, 안드로이드 7, API 24에서도 큰문제가 없습니다.

안드로이드 4.4.4, API 19에서 http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false

해당 스크립트가 로딩이 안되는거 같네요.

 로딩이 안되서 daum.postcode.load를 호출하면 스크립트 자체가 안돌아 가는거 같아요.

특정 버전 이하의 안드로이드 webview에서 작동하지 않는 문제가 있나요?

**Comment by daumPostcode** [comment]
@clwhite 
안녕하세요~

그런 처리는 되어 있지 않습니다.
알려주신 주소의 경우엔 저희가 공개하고 있는 로더스크립트로, 해당스크립트가 호출되어 실행된 뒤에, 실제 코어 스크립트(현재 180928.js)가 로딩이 되게 됩니다.
웹인스펙터 확인이 가능하시다면, 왜 로딩이 되지 않는지 확인 부탁드립니다.

혹시 https 환경의 페이지라면 위 주소의 파일은 로딩이 되지 않습니다. 가이드 페이지에 있는 https용을 이용해 주시면 됩니다.

이외에는 전체적인 오류메세지를 알려주셔야 원인 파악이 가능합니다.

**Comment by clwhite** [comment]
daum 을 JSON.stringify 로 로그를 찍어보니

{"postcode":{"version":"180928"}} 이라고 뜨네요. postcode에 load라는 function도 있는걸로 알고 있는데 로딩이 제대로 안된듯 하네요.

아래 코드가 제가 작성한 javascript입니다.
React native webview를 사용하는데, 구버전 안드로이드에서만 안되네요...

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body style="width:300px;height:500px;background-color:red">
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>
<script type="text/javascript">
  //load함수를 이용하여 core스크립트의 로딩이 완료된 후, 우편번호 서비스를 실행합니다.

  document.getElementById("myDiv").style.backgroundColor = "green";

  console.log("java script loaded");

  function waitForBridge() {

    //the react native postMessage has only 1 parameter
    //while the default one has 2, so check the signature
    //of the function
    console.log("window is loaded");
    console.log("post message length:", window.postMessage.length);
    if (window.postMessage.length !== 2) {
      setTimeout(waitForBridge, 200);
    }
    else {
      daum.postcode.load(function () {
        new daum.Postcode({
          oncomplete: function (data) {
            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
            // 예제를 참고하여 다양한 활용법을 확인해 보세요.
            try {
              setTimeout(() => {
                window.postMessage(JSON.stringify(data));
              }, 500);
            } catch (e) {
            }
          },
          width: '300px',
          height: '100%',
        }).embed(document.body);
      });
    }
  }

  window.onload = waitForBridge;
</script>
</body>
</html>

**Comment by daumPostcode** [comment]
@clwhite 
네~

JSON.stringify를 하시면 함수는 빠지고  멤버변수만 나오는게 맞습니다.

postcode.v2.js 파일이 로딩이 되면 daum.postcode = { version:~~~, load:func~~}이 있는것이 맞으며,
현재 로더 스크립트는 정상적으로 로딩이 되어 있는 상태입니다.

그럼 new daum.Postcode() 실행이 안되시는것 같은데, 
이는 코어스크립트가 로딩이 안되서 daum.postcode.load 함수의 콜백함수가 실행이 되지 못해서 일 수 있습니다.

현재 코드로는 원인을 파악하기 힘드며, *오류 메세지*를 알려주시면 좋을 것 같습니다.
오류메세지 없이는 확인이 어려우실것 같아요.

그리고 추가로 위 로직을 일반 브라우저에서 실행시에 정상동작이 될 경우에는 리액트네이티브 웹뷰의 셋팅 문제일 수 있습니다.

**Comment by daumPostcode** [comment]
@clwhite 
네~ 안녕하세요. 
load함수의 경우엔 postcode.v2.js 파일을 로딩할때 생성되는 것으로,
비동기로 추가를 하거나 하진 않습니다.

혹시 제가 접근할 수 있는 URL이 있을까요??
그리고 제가 위에 쓴것처럼, 어떤 오류메세지도 없을까요? 브라우저에서 실행해서 오류메세지나 현상을 말씀해 주시면 감사하겠습니다.

**Comment by hdkim** [comment]
webview에서 돌아가는거라 오류는 확인하기 어려운데

특정 버전의 안드로이드에서만 안돌아 갑니다.

https://github.com/facebook/react-native/issues/5143

해당 이슈에서 세미콜런이 빠져 있으면 자바 스크립트 로딩이 안될수도 있다고 하는데

이런 문제는 없으셨나요?

**Comment by TrustOne** [comment]
> daum 을 JSON.stringify 로 로그를 찍어보니
> 
> {"postcode":{"version":"180928"}} 이라고 뜨네요. postcode에 load라는 function도 있는걸로 알고 있는데 로딩이 제대로 안된듯 하네요.
> 
> 아래 코드가 제가 작성한 javascript입니다.
> React native webview를 사용하는데, 구버전 안드로이드에서만 안되네요...
> 
> <title></title> <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script> <script type="text/javascript"> //load함수를 이용하여 core스크립트의 로딩이 완료된 후, 우편번호 서비스를 실행합니다.
> document.getElementById("myDiv").style.backgroundColor = "green";
> 
> console.log("java script loaded");
> 
> function waitForBridge() {
> 
> ```
> //the react native postMessage has only 1 parameter
> //while the default one has 2, so check the signature
> //of the function
> console.log("window is loaded");
> console.log("post message length:", window.postMessage.length);
> if (window.postMessage.length !== 2) {
>   setTimeout(waitForBridge, 200);
> }
> else {
>   daum.postcode.load(function () {
>     new daum.Postcode({
>       oncomplete: function (data) {
>         // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
>         // 예제를 참고하여 다양한 활용법을 확인해 보세요.
>         try {
>           setTimeout(() => {
>             window.postMessage(JSON.stringify(data));
>           }, 500);
>         } catch (e) {
>         }
>       },
>       width: '300px',
>       height: '100%',
>     }).embed(document.body);
>   });
> }
> ```
> 
> }
> 
> window.onload = waitForBridge;
> </script>

안녕하세요, 궁금한게 있어서 그러는데요! 저는 oncomplete가 아예 먹통인데.. 혹시 짐작가시는부분 있으시면 말씀해주실수 있을까요? 리액트 네이티브 입니다.
