### ISSUE TITLE
아이폰 검색 결과 화면에서 스크롤이 안되는 현상

### ISSUE THREAD

**Issue by yeonsik** [daumPostcode/QnA#384]
아이폰 검색 결과 화면에서 여러개의 주소를 보기 위해 "더보기" 버튼을 누르면,
다음 페이지로 이동 했을 때 해당 화면에서 스크롤이 되지 않습니다.
"더보기" 버튼 누른 후에 다시 "접기" 버튼을 누르면 그 화면 자체에서도 스크롤이 안되네요.

상단의 입력창을 클릭하면, 다시 스크롤이 동작 하고요.

혹시 원인이나 해결 방안에 대해 알 수 있는지 문의 드립니다.

**Comment by daumPostcode** [comment]
@yeonsik 
안녕하세요~

테스트 확인을 위한 정확한 단말 정보가 필요합니다. 
아이폰 단말 버전, OS버전, 브라우저명(사파리 또는 웹뷰라면 어떤 앱의 웹뷰인지 확인)이 필요합니다.

현재 아이폰6 12.0.1 사파리에서는 팝업 및 레이어 모드에서 모두 정상 동작되고 있는 것으로 확인이 됩니다.

해당 테스트는 공식 가이드페이지에서 확인하였으며, 

말씀하신 이슈가 공식가이드페이지에서도 발생하는지 한번 확인 부탁드립니다.

추가로 제가 접근할 수 있는 주소나, 동영상 같은것을 첨부해 주시면 확인에 도움이 될것 같습니다.

확인부탁드립니다.

**Comment by yeonsik** [comment]
아래 해당 정보들 기재 하였습니다.

감사합니다.

아이폰 단말 버전 시뮬레이터로 7plus, x, xs 등으로 테스트 했는데 모두 동일하게 발생
OS 버전    11.4/12.1
브라우저명    사파리, WKWebview
사용 주소    http://restapi.fs.ncloud.com/postcode/daum_postcode.html

**Comment by daumPostcode** [comment]
@yeonsik 
네~ 
현재 확인 하였으며, 해당 이슈의 경우 아직 정확히 어떤 이슈인지 확인이 어려워서 시간이 좀 필요해보입니다.
해결책이 찾아지면 다시 멘션 드리도록 하겠습니다.

**Comment by yeonsik** [comment]
실제 단말로도 테스트 해봤는데 동일한 현상이 발생하네요.
스크롤을 계속 시도하다보면 조금 뒤에 다시 되기도 합니다.

테스트 단말은 iPhone X, 11.4.1 버전 입니다.

**Comment by yeonsik** [comment]
이슈에 대한 내용과 해결 방법에 대하여 상세하게 알려주셔서 정말 감사합니다.
알려주신 대로 처리를 하니 해당 현상이 발생하지 않습니다.
이후에는 말씀해주신대로 "페이지에 끼워넣기" 예제를 참고한 방식으로 다시
구현을 해보도록 하겠습니다.

도움 주셔서 감사합니다.

**Comment by daumPostcode** [comment]
@yeonsik 
네~ 다행이네요 ㅎㅎ

몇가지 추가로 말씀드리면, 현재 제가 알려드린 방식이 "페이지에 끼워넣기" 버전이며, 가이드페이지에 있는 내용과는 조금 다르지만 목적에따라 변형해서 이용하시면 됩니다.

resize이벤트 무한트리거 문제의 경우엔 다음주 초에 배포가 될 예정인데요. 이때 가이드페이지의 onresize콜백함수에 대한 설명이 살짝 바뀌긴 할거에요.
onresize의 콜백함수는 우편번호서비스 내부의 컨텐츠가 변했을때 발생하는 것이고, 이는 곧 height의 변경을 의미해서 실제 width/height가 모두 넘어오긴 하지만 width는 쓸일이 별로 없습니다.
(컨텐츠가 변경될 조건 - 검색/더보기/페이지 이동 등)

그래서 단말의 가로/세로 orientation이 변할때는 이벤트가 발동하지 않기 때문에
단만의 가로 세로 orientaion에 대응을 하실려면, 

**window.addEventListener('orientationchange', function (e) {
        var width = (window.innerWidth || document.documentElement.clientWidth);
        
        element_layer.style.width = width + 'px';

    }, false);**

직접 위와 같은 이벤트 리스너를 정의해서 가로세로 값 변경 값을 wrapper DOM에 넣어주시면 됩니다.
우편번호 서비스의 기본 width대응의 경우 100%로 되어 있으며(생성자에서 100%로 지정한 경우-기본값) 이는 상위 DOM의 width에 영향을 받기 때문에, 상위 DOM의 크기를 변경하면 자동으로 변하게 됩니다.

이점 참고해 주시기 바랍니다.

그럼 즐거운 하루 보내세요~~

**Comment by yeonsik** [comment]
아 그렇군요~
가이드 내용들과 알려주신 내용들을 토대로 가장 적합한 방식으로 구현해보도록 하겠습니다.
세세한 부분까지 이해할 수 있도록 자세하게 알려주셔서 도움이 많이 되네요~
빠른 답변도 너무 감사합니다.

잘 사용하도록 하겠습니다.
감사합니다.
