### ISSUE TITLE
다음 지도 서비스가 종료(이관)되는 것으로 알고 있습니다.

### ISSUE THREAD

**Issue by keviny1981** [daumPostcode/QnA#385]
혹, 다음 지도 서비스와 동일하게 우편 번호 서비스도 카카오 쪽으로 이관해야 하는지 문의 드립니다.
현재 시스템에서 사용 중인데, 미리 미리 확인을 하려고합니다.

확인 부탁드려요 ^^

**Comment by daumPostcode** [comment]
@keviny1981 
안녕하세요~

다음지도와 다음우편번호서비스는 별개입니다.
또한 다음우편번호서비스는 Developers플랫폼위에서 제공하는게 아닌, 별도로 제공/운영 하고 있는 서비스라
따로 이관을 하거나 하진 않습니다.

다만 추후, daum.Postcode()가 kakao.Postcode 와 같이 네임스페이스가 변경될 수는 있겠지만, 그렇게 된다해도 두벌로 운영되지 일괄바꾸진 않습니다.

만약 만약에 저희 서비스가 Developers 플랫폼 아래로 들어가게 된다면 그건 미리 공지를 하도록 하겠습니다(만 아마 들어갈 일은 없어보이긴 해요;; ㅎㅎ)
