### ISSUE TITLE
행안부 정보와 다릅니다.

### ISSUE THREAD

**Issue by reversal73** [daumPostcode/QnA#386]
아래와 같이 동일한주소에 대해서 행안부 검색결과와 다음 API 결과가 다릅니다.
확인부탁드립니다.

다음 주소 API 이용시
Case 1.
  - 검색어 : 경기도 안산시 단원구 롯데캐슬더퍼스트
  - 검색결과 : 검색 결과 없음
Case 2.
  - 검색어 : 경기도 안산시 원초로 61
  - 검색결과 : 경기도 안산시 원초로 61(주공5단지아파트)
                      ==> 잘못된 주소
행안부 이용시
Case 1.
  - 검색어 : 경기도 안산시 단원구 롯데캐슬더퍼스트
  - 검색결과 : 정상 검색
Case 2.
  - 검색어 : 경기도 안산시 원초로 61
  - 검색결과 : 경기도 안산시 단원구 롯데캐슬더퍼스트
                      ==> 정상 주소

**Comment by daumPostcode** [comment]
@reversal73 
안녕하세요~

건물명이 다른 부분에 대해서 제보해 주셨는데요~
이부분 해당 데이터 담당자 분께 전달하여 확인해 보도록 하겠습니다.
아마 건물명이 다르게 매핑되어 있어서 검색시 결과가 안나오는 것일 수 있습니다.

추가로, 행자부에서 받는것은 데이터일뿐, 검색엔진은 저희 독자적으로 돌아가기 때문에 다른 몇몇 주소의 경우에도 검색결과는 행안부와 다를 수 있는 점 참고부탁드립니다. 

감사합니다.

**Comment by reversal73** [comment]
언제 수정되는거죠?

**Comment by daumPostcode** [comment]
@reversal73 
안녕하세요~

현재 해당이슈 수정 완료되었습니다. 처리가 늦어진 점 죄송합니다. ㅜ.ㅜ
