### ISSUE TITLE
푸터 링크 질문드립니다.

### ISSUE THREAD

**Issue by YoonYeoJung** [daumPostcode/QnA#387]
다음 우편번호 서비스에서 하단푸터에 <<우편번호 서비스 안내>> 라는 링크가 있습니다.

아이들이 링크를 통해 다음을 들어가고 유튜브를 시청한다는 VOC로 인해 푸터를 제외하려 했지만

 사용에 제약이 있다고 하여 

링크를 제거 하려고 하는데 링크를 제거 하여도 제약이 있는지 문의 드립니다.

**Comment by daumPostcode** [comment]
@YoonYeoJung 
네~ 안녕하세요~
서비스 제공자 노출 및 홍보때문에 푸터를 제거하지 마시라는 것이었는데요.
추후 지속적인 어뷰징 발생시에는 제제가 가해질 수 있지만,
그게 아닌 일반적인 이용에는 딱히 제제가 가해지거나 하지 않습니다.

CS에 의해서 어쩔 수 없이 가려야 된다면 가리셔도 되나, 저희가 기본적으로 가리는 옵션은 제공하지는 않는 점 참고부탁드립니다.
