### ISSUE TITLE
embed 함수 사용할 때, 화면창 resize가 강제로 바뀝니다

### ISSUE THREAD

**Issue by moonch0415** [daumPostcode/QnA#388]
초기 화면이 뜰때는 정해놓은 화면크기로 나오는데, 

키보드가 뜬다던가 resize를 하면 화면크기가 

일정한 비율로 바뀌게 되면서 원래 창크기가 500px이라면 화면크기가 바뀌는 순간 일정 비율인 300px .. 299px 이런식으로 바뀌어 버립니다.

resize 함수를 추가해서 크기를 고정시켜도 소용이 없네요..

<div id="layer-address" class="fixed-lg base-l base-t size-wh100p depth-10 overlay-dark1 overlay">
	<input type="hidden" id="address-type" slug="address-type" value="billing">
	<div onclick="hide_address()" class="absolute base-l base-t size-wh100p clickable"></div>
	<button onclick="hide_address()" class="absolute base-l-inner base-t size-w40 size-h50 align-c font-30 depth-1 icon-x font-light1"></button>
	<div id="address" class="fixed center-w base-t margin-t90 margin-t60-md size-w480 size-w320-md size-h500 shadow-3 depth-11">
	</div>
</div>
<script>
    // 우편번호 찾기 화면을 넣을 element
    var element_layer = document.getElementById("address");

    function closeDaumPostcode() {
        // iframe을 넣은 element를 안보이게 한다.
        element_layer.style.display = "none";
    }

	new daum.Postcode({
		oncomplete: function(data) {
			// 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

			// 각 주소의 노출 규칙에 따라 주소를 조합한다.
			// 내려오는 변수가 값이 없는 경우엔 공백("")값을 가지므로, 이를 참고하여 분기 한다.
			var fullAddr = data.address; // 최종 주소 변수
			var extraAddr = ""; // 조합형 주소 변수

			// 기본 주소가 도로명 타입일때 조합한다.
			if(data.addressType === "R"){
				//법정동명이 있을 경우 추가한다.
				if(data.bname !== ""){
					extraAddr += data.bname;
				}
				// 건물명이 있을 경우 추가한다.
				if(data.buildingName !== ""){
					extraAddr += (extraAddr !== "" ? ", " + data.buildingName : data.buildingName);
				}
				// 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
				fullAddr += (extraAddr !== "" ? " ("+ extraAddr +")" : "");
			}

			document.getElementById($("#address-type").val() + "_postcode").value = data.zonecode;
			document.getElementById($("#address-type").val() + "_address_1").value = fullAddr;
			hide_address();
		},
		 onresize : function(size) {
		},
		width : $("#address").width(),
		height : 500,
		maxSuggestItems : 5
	}).embed(element_layer);

	initLayerPosition();
	
    function initLayerPosition(){
        var width = $("#address").width(); //우편번호서비스가 들어갈 element의 width
        var borderWidth = 0; //샘플에서 사용하는 border의 두께

        // 위에서 선언한 값들을 실제 element에 넣는다.
        element_layer.style.width = width + "px";
        element_layer.style.height = "500px";
        element_layer.style.border = borderWidth + "px solid";
    }
</script>

**Comment by daumPostcode** [comment]
@moonch0415 
네~ 안녕하세요~

말씀해주신 코드를 통해서 테스트를 해볼건데요;
어떤 플랫폼에서 발생한 것인지(IOS, Android) 어떤 버전인지, 어떤 브라우저인지
그리고 element_layer를 나타내는 DOM의 코드까지 알려주시면 감사할것 같습니다.

JS코드 특정상 HTML의 경우 외부 사이트에 삽입되는 순간 외부 사이트의 코드에 영향을 받기 때문에 최대한 비슷한 환경에서 테스트를 할려면 전체코드가 필요합니다. 더 좋은 것은 제가 접근할 수 있는 URL이 있으면 더 좋습니다.

그 크기가 변한다는 것이 height가 변한다는 것일까요? 아니면 width가 변한다는 것일까요?

**Comment by daumPostcode** [comment]
@moonch0415 
현재 알려주신 코드로는 어떻게 이슈를 확인해야되는지 명확하지가 않네요;; (말씀하신게 재현이 안됩니다)
제가 바로 위에 적은 것처럼 좀 더 상황을 픽스할 수 있도록 최대한 많은 정보를 알려주셨으면 합니다.
