### ISSUE TITLE
대구 달성군 현풍면 => 현풍읍

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#389]
안녕하세요.

대구 달성군 현풍면이 현풍읍으로 승격됨에 따라 현재 2가지 주소가 모두 노출되고 있습니다.
현풍면은 삭제 요청드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 안녕하세요~

해당 이슈는 현재 내부데이터상 변경은 되었는데, 현재 저희 검색시스템에 잘못 들어간것 같습니다.

말씀하신 이슈 데이터 담당자 분께 말씀드리도록 하겠습니다.

감사합니다.

**Comment by suseokpark** [comment]
아래 1곳 제외하고는 모두 현풍읍으로 변경된 것 확인했습니다.

`대구 달성군 현풍면 중리 280`

![image](https://user-images.githubusercontent.com/39077176/49143949-82ef2500-f33f-11e8-8f9d-1c98455c7db1.png)

확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 
현재 데이터 업데이트의 경우 DB에 적용 후 1~2일 정도 후에 검색엔진에 반영이 되고 있습니다.
그래서 현재 해당 이슈가 처리가 됬는데 이 적용 딜레이 때문에 나오는 것인지, 아니면 이번 수정에서 제외됬는지 확인이 필요할 것 같아요.

일단 말씀하신 주소의 경우엔 별도로 데이터 담당자 분께 전달하도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@suseokpark 
안녕하세요~

현재 남아있던 현풍면 관련된 주소도 삭제되었다고 연락을 받아 공유 드립니다.
한번 확인 부탁드립니다.

다시한번 제보 감사드립니다 ^^ 좋은하루보내세요~

**Comment by suseokpark** [comment]
감사합니다!
