### ISSUE TITLE
데이터 형태가 일치하지 않음.

### ISSUE THREAD

**Issue by ighai** [daumPostcode/QnA#39]
밑의 사진처럼 아파트인데도 불구하고 apartment값이 N으로 표시가 되는 중
![case 1](https://cloud.githubusercontent.com/assets/12728663/19515681/6660e1d2-9633-11e6-93ea-77e63f3d700a.png)
![case 2](https://cloud.githubusercontent.com/assets/12728663/19515680/665d0742-9633-11e6-936f-871641b3b276.png)

**Comment by daumPostcode** [comment]
@ighai 
네~ 안녕하세요~

먼저 저희가 내리는 데이터는 ["행자부 도로명주소 안내시스템"](http://juso.go.kr)에서 보이는 데이터를 기반으로 합니다.
또한 말씀해주신 apartment데이터는 주소의 건물이 **공동주택**인지 아닌지의 여부에 대한 정보를 담고 있습니다.

저희도 말씀해주신 주소를 봐보니;; 아무리 봐도 공동주택인데... N으로 나오는게 이상해서 확인해보니; 행자부측 데이터에서 **공동주택이 아니다**라는 의미로 데이터를 내려주고 있네요; 해당 정보는 juso.go.kr에서 주소를 검색해 보면, 검색결과의 우편번호 부분에 **아파트** 아이콘 유무로 알 수 있습니다.

![result](https://cloud.githubusercontent.com/assets/20675065/19543424/4fe8f906-96b2-11e6-94fe-a428c293497d.png)

그래서 결과를 봐보니 말씀해 주신 2개의 주소의 경우 아파트마크가 없고, 그렇기 때문에 저희쪽에서 데이터를 받을때도 공동주택 여부가 N으로 나오는 것으로 확인이 됩니다 ㅋ

다만 해당 데이터 수정은, 저희쪽에서 맘대로 할 수가 없으며 불편하시더라도 저희 [FAQ 1번](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)과 같이 도로명주소 검색시스템에 Q&A를 남겨서 수정하셔야 될것 같아요.
저희가 수정할 수 있는 것은 원 데이터와 다르게 잘못처리된 부분과, 검색엔진에 관련된 부분으로 원 주소데이터의 경우 주소정보라서 마음대로 수정할 수 없는점 양해 부탁드립니다.

또 다른 질문이 있으시면 언제든 이슈 등록 부탁드립니다 . 감사합니다.
