### ISSUE TITLE
ios 입력 먹통

### ISSUE THREAD

**Issue by LeeKyungWoo** [daumPostcode/QnA#391]
안녕하세요
ifream을 사용하여 레이어로 사용중입니다
ios에서만 발생되는 오류가 있어서 문의드립니다
상단 주소검색 input 터치 후 주소입력한다음 검색한 뒤, input에 입력되어있는 내용을 두번 터치하여 영역을 잡라 컨텍스트메뉴가 나오게 한 다음, 다시 input에 터치하여 커서를 잡은 뒤 내용을 입력하면 먹통입니다(입력이안되고있어요)
input에 입력했을때 먹통이 될수있는 원인들과 해결방법 좀 가이드 부탁드립니다

감사합니다

아 그리고 https입니다

**Comment by daumPostcode** [comment]
@LeeKyungWoo 
안녕하세요 ~

현재 말씀하신대로 공식가이드페이지에서 ios 12.1 사파리에서, 레이어모드로 띄우기 샘플로 확인했을때 해당 현상이 발생하지 않습니다.
먼저 저희 가이드 페이지의 샘플중 개발하시는 것과 유사한 샘플로 테스트를 해보신 후, 말씀해 주시면 감사하겠습니다.
계속 재현이 되시면 정확한 모델 + 버전 + 브라우저(웹뷰인지 아닌지 명시, 웹뷰라면 테스트가 어렵습니다)를 명시해 주시고, 
제가 접근할 수 있는 URL이나 페이지를 띄울 수 있는 full 소스를 주셔야 확인이 가능합니다. (서버페이지 말고 브라우저로 띄운 후 소스보기 했을때 나오는 HTML소스가 필요)

제가 아직 가이드페이지의 샘플 중 경고문구를 수정하진 않았는데, embed를 이용해서 layer모드로 position:fixed를 이용해서 띄울경우, ios에서는 아직도 여러 잔버그가 많습니다. (그래서 샘플은 있으나 추천하는 모드는 아닙니다.)

position:fixed, ios 가상키보드, iframe, inner-scroll 등 여러 이슈가 복합적이라 말씀하신 내용으로는 딱히 알기가 어렵습니다. 이 버그는 플랫폼 버그라 직접 수정은 불가능하고 회피할 수 밖에 없거든요.

일단 재현이 되지 않아 테스트가 불가능하기 때문에 제일 단순한 해결방법으론 가이드페이지의 샘플중 페이지에 끼워넣기 예제가 있습니다. 이 예제처럼 layer처럼 띄우는게 아닌 본문에 삽입을해서 inner-scroll과 position 옵션을 사용하지 않으면 대부분의 버그는 해결됩니다.

한번 확인 부탁드립니다.
