### ISSUE TITLE
엣지에서 오류가 발생합니다. (SCRIPT70: Permission denied)

### ISSUE THREAD

**Issue by proodaun** [daumPostcode/QnA#392]
다른 브라우져 (ie11, 크롬)에서는 팝업으로 잘 표시됩니다.
다만 엣지에서는 오류가 발생합니다. 오류 메세지는 다음과 같습니다.
SCRIPT70: Permission denied 180928.js (1,17468)
![image](https://user-images.githubusercontent.com/740431/49340239-a0dec180-f680-11e8-8994-cbfc6ed2b0f4.png)

도움을 받을수 있을까요?

엣지정보 : 
42.17134.1.0
Microsoft EdgeHTML 17.17134
2018 Microsoft

**Comment by daumPostcode** [comment]
@proodaun 
네~ 안녕하세요~

현재 제가 공식가이드 페이지의 샘플로 알려주신 엣지 버전에서 테스트를 했는데 해당 오류가 뜨진 않습니다,.
IE-Edge라면,
[FAQ13](https://github.com/daumPostcode/QnA#13-%ED%8C%9D%EC%97%85%EC%B0%BD%EC%9D%B4-%EB%B9%84%EC%96%B4-%EC%9E%88%EB%8A%94-%EC%B1%84%EB%A1%9C-%EB%9C%B9%EB%8B%88%EB%8B%A4)번 이슈일 것 같은데요.
document.domain 을 셋팅한 경우 IE-Edge계열에선 정상 동작하지 않습니다.
이 부분이 셋팅되어 있는지 확인 부탁드립니다.
