### ISSUE TITLE
다음카카오 우편번호 서비스관련

### ISSUE THREAD

**Issue by geuny1** [daumPostcode/QnA#393]
카카오 우편번호 서비스(rest api)를 연동했는데 검색 조건으로 도로명이나 동만 입력하면 우편번호가 조회가 되지 않습니다.
(도로명은 나오는데 우편번호가 안나옵니다)
기존 다음이나 행안부 등은 도로명(건물번호 없이)만으로도 조회가 되는데 카카오는 안되네요.
아예 기능적으로 안되는건지 아니면 다르게 구현가능한지 문의드립니다.
불가하다면 행안부너 다른 서비스로 전환해야해서요.

답변부탁드립니다.

**Comment by daumPostcode** [comment]
@geuny1 
안녕하세요~

해당 깃허브는 postcode.map.daum.net/guide 에 있는 API만 담당합니다.
REST API의 경우 이를 지원하는 조직이 달라서 제가 답변드리긴 어려울 것 같습니다.

https://developers.kakao.com/docs/restapi/local#%EC%A3%BC%EC%86%8C-%EA%B2%80%EC%83%89 <- 이 API라면 https://devtalk.kakao.com/ <- 개발자 포럼에 문의 주시는게 좋을 것 같습니다.

원하시는 답을 드리지 못해 죄송합니다.
