### ISSUE TITLE
지번주소/도로명주소의 순서가 바뀌어 나오는 현상

### ISSUE THREAD

**Issue by sangyeob** [daumPostcode/QnA#394]
검색창에 '59563'을 검색 후 12페이지로 가면 
3번째까지는 도로명 - 지번 순서로 나오는데, 
4번째부터는 지번 - 도로명 순서로 나오는 현상이 있는데 의도된 것인지 궁금합니다.

**Comment by daumPostcode** [comment]
@sangyeob 
안녕하세요~

아뇨, 검색결과는 입력되는 쿼리에 따라 도로명-지번 / 지번 - 도로명 세트가 검색엔진에서 정해지며, 내려오는 데이터에 따라 화면을 렌더링합니다.

말씀하신 사항은 의도된 사항은 아닌것 같은데요; 검색엔진 개발자 분께 문의 넣어 보도록 하겠습니다.

제보 감사드립니다.

**Comment by daumPostcode** [comment]
@sangyeob 
안녕하세요~ 문의 결과 공유드립니다,.

현재 해당 이슈는 프로그래밍적 버그는 아니며, 주소데이터에 대한 검색결과 제공정책에 의해서 노출되는 정상적인 결과입니다.
우편번호API에서는 
-도로명주소 (연관주소 지번주소)
-지번주소 (연관주소 도로명주소)
이렇게 하나의 쿼리에 대해서 두가지 셋트를 모두 제공을 합니다.

그리고 쿼리와 이에 해당하는 우선순위에 따라 이 세트의 노출 순서가 변하게 되고
보통 도로명주소 세트가 먼저 보이게 됩니다. 그리고 그 이후에 지번주소 세트가 따라 나오게 되어 있습니다.

전체적으로 보면 둘의 데이터는 동일합니다만, 서로 매핑되는 부분이 달라서 약간씩은 다릅니다 (특히 1:N 매핑 주소의 경우)

해당 결과 포맷의 변경은 내부에서 정책을 변경해야 되는 사항이라 논의가 필요한 부분한 부분이며, 
일단 우려하시는 버그는 아니며,
내려가는 데이터 또한 이상한 데이터가 아닌 저희 가이드페이지에서 제공하는 데이터 포맷 형식 그대로 주소타입에 맞게 정상적으로 내려가기 때문에 이용하시는데 큰 문제는 없으실 것으로 생각됩니다.

감사합니다.
추가 질문이 있으시면 댓글 부탁드립니다.
