### ISSUE TITLE
스크립트 오류관련 문의드립니다.

### ISSUE THREAD

**Issue by pkokgogogono** [daumPostcode/QnA#395]
운영체제 : windows 7 professional K 64bit

익스플로러 버전 : Internet Explorer11 버전 11.0.9600.18537 

프로그램에서 호출을 할경우 몇몇의 피씨만 간혹가다가 스크립트 오류를 발생시킵니다.

예 또는 아니오를 눌러도 스크립트 오류창이 계속 발생합니다.

프로그램을 껐다가 다시키면 정상작동하는대 원인이 무엇일까요? 

스크립트 오류의내용입니다. 추가적인 정보가 필요하시다면 말씀해주세요.

이 페이지의 스크립트에서 오류가 발생하였습니다.
줄:      0
문자:  0
오류:  Script error
코드:  0 
URL: http://t1.daumcdn.net/postcode/api/core/181211/1544591062721/181211.js

**Comment by daumPostcode** [comment]
@pkokgogogono 
네~ 안녕하세요~

우선 일반브라우저가 아닌 특정 프로그램의 웹뷰라면; 저희가 직접 대응해드리긴 어려운점 참고부탁드립니다.

일단 말씀해주신 사항으론 어떤 오류인지 알 수 있는 정보가 없습니다.
적어도 코드 레벨에서 오류가 발생하면 줄과 문자에 특정 숫자가 들어가게 됩니다.
현재 압축되어 스크립트가 내려가기 때문에 줄은 보통 1, 문자 부분에 특정 숫자가 들어가게 되는데, 현재 해당 정보는 0입니다.

이는 정확하진 않지만 해당 프로그램의 스크립트 호출 부분의 오류일 가능성이 있습니다. 또는 몇몇 PC에서 해당 스크립트 로딩이 불가능해서 그럴 수도 있습니다.

현재로써는 일반적인 사용법으로 문제가 생긴다면 http://postcode.map.daum.net/guide 가이드 페이지의 기본사용법 중 동적로딩을 한번 참고해 보시는게 어떨까요? 
일반적인 사용법은 document.write를 사용하며 동적로딩은 script태그를 동적으로 생성해서 삽입하는 방식입니다.
현재로써는 이 방법밖에 제안해 드릴 수 밖에 없네요;;(후자가 대부분의 모던 브라우저에서 더 안정적입니다)

줄/문자 부분의 아무런 정보가 없는 이상 코드레벨에서는 확인할 수 있는 내용이 없으며, 특정프로그램 내에서 사용하는거라 저희가 재현테스트로 해보지 못하기 때문에 해결책을 드릴 수 없는 점 양해 부탁드립니다.
