### ISSUE TITLE
시 보다 구가 먼저 표시되는 이슈

### ISSUE THREAD

**Issue by ninashaves2u** [daumPostcode/QnA#396]
구현은 되는데 구가 시/도에 선행해서 나오는 오류가 발생했습니다.

해운대구 부산 해운대구 대천로103번길 47로 시스템 입력이 됩니다

수정할 수 있는 방법이 있을까요?

**Comment by daumPostcode** [comment]
@ninashaves2u 
네~ 안녕하세요~

현재 가이드 페이지에서 확인해보니, 저희 시스템에서는 구 /시,도 가 바뀌어 표시가 되고 있진 않습니다.
혹시 어제 일시적으로 그랬던 것인지, 또는 데이터 받아서 조합하실때 잘못하셔서 문의 하신것인지 햇갈리네요.

후자라면, address/roadAddress/jinunAddress/autoRoadAddress/autoJinunAddress 등을 이용하시면 조합이 된 도로명 주소로 바로 이용가능하시며,
sido,sigungu,roadname 등을 통해 조합하실경우엔, sido + sigungu 순서로 붙히시면,
"해운대구 부산" 과 같은 현상은 절대 발생하지 않습니다.

한번 확인 부탁드립니다.
