### ISSUE TITLE
화면 커스터마이징 관련

### ISSUE THREAD

**Issue by supergroove** [daumPostcode/QnA#397]
화면 커스터마이징 관련 질문이 있습니다.
기업에서 해당 API를 사용하여 앱 개발을 진행해보는 것을 검토하고 있습니다.
만약, 협의 하에 비용 제공을 한다면 화면 커스터마이징 및 추가 사용할 수 있는 기능이 있는지 궁금합니다.

별도의 문의처가 있다면 알려주시면 그곳으로 문의토록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@supergroove 
네 안녕하세요~

아뇨. 현재 화면의 커스터마이징 기능은 색상테마를 몇개 변경 할 수 있는 기능외에는 따로 없습니다.

현재 우편번호 JS API는 쉽게 이용하고 적용할 수 있는 범용 API에 초점을 맞추어 유지보수 개발 중이며 이에 따라
추가적인 제휴를 통한 기능 확장은 아직 진행할 계획이 없는 점 참고 부탁드립니다.

아마 원하시는 기능의 경우, juso.go.kr(행정안전부 도로명주소검색시스템)에서 제공하는 API나, https://www.poesis.org/postcodify/ (포스트코디파이) 에서 제공하는 API를 이용하시는게 개발방향에 더 맞을것 같다는 생각이 듭니다.

도움을 드리지 못해 죄송합니다.
