### ISSUE TITLE
주소 검색 서버 환경 문의

### ISSUE THREAD

**Issue by supergroove** [daumPostcode/QnA#398]
안녕하십니까. 다음 API를 사용하여 주소 검색을 고객 서비스로 사용하려고 합니다.

아무래도 내부 구성을 알 수가 없어 이중화 사항이나 장애 발생 시 처리 방안을 알 수 없어 문의 드립니다.

1. 서버 이중화 사항
2. 장애 발생 시 알람 여부 (오류 페이지 등의 사용?)
3. 공식적인 서버 작업 시 중단되는 시간이 있는지?

해당 문의 사항에 대해 답변 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@supergroove 
안녕하세요~

1. 카카오의 인프라실 관리하에 서버가 관리되며, 현재 해당 서비스는 4대의 서버로 구성중입니다. 만약 IDC 이중화를 말씀하시는 거면, IDC이중화는 되어 있지 않다고 합니다. 즉 판교에 큰 지진이 발생하면 서비스가 죽겠지만 그외에는 큰 문제는 없을 거에요.

2. 장애를 인지하는 순간, 카카오톡 플러스친구 (다음우편번호서비스)를 통해 알림톡을 드리며, 최대한 빠른 수정을 진행합니다. 모든게 자동화로 진행되는게 아니고, 사람이 운영하는거라 시간대에 따라 편차는 있을 수 있으나 최대한 빠르게 수정을 하려고 노력중입니다.

3. 현재 운영기간 5년동안, 공식적인 서버작업 및 중단은 없었습니다. 배포 또한 무중단 배포를 기본으로 하며, 아마 서버의 중단은 앞으로도 있진 않을 것 같습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@supergroove 
제가 질문에 답변을 달고나서 생각이 들어서 질문남깁니다.

"다음 API를 이용하여 주소검색" 이라고 말씀하셨고, 현재 이 깃허브이슈 페이지는 "다음 우편번호 서비스"에 대한 질문을 올리는 것이기 때문에 답변을 드린것인데, 

간혹
kakao Developers 사이트에 있는 API의 질문도 올라오긴 하거든요.
만약 주소검색을 [주소검색 REST API](https://developers.kakao.com/docs/restapi/local#%EC%A3%BC%EC%86%8C-%EA%B2%80%EC%83%89) 이걸 말씀하시는 거라면, 해당 API는 현재 제가 담당하고 있는 것이 아니며, 관리주체가 달라서 답변이 불가능 합니다.

그게 아닌 우편번호서비스를 이용하시는 거라면 무시하셔도 됩니다.
