### ISSUE TITLE
크롬 무한로딩 이슈로 인해 질문드립니다.

### ISSUE THREAD

**Issue by wan2land** [daumPostcode/QnA#399]
Vue로 Daum Post Code 컴포넌트를 만들어서 제공하고 있는데요, 무한로딩이 발생해서 이슈(https://github.com/wan2land/vue-daum-postcode/issues/2 )가 등록되었습니다. 몇가지 테스트를 해보니 다음 우편번호 서비스 자체의 이슈인 것 같아 문의드립니다.

Os : Mac Mojave / 10.14.2
브라우저: Chrome / Version 71.0.3578.98 (Official Build) (64-bit)

새창이 아닌 `embed()`함수를 통해 호출하고 있으며, 최소 버그 발생 조건은 다음과 같습니다.

## 무한로딩 발생

```html
<!DOCTYPE html>
<html>
<head>
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
</head>
<body>
<div id="postcode"></div>
<script>
function load() {
  new daum.Postcode().embed(document.getElementById("postcode"))
}
load()
</script>
</body>
</html>
```

## 무한로딩 발생안함

```html
<!DOCTYPE html>
<html>
<head>
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
</head>
<body>
<div id="postcode"></div>
<script>
function load() {
  new daum.Postcode().embed(document.getElementById("postcode"))
}
setTimeout(() => load(), 0)
</script>
</body>
</html>
```

또한 `autoload=false`인 경우는 조건에 상관없이 발생하고 있습니다. 다만, setTimeout의 시간을 조금 텀을 주면 무한로딩이 발생하고 있지 않습니다.

## 무한로딩 발생

```html
<!DOCTYPE html>
<html>
<head>
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>
</head>
<body>
<div id="postcode"></div>
<script>
function load() {
  daum.postcode.load(() => {
    new daum.Postcode().embed(document.getElementById("postcode"))
  })
}
load()
</script>
</body>
</html>
```

```html
<!DOCTYPE html>
<html>
<head>
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>
</head>
<body>
<div id="postcode"></div>
<script>
function load() {
  daum.postcode.load(() => {
    new daum.Postcode().embed(document.getElementById("postcode"))
  })
}
setTimeout(() => load(), 0)
</script>
</body>
</html>
```

## 무한로딩 발생안함

```html
<!DOCTYPE html>
<html>
<head>
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>
</head>
<body>
<div id="postcode"></div>
<script>
function load() {
  daum.postcode.load(() => {
    new daum.Postcode().embed(document.getElementById("postcode"))
  })
}
setTimeout(() => load(), 100)
</script>
</body>
</html>
```

**Comment by daumPostcode** [comment]
@wan2land 
안녕하세요~ vue로 저희 서비스를 제공해 주셔서 먼저 감사드립니다.

해당 이슈의 경우, known 이슈이며, 실제 무한로딩처럼, 무언가 리소스를 지속적으로 로딩한다던가 하진 않습니다.
현재 의심가는 사항으로는, 
- iframe을 2중으로 사용중인데, 이에 따른 몇가지 버그들이 있습니다. 이와 연관된 문제가 아닐까 하는 생각이 있고
- 서비스내에서 이미지태그를 이용하여 로그를 보내는데(이용률 체크를 위한 로그입니다) 이 부분과 관련된 문제일까 하는 의심은 있습니다. 

다만 이게 쉽게 해결이 안되서 현재 고민중인 상태입니다. 
물론 이슈 성격상 우선순위가 좀 낮다고 판단되었고, 제가 다른업무들 때문에 밀린것도 있습니다. 이부분은 죄송하게 생각합니다. 

해당 이슈는 빠른 시일내에 처리 또는 완화할 수 있도록 해보도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@wan2land 
안녕하세요~
현재 해당이슈 처리가 완료되어 공유 드립니다. 
맥(10.14.2) 플랫폼의 크롬,파이어폭스,사파리 최신버전, 
윈도우(1803) 플랫폼의 크롬 파이어폭스, IE, Edge,
iOS 12.1, 
Andoid 4.4.2, 8.0 버전에서 정상 동작 함을 확인하였습니다.

현재 시중에 유통되어 있는 모든 단말은 확인하기가 어려운점 양해 부탁드리며,
이슈 발생시 바로 이전버전으로 즉시 롤백이 가능하오니 말씀해 주시면 감사하겠습니다.

해결방법으로는 이전에는 해당 이슈를 접근을 다르게 해서 못찾았던것 같은데요,
document.write를 한 후에 document.close를 실행하는 것으로, 즉 스트림을 닫는 것으로 해결하였습니다.

현재 코어스크립트 최신버전은 190107버전입니다.
브라우저의 캐시를 날려주신후에 테스트 부탁드립니다. 감사합니다.

**Comment by wan2land** [comment]
@daumPostcode 고맙습니다! :-)
