### ISSUE TITLE
코드삽입 방법 문의드립니다.

### ISSUE THREAD

**Issue by han3388** [daumPostcode/QnA#4]
안녕하세요.
게시글 적는 방법이 바뀌었네요.
건강지킴이라고 합니다.
저희 의견을 적극 반영하여 빠르게 적용해주셔서 정말로 감사드립니다.
이제는 저희도 맘놓고 새버전으로 옮겨갈려고 합니다.

그런데 작업을 제가 하는 것이 아니라 홈페이지 만드신 분이 해주시는데 작업 의뢰를 했더니
pleaseReadGuide 와 pleaseReadGuideTimer 기능을 적용할려니 여기에 대한 코드를 못찾겠다고 합니다.
그리고 어느 부분에 어떻게 삽입해야 되는지 안내부분에서는 이 기능에 대힌 설명만 있고 내용이 너무 부족하여 어떻게 적용해야 할지 모르겠다고 하네요.

여기에 대한 자세한 안내 부탁드립니다.

**Comment by daumPostcode** [comment]
@han3388 
네~ 안녕하세요~
일단 pleaseReadGuide 옵션에 대한 설명은 [가이드 페이지 속성](http://postcode.map.daum.net/guide#attributes)의 아래쪽에 설명되어 있습니다. 아래 스샷 첨부합니다.
![pleasereadguide](https://cloud.githubusercontent.com/assets/20675065/17919567/852056b2-6a09-11e6-8c4c-73c8fbb881ab.png)

음. 이부분은 설명만 적어 놓고 따로 코드를 넣어두진 않았는데요, 가이드 페이지의 속성탭 부분의 옵션들은 모두 생성자 함수의 옵션으로 들어가는 값이기 때문에, 쉽게 추가가 가능할 거라 생각을 했습니다.
일단, 이부분에 대한 예제는 추후에 작업을 해두도록 하겠습니다. (넣게되면 속성탭의 theme와 같이 간단한 코드가 들어갈 것 같습니다.)

간략히 설명을 드리면

```
new daum.Postcode({
    oncomplete: function(data){...},
    pleaseReadGuide : 5,
    pleaseReadGuideTimer : 1.5
}).open();
```

위와 같이 작업을 하시면 되는데요.
**pleaseReadGuide**의 값으로는 가이드 문구를 강조시킬 기점이 되는 페이지 수 입니다. 저 예제에서는 검색결과가 5페이지 이상이면 작동하게 됩니다 (값 제한은 3~20입니다)
**pleaseReadGuideTimer**의 값으로는 레이어 강조(검색결과 딤드 + 가이드 문구 강조)가 유지되는 시간입니다. 단위는 초(s)이며, 위 예제의 1.5는 1.5초동안 유지된다는 뜻입니다 (값 제한은 0.1 ~ 60 입니다)

추가적으로 pleaseReadGuide만 설정하셔도 가이드 강조 기능은 작동하며 기본 값인 1.5초로 작동됩니다. 기본값 외에 강조기능의 시간을 늘리고 싶을때 pleaseReadGuideTimer를 이용하시면 됩니다.

이외 자세한 설명은 가이드 페이지를 참고하시면 될것 같습니다.

즐거운 하루 되세요~
