### ISSUE TITLE
iOS 10 업데이트 후, 사파리 및 웹뷰에서 주소 입력시 커서가 위쪽으로 이동합니다.

### ISSUE THREAD

**Issue by yeonhoyoon** [daumPostcode/QnA#40]
안녕하세요?
먼저 좋은 서비스를 만들어 주셔서 감사합니다. 덕분에 간편하게 우편번호 서비스를 이용하고 있습니다.

이번 iOS 10 업데이트 후 'iframe을 이용하여 페이지에 끼워 넣기' 방식으로 서비스 적용시,
첨부한 사진과 같이 사파리 및 웹뷰에서 주소 입력할 때 커서가 위쪽으로 이동하는 현상이 발생합니다.
혹시 대응할 수 있는 방법이 있을까요?

![daum_postcode](https://cloud.githubusercontent.com/assets/2215411/19543291/5617275e-96b1-11e6-8fab-03519b1f0c5d.jpeg)

**Comment by daumPostcode** [comment]
@yeonhoyoon 
네~ 안녕하세요~
불편을 드려 죄송합니다. 
해당 문제의 원인은 우편번호서비스가 들어가는 wrapper의 크기보다 서제스트가 생겼을때의 크기가 더 커서 발생하는 스크롤 때문인 것으로 확인이 됩니다.

해당 현상은 검색결과가 0~3개? 정도 작게 나오는 경우에도 발생할 수 있습니다.
또한 검색어가 길어질 수록 서제스트에 매칭되는 갯수가 작아지기 때문에 커서가 다시 아래로 내려오거나 할꺼에요;;

우선 해당 문제는 저희가 내부적으로 뷰어의 최소값이 있는데 이를 키우던지 또는 서제스트 리스트의 height값을 줄인다던지 또는 다른 API를 만들어서 풀 수가 있는데요, 현재 제 일정상 수정을 바로 하기에는 시간이 잘 안나서 좀 걸릴 것 같아요 ㅜ.ㅜ

일단 @yeonhoyoon 님께서 수정하실 수 있는 방법으로 말씀드리도록 하겠습니다.

저희 가이드 페이지의 **iframe으로 끼워넣기** 예제를 보여주셔서; 이 예제를 기반으로 설명 드릴께요. 핵심은 뷰어의 height를 최소 500이상으로 유지하는 것입니다.

1. 먼저 우편번호 서비스가 들어갈 wrapper의 height값을 최초 기본값을 500이상으로 해주세요. (예시코드는 간단하게 할께요;;)
```
<div id="wrap" style="width:500px;height:500px;......">
```
2. 예제처럼 onresize 콜백함수를 이용하여 검색 결과에 따라 가변적으로 height값을 변경하시는 거라면
```
var element_wrap = document.getElementById('wrap');
new daum.Postcode({
                    oncomplete: function(data) {
                        ......................
                    },
                    onresize : function(size) {
                        element_wrap.style.height = size.height < 500 ? '500px' : size.height+'px';
                    },
                    width : '100%',
                    height : '100%'
}).embed(element_wrap);
```
위와 같이 onresize 부분에서 dom node의 스타일로 들어간 height:500px처럼 500이하로 값이 들어올 경우 무시 하시거나 강제로 500px로 넣는 부분을 추가하시면 wrapper의 크기가 500이하로 줄어들지 않기 때문에 말씀하시는 오류가 없어질 것입니다.

크기는 500정도면 딱 맞게 들어가서 임의로 정한 것이기 때문에 더 크게 하셔도 되나; 작게 하시면 다시 올라가는 현상이 발생할 거에요;; 몇번 테스트 하셔서 적절한 값을 이용하시면 될듯 합니다.

이외 추가적인 질문이 있으시면 이슈 등록 부탁드립니다~ 감사합니다.

**Comment by yeonhoyoon** [comment]
알려주신 것처럼 wrapper의 height를 500 이상으로 설정하니, 커서가 튀는 현상이 발생하지 않게 되었습니다.
감사합니다!
