### ISSUE TITLE
출하지별 배송정책 등록시 사용법

### ISSUE THREAD

**Issue by BAecomm** [daumPostcode/QnA#400]
안녕하세요, 이커머스에 api연동시 출하지별 배송정책을 등록할 수 있는지, 그리고 방법에 대해 문의 드립니다. 예를 들어 제주도나 도서산간 지방의 경우 배송비가 차등부과 되는 경우입니다. 감사합니다!

**Comment by daumPostcode** [comment]
@BAecomm 
안녕하세요~
네. 현재 제주도나 도서산간지역과 같은 정보는 저희가 따로 관리 하는 데이터가 없습니다.
해당 데이터는 직접 구축을 하셔야 될것 같습니다.

도움을 드리지 못해 죄송합니다.
