### ISSUE TITLE
팝업창 위치가 안됩니다.

### ISSUE THREAD

**Issue by cheey82** [daumPostcode/QnA#401]
function execDaumPostcode2(input_post, input_addr1, input_newaddr1) {
	new daum.Postcode({
		oncomplete: function(data) {

			var roadAddr = data.roadAddress;
			var extraRoadAddr = '';
			if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
				extraRoadAddr += data.bname;
			}
			if(data.buildingName !== '' && data.apartment === 'Y'){
			   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
			}

			if(extraRoadAddr !== ''){
				extraRoadAddr = ' (' + extraRoadAddr + ')';
				roadAddr += extraRoadAddr;
			}

			document.getElementById(input_post).value = data.zonecode;
			document.getElementById(input_newaddr1).value = roadAddr;
			document.getElementById(input_addr1).value = data.jibunAddress;
		}
	}).open({left:1300, top:50});
}

위와같이 하였는데.. 팝업창 위치가 적용 안됩니다...

**Comment by daumPostcode** [comment]
@cheey82 
네~ 안녕하세요~

우선 해당 기능은 저희가 따로 작업하는게 아닌, [window.open() 함수](https://www.w3schools.com/jsref/met_win_open.asp)의 속성중 left,top 값을 조절하는 방식입니다.
즉 특별한 기능은 아니고 네이티브 함수의 기능을 그대로 이용합니다. API만 위와같이 사용할 수 있게 한 것일 뿐입니다.

일단 현재 듀얼모니터 이상 이용하시나요? 해당 위치를 잡는 left/top 값은 듀얼모니터 일경우 위치 계산을 해서 직접 넣으셔야 합니다. API입장에선 사용자마다 어떤 값을 원하는지 알 수 없기 때문에 입력된 값을 그대로 변환없이 이용하기만 할뿐 다른 처리는 되어 있지 않습니다.

해당 이슈는 구글링을 해보시면 해결방법이 나올것 같습니다.

추가로 현재 코드는 샘플코드로 위 코드만 가지고는 어떻게 적용이 안되는 것인지 알 수 없습니다. 실제 이슈가 되는 화면이 필요합니다.
