### ISSUE TITLE
도로명주소 항목 문의

### ISSUE THREAD

**Issue by cheey82** [daumPostcode/QnA#402]
"부산 해운대구 재반로104번길 15-5"로 검색을 하게 되면

"부산 해운대구 재반로104번길 15-5 (다솜어린이집)"
이 나오게 되는데,

이것을 가져오게 되면

"(다솜어린이집)" 부분은 안가져 옵니다. 이 부분은 어떤 변수(?) 인가요?

**Comment by daumPostcode** [comment]
@cheey82 
네~ 안녕하세요~

현재 저희 API의 모든 스펙정의는
[공식 가이드 페이지](http://postcode.map.daum.net/guide)에 기술되어 있습니다.
이중 사용법음 "예제",
내리는 데이터 목록은 "속성"
메소드 사용법음 "함수"
부분을 참고해 보시면 됩니다.

실제 내리는 데이터는 코드레벨에서 oncomplete의 인자로 받는 변수를 로그로 찍어보면 바로 알 수 있으며,
가이드 페이지에서는 "속성" 부분의 "반환되는 데이터 확인하기" 버튼을 통해 확인 가능합니다.

말씀하신 데이터는 buildingName이라는 변수에 들어가 있습니다.

현재 저희 "예제"의 경우엔 "도로명주소 시행령"의 표기 규칙에 맞춰서 표기하는 방식으로 구현되 있는 것이며,
그냥 예제이고 참고사항일 뿐입니다. 모든 코드를 똑같이 따라하실 필요는 없습니다.

그래서 저희 샘플을 이용하신다면 말씀하신 주소의 다솜어린이집 이라는 건물명은 oncomplete함수 내부에서 사용하지 않도록 할겁니다. 이는 도로명규칙 시행령의 제3조 부분을 보시면 아실 수 있습니다/.(해당 링크는 가이드 페이지의 예제 부분에 존재합니다.)
다만 앞서 말씀드린 것처럼 예제코드를 그대로 이용하실 필요 없으며, 실제 oncomplete함수 내부의 구현 사항은 저희의 관리영역이 아닙니다. 온전히 API를 이용하는 개발자의 몫임을 알려드립니다.

확인 부탁드립니다.
