### ISSUE TITLE
도로명 주소 등록 요청

### ISSUE THREAD

**Issue by heody0726** [daumPostcode/QnA#403]
행정자치부 도로명 주소에 등록이 되어 있음에도 불구하고 
회사 주소가 등록이 되지 않음
등록 부탁드립니다.
주소 : 대구광역시 동구 매여로 14

**Comment by daumPostcode** [comment]
@heody0726 
안녕하세요~

현재 해당 주소의 경우 [FAQ 1번 추가사항](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)에 해당하는 주소입니다.

현재 해당 주소의 경우, 내부 매핑시스템에서 좌표로 주소들을 매핑하는데; 해당 주소의 경우 이 좌표값을 알 수가 없어서 매핑이 어렵습니다.그래서 FAQ에 표시된 것처럼 나오는 주소의 경우 현재 저희 시스템에서는 검색이 불가능한 점 참고 부탁드립니다.

현재 위와 같은 주소를 표시하기 위해선 내부 매핑 시스템이 변경되거나 검색엔진이 변경되어야 하는데, 현재 이 모듈들이 저희 서비스만을 위해서 만들어진 엔진이 아니라서 개선에 어려움이 있습니다.
현재로써는 보여드리기 어려운점 양해부탁드립니다.

죄송합니다.
