### ISSUE TITLE
건축물 대장이 존재하는데 지번 검색이 안되는 현상

### ISSUE THREAD

**Issue by outseer** [daumPostcode/QnA#404]
'홍은동10-183'로 검색하면 결과가 나오지 않고 있습니다.

2018-12-26에 승인된 건축물 대장이 존재하는데 아직 갱신이 되지 않은 것인가요?

신축 건물이라 해당 주소로 매물을 등록해야 하는데 못하고 있는 상황입니다.

확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@outseer 
네~ 안녕하세요

[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)을 참고해주세요.

저희는 도로명주소 검색시스템이며, FAQ1번에 명시된 것처럼 행정안전부 도로명주소시스템에 등록된 도로명주소만 검색이 가능하며, 몇가지 예외 주소를 제외하곤 모두 검색이 가능합니다.
저희 시스템에서 검색이 안되면 1차적으로 juso.go.kr 에서 검색을 해보시는걸 추천드립니다.
도로명주소 등록방법은 행안부 도로명검색 시스템(juso.go.kr) 고객지원을 참고해 주세요.

<img width="1211" alt="2019-01-15 4 31 52" src="https://user-images.githubusercontent.com/20675065/51165366-538e7a80-18e3-11e9-9a48-aaed704e91af.png">

감사합니다.
