### ISSUE TITLE
도로명 주소 등록 요청

### ISSUE THREAD

**Issue by kimks1985** [daumPostcode/QnA#405]

**Comment by kimks1985** [comment]
안녕하세요.
서울 서대문구 북가좌동 295-18번지에 대한

주소검색이 안되고 있는데요.
행정자치부 도로명주소 검색시스템에서는
도로명주소가 노출되는데 1일 이상 지났음에도 불구하고
업데이트 되지 않은 것 같습니다.

확인부탁 드릴 수 있을까요?

**Comment by daumPostcode** [comment]
@kimks1985 
네~ 안녕하세요~ 해당주소 데이터 담당자분께 말씀드리도록 하겠습니다.
보통 매일매일 오전에 배치로 반영이 되는데, 특정 케이스들에 한해서 문제가 가끔 발생하거든요.

수정 반영이 되면 말씀드리도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@kimks1985 
안녕하세요~

데이터 담당자분께 문의한 결과
해당 주소 정보가 생태값이 N(비활성화) 상태로 인입되어 발생된 문제였습니다.
주소값 자체는 2018년 8월에 인입이 되었는데 이 상태값이 변경이 안되어 반영이 안되었던 것이네요.

우선 도로명주소검색시스템(행안부 사이트)에서 검색이 되어 노출되게 변경하였다고 합니다.

제보 감사드립니다.

좋은 하루되세요~
