### ISSUE TITLE
Chromium에서 작동이 되지 않습니다.

### ISSUE THREAD

**Issue by juicycool92** [daumPostcode/QnA#406]
안녕하세요, 최근에 발견된 이슈인데, C#프로그램에서 사용중인 chromium web view 에서 다음 우편번호 찾기 기능이 작동하지 않아서 질문 드립니다.

구동중인 서버는 https 로 구동중 이기 때문에, 스크립트 임포트도 https에 맞게 body태그 제일 아래쪽에 설정 해 두었으나,
`Uncaught ReferenceError: daum is not defined`
가 계속하여 발생하고 있습니다.
다른 브라우저 ( 크롬과 파폭, 엣지) 에서는 정상적으로 작동중 입니다.
해당 이슈에 관해 도움을 받을 수 있을까요?

**Comment by daumPostcode** [comment]
@juicycool92 
네~ 안녕하세요

해당 오류는 스크립트 자체가 로딩이 안된경우입니다.
즉 코어스크립트가 아닌 postcode.v2.js 파일 자체가 로딩이 안된경우에 위와 같은 오류가 뜨게 됩니다.
파일 로딩이 되는지 확인을 부탁드립니다.

**Comment by juicycool92** [comment]
네, 파일로딩이 안되는 상황은 저희측에서 이미 확인 된 사항입니다. 지적해 주셔서 감사합니다.
그럼 파일 자체가 로딩이 안된경우, 해결할 수 있는 다른 방안이 있는지 궁금합니다.

**Comment by daumPostcode** [comment]
@juicycool92 
일반 웹브라우저가 아닌 경우에는 제가 도움을 드릴 수 있는 방법이 거의 없습니다..
일단 그 오류가 나는 환경을 제가 재현을 해야하는데 네이티브앱이나 다른플랫폼 웹뷰의 경우엔 사람마다 너무 다른 방식으로 제작을 하기 때문에 환경재현이 불가능합니다.
또한 제일 큰 문제가 chromium web view에 대해서는 아는바가 없어서, 왜 로딩이 안되는지는 원인을 잘 모르겠네요;

저희가 가이드 하는건 가이드 페이지에 있는 것처럼 script태그를 통해 스크립트를 로딩하는 것으로 이건 일반브라우저라면 기본적인 동작이기 때문에, 이 기본적인 동작이 안된다는건, 해당 앱의 설정 문제일 가능성이 있다고 생각합니다.

도움을 드리지 못해 죄송합니다;;

**Comment by juicycool92** [comment]
친절하신 설명 감사합니다.
혹여아 해결된다면 이슈 공유하도록 하겠습니다
