### ISSUE TITLE
내부망 PC에서 우편번호 검색시 js호출이 안되는 현상

### ISSUE THREAD

**Issue by kimseokyoung** [daumPostcode/QnA#407]
보안정책상 망분리가 되어 있는 내부망 PC 에서 우편번호 검색을 이용해야 하는데요.
인터넷이 되는 환경에서는 우편번호 검색이 잘 되지만 망분리가 되어 있는 내부망 PC 에서는 
네트워크 구성에 따른 JS파일 호출 불가 현상에 대하여 문의 드립니다.

우편번호 서비스를 구성하기 위하여 웹페이지에 적용한 다음API 소스를 통해 JS 파일을 호출합니다.
이 과정에서 API소스가 적용된 웹 서버가 아닌 PC에서 직접 JS파일 다운로드를 시도하는것으로 확인 되었습니다.
현재 PC에서 외부 인터넷 연결이 차단되어 있어 해당 JS파일 다운로드가 되지 않아 서비스 페이지 구동이 되지 않고 있습니다.
 
개발자도구 - 콘솔에서 확인해보면
 SCRIPT5009: 'daum'이(가) 정의되지 않았습니다.
라는 메세지가 나옵니다.

관련하여 해결할 방안이 있는지 문의 드립니다.

현재 아래 도메인으로 방화벽은 허용 해 놓은 상태입니다.
HTTP환경
•http://postcode.map.daum.net
•http://dmaps.daum.net
•http://s1.daumcdn.net
•http://stlog1.local.daum.net
•http://suggest-bar.daum.net
•http://t1.daumcdn.net
•https://apis.daum.net (v3 maps api 사용시)

HTTPS 환경
•https://ssl.daumcdn.net
•https://s1.daumcdn.net
•https://suggest-bar.daum.net
•https://t1.daumcdn.net
•https://spi.maps.daum.net
•https://apis.daum.net (v3 maps api 사용시)

개발소스는 jsp 에서 아래와 같은 형태로 개발되어 있습니다.
<input type="text" id="zipCd" placeholder="우편번호">
<input type="button" onclick="searchAddr()" value="우편번호 찾기"><br>
<input type="text" id="encAddr" placeholder="주소">
<input type="text" id="encDtlAddr" placeholder="상세주소">

<div id="postcodeLayer" style="display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;">
   <img src="//t1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>

<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>
<script>

var element_layer = document.getElementById("postcodeLayer");

function searchAddr() {

   new daum.Postcode({
       oncomplete: function(data) {
          // ...      
       }
   }).embed(element_layer);
}

</script>

**Comment by daumPostcode** [comment]
@kimseokyoung 
안녕하세요~

자바스크립트는 기본적으로 클라이언트 PC의 브라우저에서 다운로드 받습니다.
기본적으로 브라우저에서 다운로드되어 파싱되고 실행되는 언어입니다.

해당 오류는 postcode.v2.js 파일 자체가 다운이 되지 않아 아래에서 new daum.Postcode를 실행할때 daum이 없어서 발생한 오류입니다. daum이라는 네임스페이스는 postcode.v2.js가 다운로드가 되면 만들거든요.

이를 서버에서 실행하실려면, 서버에서 해당 스크립트를 따로 로딩하고 다운로드된 파일을 정적으로 페이지에 삽입하여 이용하는 방법이 있습니다만, 어차피 저희 API는 JS API만 다운받는다고 되는건 아니며, 그 안에서 다시 저희쪽 페이지를 호출하여 실행을 하게 되어 있습니다. 즉, 클라이언트 PC에서 외부접속이 전혀 되지 않는다면, 이용하실 수 있는 방법은 딱히 없습니다.

이전에 내부방에서 이용하시는 분들께서 질문을 종종 남겨주시는데요, 해결책으론 네트워크 담당자분께 말해서 저희가 이용하는 도메인의 IP를 방화벽 해제하여 일반 PC에서도 접근 가능하게 하는 방법외엔 딱히 해결책이 없어보입니다.

저희 API는 무조건 인터넷망이 연결된 상태에서 동작하는 API이며, 환경적으로 인터넷 접근이 어렵다면, 행안부 도로명검색시스템의 API(DB를 다운 받을 수 있는 것 같기도 합니다.) 또는 Postcodify 를 이용해 보시는게 좋을 것 같습니다.

도움을 드리지 못해 죄송합니다.
