### ISSUE TITLE
주소 검색 중, 이태원동을 '이태원1동-이태원2동으로 따로' 보여주고 처리하는 함수가 있나요?

### ISSUE THREAD

**Issue by gihong7** [daumPostcode/QnA#408]
안녕하세요 :)

서비스 내 회원가입 과정 중, 주소에서 동을 1동, 2동... 분리해서 주소를 받으려고 합니다.
예를 들어 이태원동은 이태원1동, 2동으로 나뉘어져 있는데, 다음 주소 api에서는 1동 2동을 구분하지 않고 모두 이태원동으로 일괄 처리하고 있습니다. 이걸 1동 2동으로 분리해서 주소를 받을 수 있는 함수가 있을까요?

**Comment by daumPostcode** [comment]
@gihong7 
네~ 안녕하세요~

음, 주소의 경우엔 기본적으로 법정동을 기본으로 합니다.
말씀하신 1동 2동은 행정동으로 보이는데요, 일단 기본적인 주소데이터의 경우 법정동을 기반으로 도로명주소가 매핑된다고 보시면 됩니다.

말씀하신 기능은, 저희 가이드 페이지의 속성 부분을 보시면 (http://postcode.map.daum.net/guide)
showMoreHName <- 이러한 생성자 옵션이 있는데요, 이걸 true로 활성화 시키시면,
검색되는 주소 중에, 법정동명과 행정동명이 다를경우 list에 표시를 하며, hname이라는 변수로 행정동명을 내리게 되어 있습니다. 실제 자세한 설명은 가이드 페이지를 참고해 주시기 바랍니다.

즉 oncomplete에서 내려받은 데이터의  hname 변수에 값이
있다면 법정동명과 행정동명이 다르다는 것이며, 
없다면 법정동명과 행정동명이 같다는걸 의미합니다.

한번 확인 부탁드립니다. 감사합니다.
