### ISSUE TITLE
라인(LINE), 페이스북 메신저 지원

### ISSUE THREAD

**Issue by screwbar** [daumPostcode/QnA#409]
안녕하세요.

현재 저희가 개발 중인 서비스에 카카오톡과 라인, 페이스북 메신저에 링크를 보내면 그 링크 안에서(웹뷰) 우편번호를 검색하는 기능이 있습니다.
카카오톡에서는 모두 잘 되었으나 라인, 페이스북 메신저에서는 우편번호 검색까지만 되고 검색한 주소를 클릭하면 페이지가 하얗게 변하면서 주소값을 가져오지 못했습니다.
현재 저희 서비스를 개발 중인 개발업체에서는 라인 메신저와 페이스북 메신저 브라우저에서는 다음 API를 사용할 수 없다고 하는데 지금 저희 측에서 다시 테스트를 해보니 페이스북 메신저에서 주소를 불러오는 것을 성공해서요..
혹시 다음 API는 라인에서 사용 불가능한지 알려주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@screwbar 
안녕하세요~

해당 이슈의 경우에는 웹뷰의 구현완성도에 따른 경우인데요.
아마 주소검색은 되나 클릭시 데이터를 못가져온다는 것은, 이미 부모페이지가 변경되어 버렸을 것이에요.
즉 저희가 window.open을 크로스브라우징 처리 때문에 살짝 변태적인 방법을 이용합니다. 
그래서 이러한 부분까지 모두 지원되는 브라우저에서만 동작이 잘 되는데요, 저희의 초점은 항상 일반적인 브라우저에 초점을 맞추어 개발을 하고 있고 웹뷰의 경우에는 개발사마다 너무 다르기 때문에 맞추기가 어렵습니다.

그래서 만약 팝업모드를 사용하신다면 웹뷰에 따라서 지원이 불가능한 경우가 있으니
모바일웹페이지 또는 모바일웹의 웹뷰에서 동작하는 서비스라면
embed()를 이용한 레이어나, 페이지에 삽입하는 방식(저희 예제 참고)을 이용하시는 걸 추천드립니다.
이중에서도 inner scroll버그가 적은 "페이지에 삽입하는 방식"을 이용하시는걸 권장합니다.

그리고 마지막 질문주신, 라인에서 사용불가능하다. <- 이 질문에 대한 답변은,
질문에도 쓰셨지만 우편번호 검색하는 화면이 떴다는 것은 저희 API를 로딩을 못하거나 하는 문제가 아닙니다. 제가 위에 말씀드린 웹뷰의 완성도에 따른 문제로 embed를 이용하는 방식을 이용하면 해결이 되실것 같습니다.
(구현 완성도 라는게 회사가 웹뷰를 이상하게 구현한게 아니라, 웹뷰의 경우 필요한 기능만 넣지, 일반브라우저처럼 풀스펙을 모두 구현하지 않기 때문으로 이해하시면 될것 같습니다) 

추가적인 질문이 있으시면 댓글 부탁드립니다.
