### ISSUE TITLE
우편번호 서비스 v1 관련 문의

### ISSUE THREAD

**Issue by single18** [daumPostcode/QnA#41]
'우편번호 서비스 v1'이 16년 12월31일까지 지원된다고 알고있습니다.
그렇다면 그 이후에는 아예 서비스 자체가 안되는건지, 
아니면 사용은 가능한 것인지 문의드립니다. 

개발자에게 의뢰시에 비용발생 문제가 있어서 부득이 '우편번호 서비스 v1'을 계속 써야할수도 있기
때문에 제 입장에서는 중요한 사안입니다. 

답변부탁드립니다. 그럼 수고하세요.

**Comment by daumPostcode** [comment]
@single18 
네~ 안녕하세요~ 

일단 결론 부터 말씀드리면, 서비스적인 데이터 업데이트, 그리고 기능상 업데이트는 중단됩니다.
그리고 서비스 서버 자체를 내리는 것에 대한것은 100% 결정이 난 것은 아니지만, 12월 31일날 중단되지 않더라도, 그 이후 빠른 시일내에 중단 될 수 있습니다. 이부분에 대해서는 다시 한번 서비스 차원에서 공지를 드리도록 하겠습니다.

우편번호서비스 v1을 중단할 수 밖에 없는 이유로는 아시겠지만, 데이터에 대한 문제가 가장 큽니다. 현재도 한달에 1번 업데이트이고, 이또한 v2처럼 적극적 갱신이 이루어지진 않구요. 그리고 무엇보다 6자리 구우편번호는 계속 없어지는 반면에 5자리 새우편번호는 계속 생기고 있고, 무엇보다 데이터상 5자리 새우편번호는 존재하지 않고, 내부 주소API 상으로도 이 데이터를 추가하기가 어렵습니다. (그래서 v2를 만든 이유이기도 합니다;;)

이런 이유때문에 v2로 변경 의뢰를 하시는 것을 적극 추천 드립니다.

**Comment by daumPostcode** [comment]
@single18 
안녕하세요~

우편번호 V1서비스 종료에 대한 최종일정이 결정되어 공유 드립니다.
종료 일은 2017년 2월 6일(월) 오후 3시이며, 이전까지 V2로 이관을 해주시면 감사하겠습니다.

자세한 사항은 https://github.com/daumPostcode/QnA/issues/91 <- 이 이슈를 확인해 주세요.

감사합니다
