### ISSUE TITLE
firefox iframe history 문제

### ISSUE THREAD

**Issue by seoyeongB** [daumPostcode/QnA#410]
브라우저: firefox 65.0

iframe을 사용해서 주소창을 띄우고 있습니다.
firefox의 경우 브라우저 back을 하면 iframe이 blank가 되고 다시 back을 눌러야 뒤로가기가 동작합니다.
(iframe의 history 때문인 것 같긴한데 확실히는 모르겠습니다.)

크롬이나 safari는 정상동작 합니다.
해당 이슈에 대해서 해결 방안이 있을까요?

**Comment by daumPostcode** [comment]
@seoyeongB 
네~ 안녕하세요~

해당 이슈의 경우, 브라우저별 케이스에 따른 이슈이기 때문에 시간이 좀 필요합니다.
내부적으로 해결하기가 어려울시에는 저희 API를 이용하시는 개발자분께서 직접 히스토리 체크를 해서 처리해야 할 수도 있습니다.
시간이 좀 필요하여 바로 답변을 드리기가 어려울것 같습니다.

이번주는 제가 시간이 안되서 보기가 어려워서 다음주 쯤에 해결가능한지 불가능한지부터 해서 답변을 드리도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@seoyeongB 
안녕하세요~

현재 해당이슈에 대해서 기존 히스토리를 확인해보니; 브라우저 자체에서 처리를 하는 것들이라 JS단에서 우회처리를 하는 방법외에는 없었던 것으로 확인이 됩니다.
현재 저희 검색페이지의 경우 검색시마다 form submit을 수행하는데, 이 자체가 페이지가 바뀌는 것을 의미하며, 파이어폭스에서는 이 아이프레임의 내용까지 잡는 것 같습니다.

그래서 이전 CS(https://github.com/daumPostcode/QnA/issues/286)를 참고해 보시면 도움이 되실것 같습니다.
해당옵션의 경우 기본적으로 공개를 하지 않을 옵션이므로, 
이슈 등록하신 분들에게만 제공함을 양해부탁드립니다.

생성자 옵션으로
submitMode : false

를 넣게 되면, 검색시 폼전송을 수행하지 않도록 변경이 되어 히스토리 관리대상에 빠지게 됩니다.

한번 확인 부탁드립니다.

**Comment by seoyeongB** [comment]
네 이미 `submitMode: false`는 사용중이나 같은 문제가 발생합니다.
검색시 마다 발생하는 문제가 아닌, 그냥 embed만 한 상태에서도 발생하는 문제입니다.

모달형태로 띄우고 있는데, brower back을 사용해서 우편번호 모달을 닫을 수 있도록 처리 중입니다.
우편번호를 띄우기 전 history.push를 history.back을 하면 모달이 닫히는 것을 기대하고 있습니다. (다른 브라우저 정상 동작)

기본적으로 embed를 시키면 html 구조가
div#__daum__layer > iframe[src="about:blank"] > document안에 또 iframe 존재합니다.

크롬에서 history.back()을 하면 저 위 구조가 그대로 남아있는 상태로 이전 url로 돌아갑니다.
파이어폭스의 경우 첫번째 뒤로가기를 하면 iframe[src="about:blank"] 안에 document가 초기화 된 상태로 빈 화면만 나타납니다. 두번째 뒤로가기 시에 이전 url로 돌아갑니다.

submitMode의 문제는 아닌 것 같습니다...
[가이드 페이지](http://postcode.map.daum.net/guide)에서 iframe을 이용하여 레이어 띄우기에서 우편번호 창을 띄운 후 (검색 없이) 브라우저 뒤로가기를 해도 마찬가지 입니다.
