### ISSUE TITLE
도로명 주소 등록 요청

### ISSUE THREAD

**Issue by Raphin** [daumPostcode/QnA#412]
안녕하세요.
부산광역시 동래구 명륜로 222(명륜동, 힐스테이트) 에 대한
주소검색이 안되고 있습니다.

행정자치부 도로명주소 검색시스템에서는 정상적으로 검색되나
다음 우편번호 검색에서는 검색이 되지 않습니다.

확인 및 등록 요청 드립니다.

**Comment by daumPostcode** [comment]
@Raphin 
네~ 안녕하세요~

현재 해당 주소 관련하여 주소데이터 담당자 분께 공유드렸습니다.
확인 결과가 나오면 공유드리겠습니다.

제보 감사드립니다.

**Comment by daumPostcode** [comment]
@Raphin 
안녕하세요~

일단 늦어서 죄송합니다.
현재 해당주소 정상 반영되어 댓글 드립니다.

제보 감사드립니다.
