### ISSUE TITLE
2월 10일에 모바일 웹뷰에서 주소검색시에 검색이 안되던 문제

### ISSUE THREAD

**Issue by dan1901** [daumPostcode/QnA#413]
주소 검색시 흰색 화면만 나오는 문제가 발생하였는데 원인을 알 수 있을까요?

**Comment by daumPostcode** [comment]
@dan1901 
네~ 안녕하세요~

힌화면으로 나올수 있는 원인은 다양할 수 있습니다. 현제 저희쪽 오류면 전체적인 장애로 판단이 가능하지만,
그게 아닌이상, 현재 저희 API를 적용한 페이지의 문제로 보입니다.

[FAQ12](https://github.com/daumPostcode/QnA#12-%ED%8C%9D%EC%97%85%EC%B0%BD%EC%97%90%EC%84%9C-%EA%B2%80%EC%83%89-%ED%9B%84-%EA%B2%B0%EA%B3%BC%EB%A5%BC-%ED%81%B4%EB%A6%AD%ED%95%B4%EB%8F%84-%EB%B0%98%EC%9D%91%EC%9D%B4-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4)번, 13번을 한번 확인해 보시기 바랍니다.

일단 페이지에 document.domain을 설정하는 부분이 있다면, 해당 설정이 되는 순간 저희 서비스는 이용하지 못합니다. 이부분 참고해 주시기 바랍니다.

그리고 크롬의 개발자도구를 이용하면 오류발생시 오류코드가 뜨는데 그걸 이용해 한번 확인해 보시는걸 추천드립니다.

**Comment by daumPostcode** [comment]
@dan1901 
제목을 다시보니 2월 10일에 이슈가 발생해서 문의 주신것이군요.

서버쪽 오류가 발생하면, 기본적으로 장애보고가 발생하며, 이런 시스템적인 장애보고 외에도, 엄청난 CS가 인입이 됩니다... 하지만 당일 인입된 CS(깃허브 이슈, 플러스맵 친구 1:1톡)가 하나도 없는 것으로 보아, 저희쪽 서비스의 장애보다는 다른 이슈때문에 발생한게 아닐까 싶습니다.

혹시 주말에 배포같은게 있었다면, 위에 제가 답변단 내용을 한번 확인해 보셨으면 좋을 것 같습니다.

**Comment by jonesn123** [comment]
안녕하세요 IOS 12.2 (Beta버전) 에서 주소검색이 안되는 문제가 있는데, 이부분도 한번 추가로 체크 부탁 드리겠습니다.

**Comment by daumPostcode** [comment]
@jonesn123 
정보가 너무 적습니다.....
주소검색은 매우 범용적인 질문이신데요;; 
종종 이 이슈페이지에 주소검색 REST API관련해서 여쭤보시는 분들도 계셔서요. 
저희가 서비스 하고 있는 우편번호 검색 JS API가 맞을까요?(postcode.map.daum.net/guide 에서 배포하는 JS API입니다)

두번째 웹뷰인지, 정식사파리인지 필요합니다.
웹뷰의 경우엔 저희가 지원을 해드리지 못하는 점 미리 말씀드립니다.

사파리의 경우엔 확인해 볼 수는 있습니다만, 저희 같은 경우엔 정식릴리즈가 된 이후에 확인을 하고 있습니다. 기본적인 브라우저의 기능을 사용하는 서비스이기 때문에 OS가 업데이트 된다고 표준기술이 변하거나 하진 않거든요.

추가적으로 현재 해당 버전의 단말이 없어서 바로 확인은 불가능 한데요.
정보를 좀 더 주셨으면 합니다.

**Comment by daumPostcode** [comment]
@jonesn123 
안녕하세요~ 단말이 확보되서 가이드 페이지 및 제가 테스트하는 테스트페이지를 가지고 팝업모드 및 레이어 모두를 모두 테스트 해봤는데 모두 정상동작함을 확인하였습니다.

Iphone 7 plus - ios 12.2(16E5191d) 버전으로, Safari에서 테스트하였습니다.
스샷은 레이어모드에서만 촬영하였습니다.

베타버전 OS의 경우 브라우저의 버그가 있을 수도 있으며, 웹뷰의 경우라면 이상현상이 있을 수는 있습니다.
이는 버전이 더 올라간 후에 버그 패치가 진행이 되기도 하니 한번 확인 부탁드립니다.

![img_1901](https://user-images.githubusercontent.com/20675065/52689276-fdbdf880-2f9c-11e9-80eb-298a885e6ca9.JPG)
![img_1900](https://user-images.githubusercontent.com/20675065/52689281-01ea1600-2f9d-11e9-976d-a2c194ca86ba.JPG)
![img_1897](https://user-images.githubusercontent.com/20675065/52689290-06aeca00-2f9d-11e9-96ff-eff6a39c3f15.JPG)
![img_1898](https://user-images.githubusercontent.com/20675065/52689304-0d3d4180-2f9d-11e9-9402-d0fe1c97cfcd.JPG)
![img_1899](https://user-images.githubusercontent.com/20675065/52689314-129a8c00-2f9d-11e9-9a37-6b93b6a428e3.JPG)
