### ISSUE TITLE
주소등록 요청

### ISSUE THREAD

**Issue by LeeGiBong** [daumPostcode/QnA#414]
[312 - 894]   충청남도 금산군 남이면 성곡리 1073

**Comment by daumPostcode** [comment]
@LeeGiBong 
안녕하세요~

[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고부탁드립니다.

<img width="752" alt="2019-02-12 6 24 24" src="https://user-images.githubusercontent.com/20675065/52625069-88e2b400-2ef3-11e9-9518-2ee525b4a132.png">
