### ISSUE TITLE
주소등록 요청

### ISSUE THREAD

**Issue by jomingi** [daumPostcode/QnA#415]
인천광역시 미추홀구 숙골로 90(도화동) 추가 부탁드립니다.

**Comment by daumPostcode** [comment]
@jomingi 
안녕하세요~

현재 해당 주소는 등록이 되어 있는 것으로 확인이 됩니다.
![image](https://user-images.githubusercontent.com/20675065/52762175-cbbe9c00-3059-11e9-9c98-25b5b35d9840.png)

확인 부탁드립니다.
