### ISSUE TITLE
주소등록 요청드립니다.

### ISSUE THREAD

**Issue by wonjae529** [daumPostcode/QnA#416]
안녕하세요,

명륜로 222 검색시 행정 자치부에서는 검색이 되나 Daum에서는 검색이 되지않습니다.
확인 후 반영 부탁드립니다!!

감사합니다.

**Comment by daumPostcode** [comment]
@wonjae529 
네~ 안녕하세요~

데이터 담당자분께 저번에 여쭤본 결과 현재 해당주소가 신규주소로 확인이 되는데요. 
행자부와 저희와의 싱크문제로 인해서 반영이 안된것으로 확인이 됩니다.

현재 담당자 분께서 알고 계시며, 다음주에 행자부 측에 직접 문의 하여 답변을 드리도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@wonjae529 
늦어서 죄송합니다.
현재 해당주소 정상 반영되어 답글드립니다.

제보해 주셔서 감사드립니다.
