### ISSUE TITLE
주소 등록 요청드립니다.

### ISSUE THREAD

**Issue by dan1901** [daumPostcode/QnA#417]
도로명 : 경상북도 예천군 호명면 행복로 55
지번 : 경상북도 예천군 호명면 금능리 739 

가 검색이 되지않아 등록요청드립니다

**Comment by daumPostcode** [comment]
@dan1901 

안녕하세요

[FAQ 1번 추가사항](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 확인 부탁드립니다.

해당 주소의 경우엔 현재 시스템상 매핑이 불가능하여, 저희 시스템에서 제공이 불가능합니다.
말씀하신 주소와 같은 주소들을 한번 모두 나오게 할려는 작업을 진행하려고 하였으나, 시스템적으로 변경해야되는 부분이 너무 많아서 제공이 어렵다는 피드백을 받았었습니다.
불편을 드려 죄송합니다.
