### ISSUE TITLE
주소 리턴값의 sigungucode 속성값이 존재하지 않는 경우

### ISSUE THREAD

**Issue by enenfru** [daumPostcode/QnA#42]
api 에서 sigungucode 속성값이 리턴되지 않는 경우가 있습니다.

경기 고양시 덕양구 화전동 203-12 

위 주소로 검색 할 경우 sigungucode 속성값이 존재 하지 않는데, 이 속성이 무조건 리턴해주지 않는 속성인건가요?

**Comment by daumPostcode** [comment]
@enenfru 
네~ 안녕하세요

현재 안나오는 원인은 지번으로 검색할시에는 나오지 않고 도로명으로 검색할때만 나오는 것으로 확인이 됩니다.
sigungucode의 경우 지번/도로명에서 같이 쓰이는 거라 나와야 될것 같은데, 해당 문제는 내일 데이터 담당자와 같이 확인해 보도록 하겠습니다.

내일 다시 답변 드리도록 할께요;; 불편을 드려 죄송합니다;

**Comment by enenfru** [comment]
답변 감사합니다 ^^
추가적으로 부탁드려도 될런지요?
api 리턴되어 오는 속성값들에 대해 필수 또는 선택적으로 리턴해주는 값인지에 대해 리스트가 필요합니다. 리스트가 있다면 알수 있을까요?

모든 리스트를 알 수 없다면, 리턴값의 속성 중 아래 7개의 속성값이 필수 또는 선택적으로 오는지에 대해 알고 싶습니다.
1. sido
2. sigungu
3. bname
4. address
5. zonecode
6. bcode
7. sigungucode(위 답변에서 확인받을 속성)

감사합니다.

**Comment by daumPostcode** [comment]
@enenfru 

네~

일단 API에 내려오는 데이터들의 설명은 [가이드 페이지 속성](http://postcode.map.daum.net/guide#attributes) 부분을 참고 부탁드립니다.

질문주신 내용에 답을 드리면
1. sido : (필수) - 지번/도로명 검색결과가 모두 공통으로 포함하는 데이터
2. sigungu : (필수) - 지번/도로명 검색결과의 공통 데이터 (현재 버그로 인해 지번검색시 안내려가는데 수정 예정)
3. bname : (필수, 다만 동지역과 읍면리 지역의 데이터가 다름) - 해당 주소의 법정동/법정리 이름, 해당 데이터의 경우 도로명 주소를 구성할때 주소 맨뒤에 추가 정보를 넣을 수가 있습니다. 예를 들자면 "서울 용한구 한남대로 98 (한남동)" 이렇게 말이죠. 이럴때 추가적으로 사용하시라는 의미로 넣은 데이터 입니다. 이 데이터의 경우에도 항상 내려갑니다만, 읍/면/리 주소를 검색할땐 동정보가 아니라 읍+리, 면+리 와 같이 내려가게 됩니다.
4. address : (필수) - 검색결과가 도로명-지번 순 또는 지번-도로명 순으로 쿼리에 따라 달라지는데 이때 윗줄에 표시된 주소의 값이 들어가게 됩니다. 항상 들어갑니다. 다만 사용자사 선택한 값은 아닐 수 있습니다. 이는 userSelectedType변수를 보시고 jibunAddress, roadAddress를 통해 추출하시는 것을 추천드리나, 해당 데이터에 대한 값 할당 메커니즘이 생성자의 autoMapping 파리미터에 따라 달라질 수 있기 때문에 이것 또한 가이드 페이지의 
![12](https://cloud.githubusercontent.com/assets/20675065/19586690/92935446-9792-11e6-91fa-c0c1dadd1fe6.png)
위 스샷 부분을 참고 부탁드립니다.
5. zonecode : (필수) - 새우편번호(기초지역번호) 우편번호서비스 v2의 경우(현재 사용하시는 버전) 100% zonecode가 할당되어져 있는 주소만 나옵니다. 이는 100%도로명 주소가 발급된 주소만 나온다는 의미와 같습니다. 즉 항상 내려갑니다.
6. bcode : (필수) - 이또한 참고자료로써 bname과 같이 지번/도로명 주소에서 공통으로 쓰이는 값이기 때문에 항상 내려갑니다.
7. sigungucode : (필수) - 이 데이터 또한 지번/도로명 주소의 공통 속성으로써 항상 내려갑니다. 다만 현재 문의 주신 것처럼 지번 검색시 파싱오류로 인해 내려가지 않고 있는데요;;;; 이부분은 금일 수정되어 테스트 후, 다음 주 월요일에 배포될 예정입니다. 서비스 배포한 후 이 이슈에 댓글 드리도록 하겠습니다.

말씀해 주신 데이터들 모두 필수적으로 내려가는 정보이지만, 모든 데이터를 이용하시라는 의미는 아닙니다. @enenfru 님의 시스템에 맞게 적절히 필요한 정보만 이용하시고, 또는 내려받은 데이터를 2차 가공하셔서 이용하셔도 됩니다.

자세하게 쓰긴 했는데, 일단 가이드 페이지의 속성 oncomplete부분을 한번 자세히 읽어보시면 더욱 도움이 되실 것 같아요. 추가적인 질문이 있으시면 언제든 이슈 등록 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@enenfru 
안녕하세요~

금일(2016년 10월 24일) 16시에 실서버 배포되어 공유 드립니다.
말씀해주신 지번검색시 sigungucode가 내려가지 않는 문제가 수정되었습니다 ^^

앞으로도 많은 관심 부탁드립니다 ^^ 감사합니다.
