### ISSUE TITLE
'제주특별자치도 제주시 일도1동, 일도2동' 법정동 오류

### ISSUE THREAD

**Issue by susemeee** [daumPostcode/QnA#421]
제주시의 일도동의 법정동은 각각 '일도일동'과 '일도이동'으로 기재되어야 하는데, 행정동인 '일도1동'과 '일도2동'으로 기재됩니다.

참고: https://ko.wikipedia.org/wiki/%EC%9D%BC%EB%8F%84%EB%8F%99

**Comment by daumPostcode** [comment]
@susemeee 
네~ 안녕하세요~

법정동명의 표기 방식에 대한 문의로 보이네요.
이 부분에 대해서는 제가 잘 알지 못하여 주소데이터 담당자 분께 문의해 보겠습니다.
어느정도 시간이 소요될 수 있는점 양해 부탁드립니다. 
감사합니다.

**Comment by daumPostcode** [comment]
@susemeee 
안녕하세요~
주소 담당자 분께 답변이 와서 공유드립니다.

일단 주소담당자 분께서도 인지하고 계신 이슈이며
제주도 법정동 중 숫자가 포함된 법정동명칭들을 한글로 변경하는 작업은 다음주 목요일 이전에 배포가 될 것이라고 합니다. 

제보 감사드립니다.

**Comment by daumPostcode** [comment]
@susemeee 
안녕하세요~
제주 지역 법정동에 숫자가 들어간 부분 처리가 완료되어 공유드립니다.
확인 부탁드려요~

**Comment by susemeee** [comment]
확인이 늦었네요. 처리된 부분 확인하였습니다.
감사합니다.
