### ISSUE TITLE
행안부 정보(buildingCode)와 상이 (강원 정선군 고한읍 고한3길 6-11)

### ISSUE THREAD

**Issue by mjchoi83** [daumPostcode/QnA#423]
강원 정선군 고한읍 고한3길 6-11

행안부 건물관리번호(buildingCode) : 4277025321100900002010494
daumapi건물관리번호(buildingCode) : 4277025321100900002010493

결과 값이 상이합니다.

확인 및 업데이트 부탁 드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@mjchoi83 
네~ 안녕하세요~
해당 이슈 주소데이터 담당자분께 말씀드리도록 하겠습니다.

제보 감사드립니다.

**Comment by daumPostcode** [comment]
@mjchoi83 
안녕하세요~
해당 이슈 수정 배포되어 공유 드립니다. 
감사합니다.
