### ISSUE TITLE
구글 스크립트에서 사용 가능한가요?

### ISSUE THREAD

**Issue by arenti** [daumPostcode/QnA#425]
구글 스크립트에 넣고 사용하고 싶은데 혹시 사용 가능할까요?
구글 폼에서 특정 텍스트입력창을 누르면 자동으로 다음 주소창을 띄우고 검색 후 해당 값을 리턴받아 텍스트 입력창에 넣고 싶은데...
구글 스크립트의 한계인지.. 활용하셨던 분이나 어떤 방식이나 어떤 함수를 호출해야 되는지 아는분 계실까요?

**Comment by daumPostcode** [comment]
@arenti 
안녕하세요~
구글 스크립트란게 정확히 뭔지 몰라서 잘 모르겠지만, 구글에서 제공하는 JS API 인건가요?
우선 어떤 JS 프레임워크나 라이브러리를 이용하더라도 저희 서비스는 이용이 가능합니다.

저희 서비스 가이드 페이지를 봐보시면,
특정 프레임워크나 API를 이용하는 기능이 없습니다. 순수 Javascript ES5 표준대로 구현되었으며, 그외 다른 라이브러리 디펜던시나 그런것도 없습니다.

즉 웹환경에서 어떤 웹페이지에 들어갈 수 있습니다. 다만 몇가지 제약사항들이 있으니 이는 플랫폼이나 실행 방식에 대한 문제로 FAQ를 한번 참고해 보시는게 좋을 것 같습니다.
