### ISSUE TITLE
서울시 서대문구 남가좌동 5-267번지 도로명 주소 등록 요청

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#426]
신축 빌라 주소 추가 부탁드립니다.

* 지번주소 : 서울시 서대문구 남가좌동 5-267번지 CU원룸 405호
* 도로명 주소 : 서울시 서대문구 명지대1나길 1 CU원룸 405호 (남가좌동)

![image](https://user-images.githubusercontent.com/39077176/54606018-f901ce00-4a8d-11e9-9c28-d834bd0f2d66.png)

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 안녕하세요~

해당 현상 데이터 당당자 분께 문의 드리도록 하겠습니다.
제보 감사드립니다.

**Comment by daumPostcode** [comment]
@suseokpark 
현재 해당 주소 처리되어 실서버에 반영되었습니다.
한번 확인부탁드립니다.
감사합니다.

**Comment by suseokpark** [comment]
등록 감사합니다!
