### ISSUE TITLE
인천 미추홀구 도화동 (도화두손지젤시티) 주소 등록 요청

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#427]
안녕하세요.
인천 미추홀구 도화동 (도화두손지젤시티) 주소 등록 요청 드립니다.
카카오 맵에서는 아래와 같이 `인천 미추홀구 도화동 837` 으로 표시됩니다.
http://kko.to/0NfUJXmTT

감사합니다.

**Comment by daumPostcode** [comment]
@suseokpark 
네 안녕하세요~

저희 서비스는 도로명주소를 기반으로 하는 서비스라, 카카오맵과는 기반 데이터가 좀 다릅니다.
말씀하신 주소를 행안부에서 검색해보니 도로명주소가 발급되어 있지 않네요

이러한 주소는 저희가 추가를 해드릴 수 없으며 행안부에 직접 도로명주소 발급 요청을 해주셔야 합니다.
[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)

참고해 주시기 바랍니다.

**Comment by suseokpark** [comment]
답변 감사합니다. 직접 등록 요청하도록 하겠습니다.
