### ISSUE TITLE
행안부-비공동주택 주소 건물명 표기오류

### ISSUE THREAD

**Issue by vovoxworld** [daumPostcode/QnA#428]
퇴계로73가길 30

검색결과가 다릅니다.

행안부 가이드 : 서울특별시 중구 퇴계로73가길 30(신당동) 
다음주소검색 : 서울특별시 중구 퇴계로73가길 30(신당동) 
API 결과 : 서울 중구 퇴계로73가길 30 (목향빌딩)

**Comment by daumPostcode** [comment]
@vovoxworld 
안녕하세요~

현재 저희 서비스의 경우, 주소선택에 도움을 드리고자 검색결과 목록에는 건물명이 있을시 건물명을 같이 표시해 주고 있습니다.
실제 이렇게 표시만 되어 있는 것이지, 저희 서비스를 이용해서 데이터를 받으시면 모든 데이터가 분리되어 있으며,
그 분리된 데이터를 통해 도로명주소 표시 규칙에 맞게 재 조합을 하시면 됩니다.

실제 이용하시는 서비스의 주소란에 들어가는 주소형태가 중요한 것이지, 검색결과의 경우엔 저희가 이런 이런 정보는 필요하겠다는 정책에 따라 나열한 것이며, 그렇기 때문에 행안부와는 다릅니다.

이점 참고해 주시기 바랍니다.

도로명주소 조합규칙에 대한 설명은 
저희 가이드 페이지 https://spi.maps.daum.net/postcode/guidessl
의 예제 부분에 꼭읽어주세요 라는 부분에 링크가 되어 있으니 확인 부탁드리며,
실제 예제들도 이러한 조합교칙에 맞게 작성되어 있으니 확인 부탁드립니다.
