### ISSUE TITLE
[질문] 시도(군구리스트 포함) 리스트를 받을 수 있나요?

### ISSUE THREAD

**Issue by jb9229** [daumPostcode/QnA#429]
안녕하세요.

구현하려는 기능이, 사용자가 근처의 업체를(Daum postcode로 업체 주소 등록) 조회하는 기능이입니다.

그때 사용자가 편의를 위해, 시도 리스트를 UI로 보여줘 선택하게 만들고자 합니다.(시도 선택후 => 군구 선택)

군구 리스트가 포함된 시도 리스트를 api 호출등으로 받을 방법이 있을까요?

**Comment by daumPostcode** [comment]
@jb9229 
네~ 안녕하세요~

현재 저희가 시도/시군구 등의 리스트를 제공하는 API가 따로 존재하진 않습니다.;;
한번 정부에서 제공하는 API들을 확인해 보시는게 어떠실까 합니다.

구현하시려는 기능을 보니, 사용자의 주변의 모든 업체가 검색이 되어야 될것 같은데;
저희 API의 경우 [FAQ1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)과 같이 검색이 안되는 주소도 있습니다.

그렇기 때문에 해당 기능의 경우엔 행안부의 API를 이용해 보시는게 더 좋을 것 같다는 생각이 드네요; ㅎㅎ

도움을 드리지 못해 죄송합니다.

**Comment by jb9229** [comment]
감사합니다, 행안부통해 아래와 같은 답을 받았네요

행안부 DB에서 직접 다운받아 데이터를 구축 하라네요.

====== 행안부 답변=====
안녕하세요. 
도로명주소 도움센터입니다. 

개발자센터에서 제공해드리는 API는 
시도/시군구를 선택하지 않아도 검색을 할 수 있는 통합 검색 기능을 제공해드리고있습니다. 
따라서 시도/시군구를 선택하는 기능은 따로 제공해드리지 않고 있습니다. 
시도/시군구 기능을 사용하시려면 
주소DB제공에서 데이터를 다운받아 데이터를 구축하여 사용하시면 기능을 구현하실수 있습니다. 

안내해 드린 내용이 도움이 되시기를 바라며, 
기타 문의사항은 ☎ 1588-0061 로 문의하시기 바랍니다.

**Comment by daumPostcode** [comment]
@jb9229 
아. 전체 DB를 다운받아서 구현하라는 것이군요;;

도로명 주소의 경우엔 업데이트가 매우 자주 일어납니다. 거의 1일 업데이트가 이루어져서 DB관리에 신경을 많이 쓰셔야 될것 같아요;
제가 정확히 아는 분야는 아니지만; 주소 DB받아서 그나마 업데이트 주기가 매우 적은 행정구역별 데이터만 뽑아서 새로 구축하고, 행안부의 "도로명주소 검색 REST API"를 이용해서 받은 결과를 서버에서 필터링해서 리턴해주는 방식은 어떠실까 합니다;;

아무쪼록 잘 해결되시기 바랍니다.
