### ISSUE TITLE
iOS, Facebook Webview 의 API 로드 불가 문제

### ISSUE THREAD

**Issue by andrewlee89** [daumPostcode/QnA#43]
안녕하세요.

서비스 예약 신청 시 주소입력을 다음 우편번호 API를 이용하고 있습니다.
모든 기기 및 OS, 브라우져에서 큰 문제없이 구동 되는데, 유독 iOS Facebook의 인앱브라우져만 실행이되지 않습니다. android의 Facebook은 정상동작합니다.

iOS Facebook 어플에서 사이트 링크를 타고 들어와서 주솿기를 누를 경우 흰 화면이 뜨고 아무것도 나오지 않습니다. 물론 선택을 못하니까 다시 전 페이지로 돌아가는 것은 그냥 뒤로가기 일 뿐 이구요.

얼만전까지는 카카오 웹뷰도 같은 문제가 있었는데, 따로 코드를 수정하지 않았는데 오늘 테스트해보니 카카오는 정상적으로 작동합니다. 

혹시 어떻게 해결을 해야할까요?

답변 기다리겠습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@andrewlee89 
네~ 안녕하세요~

javascript window.open native함수의 모든 동작방식을 지원하는 것은 safari, chrome등 정식 브라우저만 지원을 합니다. 웹뷰의 경우에는 브라우저의 전체 기능보다 단순하게 만드는 경우가 많아 몇몇 웹뷰(네이버앱, 다음앱 등) 말고는 부분 지원만 합니다.

그래서 이부분도 FAQ에 적을까 고민을 하고 있는데요.
그래서 모바일의 경우에는 embed를 이용해서 레이어 형식 또는 페이지에 끼워넣는 형식으로 사용하시는 것을 추천드립니다. 모바일과 PC의 경우에는 UA분기를 통해 쉽게 구분을 할 수 있기 때문에 한번 확인해 주세요.

현재 이 open로직에 대해서 서비스API차원에서 100%지원을 하려면 IE6부터 시작하는 하위 호환성 관련되서 좀 살펴볼게 많아; 개발이 늦어지고 있네요;; 이점 양해 부탁드리며, 한번 embed를 이용하여 작업을 해주시면 감사하겠습니다.

**Comment by andrewlee89** [comment]
@daumPostcode 

답변 감사합니다.

말씀하신대로 작업해보도록하겠습니다.
