### ISSUE TITLE
 Daum 우편번호 서비스 주소등록 요청

### ISSUE THREAD

**Issue by jominji1** [daumPostcode/QnA#430]
행정자치부 도로명 주소 검색시스템에 등록이 되어있으나, Daum 우편번호 서비스에 검색이 되지 않습니다.

-경산북도 경산시 삼북동 190-2번지 호텔 크라페
-경산북도 경산시 장산로 23길 7 호텔 크라페

주소 등록 요청드립니다.

**Comment by daumPostcode** [comment]
@jominji1 
네~ 안녕하세요~

해당 이슈 데이터 담당자 분께 전달하도록 하겠습니다.
제보 감사드립니다.

**Comment by jominji1** [comment]
언제쯤 정상적으로 처리가 되는지 알 수 있을까요?

**Comment by daumPostcode** [comment]
@jominji1 
네~ 안녕하세요~

담당자 분께 여쭤보니, 차주에 반영이 될것 같다고 하시네요. 정확한 일정은 확인이 어려울것 같습니다.
차주에 연락을 받으면 제가 답변 드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@jominji1 
현재 해당 주소 수정되어 실서버에 반영되었습니다.
답변이 늦어 죄송합니다.
