### ISSUE TITLE
iOS 12.2에서 UIWebView, WKWebView 사용 시 oncomplete 내에서 window.location=''이 실행되지 않는 현상

### ISSUE THREAD

**Issue by dyyeom** [daumPostcode/QnA#431]
안녕하세요, 
저희는 html 페이지를 UIWebView를 활용해서 보여주고 있습니다.
iOS 12.2에서만 제목과 같이 oncomplete() 메소드가 호출되지 않는 현상이 있습니다.
검색된 우편번호 목록에서 주소를 선택하고 나면 페이지가 흰색 화면으로 변하고 아무 동작도 하지 않습니다.
이에 따라 현재 iOS 12.2 업데이트 한 유저들은 저희 애플리케이션을 통해서 주문이 불가능한 상황입니다.
이 부분에 대한 확인을 부탁드립니다.

**Comment by daumPostcode** [comment]
@dyyeom 
안녕하세요~

[FAQ 10번](https://github.com/daumPostcode/QnA#10-iosandroid%EC%97%90%EC%84%9C-webview%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-%EC%82%AC%EC%9A%A9%ED%95%A0-%EC%88%98-%EC%9E%88%EB%82%98%EC%9A%94)
한번 참고 부탁드립니다.

웹뷰의 경우엔, 개발자들만의 커스터마이징이 모두 다르므로, 저희가 테스트를 해보는게 어렵습니다.
현재 웹뷰에 적용하고 있는 소스를 일반 브라우저에서 테스트한 후에, 거기서 정상 동작이 되는지 확인 부탁드립니다.

현재 말씀하신 사항으로는 무언가 알기가 어려운데, 힌색화면으로 변했다는걸 보니, FAQ에 적혀있는 것처럼 open메소드를 사용하시나요? open메소드에 대한 윈도우창이 열리는건 웹뷰로 개발하실때 커스터미이징을 해주셔야 합니다.
현재 몇몇 웹뷰어플리케이션(구글앱, 다음앱, 네이버앱)등과 같은 프로그램 말고는 왠만한 웹뷰에서는 open메소드는 정상적으로 동작하지 않습니다. 새창이 뜨는게 아닌 기존 부모페이지를 replace시켜버리기 때문에, 부모페이지가 사라져서 oncomplete이 동작을 하지 않는 것이죠.

이부분 한번 확인 부탁드립니다.

**Comment by dyyeom** [comment]
@daumPostcode 
말씀하신 FAQ 확인했었습니다.
embed로 작업한 상태이며, 사파리에서도 동작하지 않습니다.
사파리에서도 동일하게 iOS 12.1까지는 정상동작 하고 있으며, iOS 12.2부터만 정상동작이 되지 않고 있습니다.

**Comment by daumPostcode** [comment]
@dyyeom 
넵. 답변이 늦어 죄송합니다.

현재 해당 이슈 확인해보니 iOS 이번 업데이트 버그인것 같아 보이긴 한데요;
onComplete함수의 경우 저희가 본페이지에 영향을 최소화 하기 위해 dummy-iframe을 하나 만들게 되는데;
이 iframe에 바인딩되어 실행되는 콜백함수입니다.

특별히 이상한 부분이 아닌 네이티브 모듈의 기본기능이 안되는 것으로 보아 iframe과 연관된 버그로 생각이 됩니다.
일단 4월 4일 점심 기점으로 임시적으로 버그 회파한 버전을 올려두도록 하겠습니다.

따로 조치하실 사항은 없으십니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@dyyeom 
안녕하세요~

답변이 늦어서 죄송합니다. 현재 코어버전 190404로 회피코드 적용하여 실서버 배포되었습니다.

한번 확인 부탁드립니다.

**Comment by dyyeom** [comment]
@daumPostcode 정상적으로 동작하는 것 확인했습니다. 고맙습니다!
