### ISSUE TITLE
네이버 앱 관련 오류

### ISSUE THREAD

**Issue by id9437** [daumPostcode/QnA#432]
안드로이드 네이버 앱에서 open 함수를 사용하여 페이지 로드 후는 정상적으로 이루어지고 있는데

검색을 하면 리스트 출력까지는 완료되나 잠시 후 앱이 강제 종료되는 현상이 발생하고 있습니다.

해당 현상 원인 알려주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@id9437 
안녕하세요~

일단 네이버앱은 자사 서비스가 아닌 외부 서비스이며, 크래쉬가 난 원인은 알기 어렵습니다.
특히 단순 웹사이트가 뜬다고 크래쉬가 난다는 것은 해당 앱의 오류메세지를 보고 확인을 해야합니다.
현재 저희 서비스는 동작시에 무언가 백그라운드에서 돌아가거나, 하는 기능이 없고, 검색도 폼전송으로 서버에 요청하고 결과 받아서 그리는 역할만 하고 있습니다.

일단 네이버앱 10.2.3
안드로이드 8.0

에서 확인한 결과 크래쉬는 발생하지 않았습니다.

현재 해당 사이트가 어떤것인지 확실히 모르겠지만, 다른 몇대의 핸드폰에서도 발생하는지 확인 부탁드립니다.
현재 네이버 앱에서 앱이 크래쉬 난다고 들어온 CS는 없습니다.

한번 확인 부탁드립니다.
