### ISSUE TITLE
스크립트 오류 문의드립니다 

### ISSUE THREAD

**Issue by xqnstk** [daumPostcode/QnA#433]
안녕하세요! API 제공해주셔서 정말 감사드립니다.
주소검색기능을 사용하기 위해 테스트중입니다.

처음엔 daum객체가 없다는 오류가 나서 신뢰할 수 있는 사이트에
url(https://ssl.daumcdn.net)을 추가를 하니 그 오류 대신

" SCRIPT445: 개체는 이 기능을 지원하지 않습니다. "라는 오류가 발생합니다.
디버깅해보니 daum객체는 존재하는 걸로 봐서는 js파일 로딩문제는 아닌 것 같습니다.

참고로 IE11이고, 스크립트 코드는 head안에 있습니다. 

daum.postcode.load(function(){   //daum 조사식 추가해보니 object라 나오고
            new daum.Postcode({  //이 라인 지날 때 에러가 발생합니다.
                oncomplete: function (data) { 
                       ~~~ 

항상 수고하십니다. 감사합니다 ~~

**Comment by daumPostcode** [comment]
@xqnstk 
안녕하세요~

daum객체가 없다는 것은 postcode.v2.js <- 와 같은 로더 파일이 로딩이 되지 않았다는 것이고
이 파일이 로딩이 되면 그 이후에 19XXXX.js와 같은 실제 코어 스크립트를 로딩하게 됩니다.
이 스크립트가 로딩이 되야 daum.Postcode 생성자를 이용하실 수 있습니다.

다만 사용하신 daum.postcode.load의 경우엔 동적로딩 방식이라,
이 함수를 사용하면 코어스크립트를 로딩한 후에, function(){}으로 연결된 콜백을 이후에 실행시키게 됩니다.

일단 스크립트 로딩 문제로 보이는데요;
혹시 외부망과 단절된(인터넷이 안되는) 내부 인트라넷에서 사용하시나요?
이런경우, 네트워크 관련부서나 이런곳에서 저희가 사용하는 도메인에 연결된 IP를 모두 풀어주셔야 합니다.
저희는 인터넷이 연결된 상태에서 사용가능하며 내부망은 따로 지원하지 않습니다.

두번째 현재 테스트를 어떤걸로 하시는지 잘 모르겠지만 IE같은 느낌이 납니다.
IE는 디버깅이 어렵기 때문에 크롬으로 개발을 우선 진행하시는게 어떨까 합니다.

크롬 개발자 도구를 통해, 실제 스크립트가 로딩이 되는지 먼저 확인 부탁드립니다.

저희 서비스가 동작을 하려면, postcode.v2.js와 190404.js (2019년 4월 4일 기준) 이렇게 두개의 파일이 로딩이 되야 합니다. 이부분 확인 부탁드립니다. 크롬 개발자도구의 네트워크 탭을 확인해 보시면 됩니다.

**Comment by xqnstk** [comment]
답변감사합니다!
원격IP로 붙어서 작업하고, IE11버전에서 테스트 중입니다.
현재 Chrome브라우저를 사용하지 못 하는 상황이라 IE로 개발진행하고 있는 점 양해부탁드립니다ㅠㅠ

확인해보니 postcode.v2.js 는 다운이 되어 개발자도구의 디버거에 표시가 되지만 
19xxxx.js 스크립트가 로딩되지 않았습니다. 
19xxxx.js파일이 다운로드 되지 않는 이유는 네트워크 문제인가요?

원격 컴퓨터는 인터넷이 허용되어 있어 모든 사이트에 접근이 가능한 상태로 알고 있는데, 
혹시 해결방법이 있을까요 ㅜㅜ

**Comment by daumPostcode** [comment]
@xqnstk 
네~

현재 IP리스트는 저도 알수가 없으며, 도메인 리스트만 제공 가능합니다.
아이피 주소는 직접 nslookup 같은걸 이용해서 확인하셔서 이용하셔야 합니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net

확인 부탁드립니다.

**Comment by xqnstk** [comment]
빠른 답변 감사드립니다 !!

아 문의해보니 현재 IP로는 허용이 가능한데 도메인으로는 허용이 되지 않아
방법이 포트를 적용해서 열 수 있는 방법이 있다고 하는데
해당 도메인의 포트를 알 수 있을까요?

추가적으로 이 기능들이 웹개발에 쓰이는데
웹포트도 알려주시면 감사드리겠습니다. ex) 80, 8080

**Comment by daumPostcode** [comment]
@xqnstk 
아뇨;; 포트정보는 제가 따로 들은건 없습니다.
저희쪽은 도메인을 신청만 할뿐, 네트워크쪽 관리는 인프라쪽에서 하게 되는데 따로 포트를 알려드릴 순 없을 것 같습니다
아마 내부에서는 모르겠지만, 기본적으로 80포트를 쓰지 않을까 한데요;;

추가로 제가 도메인을 알려드리는 이유는, 저도 똑같이 nslookup 명령어로 알려드리는 것이기 때문에,
그러한 것이며, 또한 ip가 바뀌거나 하는 상황을 저희가 컨트롤 하지 못하기 때문입니다.

즉 내부망에서 이용하실려면 해당 도메인들을 이용해서 ip주소를 찾아낸 뒤에, 이 아이피들을 직접 관리하셔야 합니다.
중간에 변경이 되거나 하면 안되는 부분만 다시 찾아내서 열어주고 하는 방식으로요.

이부분 참고해 주시면 감사하겠습니다.

**Comment by xqnstk** [comment]
안녕하세요~~

네트워크 부서에 문의하여 방화벽으로 따로 차단하지 않고, 자유롭게 이용할 수 있도록 변경하고
다시 시도해봤는데 여전히 "개체는 이 기능을 지원하지 않습니다." 라고 오류메시지가 뜹니다.

 function sample4_execDaumPostcode() {
        daum.postcode.load(function(){ 
            new daum.Postcode({ 

마지막 라인에서 디버깅을 걸어보니 daum은 object로 나오고, Postcode가 undefined로 나옵니다.
이 부분 역시 내부망에서 스크립트를 다운받지 못해 생기는 문제일까요?

**Comment by xqnstk** [comment]
자세한 답변 감사합니다 !!

현재 네트워크 부서에 문의하여 방화벽 차단을 모두 해제하였습니다.
테스트해보니 크롬에서는 팝업도 뜨고 잘 돌아가는데,
여전히 IE에서는 "개체가 이 기능을 지원하지 않습니다."라는 오류가 나옵니다.
참고로 조사식으로 봐보니 Daum은 Object가 들어와있고, PostCode는 undefined로 들어가있습니다.
혹시 IE에서도 가능하게 할 수 있는 방법이 있을까요 ?

알려주시면 감사하겠습니다 !!!

**Comment by daumPostcode** [comment]
@xqnstk 
안녕하세요~

현재 저희 우편번호 서비스의 경우, 
UI대응은 IE8~최신 모던브라우저, 기능적인 대응은 IE6~최신 모던브라우저까지 대응을 하고 있습니다. (IE6,7에서는 UI가 좀 깨질지언정 기능은 동작합니다)

해당 이슈의 경우에도 브라우저에서의 로딩문제로 보이는데요.한번 캐시삭제와 같은 작업을 한번 진행해 보시고, 여차하면 브라우저 초기화도 한번 진행한 다음에 확인해 보시는 것도 방법일 수 있을 것 같습니다.
현재 저희쪽 서버가 장애가 나거나, 팝업이 뜬이후의 기능적 문제가 아닌지라;; 
해당 이슈는 제가 도와드릴게 좀 한정적이네요; 
(저의 첫 댓글을 보시면, 해당 오류가 발생한 원인을 아실 수 있습니다. 한번 확인 부탁드립니다)

**Comment by xqnstk** [comment]
서버쪽의 방화벽 문제였던 것 같습니다
현재는 해결되었습니다 !!!
감사합니다 :)
