### ISSUE TITLE
도로명 등록 요청

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#434]
안녕하세요. 아래 도로명 주소 등록 부탁드립니다.

* 서울특별시 서초구 반포동 30-20( 도로명 : 서울특별시 서초구 고무래로 89)
* 건물명 : 반포써밋(반포센트럴푸르지오써밋)

![image](https://user-images.githubusercontent.com/39077176/55481027-7582d800-565c-11e9-8817-7bf74d66676f.png)

http://kko.to/ZIaa9qkTo

**Comment by daumPostcode** [comment]
@suseokpark 
안녕하세요~

질문글에 적어주신 도로명 주소의 매핑된 지번주소는 "서울 서초구 반포동 1342" 입니다.

말씀하신 "서울특별시 서초구 반포동 30-20" 이 주소의 경우엔 현재 도로명 주소가 발급되어 있지 않습니다.
행정안전부 도로명 검색 시스템에서도 나오지 않습니다.

행정안전부 도로명 검색 시스템에 직접 주소 등록을 해주셔야 할것 같습니다.
해당 사항에 대해선 [FAQ1](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)번 참고 부탁드립니다.

![image](https://user-images.githubusercontent.com/20675065/55537688-c398e980-56f7-11e9-8aab-8cad6404c948.png)

**Comment by suseokpark** [comment]
감사합니다!
