### ISSUE TITLE
팝업 안뜨는 현상

### ISSUE THREAD

**Issue by NileCallcenter** [daumPostcode/QnA#435]
cb.or.kr(학점은행) 홈페이지 학습자등록신청 시 `우편번호 찾기` 버튼이 눌러지지 않는다는 문의가 들어왔습니다.

현재 중국에 거주,  IP가 중국이라서 문제가 있는건지.. 브라우져 바꿔가면서 해봐도 어떤걸로도 새창이 뜨지를 않는다고 합니다.

중국 IP는 차단되나요? 아니라면 어떤 문제일까요?

**Comment by daumPostcode** [comment]
@NileCallcenter 
안녕하세요~

일단 해당 현상을 확인해 볼려고 했는데,, 현재 저희 개발 시스템이 MAC이고, 무엇보다 개인인증시스템이 공인인증서 방식이라;; 현재 인증서가 없어서 확인이 어렵네요;; 집에가서 한번 확인해보겠습니다.

일단 하나 말씀드릴수 있는건,
- 저희 서비스는 IP차단 같은 기능은 없습니다.
- 우편번호서비스는 이용하는 개발사(회사)에 API를 제공하는 것이지, 이를 가지고 활용을 하는건 개발사의 몫입니다.
- 버튼을 눌러서 저희 창을 띄우는건 저희쪽이 아닌 저희API를 가져다가 쓴 홈페이지 측의 문제입니다.
- 화면이 뜬 이후의 검색이나 여러가지 문제는 저희쪽 확인사항입니다.
- 검새결과를 클릭한 이후의 동선도 개발사의 몫입니다.

즉 저희는 검색을 하는 화면을 띄울 수 있는 API를 제공해주는 서비스이며, 전적으로 활용하는 것은 개발사의 몫입니다.
지금까지 CS들의 경험으로 비추어볼때
해당 현상은 보통 우편번호 찾기 버튼을 누르면 스크립트를 통해 저희 서비스를 띄우는데;
이 스크립트에서 오류가 나서 뜨지 않는 경우가 많았습니다. 이 스크립트는 그 홈페이지에 있는 코드입니다.

그리고 글로는 확인이 안되고 오류코드나 오류메세지를 보면 대충 어떤 문제인지 확인이 되는데, 현재 제가 접속을 할 수 있는 환경이 아니여서 테스트가 어렵습니다. 이부분은 집에가서 제가 한번 확인해 볼께요.

우선적으로는 학점은행측에 문의하시는게 맞을 것 같습니다.

**Comment by NileCallcenter** [comment]
학점은행 전산팀에서는 중국에서 국가차원으로 다음 사이트를 차단한 것 때문에 발생하는 문제라고 하네요~
