### ISSUE TITLE
onComplete콜백함수가 불리기 전에 onclose콜백함수가 먼저 불리는 현상

### ISSUE THREAD

**Issue by Leedokuem** [daumPostcode/QnA#436]
공식페이지에 있는 예제와같이 동적으로 로딩해서 라이브러리를 사용하고 있는데요.
(딱히 특별한 부분이 없다고 생각되어 제 코드를 올리지 않았는데 혹시 정확한 질문이 필요하다고 판단하시면 올릴게요!)
oncomplete가 먼저 잘 불리다가 저번주 부터 갑자기 onclose가 먼저 불리는데, 간헐적으로 그럴때가 있나요? 현재는 onclose에서 처리했던 부분을 oncomplete에서 먼저처리되도록 로직을 바꾸어서 문제는 없지만 너무 궁금해서 질문드려요. 특별한 부분이 있다고 한다면 nuxt라는 라이브러리를 이용해서 csr이 아닌 ssr로 웹페이지를 구현하고있고, plugins라는 nuxt의 기능을 이용해서 웹페이지가 로딩 되기전 

<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>

를 불러오도록 개발했다는 것입니다

개발환경은 (실제 스크립트가 동작하는 환경)
os : linux
browser : chrome

입니다. 수고 많으십니다. 감사합니다

**Comment by daumPostcode** [comment]
@Leedokuem 
네~ 안녕하세요~

네 저저번주에 배포시 사이드이펙트 체크를 못했네요;;
네 맞습니다; 현재 iOS 12.2에서 onComplete 부분에서 window관련 API가 호출되지 않는 버그때문에, onComplete함수를 비동기 처리하였습니다. 그래서 onclose보다 조금 늦게 실행이 됩니다.

해당 함수 호출 부분 확인해서 호출순서에 맞도록 수정하도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@Leedokuem 
안녕하세요~

금일 19시쯤 해당 현상 수정되어 배포되었습니다,.
불편을 드려 죄송합니다. 한번 확인 부탁드려요~

**Comment by Leedokuem** [comment]
@daumPostcode 감사합니다. 정상적으로 호출됩니다!!
