### ISSUE TITLE
Uncaught TypeError: daum.Postcode is not a constructor 오류 질문드립니다.

### ISSUE THREAD

**Issue by jiDoneKeun** [daumPostcode/QnA#438]
안녕하세요.
현재 다음 주소 API를 사용하고 있습니다.

PC환경에서는 에러가 없으나 모바일 안드로이드 및 IOS환경에서 확률적(?)으로 오류가 나오고 있습니다.
Uncaught TypeError: daum.Postcode is not a constructor

환경
운영 : linux
클라이언트 : Chrome, Safari (모바일) 
PC 또한 chrome 디버깅 환경을 모바일로 변환 후 여러차례 시도시에 에러 발행

소스코드 : 
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

var thisId = $("#revAddrSearch").attr("id");
			new daum.Postcode({
		        oncomplete: function(data) {
		        	
		        	// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
	                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
	                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
	                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.

	                
	                
	                // 우편번호와 주소 정보를 해당 필드에 넣는다.
	                if(thisId == "revAddrSearch"){
		                $('input[name=revMbrZipcode]').val(data.zonecode);
		                
		                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
			                  $('input[name=revMbrAddr]').val(data.roadAddress);
			                } else { // 사용자가 지번 주소를 선택했을 경우(J)
			                    $('input[name=revMbrAddr]').val(data.jibunAddress);;
			                }
		              	  //$('input[name=revMbrAddr]').val(fullAddr);
		              	  
					
		                // 커서를 상세주소 필드로 이동한다.
		                //$('input[name=revMbrAddrDtl]').val(extraAddr);
		                $('input[name=revMbrAddrDtl]').val('');
		                $('input[name=revMbrAddrDtl]').focus();
	                }
		        }
		    }).open();

입니다.
수고많으십니다.
감사합니다.

**Comment by daumPostcode** [comment]
@jiDoneKeun 
안녕하세요~
저희 서비스의 경우 총 2개의 스크립트를 부르게 됩니다.
한개는 postcode.v2.js 파일 (실제 입력하신 파일)
그리고 이 파일안에서 오늘 날짜 기준 190416.js 파일을 로딩합니다. 이 파일이 실제 코어스크립트이며
이 파일이 로딩이 되어야지만 daum.Postcode 클래스가 생성됩니다.

해당 오류는 네트워크 또는 여러 이유로 인해 코어스크립트가 로딩이 안되서 발생한 문제로 판단이 됩니다.
그래서 로딩에 관련된 스케쥴링을 좀더 명확히 할 수 있는
동적로딩 방식을 한번 이용해 보시는게 어떠실까 합니다. 이 방식을 이용하면 위처럼의 오류는 안뜰꺼고, 스크립트가 로딩이 안되면 아예 실행이 안되게 됩니다.

저희 가이드 페이지(https://spi.maps.daum.net/postcode/guidessl)의 기본사용법 중 두번째 동적로딩 사용하기 방법을 한번 이용해 보시길 추천드립니다.
autoload=false 파라미터와  daum.postcode.load 함수를 이용하는 방법입니다.

참고부탁드립니다.

**Comment by jiDoneKeun** [comment]
시간내어 답변달아 주셔서 감사합니다.
덕분에 해결되었습니다.
