### ISSUE TITLE
한 페이지에서 2개의 다음우편번호서비스 사용 가능한가요?

### ISSUE THREAD

**Issue by mixent** [daumPostcode/QnA#439]
한 페이지(동일 페이지)에서 2개 이상의 다음우편번호서비스 사용 가능한가요?
예를 들어, 회원가입페이지내에,
개인주소, 회사주소 2개를 입력하는 경우 입니다.

**Comment by daumPostcode** [comment]
@mixent 
네~ 사용가능합니다.
저희 가이드페이지 (https://spi.maps.daum.net/postcode/guidessl) 의 예제를 보시면
한화면에 4개를 이용합니다.

스크립트 로딩은 한번만 하시면 되고, 객체 2개를 이용하셔도 되고, 객체 1개로 사용하셔도 되구요. 구현은 개발자가 원하는대로 하실 수 있습니다.
