### ISSUE TITLE
주소 데이터  특수문자 

### ISSUE THREAD

**Issue by kiwon5** [daumPostcode/QnA#44]
안녕하세요 

주소검색시 주소에 아래와 같이 특수문자로 표현되는 경우가 있습니다. 사용시 특수문자로 인해 시스템 반영이 어려운 경우가 있는데요. 원래 정부에서 제공하는 data를 그대로 서비스 하시는지, 특수 문자 처리에 예외된 케이스 인지 궁금하며 만약 특수문자 출력이 정상이라면 제거하고 서비스 하실 계획이 있는지 문의드립니다. 

![3](https://cloud.githubusercontent.com/assets/12460630/19647830/e6696f56-9a3a-11e6-9cba-446e0656232d.png)

**Comment by daumPostcode** [comment]
@kiwon5 
네~ 안녕하세요~

결론부터 말씀드리자면 행자부로부터 받은 데이터 그대로 내려보내고 있습니다.
주소 또는 건물의 특수문자, 특히 주소의 경우 특수문자를 제외시키면 전혀 다른 이름이 될 소지가 있고, 요청자의 의도가 깔린 정보이기 때문에 등록된 정보 그대로 처리를 하고 있습니다. 그렇기 때문에 추후에도 주소나 건물명 등 주소정보 전반에 대해서는 따로 후처리를 진행할 계획은 없습니다.

만약 특수문자를 제외하고 싶으신 경우에는 oncomplete콜백 함수에서 정규식을 이용하여 모든 특수문자를 제거 한 후 사용하시면 될듯 합니다.
