### ISSUE TITLE
혹시 서비스가 유료화될 가능성이 있나요?

### ISSUE THREAD

**Issue by Wonseok1** [daumPostcode/QnA#441]
정말 혹시나해서 여쭤보는건데 다음 우편번호 서비스가 유료화될 가능성이 있나요?
있다면 언제쯤 실행될예정인지 알려주셨으면 바랍니다.
좋은 서비스를 제공해주시느라 고생이 많으십니다.

**Comment by daumPostcode** [comment]
@Wonseok1 
네~ 안녕하세요~

아뇨~ 유료화 계획은 없습니다.
현행 상태를 계속 유지할 것이라 생각이 되구요(국가에서 주소시스템을 또 바꾸면 모르겠지만요;;;)

걱정 안하셔도 될것 같아요~

다만, 현행 기준 버그성 개선은 지속적으로 할 예정이나, 신규기능의 추가는 좀 어려울 수 있는 점 참고부탁드립니다.
