### ISSUE TITLE
buildingCode 상이로 인한 주소문의

### ISSUE THREAD

**Issue by umtoto** [daumPostcode/QnA#442]
안녕하세요.
행자부 도로명주소의 건물관리번호와 맵핑 중 일치하지 않는 주소가 있어 질문드립니다.
혹시 아래의 건물관리번호에 해당하는 Daum 주소가 어떻게 되는지 알 수 있을까요?

buildingCode : '4418010500103110007007233'

**Comment by daumPostcode** [comment]
@umtoto 
안녕하세요~
네 해당 건물관리번호 주소 담당자분께 말씀드리도록 하겠습니다.
제가 DB를 볼 권한이 없어서;; 시간이 좀 소요될것 같아요;;

**Comment by umtoto** [comment]
네 확인 부탁드립니다~ 감사합니다

**Comment by daumPostcode** [comment]
@umtoto 
안녕하세요~ 담당자분께서 확인해주신 내용 공유드립니다.

해당 건물은 지난 2019년 2월에 삭제 되었습니다.
삭제되기 전 주소는 아래와 같습니다. 참고 부탁 드립니다.
- 도로명주소 : 충남 보령시 느랏길 21
- 지번주소 : 충남 보령시 명천동 311-7

이렇다고 합니다. 현재 행안부 사이트에서도 검색해보니 위 주소는 검색이 되지 않네요. 참고 부탁드립니다.
