### ISSUE TITLE
크롬 CSP 보안정책 관련문의 드립니다.

### ISSUE THREAD

**Issue by minszero** [daumPostcode/QnA#443]
[1]
![image](https://user-images.githubusercontent.com/50224381/57119621-a7e03c00-6da6-11e9-875e-7e43016d44ad.png)
[2]
![image](https://user-images.githubusercontent.com/50224381/57119667-f42b7c00-6da6-11e9-9bdd-f90b23bdc481.png)

현재 IE에서는 팝업창이 정상적으로 뜨는데 크롬에서는 팝업을 띄우면 크롬DevTools의 Console에는 [1]과같은 메세지가 나오며 화면은 [2]와 같이 나옵니다.
혹시 몰라 아래 두가지 방법을 모두 사용해 보았으나 같은 현상이여서 문의 드립니다. 
[방법1]
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>
---function 내부---
var postPopup = new daum.Postcode({
	oncomplete : function(data) {
		if(data.userSelectedType == "J" && data.userLanguageType == "K"){
			//지번주소 한글
		 	addr1 = data.jibunAddress;
		}else if(data.userSelectedType == "R" && data.userLanguageType == "K"){
			//도로명주소 한글
			addr1 = data.roadAddress;
			if(data.buildingName !=""){
				addr1 = addr1 + " (" + data.buildingName + ")";
			}
		}else if(data.userSelectedType == "J" && data.userLanguageType == "E"){
			//지번주소 영문
			addr1 = data.jibunAddressEnglish;
		}else if(data.userSelectedType == "R" && data.userLanguageType == "E"){
			//도로명주소 영문
			addr1 = data.roadAddressEnglish;
		}
		sheet2.SetCellValue(Row, "zip", data.zonecode);
		sheet2.SetCellValue(Row, "addr1", addr1);
		sheet2.SetCellValue(Row, "addr2", "");
		sheet2.SetCellValue(Row, "addrEng", data.addressEnglish);
	}
}).open();
[방법2]
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false"></script>
---function 내부---
daum.postcode.load(function(){
	new daum.Postcode({
		oncomplete: function(data) {
			// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
			// 예제를 참고하여 다양한 활용법을 확인해 보세요.
			if(data.userSelectedType == "J" && data.userLanguageType == "K"){
				//지번주소 한글
				addr1 = data.jibunAddress;
			}else if(data.userSelectedType == "R" && data.userLanguageType == "K"){
				//도로명주소 한글
				addr1 = data.roadAddress;
				if(data.buildingName !=""){
					addr1 = addr1 + " (" + data.buildingName + ")";
				}
			}else if(data.userSelectedType == "J" && data.userLanguageType == "E"){
				//지번주소 영문
				addr1 = data.jibunAddressEnglish;
			}else if(data.userSelectedType == "R" && data.userLanguageType == "E"){
				//도로명주소 영문
				addr1 = data.roadAddressEnglish;
			}
			sheet2.SetCellValue(Row, "zip", data.zonecode);
			sheet2.SetCellValue(Row, "addr1", addr1);
			sheet2.SetCellValue(Row, "addr2", "");
			sheet2.SetCellValue(Row, "addrEng", data.addressEnglish);
		}
	}).open();
});

**Comment by daumPostcode** [comment]
@minszero 
안녕하세요~
현재 크롬 버전 74.0.3729.131(공식 빌드) (64비트)
에서 공식가이드페이지에서는 해당 현상이 발생하지 않는데요.

이용하시는 사이트에 CSP설정이 되어 있는게 아닐까 합니다. 이부분은 저희쪽에서 어떻게 할 수는 없고,
해당 설정에 저희쪽 도메인을 풀어주셔야 될것 같습니다.
