### ISSUE TITLE
우편번호 검색 시 데이터중복 및 도로명주소 누락

### ISSUE THREAD

**Issue by joon7897** [daumPostcode/QnA#444]
![image](https://user-images.githubusercontent.com/26395948/57497118-4c1b3300-7311-11e9-8100-ae44a171c42b.png)

위 이미지는 우편번호 : 12109 를 조회하여 2페이지 가장 마지막에있는 주소를 선택한 결과입니다.

시스템 구성상 지번/도로명 주소가 모두 필요한데 팝업에서 도로명 주소를 선택해도

addressType: "J", roadname: "", bname1: "" 으로만 셋팅되는 상태입니다.

![image](https://user-images.githubusercontent.com/26395948/57497745-e11f2b80-7313-11e9-92e5-01b1a15faf5e.png)

문제가되는 주소는 "**경기 남양주시 별내4로 25 미리내마을 4-2단지**" 이고,

1페이지에 동일한 데이터가 있는데 이건 지번/도로명 잘 가져옵니다..

외부 사용자들이 선택하는거라 단속이 어렵고 다른 케이스들이 있을지 몰라 섣불리 예외처리 하기가 어렵네요... 

우편번호로 검색하는 경우에만 위 오류데이터가 조회되는데 삭제나 제외시킬 수는 없는지 피드백 부탁드립니다!

**Comment by daumPostcode** [comment]
@joon7897 
안녕하세요~

첫번째 
반복현상은 저희 검색엔진의 시스템상 발생하는 문제인데요.
쉽게 설명을 드리면,

저희 시스템은 도로명주소와 지번주소가 서로 매핑되어 있습니다. 
그래서 검색엔진에서는 항상 도로명-지번 세트와, 지번-도로명 세트를 모두 검색해서 가져오게 됩니다.
이때 검색질의어가 도로명주소, 기초구역번호(새우편번호) 등 도로명 주소를 나타내는 질의어라면
"도로명-지번" 세트를 먼저 보여주고, 그 뒤에 "지번-도로명" 세트를 붙여서 보여줍니다.
마찬가지로 질의어가 지번형식의 타입이라면 "지번-도로명"세트를 먼저 보여주고, 뒤에 "도로명-지번"세트를 붙여서 보여주게 됩니다. 
그래서 현재 검색된 결과를 잘 보시면, 
계속 "도로명-지번" 순으로 검색결과가 나오다가, 어느순간 "지번-도로명"순으로 변경되는 것을 확인하실 수 있습니다. 그리고 이 두 데이터는 배치순서만 다르지 동일한 데이터이며, 그리고 사용자가 어떠한 값을 누르더라도 내려가는 데이터상 동일한 정보를 추출할 수 있도록 데이터를 셋팅하고 있습니다.
(해당 건은 제가 수정을 할 수가 없는 사안이라; 해당 개발팀에 문의넣어볼 수 있는데요, 수정이 어려울 수 있습니다;;)


두번째, 말씀해주신 데이터의 경우
addressType의 경우엔 검색 리스트의 한 셀을 보시면
```
"도로명" XXXX
"지번" XXXX

또는

"지번" XXXX
"도로명" XXXX
```
이렇게 되어 있을 거에요.
이때 윗줄이 메인주소, 아랫줄이 연관주소라고 하는데,
addressType은 이 연관주소의 타입을 가리킵니다. 즉 유저가 무엇을 선택했는지는 상관없고, 리스트의 한 셀에 배치된 형식에 따라 값이 결정됩니다.
유저가 어떤걸 선택했냐를 알고 싶으신 경우엔 userSelectedType 이라는 변수가 있으니 이걸 한번 확인해 보시면 좋을것 같습니다.

bname1 의 경우엔, 읍/면 지역일 경우에 "읍"과 "면" 정보가 들어갑니다.
"동" 지역일 경우엔 들어가지 않습니다. "동" 지역의 경우 "시" 뒤에 바로 오거나, "구" 정보가 앞에 붙을 수 있으나, "시"와 "구" 정보는 sigungu 쪽에 들어가기 때문에 bname1은 셋팅되지 않습니다. 
이부분 참고 부탁드립니다.

마지막 roadname1의 경우엔
이부분은 데이터상 버그로 판단됩니다.
말씀해 주신 데이터 리스트상 "불암로 70" 주소와 동일한 패턴인데, 값이 빠져있다는건 내부이슈로 판단이 됩니다.
해당건의 경우 서버담당자분께 문의드려서 최대한 빨리 처리하도록 하겠습니다.



이외, 이용하시는 방법인 사용자가 어떤 주소를 선택하더라도
"도로명 주소"와 "지번 주소"를 모두 가져야 할 경우에는 저희가 내리는 데이터상
- roadAddress, jibunAddress
- autoRoadAddress, autoJibunAddress ( 앞에 auto가 붙은 것은 1:N 매핑 데이터시에 이용됩니다, 가이드 페이지 참고)

위 4개의 변수를 확인하시면 항상 데이터를 추출하실 수 있으니 이점 참고 부탁드립니다.

**Comment by joon7897** [comment]
![image](https://user-images.githubusercontent.com/26395948/57605723-45571f00-75a2-11e9-9279-8227bfd4a617.png)

05715 로 검색하여 3페이지에 위치한 데이터 입니다.

도로명 주소 선택을 위한 '더보기'를 눌러 선택하면 roadname을 가져오나

그렇지 않고 기본 데이터 선택 시 문의드렸던 내용과 동일하게 roadname을 가져오지 못합니다.

내부 데이터 조정에 도움이 될까해서 덧글 남깁니다.

**Comment by daumPostcode** [comment]
@joon7897 
네! 안녕하세요~
네 수정되면 제가 댓글로 추가로 알려드릴거에욤~
추가로 알려주신 주소셋도, 같은 현상임을 확인하였습니다. 
현재 엔진개발자분게 문의드렸고 확인이 된상태이므로 곧 수정이 되지 않을까 합니다.
아무튼 수정이 되면 말씀드리겠습니다~

**Comment by daumPostcode** [comment]
@joon7897 
안녕하세요~
엔진 개발자분께 답변을 받았으며,
현재 시간부터는 모두 수정이 되었을 것이라고 합니다.

현재 말씀해 주신 검색어 2개로 확인결과 정상동작하네요~
한번 확인 부탁드립니다.

**Comment by joon7897** [comment]
네 정상 데이터 확인하였습니다. 감사합니다 ^^
