### ISSUE TITLE
주소지 추가 요청

### ISSUE THREAD

**Issue by Skycheon** [daumPostcode/QnA#446]
아래 주소지가.. 카카오 지도에는 검색이 되는데 우편번호 서비스에선 검색이 안됩니다.(도로명, 지번 둘다 안됨)

예전부터 안됐는데.. 계속 안돼서.. 추가 요청 드립니다.

지명 : 한국전력공사 경기북부지역본부
주소 : (신) 경기도 의정부시 용민로19번길 80
          (구) 경기도 의정부시 용현동 267-8

**Comment by daumPostcode** [comment]
@Skycheon 
안녕하세요~

해당 주소의 경우 안타깝게도;; 현재 시스템상 추가가 어렵습니다.
[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 을 보시면 "추가사항" 이라는 부분이 있는데요

해당 한전의 주소의 경우 보안주소라는 이유로 좌표값을 저희에게 주지 않습니다.
그래서 저희 시스템상 매핑이 불가능해서 현재 행안부 도로명검색 시스템에서 검색시 지도마크가 없는 주소들은 표출이 불가능합니다,.

이는 카카오지도에서도 확인이 가능한데요.
"한국전력공사 경기북부지역본부" 이렇게 검색을 할 경우에는 "장소"로 검색이 된것이며, 장소에 매핑된 주소가 나오게 됩니다. 이때도 주소를 잘 보시면 도로명주소가 아닙니다. 
반면에 주소(지번이나 도로명 아무거나)로 검색을 하면 나오지 않습니다. 이는 제가 위에 말씀드린 것처럼 매핑이 안되어서 발생하는 문제입니다.

해당 이슈의 경우엔 내부적으로 논의를 한적이 있는데요, 
일단 수정되어야 되는 파트가 상당히 광범위해서 현재로써는 수정이 조금 어려울것 같습니다.
최상의 서비스를 드리고 싶은데 마음대로 되진 않네요;;;;

아무튼 불편을 드려 죄송합니다.
