### ISSUE TITLE
설치 후, Postcode 컴포넌트 render 해보면 에러가 납니다.

### ISSUE THREAD

**Issue by lshwa80** [daumPostcode/QnA#447]
동일하게 나오고 있는 에러는,

1. Warning: useEffect received a final argument during this render, but not during the previous render. Even though the final argument is optional, its type cannot change between renders.

2. Uncaught TypeError: Cannot read property 'document' of null

입니다.

기본적으로 화면에 출력조차 안되고 있습니다.
에러가 나더라도 계속 새로고침을 하면, 어쩌다 한 번 위 에러 2가지 표시와 함께 나옵니다.

create-react-app 으로 간단하게 프로젝트에 적용 예정인데,
수정이 되었으면 좋겠습니다.
사용 리액트 버전은 16.8.6 입니다.

**Comment by daumPostcode** [comment]
@lshwa80 
안녕하세요~

현재 제가 공식적으로 배포하는 라이브러리는 plain javascript로 구성된 라이브러리이며
React나 Angular, Vue 등으로 포팅된 라이브러리는 없습니다.
이런 추가 라이브러리의 경우 외부의 개발자분께서 따로 개발하셔서 공유해 주신 것으로, 수정권한이 저한테 있지 않습니다.
해당 라이브러리의 경우 라이브러리 개발자분께 말씀해 주시면 감사하겠습니다.
그래서 만약 저희 API문제라면 라이브러리 개발자분과 협의해서 수정해볼 수 있을 것 같습니다.

**Comment by bernard-kms** [comment]
혹시 동일한 현상을 겪고 이 이슈를 보고 계시다면, https://github.com/bernard-kms/react-daum-postcode/issues/4 를 참조해주세요
