### ISSUE TITLE
onComplete 콜백까지 잘오는데 종료가되지않습니다

### ISSUE THREAD

**Issue by kotran88** [daumPostcode/QnA#448]
ionic v3 환경입니다
아래와 같은 코드로 잘 뜨고, 주소를 선택할경우 onComplete 콜백으로 잘 옵니다.
done 얼럿도 뜨고...근데 브라우저가 종료가 안됩니다...ㅜㅠ 이거 어쩌나요 ㅜ

```
daum.postcode.load(function(){
        new daum.Postcode({
            oncomplete: function(data) {
              console.log(data);
              window.alert("done");
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
                // 예제를 참고하여 다양한 활용법을 확인해 보세요.
            }
        }).open({
          autoClose: true //기본값 true
      });
    });
```

**Comment by daumPostcode** [comment]
@kotran88 
안녕하세요~

open의 경우 팝업을 띄우는 함수인데,
만약 일반 웹뷰 환경이라면 웹뷰커스터마이징을 좀 하셔야 합니다. 
보통 웹뷰에서는 기본적으로 팝업이 지원되지 않을거에요. 팝업이 열리긴 하나 그건 잘보면 페이지 자체가 변경되는 것이지 팝업이 아닙니다.

저기서 종료가 안됬다는 것은 저 onComplete콜백은 팝업 모듈에 바인딩이 되어 실행되기 때문에 실행이 되는 것이나, 실제 종료를 하려면 부모페이지에서 팝업을 실행시킨 주체가 필요한데, 그 레퍼런스가 없어져서 그럴거에요.

그래서 만약 일반브라우저(크롬이나 사파리 등)가 아닌 웹뷰라면 팝업보다

embed를 이용해서 레이어나 끼워넣기 예제를 사용하시는걸 추천드립니다.
이중 스크롤 이슈를 회피하려면 끼워넣기 예제를 참고해 보시는것도 좋을 것 같아요~
해당 예제는 공식 가이드 문서에 있으니 참고부탁드립니다.

추가 질문이 있으시면 댓글 주세요~
