### ISSUE TITLE
주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by namsm05** [daumPostcode/QnA#449]
경기도 파주시 광탄면 보광로 962
경기도 파주시 광탄면 마장리 406

둘다 같은 주소고, 행자부에서도 검색됩니다.
다음api에서는 검색되지 않습니다.

**Comment by daumPostcode** [comment]
@namsm05 
안녕하세요~
해당 주소는 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 의 추가사항 부분을 보시면 확인하실 수 있습니다.
현재 저희 시스템에선 FAQ1번과 같은 형태를 띄는 주소의 경우 매핑을 할수 없어서 서비스 노출이 어렵습니다.

현재 주소시스템이 이렇게 구현되어 있어서 바로 변경이 어려운 상황입니다.
해당건의 경우, 내부적으로 정책상 풀어야 되는 문제가 많아서 고려중인데요.

일단 현재로써는 보여드릴 방법이 없음을 말씀드립니다.

도움을 드리지 못해 죄송합니다.
