### ISSUE TITLE
강제종료..

### ISSUE THREAD

**Issue by lys6115** [daumPostcode/QnA#45]
크롬 최신버전 업데이트이후 주소검색 버튼 클릭시(팝업형태) 크롬이 강제종료되더라구요..
다른 브라우저에서는 잘실행됩니다.
어떤문제인지 몰라 구글측에도 연락은 해놨는데,  이게 어느부분에서 충돌후 종료되는지 알수 있을까요?

**Comment by daumPostcode** [comment]
@lys6115 
네~ 안녕하세요~

현재 크롬 버전 54.0.2840.71 (64-bit) (Windows, Mac 동일)에서 가이드 페이지 및 자체 테스트케이스 실행시 말씀하신 오류가 재현이 되지 않네요;;

예전에 크롬을 업데이트하고 나서 서비스가 실행되지 않는다는 현상이 있었는데요, 해당 오류의 경우 사용자께서 크롬을 재설치 한 후 사라졌다고 합니다. [해당 이슈 참고 링크](https://github.com/daumPostcode/QnA/issues/35)

저또한 브라우저와 OS의 작동방식에 대해 정확히는 모르지만, 예전에 IE에서 MS Office설치시 설치되는 파일때문에 windows.open() javascrpt 함수가 동작하지 않던 문제가 있었습니다. 이와 비슷하게 OS자원을 활용하다 보니 충돌이 나는게 아닌가 하는 생각이 조금 드네요;;

그런데 현재 저희쪽에서는 재현이 되지 않기 때문에 혹시 저희가 접근할 수 있는 URL이나, 전반적으로 살펴볼 수 있는 코드뭉치가 있다면 알려주시면 좀 더 분석해 보도록 하겠습니다;;

**Comment by lys6115** [comment]
네 재설치 후에 정상 작동이 됩니다! 감사합니다.

**Comment by daumPostcode** [comment]
@lys6115 
다행이네요;; 최신 크롬이 좀 문제가 있어보입니다. 말씀해 주신 문제 외에도 CSS관련된 문제도 있네요;;;

아무쪼록 잘 해결되셔서 다행입니다 ^^
