### ISSUE TITLE
인천 서구 마전로99번길로 검색시 구상세주소가 0 나옵니다.

### ISSUE THREAD

**Issue by parkgumju** [daumPostcode/QnA#451]
인천 서구 마전로99번길로 검색시 구상세주소가 0 나옵니다.
구주소를 지원 하지 않는다면 아에 표시가 안되거나 다른 방식으로 바꿔 주셨음 좋겠습니다.

**Comment by daumPostcode** [comment]
@parkgumju 
네~ 안녕하세요~

"인천 서구 마전로99번길"로 행안부 도로명검색시스템에서 검색해보니
아래 스샷과 같이 검색이 됩니다. 현재 저희 시스템의 기반주소 데이터는 행안부 데이터를 따르고 있으며, 현재 검색이 되는 것으로 보아 강제로 삭제는 어렵습니다.

해당 주소가 오류인지는 데이터 담당자분께 한변 여쭤보도록 하겠습니다.
감사합니다.

![스크린샷 2019-05-24 오후 1 51 59](https://user-images.githubusercontent.com/20675065/58303460-26bb1880-7e2b-11e9-9822-0ab021d33cc4.png)

**Comment by daumPostcode** [comment]
@parkgumju 
안녕하세요~

데이터 담당자분께 문의결과 아래와 같은 답변을 받았습니다.
참고부탁드립니다.

```
해당 지역에 지번주소가 발급되지 않았을 때, 지번주소가 0으로 표기되는데요.
(예 : 경기도 화성시 수노을1로 148)

관련 기관에 문의한 결과,
해당 지역은 마전지구 구획사업정리에 포함되어 있어 해당 지번이 없는 것으로 확인되었습니다.
사업이 완료되는 시점에 지적도 함께 업데이트 될 예정이며, 행안부에서 업데이트가 되면 하루 뒤에 우리 서비스에도 반영될 예정입니다.
```

감사합니다.
