### ISSUE TITLE
주소검색이 되지 않습니다.

### ISSUE THREAD

**Issue by yeakhus** [daumPostcode/QnA#452]
주소 검색이 되지 않습니다. 추가해 주세요.
행안부 주소 검색에서는 검색이 됩니다.

강원도 고성군 간성읍 수성로 37-12

**Comment by daumPostcode** [comment]
@yeakhus 
안녕하세요~

![image](https://user-images.githubusercontent.com/20675065/58530290-2a7ae080-8219-11e9-9ac3-9815ef3e26f6.png)

해당 이슈 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고부탁드립니다.

현 시스템상 위와 같은 주소는 추가가 어렵습니다. 이점 양해 부탁드립니다.
해당 이슈의 경우엔 현재 수정에 필요한 사항을 점검중에 있습니다. 워낙 여러서비스 여러부서에 얽힌 문제라서 쉽지 않네요. 시간이 오래 걸릴 수 있는 점 양해 부탁드립니다. 
불편을 드려 죄송합니다.
