### ISSUE TITLE
팝업 중복 관련 문의

### ISSUE THREAD

**Issue by ParkJaeSungOne** [daumPostcode/QnA#454]
팝업이 여러개 열리는 걸 방지할 수있는 방법이 있을까요 ?
팝업이 여러개 열렸을 경우 값이 들어가지 않는 현상이 발생합니다.

**Comment by daumPostcode** [comment]
@ParkJaeSungOne 

안녕하세요~
저희 가이드 페이지의 함수부분에 보시면 해결책이 있습니다.
https://spi.maps.daum.net/postcode/guidessl#methods

open함수의 인자로 popupName 값을 설정하면 여러개 뜨는 것을 방지할 수 있습니다.
예제 샘플도 같이 제공중이니 한번 확인 부탁드려요~

감사합니다.
