### ISSUE TITLE
주소 검색 이슈

### ISSUE THREAD

**Issue by ljh8993** [daumPostcode/QnA#455]
하이브리드앱으로 진행하고있는데요
1. 주소 검색
2. 검색 결과물이 많아서 뜨는 도로명, 지역명 전체 버튼을 클릭해서 검색한 경우
페이지를 pop할 경우에
프로그램 자체가 재부팅이 됩니다.
데이터를 받아오지 않고 검색만 해도 나타나는 현상입니다.
해결방안이 있을까요?

**Comment by daumPostcode** [comment]
@ljh8993 
안녕하세요~

하이브리드앱의 경우엔 전확히 저희가 진단을 하는게 어려운데요;; 일단 웹뷰를 활용한 서비스는 저희가 공식적으로 대응해 드리진 못하는점 말씀드립니다.

1. 주소를 검색을 하거나
->> 현재 주소를 검색할때 form submit 방식을 활용합니다. 만약 이게 문제일것 같으시다면, 생성자 옵션으로 submitMode : false 를 한번 넣어서 테스트 해보시기 바랍니다. 이 방식은 location.replace를 활용합니다.

2. 도로명 필터링도 일반주소검색과 동일합니다.
우선 도로명/지역명 전체버튼의 경우 클릭하는 순간 데이터를 가져오고 렌더링합니다.
이 데이터를 선택했을 경우에도 기본적으로 form submit 방식으로 전달이 되며, 1번에 말씀드린 submitMode:false 로 설정하면 location.replace로 변경됩니다.
일단 저희 서비스의 동작방식은 이러하고, 이러한 동작은 모두 iframe내부에서 동작합니다.

혹시 웹뷰가 이 iframe의 내부에서의 페이지 이동까지 잡는지 한번 확인해 보시는 것도 좋을 것 같습니다.
일단 제가 앱개발자(또는 하이브리드앱 개발 경험)이 전무해서;; pop을 한다는 의미를 대충 모달로 띄운걸 내린다는 의미로 보이긴 하는데; 정확히 해결책을 말씀드릴 수가 없는점 양해 부탁드립니다.

혹시 해당 현상이 일반 크롬브라우저나 사파리에서도 발생하는지 확인 부탁드립니다. 일반브라우저에서 정상동작한다면, 그건 웹뷰문제일 확률이 매우 높습니다.

한번 확인 부탁드려요.

**Comment by ljh8993** [comment]
옵션을 설정하니 정상작동이 됩니다
하이브리드 앱에서는 pop과 push로 페이지간 이동을 해요
pop한다고 말씀드린건 뒤로가기로 생각하시면 될 것 같습니다

form submit 방식과 location.replace 방식의 어떤 차이때문에
뒤로갔을 때 form 방식은 새로고침을 하게 되는 건가요?

**Comment by daumPostcode** [comment]
@ljh8993 
form submit은 하나의 새로운 페이지로 이동되는 것이라고 생각하시면 됩니다. 그래서 history에 스택이 쌓이죠.
반대로
location.replace는 페이지 자체를 변경하는 것이라 history에 스택이 쌓이지 않습니다.
이 차이라고 생각하시면 되요.

위 모드를 추가한 이유는 몇몇 단말에서 여러번 검색하면 history가 계속 쌓이는데, 뒤로가기시에 이렇게 쌓이는 불필요한 페이지들이 pop되면서 오류와 같은 현상이 발생해서 추가하게 되었습니다.
iframe 내부에서의 페이지 이동인데 그걸 잡더라구요 ㅎㅎ

도움이 되셨으면 좋겠네요~

**Comment by ljh8993** [comment]
도움 감사드립니다
