### ISSUE TITLE
주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by kfmaDev** [daumPostcode/QnA#456]
번지가 176 또는 17-6 으로 끝나는 주소는 검색에 오류가 있는 거 같은데 확인 부탁드립니다.

 - 충북 진천군 초평면 은암리 176

 - 경기도 성남시 분당구 금곡동 176

 - 서울특별시 송파구 신천동 17-6

**Comment by daumPostcode** [comment]
@kfmaDev 
네~ 안녕하세요!

제보 감사드립니다.
해당현상 담당자분께 공유드리도록 하겠습니다.
수정이 되면 다시 댓글로 답변 드리도록 할께요~

**Comment by daumPostcode** [comment]
@kfmaDev

안녕하세요~
저번주 금요일 저녁 검색엔진 담당자분께서 해당 사항 수정하여 실서버에 적용하였습니다.
늦게 공유드려 죄송합니다. 한번 확인 부탁드립니다.~
