### ISSUE TITLE
주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by 1jinsu** [daumPostcode/QnA#458]
도로명으로는 강원도 고성군 토성면 뒷골길 106
지번으로는 강원도 고성군 토성면  학야리 221
우편번호는 24753
행안부의 도로명 주소 안내에는 뜹니다.

**Comment by daumPostcode** [comment]
@1jinsu 

안녕하세요~
해당주소의 경우 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)

"추가사항" 부분에 해당되는 내용입니다.

현재 위와 같은 주소는 검색이 되지 않는데요. 이부분은 시스템적으로 현재로써는 처리가 불가능하여 추가가 어려움을 말씀드립니다.

불편을 드려 죄송합니다.
