### ISSUE TITLE
Webview에서 우편번호 검색 페이지가 로딩되지 않고 빈 페이지로 나옵니다.

### ISSUE THREAD

**Issue by jyhwangaaa** [daumPostcode/QnA#459]
Webview에서 우편번호 검색 페이지가 로딩되지 않고 빈 페이지로 나옵니다.
특정단말 : SM-P585NO
안드로이드 버전 : 8.1.0

**Comment by jyhwangaaa** [comment]
크롬 버전을 75.0.3770.67 로 업그레이드 하고 문제가 발생 하였습니다!!!

**Comment by RyuDJ** [comment]
저도 동일한 증상이 발현되네요.. 혹시 해결하셨나요?

**Comment by daumPostcode** [comment]
@jyhwangaaa 
@RyuDJ 

안녕하세요~
현재도 동일한 이슈 발생중이실까요?
주말에 장애가 발생하진 않았으나, 발생전에 장애를 막기위한 처리가 있었습니다. 
혹시 지금도 동작하지 않는다면 말씀 부탁드립니다.

**Comment by uk9336** [comment]
일부 기기에서 페이지가 올라오지않고 빈 흰화면이 올라옵니다 해당 크롬버전의 문제인가요 ?

**Comment by younkgkyu** [comment]
저도 동일한 증상이 발생하고 있습니다.
대응 가능한 방법이 있을까요?
AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.89 Mobile Safari/537.36
