### ISSUE TITLE
크롬 신규버전 강제종료

### ISSUE THREAD

**Issue by brendaniel** [daumPostcode/QnA#46]
확인부탁드립니다.
팝업이 실행되고 
new daum.Postcode  구문 넘어가는순간에 부모창도 닫혀버립니다.

**Comment by daumPostcode** [comment]
@brendaniel 

네~ 안녕하세요~

현재 정보가 너무 없어서 확인이 어려운데요. 저희쪽 컴퓨터에서는 현재 재현이 되지 않습니다.

OS정보, 오류가 나는 브라우저 정보 및 저희가 접근할수 있는 URL이나 코드 뭉치가 있다면 알려주셔야 저희가 확인이 될것 같습니다.

**Comment by jae-eok-Kim** [comment]
저도 같은 문제로 고생했는데 크롬을 지우고 재설치 해서 해결했어요
