### ISSUE TITLE
주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by f2jazz** [daumPostcode/QnA#460]
서울특별시 용산구 한강로2가 342번지 래미안용산 B동

위 주소가 검색되지 않습니다.

**Comment by daumPostcode** [comment]
@f2jazz 
네~ 안녕하세요~

현재 해당주소관련 데이터 담당자분께 공유드렸습니다.
답변 받는대로 댓글드릴게요~

불편을 드려 죄송합니다

**Comment by daumPostcode** [comment]
@f2jazz 
지금 다시 확인해보니; 해당 주소의 경우엔 juso.go.kr에서도 검색이 되지 않네요.
그럼 저희 시스템에도 안나오는게 맞습니다.
데이터 담당자분께 받은 답변으로는 "문의 하신 주소는 해당 구역 필지정리로 없어진 지번"이라는 답변을 받았습니다.
현재 저희 우편번호서비스말고 PC지도나 이런곳에서 나오는 이유는 현행화가 덜되서 그런것으로, 해당 이슈는 이번주 말에 반영 예정입니다.

레미안용산 의 주소는 "서울 용산구 한강로2가 422번지" 이게 맞을거에요~

감사합니다.
