### ISSUE TITLE
정말 너무 급합니다. 꼭 도와주시기 바랍니다.

### ISSUE THREAD

**Issue by hoony92** [daumPostcode/QnA#462]
현재 다음 주소 api를 사용하여 앱을 만들고 있습니다.
테스트를 위해 웹에서 돌려봤을땐 잘돌아가는데 
cordova를 입힌 어플(앱) 에서는 아예 검색창 조차 뜨질 않습니다.
일단 https 와 http 모두 다사용설정해보았으며 더이상 접근 방법조차 알수가 없어서 이렇게 물어봅니다.
이클립스로 개발하며 vue.js 를 사용하고 cordova를 사용하여 앱을 만듭니다.

에러 내용은 

service.v2.min.js:4 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'http://' in a call to 'postMessage'.
    at b (http://t1.daumcdn.net/postcode/cssjs/service/1557749450704/service.v2.min.js:4:15285)
    at Object.d [as sendResizeMessage] (http://t1.daumcdn.net/postcode/cssjs/service/1557749450704/service.v2.min.js:4:15432)
    at http://t1.daumcdn.net/postcode/cssjs/service/1557749450704/service.v2.min.js:5:20176

이런식으로 뜨며 다시한번 말씀드리면 웹에서는 잘되는데 앱에서는 버튼클릭시 아무 화면도 뜨질 않습니다. 
빨리 답변주시면 감사하겠습니다.  감사합니다.!

**Comment by daumPostcode** [comment]
@hoony92 
네~ 안녕하세요~

톡으로 말씀드린 것처럼 처리하시면 될것 같아요~
FAQ10번과 관련된 이슈로 보입니다~
