### ISSUE TITLE
Webview에서 우편번호 검색 페이지가 빈 페이지로 나옵니다.

### ISSUE THREAD

**Issue by jhlee7509** [daumPostcode/QnA#464]
안드로이드에서 웹뷰로 불러와 사용중입니다.
한두달가량 문제없이 잘 사용하고있었습니다.
오늘 확인해보니 일부 사용자 혹은 장치에서 검색 페이지가 빈 페이지로 나온다는 것을 확인했습니다.
모든 사용자나 동일한 조건의 사용자가 아니라 문제 찾기가 어려워 문의 드립니다.

아래가 정상 작동하는 기기 스크린샷 화면이

![검색 페이지](https://user-images.githubusercontent.com/44347495/59327361-3b9d1480-8d24-11e9-8df4-68122ffef22d.jpg)

아래가 빈 페이지로 작동하는 기기 스크린샷 화면입니다

![빈 페이지](https://user-images.githubusercontent.com/44347495/59327362-3b9d1480-8d24-11e9-8910-f98f1da10cf8.jpg)

참고로 하나는 유심이 있고 하나는 없는 폰입니다.
하지만 유심이 없는 다른 폰에서도 정상 작동하여 유심의 문제는 아니라고 생각하고
같은 네트워크 환경에서 진행 하였다는 점도 알려드립니다.

**Comment by daumPostcode** [comment]
@jhlee7509 
네~ 안녕하세요~

현재 저희쪽 서버의 장애나 그런 상황은 없었는데요;;
웹뷰의 경우엔 각 웹뷰의 개발자마다 어떻게 개발했느냐에 따라 다르고, 케이스가 너무 다양해서, 공식 지원대상은 아닙니다.

혹시 해당 문제가 발생했을때, 오류메세지를 알 수 있으시다면 오류메세지를 같이 주시면 좋을 것 같습니다.
직접 개발하신 것이라면 확인 가능하실것 같아요.

**Comment by jhlee7509** [comment]
오류 메시지 잡아보려고 시도했는데 오류메시지가 안잡히네요
웹상에서는 문제없이 잘 나옵니다. 앱 내부의 웹뷰에서도 되는사용자 안되는 사용자가 기준이 없어서
현재 웹뷰 띄우기 위한 코드는 이렇습니다.

1. <script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=true"></script>
2. <script>
3.     new daum.Postcode({
4.         oncomplete: function(data) {
5.             if(data.userSelectedType=="R"){
6.                 window.TestApp.setAddress(data.zonecode, data.roadAddress, data.buildingName);
7.             }
8.             else{
9.                 window.TestApp.setAddress(data.zonecode, data.jibunAddress, data.buildingName);
10.             }       
11.         }
12.     }).open();
13. </script>

**Comment by daumPostcode** [comment]
@jhlee7509 
화면이 아예 안뜬다는 것은 페이지 호출 자체가 안된 것으로 판단이 됩니다.
이는 제가 몇일 전에 패치를 하였는데, 저희쪽으로 전달하는 쿼리스트링값이 너무 길어질 경우에 발생할 수도 있는데, 현재의 모던브라우저에서는 해당 이슈가 발생할 확률은 좀 낮거든요, 혹시 저희 웹뷰가 뜨는 창의 전체 fullURL이 몇글자 정도가 될까요?

추가로 open()의 경우 웹뷰 구현정도에 따라 다르지만, 팝업이 아닌 원본 뷰를 대체하는 것으로 실행이 될 수도 있는데요. 그래서 웹뷰에서 사용할때는 open 함수를 추천드리지 않습니다.
한번 embed를 이용해서 구현해 보시는건 어떨까 합니다.
