### ISSUE TITLE
도로명주소의 데이터값을 제대로 받아오지 못하는것 같습니다.

### ISSUE THREAD

**Issue by everymeari** [daumPostcode/QnA#465]
경기 수원시 팔달구 권광로 181 <-- 이주소의 도로명주소로 검색했을시
window.CITApp.setAddress(data.zonecode, data.roadAddress, data.buildingName, data.jibunAddress );

도로명클릭시
zonecode= "16490"
roadAddress= "경기 수원시 팔달구 권광로 181"
buildingName= "씨네파크"
jibunAddress = ""
지번클릭시
zonecode= "16490"
roadAddress= "경기 수원시 팔달구 인계동 1113-11"
buildingName= "씨네파크"
jibunAddress = "경기 수원시 팔달구 권광로 181"

지번으로검색햇을시엔 4가지 데이터값을 전부 받아오는 반면에 도로명주소의 결과값을 선택햇을시 jibunAddress 의 데이터값을 못받아오고있는데 데이터가 누락된것인지 알고 싶습니다.

**Comment by daumPostcode** [comment]
@everymeari 
안녕하세요~

해당 주소의 경우 도로명으로 검색시
도로명과 지번과의 관계가 1:N 입니다.

이런상황일때, 도로명을 선택하면 지번은 N개중에 1개를 선택해야 하기 때문에, 저희가 임의로 최상위 지번주소를 선택해서 내리게 되는데요. 이자체가 임의 선택이므로
jibunAddress에 들어가지 않고, autoJibunAddress에 들어가게 됩니다.

저희 가이드 페이지의 속성 부분의 "반환되는 데이터 확인하기"로 확인가능 하며, data Table 아래에 autoRoadAddress, autoJibunAddress에 관한 설명도 있으니 참고부탁드립니다.

그리고 [FAQ 16, 17번](https://github.com/daumPostcode/QnA#16-%EC%82%AC%EC%9A%A9%EC%9E%90%EA%B0%80-%EC%A7%80%EB%B2%88%EB%8F%84%EB%A1%9C%EB%AA%85-%EC%A4%91-%EC%96%B4%EB%96%A4-%EA%B2%83%EC%9D%84-%EC%84%A0%ED%83%9D%ED%95%98%EB%8D%94%EB%9D%BC%EB%8F%84-%EB%AC%B4%EC%A1%B0%EA%B1%B4-%EB%8F%84%EB%A1%9C%EB%AA%85-%EC%A3%BC%EC%86%8C%EB%A7%8C-%EC%9D%B4%EC%9A%A9%ED%95%98%EA%B3%A0-%EC%8B%B6%EC%9D%80%EB%8D%B0-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC%EB%90%98%EB%82%98%EC%9A%94)을 한번 참고해보셔도 좋을것 같아요~

이외 궁금하신사항이 있으면 말씀해주세요~
