### ISSUE TITLE
oncomplete를 바로 호출하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by hikarubs** [daumPostcode/QnA#466]
정해진 주소를 던져주면 oncomplete 를 바로 실행 시키고 싶은데 현제 예제는

new daum.Postcode({...})..embed(element, {
    q: '판교역로 235'
});

이것만 나와있어서 어쩧게 해야 할지 모르겠습니다. 저 예제대로 라면

판교역로 235 로 찾아진 주소를 선택하는 창이 뜨고 그걸 또 한번 눌러줘야 하는데 그 과정없이 

바로 결과가 적용되게 하고 싶거든요

**Comment by daumPostcode** [comment]
@hikarubs 
네~ 안녕하세요~

현재 말씀하신 기능은 구현되어 있지 않습니다. 현 서비스는 사용자에게 주소를 검색하고 선택할 수 있는
우편번호-주소 검색기를 API로 제공하는 것이며,

말씀하신 기능의 경우, 손쉽게 기계적인 데이터 추출이 가능하므로, 어뷰징 요소가 될 수 있습니다.
현재로써는 자동선택 기능은 넣은 계획이 없음을 말씀드립니다.

주소를 기계적으로 가져오는 뷰나 모듈을 만들고 싶으시다면, 저희 서비스보다
postcodify나 행안부 API를 이용해 보시는게 좋을 것 같아요~
