### ISSUE TITLE
동일 조건으로 주소검색이 될 때도 안될 때도 있습니다. 

### ISSUE THREAD

**Issue by yeonjun2** [daumPostcode/QnA#467]
동일 조건으로 주소를 검색하는데 될 때도 있고 안될 때도 있습니다 . 

http://postcode.map.daum.net/guide 에서 
팝업을 이용하여 도로명 주소와 지번 주소 모두 보여주기 예제를 하여도 동일합니다. 

제가 생각했을땐 내부망 때문에 이런 문제가 있는 것 같습니다. ( 참고로 테더링을 통해서 검색하면 100% 검색이 됨 ) 

이런 경우  http://t1.daumcdn.net 도메인으로 방화벽을 허용하기를 하면 되는 것인가요 ?

50%정도의 확률로 검색이 되지 않는데 이게 방화벽과 관련이 있는 것인가요 ?

무조건 되지 않는다면 , 방화벽 문제인거 같은데 확률적으로 검색이 되지 않아 의문입니다. 

그리고 저희는 지도는 사용하지 않고 오직 주소만 검색하여 사용할 것인데 http://t1.daumcdn.net 만 허용하면 되는것인지 아니면  Issue no 407과 동일하게 
•http://postcode.map.daum.net
•http://dmaps.daum.net
•http://s1.daumcdn.net
•http://stlog1.local.daum.net
•http://suggest-bar.daum.net
•http://t1.daumcdn.net
•https://apis.daum.net (v3 maps api 사용시)
모두 허용을 해야 하는 것인가요 ?

지원 감사합니다.

**Comment by daumPostcode** [comment]
@yeonjun2 
안녕하세요~

네~ 내부망에서 이용하시는군요, 내부망의 경우, 저희가 공식 지원은 어렵고, 그래서 허용해야하는 도메인리스트만 제공하며, 해당 도메인리스트를 통해 IP를 찾아내서 방화벽에서 푸시거나 하시면 됩니다.

우선 말씀하신 것처럼 지도 API를 쓰지 않으신다면 apis.daum.net은 허용하지 않아도 됩니다. 또한 지도를 쓰신다면, Kakao Developers에서 제공하는 것으로 바뀌어서;; 위 도메인이 아니기도 합니다;;;; ㅎㅎ 암튼 이건 지도를 같이 쓰실때 알아보시면 되실것 같아요.

그외 나머지 도메인을 풀어주셔야 되는데요,
현재 t1, s1,의 경우엔 저희 CDN서버이며, IP가 한두개로 구성되어 있진 않을 겁니다. 이는 저희쪽 소관이 아닌지라 IP가 어떻게 될지는 잘 모르겠습니다. 그외 다른 서버의 경우에도, 거믜 비슷합니다. 

아마 말씀하신 것처럼 IP블락이 당해서 그런것 같습니다.
추가로 사이트 이용하실때 크롬이나 이런곳에서 개발자도구를 키신 다음에 못불러오는 파일이 있거나 페이지가 있으면 그 페이지나 파일이 블락당한 것이라서 확인해 보시는게 어떨까 합니다;;

직접적인 도움을 드리지 못해 죄송합니다.
