### ISSUE TITLE
방화벽 등록이 필요한 도메인의 IP 와 Port No 공유 요청드립니다.

### ISSUE THREAD

**Issue by yeonjun2** [daumPostcode/QnA#468]
안녕하세요 ! 내부망을 사용하고 있는 유저 입니다. 

회사 정책상 도메인으로 방화벽 허용은 불가능 하다고 합니다. 
아래 도메인에 대하여 IP 와 Port No 를 알 수 있을까요 ?
•http://postcode.map.daum.net
•http://dmaps.daum.net
•http://s1.daumcdn.net
•http://stlog1.local.daum.net
•http://suggest-bar.daum.net
•http://t1.daumcdn.net

감사합니다.

**Comment by daumPostcode** [comment]
@yeonjun2 
안녕하세요~

저희도 IP주소 자체를 제공해 드리진 못합니다.
아랫 글에서 말씀드린 것처럼, 네트워크 인프라의 관리는 제 소관이 아니기도 하구요;;;

그래서 저희는 도메인 리스트 밖에 제공드리지 못하며
nslookup과 같은 명령어를 통해서 직접 알아내신 후에 작업하셔야 합니다.
포트의 경우엔 외부에 나가는 서비스는 80으로 열려 있을 것 같네요;;
