### ISSUE TITLE
주소검색창이 빈창이뜹니다.

### ISSUE THREAD

**Issue by HwangJaeBeom** [daumPostcode/QnA#469]
FAQ 13번에 관해서 질문입니다.
document.domain을 사용중인곳에서 윈7 익스11은 주소검색창이 뜨는데
윈10 익스11에서는 주소창이 안뜹니다.
둘다 사용가능하게 할 방법이 있을까요?

**Comment by daumPostcode** [comment]
@HwangJaeBeom 
안녕하세요~

네. 브라우저가 같은 IE11이더라도, 윈7과 윈11은 빌드가 다릅니다.
그에따른 차이가 존재할 수 있어요. 위와 같은 현상은 그런 빌드차이에서 오는 현상 같습니다.

현재로써는 브라우저 자체에서 막는 것이므로 저희가 해당 이슈를 해결할 수 있는 방법은 없습니다.
