### ISSUE TITLE
아이폰 어플 실행 불가..

### ISSUE THREAD

**Issue by SonghyunJun** [daumPostcode/QnA#47]
안녕하세요. 저희 사이트에 iframe을 이용하여 페이지에 끼워 넣기를 이용해서 소스를 붙였습니다.
현재 지금 웹과 모바일 소스는 하나로 두고 어플 껍데기만 마켓이랑 구글에 올려놓은 상태입니다.
그 올려놓은걸 다운 받아서 폰에 설치 후 우편번호 찾기 버튼을 누르면 안드로이드에서는 정상적으로 작동이 됩니다. 하지만 아이폰에서는 모바일 웹으로 우편번호찾기를 누르면 정상적으로 페이지에 끼워넣어지는데 어플을 통해 들어가서 우편번호 찾기 버튼을 누르면 현재페이지의 화면 제일 상단으로 가는 현상만 나타나고 우편번호 검색 폼은 나오질 않습니다.(동작X) 어플에서는 왜 안먹히는지 궁금해서 글 남깁니다. 혹시 해결 방안이 있으면 알려주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@SonghyunJun 
네~ 안녕하세요~

일단 이전부터 앱으로 wrapping한 후에 이상 동작을 한다는 제보가 들어오긴 하는데요, 지금 말씀해 주신 사항은 처음 접해 보는 거네요;; 
"현재 페이지의 화면 제일 상단"으로만 간다는 얘기는 스크롤이 강제적으로 올라간다는 것인데,
의심해 볼 수 있는 상황은 어딘가 서비스가 숨겨진 상태로 검색창에 포커스가 간 것인데, 아이폰의 경우에는 보안 이슈로 인해 사용자의 입력이 없이 input박스에 코드 레벨에서 커서를 넣지 못합니다.(그래서 아이폰에서 저희 서비스를 여시면 말풍선 같은게 뜨는게 그 이유이죠;;)
그래서 커서에 포커싱된 스크롤 이동은 아닌 듯 하고, 저희 서비스가 뜨지 않는다는 것이기 때문에, 앱으로의 wrapping이 어떤 방식으로 되어 있는지는 모르나, 느낌적인 느낌으로 core스크립트가 로딩되지 않거나 해서 스크립트 오류가 발생하여 그냥 페이지가 최상단으로 올라가는게 아닐까 하는 의심이 듭니다.

정확한건 저희가 재현을 해보고, 오류나 기타 로직에 대해서 분석을 해봐야 되는데요.
현재 저희가 확인할 수 있는 방법이 있을까요??

**Comment by SonghyunJun** [comment]
제가 동영상을 찍어서 보내드리고 싶은데 혹시 메일 주소 알수 있을까요??
로직과 동영상으로 현상 촬영해서 보내드리겠습니다.

**Comment by daumPostcode** [comment]
@SonghyunJun 
네~ 이 깃허브 계정을 보시면 이메일이 있습니다. 여기로 보내주시면 되구요.

아래 이메일 입니다~
ftdev5@daum.net

여기로 보내주시면 됩니다. 그런데 저희가 다운을 받아 볼 수는 없는 것이지요?
앱으로 단순 wrapping이라 해도 방식에 따라 다를 수 있는데; 보통 버그는 현상으로만 정확한 진단을 하기가 어려운 경우가 있어서요; 코드레벨로 확인이 필요할때가 많은데, 일단 영상 주시면 확인해 보도록 하겠습니다.

**Comment by SonghyunJun** [comment]
어플을 다운 받을수 있으신데 현재 저희가 G-star 관련 이벤트 중이라 사람들에게 신청을 받고 있거든요... 그래서 주소검색이 안되면 아이폰 유저들은 해당 이벤트에 응모가 불가능해서 주소검색쪽을 막아놓고 오픈해놓은 상태입니다.
혹시라도 다운 받아 보시려면 앱스토어에 kocca 검색 하셔서 아카데미 말고 kocca 다운 받으시면 됩니다.
그리고 실행 시키셔서 오른쪽 하단에 선물 박스 누르시면 이벤트 페이지로 이동이 되고 지스타 이벤트 들어가시면 됩니다. 메일은 보내드렸습니다. 꼭 확인 부탁드리겠습니다...ㅠㅠ

**Comment by daumPostcode** [comment]
@SonghyunJun 
네~ 알려주신 앱 다운로드 받아서, 확인해보고 있는데요. 현재 작업중이신 것 같더라구요;; 일단 모웹주소를 알려주시지 않아서, proxy연결해서 페이지를 봐볼려고 했는데 안되네요;;
그래서 일단 보내주신 jsp파일을 보고 있는데요, 일단 서버문제가 아니라 FT문제이기 때문에 리소스(js,css)파일만 경로 설정하고 보는데요. 말씀해 주신데로 일반 브라우저에서는 정상적으로 동작을 하네요; 
그렇다는 것은 웹뷰의 문제일 확률이 매우 높은데요, iOS의 safari와 webview는 서로 같지 않습니다. 이부분은 아실 것 같아요;; safari에서 멀쩡해도 webview로 들어가는 순간 안되는 경우가 허다합니다.

일단 제쪽에서는 개발툴로 연결이 안되어 직접 디버깅을 하기가 힘들어서(JS, CSS는 동적 렌더링이라 코드만 봐서는 추적하기가 좀 힘들어서요;;) 추측밖에 할 수가 없을 것 같습니다. 개인적으로 초간단 웹뷰(구글링.. 앱개발자가 아니라서;;;;)를 만들어서 보내주신 jsp파일을 돌려 보았지만 말씀하신 이슈가 재현이 안되네요;;

일단 직접 iOS 앱의 껍데기?를 만들고 계시다면, Simulator나 실물폰에서 실행시킨 후에, Safari의 개발자 도구로 내부에서 돌아가는 웹페이지를 디버깅 가능합니다.(저는 외부 앱이라서 불가능합니다.) 일단 이렇게 확인해 보셔서 td태그안에 노드가 잘 들어가는지 확인 부탁드립니다.

그리고 보통 UI상 표시가 되지 않는 부분은 CSS관련 오류가 매우 큽니다.
td안에 div가 있고 해당 노드가 position:relative를 가지고 있는데, 이부분때문에 td태그안에 있긴 하지만 렌더링상 밖으로 빠져버려 테이블 뒤로 빠진다던가;; 아니면 td의 크기가 고정되어 커지지 않아 발생한다던가 하는 문제일 수도 있습니다.(스타일 기능상 되야 되는데 안되는 경우가 매우 많거든요;;) 일단 필수적으로 필요하다고 판단되는 css속성은 모두 제거하시고 필요한 것만 넣어서 해보시고, safari개발자 도구 이용하면 동적으로 수정해보면서 UI변화도 확인 가능하니 한번 부탁드려요;; 

딱! 해결책을 내드리고 싶은데;; 확인이 어려워서 추측밖에 드릴 수가 없는 점 양해부탁드립니다;;

**Comment by SonghyunJun** [comment]
아 넵 감사합니다 말씀하신대로 한번 테스트 해보록 하겠습니다.
