### ISSUE TITLE
주소검색이 되지 않습니다.

### ISSUE THREAD

**Issue by dnltpdnd** [daumPostcode/QnA#471]
충청북도 청주시 화계동 199 주소가 검색되지 않습니다.

**Comment by daumPostcode** [comment]
@dnltpdnd 
안녕하세요~

![image](https://user-images.githubusercontent.com/20675065/59823358-efc41e00-9368-11e9-89fc-f24b55a2a79a.png)

저희가 데이터터를 받는 행안부 도로명검색시스템에도 검색이 되지 않는 주소입니다.
FAQ1번을 참고해서 행안부측에 등록요청해 주세요. 도로명 주소가 발급되지 않은 주소는 일단 저희 시스템에서 검색되지 않는점 참고해 주세요.
