### ISSUE TITLE
안드로이드 웹뷰에서 로드시에 빈 페이지 나옵니다.

### ISSUE THREAD

**Issue by karorok** [daumPostcode/QnA#472]
웹뷰 세팅
        daum_webView.getSettings().setJavaScriptEnabled(true);
        daum_webView.getSettings().setSupportMultipleWindows(true);
        daum_webView.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);

웹 페이지 코드
<?php

header("Content-Type: text/html; charset=UTF-8");

?>
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false">
   //load함수를 이용하여 core스크립트의 로딩이 완료된 후, 우편번호 서비스를 실행합니다.
   daum.postcode.load(function(){
       new daum.Postcode({
           oncomplete: function(data) {
               // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
               // 예제를 참고하여 다양한 활용법을 확인해 보세요.
           }
       }).open();
   });
</script>

이렇게 구성되어 있는데 흰창만 뜨고 안나옵니다.
맨 처음에는 잘 나오다가 어느 순간 갑자기 나오지를 않습니다.

**Comment by daumPostcode** [comment]
@karorok 
안녕하세요~

우선 웹뷰의 경우에는 저희가 공식적인 지원을 해드리기가 어렵습니다.
해당 페이지가 브라우저에서 잘 동작하는지 먼저 확인 부탁드립니다.

전 안드로이드나 아이폰 개발을 하질 않아서, 웹뷰 관련 API옵션은 잘 모릅니다.
그래서 경험적으로 말씀드리면, 지금까지 웹뷰에서 이용시
우편번호서비스의 open()함수를 이용할 경우, 따로 처리를 하지 않는이상, 팝업이 안뜨고 기존 페이지를 덮어 버리는 현상이 발생되었기 때문에 open보다는 embed를 더 추천드립니다.

추가로 힌색화면이라면, 페이지 자체가 로딩이 안됬거나, 스크립트에러일 수 있는데요,
힌색화면이 뜰때의 오류메세지가 필요합니다.
