### ISSUE TITLE
안드로이드 디바이스 기기에서만 나는 오류

### ISSUE THREAD

**Issue by ljh8993** [daumPostcode/QnA#473]
아이오닉 하이브리드 앱으로 진행했습니다
몇달간 동작이 잘 되었었는데
저번주 부터 주소검색 후 주소 클릭했을 때
안드로이드기기에서만 동작을 안하길래 (시뮬레이터, ios 기기, 웹뷰 등등에선 잘 동작합니다)
디버깅해보니 이런 에러메시지가 나오더라고요

Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'http://' VM9 service.v2.min.js:4 in a call to 'postMessage'.
	at b (http://t1.daumcdn.net/postcode/cssjs/service/1557749450704/service.v2.min.js:4:15285)
	at Object.d [as sendResizeMessage] (http://t1.daumcdn.net/postcode/cssjs/service/1557749450704/service.v2.min.js:4:15432)
	at http://t1.daumcdn.net/postcode/cssjs/service/1557749450704/service.v2.min.js:5:20176

의견 부탁드립니다

**Comment by daumPostcode** [comment]
@ljh8993 
안녕하세요~

저희 우편번호서비스에서는 이종도메인간 통신을 위해서 postMessage 함수를 이용하고 있습니다.
이유는 아시는 것처럼, 저희 서비스의 검색팝업과, 이용하시는 사이트의 도메인이 서로 다르기 때문에, 스크립트로 일반적인 데이터 전달이 불가능하기 때문에 이용하고 있습니다.

해당 오류는 postMessage를 이용할때, 부모페이지의 도메인값을 참고해서 메세지를 던지게 되는데,
이 도메인 값이 정상적이지 않다는 오류인데요.

해당 앱의 웹뷰에서 location.host 값이 정상적으로 추출되는지 확인 부탁드립니다.

**Comment by ljh8993** [comment]
안드로이드 기기에서만 location.host이 '' 로 출력되네요
아이폰에서는 locahost:8080 이 잘 찍히고 있습니다
