### ISSUE TITLE
NUXT IE11 에서 진행이 안됩니다.

### ISSUE THREAD

**Issue by kjpar0317** [daumPostcode/QnA#476]
vue nuxt 프레임워크에 polyfill한 상태이고
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js' },
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js' },
      { src: 'https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js' }
위에 3가지 전역
한 후 모듈에 등록해서 해봤더니 크롬, 엣지 다 되는데 ie11에서 안되네요..
console창에는 구문오류 발생하고요

**Comment by daumPostcode** [comment]
@kjpar0317 

안녕하세요~
어떤 구문오류가 발생하나요?
폴피필로 인해 발생되는 문제는 저희가 해결하기 어렵습니다. 이미 저희 API는 폴리필이 필요없도록 IE6~모던브라우저까지 기능적 대응은 되어 있는 상태입니다.

일단 어떤 구문 오류가 발생하는지 알려주시면 좋을것 같습니다.

**Comment by kjpar0317** [comment]
@daumPostcode 
ie11에 개발자모드 캡쳐 보냅니다. 이것만으로 판단 가능한지는 잘 모르겠네요.

`!function(e,t){if(true)module.exports=t();else { var n, o; }}(window,function(){return function(e){var t={};function o(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return e[n].call(a.exports,a,a.exports,o),a.l=!0,a.exports}return o.m=e,o.c=t,o.d=function(e,t,n){o.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},o.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},o.t=function(e,t){if(1&t&&(e=o(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var a in e)o.d(n,a,function(t){return e[t]}.bind(null,a));return n},o.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return o.d(t,"a",t),t},o.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},o.p="",o(o.s=0)}([function(e,t,o){"use strict";o.r(t);let n=!1;const a=[],d=[];var i={props:{q:{type:String,default:""},animation:{type:Boolean,default:!1},noAutoMapping:{type:Boolean,default:!1},noShorthand:{type:Boolean,default:!1},pleaseReadGuide:{type:Number,default:0},pleaseReadGuideTimer:{type:Number,default:1.5},maxSuggestItems:{type:Number,default:10},showMoreHName:{type:Boolean,default:!1},hideMapBtn:{type:Boolean,default:!1},hideEngBtn:{type:Boolean,default:!1},alwaysShowEngAddr:{type:Boolean,default:!1},zonecodeOnly:{type:Boolean,default:!1},theme:{type:Object,default:()=>({})}},data:()=>({styleHeight:0}),mounted(){new Promise((e,t)=>{if(window.daum&&window.daum.postcode)return e();if(a.push(e),d.push(t),n)return;n=!0;const o=document.createElement("script");"https:"===location.protocol?o.src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false":o.src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false",o.async=!0,o.charset="utf8",(document.head||document.getElementsByTagName("head")[0]||document.body||document.getElementsByTagName("body")[0]).appendChild(o),o.onload=(()=>{n=!1,a.forEach(e=>e())}),o.onerror=(()=>{n=!1,d.forEach(e=>e())})}).then(()=>new Promise(e=>window.daum.postcode.load(e))).then(()=>{new window.daum.Postcode({width:"100%",height:"100%",animation:this.animation,autoMapping:!this.noAutoMapping,shorthand:!this.noShorthand,pleaseReadGuide:this.pleaseReadGuide,pleaseReadGuideTimer:this.pleaseReadGuideTimer,maxSuggestItems:this.maxSuggestItems,showMoreHName:this.showMoreHName,hideMapBtn:this.hideMapBtn,hideEngBtn:this.hideEngBtn,alwaysShowEngAddr:this.alwaysShowEngAddr,zonecodeOnly:this.zonecodeOnly,theme:this.theme,oncomplete:e=>{this.$emit("complete",e)},onresize:e=>{this.styleHeight=`${e.height}px`}}).embed(this.$refs.container,{q:this.q,autoClose:!1})})},computed:{styles(){const e={};return e.height=this.styleHeight,e}},render(e){return e("div",{class:["vue-daum-postcode"]},[e("div",{class:["vue-daum-postcode-container"],ref:"container",style:this.styles})])}};function r(e,t){t=t||{},e.component(t.name||"vue-daum-postcode",i)}o.d(t,"install",function(){return r}),o.d(t,"VueDaumPostcode",function(){return i}),"undefined"!=typeof window&&window.Vue&&r(window.Vue);t.default={install:r}}])});
//# sourceMappingURL=index.js.map`

에서 라인
`{type:Boolean,default:!1},zonecodeOnly:{type:Boolean,default:!1},theme:{type:Object,default:()=>({})}},data:()=>({styleHeight:0}),mounted(){new Promise((e,t)=>{if(window.daum&&window.daum.postcode)return e();if(a.push(e),d.push(t),n)return;n=!0;const o=document.createElement("script");`

에서 구문 오류가 발생하네요.
