### ISSUE TITLE
검색후 주소 선택시 다른사이트로 리다이렉트되는 이슈가 있나요?

### ISSUE THREAD

**Issue by huxx-j** [daumPostcode/QnA#477]
우편번호 검색 서비스를 정말 잘 쓰고있습니다.
오늘 저희 서비스에서 주소 검색후 선택하면 '야후'로 연결된다라는 이슈가 올라왔는데...
검색 창이 안뜨는 이슈는 몇번 있었어도 오늘같은 경우는 처음이라... 
혹시 '야후'가 아니더라도 다른 사이트로 리다이렉트 된 이슈가 발생한 적이있나요?

**Comment by daumPostcode** [comment]
@huxx-j 
안녕하세요~

아뇨 라디이렉트 코드는 존재하지 않습니다.
주소 선택 후에는 oncomplete콜백함수를 실행시키면서 데이터를 넘겨주는게 다입니다.
명시적인 "지도" 버튼을 눌렀을때만 map.kakao.com으로 연결되구요.

만약 다른 사이트로 연결됬거나 이런거면, 그 유저분이 어떤 브라우저를 쓰시는지 모르나, IE의 경우 특정 툴바나 엑티브엑스, 크롬은 확장프로그램들을 점검해 보면 좋을 것 같습니다.
브라우저를 초기화 한 후에 한번 시도해 보시라고 가이드 주시는게 좋을 것 같아요. (크롬의 경우 시크릿 모드를 사용하면 테스트 가능합니다)

추가로.... 리다이렉트 코드가 있지도 않지만,,,, 있다해도 map.kakao.com이나 www.daum.net이면 모를까... 야후로 이동시킬 일은 없지요....

**Comment by huxx-j** [comment]
저도 처음 이슈가 올라왔을때 '왜 하필 야후인가?' 라는 의문이 들어서
고객의 브라우저 문제 인거 같다고 안내를 했습니다. ㅎㅎ

그리고 혹시라도 이런 이슈가 이전에는 있었는지 궁금해서 문의했습니다 ㅎㅎ
답변 감사합니다.
