### ISSUE TITLE
내부망 테스트 

### ISSUE THREAD

**Issue by kcmmmmm** [daumPostcode/QnA#478]
안녕하세요.
다음 우편번호 서비스(http://postcode.map.daum.net/guide)를 이용하여 주소검색을 개발하려고합니다.
보안정책상 망분리가 되어있는데요.
내부망에서 테스트를 하려면 방화벽을 해제해야 할 것 같은데
내부망 테스트 시 해제해야 하는 도메인 목록이나 IP목록 요청드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@kcmmmmm 
네~ 안녕하세요~

네~ 내부망에서 사용하실려면 아래 제공해드리는 도메인 리스트를 통해 IP를 알아내거나 하시는 방법으로 직접 해주셔야 합니다. 현재 내부망의 경우 정식 서비스 지원은 해드리지 못하는점 참고부탁드립니다.

HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net

HTTPS 환경 
-  https://ssl.daumcdn.net
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net


감사합니다.
