### ISSUE TITLE
(재) NUXT IE11에서 진행이 안됩니다.

### ISSUE THREAD

**Issue by kjpar0317** [daumPostcode/QnA#479]
안녕하세요. 
저번에 문의한 NUXT IE11에서 진행이 안되는거 어떻게 진행이 되는건가요??
현재 
VUE + NUXT + VUETIFY로 프로젝트 진행중인데..
다음 카카오 주소 가져오는 모듈이 너무 좋아서 이용하고 싶은데.. IE11에서 진행이 안되니... 고객이 IE11에서 안된다면 빼달라고 하네요... 이번에도 말씀드리지만 POLYFILL적용 상태이고 

`
  modules: [
    '@nuxtjs/apollo',
    '@nuxtjs/axios',
    '@nuxtjs/proxy',
    '@nuxtjs/toast',
...
    ['vue-daum-postcode/nuxt', { name: 'vue-postcode' }]
  ],
`
에서 vue-daum-postcode/nuxt를 빼고 진행하면 IE11에서 되고요.
만약 넣고 진행하면 첫화면부터 Javascript오류 발생하여 모든 자바스크립트 이벤트가 먹통이 됩니다. 에러는 아래글에 있습니다.

**Comment by daumPostcode** [comment]
@kjpar0317 
네~ 안녕하세요~

우선 해당 vue 모듈은 제가 개발한게 아닌, 외부 개발자분께서 만들어서 공유해 주신 라이브러리 입니다.(매우 감사하신 분들 ^^)
아마 뷰 라이브러리 자체의 문제는 해당 라이브러리를 만드신 분께 질문을 하시면 더 빠른 답변을 얻으실 수 있을 것 같습니다.

다만, 뷰 라이브러리의 소스코드 및, IE11에서만 안된다는 상황을 보니 대략 감이 오는데;

IE11은 아시는 것처럼 ES6 문법이 적용되지 않습니다. 즉 babel이나 기타 다른 툴을 이용해서 translating을 시켜야 하는데요. 아마 만드시고 계신 프로젝트에서 vue-daum-postcode 모듈을 translating하지 않는 것 같은 느낌입니다.

현재 vue라이브러리를 만드신 분의 깃허브의 demo페이지를 봐도, IE11에서는 아래 글에서 올려주신 오류위치와 같은 곳에서 오류가 발생합니다. (IE11에서는 Arrow function이 없습니다. 딱 Arrow function으로 정의된 부분부터 오류가 나기 시작하는것 같아요~)

즉, 해당라이브러리의 브라우저에 맞는 Translating을 시켜주시면 IE11에서도 문제없이 동작할 것으로 생각됩니다.
한번 빌드시 라이브러리도 같이 빌드가 되는지 확인해보셔요~

감사합니다~
