### ISSUE TITLE
ionic://localhost 에서 데이터를 요청했는데 http://localhost로 데이터를 반환해줍니다.

### ISSUE THREAD

**Issue by aldegad** [daumPostcode/QnA#480]
안녕하세요.

저희가 cordova-plugin-ionic-webview 를 사용하는데,

iOS는 scheme을 ionic://으로 사용합니다.

그래서 ionic://localhost환경에서 iframe을 열었는데,

http://localhost로 반환을 해줘서 데이터를 받지 못했습니다.

혹시 저 부분을 요청한 페이지를 정확히 받도록 수정해주시거나, 혹은 저희쪽에서 대응하는 방법이 있을까요?

**Comment by daumPostcode** [comment]
@aldegad 
안녕하세요~

현재 우편번호 서비스에서는 https 와 http 이 두가지의 프로토콜만 허용해서 그런것인데요.
이외의 프로토콜도 받을 수 있도록 수정하도록 하겠습니다.

내부에서 값을 가져오는 변수는 location.protocol 에 들어있는 값을 그대로 사용한다고 보시면 됩니다.
그래서  http: or https:
와 같은 형식으로 내부에서 저장하여 사용하고 있습니다.

수정배포의 경우 다음주 월요일 오후에 배포하도록 하겠습니다. 
감사합니다.

**Comment by daumPostcode** [comment]
@aldegad 
안녕하세요~

7월 22일 15시 20분
말씀하신 요청사항 처리하여 배포되었습니다.

확인 부탁드립니다.
기존에 강제로 셋팅하던 부분을 location.protocol 값을 그대로 이용하도록 수정하였으니 참고 부탁드려요~

**Comment by aldegad** [comment]
안녕하세요, 데브몬스터의 김수홍입니다.
감사합니다!!

--------------------------
김 수 홍
(주)데브몬스터 / 대표이사

서울시 송파구 올림픽로 10길 35 4층 (주)데브몬스터
연락처 : 010-5604-4147
email : aldegad@naver.com
포트폴리오 : http://www.freemoa.net/m7/freelance_detail?fno=7883
 
-----Original Message-----

**Comment by aldegad** [comment]
@daumPostcode 
감사합니다!!
