### ISSUE TITLE
주소검색이 되지 않습니다.

### ISSUE THREAD

**Issue by hanaware** [daumPostcode/QnA#482]
경기도 양주시 장흥면 호국로 176-16

도로명사이트에서는 검색이 되는데 다음에서는 되지않습니다.
확인해주세요!

**Comment by daumPostcode** [comment]
@hanaware 
안녕하세요~

해당 주소가 매핑된 지번으로 검색을 할경우에는 도로명 주소가 나오네요.
해당 이슈는 검색엔진 이슈인것 같기도 한데, 담당자분께 CS전달 하도록 하겠습니다.

답변이 오거나 수정이 되면 말씀드릴께요~ 감사합니다.

**Comment by daumPostcode** [comment]
@hanaware 
안녕하세요~
현재 해당 이슈 수정되었습니다.

불편을 드려 죄송합니다.
