### ISSUE TITLE
IE, iframe 이용하여 레이어 띄우기시 검색 input 작동이 안되요

### ISSUE THREAD

**Issue by kanghyeran** [daumPostcode/QnA#483]
iframe 이용하여 레이어 띄우기 방식으로 작업을 했는데요,
다른 상황에서는 정상적인데

IE에서 모달창(position: fixed 적용된 레이어) 띄운 상태에서 주소 검색 레이어 띄우면
주소찾기 입력창(input#region_name) 이 정상작동 안되고 있습니다.

포커스 자체가 안들어가고 placeholder 요소가 가로 막아버립니다.
placeholder 요소와 겹치지 않는 input#region_name 영역 클릭시 포커스가 들어가지긴 하는데
내용 입력 하더라도 placeholder 요소의 show 클래스가 추가/삭제 되는 동작도 실행이안됩니다.
한/영 변경도 안되고요. ctrl+a/c/v 등 단축키도 역시 동작안되고요

position: fixed 적용된 모달창 A를 띄운 상태에서
주소 검색 레이어인 B를 띄우면 해당 문제가 발생합니다.

position: relative 만 이뤄진 페이지에서
주소 검색 레이어인 B를 띄우면 정상이고요,

input#region_name 에 접근이 불가능하고
어찌 접근되어도 관련 event function이 정상 작동 안되는것 같아요 ㅜ,ㅠ
어디가 문제인건지 도무지 감이 안잡히네요... 도와주세요...

**Comment by daumPostcode** [comment]
@kanghyeran 
안녕하세요~

OS버전, IE버전에 관한 정보가 필요합니다.. IE라고말 말씀하시면 IE는 버전이 많고, Win7 IE, WIn8 IE, Win10 IE가 IE버전이 같다해도 다 다르거든요;;;
좀더 상세한 재현스펙을 알려주시면 좋을 것 같습니다.

모던브라우저도 마찬가지지만, 구형인 IE브라우저라면 안되는 것은 정상은 아니지만, 정상?이라고 볼 수도 있습니다. ㅎㅎ;;; (많은걸 포기하게 만드는 브라우저라서요)

position:fixed 속성의 경우 iOS에서는 브라우저 버그로 개인적으로 모바일에서 저희 서비스를 쓰실땐 저희 예제에 있는 레이어모드보다 끼워넣기 예제를 더 추천드리는 편인데요, 이게 position:fixed 엘리먼트 안에 우편번호 서비스가 들어가서 동작할시, 알기 어려운 키보드 동작 오류와 스크롤 오류가 많아서 그렇습니다.

이러한 버그가 IE에서도 비슷하게 존재하는것 같은데, 일단 재현 케이스를 확실히 알려주시면 좋을 것 같습니다.
또한 저희 공식 가이드 페이지에 있는 예제 샘플에서도 같은 현상이 일어나는지도 확인해 주시면 좋을 것 같습니다.

스타일 속성과 연관된 버그의 경우엔, 해당 속성을 유지하면서 해결하는건 매우 어렵습니다. 더큰 수정을 야기시키기도 해요. 제 개인적인 생각으로는 해당 속성을 반드시 사용해야하는 경우(네 반드시 절대 불가 변경일때)가 아닌 이상, 해당 속성 사용을 포기하고 대체제로 (relative or absolute) + javascript를 통해서 간접구현하는 방식을 추천해 드립니다.

일단 테스트 환경 상세스펙을 알려주세요~

**Comment by kanghyeran** [comment]
IE 11 버전에서 테스트한거고요,
우편번호 서비스는 relative element 부모 아래에 위치하며 
해당 요소는 absolute로 변경하여 테스트해봐도 동일합니다.
구조가 아래와 같은 상태입니다.
<pre>
&lt;div class="wrap" style="position:relative;"&gt;
    &lt;div class="modal"&gt;
&lt;/div&gt;
</pre>

**Comment by kanghyeran** [comment]
> iframe 이용하여 레이어 띄우기 방식으로 작업을 했는데요,
> 다른 상황에서는 정상적인데
> 
> IE에서 모달창(position: fixed 적용된 레이어) 띄운 상태에서 주소 검색 레이어 띄우면
> 주소찾기 입력창(input#region_name) 이 정상작동 안되고 있습니다.
> 
> 포커스 자체가 안들어가고 placeholder 요소가 가로 막아버립니다.
> placeholder 요소와 겹치지 않는 input#region_name 영역 클릭시 포커스가 들어가지긴 하는데
> 내용 입력 하더라도 placeholder 요소의 show 클래스가 추가/삭제 되는 동작도 실행이안됩니다.
> 한/영 변경도 안되고요. ctrl+a/c/v 등 단축키도 역시 동작안되고요
> 
> position: fixed 적용된 모달창 A를 띄운 상태에서
> 주소 검색 레이어인 B를 띄우면 해당 문제가 발생합니다.
> 
> position: relative 만 이뤄진 페이지에서
> 주소 검색 레이어인 B를 띄우면 정상이고요,
> 
> input#region_name 에 접근이 불가능하고
> 어찌 접근되어도 관련 event function이 정상 작동 안되는것 같아요 ㅜ,ㅠ
> 어디가 문제인건지 도무지 감이 안잡히네요... 도와주세요...

**Comment by daumPostcode** [comment]
@kanghyeran 

이슈가 클로징 되었군요;
해결이 되셨으면 좋겠습니다.

제가 다른 프로젝트 때문에, 깊게 확인을 하지 못했는데 죄송합니다.
