### ISSUE TITLE
주소 검색이 되지 않습니다.

### ISSUE THREAD

**Issue by KimJongYoon** [daumPostcode/QnA#484]
"제주특별자치도 동홍동 1480-6"
(건물이 없고 지번만 있는 주차장 주소)
-> 카카오맵에서 검색 됨
     -> 카카오API (로컬) 주소 REST API 검색 -> 검색 됨
     -> **카카오맵에서 검색이 가능**해서 카카오 우편번호 서비스에서 위 주소 검색 시 조회가 안됨
-> 도로명주소 API에서 검색되지 않음
     -> 문의 시 건물 DB만 관리하기 때문에 건물이 없으면 주소가 없음

제주도 차고지 관련 프로젝트를 하고 있는데 위와 같은 문제점이 있습니다.
카카오맵처럼 우편번호 검색도 지번주소만 있는 주소 검색이 되게 해주실 수 있나요?

**Comment by daumPostcode** [comment]
@KimJongYoon 
안녕하세요~

우편번호서비스는 "도로명검색시스템"이며, 원 데이터는 행안부에서 도로명주소DB를 제공받아서 사용합니다.

현재로써는 저희 우편번호서비스로는 "도로명 주소"가 발급되지 않은 주소의 경우엔, 추가로 제공해 드리기가 어려운점 말씀드립니다.

카카오맵의 경우엔 우편번호서비스에서 사용하는 주소데이터 + 지번 데이터 + 장소에 매핑된 주소(지번or 도로명) 데이터 등 여러 데이터를 복합적으로 이용하기 때문에, 많은 장소가 나오는 것으로써,
저희 시스템과는 메커니즘이 많이 다릅니다.

건물이 아닌 일반 지번 주소에 관련된 사항은,, REST API를 이용하시는게 좋으실것 같아요..

도움을 드리지 못해 죄송합니다.
