### ISSUE TITLE
안드로이드 주소검색api 가 안됩니다..

### ISSUE THREAD

**Issue by mikejkh** [daumPostcode/QnA#485]
안드로이드 어플 개발중에 주소검색 api를 사용하고 있는데 크롬 패치가 업데이트 되면서 주소검색이 안되고 있습니다..
저번주 주말부터 안되고 있는 것 같은데 언제쯤 사용 가능할까요?

**Comment by daumPostcode** [comment]
@mikejkh 
안녕하세요~
혹시 주소 검색이 안되고 있는 현상이
구체적으로 어떻게 안되고 있는 것을 말씀하실까요?

팝업창이 안뜨는 것인가요? 아니면 검색했을때 결과가 안나오는 것인가요?

**Comment by mikejkh** [comment]
아예 백색화면이 뜹니다..

**Comment by mikejkh** [comment]
팝업창 자체가 안뜹니다

**Comment by daumPostcode** [comment]
@mikejkh 
해당 오류의 경우엔, 
저희 api를 이용하는 페이지에 document.domain값과 같은 코드가 포함될때 발생하는 화면이긴 한데요.
혹시 안드로이드에서 말고, 일반 브라우저에서도 발생할까요?

**Comment by mikejkh** [comment]
안드로이드화면에서만 그렇다고합니다
