### ISSUE TITLE
앱에서 주소 검색이 안됩니다.

### ISSUE THREAD

**Issue by mimipet123** [daumPostcode/QnA#486]
안녕하세요 앱을 운영하고 있습니다. 
현재 주소 입력을 위해서 "다음 우편번호 검색" 서비스를 사용중인데.. 확인해보니 7월 7일부터 일부 단말에서 우편번호 검색이 빈화면으로 뜹니다. 수정방법을 가이드 해주시면 감사합니다.

**Comment by daumPostcode** [comment]
@mimipet123 
안녕하세요~

혹시 해당 앱이 어떤 앱인지 알려주실 수 있으신가요?
또는 document.domain값을 사용하시는지, 또는 http프로토콜용 API를 사용하시는지
사용하는 서비스에서 location.host, location.protocol 값도 알려주시면 감사하겠습니다.
여기에 적기 힘드시면
goni.r@kakaocorp.com 으로 보내주시면 감사하겠습니다.

**Comment by mimipet123** [comment]
안드로이드 앱 이름 : 미미살롱펫

안드로이드 앱에서 웹뷰로 로드하는 URL : http://210.180.118.201/mimiRes/addrtogps_android.html

addrtogps_android.html에 Daum API 정의 
   <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
   <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=051bb0272ed4b4ba2df14918429a1539&libraries=services"></script>
