### ISSUE TITLE
모바일 주소 검색시

### ISSUE THREAD

**Issue by route61jj** [daumPostcode/QnA#487]
![KakaoTalk_Photo_2019-07-29-10-35-59](https://user-images.githubusercontent.com/41247490/62016372-b646c400-b1ec-11e9-85ae-4d1004857334.jpeg)
![KakaoTalk_Photo_2019-07-29-10-35-52](https://user-images.githubusercontent.com/41247490/62016374-b646c400-b1ec-11e9-86a8-2cccc4d4e129.jpeg)

안녕하세요.. 
모바일  화면에서
주소검색 창을 띄운후, 
주소를 입력하기 위해 주소검색 부분을 클릭하면 
키보드가 위로 올라오면서, 검색창의 윗부분이 가려집니다. 
이부분 어떻게 해결 가능한지요?

**Comment by daumPostcode** [comment]
@route61jj 

안녕하세요~
초기에 레이어를 띄울때 조금 아랫쪽에 띄우시면 되실것 같은데, 그렇게는 안될까요?
position:fixed를 사용하고 계신다면, position:absolute를 한번 이용해 보시는게 어떨까 합니다.

키보드가 올라왔을때의 위치를 잡거나, 또는 저희 팝업을 원하는 위치에 띄우는 코드는, 온전히 개발자님의 몫이고, 또한 현재 개발하고 계시는 사이트 특성에 따라 해결방법은 다르기 때문에 제가 딱 어떻게 하라고 말씀드리긴 어려울것 같습니다.
