### ISSUE TITLE
(추가) embed 함수의 인자(요소)를 인식하지 못합니다.

### ISSUE THREAD

**Issue by parkjg20** [daumPostcode/QnA#488]
+) sample3번 코드로 테스트 해보았습니다

jquery와 순수자바스크립트로 모두 테스트 해 보았는데
주소 검색화면이 원하는 위치에 표시되지 않고, 화면 최하단에 추가됩니다

id값에 이상이 있는 것 같진 않습니다. 무슨 문제일까요?

+) 더불어 크롬 콘솔에는 다음과 같은 메시지가 출력됩니다만 iframe이  뜨긴 합니다
```
postcode.v2.js:1 A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/postcode/api/core/190722/1563776399461/190722.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
```

**Comment by daumPostcode** [comment]
@parkjg20 
안녕하세요~

우선 두번째 질문에 답변을 드리면,
해당 현상은 postcode.v2.js를 이용한 동기로딩을 수행할때 발생되는 것으로, 인터넷이 매우 느린 환경에서 페이지가 블락되는 현상을 겪을 수 있다라는 경고문구로, 실제 기능과는 상관이 없습니다. 해당 오류를 회피할려면; 가이드페이지에 있는 동적로딩을 이용하시면 해결됩니다.

첫번째 질문의 경우엔, 세번째 샘플을 사용하셨다는 것은 embed를 이용한 iframe으로 띄우는 방식인데요,
가이드 페이지에 보시면 open함수와 embed함수가 받을 수 있는 인자가 다릅니다.
embed함수에는 따로 위치를 조정할 수 있는 옵션은 없습니다. 레이어모드(embed)를 이용하실때의 레이어의 위치는 직접 상위wrapper의 위치를 직접 제어해 주셔야 합니다.

**Comment by parkjg20** [comment]
@daumPostcode 
네 예제에 나와있는 대로 wrapper를 생성하고 embed(wrapper)  형태로 메소드를 수행한 상태였습니다. 코드 첨부를 하지 않아 불편함을 드려 죄송합니다.

`
// 두가지 방법 모두 시도해봤습니다.
var element_wrap = $('#wrap');
// 또는
var element_wrap = document.getElementById('wrap'); 

    function foldDaumPostcode() {
       element_wrap.css("display", "none");
    }

    function sample3_execDaumPostcode() {
        //설정
        }).embed(element_wrap);
        element_wrap.css("display", 'block');
`

**Comment by parkjg20** [comment]
네 예제에 나와있는대로 embed(요소) 형태로 메소드를 호출하였고, 스크립트는 페이지 최하단에 첨부되어있습니다.

코드와 출력 화면 첨부하겠습니다.
코드는 jquery와 순수자바스크립트 두 방법으로 모두 테스트 해보았습니다.
`
    var element_wrap = $('#wrap');

    function foldDaumPostcode() {
        element_wrap.css("display", "none");
    }
    function sample3_execDaumPostcode() {
       // ....설정 생략.....
        }).embed(element_wrap);

        element_wrap.css("display", 'block');
    }
`

![image](https://user-images.githubusercontent.com/42087150/62669089-4fce5c80-b9c9-11e9-8f4d-712b421d516a.png)

![image](https://user-images.githubusercontent.com/42087150/62669159-91f79e00-b9c9-11e9-9b27-7d93fd63c76e.png)
