### ISSUE TITLE
IE 에서 SCRIPT7002 오류

### ISSUE THREAD

**Issue by rorent** [daumPostcode/QnA#489]
안녕하세요
window 7, 10 동일하며
ie 버전 11.885.17134.0 
간헐적으로 IE 에서 우편번호 호출 시 
SCRIPT7002: XMLHttpRequest: 네트워크 오류 0x2efd, 00002efd 오류가 발생하여 작업을 완료할 수 없습니다.
간헐적으로 나는 오류라 계속 테스트를 했을 경우 어쩌다 한번씩 오류가 나옵니다.

현재 운영 환경에서만 오류가 보고되었습니다.
https 환경이며
 
호출 script 는 
<script src="https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js"></script>
<head></head> 태그 안에서 호출되고 있습니다.
구글링 결과
예상은 cross site 오류로 생각되며
 ajax 호출 시 crossDomain : true 로 해결가능하다는 방법이 있던데
지금 script 추가 후 
layer popup 에서
new daum.Postcode({
...
})
로 호출합니다.

운영 환경은 AWS 환경이며 
내부망 IE 에서 인증서 오류는 문제건으로 가지고 있는 상태입니다.

혹시 내부망 사용중이라 방금같은 오류가 생기는지 궁금합니다.
너무 두서없이 적은 거라 추가적인 질문은 댓글 부탁드립니다.

**Comment by daumPostcode** [comment]
@rorent 
안녕하세요~

우선 현재 우편번호 서비스에서 AJAX요청을 하는 부분은, 검색을 한 후에, 검색어 아래에 "도로명 전체","지번 전체"에 해당하는 주소필터링 부분에 적용되어 있습니다.
다만 해당 필터링데이터를 호출할때, 내부의 검색페이지와 동일한 도메인을 가진 서버로 호출하기 때문에
크로스도메인 문제는 발생하지 않습니다.

확실하진 않는데,
현재 저희 JS API스크립트의 주소가 변경되었는데 한번 이걸로 변경해 보시겠어요?
```
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js
```

추가로 내부망에서만 발생할 수 있는지는,,, 음.... 저도 제 지식의 한계로 인해서;; 해당 부분은 확실히 잘 몰라서 확답이 어렵네요;;;

간혈적 오류고 운영환경이라면 한번 IE의 브라우저 초기화(인터넷 옵션 -고급 - 브라우저 재설정)을 한번 해보시는게 어떨까 합니다.

적절한 답변을 드리지 못해 죄송합니다.
