### ISSUE TITLE
특정 상황에서 글자 입력이 이루어지지 않음

### ISSUE THREAD

**Issue by dir4you** [daumPostcode/QnA#49]
아이폰 앱에서 테스트하였습니다
1. 주소 검색 페이지에서 '터치하여 검색해 주세요'와 함께 주소입력 필드에 터치함
2. iOS 키보드가 올라오면서 입력이 가능한 상태가 됨
3. 아무 단어나 한글자 입력을 진행함
4. 입력창에 단어가 표시되며 검색결과 출력됨 (키보드 ON 상태)
5. 검색결과가 출력된 목록 부분을 스크롤 (스와이프 업/다운) 동작시도
6. 입력창에 검색단어와 커서가 깜빡인 상태 유지된 것으로 보임, 하지만 이상태에서 추가 입력이나 수정 삭제가 안됨. 물론 iOS 키보드에 fu표시 '완료'를 눌러 키보드를 완전히 내린후 다시 호출하면 정상 입력됩니다.

이 증상에 개선을 요청드립니다 :-)

**Comment by daumPostcode** [comment]
@dir4you 
네~ 안녕하세요~

상황 재현을 위해 몇가지 질문 드릴께 있습니다.

1. 아이폰 앱에서 테스트 <- 이 아이폰 앱이라는게 어떤 것일까요? 사파리는 아닌것 같은데, 혹시 저희가 접근 할 수 있는 앱인가요? 아니면 웹뷰를 이용한 앱인가요?
2. 4번의 검색결과가 제가 보기에는 검색버튼을 누른 후가 아닌, 누르기 전에 검색어 제안을 해주는 "서제스트"기능을 생각이 됩니다. 이게 맞을까요?

왜냐하면, 현재 사파리에서는 저희 공식 가이드페이지를 열어서 테스트해본결과, 말씀해 주신 이슈가 재현이 되지 않습니다. 

일단 ios 8~9 때부터 안드로이드는 정상이나 아이폰에서 유독 2중 iframe구조일때, input박스의 이벤트 및 키보드 입력이 비정상적으로 작동하는 문제가 있습니다. 이를 해결하기 위해, 여러가지 예외처리가 되어 있는데요. 말씀해 주신 이슈를 보니 저희가 놓친게 있는 것 같네요.

일단 이슈가 재현이 되지 않기 때문에 무작정 방어 코드를 넣거나, 버그가 있을 만한 코드만 뽑아내어 간소화 테스트를 하기가 힘들어 바쁘시겠지만, 한번 더 댓글 부탁드립니다. 

추가적으로 웹뷰일 경우, 각 개발자마다 구현정도가 다르기 때문에 예외 케이스가 많아서, 저희가 처리를 못하는 부분이 생길 수 있습니다. 이런 경우 현재의 최선의 방법으로 저희가 상황을 회피할 수 있게 제안을 해드릴 수도 있는 점 양해 부탁드립니다.

**Comment by dir4you** [comment]
먼저 자세하게 답변 달아주셔서 너무 감사합니다.

1. 아이폰 앱 테스트의 경우 저희가 개발한 앱에서 반영하는 과정에서 발생하였습니다. 현재 App Store에 등록되어 있는 버전으로도 테스트가 가능한 부분이라, 정보를 남겨 드리도록 하겠습니다.
 * App Store Download Link 
 https://itunes.apple.com/kr/app/mataju/id1167947849?mt=8

 * 회원가입절차(SNS인증방식)가 필요하고, 로그인이 이루어진 상태에서 맡기기/찾기 버튼을 누른 이후  맡기기 플로팅 버튼을 누르셔서 '장소와 연락처를 알려주세요' 항목을 눌러주시면 '새주소 등록'항목으로 바로 진입해 보실 수 있습니다.   

 2. 4번항목에 언급한 결과는 자동으로 검색어를 제안해주는 서제스트 기능을 의미하는 것이 맞습니다. 위 동작을 이해하시기 편하도록 제가 증상을 재현한 부분을 촬영해서 링크를 걸어보도록 하겠습니다. 
 http://www.youtube.com/watch?v=U81pOmxYYFo

**Comment by daumPostcode** [comment]
@dir4you 
네~ 안녕하세요~

먼저 동영상 감사드립니다. 그런데 현재 앱은 다운 받았는데, 회원가입이 되질 않아(서버에 이상이 있는 것 같아요.. 전화번호, 카카오톡, 페북 다 가입이 안되네요;; 가입시도 시간 4시 30분); 실질적으로 앱에서는 확인 못해봤네요;

일단 이슈가 무엇인지 파악이 됬는데, 현재 상황을 말씀드리면,
"서제스트"의 경우 input창의 포커스가 blur가 되면 사라집니다. 즉 focus가 계속 남아있어야 되는데, 일부 ios 웹뷰에서 오작동을 하는 것으로 보입니다(첫번째 댓글의 이중 iframe과 연관이 있습니다.) 그래서 현재 해결방법으로는 ios webview에 한해서만 서제스트의 touch이벤트를 조작하거나, 구조를 완전히 바꾸는 방법이 있는데, 후자는 현재 여건상 쉽지 않아보여, 전자로 작업을 진행해야 될것 같습니다.

만약 UA를 따로 변경하지 않더라면, version/X 라는 값이 웹뷰에서는 나오지 않는데요, 이를 통해 safari 브라우저인지 웹뷰인지를 구분하니 혹시 UA를 변경하였다면 version이라는 값이 들어가 있는지만 확인해 주시면 될 듯 합니다. (원천적인 해결 방법은 하위호환성을 위한 코드를 분리하여 모던 브라우저에 맞게 구조 개선을 해야하나, 현재 일정상 힘들어서 진행이 어려운점 양해 부탁드립니다 ㅜ.ㅜ)

일단 기존에 다른 버그로 인하여 webview체크로직을 보니, 현재 10은 빠져 있어서 추가해서 배포를 할 예정입니다. 
(혹시나,, 정말 혹시나 이 부분에 의한 사이드이펙트일 확률이 조금이라도 있으니 혹시나 배포 후에 정상동작하는지 한번만 확인 가능하실까요?)

**Comment by daumPostcode** [comment]
@dir4you 
dir4you님 안녕하세요~ 

위 댓글에서 제가 마지막에 괄호에 넣은 문구는 잊으셔도 됩니다;;;;;;
일단 처음 댓글처럼, ios webview에서의 이중 iframe관련한 버그였고, 현재 작업완료 후 테스트 중입니다.
다만 웹뷰의 경우 커스터마이징 정도에 따라 결과가 좀 다를 수 있으니, 내일 배포 후에 확인 요청을 드리도록 할께요;

**Comment by daumPostcode** [comment]
@dir4you 
금일 오후 1시 30분 이후 실서버 배포 예정입니다. 참고 부탁드립니다~

**Comment by daumPostcode** [comment]
@dir4you 
현재 시간 13시 40분 실서버 배포완료되었습니다. 검색영역에 검색어 입력후 서제스트쪽를 스크롤 할려고 하면 키보드가 내려가도록 하였습니다. 이는 위에서 말씀드린 것처럼, 가짜키보드 버그를 회피하기 위한 방법이며, 한번 확인 부탁드립니다. 
(간혹 웹뷰마다 코드가 안먹는 현상이 있습니다. 이부분에 대해서는 모든 웹뷰를 대응할 수 없기 때문에, 원천적인 해결방법은 좀 더 고민이 필요해 보여요;;;)

**Comment by dir4you** [comment]
안녕하세요! 먼저 빠른 답변에 감사한 마음 전합니다.

업데이트 내용을 확인한 후 iOS App으로 구현한 페이지에서 위 사항을 테스트해보았으나 동일한 증상으로 확인되는 상태인데요. 이 증상을 다음측에서 테스트해보시는데 도움이 될 수 있는 부분이 있다면 어떤것들이 있을까요? 해결을 위해서라면 여러가지로 찾아보고 싶습니다.

더불어 이 전에 서버 문제로 구현된 내용이 반영된 iOS APP 이용이 어려웠던 사항은 개선되어서 가능하시다면 저희 앱에서도 테스트 시도해 주신다면 더욱 감사하겠습니다.

**Comment by daumPostcode** [comment]
@dir4you 
네~ 안녕하세요~ 도움을 주신다니 엄청 감사드립니다 ^^

일단 현재 상황에 대해서 설명을 드리면,
11월 2일에 배포가 된 내용은 1차적으로 서제스트 리스트를 터치할때 input박스의 blur이벤트가 동작하지 않도록 한 부분을 제거한 버전입니다.

그리고 일단 제가 아주아주 기본적인 웹뷰 (프로젝트 생성후, 스토리보드에서 웹뷰만 드래그해서 만든.....)에서는 위 수정사항 반영후, 키보드가 정상적으로 내려가는 것을 확인을 하였습니다. 다만, 고도화된 웹뷰 - 크롬, 다음앱웹뷰, 네이버앱웹뷰 의 경우 동작방식이 상이 했는데요, 크롬과 다음앱웹뷰는 기본브라우저인 safari와 비슷하게 동작을 하고 있었고, 네이버웹뷰의 경우에는 버그가 그대로 남아 있는 것으로 확인이 됩니다. 일단 네이버 웹뷰에서는 현재 blur이벤트나 input박스의 제거 및 재삽입 등의 액션을 취해도(input박스를 제거하면 키보드가 내려갑니다) 아무련 반영이 안되는 점을 보아, ios9과 다르게 ios10에서는 내부적으로 변경이 있는 것으로 생각이 되네요.. 

현재로써는 웹에서 키보드의 기본적인 제어방식을 통해 제어가 되지 않기 때문에, 여러가기 꼼수를 쓰고 있는 것인데, 제가 자체적으로 테스트하면서 느낀 것은, PC는 그대로 두더라도, Mobile(iOS, Android)에서는 open(), embed()할때의 로직을 변경을 해야 해결이 될것 같아 보입니다. 현재는 PC와 mobile모두 동일한 로직을 사용합니다.

네,, 결론적으로 dir4you님께서 다음앱이나,크롬처럼 웹뷰에서 처리를 해주셔도(다만, 어떤 부분이 어떻게 처리되어 있는지는 몰라서 말씀드리기가... 쉽지 않네요./.), 다른 분들이 이용할때 또 발생할 수도 있는 부분이라, 저희쪽에서 로직 간소화 및 작업을 진행해야 될것으로 생각이 드네요;

일단, 현재 이 부분을 처리함에 있어 시간이 조금 들어가는데요, JS API(161102.js)의 경우 배포가 좀 자유롭기 때문에 제가 현재 이 이슈에 댓글을 달면 한번 확인만 부탁드립니다;;

**Comment by daumPostcode** [comment]
@dir4you 
안녕하세요~~

금일 10시 40분 ios 에서 키보드 입력버그가 수정되어 말씀드립니다.

현재 알려주신 "마타주"앱으로 확인해본 결과 정상적으로 동작을 하는데~ 한번 확인 부탁드려요~

추후 추가적인 이슈가 있으시면 언제든 이슈 등록 부탁드려요~
감사합니다~^^

**Comment by dir4you** [comment]
안녕하세요! 
말씀해주신 내용을 보고 테스트해 본 결과, 정상작동하는 것으로 확인되었습니다. ^^
신속하게 응대해주셔서 편하게 사용할 수 있게 되었어요. 꼼꼼하게 확인과 검토를 진행해 주셔서 다시 한 번 감사말씀 드립니다.
