### ISSUE TITLE
영문 주소 선택 시 영문으로 표기 문의

### ISSUE THREAD

**Issue by minkeuncho** [daumPostcode/QnA#490]
Daum의 우편번호 API를 잘 사용하고 있습니다,
좋은 API 제공에 매우 감사합니다.

현재 서비스중인 페이지가 다국어를 지워해야할 상황에 놓여 문의드립니다.

한글주소 검색후 영문변환은 가능하나, 영문명 클릭 시 한글 값이 들어가는 것을 

영문으로 값이 들어가게 할수 있나요?

**Comment by daumPostcode** [comment]
@minkeuncho 
안녕하세요~

공식가이드페이지 (http://postcode.map.daum.net/guide#attributes)
의 속성부분을 보시면, 각 주소정보를 담고 있는 변수
address
jibunAddress
roadAddress
autoJibunAddress
autoRoadAdress
는 모두 쌍으로 English라는 단어를 뒤에 붙히면 (ex. addressEnglish)
영문값을 얻으실 수 있습니다.

이부분 참고 부탁드립니다~
