### ISSUE TITLE
주소가 검색되지 않습니다. (행정자치부에서는 검색됨 ) 

### ISSUE THREAD

**Issue by bluesavor** [daumPostcode/QnA#491]
- 도로명 : 종로구 창의문로 3길 13

위 주소는 행정자치부에서는 검색이 잘 되나, 현재 다음 주소에서는 검색이 되지 않고 있습니다. 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@bluesavor 
안녕하세요~

해당주소 데이터 담당자분께 문의해서 수정하도록 하겠습니다.
제보 감사드립니다 ^^

**Comment by reedfim** [comment]
@bluesavor

안녕하세요~ 현재 해당 주소 오류 수정되어 서비스에 반영되었습니다.
제보 감사드립니다 ^^
즐거운 하루 되세요~

**Comment by daumPostcode** [comment]
@bluesavor

안녕하세요~ 현재 해당 주소 오류 수정되어 서비스에 반영되었습니다.
제보 감사드립니다 ^^
즐거운 하루 되세요~
