### ISSUE TITLE
안녕하세요 급합니다. 빠른 확인 부탁드립니다.

### ISSUE THREAD

**Issue by mimipet123** [daumPostcode/QnA#492]
앱에서 주소 검색이 안되어서  7월 말에 질문을 했었고 
- 혹시 해당 앱이 어떤 앱인지 알려주실 수 있으신가요?
또는 document.domain값을 사용하시는지, 또는 http프로토콜용 API를 사용하시는지
 사용하는 서비스에서 location.host, location.protocol 값도 알려주시면 감사하겠습니다.
여기에 적기 힘드시면
goni.r@kakaocorp.com 으로 보내주시면 감사하겠습니다

이렇게 답변이 와서 

안드로이드 앱 이름 : 미미살롱펫

안드로이드 앱에서 웹뷰로 로드하는 URL : http://210.180.118.201/mimiRes/addrtogps_android.html

addrtogps_android.html에 Daum API 정의 
   <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
   <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=051bb0272ed4b4ba2df14918429a1539&libraries=services"></script>

갑자기 질문이 사라졌습니다. 

확인 꼭 바랍니다.  

이메일로도 보냈습니다.

**Comment by daumPostcode** [comment]
@mimipet123 
안녕하세요~

넵 답반이 늦어서 죄송합니다.
"미미살롱펫" 이라는 앱은 플레이스토어에서 검색이 안되서 (미미살롱펫 for 디자이너 만 검색되네요;;)
알려주신 페이지를 확인해 봤는데요.

말씀해주신 페이지를 보니 open()함수를 이용한 팝업형 모드를 사용하신것 같습니다.
[FAQ10](https://github.com/daumPostcode/QnA#10-iosandroid%EC%97%90%EC%84%9C-webview%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-%EC%82%AC%EC%9A%A9%ED%95%A0-%EC%88%98-%EC%9E%88%EB%82%98%EC%9A%94)번을 확인해보시면 적혀 있는데요,

웹뷰에서 window.open함수를 잘 지원하는지 확인을 해보셨으면 좋겠습니다.
저희가 쓰는 방식은 ''(공백=about:blank)를 팝업을 띄운후, 그 팝업객체를 받아서 document.write로 내부에 컨텐츠를 쓰는 방식입니다. (IE계열 하위브라우저와 동시에 대응 가능한 코드라 좀 복잡하게 되어 있습니다)

만약 이게 잘 적용이 안되어 있다면, embed 함수를 이용한 방식으로 이용하시는걸 추천드립니다.
(PC에서 알려주신 페이지를 열어보니 팝업제한을 풀라고 하네요, 혹시 웹뷰에서도 이런 옵션이 있어서 팝업을 못열게 하는게 아닐까 하는 생각이 듭니다;;)

확인부탁드려요~

추가로, 저는 github에 올라온 어떤 질문도 삭제하지 않습니다.
