### ISSUE TITLE
다음지도 api 활용 시 UI 커스텀 가능 범위 문의드립니다.

### ISSUE THREAD

**Issue by chloekwon** [daumPostcode/QnA#493]
다음 우편번호 검색 api 사용 시
다음에서 제공하는 우편번호 검색 폼 형식이 아닌
자체 스크립트로 개발하여 저희 쪽 디자인으로 커스텀할 수 있는 방법이 있는지 문의드립니다.
또한 상기와 같이 작업 시 powerd by Kakao 라는 로고를 미노출해도 무관할까요?

질문 답변 부탁드리겠습니다.

**Comment by daumPostcode** [comment]
@chloekwon 
안녕하세요~

아뇨 현재 검색팝업의 레이아웃자체를 변경할 수 있는 기능은 없습니다.
그렇기 때문에 powerd by kakao또한 삭제하실 수 없습니다.

만약 데이터만 필요하신 경우라면
저희 API보다는

행정안전부 도로명 검색시스템에서 제공하는 행안부API(http://www.juso.go.kr/addrlink/main.do?cPath=99JM)
또는
postcodify (https://www.poesis.org/postcodify/) 를 이용해 보시는게 어떠실까 합니다.

감사합니다.
