### ISSUE TITLE
[급]중국에서 http://dmaps.daum.net/map_js_init/postcode.v2.js 로딩시 속도문제

### ISSUE THREAD

**Issue by pinksola** [daumPostcode/QnA#494]
중국에서 저희 사이트 접속시 속도가 느려서 확인해봤더니
http://dmaps.daum.net/map_js_init/postcode.v2.js 
이 파일 로딩이 잘 되지 않고 있습니다.

그래서 http://dmaps.daum.net/map_js_init/postcode.v2.js 이 파일을 로컬로 수정하려고 했으나
다른 이슈들의 답변을 참고해보니 로컬에서 불러오면 추후 업데이트등에 대한건 제공받는게 힘들다고 그러셔서 ㅠㅠ

중국쪽에서 왜 이 파일로딩시 속도가 안나오거나 아예 파일로딩이 되지 않을까요~
혹시 로컬에서 로딩하는 방법 말고 속도지연문제를 해결할 방법이 있을까요?
중국쪽에서 운영중인 다른 한국사이트들중 이 다음주소검색 api를 사용하는 다른 방법이 있을지
문의드려봅니다~

감사합니다~!!

**Comment by daumPostcode** [comment]
@pinksola 
안녕하세요~

일단 스크립트 자체가 중국에서 다운로드가 느린이유는 정확히 설명 드리진 못할것 같습니다.
CDN서버에 타국에서 접속시 속도가 안나오는지 그런건 제가 알수가 없는 상황이라서요;;
즉 네트워크쪽 관련된 문제는 제가 답변을 드리기 어려운점 말씀드립니다.

이외, 코드레벨에서 한가지 설명을 드리면
기본적으로 저희 JS API는 
1. postcode.v2.js 파일을 다운로드 받은 다음에,
2. 19XXXX.js 라는 core스크립트를 다운로드 받게 됩니다.

다만 정적로딩 방식을 이용하신다면
1번이 수행이 된 후에, 2번을 수행시 document.write를 통해 페이지 페이지 렌더링과 동기화 처리를 시켜버리기 때문에, 저희 우편번호서비스 코어스크립트가 모두 로딩되서 파싱되기 전까지, 웹페이지가 뜨질 않습니다.
그래서 크롬에서 정적로딩 방식을 쓴 상태에서 콘솔을 여셔서 보시면, 네트워크가 느린 경우에 페이지가 블락킹이 될수 있다고 경고문구가 뜹니다.
즉 이럴 경우에는, 저희 스크립트를 웹페이지의 맨 하단에 넣거나, 밑에 설명할 동적로딩 방식을 이용하시면 됩니다.

저희 가이드 페이지를 보시면 로딩 방식이 2가지가 있습니다.
그중 두번째가 동적로딩으로 ?autoload=false를 파라미터를 추가하고, daum.postcode.load() 함수를 이용하는 방식입니다.
이 방식은 따로 페이지 렌더링 블락을 걸지 않기 때문에, 저희 스크립트로 하여금, 페이지가 그려지지 않거나 하는 일은 발생하지 않습니다. 

물론 맨 앞에 말씀드린 것처럼 정적로딩이던 동적로딩이던 네트워크 문제로 파일자체가 다운로드가 안되면,, 우편번호 서비스가 실행이 되진 않겠죠;;;

아무튼, 웹페이지의 초기 접속시 느리다면, 정적로딩 방식을 사용중이신것 같고, 그게 네트워크가 느린 상태에서 페이지 블락킹을 시켜서 더 늦게 뜨는 것처럼 보이는 것일 수 있습니다.
저희 스크립트를 body맨 하단에 위치, 또는 동적로딩 방식으로 변경을 해보심이 어떠실까 합니다.

자세한 사항은 가이드 페이지를 참고해주세요~
