### ISSUE TITLE
윈도우 XP ie8 에서 호출시 에러가 발생합니다.

### ISSUE THREAD

**Issue by kkng01** [daumPostcode/QnA#495]
첨부된 이미지와같이 에러가 발생하는데 ie8은 지원안하나요?

확인부탁드립니다.

![에러](https://user-images.githubusercontent.com/54053506/62916686-62370480-bdd4-11e9-94e1-988c6c2ab2cc.png)

**Comment by daumPostcode** [comment]
@kkng01 
안녕하세요~

현 시점 기준
기능적으로 IE8은 대응하고 있습니다.
다만 현재 회사에서 XP,IE8의 경우 보안적인 측면으로 인해 테스트 환경이 없어서 재현을 하진 못할 것 같습니다.
(XP는 2014년 4월 8일, IE8은 2016년 1월 12에 Microsoft사에서 공식 지원 종료한 OS와 브라우저입니다, 되도록이면 Windows10 플랫폼을 이용해 주시면 좋을 것 같습니다.)

일단 해당 오류가 발생할 수 있는 상황이 있습니다.
오류가 발생한 코드 라인을 보면
d.body가 없다는 것인데, 이는 document.body가 존재하지 않다는 것을 의미 합니다.
추가로 document.body가 위치한 코드가 실행이 될려면, embed(target) 함수에서 target값에 null또는 undefined가 들어가고 있다는 것을 의미합니다.

우선 질문자님의 코드에서
target값이 정확한 Dom Object로 잡히는지 확인 부탁드리며
postcode.v2.js와 190722.js 파일이 다운받아지고 해석되기 전에, document.body 객체에 무언가 다른 작업을 수행해서 body객체를 null로 바꾸는 것은 아닌지, 확인 부탁드립니다.

일단 현재 올려주신 alert창 하나만으론 위와 같이 유추할 수 있습니다.
추가 질문이 필요하신 경우 추가 댓글 부탁드리며,
이용하시는 코드까지 첨부해 주시면 좋을 것 같습니다.

저희 API는 독립적으로 실행되기 보다, 이용하는 사용자의 환경에 영향을 받는 코드이니만큼, 이용하시는 방법도 확인이 필요합니다. 또는 저희 API를 이용하시는 사이트를 제공해 주셔도 좋습니다.

감사합니다.
