### ISSUE TITLE
검색결과 선택후 화면처리 문의

### ISSUE THREAD

**Issue by typingmachine** [daumPostcode/QnA#497]
안녕하세요.

예제를 참고하여 embed모드를 사용하여 개발 중입니다.

검색결과 주소 선택을 하면 검색결과 셋팅 후 결과 내용이 사라지는데요.

결과 내용을 사라지지 않고 그대로 두는 옵션은 없는지 궁금합니다.

**Comment by daumPostcode** [comment]
@typingmachine 
네~ 안녕하세요~

저희 가이드 페이지를 보시면 open()/embed() 함수의 인자로 설정하실 수가 있습니다.
http://postcode.map.daum.net/guide#methods

위 페이지에 가셔서 함수부분에 보시면 함수의 인자로 { autoClose:false}를 주면 원하시는 결과를 얻으실 수 있으실 거에요.

다만 embed모드를 사용시에는 저희 가이드 페이지에서는 target DOM node를 display:none을 시키는데,
이것과 위 함수의 동작은 별개로 동작하는 것이니 참고 부탁드립니다.
