### ISSUE TITLE
윈도우 XP ie8 버전 호출시 에러 문의

### ISSUE THREAD

**Issue by kimhaegyeong** [daumPostcode/QnA#498]
안녕하세요.

윈도우 XP ie8을 사용중입니다.
#495 와는 다른 에러메시지가 발생해서 문의드립니다.

저희는 포스에서 윈도우 xp를 사용하여 ie 버전 업그레이드가 어렵습니다 ㅠ
검토부탁드립니다.

![20190826_173014](https://user-images.githubusercontent.com/8994267/63677632-60376180-c828-11e9-8e7c-c88775c26a87.jpg)

**Comment by daumPostcode** [comment]
@kimhaegyeong 
안녕하세요~
해당 오류의 경우엔, 코드레벨 오류라기보다, IE의 설정 이슈로 확인이 됩니다.
800704a6라는 오류 코드명은 제가 작성한 코드에서는 나올수가 없는 오류거든요;;; ㅎㅎ

구글링을 좀 해보니, XP의 IE8 보안옵션관련된 부분같아 보입니다.
[인터넷 옵션] -> [보안]탭 -> [인터넷] 선택 -> 사용자 지정 수준을 선택해서

"기타" 부분에 "팝업 차단 사용" 이걸 해제해 주시고 (즉 팝업을 항상 허용하겠다는 의미)
"스크립팅" 부분에  Active스크립팅 체크, XSS필터링 체크를 한번 해보셔요.
또는 보안등급을 "보통" 정도로 한번 셋팅해보시는게 어떠실까 합니다.

팝업설정의 경우 [개인정보]탭에 들어가도 설정이 가능하실것 같아요.

한번 확인 부탁드립니다.

아래글 참고 부탁드립니다.
https://social.msdn.microsoft.com/Forums/ie/en-US/4357c254-d571-4166-bd62-ca7f21be121a/ie-8-800704a6-when-opening-javascript-driven-web-pages?forum=iewebdevelopment

감사합니다.
