### ISSUE TITLE
주문페이지에서 우편번호 검색창이 뜨지 않습니다. 

### ISSUE THREAD

**Issue by FFDROOT** [daumPostcode/QnA#499]
안녕하세요. 저는 농사펀드라는 사이트 운영자입니다. 
www.ffd.co.kr 

주문결제 페이지에서 받을 곳 주소입력을 위해 우편번호 검색을 이용하고 있는데요. 
몇일 전 간헐적으로 웹과 모바일에서 우편번호 검색창이 뜨지 않는 경우가 발생했습니다. 
새창으로 다시 접속하거나 새로고침을 해서 문제가 해결되었는데요. 
어제 밤부터는 이 문제가 계속되고 있습니다. 

일을 도와주는 개발자 검토의견으로는 
https://t1.daumcdn.net/postcode/api/core/190722/1563776399461/190722.js
위 자바스크립트 리소스 로드에 실패해서 검색창이 안뜨는데 원인을 잘 모르겠다고 합니다. 
어떻게 조치해야 될까요? 

갤럭시 s10+에서 크롬 브라우저, 기본 브라우저 2가지 시도해도 안되었고
아이폰7 사파리, 크롬브라우저에서도 같은 현장입니다. 
웹 웨일브라우저, 인터넷 익스플로러에서도 마찬가지입니다.

**Comment by daumPostcode** [comment]
@FFDROOT 
안녕하세요~

현재 해당이슈에 대해서 원인을 파악중인데,, 확실히 무엇때문에 발생한 것인지 확인은 하지 못하였습니다.
(서비스 6년째 운영중인데,, 처음 받는 CS네요;;;;)

일단 저희 우편번호 서비스는 코어스크립트 로딩방식이 2가지가 있는데요
1. 정적로딩
2. 동적로딩

지금 현재 고객님 사이트에 적용된 버전은 정적로딩 방식입니다.
이는 postcode.v2.js 를 로딩하자마자 document.write로 코어스크립트를 받는 것인데, 이상하게, 이 스크립트 자체가 실행이 안되는 케이스가 발생을 하네요;; 이부분은 연구가 필요한 부분이라;; 바로 답변은 드리기 어려울것 같습니다.

두번째 방식인 동적로딩 방식을 이용해 보시는게 어떠실까 합니다.
https://spi.maps.daum.net/postcode/guidessl
위 가이드 페이지에 보시면 기본사용법에 동적로딩 방식이 있습니다.
사용방식이 살짝 다른데요. 개발자분께서 보시면 금방 적용가능하십니다.
위 방식은 document.write를 사용하지 않고, 코어 스크립트를 페이지가 초기화될때 부르지도 않기 때문에, 많이 사용하시는 방법입니다.
한번 이걸로 테스트 부탁드려요.~

추가로, 저희 API의 주소가 spi.maps.daum.net으로 되어 있는데, ssl.daumcdn.net으로 변경되었어요~ 
모든건 가이드 페이지에 적혀 있으니 한번 확인 부탁드립니다.

감사합니다.

**Comment by FFDROOT** [comment]
답변감사드립니다. 
답변 주신 내용을 모두 적용해 보았는데 현재 


![Screenshot 2019-08-28 at 11 18 13](https://user-images.githubusercontent.com/54564691/63821365-b373f600-c987-11e9-9205-2b78337aa3ec.jpg)

코드는 모두 정상인 것은 확인했고 다른 코드들로 바꿔서 테스트 해봤는데 항상 문제는 js 파일 로드를 못한 것…

두 가지 로딩 방식 중 정적로딩을 사용하고 있고
어제 동적로딩으로 바꿔서 테스트 해봤고 결과는 역시 동일하게 js 파일 로드 못한 것..

다른 점이라면 동적로딩으로 하면 팝업 창은 뜨는데 안에 내용이 표시가 안됨. (js 파일에서 내용을 가져와야 하는데 로드가 안되니..)

**Comment by FFDROOT** [comment]
답변 감사드립니다. 

답변 주신 내용으로 다 조정해 보았는데 다시 같은 문제가 발생하고 있습니다.
어제 밤 12시 ~ 1시쯤 테스트했을 때는 정상적으로 작동했었는데 오늘 오전에 다시 문제가 발생했습니다. 

모바일(아이폰7)에서는 레이어창이 뜨지않고 
웹브라우저(크롭, 웨일)에서는 창이 뜨고 검색까지 되는데 결과 주소가 클릭이 되지 않습니다. 

![Screenshot 2019-08-28 at 11 18 13](https://user-images.githubusercontent.com/54564691/63821433-f6ce6480-c987-11e9-9c9f-33c664a9f331.jpg)



원인 파악이나 조치가 오래 걸리는 문제일까요? 
주소입력 문제로 주문완료 자체가 안되고 있어서 오래 걸리는 문제라면 불편하더라도 주소검색을 빼고 '텍스트필드'로 변경하는 결정을 내려야 할 것 같아서 다시 한번 문의드립니다. 

아래는 개발자의 작업 공유내용입니다. 

코드는 모두 정상인 것은 확인했고 다른 코드들로 바꿔서 테스트 해봤는데 항상 문제는 js 파일 로드를 못한 것…

두 가지 로딩 방식 중 정적로딩을 사용하고 있고
어제 동적로딩으로 바꿔서 테스트 해봤고 결과는 역시 동일하게 js 파일 로드 못한 것..

다른 점이라면 동적로딩으로 하면 팝업 창은 뜨는데 안에 내용이 표시가 안됨. (js 파일에서 내용을 가져와야 하는데 로드가 안되니..)

지금은 된다니 조금 더 지켜봅시다..

맨 아래 주소는 daumcdn으로 다시 바꿔놨음…

daumcdn 주소가 안되서 spi.map으로 바꾼 건데…

이슈 계속 공유해줘…

**Comment by daumPostcode** [comment]
@FFDROOT 

네~
해당 내용의 원인은 파악이 완료되었으며, 수정을 해야하는데, 로더 모듈 자체를 변경할 예정이라 시간이 좀 걸릴 것 같아요.

해당 로더 모듈이 현재 웹서비스들에서 사용하는 방식은 아니고, 서비스가 예전에 배포되다보니; 좀 옛날 방식을 쓰고 있긴 합니다. 그래서 해당 모듈의 변경을 현재 고려중에 있습니다.

우선 문제의 원인은 홈페이지에서 부르는 여러 다른 스크립트의 async 옵션에 의해서, 스크립트가 중간에 끼어들어서 저희쪽 로더에서 실패가 발생하는 것으로, async속성을 빼신다면 해결이 될 수 있을 것으로 보이나, 이는 적절치 못한 수정방법이기 때문에, 동적로딩 방식을 권해드린 것인데요.

동적로딩의 경우 daum.postcode.load 함수가 실행될때 script태그를 따로 생성해서 head에 삽입하는 것인데,
이또한 동작이 안된다니 좀 고민이 필요하네요.
어떻게 사용하고 계실지 모르지만,

메인 스크립트는
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false"></script>

이렇게 적어두시고, 주소검색 버튼을 눌렀을때
sample3_execDaumPostcode() 이 함수를 실행시키는게 아니라
daum.postcode.load(function() { sample3_execDaumPostcode() })
이렇게 실행되게 해보시면 스크립트 로딩이 실패하는 현상은 뜨지 않을 것 같습니다.

그리고 추가 질문주신것중에
검색결과 목록에서 주소 데이터를 못 뽑아 내는것은, 지금의 로딩 문제와는 별개입니다.
이는 oncomplete함수내의 오류가 발생하고 있을 가능성이 매우 큽니다(실제 90% 이상 oncomplete내부의 null포인터 접근 오류로 발생하더라구요.)
oncomplete함수의 구현은 저희가 제공하는게 아니라, 이용하시는 분께서 자신의 사이트에 맞춰서 재차 구현해줘야 하는 부분이기 때문에, 이부분 먼저 확인 부탁드립니다.

한번 확인 부탁드립니다.

**Comment by Daeik** [comment]
jQuery의 `$.getScript`에서도 동일 증상이 이전에는 없었는데 얼마 전부터 발생하고 있습니다.

기존에는 `?autoload=false` 없이 `$.getScript` 함수로 동적 로딩한 뒤 `daum.postcode.load` 함수를 호출하면 `new daum.Postcode` 생성자가 존재했는데, 이제는 `?autoload=false` 없이 `$.getScript`를 이용해서 로드하면 네트워크 상에서 코어 코드를 로드조차 하지 않는 동일 현상이 발생하니 참고 부탁드립니다!
