### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by han3388** [daumPostcode/QnA#5]
안녕하세요.
아래 답변 감사드립니다.

그런데 적용후 첨부하는 파일처럼 주소 검색은 되는데 선택을 하면 홈페이지 주소록에 적용될때 에러가 생긴다고 합니다.
![111](https://cloud.githubusercontent.com/assets/21211371/17926203/089504ae-6a2b-11e6-8169-8f1a5ef55f33.JPG)

이유가 뭔지 찾을 수가 없다고 하네요.

더더욱 이상한 것은 어떤 컴에서는 정상으로 되고 어떤 컴에서는 안된다는 것입니다. 반반 정도로요.
휴대폰도 마찬가지고요.
pleaseReadGuide 이 옵셥도 주소가 정상적으로 적용되는 컴에서는 되지만 그렇지 않은 컴에서는 안됩니다.

혹시 예전 우편번호 방식으로 2칸으로 나누어져서 그런건 아닌지 문의해보니 보이는 것만 그렇게 했고
데이타 소스상으로는 새우편번호를 불러오도록 했다고 하네요.
에러 생기는 칸을 보면 1번째와 3번째칸 인것으로 보면 분명 예전의 버전에서 새버전으로 바뀌면서 
무언가 충돌이 생기는 것 같아보이기도 한는데 무엇 때문인지 찾기 힘들다고 하네요.

이런 사례가 있나요?
이유가 뭔지...?? 답답하네요.

**Comment by daumPostcode** [comment]
@han3388 
네~ 

첫번째
v1과 v2는 대부분 비슷하지만, 단순히 스크립트만 바꾼다고 해서 100%바뀌진 않습니다.
주소부분에 undefined로 떨어지는 것은 v2버전에서 제공하지 않는 데이터를 이용하실 가능성이 있습니다.
이부분은 소스코드나 확인 가능한 URL이 있으면 제가 확인해 드릴 수 있는데요. 이는 시간이 좀 걸리니
[가이드 페이지 - 이전버전에서 옮기기](http://postcode.map.daum.net/guide#upgrade) 와, [속성](http://postcode.map.daum.net/guide#attributes) 부분의 oncomplete 콜백 데이터 설명과, 그 아래 파란색 박스로 "자세히 알아보시겠습니까?"라는 설명 박스가 있습니다. 그 부분도 참고해 보시면 도움이 되실 거라 생각됩니다.

두번째
pleaseReadGuide의 경우에는 검색결과에 따라 반응합니다. 즉 최소 값(3)으로 입력시 3페이지 이상 검색결과가 나오지 않는다면 작동하지 않습니다. 이는 강제고 1,2를 넣어도 3으로 자동 셋팅되기 때문에 그 이하는 작동되지 않습니다.
이외 다른 문제점은 현재로써는 파악이 안되고, 같은 주소를 검색했는데 되는 컴과 안되는 컴이 있다면, 해당 주소와, 컴퓨터들의 OS, 그리고 사용한 브라우저 정보를 알려주시면 확인해 보도록 하겠습니다.
