### ISSUE TITLE
위치정보도 지원되나요?

### ISSUE THREAD

**Issue by cafewill** [daumPostcode/QnA#50]
주소 검색후 선택한 항목에 대한 위치 정보 (geocode) 도 지원되나요?

**Comment by daumPostcode** [comment]
@cafewill 
네~ 안녕하세요~

현재 저희 API에서 제공되는 정보는 [가이드 페이지의 속성부분의 oncomplete 설명란](http://postcode.map.daum.net/guide#attributes)에 적혀 있습니다.

말씀하신 geocode의 경우에는 제공되지 않습니다.

**Comment by cafewill** [comment]
@daumPostcode 

답변 감사합니다.
일단 아래 구글 api 로 해결은 했는데.. 다음 지도 api 에서도 지원되면 유용 할 것 같습니다 ^^
https://developers.google.com/maps/documentation/geocoding/intro

**Comment by daumPostcode** [comment]
@cafewill 
아~ 네 ㅎㅎㅎ

저희 우편번호 서비스에서는 지원하지 않지만; 저희 지도 API를 통해서는 이용가능합니다~ 구글을 이용하셔도 거의 같은 결과를 얻으실수도 있구요~ 편한 방법으로 이용하셔도 됩니다~

저희 가이드페이지 샘플부분의 맨 마지막 샘플도 그와 관련된 샘플이며

지도 API 다큐멘테이션은 [map v3 service.Geocoder](http://apis.map.daum.net/web/documentation/#services_Geocoder) 와 [지도API샘플](http://apis.map.daum.net/web/sample/addr2coord/)을 참고하시면 됩니다 ^^

감사합니다~

**Comment by cafewill** [comment]
@daumPostcode 

아.. 그렇군요! 답변 감사합니다 (__)

**Comment by cafewill** [comment]
@daumPostcode 

주말에 알려주신 다음 지도 api 를 몇가지 테스트해봤는데.. javascript 을 활용한 샘플외에 커맨드라인 샘플은 없나요? xml, json 포멧 등 rest 로 연동할 수 있는게 있음 좋겠네요 ^^

**Comment by daumPostcode** [comment]
@cafewill 
네~ 안녕하세요~

일단, 우편번호서비스의 경우 REST API는 제공하고 있지 않습니다.

다만 좌표변환의 경우 REST API로 제공합니다 [Daum Developers 로컬 API 참고](http://developers.daum.net/services/apis/local) 해당 API는 우편번호 서비스와 다르게 apikey가 필요하며, 설명을 읽어보신 후 사용하시면 될것 같아요~

**Comment by cafewill** [comment]
@daumPostcode 

넵.. 정말 많은 도움이 되고 있습니다. 감사합니다 (__)
