### ISSUE TITLE
아래 이슈, 안내해 주신 방법으로 조치했는데 해결이 안되었습니다. 

### ISSUE THREAD

**Issue by FFDROOT** [daumPostcode/QnA#500]
답변 감사드립니다.

답변 주신 내용으로 다 조정해 보았는데 다시 같은 문제가 발생하고 있습니다.
어제 밤 12시 ~ 1시쯤 테스트했을 때는 정상적으로 작동했었는데 오늘 오전에 다시 문제가 발생했습니다.

모바일(아이폰7)에서는 레이어창이 뜨지않고
웹브라우저(크롭, 웨일)에서는 창이 뜨고 검색까지 되는데 결과 주소가 클릭이 되지 않습니다.
![Screenshot 2019-08-28 at 11 18 13](https://user-images.githubusercontent.com/54564691/63821725-039f8800-c989-11e9-9959-0d695297d717.jpg)

원인 파악이나 조치가 오래 걸리는 문제일까요?
주소입력 문제로 주문완료 자체가 안되고 있어서 오래 걸리는 문제라면 불편하더라도 주소검색을 빼고 '텍스트필드'로 변경하는 결정을 내려야 할 것 같아서 다시 한번 문의드립니다.

----- 아래는 개발자의 작업 공유내용입니다. -----

코드는 모두 정상인 것은 확인했고 다른 코드들로 바꿔서 테스트 해봤는데 항상 문제는 js 파일 로드를 못한 것…

두 가지 로딩 방식 중 정적로딩을 사용하고 있고
어제 동적로딩으로 바꿔서 테스트 해봤고 결과는 역시 동일하게 js 파일 로드 못한 것..

다른 점이라면 동적로딩으로 하면 팝업 창은 뜨는데 안에 내용이 표시가 안됨. (js 파일에서 내용을 가져와야 하는데 로드가 안되니..)

지금은 된다니 조금 더 지켜봅시다..

맨 아래 주소는 daumcdn으로 다시 바꿔놨음…

daumcdn 주소가 안되서 spi.map으로 바꾼 건데…

이슈 계속 공유해줘…

**Comment by daumPostcode** [comment]
@FFDROOT 
안녕하세요~

아래글에 적용방법 다시 설명드렸는데; 해당 방법으로 처리해 보셨을까요?
https://github.com/daumPostcode/QnA/issues/499#issuecomment-525569400

요약하면
주소검색 버튼의 onclick 이벤트에
sample3_execDaumPostcode() 이 함수를 바로 실행하게 되어 있는데
가이드 페이지에 있는 것처럼
    //load함수를 이용하여 core스크립트의 로딩이 완료된 후, 우편번호 서비스를 실행합니다.
    daum.postcode.load(function(){
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
                // 예제를 참고하여 다양한 활용법을 확인해 보세요.
            }
        }).embed(target);
    });

new daum.Postcode()를 실행하기 전에 daum.postcode.load함수를 실행하고 new daum.Postcode를 콜백으로 넣어서 실행해 보시는걸 추천드립니다.

이렇게 하면. 버튼을 클릭할때 코어스크립트를 로딩하게 되고, 로딩이 끝나면 new daum.Postcode를 실행하기 때문에, 코어 스크립트가 로딩이 안되는 현상은 발생하지 않을거에요. 

지금 발생하는 이슈는 스크립트 로딩에 대한 타이밍 문제이고, 이 타이밍 문제는 페이지가 초기화될때, 수많은 스크립트를 부르면서 발생되기 때문에, 모든 로딩이 끝난후에 검색 버튼 누를때 별도로 로딩한다면 문제가 없을거에요.
실제 SPA를 만드시는 분들께 추천드리는 방법이기도 합니다.

그리고 아래글에서 댓글로 말씀드린 것처럼
주소 검색 결과를 선택했을때 아무런 동작을 안하는 것은 oncomplete함수의 내부 구현을 확인해 보시기 바랍니다.

또는 제가 확인할 수 있는 URL을 알려주시면 접속해서 확인해 보도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@FFDROOT 
안녕하세요~
현재 어제 원인 파악한 부분 수정되어 배포되었습니다.

다만 위 댓글이나 어제 올려주신 이슈의 답변처럼, 동적로딩 방법을 사용하면 해결가능하며,
정적로딩방식을 사용하더라도 2019년 19시 45분 패치로 인해서 오류가 발생한 상황은 발생하지 않을거라 생각됩니다.

끝으로, 현재 우편번호 서비스의 API 로더스크립의 경우, 지금과 같이 2단계 로딩을 하지 않고,
단일 로딩으로 처리할 수 있도록 준비중에 있습니다.
위 방식이 개발이 완료되면 카카오톡 플러스친구를 통해 공유해 드리도록 하겠습니다.

감사합니다.

**Comment by freeand01** [comment]
오늘 오전부터 잘되던 주소 검색창이 갑자기 안되는 버그가 발생하였습니다. 
위 내용을 보니 뭔가 업데이트가 이루어지고 나서 문제가 생긴 것으로 보이네요ㅠ-ㅠ
커머스라 데미지를 크게 입었네요. 주문 자체가 진행이 안되니...

PC는 정상 작동하나 모바일에서만 작동이 안되었고
현재는 소스를 수정하여 정상 작동 되고 있습니다.

저희 쪽에서는 동적 로딩을 하고 있는데 js를 호출 할 때 
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
이렇게 사용 하고 있었습니다. 요 몇년간은 정상적으로 사용 했었습니다.

그러다 오늘 오전에 팝업이 안뜨는 걸 확인하고 혹시 몰라서 이걸 메뉴얼대로 
<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>
이렇게 자동 로딩을 막는 호출로 변경을 하니 바로 정상 작동 하더라고요ㅠㅠ 다행..

저희 몰 처럼 갑자기 우편번호 팝업이 안떠서 당황하신 분들을 위해 
댓글을 남겨 봅니다.

**Comment by FFDROOT** [comment]
@daumPostcode 님. 빠르게 패치를 진행해주셔서 고맙습니다. 
PC와 모바일에서 정상적으로 작동됩니다. 
몇일 간 이 문제때문에 고생했는데 도움 주셔서 고맙습니다. 

@freeand01 업데이트 되면서 문제가 있으셨군요. 
그렇게 정보 공유해주셔서 이후 저희같은 문제가 생기는 분들께 도움이 될것 같네요.
고맙습니다.

**Comment by daumPostcode** [comment]
@FFDROOT @freeand01 
먼저 잘 해결되셨다니 다행입니다.
하지만 몇일,, 몇시간동안 서비스에 장애를 일으킨 점 죄송하게 생각합니다.

이에따라, 현재 현행 유지중인 스크립트 로딩방식(로더+코어 독립로딩)을 버리고,
단독 스크립트 로딩으로 변경하려 합니다. 이렇게 변경이 되면, 스크립트가 로딩되기 전에, daum.Postcode를 실행하는 상황만 아니라면(이건 당연한거니;;) 지금처럼 코드레벨상 오류로 인해 스크립트가 로딩이 되지 않는 경우는 없을거에요. (당시에는 인프라가 뒷받침을 해주지 못해서;; 할 수가 없었던 상황이였고 지금은 가능합니다)

해당 변경건은 개발이 완료되면 우편번호서비스 플러스친구로 공지하도록 하겠습니다.

다시한번 불편을 드려 죄송합니다.
