### ISSUE TITLE
도로명 주소 반영 시 입력칸 character제한

### ISSUE THREAD

**Issue by ashley101-cyber** [daumPostcode/QnA#501]
도로명 주소 반영 시 입력칸 character제한으로 도시, 시 등 각각의 구분자 DB를 따로 올릴 수도 있는지 궁금합니다. 
있는 경우 DB 를 어디서 확인하면 될까요?

**Comment by daumPostcode** [comment]
@ashley101-cyber 
안녕하세요~
문의 주신 내용이 약간 이해가 되지 않는데,, 음.
저희 JS API를 사용할때 발생하는 문제가 아닌, 저희가 내부에서 사용하고 있는 도로명 주소의 DB가 필요하다는 말씀이실까요?

이 질문이시라면, 현재 저희는 별도로 REST API방식으로 우편번호 서비스에서 사용하는 데이터를 내릴 계획은 없으며, 이외 별도의 DB제공도 계획이 없는 점 참고 부탁드립니다.

별도의 DB가 필요하시다면, 행안부 도로명주소검색시스템에서 제공하는 API나, Postcodify에서 제공하는 API를 한번 확인해 보시는게 어떠실까 합니다. 

감사합니다.
