### ISSUE TITLE
daum.Postcode is not a constructor 오류 질문드립니다.

### ISSUE THREAD

**Issue by jiyoung4** [daumPostcode/QnA#503]
안녕하세요.
현재 다음 우편번호 API를 사용하고 있습니다.
ssl 적용한터라 새로운 버전으로 적용하고 autoload=false 설정 및 동적로딩해서
잘 사용하고 있었습니다.
그런데 지난주 부터 팝업창이 뜨지 않고 아래와 같은 오류가 발생합니다.
원인을 알 수 있을까요?

ERROR TypeError: daum.Postcode is not a constructor
    at profile.component.ts:117
    at f (postcode.v2.js:1)
    at Object.a.postcode.load (postcode.v2.js:1)
    at ProfileComponent.push../src/app/pages/main/profile/profile.component.ts.ProfileComponent.openSearchAddress (profile.component.ts:103)
    at Object.eval [as handleEvent] (ProfileComponent.ngfactory.js:532)
    at Object.handleEvent (core.js:23107)
    at Object.handleEvent (core.js:23652)
    at dispatchEvent (core.js:20556)
    at core.js:21003
    at HTMLInputElement.<anonymous> (platform-browser.js:993)

daum.postcode.load(function () {
      new daum.Postcode({                                 ---> 이부분에서 걸립니다.
        oncomplete: function (data) {

load 이후 코어 스트립트가 안올라오는 것 같습니다.
개발자 도구에서 postcode.v2.js는 확인되나 그 이후에 생성되야 하는 19XX.js는 없습니다.

**Comment by daumPostcode** [comment]
@jiyoung4 
안녕하세요~

먼저 불편을 드려 죄송합니다.
저희 가이드 페이지에 있는 이 방식으로 로딩을 하고 계신 것이지요?
![image](https://user-images.githubusercontent.com/20675065/64143451-0c8dcf00-ce4b-11e9-91b8-55cf7cd9ccc8.png)

위 원인은 코어스크립트 로딩 실패가 맞습니다.
현재 발생하는 에러는 저번주의 정적로딩 방식을 이용할때 코어스크립트가 로딩되지 않는 현상때문에
로더스크립트가 수정이 되었습니다.

일단 postcode.v2.js 파일을 로딩하는 부분에 autoload=false는 꼭 붙혀 주시고
daum.postcode.load()의 실행 부분을 실제 우편번호 서비스를 띄울때 사용해 보시겠어요?

즉 
<script src=postcode.v2.js></sciprt>
<script>
daum.postcode.load(function() {
   new daum.Postcode()...
});
</script>

이게 아니라.

<script src=postcode.v2.js></sciprt>
이 스크립트만 페이지 초기화시 미리 로딩해둔 뒤에

실제 우편번호 창이 필요할때.
daum.postcode.load(function() {
   new daum.Postcode()...
});
함수를 실행시키면, 

브라우저의 초기화 로직과 분리가 되기 때문에, 안정적으로 불러올 수가 있습니다.

한번 이렇게 해보시고, 현재 로더 스크립트 없이 독립적으로 호출 할 수 있도록 준비중이니
잠시만 기다려 주시면 감사하겠습니다.

또는 제가 확인할 수 있는 URL을 전달해 주시면 확인해 보도록 하겠습니다.
반드시 재현이 되는 환경도 명시해 주시면 좋을 것 같아요.

**Comment by jiyoung4** [comment]
감사합니다. 꼼꼼히 알려주신대로 다시 확인하니 제대로 됩니다!!
autoload=false 부분을 postcode.v2.js 파일 로딩 이후에 붙였었네요.
