### ISSUE TITLE
e.Postcode is not a constructor 에러와 함께 사용이 되질 않습니다.

### ISSUE THREAD

**Issue by 91debug** [daumPostcode/QnA#505]
![image](https://user-images.githubusercontent.com/7323747/64306479-d593f680-cfcd-11e9-9373-37152d0edb10.png)

갑자기 해당 에러와 함께 우편번호 사용이 되질 않습니다.

```
const daum = (window as any).daum;
    const obj = this;
    daum.postcode.load(function() {
      new daum.Postcode({
          oncomplete: function(data: any) {
            obj.setState({
              roadAddress: data.address,
              roadAddressError: false,
            });
          }
      }).embed(document.getElementById('address-popup'));
    });
```

**Comment by daumPostcode** [comment]
@91debug 
네~ 안녕하세요~

현재 공지 발송 문제로 인해; 플친 공지를 발송을 못하고 있는데요. 
현재 [공식가이드페이지](http://postcode.map.daum.net/guide)를 확인해 보시면, 신규 로딩 스크립트가 추가되었습니다.

해당 스크립트를 이용하시면 해당 문제가 해결이 되실거라고 생각됩니다.

추가로 기존 스크립트를 이용하시는데 daum.postcode.load라는 함수를 이용하실려면
autoload=false 를 반드시 붙혀주셔야 됩니다.

확인 부탁드립니다. 감사합니다.

**Comment by 91debug** [comment]
감사합니다 해결됐습니다.
