### ISSUE TITLE
기존 자바스크립트API URL 유지예정기간 문의드립니다.

### ISSUE THREAD

**Issue by likesunset** [daumPostcode/QnA#507]
금일 수신받은 메시지에 따르면 기존자바스크립트 API의 URL이 당분간 유지된다고 하셨는데요.  
기존URL종료에 대한 러프한 일정이라도 알고싶습니다.  
최소 3개월에서 6개월 정도 유지된다고 봐야하나요?
확인부탁드립니다.

**Comment by daumPostcode** [comment]
@likesunset 
안녕하세요~

기존 자바스크립트 URL의 경우, 종료를 하게 될시에, 최소 3개월 전에 따로 공지를 드릴 생각입니다.
일단 현재 최소 6개월 ~ 1년 이상은 유지할 예정이구요. 아직 종료 일정이나 이런건 정해진게 없습니다.

배포 방식도 구버전과 신버전이 따로 되는 것도 아니며, 통합관리되기 때문에, 빨리 없앨 이유는 현재로써는 없습니다.

현재 URL이 변경된 이유도, 새로운 기능을 추가하기 위해 또는 배포의 효율성을 위해서 하는 것보다,

기존의 스크립트 로딩 방식이, 시간이 흐름에 따라, 5~6년전에는 발생하지 않았던, 여러가지 잠재적 문제점이 발견되어서 그렇습니다.
지금도 종종 올라오는 "생성자가 없다"는 오류가 바로 그 예인데요. 이러한 문제점을 사전에 막을 수 있는게 금일 패치된 신규URL이기 때문에, 현재 당장 오류가 없더라도 바꿔주시는게 더 좋을 것 같습니다.

감사합니다.
