### ISSUE TITLE
10시 30분경 신규URL 적용 페이지 로딩 지연 오류

### ISSUE THREAD

**Issue by crispfeel** [daumPostcode/QnA#508]
신규 URL적용페이지들이 금일 10시30분경 모두 지연되는 현상이 있었습니다.
우선 구URL로 변경처리하였는데 해당이슈 확인 된것인가 문의드립니다.

**Comment by crispfeel** [comment]
> 신규 URL적용페이지들이 금일 10시30분경 모두 지연되는 현상이 있었습니다.
> 우선 구URL로 변경처리하였는데 해당이ekdma슈 확인 된것인가 문의드립니다.
--->> 다음 사이트 자체가 느리네요....확인

**Comment by jongminkimwilo** [comment]
현재 11:40 다음사이트는 빠른데 문제 해결이 안된거 같은데
해결 되셧나요?
