### ISSUE TITLE
IE에서 우편번호 검색 화면이 정상적으로 나오지 않습니다.

### ISSUE THREAD

**Issue by goborther** [daumPostcode/QnA#509]
IE 에서 우편번호 검색 화면이 정상적으로 나오지 않습니다.

http://postcode.map.daum.net/guide

우편번호 가이드 사이트 에서도 제대로 안나오네요

**Comment by devegoist** [comment]
IE 에서 카카오맵과 우편번호, 다음 홈페이지 포함해서 전반적으로 느리고 오류가 있는것같습니다.
