### ISSUE TITLE
is there a english file? don't understand Korean 

### ISSUE THREAD

**Issue by Rhate** [daumPostcode/QnA#51]
Would be appreciate if you could provide some english documents, or Chinese even better

**Comment by daumPostcode** [comment]
@Rhate 
hi~ Rhate

First of all, i can't speak english well, please understand.

Im sorry. I can't provide English documents; please translate this site and understand look this  [sample code](http://postcode.map.daum.net/guide#sample) 

For the Republic of Korea address system, please refer to [this site](http://www.juso.go.kr/openEngPage.do).

Thanks for your attention to our service.
