### ISSUE TITLE
도로명주소 api 먹통입니다...

### ISSUE THREAD

**Issue by jongminkimwilo** [daumPostcode/QnA#510]
금일 오전부터 갑자기 api를 포함한 페이지 로딩이 느려짐과 동시에
api호출을 하면 아예 불러오지를 못하네요...
현재 정적 js 를 불러오고 있었으며
신규로 등록해주신 js를 사용해 보아도
먹통입니다...

혹시 같은 증상이신분 있으신가

**Comment by bicerin** [comment]
저는 지금 IE에서만 api호출이 안되네요..

**Comment by sukmo88** [comment]
저도 IE에서 주소검색 api 창이 안나오네요

**Comment by jongminkimwilo** [comment]
저는 구버전 정적 js 쓰고있는데 크롬에서 확인하니깐 크롬은 되네요...
근데 저희 유저분들은 다 익스플로러 쓰셔서.... 하오... ㅜㅜㅜㅜㅜㅜㅜ
공짜로 쓰는 서러움이네요 ㅜㅜㅜㅜㅜ

**Comment by Chimin-Chang** [comment]
저희도 구버전 쓰는데 크롬은 되는데 ie에서 안되네요..

**Comment by bicerin** [comment]
IE로 http://postcode.map.daum.net/guide 들어가면 동일하게 주소검색창이 안나오네요...

**Comment by jongminkimwilo** [comment]
개발자분들 아시겟죠??? ㅜㅜㅜ
수정작업 중이시겟죠?? ㅜㅜㅜㅜ
저희는 ie 문서모드도 7로 고정해서 쓰는데 ㅜㅜㅜ
ie11만되는거 아니겟졍... ㅜㅜㅜ

**Comment by jaymz9634** [comment]
저희도 쇼핑몰 운영하는데 안됩니다.. 좀 긴급하게 처리 부탁드려요..

**Comment by hsjang95** [comment]
ie에서만 안됩니다 엣지포함

**Comment by zlot1112** [comment]
IE에서 저도 안되네요.
https://t1.daumcdn.net/postcode/api/core/190904/1567667253555/190904.js
문제있나봐요

**Comment by wantfly32** [comment]
CDN 서버 SSL 인증서 교체 작업이 잘못된거 아닌가요?

**Comment by leesh312** [comment]
[공지](https://github.com/daumPostcode/QnA/issues/511)가 올라와 있습니다. 
참고하세요ㅎㅎ
