### ISSUE TITLE
[장애공지] 현재 외부 CDN서버 장애가 발생하고 있습니다,.

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#511]
안녕하세요~

우편번호 서비스 담당자입니다.
현재 외부 CDN서버 업체의 서버 부하로 인해 우편번호서비스 및, 기타 kakao관련 대부분의 서비스가 동작이 지연되고 있습니다.

현재 외부 네트워크 문제라, 현재 관련 부서에서 확인중에 있습니다.

불편을 드려 죄송합니다 ㅜ.ㅜ

**Comment by daumPostcode** [comment]
현재 외부 CDN에 몰리는 트래픽을 일부 다른 곳으로 분산하려고 준비중이라고 합니다.
이부분 처리되면 다시 댓글로 공유드리도록 하겠습니다.

**Comment by moo-guen-lee** [comment]
안타깝네요
예전에도 발생했던것 같은데..

**Comment by leesh312** [comment]
@moo-guen-lee 
안녕하세요? 혹시 기존에 발생했던 이슈가 똑같이 CDN 관련 이슈였을까요?
그랬다면 해결에 어느정도 시간이 걸렸는지 아시는지요?

미리 감사드립니다.

**Comment by moo-guen-lee** [comment]
예전에 따로 원인 체크는 하지 않았습니다.
그전에 복구해주셨거든요.

특이사항 있으면 정보 제공해드리겠습니다.

**Comment by daumPostcode** [comment]
@moo-guen-lee 네 예~~전에 비슷한 장애가 크게 한번 있었죠;; 그때도 외부 네트워크 관련 문제였던 것으로 기억하는데;; ㅜ.ㅜ 이 부분은 저희서 서비스제공 부서로 믿고 쓰고 있는 것이라;; 장애가 발생하면 대응이 쉽진 않네요 ㅜ.ㅜ

@leesh312 
최근에 발생한 문제는 저희가 개발한 로더스크립트의 코드레벨에서의 잠재적 오류때문에 그러한 것이며, 현재 발생하고 있는 장애는 네트워크 쪽 문제입니다. 저희 소관이 아니라서 현재 관련부서에서 처리 중에 있습니다.

**Comment by moo-guen-lee** [comment]
지금은 동작하고 있는것으로 보이네요

**Comment by daumPostcode** [comment]
현재 장애관련 처리가 완료되었습니다.
다만 유저 컴퓨터에서 해결이 될려면 브라우저의 캐시삭제 및 브라우저 재시작이 필요합니다 ㅜ.ㅜ
이부분 확인 부탁드립니다.
