### ISSUE TITLE
[장애 처리 완료] CDN관련 장애가 처리가 완료되어 공유드립니다.

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#512]
안녕하세요~ 우편번호 서비스 담당자입니다.

정확한 원인의 경우, 추후 담당부서의 장애일지를 토대로 해당 내용을 공유드릴 수 있을 것 같고,
일단 관련부서에서 처리가 완료됬다는 회신을 받았습니다.

다만, 현재 작동중인 IE의 브라우저의 캐시를 모두 삭제하셔야 하며,
브라우저 또한 재시작을 한번 해주셔야 합니다.

현재 장애가 발생한 상태 그대로인 상태에서는 새로고침을 해도 반영이 되지 않기 때문에
꼭 캐시 삭제 및 브라우저 재시작이 필요합니다.

이부분 참고 부탁드리며, 장애로 인해 불편을 드려 죄송합니다.

**Comment by ever0101** [comment]
빠른 대응 감사합니다.
