### ISSUE TITLE
도로명 검색이 되지 않습니다!

### ISSUE THREAD

**Issue by ksbwy** [daumPostcode/QnA#513]
안녕하세요,
행정안전부 사이트에서는 검색이 됩니다. (국가보안시설이라 직접등록 부탁드립니다.)

'경상북도 경산시 경안로87길 46(대정동)  (우)38500'

빠른 등록 부탁드려요..

**Comment by daumPostcode** [comment]
@ksbwy 
네~ 안녕하세요;;

죄송하게도, 현재 내부시스템 및 정책상, 행안부에서 표시되는 보안주소(말씀하신 주소와 같은 주소들)의 경우 저희 시스템에 반영이 어렵습니다.
내부의 데이터는 존재하나 저희 시스템의 구조상 현재 보안주소의 경우엔 표출이 제한되어 있는데요.
일단 현재로써는 수동으로도 반영이 어려운점 양해 부탁드립니다;;

이부분에 대해서는 담당자분들에게 다시한번 말씀드리도록 하겠습니다.

원하는 답변을 드리지 못해 죄송합니다.

모든 주소가 다 나오는 서비스로는 postcodify 또는 행안부 공식 API를 이용하시는게 대안이 될 수 있을 것 같습니다.
감사합니다.

**Comment by ksbwy** [comment]
답변 감사합니다.
다름이 아니라,, 한국환경공단 사이트에서 법정 정기검사 신청을 해야하는데,
거기 등록되어 있는 API가 daum 입니다.. 정확한 주소로 신청해야하는데..저로써도 대안이 없어요..
그리고 위치표시가 되어 있지 않는데도 검색이 되는 곳도 있는데,, (ex 경안로497)
이러한 경우는 어떻게 등록이 되어있는 것인가요..?

**Comment by daumPostcode** [comment]
@ksbwy 
넵. 일반적으로 행안부 사이트에서 검색시 지도표시가 없는 주소를 보안주소라 볼 수 있는 것은 맞습니다.
다만, 실제 보안주소라 하는 것은, 데이터측면에서 볼때, 행안부가 저희에게 "좌표"값을 안주는 데이터를 말합니다.
이 "좌표"값이 없으면, 내부 데이터화를 하기위한 매핑작업을 수행할 수가 없어서,
결과적으로 저희 검색엔진에서는 표출이 불가능하게 되어 버리는 것이거든요;;


이 부분을 처리하기 위해 논의를 한적이 있지만, 개발 리소스상 추가 개발이 어려워서 잠정보류가 됫던 사항입니다.
다만 이게 내부 매핑로직을 떠나서, "주소 자체"로써는 가치를 지니기에, 주소를 제공하는 서비스에서는 필요한 부분이긴 합니다. 해당 부분에 대해서 의견 취합해서 다시 건의해 보도록 하겠습니다.
(이게 제가 개발할 수 있는 부분이 아닌지라;; 시간이 좀 걸리는 점 양해 부탁드립니다)
