### ISSUE TITLE
방화벽 해제를 위해 서비스 IP를 알고 싶습니다

### ISSUE THREAD

**Issue by delete-null** [daumPostcode/QnA#514]
외부와 통신하는 ip를 전부 차단하고
허용된 IP만 오픈하는 정책이라 우편번호 API를 사용을 위해
허용할 IP 목록이나 대역이 필요합니다

아래 URL을 접속하기 위해  IP 목록 문의드립니다
dmaps.daum.net
t1.daumcdn.net

**Comment by daumPostcode** [comment]
@delete-null 
안녕하세요~
IP대역 리스트의 제공이 어렵습니다.

현재 인트라넷에서의 사용의 경우 정식 지원은 불가하며,
사용하실 경우엔, 서비스에서 사용하는 도메인들의 IP를 직접 확인하시여 등록하셔야 합니다.

명쾌한 답변을 드리지 못해 죄송합니다.
