### ISSUE TITLE
후석로 325번지 검색후 나오는 더샵 주소의 경우 인코딩이 깨져있는 현상이 발견됩니다.

### ISSUE THREAD

**Issue by alactory** [daumPostcode/QnA#515]
후석로 325번지 검색후 나오는 더샵 주소의 경우 인코딩이 깨져있는 현상이 발견됩니다.
주소입력시 인코딩이 깨어져 들어가서 최종적으로 DB에 입력시에도 안되는 현상이 발생합니다.
확인 부탁드리겠습니다.

**Comment by daumPostcode** [comment]
@alactory 
안녕하세요~

넵. 버그 제보 감사드립니다.
주소 데이터 담당자 분께 전달하도록 하겠습니다.

다만 추석 연휴라서;; 처리에 시간이 좀 걸릴 것 같습니다.
제보 감사드립니다 ^^

**Comment by daumPostcode** [comment]
@alactory 
안녕하세요~

해당 이슈 어제부터 수정되어 반영되었습니다.
말씀해주신 주소외에 6건이 더 있어 같이 변경되었습니다.

제보 감사합니다.
