### ISSUE TITLE
경기 용인시 처인구 양지면 죽양대로2016번길 56 -> 없는 주소로 나옵니다.

### ISSUE THREAD

**Issue by mpfireball** [daumPostcode/QnA#516]
광산휴게소로 카카오맵에서는 검색이 되는데 api에서는 없는 주소로 나옵니다. 
처리부탁드립니다.

**Comment by daumPostcode** [comment]
@mpfireball 
안녕하세요~

현재 저희 우편번호서비스는 행안부 데이터를 기반으로 합니다.
말씀하신 주소의 경우 행안부 도로명검색 시스템에서 검색이 되지 않습니다.
![image](https://user-images.githubusercontent.com/20675065/65015718-4091e580-d95d-11e9-9730-8b6972303c3a.png)

도로명 주소가 변경되었거나, 사라진 주소 일 수 있기 때문에 해당 부분 확인 부탁드립니다.

추가로 카카오지도의 경우 저희API의 데이터 + 여러 CP사를 통한 장소데이터
를 모두 통합하여 보여주기 때문에, 간혹 저희보다 검색이 많이 되는 것처럼 보이지만,
이는 장소 검색일뿐, 주소 검색은 저희랑 같습니다.
![image](https://user-images.githubusercontent.com/20675065/65015801-7d5ddc80-d95d-11e9-9550-ed8d712d62ad.png)
위 스샷처럼 !주소! 영역을 보시면 말씀하신 주소는 없으며,
장소 영역에 존재합니다. 장소의 경우에는 자동으로 시간이 지나면 업데이트가 되기도 하지만, 고객분들의 제보에 의해서도 반영이 되기 때문에, 만약 해당장소가 변경되었거나 사라졌다면 제보해 주시면 감사하겠습니다.
