### ISSUE TITLE
Kakao 우편번호 서비스를 행정망 사용에 관하여 문의 드립니다.

### ISSUE THREAD

**Issue by seounghoon8218** [daumPostcode/QnA#519]
Kakao 우편번호 서비스를 행정망에서도 사용이 가능한가요??

사용이 가능하다면 따로 설정이 필요한건지 궁금합니다.

**Comment by daumPostcode** [comment]
@seounghoon8218 

안녕하세요~

행정망이란게 어떤 것일까요??
일반적인 회사의 내부 인트라넷망을 말씀하시는 것일까요??

내부 인트라넷이라면 외부로 빠지는 인터넷이 막혀 있을 것 같은데,
이부분은 저희 서비스가 이용하는 도메인의 IP리스트를 네트워크 담당자에게 전달하여 방화벽에서 해제해 주셔야 될거에요. 저희가 IP리스트는 제공해드릴 수 없고, 도메인 리스트만 제공 가능합니다.

추가로 내부망에서 저희 API자체를 이용하시는 것은 아무 문제가 안되나,
API 오류발생시 저희가 접근자체가 불가능하기 때문에 저희가 대응해 드리진 못합니다.
이부분 참고 부탁드립니다.

아래 도메인 리스트 참고부탁드립니다.
HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://stlog1.local.daum.net 
- http://suggest-bar.daum.net
- http://t1.daumcdn.net

HTTPS 환경 
- https://ssl.daumcdn.net
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://spi.maps.daum.net
