### ISSUE TITLE
Daum 우편번호 서비스에서 검색이 안되는 주소 반영요청

### ISSUE THREAD

**Issue by k90jin** [daumPostcode/QnA#52]
행자부 도로명 주소 검색시스템에서는 검색이 되는데 Daum 우편번호 서비스에서 검색안됨.

"경기도 성남시 수정구 위례대로 83"
밀리토피아호텔

확인 후 반영시켜주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@k90jin 
네~ 안녕하세요~

이상하네요;; 왜 안나올까요... 만약에 신규 추가된 주소라면 저희 시스템에 반영이 하루가 걸리긴 하는데, 다른 문제일 수도 있으니 데이터 담당자분께 말씀드리도록 하겠습니다.

불편을 드려 죄송합니다 ;;'

**Comment by daumPostcode** [comment]
@k90jin 
안녕하세요~

데이터 담당자 분께 여쭤본 결과,
현재 해당주소의 좌표값을 행자부에서 내려주지 않고 있습니다.(juso.go.kr에서 검색해보시면 지도 마크가 없습니다)
이런 주소의 경우 여러가지 이유가 있을 수 있지만 보안지역일 가능성이 매우 큽니다.

그래서 저희쪽에서는 이런 주소들의 경우에는 검색에서 제외를 하는데요.
현재 이런 주소가 꽤 많아서, 지도 표출 문제와 더불어, 우편번호 서비스 적용 문제도 논의 중에 있습니다. 
해당 논의가 완료되는데로 서비스에 적용될 것 같지만, 아직 정확한 일정은 확인이 안되네요;;
