### ISSUE TITLE
지번주소에 구 정보가 포함되지 않습니다

### ISSUE THREAD

**Issue by w-kimhyeyoung** [daumPostcode/QnA#520]
'광주 북구 용봉로 77' 로 검색하였을 경우, 지번주소 결과가 모두 '광주 용봉동 ~' 으로만 나옵니다. 
광주에는 용봉동이 북구와 광진구에 각각 있고 해당 도로명 주소는 명확하게 북구 용봉동임에도 구 정보가 없이 나오는 이유가 무엇인가요?
수정해주실수는 없는지 궁금합니다.

**Comment by daumPostcode** [comment]
@w-kimhyeyoung 
안녕하세요~

검색결과를 확인해보니, 검색엔진 오류로 보입니다.
담당 개발팀에 문의 넣도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@w-kimhyeyoung 
안녕하세요~

해당이슈 금일 17시 30분 부로 수정완료되어 공유 드립니다.

제보 감사합니다 ^^
