### ISSUE TITLE
iOS13 이상으로 업데이트 이후 검색결과 화면 스크롤 문제

### ISSUE THREAD

**Issue by JinSun88** [daumPostcode/QnA#521]
주소검색 후 결과 화면에서 스크롤 시
첫 터치에는 스크롤 되지 않고 추가적으로 한번 더 터치하거나
시간 차이를 많이 두고 터치 할 경우에만 스크롤이 가능합니다.
iOS12 대의 운영체제가 설치되 아이폰에서는 정상 작동하고
iOS13 대로 업데이트 한 기기에서만 발생 중입니다.

앱 상에서 여러가지 방법으로 처리해보았으나 해결되지 않고
iOS 13대 기기의 safari에서도 동일하게 발생하여 문의드립니다.

**Comment by daumPostcode** [comment]
@JinSun88 
네~ 안녕하세요~

iOS 13대 버전 단말기를 빌려서 테스트 해보도록 하겠습니다.
현재 제가 확인해 볼수 있는 단말기가 iOS 13.1 아이폰8+ 단말기인데요.

한번 확인해 보도록 하겠습니다. 
테스트의 경우 Safari에서의 구동만 테스트가 가능하며, 인앱 웹뷰의 경우엔 테스트가 불가능한점 양해 부탁드립니다.

시간이 좀 걸릴 수 있으니, 서비스를 개발하시는 중이시라면, "iframe으로 끼워넣기" 예제를 한번 참고해서 내부스크롤이 안생기게 하는 방식으로 적용해보시는 것을 추천드립니다.
(아이폰 내부스크롤(inner scroll)은 버그가 좀 많아서요;;)

**Comment by daumPostcode** [comment]
@JinSun88 
안녕하세요~

소프트웨어 버전 13.1, iphone 8+ 에서 현재 정상적으로 동작을 하는 것으로 보입니다.
테스트한 페이지는
- 공식가이드 페이지의 팝업형, 레이어형, 끼워넣기 예제이며
가이드페이지의 다른 CSS스타일에 영향을 받을 수도 있기 때문에, 빈Html파일에 샘플코드를 복사해서 별도로 테스트를 해봐도 정상적으로 동작을 하고 있습니다.

혹시 만드시고 계신 페이지가 아니라, 공식 가이드 페이지의 샘플로도 테스트 해보실 수 있으실까요?

추가로 제가 접근하여 확인할 수 있는 URL이 있으면 공유해 주시면 감사하겠습니다.
공개하시기 어려울경우 goni.r@kakaocorp.com 으로 보내주셔도 됩니다.

감사합니다.

**Comment by daumPostcode** [comment]
@JinSun88 
안녕하세요~

현재 해당오류 수정되어 실서버에 배포하였습니다.
wrapper아래에 생성되는 div node의 overflow-y 값이 auto로 설정되어 발생한 부분이였는데요.
ios13으로 올라오면서 이에대한 처리가 변경된것 같아 보입니다.

현재 수정완료되었습니다.
daum.postcode.version 을 찍어보시면 191007로 나온다면 최신파일이 받아진 것이니 한번 확인 부탁드립니다.

감사합니다.

**Comment by JinSun88** [comment]
정상동작 확인하였습니다! 빠른 처리 감사드립니다!!!
