### ISSUE TITLE
안드로이드에서 주소 검색 시 텍스트 붙여넣기

### ISSUE THREAD

**Issue by hyoungsD** [daumPostcode/QnA#522]
안드로이드 웹뷰로 사용하고 있습니다.

복사해 둔 텍스트를 주소 검색에서 붙여넣기 후 검색할 때, 유독 안드로이드에서만 붙여넣기가 되지 않는 오류가 있습니다.

텍스트를 한 글자라도 쓴 후에는 붙여넣을 수 있지만, 플레이스홀더 텍스트가 보이는 기본 상태에서는 불가능합니다.
해결방법이 있는지 문의드립니다.

**Comment by daumPostcode** [comment]
@hyoungsD 
네~ 안녕하세요~

음. 제가 쓰고 있는 안드로이드 폰으로 확인을 해보았는데요
- 모델 : 갤럭시 S10 5G
- 소프트웨어 버전 : 안드로이드 9.0
- 테스트앱 : 다음앱

다음앱에서 열리는 브라우저는 웹뷰입니다. 
웹뷰의경우 개발자에 따라 천차만별로 구현이 되는 상황이기 때문에, 정확한 테스트 케이스를 맞추기가 어렵습니다.
일단 말씀하신 부분이 웹뷰이기 때문에 다음앱 웹뷰로 테스트 하였구요, 기본적인 크롬에서는 정상 동작합니다.

- 영상을 찍다보니 용량이 10메가가 넘어가서;; 카카오티비에 올려서 공유드립니다
https://tv.kakao.com/channel/3405875/cliplink/402717112

테스트 환경의 문제 또는 코드레벨에서의 오류일 수도 있습니다.
한번 확인 부탁드립니다.
