### ISSUE TITLE
sido 관련 질문

### ISSUE THREAD

**Issue by rival6821** [daumPostcode/QnA#523]
다음우편검호검색 결과의
sido 시/도
값의 리스트를 얻을 수있는 방법이 있을까요? 부탁드립니다.ㅜㅜ

**Comment by daumPostcode** [comment]
@rival6821 
안녕하세요~

검색결과(페이지당 15개)의 sido 데이터 리스트를 말씀하시는 것일까요?

현재 저희는 온전히 검색결과중에 선택된 1개의 주소에 해당하는 주소의 데이터만 제공을 하고 있습니다.
REST API나 프로세싱용 데이터처럼 페이지 전체의 데이터를 리턴하거나, 추출해주는 API는 없습니다.

해당 기능이 필요한 경우라면, 직접 데이터를 다룰 수 있는
행안부 데이터 API 또는, postcodify를 한번 확인해 보시는게 좋을 것 같아요.

한번 확인 부탁드립니다.
