### ISSUE TITLE
주소 등록 요청드립니다. 

### ISSUE THREAD

**Issue by suseokpark** [daumPostcode/QnA#524]
아래 주소 등록요청드립니다. 

* 서울시 명륜4길 20-3 (서울시 명륜 3가 1-71)
* 경기도 고양시 덕양구 지축동 490-61
> https://place.map.kakao.com/1942657222

**Comment by daumPostcode** [comment]
@suseokpark 
네~ 안녕하세요~

첫번째 주소의 경우엔 주소담당자 분께 전달하도록 하겠습니다.

다만 두번째 주소의 경우엔 행안부 도로명검색 시스템에서도 검색이 되지 않습니다.
![image](https://user-images.githubusercontent.com/20675065/66538364-fb796180-eb5e-11e9-9e18-4c2bebb833f5.png)

행안부 도로명검색시스템의 고객센터를 통해 직접 등록해 주시기 바랍니다. 또는 해당 업체가 등록을 요청해도 됩니다.

카카오지도에서 검색이 되는 것은 주소가 검색되는게 아닌, 장소가 검색이 되어서 그러한 것으로, 해당 장소를 확인해 보셔도 도로명 주소가 없고 지번주소만 있는걸 확인하실 수 있으십니다.
저희 우편번호서비스 API는 "도로명 주소"만 검색이 가능하므로, 도로명주소가 발급되지 않은 지번주소는 나오지 않습니다.

이부분 확인 부탁드립니다.

**Comment by suseokpark** [comment]
빠른 등록 감사합니다. 
두번째 주소는 직접 등록하도록 하겠습니다.
