### ISSUE TITLE
도로명 주소 등록 요청

### ISSUE THREAD

**Issue by jinier** [daumPostcode/QnA#525]
해당지번주소 : 충북 청주시 청원구 우암동 1202-1
사유 : 해당주소로 사업자등록증을 구청에서 받았으나, 도로명 주소가 지정되지 않아 우편번호 등 타기관 등록이 어렵습니다.

**Comment by jinier** [comment]
특성화거리로 2022년까지 청주시에서 허가가 나있습니다

**Comment by daumPostcode** [comment]
바로 위 이슈와 같은 이슈로 해당 이슈는 close 처리합니다.
