### ISSUE TITLE
도로명주소 등록요청

### ISSUE THREAD

**Issue by jinier** [daumPostcode/QnA#526]
해당지번주소 : 충북 청주시 청원구 우암동 1202-1
사유 : 해당주소로 사업자등록증을 구청에서 받았으나, 도로명 주소가 지정되지 않아 우편번호 등 타기관 등록이 어렵습니다.
특성화거리로 2022년까지 청주시에서 허가가 나있는 상황입니다.
#

**Comment by daumPostcode** [comment]
@jinier 
네~ 안녕하세요~

해당 주소는 현재 행안부 도로명주소검색시스템(http://juso.go.kr)에서도 검색이 되지 않습니다.
![image](https://user-images.githubusercontent.com/20675065/66829850-33353e80-ef8f-11e9-9517-d40075e40db2.png)

위 사이트에서 검색이 되지 않는다는 것은 도로명주소가 발급되어 있지 않았다는 것으로, 저희 우편번호서비스의 도로명주소 데이터는 행안부데이터를 토대로 하기 때문에 저희쪽에서도 검색이 되지 않는 것인데요

도로명 주소는 직접 또는 해당 주소의 건물 소유자나 기타 연관있으신 분이 등록하시면 됩니다.

이 방법은
[FAQ 1번](https://github.com/daumPostcode/QnA/blob/master/README.md#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고 부탁드립니다.

감사합니다.
