### ISSUE TITLE
도로명 주소가 없을시 지번도 검색이 되지 않는 케이스에 대한 문의

### ISSUE THREAD

**Issue by doongsilee** [daumPostcode/QnA#529]
도로명 주소가 지정이 되어있는 경우에는 지번주소로 검색해도 결과가 나오지만,
반대의 경우에는 지번주소는 있음에도 결과가 아예 나오질 않는듯 한데요.

이게 설명되어있는 FAQ 1번에 도로명 주소로만 검색이 가능합니다라는 문구의 의미인가요? 이부분이 뭔가 의미가 좀 혼동 되는듯 합니다. 실제로는 도로명주소가 있는 주소의 경우는 지번으로도 검색이 되거든요.

아무튼 지번주소만 있는 경우에도 검색결과가 나오도록 하는 수정은 어려울까요?

**Comment by daumPostcode** [comment]
@doongsilee 
안녕하세요~

해당 FAQ 1번의 문구는 말씀하신 것처럼 혼동의 여지가 있어 수정하도록 하겠습니다.

일단 답변을 드리자면,
현 우편번호서비스의 경우, 행안부의 도로명주소 데이터를 기반으로 하며,
"도로명 주소가 발급된 주소"만 검색이 됩니다.

도로명 주소가 발급이 됬다는 것은, 해당 도로명 주소는 특정 지번주소와 매핑이 되어 있다는 것으로,
저희 검색 엔진 내부에서 이 둘을 모두 검색이 가능해서 그렇습니다.

즉 도로명 주소를 입력하던, 지번 주소를 입력하던, 검색이 되는 주소는 "도로명 주소가 발급된 주소"에 한해서 검색이 이루어 집니다.
이말은 "도로명 주소가 발급되지 않은 주소"는 검색이 되지 않는다는 것을 뜻합니다.
이러한 이유는 "도로명 주소"가 발급이 되어야지만 5자리 기초구역번호(새우편번호)가 발급이 되기 때문입니다.

이부분 참고해 주시기 바랍니다.

그래서 검색이 안될경우 juso.go.kr에서 도로명 주소가 발급이 되어 있는 상태인지 확인하셔서 등록을 별도로 진행하셔야 하며, 행안부 API와 다르게 행안부에서 검색시 지도마커가 표시가 되지 않는 일명 "보안 주소"의 경우엔, 현재 저희 내부에서 매핑할 근거가 없는 관계로 저희 시스템에서는 제외되어 검색이 되는점 참고 부탁드립니다.

**Comment by doongsilee** [comment]
@daumPostcode 

빠른답변 감사드립니다.

설명해주신 내용은 잘 이해 했습니다.
그렇다면 혹시 새우편번호(도로명 주소)가 없는 경우에 구 우편번호(기존 지번주소와) 라도 보여줄수 있도록 기능을 추가한다거나 하는 계획은 혹시 없으실까요? 
카카오맵에서 검색해보면 데이터는 이미 카카오에 있는걸로 보이긴 합니다.
시골이나 도시 외곽쪽에 꽤 높은 확률로 도로명 주소가 없는 경우가 있는듯 합니다.

**Comment by daumPostcode** [comment]
@doongsilee 
안녕하세요~

해당서비스의 취지가 도로명 주소를 쉽게 적응할 수 있는 것에 의미를 두었기 때문에,
기능추가의 기술적 난이도가 있어서라기보다, 정책상 지원해 드리기가 어렵습니다.

특히나 기초구역번호는 현재 신뢰할 수 있는 정보이나, 구우편번호소(6자리)의 경우 신뢰할 수 없는 데이터라서, 해당 정보만 있는 데이터를 외부로 노출시키기엔 좀 부담이 있는 상황입니다.
그리고 도로명주소가 없다는 것은 건물이 없다는 뜻이거나, 해당 건물주나 연관되신 분이 도로명주소 생성 요청을 아직 안하신 것이기 때문에 이는 검색이 되지 않는게 맞다고 생각됩니다.

이에따라 현재 해당 기능에 대한 API의 외부 적용은 어려울 것 같습니다.

추가로 카카오맵과 검색결과가 차이가 나는 것은, 카카오맵은 지번주소,도로명주소,장소에 매핑된 주소 등을 검색하는 통합시스템이며, 저희 서비스는 "도로명 주소"만 검색하는 시스템이라 차이가 발생하는 것이라 생각해주시면 감사할 것 같습니다.

**Comment by doongsilee** [comment]
네 답변 감사드립니다.
