### ISSUE TITLE
iOS 웹뷰관련입니다.

### ISSUE THREAD

**Issue by trilliwon** [daumPostcode/QnA#53]
---

**9. 모바일앱에서도 사용할 수 있나요?**

웹뷰를 이용하여 하이브리드앱 제작 방식으로 사용할 수 있습니다. 단, html,js,css들을 정적으로 넣고 실행하는 경우에는 데이터 전달이 되지 않기 때문에, 페이지를 호출하는 방식으로 사용하셔야 합니다.

---

QnA 9번에서 페이지를 호출하는 방식으로 해야한다고 하셨는데요. 현재 우편번호뷰만 나오는 페이지는 따로 제공하고 있지 않으신가요?

```
http://postcode.map.daum.net
```

위 페이지를 로드하면 잘못된 접근이라도 뜨던데.. ** 페이지를 호출하는 방식으로 **라고 하시는 거면 서버에 웹페이지 만들고 그 웹페이지를 호출해야 하는 건가요?

**Comment by daumPostcode** [comment]
@trilliwon 
네~ 안녕하세요~

네 맞습니다. 서버에 웹페이지 만들고 그 웹페이지를 호출하는 방식입니다. 웹앱을 만들시 프레임워크에 따라 다르겠지만 보통 정적으로 JS파일들을 로딩하는 방식으로 하게 되는데, 저희 우편번호 서비스의 경우 도메인 정보를 필요로 하기 때문에, 도메인 정보가 없으면, 검색 뷰어는 뜰지 몰라도 주소를 선택했을때 주소값을 내려 받을 수 없습니다.

기본적으로 우편번호 서비스 플랫폼은 웹기반이며, 웹앱의 경우에는 이용하시는 개발자분께서 대응하셔야 합니다.

그리고 아마 말씀하신 도메인으로 접속하면, "잘못된 접근"이라고 뜨고 자동으로 가이드 페이지로 이동이 될텐데요. 그 가이드 페이지를 읽어보시면, 저희 API를 어떻게 사용해야 되는지 아실 수 있으실 거에요. 저희는 JS API를 제공하고 있고, 직접적으로 검색 뷰 페이지를 제공하는 것은 아닙니다. JS API를 통해서 뷰어를 띄우는 방식이기 때문에; 가이드 페이지를 한번 읽어보시는 것을 적극 권장합니다.

**Comment by trilliwon** [comment]
답변 감사합니다! 검색 뷰까지 지원하지 않는 이유가 있나요?

**Comment by daumPostcode** [comment]
@trilliwon 
네~

음... 좀 길게 설명을 드릴께요;

검색뷰만 따로 제공하지 않는 것은, 저희 우편번호서비스의 목적과 관련이 있습니다. 

해당 서비스는 도로명주소의 보급으로 인해 각 사이트마다 데이터의 커버리지가 모두 다르고, 검색뷰어의 파편화로 인해 검색이 어렵다는 점에서 착안하여, 주소입력시의 우편번호 검색을 우리가 가진 데이터를 통해 지원해 보자입니다.

추가적으로 우편번호 검색의 경우, 방대한 데이터와 처리에 따른 개발자들의 노고에 비해, 외부 시선이 당연하고 쉽게 생각하는 경향이 있기 때문에, 한번 만들어진 이후 업데이트가 잘 안되는 경향이 많습니다. 특히 도로명 주소의 경우에는 하루에도 몇십에서 몇백건이 업데이트 되는데, 계속 업데이트를 안해주면 주소가 나오지 않거든요. 

위와 같이 서비스적인 목적, 개발자들의 편의성 향상을 위해 만들어진 서비스이며,
무엇보다, 일반 사이트에서 사용되고 있는 우편번호 검색이기 때문에, 검색을 한 후에 사용자가 주소를 선택하면 해당 사이트에서는 그 주소를 받아야 합니다. 여기까지가 기본적인 우편번호 검색 시스템의 동작 시스템이라고 생각하고 기획되고 만들어진 것이기 때문에, 단순하게 뷰어 URL만 제공하는 것은 의미가 없다고 생각했습니다.(외부 사이트에서는 도메인이 달라서 데이터를 건들 수 없기 때문이죠.)

그리고 추가 댓글 질문에서 말씀하신 것과는 뉘앙스가 조금 다른게, JS API를 통한 검색 뷰는 제공을 합니다. 직접 접근할 수 있는 검색 뷰를 제공하지 않는다는 것이죠.

여기서 질문하실 수 있는 내용이 REST API로는 왜 제공을 안하냐고 할 수도 있으시겠지만, 검색 뷰와 REST API는 관리 주체와 관리방식이 전혀 다릅니다. REST API로 할시 발생할 수 있는 이슈가 너무나 많고 불필요한 어뷰징이 매우 많이 발생 할 수 있습니다. 그래서 회사 차원에서 REST API로 제공하는 것들은 데이터 정제 및 안전성이 검증된 것들만 나갈 수 있는 것이며, 도로명 주소의 경우에는 지금도 내부적으로는 계속 바뀌기 때문에 아직까지 REST로 풀 계획은 없습니다.

제가 주저리 주저리 많이 쓰긴 했는데, 이해 안되는 부분이 있으시면 댓글 부탁드려요~

**Comment by trilliwon** [comment]
답변 감사합니다.
