### ISSUE TITLE
주소정정요청(행정자치부 도로명주소에는 정정완료)

### ISSUE THREAD

**Issue by thsu1** [daumPostcode/QnA#530]
천안시 동남구 신촌로8 검색시 나오는 청해용궁횟집이 이전되었는데 도로명주소의 정보에 계속하여 표시가 됩니다.
행정자치부 도로명주소에는 정정요청을 하여 반영이 된 상태인데
다음 우편번호 서비스에는 계속해서 노출이 되고 있습니다. 정정요청 부탁드립니다.

**Comment by daumPostcode** [comment]
@thsu1 
넵~ 제보 감사드립니다~

해당건 주소 담당자 분께 전달하도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@thsu1 
해당건 현 시간부로 수정되어 배포되었습니다.
제보 감사드립니다 ^^
