### ISSUE TITLE
제공해주는 주소값에대한 문의

### ISSUE THREAD

**Issue by bbqds123** [daumPostcode/QnA#531]
다음주소 API를 이용해서 주소를 입력하고 있는데

저희 DB에 주소값이 들어간게 통일성이 없는 문제가 발생했습니다.
ex) 대전시 중구 ~ , 대전광역시 중구 ~
이렇게 어떤값은 광역시가 들어가 있고 어떤값은 광역시가 안들어가있는 상황입니다.

혹시 제공해주는 값이 광역시나 특별시, 특별자치시 등이 있다가 빠진적이 있는지 문의드립니다.

만약 답변하기 어려우시다면,
행정안전부 주소DB에서 가져오기때문에 행정안전부에 문의를 해야하게 맞는지에 대한것도 맞는지 확인부탁드립니다.

**Comment by daumPostcode** [comment]
@bbqds123 
안녕하세요~
저희 시스템은 기본적으로 옵션셋팅을 하지 않는한, 축약형으로 내려가게 됩니다.
다만 "세종특별자치시", "제주특별자치도"의 경우 지자체의 요청에 의해 풀네임으로 들어가게 됩니다.

데이터상 이게 잘못 들어갔다는 것은 현재로썬 찾기가 매우 어렵긴 한데,
세종과 제주가 아닌 다른 지역이 축약형이 풀린 것일까요? 해당 주소가 저장된 시점을 알려주시면 데이터와 엔진 개발자 분께 전달하도록 하겠습니다.

**Comment by bbqds123** [comment]
축약형이 2017년 01월 ~ 2017년 06월 쯤 축약형이 데이터가 아닌 값이 종종 입력되어 있습니다.
확인해주시면 감사하겠습니다.
ex) 서울 -> 서울특별시, 인천 -> 인천광역시

**Comment by bbqds123** [comment]
혹시 이전버전에서는 축약형으로 안나왔었는지도 궁금합니다

**Comment by daumPostcode** [comment]
@bbqds123 
날짜가 상당히 오래되서;; 해당 기간의 서버로그로는 확인이 어려울것 같습니다.
다만 API상 문제가 있으면 이슈가 올라오는데, 해당 축약형 관련해서 이슈를 여기서 검색해 보니

https://github.com/daumPostcode/QnA/issues/107
이러한 글이 있네요. 당시에 JS API의 파라미터 관련 변경패치가 있었는데,
JS API의 http와 https프로토콜의 구성 방식의 차이로 인해서, https의 프록시 서버에서 캐시가 삭제되지 않아서 발생했던 문제였습니다.

해당 이슈는 해당 이슈가 발생했을때 외에는 따로 보고된 적이 없으며, 브라우저 캐시 삭제를 통해 해결이 되었으며, 이후에 이를 원천적으로 해결하기 위해 https용 API의 서버를 변경하였습니다.
그리고 2019년 하반기에는 http와 https를 통합하였고, 새로운 주소로 변경이 되었습니다. (async 로딩 관련 이슈 수정건)
이 주소는 http://postcode.map.daum.net/guide 공식 가이드 페이지에 적혀 있으며
https://github.com/daumPostcode/QnA/issues/506 공지 및 플친으로도 발송이 완료된 상태입니다.

만약에 아직도 spi.maps.daum.net을 아직도 사용하신다면, 위 가이드를 통해 변경해 주시면 감사하겠습니다.

감사합니다.
