### ISSUE TITLE
충북 음성군 음성읍 중앙로 197(세룡아파트) 의 아파트 이름이 잘못 입력되었습니다.

### ISSUE THREAD

**Issue by YoungHeom** [daumPostcode/QnA#532]
세룡아파트가 아니라 세륭아파트입니다. 수정 부탁드립니다.

**Comment by YoungHeom** [comment]
세룡아파트가 아니라 세륭아파트입니다. 수정 부탁드립니다. (question을 어떻게 다는지 몰라서 그냥 글을 씁니다.)

**Comment by daumPostcode** [comment]
@YoungHeom 
안녕하세요~
![image](https://user-images.githubusercontent.com/20675065/68823437-177c9f80-06d7-11ea-9e65-d79f6f5356ab.png)

현재 행안부 도로명주속소검색시스템에서도 세룡아파트라고 되어 있습니다.
저희 우편번호서비스상의 아파트명의 경우엔 제가 따로 주소 담당자분께 문의 드려서 고칠수 있으면 고치도록 하겠습니다.
다만 행안부는 직접 행안부 고객센터에 연락주셔야해요~

감사합니다.

**Comment by daumPostcode** [comment]
@YoungHeom 
안녕하세요~

담당자분께 문의결과,
행안부 도로명검색 시스템 고객센터(https://www.juso.go.kr/help/QABoardList.do)에 문의해서 수정하셔야 될것 같습니다.
행안부 측에서 수정이 완료되면 저희쪽에도 자동 반영이 됩니다.

감사합니다.

**Comment by YoungHeom** [comment]
@daumPostcode 앗 그렇군요.. 알려주셔서 감사합니다!
