### ISSUE TITLE
주소수정 

### ISSUE THREAD

**Issue by sungaejeon** [daumPostcode/QnA#533]
안녕하세요,
카카오비즈니스인증을 받을려고 하는데, 주소문제로 계속 반려가 되고 있습니다.
사업자등록증 주소가 '경기도 고양시 일산동구 중앙로 1275번길 86-23
(장항동, 청원레이크빌 208호,209호,210호)입니다.
중앙로 1275번길 86-23번길을 검색시 86-1로 나옵니다.

86-23인데 왜 86-1로 나오는지..
주소수정해주세요, 이걸로 계속 심사에 떨어지고 있습니다.

**Comment by daumPostcode** [comment]
@sungaejeon 
안녕하세요~

![image](https://user-images.githubusercontent.com/20675065/68912786-8cfe7380-079c-11ea-9e19-82cd930f937b.png)
저희 시스템에서 주소가 나오지 않는 이유는 크게 보면 두가지가 있습니다.
1. 행안부 도로명주소시스템에서 검색이 안될때
-> 도로명 주소 자체가 발급이 안된상황
2. 보안주소일때
-> 현 우편번호서비스 시스템에서는 보안주소의 경우 매핑불가로 서비스가 되지 않으나, 추후 개선하기 위해 현재 작업중입니다.

위 두가지 이슈중. "경기도 고양시 일산동구 중앙로 1275번길 86-23" 이 주소의 경우엔
도로명 주소가 없습니다.

행안부에 검색해 보면 나오지가 않네요. 행안부 도로명주소검색시스템에서 고객센터를 통해 문의를 넣어 보시는게 좋을 것 같습니다.

행안부에 추가가 되면 저희 시스템에는 익일 추가가 됩니다.

그리고 이 모든건 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)에 적혀 있으니 확인 부탁드립니다.
