### ISSUE TITLE
embed방식으로 검색창을 뛰운 후 검색필드에 포커스를 줄 수 있나요?

### ISSUE THREAD

**Issue by leesc81** [daumPostcode/QnA#535]
안녕하세요.
embed방식으로 우편번호 검색창을 뛰워서 사용하고 있습니다.

embed()를 실행해서 나타난 레이어를 살펴보니, 아이프레임에 또 아이프레임에 컨텐츠를 뛰우는 방식이더군요~
그래서 아이프레임내의 #region_name이 input필드길레 찾아서 포커스를 줘봤으나, 다른 도메인에서 뛰운 아이프레임내의 컨텐츠를 조작하는것은 브라우져에서 막아서 포커스를 줄수가 없었습니다.

혹시 인풋필드에 포커스를 줄 수 있는 방법을 제공해주고 있나요?
또한 이걸 적용하려면, 페이지 로드가 완료되었음을 알리는 이벤트도 있어야 할것으로 보입니다.

**Comment by daumPostcode** [comment]
@leesc81 
네~ 안녕하세요~

현재 검색어 입력창에 포커스를 주는 기능(api)은 없습니다.
그리고 현재 우편번호 서비스의 함수나, 콜백등을 보시면 단방향 통신만 가능합니다. (검색팝업 -> API).
그래서 해당 기능의 경우, 동작은 단순하나 내부적으로 고칠 부분이 존재해서 현재로써는 좀 어려울 것 같습니다.

추가적으로,
외부에서 스크립트로는 제어는 불가능한데,
말씀하신 것처럼, 마지막 iframe에 떠있는 창은 저희쪽 도메인에 연결된 페이지입니다.(다른 도메인이 맞습니다)
이중 iframe을 사용한 이유는 IE6~11까지의 postMessage 호환성 이슈때문에 어쩔 수 없이 그런 구조로 된것으로 참고 부탁드립니다.

**Comment by leesc81** [comment]
이 늦은시간에 답변해주시고 감사드립니다^^
팝업이 뜨면서 인풋박스에 포커스를 주면 좋겠는데 현재 적용이 어렵다하시니 아쉽지만 어쩔수없네요..
한가지 추가적인 문의가 있는데 건물명이 현재는 써제스트 검색조건에서 빠져있나요?
예전에 써제스트에서 일부 건물명으로는 검색이 되는데, 안되는 경우가 있다고 문의글을 이곳에 올렸던적이 있었습니다.
예전에 요청드린적이 있는 사항인데

**Comment by daumPostcode** [comment]
@leesc81 
네~ 안녕하세요~

현재 서제스트의 경우 정답셋리스트를 주소정보만을 이용하고 있습니다.
이를 건물도 들어가게 하려면 정답셋 리스트를 변경해야하거나 다른 API를 이용해야 하는데,
이거 바꾸는게 쉽지가 않아서 적용을 못하고 있습니다. 

데이터쪽 담당은 따로 있어서 제가 관여를 할 수가 없는 부분인지라, 바꾸기가 좀 어렵네요.


무엇보다 제가 우편번호서비스만의 단독기능이라면 시간을 내서라도 추가를 할것인데, 외부 팀과의 협업을 통해서 해야되는 것이라서 시간내기가 좀 어렵습니다. 현재 제 상황이 그렇게 여유롭지가 못해서(다른 업무가 좀 많아요;; ㅜ.ㅜ) 밀리는 상황입니다.

죄송하지만 해당 이슈의 경우 현재로써는 적용이 좀 어려운점 양해 부탁드립니다.
