### ISSUE TITLE
주소가 검색되지 않습니다.

### ISSUE THREAD

**Issue by KOOSANGYOON** [daumPostcode/QnA#536]
안녕하세요.
다름이 아니라, 고객 CS가 들어와서 확인하던 중, 주소지가 확인이 되지 않아서 이렇게 문의를 드리게 되었습니다.

아래는 CS 문의 내용입니다.

=====================

문의 내용:
주문을 위해 배송지 입력하려했으나 주소지 미노출로 문의
배송지 : 경상남도 창원시 성산구 공단로 799 / 지번 : 성주동 30
ㄴ 확인시 미노출, 지번 검색시 아예 다른 주소지 노출됨

=====================

해당 주소에서 [공단로 799] 로 검색시에,
경남 통영시 광도면 공단로 798
경남 통영시 광도면 공단로 800
이 검색이 되고, 위의 주소는 검색이 되질 않는데요.
혹시 원인을 알 수 있을까요 ?

**Comment by daumPostcode** [comment]
@KOOSANGYOON 
안녕하세요~

해당 이슈의 경우 
[FAQ 1번 추가사항](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 에 해당되는 내용입니다.

juso.go.kr 행안부 도로명검색시스템에서 공단로 799를 검색해보면 검색 결과에 지도마크가 없는 것이 확인 되실 건데요. 이런 경우 행안부가 저희에게 데이터를 줄때, 보안주소라는 개념으로 몇몇 중요 정보를 빼고 주게 됩니다.
그래서 저희쪽 시스템에서는 이 주소를 매핑할 수가 없어서. 표출이 안되는 것이에요.

다만, 현재 이 이슈의 경우엔 "주소 자체"로써는 가치가 있다고 판단되었고,
현재 내부 데이터 및 검색엔진 개편작업을 진행 중에 있습니다.
이번달에 시작해서 앞으로 몇달 걸릴 것 같긴 하지만, 빠르면 내년 1월쯤에 적용이 되지 않을까 싶어요.
조금만 기다려 주시면 감사하겠습니다.

**Comment by KOOSANGYOON** [comment]
빠른 답변 너무나 감사드립니다.
내년 1월 적용이 되기를 기다리고 있겠습니다 :)
