### ISSUE TITLE
현재 우편번호 안내 페이지 및 API 전체적으로 접속이 안됩니다.

### ISSUE THREAD

**Issue by Kaintino** [daumPostcode/QnA#539]
현재 우편번호 검색 페이지 및 API 전체적으로 접속이 안됩니다.
빠른 확인 부탁 드리겠습니다.

**Comment by daumPostcode** [comment]
@Kaintino 
불편을 드려 죄송합니다.
금일 11시 54분에 조치 완료되었습니다.
