### ISSUE TITLE
크롬에서 튕김 현상

### ISSUE THREAD

**Issue by tnqls1532** [daumPostcode/QnA#54]
오늘 갑자기 크롬에서 튕기는 현상이 발생 확인하였는데 이런 현상에
대해서 해결책을 알수 있을까요? 전부 그런 것은 아닌 것 같고 pc 마다
다른 것 같습니다. ie 에서는 정상적이구요.

**Comment by daumPostcode** [comment]
@tnqls1532 
네~

혹시 이 이슈와 같은 문제가 아닐까 합니다.
[링크 참고](https://github.com/daumPostcode/QnA/issues/45) 
위 링크의 댓글을 보시면 비슷한 이슈가 많은데 크롬 재설치로 해결이 되었습니다.

크롬 이번 버전의 경우, 버그가 상당히 많아요;; 우편번호 서비스는 아니지만 다른 서비스 CSS opacity문제도 이상생기고;;;; 암튼 한번 재설치 부탁드립니다;;
