### ISSUE TITLE
금일 오전 11시 20분경 부터 11시 50분경 까지 서비스 중단의 원인

### ISSUE THREAD

**Issue by lala1104** [daumPostcode/QnA#541]
다음 우편번호 api로 서비스를 하고 있습니다.
금일 오전 11시 20분경 부터 11시 50분경 까지 서비스 중단이 있었습니다.
원인이 무었인지 확인을 요청드립니다.

**Comment by ibin79** [comment]
공지가 올라왔었어요.

https://github.com/daumPostcode/QnA/issues/540#issuecomment-558908376
