### ISSUE TITLE
구글앱스크립트 & 크롬 조합에서 검색칸에 자동 포커스가 안됩니다

### ISSUE THREAD

**Issue by nain311** [daumPostcode/QnA#542]
구글 스크립트에 다음 주소 api를 넣으려고 하는데요..

하기 페이지에서 우편번호 검색하면 나오는 iframe에서 주소검색부분에 포커스가 자동으로 넘어가지 않습니다.

https://script.google.com/macros/s/AKfycbyasUoPKaRjWD09dKBb2qOCH5c9VrpqI7KQN93P/exec

엣지에서는 정상적으로 작동됩니다.

**Comment by daumPostcode** [comment]
@nain311 
안녕하세요~
현재 검색창에 포커스를 주는 것은 내부적으로 로딩 완료시 스크립트를 통해 포커스가 가도록 하고 있긴 하지만,
이용하시는 플랫폼에 따라 제대로 동작을 안할 수 있습니다.

현재 댓글을 달고 있는 시점에서는 별도의 해결책은 없습니다.

해당 부분은 제가 확인을 해보아야 겠지만, 저희 서비스도 iframe을 이용하는데, 현재의 페이지도 iframe으로 둘러 쌓여 있네요, 그리고 엣지에서 동작을 한다면, 크롬에서의 iframe 중첩상황에서의 버그일 확률도 있습니다.
이부분 참고 부탁드립니다.
