### ISSUE TITLE
아이폰 웹뷰에서 주소 스크롤 안되는문제

### ISSUE THREAD

**Issue by kkokkokim14** [daumPostcode/QnA#543]
안녕하세요.

아이폰에서 UIWebView에서  url을 http://postcode.map.daum.net/guide로 띄웠을때

iframe을 이용하여 페이지에 끼워 넣기 를 적용 하였습니다.

그런데 아이폰에서 검색된 결과물의 스크롤이 안되는 문제가 있습니다.

스크롤 되게 하는방법이 없는지 궁금 합니다.

**Comment by daumPostcode** [comment]
@kkokkokim14 
안녕하세요.
웹뷰의 경우 개발자가 어떻게 제어하느냐에 따라 결과물이 많이 달라서 확답은 못드립니다.

우선, 페이지에 끼워넣기의 경우,
버그가 많은 inner scroll대신에, 실제 webview에 뜨는 부모페이지의 본문 크기를 늘려서, 본문의 스크롤을 이용하는 예제입니다.

끼워넣기로 특정 DOM에 넣었으나, 해당 DOM의 크기를 늘리지 않았거나, 또는 본문의 스크롤이 막혀 있는지, 확인 부탁드립니다.

추가로 웹뷰보다 일반 브라우저에서 먼저 테스트해 보셔서 기능이 정상이라면 웹뷰에 넣어보시는게 좋을 것 같습니다.

**Comment by kkokkokim14** [comment]
> @kkokkokim14
> 안녕하세요.
> 웹뷰의 경우 개발자가 어떻게 제어하느냐에 따라 결과물이 많이 달라서 확답은 못드립니다.
> 
> 우선, 페이지에 끼워넣기의 경우,
> 버그가 많은 inner scroll대신에, 실제 webview에 뜨는 부모페이지의 본문 크기를 늘려서, 본문의 스크롤을 이용하는 예제입니다.
> 
> 끼워넣기로 특정 DOM에 넣었으나, 해당 DOM의 크기를 늘리지 않았거나, 또는 본문의 스크롤이 막혀 있는지, 확인 부탁드립니다.
> 
> 추가로 웹뷰보다 일반 브라우저에서 먼저 테스트해 보셔서 기능이 정상이라면 웹뷰에 넣어보시는게 좋을 것 같습니다.
바쁘신 와주에 답변 감사합니다.
현재 ios uiWebView달랑 그거 하나만 화면에 띄운거라서 따로 아이폰에서 설정값을 변경한것은 없습니다. 
말씀하시는건 끼워넣기해서 iframe을 늘려서 스크롤 없게 처리하라는 말씀이신가요?

**Comment by daumPostcode** [comment]
@kkokkokim14 
내부적으로 검색결과의 화면은 항상 늘어나 있습니다.
단지 겉을 감싸고 있는 wrapper의 사이즈가 고정이냐, 가변이냐에 따라서,
레이어형식의 innerscroll이 발생할지,
끼워넣기 형식의 body scroll이 발생할지 결정이 됩니다.

저희 예제를 보시면

onresize : function(size) {
        element_wrap.style.height = size.height+'px';
},

onresize함수라는게 존재하며, 이는 우편번호 서비스의 내부 화면이 업데이트 될때마다 발생합니다.
보시는 것과 같이 콜백함수로 넘겨온 size값을 element_wrap의 height값에 넣어주어, 우편번호 서비스의 검색결과 화면과 wrapper의 height값을 똑같히 맞추고 있습니다.
wrapper의 경우 이용자분이 만드는 Dom node이며, 본문에 속한 node이기 때문에 본문의 height가 그만큼 늘어나게 되는 것이죠.

한번 참고 부탁드립니다.

**Comment by grandciel** [comment]
iPhone6+ / iOS 10.3.3, iOS 12.2 에서도 동일한 상황인듯 보입니다.
사파리로 postcode.map.daum.net 사이트 들어가도 동일하게 스크롤이 안되는 상황이네요..
혹시 해결 방법이 있을련지요..
