### ISSUE TITLE
iOS 13에서 height: auto 이슈 문의

### ISSUE THREAD

**Issue by qbbang** [daumPostcode/QnA#544]
안녕하세요. 담당자님
아이폰에서 iframe을 이용하여 페이지에 끼워 넣기 부분을  
아래와 같이 폴더 쪽은 제거해서 사용 하고 있는데
iOS13에서만 auto가 먹히지 않는거 같아 문의 드립니다.

document.body.scrollHeight를 가져오면 
iOS 13인 경우 155(?)를 
iOS 12이하 인 경우 ViewPort, 해당 디바이스의 높이를 가져옵니다.

[iOS13 미만 버전 이미지 url](https://tva1.sinaimg.cn/large/006tNbRwgy1g9ieed4otcj30hs0vktah.jpg)
[iOs13 버전 이미지 url](https://tva1.sinaimg.cn/large/006tNbRwgy1g9ief6n3rhj30u01szgqo.jpg)

<!DOCTYPE html>
<html>
<head></head>
<body onload="execDaumPostcode()">
<meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>
<div id = "wrap" style = "display:block; margin:5px 0; position:relative; height: auto; overflow:hidden; z-index:1; -webkit-overflow-scrolling:touch;"> 
</div>
<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
  // 우편번호 찾기 찾기 화면을 넣을 element
  var element_wrap = document.getElementById('wrap');
  function execDaumPostcode() {
    // 현재 scroll 위치를 저장해놓는다.
    var currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);
    new daum.Postcode({
      oncomplete: function(data) {
      },
      // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분. iframe을 넣은 element의 높이값을 조정한다.
      onresize : function(size) {
          console.log(size)
          element_wrap.style.height = size.height+'px';
      },
      width : '100%',
      height : '100%'
    }).embed(element_wrap);
    // iframe을 넣은 element를 보이게 한다.
    element_wrap.style.display = 'block';
  }
</script>

**Comment by daumPostcode** [comment]
@qbbang 
안녕하세요~
해당 이슈가 iOS 13에서
저희 가이드 페이지의 "페이지에 끼워넣기" 예제처럼, onresize 콜백으로 size값이 잘못 넘어온다는 말씀이시죠?

테스트 하신 아이폰은 어떤 모델일까요?
그리고 추가적으로 폴더를 제거해서 사용하신다는게 어떤 말씀이신지 잘 모르겠습니다;;

일단 iOS13이 설치된 아이폰을 대여해서 확인해 보도록 할께요.
테스트는 iOS13 + Safari에서 진행됩니다.

확인 되면 말씀드리겠습니다.

**Comment by qbbang** [comment]
테스트 기종은 XS 입니다👍
제가 자바스크립트를 잘 몰라서 폴더 제거라 표현했는데
<body onload="execDaumPostcode()">
를 통해서 function execDaumPostcode() { } 바로 호출 했다는 의미 였습니다!

예제 코드에서 아래 부분을 제거하고
<input type="button" onclick="sample3_execDaumPostcode()" value="우편번호 찾기">
바로 onload를 실행? 했다고 보시면 될거 같습니다!

**Comment by daumPostcode** [comment]
@qbbang 
안녕하세요~
아이폰 XS 13.2.2 버전을 빌려서 Safari에서 테스트 해보았습니다.
이용한 코드는 다음과 같습니다.
https://www.notion.so/iOS-13-height-auto-544-992b7330c0d74fb8846e5a2df9b3b793
(깃허브 이슈페이지의 코드등록부분이 잘 안되서, 별도의 링크로 첨부합니다.)
단순히 페이지 끼워넣기 샘플 예제이며, html은 어떤 스타일 처리도 되어 있지 않습니다.

[20191203_161820(1).mp4.zip](https://github.com/daumPostcode/QnA/files/3915210/20191203_161820.1.mp4.zip)
(이건 해당 소스의 구동 동영상 입니다)

맨처음 이슈에 올려주신 스샷을 다시 확인해보니;
제 개인적인 생각으로는 body의 height가 어떤 스타일 속성에 의해서 작게 유지가 되는것 같기도 합니다.
웹뷰의 경우에도 디버깅이 가능하니 (맥과 연결해서 사파리 개발자 도구로 확인)
웹인스펙터를 통해 디버깅을 해보시는걸 추천드립니다.

일단 Safari 브라우저에서는 별다른 특이점이 안보이네요;;

**Comment by qbbang** [comment]
@daumPostcode 
담당자님 친철한 확인 감사합니다.
스타일 속성 쪽 다시 살펴보도록 하겠습니다!!! 감사합니다 좋은 하루되세요
