### ISSUE TITLE
서비스 운영 기간에 대해서 문의드립니다.

### ISSUE THREAD

**Issue by sangminns** [daumPostcode/QnA#545]
안녕하세요~

현재 재직 중인 회사에서 Daum 우편번호 서비스 사용을 기획하고 있습니다.
 
이에 따라 정해진 서비스 운영 기간이 있는지와 서비스가 중단될 수 있는 여부가 있는지에 대해 급하게 문의 드립니다.

또한, 현재 일부 제공되고 있는 구우편번호는 추후 삭제될 예정이라고 공지를 봤습니다. 정해진 시기가 있다면 시기가 언제쯤인지 부탁드립니다~!

감사합니다.

**Comment by daumPostcode** [comment]
@sangminns 
네~ 안녕하세요~

현재 서비스를 종료할 계획이나, 축소할 계획은 따로 없습니다.
다만, 현 서비스를 최신 환경에 맞게 리팩토링을 하는 작업 또한 예정되어 있지 않습니다.
즉, 현상태 그대로 최대한 버그를 최소화 하면서 유지할 예정이며, 내부 코드가 현재의 플랫폼들과 맞지 않다고 판단이 되면, 리팩토링은 진행할 수 있습니다.
(현 버전은 IE6부터 모던 브라우저 및 모바일 브라우저를 지원합니다)

즉, 예정된 것은 없으며, 저또한 제 생각엔 계속 운영이 되지 않을까 생각이 됩니다. 딱히 접을 만한 이슈는 없거든요.
하지만 앞으로의 5년 10년 후의 경우엔 솔직히 장담을 드릴 수는 없을 것 같습니다;;

이외 API의 코드레벨에서의 유지보수와 별개로
"주소 데이터"의 경우 상시 업데이트를 진행하고 있습니다.
행안부 데이터와 일일 동기화가 진행이 되며, 내년 초쯤엔 저희 서비스의 최대 약점인 "보안주소"가 검색이 안되는 문제도 해결이 될 것이라고 생각됩니다. 
질문 주신 "구우편번호" 6자리의 경우엔, 해당 데이터는 국가에서도 관리가 되지 않습니다.
해당 삭제 시기의 경우에도 내부적으로 작업을 진행 중인데, 내년 초에 삭제가 되지 않을까 싶습니다.

이러한 데이터 관련 이슈는 내부적으로 변경 일정이 픽스가 되면 깃허브 이슈 공지나, 카카오톡 채널을 통해 말씀드리도록 하겠습니다.
