### ISSUE TITLE
현재 간헐적으로 주소검색좌측에 dev로 뜨면서 주소 검색이 되지않는현상.

### ISSUE THREAD

**Issue by arcjeen** [daumPostcode/QnA#546]
현재 간헐적으로 주소검색좌측에 dev로 뜨면서 주소 검색이 되지않는현상이 있는것 같은데
api 설정이 따로 추가된것이 있나요 아니면 내부장애인가요?

![스크린샷 2019-12-05 오전 11 41 16](https://user-images.githubusercontent.com/23724812/70199143-4628eb80-1754-11ea-9301-c4e86b738182.png)

**Comment by daumPostcode** [comment]
@arcjeen 
안녕하세요~

혹시 지금도 계속 발생하고 있을까요?
해당 이슈 서버개발자 분께 전달했고, 현재는 발생안할거라고 하시네요.
혹시 지금도 발생하고 있다면 말씀해 주시기 바랍니다.

불편을 드려 죄송합니다.

**Comment by shoong-k** [comment]
안녕하세요. 
카카오페이에서 여전히 재현되고 있습니다.
재현되는 고객님 기준으로 확인해볼 수 있는 방법이 있을까요? 

CS센터 번호가 있으면 알려주심 고객님께 전달 드릴 수 있도록 하겠습니다.

**Comment by daumPostcode** [comment]
@arcjeen 
해당 이슈는 일시적인 오류였던 것으로 보이며 현재는 처리 되었습니다. 지금도 발생하신다면 캐시삭제를 한번 부탁드립니다.

@shoong-k 
카카오채널 톡으로 알려드린 것처럼 아지트나 고객님께 캐시삭제를 한번 요청드리는 것도 좋을것 같습니다.
