### ISSUE TITLE
Uncaught TypeError : Cannot read property 'action' of null

### ISSUE THREAD

**Issue by wozjcom** [daumPostcode/QnA#547]
안녕하세요? 

가이드 문서에 있는 sample6을 그대로 사용하고 있습니다.
다음과 같은 오류가 계속 발생하는데, 어떻게 조치해야 하는지요?

![image](https://user-images.githubusercontent.com/58539132/70199336-bf284300-1754-11ea-9cf1-62903d808054.png)

**Comment by daumPostcode** [comment]
@wozjcom 
안녕하세요~

해당오류는 우편번호 검색창으로부터 null데이터가 들어와야 발생하는 이벤트인데, 일반적인 상황이라면 발생할 수 없는 이슈입니다.

아마 바로 아래에 올라온 이슈와 관련된 사항같은데 혹시 지금도 발생하고 있을까요?

**Comment by wozjcom** [comment]
우편번호 찾기 버튼을 클릭해서, 레이어 창이 뜰때 발생합니다.
창은 아래와 같이 정상적으로 뜨고, 검색도 잘 됩니다.

이전에는 이런 오류가 없었습니다.

![image](https://user-images.githubusercontent.com/58539132/70210094-281fb300-1775-11ea-85ce-83aa0b1204e7.png)

**Comment by daumPostcode** [comment]
@wozjcom 
네. 그러시군요;;
일단 JS API자체는 금일 배포나 업데이트가 없었으며,
서버의 자바모듈만 변경하였는데.

일단 저희쪽에서는 확인이 안되서, 혹시 제가 접근할 수 있는 URL이 있을까요??
추가로 JS API 스크립트는 어떤걸 쓰실까요??
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js <- 만약 이걸 쓰고 계시지 않다면 이걸로 한번 바꿔보시겠어요??

**Comment by wozjcom** [comment]
chrome이나 opera로 접속시 공식 예제 사이트에서도 같은 에러가 나옵니다.
http://postcode.map.daum.net/guide#sample

opera에서는 초기에만 에러가 나오고, 몇 번 새로 고침하면, 해당 에러가 나오지 않습니다.

ie 로 접속시는 해당 에러가 나오지 않습니다.

제 pc 브라우져 설정 문제인지요?

![image](https://user-images.githubusercontent.com/58539132/70215937-eba68400-1781-11ea-880e-7c0a9c356c10.png)

**Comment by daumPostcode** [comment]
@wozjcom 
네; 일단 wozjcom님 외에는 별도의 동일한 CS가 추가적으로 들어오진 않았습니다.
현재 저희 개발환경이 Mac인지라, Mac Opera, Chrome (둘다 최신버전) 에서 확인해 보았고
Windows 10 (1903) Chrome 75,  IE11.0.160, Edge, Opera (최신) 브라우저로 확인을 해보았는데, 말씀하신 해당 현상이 발생하지 않습니다;;
혹시나 내부망이라 그런가 해서, 핸드폰 테더링으로 외부망으로 변경하여 테스트를 하여도 동일하였습니다.

브라우저 캐시를 삭제해 주시고,
브라우저 자체를 한번 초기화를 해보시는게 어떨까 합니다.

한번 확인 부탁드립니다.

**Comment by wozjcom** [comment]
안녕하세요?

원인을 찾은 것 같습니다. 최근에 제 chrome 에 AdBlock 이란 확장 프로그램을 설치해서 사용하고 있습니다. 해당 프로그램을 삭제하고, 캐시 지운다음에 실행하니, 오류없이 잘 동작합니다. AdBlock 확장 프로그램이 영향을 주는것 같습니다.

AdBlock은 getadblock.com 에서 제공하는것으로 chrome 웹 스토어에서 자주 사용하는 확장 프로그램입니다.

빠른 응답에 감사드립니다.

**Comment by daumPostcode** [comment]
@wozjcom 
아. adblock때문이였군요; adblock이, 우편번호 서비스의 크로스도메인 통신을 막는 것처럼 보이네요;;
다만, 가이드페이지에서도 오류가 나셨는데, 가이드페이지와, 우편번호검색창의 경우 같은 도메인임에도 불구하고 에러가 나는걸 보면, HTML스펙상 이종 도메인끼리의 데이터 통신 방법인 postMessage 자체를 어떻게 제어를 하는 것으로 추측이 됩니다;;

아무튼, 해결책을 찾으셨다니 다행입니다. ^^
