### ISSUE TITLE
embed {q: 값} 을 바로 적용되게 가능한가요 ?

### ISSUE THREAD

**Issue by NohSeungWon** [daumPostcode/QnA#548]
안녕하세요.
동적으로 우편번호 api를 띄우고 있는데 
자주 찾는 주소값은 embed 값을 통해 사용자에게 default로 보여주고 있습니다.

여기서 더 나아가
자주 찾는 주소를 버튼으로 만들고 사용자가 클릭하면 
바로 적용되서 oncomplete를 활용할 수 있는 방법이 있나요 ?

**Comment by daumPostcode** [comment]
@NohSeungWon 
안녕하세요~

아뇨 현재로써는 검색화면까지 검색어를 전달하는 기능은 있으나, 자동으로 선택되게 하는 기능은 없습니다.
해당 기능의 경우 아직까지 추가할 계획은 없습니다.
이점 참고 부탁드립니다.

**Comment by NohSeungWon** [comment]
답변 감사합니다!
