### ISSUE TITLE
주소 검색시, 우편번호가 행정자치부[도로명 주소 검색 시스템] 과 다르게 나오는 현상

### ISSUE THREAD

**Issue by KOOSANGYOON** [daumPostcode/QnA#549]
안녕하세요.
다름이 아니라, 다음 우편번호 서비스에서 검색했을때와, 행정자치부 도로명 주소 검색 시스템에서 검색했을 때에,
우편번호가 다르게 나오는 이슈를 발견해서 이렇게 문의드립니다.
물류센터에서 상품이 출고 되었다가 다시 반송되는 일이 발생하여 해당 이슈 발견하였습니다.

다음 우편번호 서비스에서 [도봉로3나길 2] 검색시에는,
[02728] 서울 성북구 도봉로3나길 2 길음동  <- 와 같이 결과가 나옵니다.

행정자치부 도로명 주소 검색 시스템에서 검색시에는,
[02729] 서울특별시 성북구 도봉로3나길 2(길음동)  <- 와 같이 결과가 나옵니다.

아마 우편번호의 불일치 떄문에 상품이 반송된것이 아닌가 싶습니다.
혹시 이 현상에는 어떤 문제가 있는지 궁금합니다.

**Comment by daumPostcode** [comment]
@KOOSANGYOON 
안녕하세요~

해당 주소정보 이상건에 대해서 주소데이터 담당자분께 바로 전달하도록 하겠습니다.
제보해 주셔서 감사드립니다. 담당자분께 회신이 오면 해당 내용에 대해서 다시 공유 드리도록 하겠습니다.
감사합니다.

**Comment by KOOSANGYOON** [comment]
네, 빠른 답변 감사합니다. 기다리고 있겠습니다 ! :)

**Comment by daumPostcode** [comment]
@KOOSANGYOON 
안녕하세요~

현재 말씀하신 이슈는 처리 완료 되었습니다~

우선 해당 오류가 발생한 이유는, 행안부에서 저희쪽으로 데이터를 넘겨줄때, 변동자료로 들어오지 않아서 업데이트가 안된것인데요. 행안부측에 물어보니 우편번호만 변경되는 경우에는 사람이 직접 수정을 하기 때문에 간혹 오류가 발생할 수 있다고 합니다.

우선 해당 오류가 존재하는 모든 주소 대략 79건을 모두 업데이트 하였으며,

현재 저희가 백단 시스템을 개선하고 있는데, 해당 시스템이 완료가 되면 지금과 같은 오류는 거의 없어질 거라 생각이 됩니다.

불편을드려 죄송하고, 현재는 정상 적용되었으니 확인 부탁드립니다.
감사합니다.

**Comment by KOOSANGYOON** [comment]
빠른 처리 너무 감사드립니다. 현재 정상작동하는것 확인 완료했습니다. 매번 감사합니다 :) 추가 문의사항 있을시에, 질문 드리겠습니다 !
