### ISSUE TITLE
IE10에서 액세스가 거부되었습니다. 오류 (161102.js (1,15739))

### ISSUE THREAD

**Issue by angel3330** [daumPostcode/QnA#55]
ie10으로 호출시 아래 js파일에서 액세스 거부 스크립트 오류가 뜨는데요..
161102.js (1,15739)
파일명을 보니 어제자인데 뭔가 수정된걸까요?
어떻게 해결할 수 있을까요..?

**Comment by daumPostcode** [comment]
@angel3330 
네~ 안녕하세요~
11월 2일에 실서버 배포가 있었지만, 서비스 실행 로직의 변화는 없습니다. (유틸성 함수 추가건입니다.)

현재 저희가 테스트를 해봐도 IE10에서 정상적으로 팝업이 열리는데요. 혹시 저희 우편번호 서비스를 이용하시는 페이지에서 document.domain값을 설정하여 이용하실까요?

document.domain값을 설정을 하면 현재로써는 기술적인 이슈로 대응이 불가능함을 말씀드립니다;;
혹시 다른 이유라면, 저희가 접근할 수 있는 URL이 있으면 알려주시면 확인해 보도록 하겠습니다.
