### ISSUE TITLE
주소 등록 요청 - 전라남도 여수시 관문동 8-7(신주소 : 전남 여수시 관문6길 10)

### ISSUE THREAD

**Issue by minssookim** [daumPostcode/QnA#550]
전라남도 여수시 관문동 8-7(신주소 : 전남 여수시 관문6길 10)

해당 주소 추가 요청 드립니다.

**Comment by daumPostcode** [comment]
@minssookim 
안녕하세요~

<전남 여수시 관문6길 10 으로 검색결과>
![image](https://user-images.githubusercontent.com/20675065/70966124-6ef69c80-20d5-11ea-9e75-2840b4e3f6d5.png)
![image](https://user-images.githubusercontent.com/20675065/70966127-761daa80-20d5-11ea-9412-7d609d56c8c8.png)
- 행안부 도로명검색시스템 및 저희 우편번호시스템 모두 검색이 되고 있습니다.
- 위 도로명 주소에 매핑된 지번주소의 경우 "전남 여수시 관문동 1156"으로 되어 있습니다.
- 만약 위 매핑된 주소가 다르다면 이또한 행안부 도로명검색 시스템의 고객센터를 통해 수정 부탁드립니다.

<전남 여수시 관문동 8-7 로 검색결과>
![image](https://user-images.githubusercontent.com/20675065/70966133-8170d600-20d5-11ea-8269-114fc0c8a8b9.png)
- 행안부 도로명검색 시스템에서 검색이 되지 않습니다.
- 행안부 도로명검색 시스템의 고객센터를 통해 주소 등록해 주시기 바랍니다.
- [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)을 읽어보시면 확인 가능하십니다.


확인 부탁드립니다.

감사합니다.
