### ISSUE TITLE
https 호출 문의드립니다

### ISSUE THREAD

**Issue by soromi** [daumPostcode/QnA#551]
안녕하세요!

<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
다음과 같이 API를 https로 호출하고 있습니다.

디버깅해보니 API에서 추가로 다음 파일들이 함께 로드되구요.
- jquery-1.11.0.js
- service.v2.min.js

문제는 추가로 로드 되는 파일들이 https가 아닌 http로 로드됩니다.
웹뷰로 사용중인데, 안드로이드 9.0부터는 https를 무조건 사용해야해서 에러가 생기네요..
(일단 에러는 안드로이드에서 예외처리 하였습니다.)
혹시 http로 불러오신건 의도하신건걸까요?

**Comment by daumPostcode** [comment]
@soromi 
안녕하세요~

현재 우편번호 서비스의 팝업창 스크립트의 경우,
API스크립트(postcode.v2.js)와 관계없이, 저희 우편번호 서비스를 띄우는 부모페이지의 프로토콜 정보에 영향을 받습니다.

즉 부모페이지가 http로 되어 있다면, http로 띄우고 있고,
https로 되어 있다면 https로 뜨게 됩니다.

해당 내용 한번 확인 부탁드립니다.

**Comment by soromi** [comment]
아하 그렇군요
친절한 답변 감사합니다 :) !
