### ISSUE TITLE
안녕하세요 우편번호 찾기 api 관련 질문이 있습니다

### ISSUE THREAD

**Issue by Leesuw** [daumPostcode/QnA#552]
제가 현재 다음 우편번호 찾기 api를 사용중인데요 현재 시스템에서는 우편번호 검색을 하면 팝업이 열리고 그곳에서
주소를 입력 한뒤 주소를 선택하면 팝업이 종료가 됩니다.

하지만 제가 구현하고 싶은 부분은 주소를 선택 하여도 팝업이 종료 되지 않고 사용자가 상세주소 입력하는 팝업으로 넘어가서 입력 후에 팝업이 종료 되는 시스템을 구현하고 싶은데 혹시 가이드를 알려 주실 수 있을까요?

**Comment by daumPostcode** [comment]
@Leesuw 
네~ 안녕하세요~

말씀하신 기능을 구현하시려면,
실제 팝업을 직접 띄우시는 것부터 시작하셔야 합니다.

팝업을 띄우시고, 그 팝업 안에다가 embed()를 이용하여 저희 우편번호 서비스를 엽니다.
저희 가이드 페이지를 보시면 "iframe으로 페이지 끼워넣기"라는 예제가 있는데 그런형식으로 팝업에 fit하게 띄우신 후에, 거기서 검색어를 입력하고 주소를 선택하면, 저희 서비스를 닫으면서 팝업쪽으로 데이터를 전달합니다.

데이터를 전달을 받았으면, 
1. 그 팝업에서 (페이지 이동없이) 바로 상세 주소를 입력하는 화면을 생성해서 세부정보를 입력받고 "확인" 버튼 같은 버튼을 누르면 실제 부모페이지로 전달되게 하실 수 있습니다.
2. 팝업에서 데이터를 받으면 해당 데이터를 form으로 묶은후에 submit을 세부정보를 입력할 수 있는 페이지로 전달 시킵니다. 그 후에 그 페이지에서 세부주소를 입력받고 확인을 눌러서 부모페이지로 가게 하는 방법도 있을 것 같습니다.
3. 이건 2번 방법과 같은데 location.href를 통해 querystring 방식으로 세부정보를 입력받는 페이지로 데이터를 전달시켜서 하는 방법입니다.

다만 2번과 3번과 같이 팝업내의 페이지가 변경되었을 경우, 부모페이지를 가리키는 opener 객체가 잘 살아 있는지 확실하진 않네요(opener 통해 부모페이지로 데이터를 전달해야 되니까요)

제일 좋은건 1번 방법으로, 미리 세부주소를 입력받는 화면을 만들어 둔다음에 이를 display:none으로 숨겨두고 그 위에 저의 우편번호 서비스를 띄우신 후에 저희 우편번호 서비스의 oncomplete함수가 실행되면 저희 서비스는 꺼질 것이고 이때 세부주소 입력받을 화면을 보이게 한후에, 사용자가 선택한 주소도 해당 입력창에 넣어주고 하면 될것 같습니다.

참고가 되셨길 바랍니다.
