### ISSUE TITLE
vue-daum-postcode 익스 11 버전에서 문법오류

### ISSUE THREAD

**Issue by kwon-junho** [daumPostcode/QnA#553]
안녕하세요~
현재 vue 2.9.6 버전을 사용하고 있습니다.
크롬이나 엣지 버전에서는 정상적으로 로딩하고 있으나 
11버전에서는 문법오류로 불러오지 못하고 있습니다.
확인부탁드립니다.
![vue-daum-postcode](https://user-images.githubusercontent.com/50051969/71252423-52be5e00-2368-11ea-96f7-3bfeeb414a19.png)

**Comment by daumPostcode** [comment]
@kwon-junho 
안녕하세요~

해당 이슈의 경우 해당 Vuew 라이브러리를 제작한 분께 이슈를 알려주심이 더 빠르실 것 같습니다.
제가 해당 라이브러리를 만들진 않아서요;;;

https://github.com/wan2land/vue-daum-postcode

위 깃허브 링크이니 한번 참고 부탁드립니다.

**Comment by kwon-junho** [comment]
아 답변하세요 합니다.
링크 감사합니다.
