### ISSUE TITLE
팝업 시 검색어 전달 할 수 있나요??

### ISSUE THREAD

**Issue by cyc31041** [daumPostcode/QnA#554]
텍스트박스에 검색하려는 검색값 입력 후 버튼 눌러서 팝업 시키려고 하는데
팝업 시 검색값을 넘겨서 팝업 된 창에 검색하는 텍스트박스에 값을 세팅해 줄 수 있나요??

**Comment by daumPostcode** [comment]
@cyc31041 

네 안녕하세요~
open({q : "검색어" })로 가능합니다.
자세한 사항은 
http://postcode.map.daum.net/guide#methods
공식 가이드 페이지 참고 부탁드립니다.

감사합니다.
