### ISSUE TITLE
면에서 읍으로 승격한 주소로 검색 시 결과가 나오지 않고 있습니다.

### ISSUE THREAD

**Issue by outseer** [daumPostcode/QnA#555]
![image](https://user-images.githubusercontent.com/12990803/71965485-1ed9a880-3243-11ea-92c7-e8cc94cade41.png)

해당 주소는 1/1에 면에서 읍으로 승격하였습니다.

승격한 주소로 검색하면 결과가 나오지 않고 있으며 이전 주소로 검색하면 승격한 주소를 결과로 보여주고 있습니다.

juso.go.kr 에서는 승격한 주소로 검색이 되고 있습니다.

**Comment by daumPostcode** [comment]
@outseer 
안녕하세요~

아마 해당 주소의 경우 지자체의 반영일정에 따라 주소 정보는 반영이 되었는데,
검색엔진 관련해서 문제가 있는 것으로 보입니다.
해당 이슈 담당자분께 전달하여 원인파악하여 해결하도록 하겠습니다.

제보해 주셔서 감사합니다.
