### ISSUE TITLE
EUC-KR 페이지에서 호출시 title 인코딩이 깨집니다.

### ISSUE THREAD

**Issue by devybh** [daumPostcode/QnA#556]
EUC-KR 페이지에서 호출시 title 인코딩이 깨집니다.
추가로, IE 에서 팝업차단이 되어있을때 alert 메세지도 깨집니다.

시대 흐름에 맞게 UTF-8 페이지를 구축하는 것이 맞겠으나..
아직 정리하지 못하고 EUC-KR 을 사용하는 서비스가 있습니다..
EUC-KR 을 살

**Comment by daumPostcode** [comment]
@devybh 
안녕하세요~

해당 문제를 수정하려면 저희쪽에서 파일 인코딩을 모두 변경해서 별도 배포를 해야하는데, 이렇게 두벌관리하는 것은 솔직히 좀 어렵습니다. 현재 저희의 개발환경 모두 UTF-8 기반이며, 이 자체를 변경해서 개발하는 것 자체가 좀 어렵기 때문이에요.. 

죄송 해당 이슈의 경우 현재로써는 대응해 드리지 못할 것 같습니다.
원하는 답변을 드리지 못해 죄송합니다.
