### ISSUE TITLE
ios webkit으로 페이지 끼워넣기를 적용하면 해상도가 이상합니다!

### ISSUE THREAD

**Issue by HaeSeongPark** [daumPostcode/QnA#557]
![스크린샷 2020-01-11 오전 8 57 05](https://user-images.githubusercontent.com/24935280/72194294-6c773080-3450-11ea-9344-7f99bbb19ec6.png)

위 사진처럼 너무 작게 나오는데 혹시 화면에 딱 맞게 할 수 있을까요??
참고 url은 아래와 같습니다.
https://mafiahomepage.s3.ap-northeast-2.amazonaws.com/postCode+2.html

테스트 환경 기기 : ios7 / os : 13.2.3

**Comment by daumPostcode** [comment]
@HaeSeongPark 
안녕하세요~

해당이슈는 저희이슈가 아닌점 참고 부탁드립니다.
HTML페이지를 모바일 페이지에 맞게 띄울때 meta태그를 이용하시면 되는데요.
meta태그의 속성중 viewport를 이용해서 설정하는 방법이 있습니다. 이를 구글링을 한번 해보시는걸 추천드립니다.

추가로 해당 페이지를 제가 소스보기를 해보니 body도 없고 head도 없고 doctype도 없는데요, html파일의 기본 구조를 맞춰서 코딩하시는걸 추천드립니다. 해당 페이지처럼 작업을 하시면 브라우저별로 맘대로 해석하게 됩니다.

참고가 되셨으면 좋겠네요.

**Comment by HaeSeongPark** [comment]
아 감사합니다. 덕분에 잘 해결할 수 있었습니다!
