### ISSUE TITLE
새로운 우편번호 업로드

### ISSUE THREAD

**Issue by amber3000** [daumPostcode/QnA#558]
전북 김제시 백구면 유강리 421-21 이라는 주소지가
다음/네이버 검색상에서는 정상적으로 검색이 됩니다.
다만, 카카오 우편번호 검색시에는 해당 주소지가 확인이 되지않고있는데
업로드 가능한가요?

**Comment by daumPostcode** [comment]
@amber3000 
안녕하세요~

해당 주소는 현재 도로명주소가 발급되어 있지 않은 주소입니다.
현재 저희 서비스는 도로명검색시스템으로 도로명주소가 발급된 주소만 검색이 됩니다. 기존 지번만 존재하는 주소는 검색이 되지 않습니다(다음/네이버 검색과 다른 부분입니다)
이부분 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/20675065/72310429-18c14d00-36c5-11ea-95b1-911fcf84970a.png)
(행안부 도로명 검색 시스템 검색결과)

자세한 사항은 : [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)을 참고하시여 진행해 주시기 바랍니다.

행안부에 도로명주소 발급요청을 직접 하셔야 하며(저희가 대행해 드리지 못합니다) 행안부에서 추가가 되면, 저희쪽에도 반영이 됩니다.

감사합니다.
