### ISSUE TITLE
도로명 검색 시 스크롤 오류 발생

### ISSUE THREAD

**Issue by sgkwon4** [daumPostcode/QnA#559]
안녕하세요.

ios 에서 주소 검색창을 열고 도로명 주소 검색을 할 경우 결과값으로 나오는 리스트에서
 스크롤이 되지 않습니다. (ios 하위버전인듯 합니다 12.1.4)
스크롤 없이 전체 화면으로 나오고 하단에 있는 주소를 선택할 수 없습니다.
답변 부탁드립니다. 감사합니다.

![주소창](https://user-images.githubusercontent.com/59909976/72413194-91ea9e00-37b2-11ea-8fd2-063226ad3ebf.png)

**Comment by daumPostcode** [comment]
@sgkwon4 
안녕하세요~

해당 단말기로, 저희 공식가이드 페이지의 레이어로 띄우는 예제에서도 동일하게 발생할까요?

현재 스샷을 보면 embed함수를 이용한 레이어모드를 이용하시는것 같고, 특정 DOM 태그안에 우편번호 서비스가 들어가있는 것 같은 느낌인데요, 
그 DOM태그를 A라고 한다면 A의 스타일에 webkit-overflow-scolling 옵션을 한번 넣어보시는걸 추천드립니다.
현재 저희 가이드 페이지를 보시면 추가가 되어 있는걸 확인하실 수 있습니다.

레이어 모드의 경우엔, 저희 우편번호 API가 스크롤링까지 지원해주지 않습니다. 외부 DOM을 만드는 사람은 저희 API를 이용하는 개발자이고, 그 개발자분께서 외부 DOM보다 세로가 긴 리스트가 들어올때 어떻게 동작하게 할지는 개발자의 몫이죠.

한번 확인 부탁드립니다. 또한 현재 제공해 주신 정보로는 어떻게 구현되어 있는지 한계가 있어서 정확한 답변은 어렵습니다만, 우선 저희 가이드페이지에서 제공하는 레이어로 띄우는 예제를 잘 살펴보시면 좋을 것 같습니다.

**Comment by sgkwon4** [comment]
안녕하세요 ~ 답변 감사합니다. 

일단 추천해주신 webkit-overflow-scolling  옵션은 이미 적용중입니다. 
<div> 안에 옵션 적용해 두었고 지도팝업이 뜰 때 <div> 에 embed 함수로 주소가 들어갑니다. 

그리고 외부 DOM 보다 세로가 긴 리스트가 들어가는게 아니라
선언해놓은 <div> 내에 리스트가 들어가고 있습니다. 
안드로이드 및 ios 13버전 이상일 경우에는 해당 현상이 일어나지 않고 있습니다. 

그리고 말씀주신 가이드 페이지에서 제공하는 예제를 
문제가 있는 ios 7 12~13버전 으로 접속했을 경우에도 캡쳐드린 것 것과 같은 현상이 발생합니다. 

답변부탁드립니다. 
감사합니다.

**Comment by daumPostcode** [comment]
@sgkwon4 
네~ 안녕하세요~

넵. 아이폰7 12.1.4, 12.4.1 버전을 빌려서 테스트 해보도록 하겠습니다.
테스트는 safari에서 진행될 예정이나, 버그가 확인이 되고 처리가 되는데 시간이 좀 걸릴 수 있습니다.

음.. 우선 저희 가이드 페이지의 샘플들은 이렇게 활용할 수 있다 정도로만 확인을 하시면 되는데,
맨처음 글에서 올려주신 스샷을 보니 한 페이지 전체에 저희 검색 화면만 뜨는 것 같더라구요.
부모페이지 위에 레이어 형식으로 띄워야 되는 상황이 아니라면, 개인적인 경험상 아이폰에서 inner scroll이 발생되지 않고 코딩하시는걸 추천드립니다. (아이폰이 inner scroll 관련 버그가 좀 많아서요.)

즉, 스샷처럼 한페이지에 저희 서비스만 뜬다면, onresize 콜백함수를 이용해서, 저희 서비스를 감싸고 있는 dom의 height자체를 늘려서 body scroll로 동작하도록 하시는게 어떠실까 합니다.

일단은 해당 단말기를 빌려서 확인해 보도록 하겠습니다.

**Comment by sgkwon4** [comment]
감사합니다 ~! 테스트 완료 후 알려주시면 감사하겠습니다. 
그리고 혹시 연락할 수 있는 이메일 주소가 따로 있을까요 ??

**Comment by daumPostcode** [comment]
@sgkwon4 
안녕하세요~

금일 15시 30분경, iOS 12.X버전에서 레이어모드 사용시 스크롤이 되지 않던 현상이 수정되어 패치되었습니다.

브라우저의 콘솔창에서 daum.postcode.version을 찍었을시 200117이 나오면 최신버전으로 업데이트가 된 것으로,
아이폰7 iOS 12.1.4, 12.4.1, 13.3 에서 테스트 및 확인하였습니다.

이후 문제가 있으시면 말씀해 주시기 바랍니다.

따로 연락이 가능한 메일은 goni.r@kakaocorp.com 으로 주시면 되세요~
감사합니다.

**Comment by sgkwon4** [comment]
안녕하세요. 
답변 확인하고 테스트 한 결과 문제가 있어 확인요청 드립니다. 

1.	스크롤이 되지 않는 문제 
iPhone SE (11.4.1), iPhone 7 (12.1.4), iPad (12.4.2)
버전에서는 여전히 스크롤이 내려가지 않고 있습니다. 

2.	추가 문제 확인 ( IOS 에서만 확인됩니다 )
맨 위 상단의 검은 바탕의 주소검색 바 가 가려지는 현상이 확인되었습니다. 
( 검은 바탕의 주소 검색 바는 div 태그로 구현되어있습니다. div 태그가 사라짐. )

정상화면과 오류화면에 대한 캡쳐는 연락가능 메일로 전달드렸습니다. (1/23)
확인부탁드립니다. 감사합니다.

**Comment by daumPostcode** [comment]
@sgkwon4 
메일로 회신을 드렸지만, 이슈등록을 해주셔서 추가 답글 드립니다.

1번 이슈의 ipad(아이패드프로 9.7 12.4.1 버전, 아이패드에어 12.4.3)를 대여하여 확인을 해보았는데요.
두 단말의 Safari브라우저에서 embed를 이용한 layer모드의 샘플코드를 별도의 페이지에서 확인했을때 정상적으로 스크롤이 되었으며, 공식가이드페이지의 layer모드 이용하기 샘플을 이용했을 경우에도 정상적으로 스크롤이 되었습니다.

현재 SE 단말과 7단말의 경우 아직 대여를 하지 못해서 테스트를 못해봤습니다만, 7의 경우엔 이전의 버전에서 정상적으로 동작을 하였는데요. 이런 경우엔 해당 뷰를 띄우는 코드를 제공해 주셔야 어느정도 확인이 가능합니다.

다만 직접 개발하시는 경우엔 Safari를 통해 디버깅이 가능하니 이걸로 먼저 체크해 보시는걸 추천드립니다.

추가로 제가 메일로 답변드린 inner-scroll이 동작하도록 하지말고 body-scroll로 동작이 되게 하라는 것은,
iOS 12버전에서 크리티컬한 버그가 존재하기 때문에 그런것으로,
body의 height가 우편번호검색결과의 height보다 작을 경우, inner-scroll을 통해 검색결과를 스크롤하여 맨 아래에 있는 주소를 선택할 경우, 선택이 되지 않고, 검색결과의 최상단으로 이동해버리는 문제가 있습니다.
이는  body의 height를 검색결과의 height와 같거나 크게 만들면 해결이 됩니다. 해당이슈는 현재로써는 처리가 불가능 하기 때문에, inner-scroll말고 최대한 body-scroll를 이용하시는게 더 좋을거라 생각됩니다.


2번 이슈의 경우엔, 저희 우편번호검색화면을 제외한 바깥의 wrapper의 로직의 경우 저희가 처리할 수 없는 부분이기 때문에, 해당이슈의 경우에도 디버깅을 통해 알아보시는것을 추천드립니다.

**Comment by daumPostcode** [comment]
@sgkwon4 
iPhone SE 11.4.1, iPhone 7 12.1.4

테스트 환경 : Safari
- 레이어모드 샘플코드를 이용한 별도 페이지
- 공식 가이드 페이지의 레이어모드

두가지 모두 테스트 해보니 스크롤이 정상적으로 동작하고 있습니다.
한번 확인 부탁드립니다.
