### ISSUE TITLE
다음 api 사용 시 도로명 코드 오류

### ISSUE THREAD

**Issue by kyeongjin** [daumPostcode/QnA#56]
안녕하세요.
다음 api 사용하여 쇼핑몰 운영 중에 있습니다.

그런데 다음 api 사용 중 

아래 주소들의 도로명 코드를 제대로 전달 받지 못하는거 같아 문의 드립니다.

경기 김포시 대곶면 거물대리 272
경기 김포시 대곶면 거물대리 232

이 주소의 도로명 코드가 정확하게 오지 않고 있는데,
확인 부탁 드리며,

또한 다른 주소들도 도로명 코드가 제대로 전달 되지 않는 부분이 있다면
확인 할 수 있다면 확인 해주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@kyeongjin 
네~ 안녕하세요~

도로명코드(roadnameCode)의 경우 도로명주소로 검색할 경우에만 내려갑니다.
검색어 쿼리에 따라 백단에서의 데이터 검색 방법이 달라서 발생하는 문제인데요.

지번형식으로 검색을 하면 메인주소(검색 결과의 첫번째줄)가 지번으로 연관주소(검색결과의 두번째줄)가 도로명으로 나옵니다. 도로명 주소 형식으로 검색을 하게되면 반대로 되구요.

말씀해주신 2개의 주소모두 지번형식으로 되어 있기 때문에 roadnameCode가 내려가지 않는 것으로 확인되며,
도로명 주소(거물대리 272 -> 율마로 193-23)로 검색하면 정상적으로 내려갑니다.

그래서 다른 주소라기 보다, 지번이 메인주소로 잡히면 roadnameCode가 없으며, 도로명 주소가 메인으로 잡혀야 roadnameCode가 있습니다. (메인주소의 값은 데이터의 address변수에 들어가게 됩니다)

해당 데이터에 대한 자세한 설명은 저희 [가이드 페이지의 속성탭의 oncomplete](http://postcode.map.daum.net/guide#attributes)부분에 명시가 되어 있으니 한번 확인 부탁드립니다.

이와 별개로, 지번형식으로 검색을 할경우에도 도로명주소가 연관주소로 나오기 때문에, 해당 도로명 주소에도 roadnameCode를 내릴 수 있는지 내부적으로 검토해 보도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@kyeongjin 
안녕하세요~

기능 건의사항에 대해서 중간 공유 드립니다.
현재 roadname/roadnameCode의 경우 도로명 주소가 메인으로 검색이 될때에만 내려가고 있는데요, 이를 도로명주소가 연관주소(지번 주소가 메인으로 검색시)가 될때에도 내릴 수 있도록 작업중입니다.

조금만 더 기다려 주시면 될것 같아요;

배포는 빠르면 다음주 정도에 가능할 거라 생각됩니다.

감사합니다.

**Comment by daumPostcode** [comment]
@kyeongjin 

안녕하세요~

현재 검색 결과가 지번:도로명 주소의 경우에도 선택한 도로명 주소의 roadname/roadnameCode를 데이터로 내려갈 수 있게 업데이트가 되었습니다.

자세한 사항은 저희 가이드페이지를 참고 부탁드립니다.

오래 기다리게 해서 죄송합니다.

그럼 즐거운 하루 보내세요~
