### ISSUE TITLE
주소 검색이 안됩니다

### ISSUE THREAD

**Issue by hse06179** [daumPostcode/QnA#560]
경기도 이천시 마장면 억만리로 137
이 주소가 검색해도 안나옵니다.
행정안내부 도로명주소 검색사이트에서는 검색하면 잘 뜨는데 말이죠

**Comment by daumPostcode** [comment]
@hse06179 

안녕하세요~
말씀하신 주소는 [FAQ 1번](https://github.com/daumPostcode/QnA/blob/master/README.md#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)의 추가사항 부분에 해당되는 주소입니다.

![image](https://user-images.githubusercontent.com/20675065/72701475-c4b9db00-3b92-11ea-9f23-fd5ab8acd80c.png)

일명 보안주소라고 불리우는 주소로 행안부에서 특정 데이터를 주지 않아 저희시스템에 매핑이 불가능한 주소로,
현재로써는 노출이 불가능합니다.

다만 해당 주소와 같은 보안주소의 경우에도 노출이 될 수 있도록 노력하고 있으니 조금만 더 기다려 주시면 감사하겠습니다.
