### ISSUE TITLE
주소검색이안되요

### ISSUE THREAD

**Issue by kimtaejeong6145** [daumPostcode/QnA#561]
원산2길 3 인데 검색이안되요 
원산동808 도 안되구요

**Comment by daumPostcode** [comment]
@kimtaejeong6145 

안녕하세요~

말씀하신 주소의 경우 현재 "미고시"상태입니다.
행안부 도로명검색시스템에서 검색해 보시면 아실 수 있는데요.
행안부 설명에 의하면 "고시"이후 법적효력이 발생하며 고시되기까지 5일 이상 소요가 될 수 있다고 합니다.
"미고시"주소의 경우 행안부 사이트에서만 검색이 되는 주소이며, 추후 확정"고시"가 되면 저희 시스템에 등록이 됩니다.

![image](https://user-images.githubusercontent.com/20675065/72869247-eef0d180-3d27-11ea-86d5-a08446bfbe92.png)

확인 부탁드립니다. 감사합니다.

**Comment by kimtaejeong6145** [comment]
고시되었는데 안뜨네요!

**Comment by daumPostcode** [comment]
@kimtaejeong6145 
안녕하세요~
5일전에 질문을 남기셨는데;; 지금 봤네요;;
일단 저흰 행안부의 데이터를 이용하고 있는 것은 맞으나, 그 동기화 시점이 행안부와 같지 않습니다.
행안부에서 도로명주소가 수정됬거나, 미고시->고시로 넘어가더라도 저희에게 실시간으로 데이터를 주는게 아니라
특정 시간대에 한꺼번에 주게 됩니다.

그렇기 때문에 빨라도 행안부가 업데이트된 시점 이후 +1일이 걸리게 됩니다.
이부분 참고부탁드리기 바랍니다.
