### ISSUE TITLE
안드로이드 9.0 webview 주소 api 문의 드립니다.

### ISSUE THREAD

**Issue by YouJinSeon** [daumPostcode/QnA#563]
안녕하세요 문의드릴 것이 있어 글 남깁니다.

안드로이드 9.0에서 webview로 다음 주소 api 호출 시 아래 사진과 같이 문제가 발생하고 있어 어떠한 조치를 취해도 해결하지 못하여 이유가 어떤 것인지 궁금합니다.

![KakaoTalk_20200128_100510803](https://user-images.githubusercontent.com/60372820/73228440-ed0c8f80-41b9-11ea-8d5c-fe15b3aab92d.jpg)

**Comment by daumPostcode** [comment]
@YouJinSeon 
안녕하세요~

올려주신 화면을 볼땐, CSS가 로딩이 안되는 것으로 보입니다.
직접 해당 앱을 개발하신다면, 웹뷰의 경우에도 디버깅이 가능하기 때문에, 디버깅을 한번 해보시는걸 추천드립니다.
CSS(스타일시트)가 왜 로딩되지 않았는지는 저는 알 수 없기 때문에, 디버깅을 통해서 알아보시는게 좋을 것 같습니다.

감사합니다.
