### ISSUE TITLE
도로명 검색 박스 한글깨짐

### ISSUE THREAD

**Issue by landboy75** [daumPostcode/QnA#564]
안녕하세요. 현재 주소 검색에 문제가 있어 글을 남깁니다.

주소 검색시 도로명 검색 박스 있을 경우 여기서 하나의 도로명을 선택하여 검색한 후..
결과가 출력된 화면에서 다시 도로명 검색 박스를 펼칠때...
도로명 목록의 한글이 모두 ?로 깨져서 나오고 있습니다.

현재 우편번호 서비스 사용 가이드 페이지에서도 동일한 증상이 발생하고 있습니다.

확인 바랍니다.

![우편번호](https://user-images.githubusercontent.com/60426063/73346385-1f58e280-42c9-11ea-9ec2-1ea36de21e6f.jpg)

**Comment by daumPostcode** [comment]
@landboy75 
네~ 안녕하세요~

버그가 있었군요... 우선 불편을 드려 죄송합니다.
해당 현상 서버 개발자분께 전달하여 빠른 시일내에 수정조치 하도록 하겠습니다.

제보 감사합니다.

**Comment by daumPostcode** [comment]
@landboy75 
안녕하세요~

금일 오후 두시경에, 해당 현상 수정하여 배포되었습니다.
제보해 주셔서 감사드립니다.

즐거운 하루 되세요~
