### ISSUE TITLE
주소 등록 요청 드려요 - 구:  경기도 이천시 마장면 회억리 산46 / 신: 경기도 이천시 마장면 억만리로 137

### ISSUE THREAD

**Issue by minssookim** [daumPostcode/QnA#565]
구주소 :  경기도 이천시 마장면 회억리 산46 
신주소 :  경기도 이천시 마장면 억만리로 137

**Comment by daumPostcode** [comment]
@minssookim 

안녕하세요~

[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)

참고 부탁드립니다.

해당 주소는 현재로써는 제공해 드릴 수가 없으며, 추후 개선사항에 포함되어 있습니다.
빠르면 상반기 정도에 보여드릴 수 있을 것 같습니다.

감사합니다.
