### ISSUE TITLE
팝업창 제목, 한글 깨짐

### ISSUE THREAD

**Issue by seobangnim** [daumPostcode/QnA#566]
![image](https://user-images.githubusercontent.com/56711939/73908721-eaaee180-48ed-11ea-9005-8877dd8e7da8.png)

팝업창의 타이틀 부분의 한글이 깨집니다.
euc-kr 에서 서비스하고 있으며, 마우스 오른쪽 눌러 인코딩을 한국어로 변경시 아래와 같이 더 많이 깨지는 현상이 발생합니다.

![image](https://user-images.githubusercontent.com/56711939/73908695-d8cd3e80-48ed-11ea-95be-fa0423d31d5e.png)

**Comment by daumPostcode** [comment]
@seobangnim 
안녕하세요~

저희 서비스와 케릭터셋이 맞지 않아서 그런것 같은데요;;
우편번호 서비스는 UTF-8 기반입니다.
일단 결론부터 말씀드리면 현재 euc-kr 기반을 지원해 드리긴 어려울 것 같습니다.

도움을 드리지 못해 죄송합니다.

대안 서비스가 필요하시다면,
행안부의 도로명검색 시스템 API나
postcodify를 이용해 보시는게 어떠실까 합니다.

감사합니다.
