### ISSUE TITLE
주소 등록 요청드립니다.

### ISSUE THREAD

**Issue by minssookim** [daumPostcode/QnA#567]
신주소 ) 경기도 파주시 광탄면 보광로962 , 행복드림아파트
구주소 ) 경기도 파주시 광탄면 마장리406 , 행복드림아파트

**Comment by daumPostcode** [comment]
@minssookim 
안녕하세요

해당건은 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고부탁드립니다.

해당건은 현재로써는 해결이 불가능하며,
추후 올해 1분기 안에 엔진개편을 통해 지원가능하도록 개편중입니다.
해당 내용은 실 적용이 되면 공지해 드리도록 하겠습니다. 

감사합니다.
