### ISSUE TITLE
android webview 포커스 질문입니다.

### ISSUE THREAD

**Issue by babo3yong2** [daumPostcode/QnA#568]
android webview에서 embed() 방식으로 구현하고 있습니다.
호출이 완료 된 후 focus가 검색창으로 이동하지만
키보드가 올라오지 않습니다.
키보드가 올라오게하고 싶어서 임의로 포커스를 이동해도 
해결하지 못하고있습니다..

혹시 방법이 있을까요?

**Comment by daumPostcode** [comment]
@reedfim 
안녕하세요~

해당현상에 대해서 현재 확실하게 해결할 수 있는 방법은 잘 모르겠습니다.;;;

아이폰의 경우엔 강제로 코드레벨에서 키보드를 올라오게 할려고 해도, 유저의 액션이 없는 상태에서는 동작을 하지 않았습니다.
안드로이드의 경우에도 같은 현상인지는 확실하지 않긴 합니다.
단순히 iframe내에 존재하는 input태그에 대해서는 반응을 안하는 것일 수도 있습니다.

현재 저희 우편번호서비스의 경우 내부의 검색화면을 유저가 컨트롤하기 어렵습니다. 단순하게 색상 바꾸는것 외에는 거의 없다고 보셔도 되고, 검색화면의 도메인이 이용하시는 도메인과 다르기때문에 스크립트로 제어도 안됩니다.
즉, 검색화면의 커스터마이징이 필요하신 경우엔
행안부에서 제공하는 API 또는 Postcodify도 한번 참고해 보시면 좋을 것 같습니다.

도움을 드리지 못해 죄송합니다.
