### ISSUE TITLE
검색이 안되는 주소 반영 요청

### ISSUE THREAD

**Issue by JaeBeomLee** [daumPostcode/QnA#57]
정자역에 있는 엠코헤리츠는 나오는데 미금역에 있는 엠코헤리츠는 검색이 안됩니다.

미금엠코헤리츠, 금곡동 엠코헤리츠 -> 경기도 성남시 분당구 성남대로 151

검색되도록 요청 드립니다.

P.S. 정자역 엠코헤리츠보다 미금역 엠코헤리츠가 더 오래됫습니다..

**Comment by daumPostcode** [comment]
@JaeBeomLee 
안녕하세요~

우선 저희 데이터는 행정자치부 도로명 주소 데이터를 기반으로 하고 있으며, 주소의 오탈자, 매핑오류, 검색엔진 등의 버그를 제외하고 주소데이터 자체는 행자부에 건의 해주셔야 합니다.
이는 이 깃허브의 README.md 파일을 보시면 1번 사항에 기술해 놓았으니 확인 부탁드려요 [FAQ 1번 참고](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)

"경기도 성남시 분당구 성남대로 151" 주소의 경우 행자부(http://juso.go.kr)에서도 건물이 등록이 안되어 있는 것 같은데요. FAQ1번을 참고하시어 건물 등록을 해주시기 바랍니다. 

행자부 사이트에 반영이 되면 저희는 익일 시스템에 반영됩니다.

감사합니다.
