### ISSUE TITLE
특정 기종에서만 우편검색창이 미노출되는 현상이 있습니다.

### ISSUE THREAD

**Issue by cshtoyou** [daumPostcode/QnA#571]
상품의 주문서 작성 페이지에서 주소 입력을 위해 우편번호 검색을 필수로 하고 있습니다.
이 때 다른어플은 정상 구동되나 '공구마켓' 어플 구동시에만 주소입력 화면이 빈화면으로 노출되지 않는 현상 발생함.

- Mobile Device : 삼성 갤럭시 S9
- Mobile App : Android 공구마켓

공구마켓 삭제후 재설치로 최신버전 사용
LTE / 와이파이 모두 사용시 동일한 현상 발생 중

다른 디바이스에서는 정상인데 이럴때 어떤 케이스가 있는지 더 확인해봐야 할까요?

CS 인입건이라 별도 로그는 확인되지 않은 상태 입니다.

**Comment by daumPostcode** [comment]
@cshtoyou 
안녕하세요~

혹시 그 모바일앱에서 저희 서비스를 띄우실때 어떤것을 이용하시나요?
open을 이용한 팝업인지, embed를 이용한 레이어인지가 궁금합니다.

현재 웹뷰에서는 웹뷰의 구현스펙에 따라 open함수로 호출시 제대로 뜨지 않을 수 있습니다.
해당 앱에서 띄우는 페이지를 일반 사파리나, 크롬 브라우저에서도 동작하지 않는다면 저희가 확인이 가능하나,
웹뷰의 경우엔 저희가 확인할 수 있는 방법(디버깅)이 없기 때문에 별도로 처리해 드리긴 어렵습니다.

우선 open인지 embed인지 말씀해 주시면 좋을것 같고,
open을 사용하신다면 embed를 이용해서 이용해보시는걸 추천드립니다.

**Comment by cshtoyou** [comment]
스크린샷 올립니다

![image_20200220_17 15 23](https://user-images.githubusercontent.com/61269798/74925545-b839d400-5417-11ea-919e-58389320c76d.png)

**Comment by daumPostcode** [comment]
@cshtoyou 
에러메세지를 확인해 주시면 좋을 것 같습니다.
만약 직접 만드신 앱이라면, 에러메세지 확인이 가능하실거에요.
추가로 해당 페이지의 userAgent를 알려주셔도 좋을 것 같습니다.

**Comment by cshtoyou** [comment]
이슈 종료합니다. 특정 기기에서만 발생 케이스 원인 파악 안됨
