### ISSUE TITLE
지역코드가 다르게 나오는것 같습니다.

### ISSUE THREAD

**Issue by LustigerKerl** [daumPostcode/QnA#574]

**Comment by LustigerKerl** [comment]
sigunguCode 가 K-stat에 등록된 서울의 코드와 다르게 나옵니다.

**Comment by daumPostcode** [comment]
@LustigerKerl 
네~ 안녕하세요~

이번 검색엔진 개편하면서 발생한 이슈로 보입니다.
현재 엔진 담당자 분께서 확인하셨고 수정작업 진행중입니다.

완료가 되면 공유해 드리도록 하겠습니다.

불편을 드려 죄송합니다. ㅜ.ㅜ

**Comment by LustigerKerl** [comment]
혹시 sigunguCode는 행정동 코드인가요 법정동 코드인가요?

**Comment by daumPostcode** [comment]
@LustigerKerl 
안녕하세요~ 금일 18시에 해당 이슈 처리되어 배포되었다고 합니다.
추가로 현재 저희 서비스가 제공하는 주소는 모두 법정동 주소이며,
sigunguCode의 경우 법정동코드의 앞 5자리라고 보시면 됩니다.

감사합니다.
