### ISSUE TITLE
문의드립니다 (Issue) - roadname_code 관련

### ISSUE THREAD

**Issue by johnbaek85** [daumPostcode/QnA#579]
안녕하세요 

업데이트 후에 주소 검색할 때 불러오는 data 중에 'roadname_code' 값이 간혹 7자리가 아닌 끝 두 자리값만 불러와지는 오류가 생긴 것 같습니다. 저장된 데이터들 중 3월 3일 이후 주소가 업데이트 된 데이터 중의 일부만 roadName_code 가 두 자리수입니다.  (현재 계속 발생 중)

(원래는 7자리수, 다시 업데이트 하면 정상적으로 7자리, 모든 경우에 그렇지 않고, 1~2% 정도의 확률로 발생하고 있네요...)

데이터 오류가 처음 발생한 시각이 03 / 03 / AM 11:05분경인것으로 보아 엔진이 배포된 이후 발생하는 문제점인 것 같습니다.

**Comment by johnbaek85** [comment]
도로명 주소로 검색했을 때 바인드되는 roadname_code는 이상이 없는데요,
지번 주소로 검색해서 도로명 주소를 선택할 시 roadname_code 값이 두 자리인 것으로 확인됩니다. 
![roadname_code error](https://user-images.githubusercontent.com/50669754/76187240-310e9d80-6218-11ea-9bf6-3d7bae297e2d.png)

**Comment by daumPostcode** [comment]
@johnbaek85 
안녕하세요~
답변이 늦어서 죄송합니다.

해당 내용 엔진개발자 분께 전달하여 확인조치 하도록 하겠습니다.
제보 감사드립니다!

**Comment by daumPostcode** [comment]
@johnbaek85 
해당 이슈의 경우 확인해보니
도로명-지번 관계(메인주소가 도로명, 연관주소가 지번)일때는 발생하지 않고
지번-도로명(메인주소가 지번, 연관주소가 도로명 > 현재 스크린샷)일때 발생하는 것으로 확인이 됩니다.

(검색 쿼리에 따라 이 순서는 변경될 수 있습니다)
아무튼, 해당 원인을 찾았고, 현재 엔진개발자분께서 수정작업에 들어갔으며, 수정이 되면 댓글로 답변드리도록 하겠습니다. 
제보 감사드립니다 ^^

**Comment by johnbaek85** [comment]
넵 감사합니다,
연락 기다리고 있겠습니다!! :)

**Comment by daumPostcode** [comment]
@johnbaek85 
안녕하세요~
어제 밤 10시에 해당 오류 수정되어 장상 배포 되었습니다.
한번 확인 부탁드립니다 ^^

감사합니다~

**Comment by johnbaek85** [comment]
확인했습니다. 
지번주소로 검색시에도 도로명 주소 코드 이상 없네요 
빠른 조치 감사합니다 
좋은 하루 되세요 ;)
