### ISSUE TITLE
지번 주소 검색 시 도로명 코드가 없는 경우

### ISSUE THREAD

**Issue by kyeongjin** [daumPostcode/QnA#58]
안녕하세요.
다음 api를 11월 부터 사용하고 쇼핑몰 운영 중에 있습니다.

쇼핑 몰 퀵 배송을 사용하여 
도로명 코드가 꼭 필요하지만 지번 주소로 검색 시 1:N 매칭이 되는 경우 도로명 코드가 없는 경우가
너무 많이 발생하여, 쇼핑몰 운영의 차질이 있어 문의 드립니다.

지번 주소로 검색 할 시에도 정확하지 않는 도로명 코드라도 넘겨 주는 방법이 없으신가요?
그럼 확인 부탁 드리겠습니다.

**Comment by daumPostcode** [comment]
@kyeongjin 
안녕하세요~

네; 현재 지번으로 검색을 했을시에는 roadnameCode가 내려가지 않습니다(1:1이든 1:N이든 모두 포함)
이 부분에 대해서는 현재 내부에서 이슈제기가 된 상태이나, 데이터 맵핑 작업 등이 필요하여 현재 개발 논의 중에 있습니다.

정확한 일정은 말씀드리기 어려운데요;; 빨리 논의해 보도록 하겠습니다;; 불편을 드려 죄송합니다 ㅜ.ㅜ

**Comment by daumPostcode** [comment]
@kyeongjin 
안녕하세요~

기능 건의사항에 대해서 중간 공유 드립니다.
현재 roadname/roadnameCode의 경우 도로명 주소가 메인으로 검색이 될때에만 내려가고 있는데요, 이를 도로명주소가 연관주소(지번 주소가 메인으로 검색시)가 될때에도 내릴 수 있도록 작업중입니다.

조금만 더 기다려 주시면 될것 같아요;

배포는 빠르면 다음주 정도에 가능할 거라 생각됩니다.

감사합니다.

<아래 CS와 같은 분이시군요 ㅎㅎㅎ;;>

**Comment by kyeongjin** [comment]
네, 답변 주신 사항 확인 하였습니다.
배포가 되었을 시 확인 할 수 있도록 다시 한번 알려주시면 감사하겠습니다.

친절한 답변 감사드리며, 새해복 많이 받으십시오.

**Comment by daumPostcode** [comment]
@kyeongjin 

안녕하세요~

방금 이전에 쓰신 문의 글에 댓글 드렸습니다..

현재 기능추가된 버전이 업데이트 되었으며, 자세한 사항은 가이드 페이지 참고 부탁드려요~~

감사합니다
