### ISSUE TITLE
문의사항

### ISSUE THREAD

**Issue by dhlife09** [daumPostcode/QnA#581]
안녕하세요~ 우편번호 api 덕분에 사이트에 잘 적용하여 사용중입니다.

다름이 아니라 도로명주소와 지번 이렇게 두 가지가 노출되는데요, 지번을 숨기고 도로명주소만 나타낼 수 있을까요?

**Comment by daumPostcode** [comment]
@dhlife09 
안녕하세요~
아뇨 현재 해당 기능은 구현되어 있지 않습니다.
저희 시스템은 지번 및 도로명이 입력되는 쿼리에 따라 순서가 변경이 되기 때문에 해당 기능을 추가하기는 어려울것 같습니다.
감사합니다.

**Comment by dhlife09** [comment]
답변 감사합니다~ 잘 사용하겠습니다. ^^
