### ISSUE TITLE
문의드립니다. 

### ISSUE THREAD

**Issue by Trycodingman** [daumPostcode/QnA#588]
.

**Comment by daumPostcode** [comment]
@Trycodingman 
안녕하세요~
제가 웹뷰나 native 코드는 알지 못해서; 올려주신 코드를 모두 이해하진 못하지만;;
일단 저희 서비스는 우편번호API가 실행되는 페이지가 http로 시작되는 도메인이 아닌 경우에는 통신을 하지 못합니다.

이는 [FAQ9번, 10번](https://github.com/daumPostcode/QnA#9-%EB%AA%A8%EB%B0%94%EC%9D%BC%EC%95%B1%EC%97%90%EC%84%9C%EB%8F%84-%EC%82%AC%EC%9A%A9%ED%95%A0-%EC%88%98-%EC%9E%88%EB%82%98%EC%9A%94)을 참고해 보시면 좋을 것 같습니다.
한번 확인 부탁드립니다.
