### ISSUE TITLE
Autofocus를 비활성화하고 싶습니다.

### ISSUE THREAD

**Issue by U-lis** [daumPostcode/QnA#589]
안녕하세요 먼저 무료로 좋은 기능 잘 사용하고 있습니다. 개발과 지속적인 지원에 감사드립니다.

현재 page 안에 주소검색창을 embed해서 사용하기 위한 작업을 하고 있는데 동적으로 검색기를 불러 렌더링하면 검색바에 자동으로 focus가 가서 페이지가 강제로 해당 위치로 스크롤되는 현상이 있습니다.

공식 지원 라이브러리는 아니지만 React 에서 편하게 쓸 수 있게 porting되어 있는 [react-daum-postcode](https://github.com/bernard-kms/react-daum-postcode) 를 쓰고 있습니다. 여기에도, [공식 문서](http://postcode.map.daum.net/guide#attributes) 에도 autofocus를 처리하는 부분은 보이지 않아서 이에 대해 어떻게 처리할 수 있을 지 문의드립니다. 

정작 [문서 최상단](http://postcode.map.daum.net/guide) 에 있는 검색창에는 autofocus가 가지 않는 것 같은데, 방법이 있으면 알려주시면 큰 도움이 될 것 같습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@U-lis 
안녕하세요~

저희 우편번호 서비스가 열릴때, 실제 우편번호검색화면의 input박스에는 focus가 가지 않으나, 
저희 서비스에 focus가 가서 스크롤이 이동된다는 말씀이시지요?

우선 현재 PC플랫폼에서 실행하는 경우에는 저희 검색페이지의 특정 input박스에 focus()를 주고 있긴 합니다.
이는 키보드로 이동시 저희 서비스를 쉽게 찾기 위한 접근성 측면에서 적용된 기능입니다.

다만 말씀하신 것처럼 부작용도 좀 있기 때문에, 해당 기능을 on/off 시킬 수 있도록 적용해 보도록 하겠습니다.

추가로 실제 검색어가 입력되는 input박스의 경우엔 PC버전에서만 포커스가 이동되며, 모바일에서는 보안제약 및 가상키보드 이슈로 제대로 동작하지 않는점 참고 바랍니다.

해당 이슈의 경우 기능이 추가가 되면 이 이슈에 추가 댓글로 말씀드리도록 하겠습니다. 
빠르면 다음주에 가능할 것 같아요~
감사합니다.

**Comment by daumPostcode** [comment]
@U-lis 
안녕하세요 답변이 매우 늦어서 죄송합니다.

현재 금일 배포로 

- focusInput = true/false (default: true)
ㄴ false설정시 우편번호서비스 실행 후 자동으로 input박스에 초점이 가지 않습니다.
- focusContent = true/false (default: true)
ㄴ 동작방식이 환경에 따라 다를 수 있어 해당옵션은 필요하신 분만 이용하는 히든옵션입니다.
ㄴ focusInput설정시에도 스크롤이 튀는 현상이 발생한다면 해당 옵션도 false로 설정해주시면 감사하겠습니다.

한번 확인 부탁드립니다.
감사합니다.

**Comment by bernard-kms** [comment]
안녕하세요, `react-daum-postcode`의 메인테이너입니다.
우편번호 서비스에 추가된 생성자 속성(`focusInput`, `focusContent`)을 반영한 새로운 릴리즈를 배포했습니다. (https://github.com/bernard-kms/react-daum-postcode/releases/tag/v1.9.0)

우편번호 서비스의 지속적인 운영과 개발에 감사드립니다 :)
