### ISSUE TITLE
다음 주소 검색 시 문의 사항

### ISSUE THREAD

**Issue by kyeongjin** [daumPostcode/QnA#59]
안녕하세요.

지번 주소로 검색 했을 시에 받아온 도로명 주소로
다시 한번 다음 api에 검색하여 값을 받아오고 싶어 문의 드립니다.

이 경우 
지번 주소 검색 -> 도로명 주소 받아옴 -> 받아온 도로명 주소를 다시 한번 다음 api에 검색

위와 같은 프로세스로 주소값들을 받아오고 싶습니다.
그런데 팝업이나 iframe으로 검색 했을 시, 가능하지 않는 것으로 보여,
따로 다음 api url을 통하여 값을 받아 올 수 있는 지 알고 싶습니다.
ajax 통신 및 다른 유사한 방법도 괜찮습니다.

빠른 확인 부탁 드리겠습니다.

**Comment by daumPostcode** [comment]
@kyeongjin 

네~ 안녕하세요~

현재 우편번호 서비스는 팝업형/레이어형 뷰를 가진 JS API형태로만 제공을 하고 있으며,

REST API형태로는 제공을 하고 있지 않습니다. 
아쉽지만, 해당 기능에 대해서는 행자부에서 제공하는 데이터를 가지고 직접 매핑하셔야 될 것 같아요;;
