### ISSUE TITLE
bname, bname1, bname2 문의

### ISSUE THREAD

**Issue by leejaycoke** [daumPostcode/QnA#590]
안녕하세요. 좋은 라이브러리 제공해주셔서 감사합니다.

`bname`과 `bname2`값에 어떤 차이가 있는지 알려주실 수 있나요?
메뉴얼에는 두 필드값에 대하여 같은 설명이 적혀 있습니다.
제 생각하기에는

* `bname`: 법정동/리
* `bname1`: `bname`이 법정리 일때 읍/면 정보

값으로서 `bname2`필드가 필요할까? 문의이 듭니다.

직접 주소 검색을 해봐도 `bname`과 `bname2`는 항상 같은 값으로 응답합니다.

혹시 두 값이 다를 수 있다면 예제 데이터(or 주소)를 알려주실 수 있나요?

감사합니다. ~~~

**Comment by daumPostcode** [comment]
@leejaycoke 
안녕하세요~

bname과 bname2는 같은 데이터가 내려가는게 맞습니다.
실제 내부에서도 같은 데이터를 이용합니다.

그런데 왜 같은 데이터로 두었냐 하면,,
"읍/면" 지역의 경우 bname1에 읍면 정보가 들어가는데,
"리" 정보의 경우 "읍/면"정보의 하위 정보 또는 다음정보에 해당되기 때문에 bname2 로 명명하였습니다,.

즉, 깔맞춤을 위한 데이터 구성일뿐, 말씀하신것처럼 bname1 + bname
 이렇게 쓰셔도 무방합니다~

**Comment by leejaycoke** [comment]
@daumPostcode 답변 감사합니다. :)
