### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by kyeongjin** [daumPostcode/QnA#6]
우정사업본부에서 2016년 11월 1일 부터  우편번호 6자리는 제공 하지 않는다고 확인 하였는데,
그렇게 되면, 다음 api 에서도 6자리 우편번호는 제공하지 않나요?

더불어 일련번호 9자리도 제공하지 않나요??

**Comment by daumPostcode** [comment]
@kyeongjin 네~ 안녕하세요~

일단 질문주신 내용중에서 2016년 11월 1일에 어떤 정책을 시행한다 하는 내용은 받지 못한 상태입니다.

일단 저희가 파악하고 공지하는 내용으로는
[Q&A 페이지](https://github.com/daumPostcode/QnA)의 FAQ 3번과 같이
**2015년 8월 1일**부터 저희쪽으로 신규주소 또는 갱신된 주소를 우정국 또는 행자부에서 데이터를 전달 받을시, 6자리 구우편번호는 없습니다.([우정국 공지 참고](http://www.epost.go.kr/main.retrieveNoticeContent.comm?news_seq_no=900)) 다만 모든 주소가 한번에 업데이트가 안되기 때문에, 저희 우편번호서비스 검색 결과에도 구우편번호가 있는 주소도 있고 없는 주소도 있고 하는 거에요~ 하지만 점차적으로 구우편번호는 없어질 것입니다. 다만 이를 대체할 **새우편번호(기초구역번호 5자리)**는 항상 모든 주소에 있기 때문에 이를 활용하셔야 합니다.

만약 v1서비스를 이용하고 계시다면 이번에 v2로 이전 해주시는 것을 강력히 추천하구요. v2를 이용하고 계신다면 우편번호 데이터필드를 postcode에서 zonecode로 변경해서 이용하시는 것을 추천합니다.

또한 추가적으로 **2016년 8월 1일** 부터는 6자리 구우편번호를 쓰면 규격외 요금이 매겨진다고 하니 이부분도 참고 부탁드립니다 ([우정국 공지사항](http://www.epost.go.kr/main.retrieveNoticeContent.comm?news_seq_no=1063&targetRow=1&searchKey=&searchWrd=))

그리고 일련번호 9자리라는 것이 어떤 데이터를 말씀하시는 것일까요?
혹시 "6자리 구우편번호 + 3자리 구우편번호일련번호"를 말씀하시는 것일가요? 
저희 [가이드 페이지 속성 탭](http://postcode.map.daum.net/guide#attributes)의 oncomplete부분의 표를 보시면 확인 가능 하신데요, 해당 데이터는 구우편번호를 받을 수 없었던 2015년 8월 1일 부터, 구우편번호가 없는 주소에는 내려가고 있지 않습니다. 이점 참고 부탁드립니다.
