### ISSUE TITLE
세종특별자치시 검색시 response Data - sigungu 필드 null 리턴 문의

### ISSUE THREAD

**Issue by enenfru** [daumPostcode/QnA#60]
안녕하세요~
전에 주소 response 데이터에 대한 필수 또는 옵션에 대한 이슈를 남긴적이 있습니다.
이슈 링크 [https://github.com/daumPostcode/QnA/issues/42](https://github.com/daumPostcode/QnA/issues/42)

sigungu 에 대한 필드는 필수로 받을수 있는 값이라고 말씀하셨는데요.

세종특별자치시로 검색했을 때,  sigungu 값이 null을 리턴하고 있습니다.
sigunguCode 값은 있지만 sigungu 값이 없는 것도 이상합니다.

이것도 버그인지 확인 부탁드립니다^^~ 감사합니다.

**Comment by daumPostcode** [comment]
@enenfru 
네~ 안녕하세요~

네;; 버그는 아니에요; 세종특별자치시의 경우, 상위 뎁스인 do가 없기 때문에, sido 변수에 매핑이 되고, sigungu 변수에는 매핑이 안되며, sigunguCode는 sigungu변수에만 명확하게 해당되는 데이터라기 보다 sido-sigungu 변수와 매핑되는 변수라고 보시면 됩니다. 

변수명에서도 알 수 있지만, sido와 sigungu의 si는 겹칩니다. 이는 주소의 뎁스 구조에 따라 적절히 분배를 하는 것인데요, '시' 정보의 경우 '도' 정보가 있으면 sigungu에, 없으면 sido에 '시' 정보가 들어갑니다. 이와 비슷한게 '특별시나 광역시'인데, 이 주소들은 '구'정보가 있고, 세종은 '구'정보가 없기 때문에 말씀하신 것과 같은 문제가 발생합니다.

이와 다르게 코드의 경우에는 주소의 뎁스 형태와 상관없이, 전국 지역을 특정 규칙에 따라 부여한 것이기 때문에 code값을 이용하시는 데에는 큰 문제는 없으실 거에요. sigunguCode의 경우 어떤 주소에 상관없이 법정동코드의 앞 5자리 또는 도로명코드의 앞 5자리 정보를 이용하기 때문에 sido-sigungu의 데이터 유무와 상관없이 이용하시면 됩니다.

아무튼, 세종시의 경우 좀 애매한 케이스라, sigungu 정보의 경우, null데이터에 따른 내부적으로 예외처리를 하시는 것을 권장합니다.

도움이 되면 좋겠으나, 답변이 이해가 안가시거나 다른 질문 사항이 있으시면 언제든 댓글 또는 이슈 등록 부탁드립니다.
