### ISSUE TITLE
특별자치시, 특별자치도 같은경우 약식으로 받을수는없는건가요?

### ISSUE THREAD

**Issue by shtmrl** [daumPostcode/QnA#61]
세종특별자치시나 제주특별자치도 같은경우는 전체 이름으로 받는데
서울특별시나 인천광역시 같이
서울,인천 이렇게
세종,제주 이런식으로 받을 수있나요?

**Comment by daumPostcode** [comment]
@shtmrl 
네~ 안녕하세요~

설정옵션중에 shorthand라는 옵션이 있는데요, 기본적으로는 true입니다. 그래서 대부분의 주소 1뎁스의 경우 축약형태로 내려가고 있는데요.

아쉽게도, 세종특별자치시, 제주특별자치도의 경우 지자체의 요청으로 인해 제외된 케이스 입니다.
현재는 이 두가지가 지자체 요청의 의해 축약형태로 나오지 않기 때문에, 적용하시는 쪽에서 임의로 이 두가지 케이스의 경우에 replace를 해주시면 될것 같습니다.

감사합니다.
