### ISSUE TITLE
전북 전주시 덕진구 동산동 664-5 (전라북도 전주시 덕진구 쪽구름3길 35) 검색이 안됩니다.

### ISSUE THREAD

**Issue by jungsoo108** [daumPostcode/QnA#613]
전북 전주시 덕진구 동산동 664-5 (전라북도 전주시 덕진구 쪽구름3길 35) 검색이 안됩니다.

**Comment by daumPostcode** [comment]
@jungsoo108 

안녕하세요~
넵. 현재 5월 15일 전주시 행정구역 명칭변경 업데이트가 있었는데,
변경에 따른 엔진 반영이 늦어져서 발생한 문제로, 빠르면 오후 6시 이후에 검색엔진에 반영이 될 수 있을 것 같습니다.

불편을 드려 죄송합니다 ㅜ.ㅜ

**Comment by daumPostcode** [comment]
@jungsoo108 
안녕하세요~ 현재 해당 오류 수정 되어 실서버에 반영되었습니다.
확인 부탁드립니다.
불편을 드려 죄송합니다.
