### ISSUE TITLE
maxSuggestItems 속성이 작동 안 하는 거 같은데 확인 부탁드립니다.

### ISSUE THREAD

**Issue by GoatHead** [daumPostcode/QnA#616]
안녕하세요? 좋은 서비스 만들어주셔서 따로 구현/유지 보수에 대한 걱정 없이 편안하게 이용하고 있습니다. 감사합니다.

다름이 아니라 [공식 가이드](http://postcode.map.daum.net/guide) 에서 제공하는 레이어 팝업 예제의 maxSuggestItems 속성이 제대로 작동하지 않는 것 같아 문의드립니다. 속성이 직관적으로 보여주는대로라면 검색 결과값으로 5개를 출력해야 하는데, 지금은 설정하거나 설정하지 않으나 최대량을 보여주고 있는 것 같습니다.

[JsFiddle 링크](https://jsfiddle.net/73ejfg8a/)

**Comment by daumPostcode** [comment]
@GoatHead 

안녕하세요~
maxSuggestItems의 경우, 검색결과가 아닌 검색어를 입력할때 나타나는 서제스트 리스트의 갯수를 의미합니다.
몇몇 단말기에서 서제스트 갯수가 너무 많을시 문제가 발생한 경우가 있어서 추가한 옵션입니다.

<img width="1349" alt="스크린샷 2020-05-24 오후 10 23 18" src="https://user-images.githubusercontent.com/20675065/82755243-5e2d1e00-9e0d-11ea-82ea-791c073309fd.png">
<img width="1315" alt="스크린샷 2020-05-24 오후 10 23 38" src="https://user-images.githubusercontent.com/20675065/82755244-608f7800-9e0d-11ea-9c3e-5d7fe2f32891.png">

위 두 스샷을 비교해 보시면 아실 수 있으실 거에요~
저희 회사 내부에서는 검색어를 입력할때 나오는 리스트를 서제스트라 부르기 때문에 속성명이 그렇게 지어진점 참고 부탁드립니다.

감사합니다.

**Comment by GoatHead** [comment]
@daumPostcode 

답변 감사드립니다 ^^ 용어상에서 오해를 했었나봐요
