### ISSUE TITLE
ionic 에서 주소 선택 후 NavController.pop() 실행 시 앱이 재시작되는 현상 문의

### ISSUE THREAD

**Issue by thimtkfkd05** [daumPostcode/QnA#618]
안녕하세요, 현재 아이오닉 프레임워크로 앱을 개발 중입니다.
그런데 지난 달까지 정상적으로 작동하던 주소검색 동작이 며칠 전부터 갑자기 제목과 같은 현상을 일으키고 있습니다.
아이오닉 앱에 연동 시 참고한 코드는 아래 블로그의 것이고,
https://stove99.github.io/javascript/2019/10/08/daum-postcode-in-ionic/
이 블로그 글의 댓글에도 저와 같은 증상을 겪는 분이 계셨습니다.
안드로이드/iOS/Web 모든 환경에서 동일한 증상입니다.

혹시 문제가 무엇인지 알 수 있을까요?

**Comment by daumPostcode** [comment]
@thimtkfkd05 
안녕하세요~

글쎄요... 음.. 추가된 기능이라 해봤자. focus여부랑 onsearch 콜백밖에 없는데. 음...
제가 아이오닉을 잘 몰라서; 적절한 답변을 드리긴 어려운데,
현재 우편번호 서비스는 기본적으로 내부 iframe에서 form submit으로 검색을 합니다.
이와 관련된 문제라면, submitMode:false 옵션을 통해 location.replace를 이용하도록 변경할 수 있는데 한번 이걸로 바꿔 보시겠어요?

**Comment by thimtkfkd05** [comment]
답변 감사합니다! 늦은 시간에도 확인하시는군요.. 고생이 많으십니다ㅜㅜ
지금 한번 확인해보겠습니다!

**Comment by thimtkfkd05** [comment]
submitMode: false 옵션 추가했더니 한번에 해결되었습니다!
늦은 시간에 정말 감사합니다ㅠㅠㅠ
스크립트 내에서 location 을 변동시키는 코드가 있었나보네요
오늘 반나절동안 삽질하던거 덕분에 금방 해결되었습니다 정말 진심으로 감사드립니다ㅜㅜ
좋은 밤 보내세요!! :)

**Comment by daumPostcode** [comment]
@thimtkfkd05 
오. 다행입니다. ㅎㅎ

submitMode 옵션의 경우, 몇몇 서비스에서, 우편번호서비스에서 여러번 검색을 하면 불필요한 history stack이 쌓여서 뒤로가기 할경우 버그처럼 보이는 현상때문에 추가한 것인데;;

아이오닉에서도 이와 비슷하나 좀 다르게 동작을 하나 보군요.
아무튼 해결이 되셔서 다행입니다.
고생하셨습니다~
