### ISSUE TITLE
우편번호 api 문의

### ISSUE THREAD

**Issue by wjdalsla87** [daumPostcode/QnA#62]
다음에서 제공하는 우편번호 api를 사용하고 있습니다.

그런데  시청 전산 행정망에서는 우편번호 창이 뜨지 않습니다.
(그 외에는 정상적으로 열림)

지도 api 는 http://cafe.daum.net/daumdna 안내사항이 있는데

우편번호는 있지 않아서 어떻게 해야하는지 문의합니다.

전산실에 연락해보니, 아이피가 막혀있는지 확인할 수 있도록 아이피를 알려달라고 하는데
 <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
에서  dmaps.daum.net 의 아이피 주소를 확인할 수 없습니다.

어떻게 해야하는지 문의합니다.

**Comment by daumPostcode** [comment]
@wjdalsla87 
네~ 안녕하세요; 답변이 늦어 죄송합니다;

시청 전산 행정망이라고 하시니; 외부 인터넷 연결이 되지 않은 내부 인트라넷 이신가요?
일단 내부 전산망에서는 저희 서비스가 접근이 불가능한 것은 알고 계실거에요; 일단 내부 전산망에서 사용하실땐 지도API와 방식은 같습니다. 다만 지도 API는 제휴센터를 통해 도메인이 하나로 묶여 있는 터널링 버전을 이용하시면 되는데, 우편번호 서비스의 경우에는 준비가 되어 있지 않습니다.

그래서 요청이 올때마다 방화벽 해제를 해야할 도메인 리스트를 알려드리고 있는데요. 방화벽에서 보통 IP를 통해 접근해제를 풀기 때문에 IP를 직접 확인하셔서 처리하셔야 합니다. (방화벽 처리 관련된 부분은 제가 이쪽 전문가가 아니라서 정확히는 설명을 못 드리는 점 양해 바랍니다.)

--------------------
아래부터는 우편번호 서비스에서 사용하는 도메인 리스트입니다.
HTTP환경
- http://postcode.map.daum.net 
- http://dmaps.daum.net 
- http://s1.daumcdn.net 
- http://i1.daumcdn.net 
- http://m1.daumcdn.net 
- http://apis.daum.net 
- http://stlog1.local.daum.net 
- http://sughub.search.daum.net (v1,v2)
 
HTTPS 환경 
- https://spi.maps.daum.net 
- https://s1.daumcdn.net 
- https://i1.daumcdn.net 
- https://m1.daumcdn.net 
- https://apis.daum.net 
- https://sughub.search.daum.net (v1,v2)

HTTP 또는 HTTPS환경에 따라 처리해야할 도메인이 약간 다릅니다. 이점 확인 하시고 처리 부탁드립니다.

감사합니다.
