### ISSUE TITLE
ios. wkwebview사용시 주소선택 문제.

### ISSUE THREAD

**Issue by joohopark** [daumPostcode/QnA#620]
제가 무엇인가 빼먹은게 있을수도 있지만 

현제 개발 환경은
- cordova 
( 플러그인 : cordova-plugin-wkwebview-engine/ cordova-plugin-wkwebview-file-xhr/ cordova-plugin-inappbrowser...)
- ios 12 +
- xcode 11.4

을 사용하고 있는 하이브리드앱을 개발중 입니다.

다음 주소 찾기 기능을 추가할때는 webview로 했었고
현재는 애플에서 wkwebview만 사용을 권고해서 wkwebview로 전면 수정한 이후 테스트 중 

다음 주소 찾기에서 주소를 누르면 autoclose되지 않고 safari 개발자 기능으로 콘솔을 열어보면 

>Unable to post message to file://. Recipient has origin null.

에러가 발생합니다. 

구글링을 하다보니 

https://github.com/apache/cordova-ios/issues/756

이러한 유사 이슈가 있던데 혹시 다른 해결 방법을 알고계신지 여쭤봅니다..

 다음 주소 찾기 를 사용한 코드는 아래와 같습니다

`//
new daum.Postcode({
                oncomplete: function(data) {

                    // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                    // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                    // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                    var addr = ''; // 주소 변수
                    var extraAddr = ''; // 참고항목 변수

                    //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                        addr = data.roadAddress;
                    } else { // 사용자가 지번 주소를 선택했을 경우(J)
                        addr = data.jibunAddress;
                    }

                    // 우편번호와 주소 정보를 해당 필드에 넣는다.
                    $("#zip_code").val(data.zonecode);  //우편번호
                    $("#first_address").val(addr)     //사용자가 선택한 주소
                    $("#area_code").val(data.sigunguCode)//시/군/구 코드로 우선 삽입

                    // iframe을 넣은 element를 안보이게 한다.
                    // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)
                    element_wrap.style.display = 'none';

                    //삽입 후 뒤로가기
                    fn.popPage();

                },
                // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분. iframe을 넣은 element의 높이값을 조정한다.
                onresize : function(size) {
                    element_wrap.style.height = 'calc(100vh - 83.33px)';
                },
                width : '100%',
                height : '100%'
            }).embed(element_wrap);
//
`

가련한 중생에게 도움을 조금이나마 주시면 감사하겠습니다...
ㅠㅠ

**Comment by daumPostcode** [comment]
@joohopark 
안녕하세요~

저희가 내부적으로 사용하는 postMessage의 보안정책에 따라 락이 걸리는 것으로 보이는데요.
postMessage를 이용할때 데이터를 전달할 사이트의 도메인값이 필요한데, 이때 해당 도메인이 file:// 이런 프로토콜을 사용할시 데이터 전달을 할 수가 없습니다.

이는 [FAQ9번, 10번](https://github.com/daumPostcode/QnA#9-%EB%AA%A8%EB%B0%94%EC%9D%BC%EC%95%B1%EC%97%90%EC%84%9C%EB%8F%84-%EC%82%AC%EC%9A%A9%ED%95%A0-%EC%88%98-%EC%9E%88%EB%82%98%EC%9A%94)을 통해 아실 수 있으며, 우편번호서비스 화면을 띄울 페이지를 별도로 web server를 통해 페이지를 불러와서 동작할 수 있게 작업을 하셔야 합니다.

우편번호 서비스 API는 웹환경에 맞게 설계된거라 코르도바와 같은 웹앱을 사용할땐 바로 적용이 되진 않습니다.
이부분 확인 부탁드립니다.

**Comment by joohopark** [comment]
답변 감사합니다! 찾아보다가 faq 참조한 이후 
1. 서버에 html페이지 만들고 여기서 다음주소 찾기를 띄우고
2. cordova에서 iframe으로 연 후
3. 서버와 클라이언트(cordova)간 passdata를 통해 해결했습니다!

이 이슈는 닫는걸로 하겠습니다. 3일정도 삽질 결과 이 방법이 젤 깔끔하네용..
