### ISSUE TITLE
동삭1로22번길 19-17 지번 문의

### ISSUE THREAD

**Issue by jomingi** [daumPostcode/QnA#628]
안녕하세요.
아래 주소의 지번이 없습니다. 확인바랍니다.

주소 : 경기도 평택시 동삭1로22번길 19-17

**Comment by daumPostcode** [comment]
@jomingi 
안녕하세요~ 버그 제보 감사드립니다.

해당 내용 주소 데이터 담당자 분께 전달하도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@jomingi 
안녕하세요~
중간공유 드립니다.

금일 말씀하신 도로명주소에 매핑된 지번주소의 오류가 수정되었습니다.

다만, 아직 지번주소로 검색시에는 지번이 없는현상이 있는데, 해당 현상도 곧 수정하도록 하겠습니다. 
감사합니다.

**Comment by daumPostcode** [comment]
@jomingi 
현재 지번주소로 검색했을때에도 지번값이 잘 나오도록 패치 되었습니다. 
감사합니다.
