### ISSUE TITLE
phonegap 사용문의

### ISSUE THREAD

**Issue by sbkim422** [daumPostcode/QnA#63]
폰갭(cordova)를 사용해서
정상적으로 불러오고 검색도 잘 됩니다
그런데 검색된 주소를 누르면 oncomplete 함수를 타지 않습니다
왜 그런지 궁금합니다

**Comment by daumPostcode** [comment]
@sbkim422 
네~ 안녕하세요~

저희 깃허브 README.md파일을 한번 읽어보시면 좋으실것 같습니다.
그중. [12번](https://github.com/daumPostcode/QnA#12-팝업창에서-검색-후-결과를-클릭해도-반응이-없습니다)을 한번 읽어보세요. 

저희 우편번호 서비스는 웹서비스이며, 폰갭이나 코르도바에서 이용시, 검색까진 될 수 있어도 주소를 내려받을 수는 없습니다. 이는 외부 사이트에서 저희 도메인의 서비스가 뜨는거라 이종도메인통신 방법을 이용하는데 이때 클라이언트의 도메인정보가 필수 입니다. 아마 폰갭에서 바로 실행하신 것이면 이 도메인 정보가 없기 때문에 oncomplete함수는 실행되지 않습니다.

제가 폰갭이나 코르도바를 잘 몰라서 구체적인 해결책은 제시하지 못하지만,
저희 우편번호 서비스가 뜨는 페이지에서는 추가적인 웹뷰에 페이지를 호출하여, 그 페이지 안에서 사용하셔야 됩니다.
즉 정적 파일로 실행이 아닌, 웹서비스처럼 띄우셔야 합니다.

한번 확인 부탁드립니다.
