### ISSUE TITLE
주소로 좌표 검색 안되는 주소지가 있습니다.

### ISSUE THREAD

**Issue by casual77** [daumPostcode/QnA#638]
'경기 화성시 메타폴리스로 38' 로 검색하면 주소검색은 잘 나오나 해당 주소로 지도좌표 검색이 안나옵니다.
지번 형식의 같은 주소지는 지도좌표가 나옵니다.
확인해주시며 좋겠습니다.

**Comment by daumPostcode** [comment]
@casual77 
안녕하세요~

저희 우편번호서비스에서는 별도의 좌표를 내리지 않고 있습니다.
즉 저희 서비스를 이용해서 내려받은 주소를 기반으로 별도의 API를 이용해서 좌표값을 가져오시는것 같으신데요.

해당 주소-좌표 변환 API를 배포하는 곳, 또는 카카오개발자사이트에 문의해 주셔야 합니다.
한번 https://devtalk.kakao.com/ 여기에 문의를 남겨주시면 좋을 것 같습니다.

감사합니다.

**Comment by casual77** [comment]
네, 안내해주신데로 해보겠습니다.
답변 감사합니다.
