### ISSUE TITLE
울산광역시 남구 돋질로436번길 14(삼산동) 등록요청합니다.

### ISSUE THREAD

**Issue by Kuhave** [daumPostcode/QnA#639]
울산광역시 남구 돋질로436번길 14(삼산동)

juso.go.kr 사이트에서 조회가 됩니다. [조회결과](https://www.juso.go.kr/support/AddressMainSearch.do?searchKeyword=%EB%8F%8B%EC%A7%88%EB%A1%9C436%EB%B2%88%EA%B8%B8+14&dsgubuntext=&dscity1text=&dscounty1text=&dsemd1text=&dsri1text=&dssan1text=&dsrd_nm1text=&searchType=TOTAL&dssearchType1=road&dscity1=&dscounty1=&dsrd_nm_idx1=%EA%B0%80_%EB%82%98&dsrd_nm1=&dsma=&dssb=&dstown1=&dsri1=&dsbun1=&dsbun2=&dstown2=&dsbuilding1=&fillterHiddenValue=)
우편번호 조회 서비스에도 조회가 되도록 요청드립니다.

그리고 이건 질문인데, 건물 이름 변경시에는 자동으로 업데이트되나요?
답변 주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@Kuhave 
안녕하세요~

![스크린샷 2020-07-22 오후 9 42 39](https://user-images.githubusercontent.com/20675065/88177724-50a4e080-cc64-11ea-803a-fbd90a4f76de.png)
현재 말씀하신 주소, 저희 우편번호서비스에도 검색되는 것으로 확인 됩니다.~

추가로 행안부 데이터상 건물이름도 변경된다면 저희도 반영이 됩니다.
만약 행안부 데이터상 수정이 되었는데 저희쪽 반영이 안된다면 이슈등록 해주시면 바로 확인하여 수정 가능합니다.
감사합니다.
