### ISSUE TITLE
검색은 되는데 value 값이 검색값을 전부 불러오지 못하는 데이터가 있습니다.

### ISSUE THREAD

**Issue by pkw1983** [daumPostcode/QnA#64]
경남 사천시 나무전길 107
로 검색을하면 
경남 사천시 나무전길 107 (한주비치맨션) 
라는 도로명이 나오는데 해당부분 value 값이 뒤에 한주비치맨션부분이 
빠져 있습니다.
수정가능한지 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@pkw1983 
안녕하세요~

일단 저희 [우편번호서비스 v2 가이드 페이지 속성 부분](http://postcode.map.daum.net/guide#attributes)에서 oncomplete에 내리는 데이터 속성에 대해서 확인 부탁드립니다.

위 주소에서
"경남 사천시 나무전길 107"은 주소 값이며, "한주비치맨션"은 건물명입니다.

건물명의 경우 buildingName 부분에 따로 들어가니 참고 부탁드립니다.

한번 확인 부탁드려요~
