### ISSUE TITLE
주소검색창에 '우편번호서비스안내' 팝업 링크를 제어할 수는 없을까요?

### ISSUE THREAD

**Issue by kdjeon** [daumPostcode/QnA#649]
안녕하세요? 

먼저 DAUM의 주소검색 서비스를 잘 사용하고 있습니다. ^^ 감사합니다.

잘 사용하고 있는데 혹시, 이런 옵션을 좀 추가 할 수 있는지 해서요..

저희 서비스가 PC웹과 모바일 웹과 모바일 앱(하이브리드(웹뷰) 앱)으로 서비스가 되는데
웹 환경에서는 문제가 안되는데.. 
앱에서 해당 링크를 클릭하면 웹뷰 내에서 해당 팝업화면이 뜨면서
서비스 중이 화면이 다 가려버립니다. 
앱에서 어떻게 닫기를 제어할 수 없는 구조를 가지고 있어서 ㅜㅜ

이걸 클릭하면 더이상 앱을 진행못하고 앱을 재시작 해야 하는데.

혹시 속성 값에 해당 안내 링크를 사용하고 안하고
옵션을 추가 할수 없을까요??

사실 실제 사용자들은 해당 링크화면에 들어가서 볼 이유도 따로 없고
해당 링크를 통해 서비스 이탈이 생기다보니 문의를 드립니다.

그럼 수고하세요~

**Comment by daumPostcode** [comment]
@kdjeon 
안녕하세요~

해당 기능의 경우 우편번호서비스 생성자의 옵션으로 제어할 수 있게 추가가 가능합니다.
다만 현재 일정상 바로 추가는 어렵고 시간이 좀 필요한점 양해 부탁드립니다.

앱에서 웹뷰로 사용하신다면, 제가 앱개발을 안해봐서 잘 모르지만,
postcode.map.daum.net/guide 페이지가 열리는 것을 앱 차원에서 체크하여 사전에 리다이렉트가 되지 않게 하는 방법은 없을까요??

**Comment by daumPostcode** [comment]
@kdjeon 
안녕하세요~
많이 늦었네요;;

현재 해당기능 추가되어 배포되었습니다.
공식가이드 페이지를 참고하시기 바라며
옵션명은 생성자에 useBannerLink : false로 입력하시면 됩니다.
다만, 하단 배너 링크는 잘 사라지는데, 
검색결과가 없을경우에도 외부로 빠져나갈 수 있는 별도링크가 사라지지 않는 현상이 있습니다. 해당건은 금일 중으로 추가 배포가 될 예정입니다.;
이부분 참고 부탁드립니다~

추가로 외부로 튕겨지는 링크를 모두 제거하실려면, hideMapBtn 옵션도 같이 쓰셔야 좋습니다.
참고 부탁드려요~

감사합니다.

**Comment by daumPostcode** [comment]
@kdjeon 
현재 최종 배포되었습니다.
감사합니다.
