### ISSUE TITLE
전라북도 정읍시 산외면 평사리 411-1  적용안됨

### ISSUE THREAD

**Issue by SangLyul-Park** [daumPostcode/QnA#65]
전라북도 정읍시 산외면 평사리 411-1  를 검색하셔 입력시
지번주소만 입력되고 도로명 주소가 입력되지 않습니다.

다른 주소는 문제 없습니다..^^*

**Comment by daumPostcode** [comment]
@SangLyul-Park 

네~ 안녕하세요~
말씀하신 주소는 지번:도로명 주소가 1:N의 경우입니다.
이러한 경우 지번 주소를 선택하면 roadAddress가 아닌 autoRoadAddress에 들어가게 됩니다. 
해당 건의 대해서는 저희 [가이드 페이지](http://postcode.map.daum.net/guide#attributes)의 속성부분 oncomplete 설명 아래의 "autoRoadAddress"관련된 설명 박스가 있습니다. 이를 확인해 보시면 될것 같아요.

![2016-11-29 4 36 28](https://cloud.githubusercontent.com/assets/20675065/20700644/eb6ee782-b651-11e6-82e0-f6075a259180.png)

데이터는 문제없이 내려가고 있습니다. 도로명 주소를 직접 선택하지 않고 지번을 선택할시, 지번:도로명 = 1:N인 경우에는 autoRoadAddress에 첫번째 도로명 주소가 들어가게 됩니다. 이점 확인 부탁드립니다.
