### ISSUE TITLE
onSearch 속성 오류 문의

### ISSUE THREAD

**Issue by lshwa80** [daumPostcode/QnA#653]
추가된 onSearch 콜백함수를 현재 사용하고 있지는 않은데,
업데이트 후, 주소검색 실행시
<img width="586" alt="스크린샷 2020-09-17 오후 2 26 09" src="https://user-images.githubusercontent.com/29138754/93426992-005e9d80-f8f8-11ea-8e18-49be897f08d1.png">
관련 오류가 뜹니다.
onComplete 콜백함수만 사용하고 있습니다.
답변 한 번 부탁드리겠습니다.

**Comment by daumPostcode** [comment]
@lshwa80 
안녕하세요~

오류메세지 스샷 감사드립니다.

다만 현재 내부에서 테스트시 해당 현상이 발생하고 있지 않는데,
API의 생성자 부분, 즉 사용하고 계시는 부분의 코드를 올려주실 수 있으실까요?

**Comment by lshwa80** [comment]
내부적으로 PostCode.js 파일에서

<img width="584" alt="스크린샷 2020-09-17 오후 3 53 52" src="https://user-images.githubusercontent.com/29138754/93430789-29822c80-f8fe-11ea-916d-e7c0dde02060.png">

props에 onComplete 함수만 받아서 사용하고 있습니다.


실제 구현되어 있는 부분은

<img width="862" alt="스크린샷 2020-09-17 오후 3 48 10" src="https://user-images.githubusercontent.com/29138754/93430860-4454a100-f8fe-11ea-83ec-8201dd67d470.png">


모달로 띄워 사용하고 있습니다.
데이터 입력은 잘 되고 있는데, 팝업을 띄우자 마자(PostCode) 를 실행하자 마자 onSearch 에러가 납니다.

<img width="1670" alt="스크린샷 2020-09-17 오후 3 57 58" src="https://user-images.githubusercontent.com/29138754/93431077-972e5880-f8fe-11ea-8e7f-25d2ff945f70.png">

**Comment by daumPostcode** [comment]
@lshwa80 
안녕하세요~
네 코드와 좀더 자세한 오류메세지 감사합니다.

음 지금 봐보니, DaumPostcode라는 react wrapper를 사용하고 계시는것 같은데,
일단 해당 패키지는 제가 배포한 것은 아니고, 다른 유저분께서 저희 API를 react에서 사용하기 쉽게 랩핑한 것입니다.
제가 생각하기에 제 API내부에서 오류가 뜨는 부분은 없어보이고,
해당 wrapper쪽에서 오류가 발생해서 ishwa80님의 코드쪽으로 오류가 throw된것 같은데요.
해당 react wrapper에서 onSearch를 받을 수 있는 준비가 안되어 있어서 발생하는 것같이 보입니다.

한번 해당 리엑트 컴포넌트를 만드신 분의 git에 이슈를 등록해 보시는건 어떠실까 합니다.

**Comment by lshwa80** [comment]
답변 감사드립니다. 개발자분께 따로 문의 드리겠습니다.

**Comment by bernard-kms** [comment]
안녕하세요, DaumPostcode react wrapper의 개발자입니다.
해당 문제를 https://github.com/bernard-kms/react-daum-postcode/commit/3748a2906f62d7e1890bd4cb42139a3f19e7f6f3 으로 고치고 [v2.0.1](https://github.com/bernard-kms/react-daum-postcode/releases/tag/v2.0.1)로 배포했습니다. 참고 부탁드립니다!

**Comment by daumPostcode** [comment]
@bernard-kms 
빠른 수정 감사드립니다 ^^ 저번에도 엄청 빠른 수정 해주셨는데, 이번에도 엄청 빠르게 해주셨네요. 감사합니다 ^^

@lshwa80 
개발자님께서 수정배포 하셨다고 하시네요. 한번 업데이트를 받아보시는건 어떠실까 해요~

추가로 현재 버그가 있어서 수정을 해야하는데 (이건 제가 수정할 케이스)
검색결과가 없을때, onSearch의 콜백함수 인자로 들어오는 변수중 count값이 "undefined" 문자열로 떨어지는 현상이 있습니다.
혹시 onSearch를 사용하시고 count변수를 사용하신다면 count변수의 type이 number일 때만 사용하시는 것을 권장합니다. number가 아닌 string이 들어올때는 0을 뜻합니다.
이는 다음주 중에 배포하여 수정될 수 있도록 하겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
onSearch콜백에서 검색결과가 없을때 count값이 undefined로 나오던 현상이 수정되었습니다.
