### ISSUE TITLE
팝업인 경우에도 닫기 버튼 생기게 할 수 있나요?

### ISSUE THREAD

**Issue by es5es5** [daumPostcode/QnA#657]
안녕하세요.

팝업방식도 레이어, 끼워넣기 처럼 닫기 버튼 넣을 수 있을까요??

답변 부탁드립니다. 감사합니다!

**Comment by daumPostcode** [comment]
@es5es5 
안녕하세요~

아뇨. open()함수를 통한 팝업모드의 경우 window.open 네이티브 함수를 이용하는 것으로
브라우저단에서 지원하는 새창이 뜨는 것이기 때문에 별도의 닫기 버튼을 만들 수 없습니다.

별도의 닫기 버튼관련 커스터마이징을 하실려면,
팝업창을 띄우는 것을 직접 구현 하신 후에, 팝업창 안에다가 저희 우편번호서비스를 embed함수를 통해 끼워넣기 처럼, 삽입을 하시면 됩니다.
그리고 팝업에서 본문으로 데이터 보내는 것도, 직접 구현을 하시면 가능합니다. 
복잡해 보이지만, 조금만 고민해 보시면 그리 어려운 문제는 아닙니다.
실제 그렇게 구현해서 이용하시는 분들도 보긴 했습니다.

**Comment by es5es5** [comment]
@daumPostcode 
Thank you for your quick response.
I WILL TRY IT.
