### ISSUE TITLE
도로명 주소(신축 건물) 등록 요청합니다.

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#66]
주소 1: 경남 창원시 의창구 북면 천주로 488번길 32 (지번: 화천리 153)

주소 2: 경기도 파주시 광탄면 마장리 406 (경기도 파주시 광탄면 보광로 962 ) 행복대림아파트   

주소 3: 대구시 수성구 교학로 13 만촌3차 화성파크드림

**Comment by daumPostcode** [comment]
@dysong1 
네~ 안녕하세요~

저흰 새로 등록된 주소를 추가하지 못합니다. 더불어 건물명 또한 추가하지 못합니다.
주소와 건물 데이터는 행자부에서 100%받아서 처리하며, 검색시 나오지 않는다면, 행자부 도로명주소 검색 시스템에 문의 주시기 바랍니다.
자세한 사항은 [FAQ1번 참고 바랍니다](https://github.com/daumPostcode/QnA#1-주소가-없습니다--검색되지-않습니다)

해당 내용 꼭 확인 부탁 드립니다.. 저희쪽에 계속 요청하셔도 저희가 해드릴 수 없기 때문에, 주소가 계속 노출이 안될 수 있어요;;
