### ISSUE TITLE
firebase hosting으로 설정시 문제

### ISSUE THREAD

**Issue by yeolrim** [daumPostcode/QnA#664]
<안드로이드 앱 daumpostcode를 활용>
git에서 누군가 올린 서버 주소로는 동작하지만
제가 직접 firebase hosting서버로 설정하여 index.html file을 동일하게 적용하였는데,
firebase hosting으로 설정한 서버가 동작을 하지 않습니다.

로그상으로는 "Uncaught ReferenceError: daum is not defined", source: https://adas-1595815802086.web.app으로 뜹니다.

스크립트상에서 body까지는 동작하고 
<script src="https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js">
이부분이 동작되지 않는것 같습니다.

**Comment by daumPostcode** [comment]
@yeolrim 
안녕하세요~
일단 웹뷰와, 해당 서비스는 제가 사용해보질 않아서 답변은 드리기 어렵습니다.
daum is not defined라는건, 로더스크립트 자체가 로딩이 안됬다는 것인데, 스크립트 로딩부분을 체크해 보시기 바랍니다.
말씀하신 postcode.v2.js 이 파일 자체가 로딩이 안된거에욤. 

추가로 말씀하신 스크립트는 로더와 코어가 이원화된 구버전 스크립트로
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

위 스크립트를 이용해 주시면 좋을 것 같습니다. 
감사합니다.

**Comment by yeolrim** [comment]
firebase hosting으로 동작확인 하였습니다.
서버에 올리고 바로 되는게 아니고 좀 기다려야 적용이 되네요.
링크주신 스크립트로 적용하고 동작확인 하였습니다
감사합니다.
