### ISSUE TITLE
도로명 주소 시스템에서는 확인 되었으나 다음에서 검색되지 않습니다.

### ISSUE THREAD

**Issue by dysong1** [daumPostcode/QnA#67]
대구시 수성구 교학로 13 만촌3차 화성파크드림

확인부탁드려요!

**Comment by daumPostcode** [comment]
@dysong1 

안녕하세요~
음.... 어디서 검색이 안되는지 정확히 알 수가 없네요... 스크린샷 첨부합니다.

1. "대구시 수성구 교학로 13 만촌3차 화성파크드림" 주소로 검색
- 도로명 주소 시스템
![1](https://cloud.githubusercontent.com/assets/20675065/20747788/c5334828-b72e-11e6-99c4-3f2017c13a73.png)

- 다음우편번호서비스
![2](https://cloud.githubusercontent.com/assets/20675065/20747791/ca85b0a4-b72e-11e6-9e3c-71258caa4d02.png)

2. "대구시 수성구 교학로 13" 주소로 검색 (건물명 제외)
- 도로명 주소 시스템
![3](https://cloud.githubusercontent.com/assets/20675065/20747810/dc370b7c-b72e-11e6-9d3b-0ae1425158a3.png)
- 다음우편번호서비스
![4](https://cloud.githubusercontent.com/assets/20675065/20747817/e5c18208-b72e-11e6-94b9-70c1246d52ff.png)


위 스샷과 같이. 건물명을 포함하거나 포함하지 않고 검색을 해도 모두 검색이 되고 있습니다.

어떤 부분에서 검색이 되지 않는지 정확히 파악이 안되어 저희가 확인작업을 진행할 수가 없네요;; 좀 더 구체적으로 말씀해 주시면 확인해 보도록 하겠습니다.

건물명이 안보이는 것은 도로명검색시스템에 등록이 안되어서 안내려 오는 것이니 확인 부탁드려요~
