### ISSUE TITLE
아파트명 변경 요청

### ISSUE THREAD

**Issue by kimplove** [daumPostcode/QnA#677]
서울시 성동구 고산자로 164 도로명의 아파트명이
행당한신아파트 에서 서울숲한신더휴아파트로 변경되었습니다.
네이버지도, 다음지도, juso.go.kr 그리고 건축물대장, 등기본등본 모두 변경되어 있습니다.
아파트명 변경을 요청드립니다.

**Comment by daumPostcode** [comment]
@kimplove 
네~ 안녕하세요~
해당 주소 건물명 변견건 확인하였습니다.
현재 행안부가 저희쪽으로 업데이트 고시 관련된 이슈가 있어서, 아직 처리가 안된건으로, 이번주 내에 반영될 예정이라고 합니다.

감사합니다.
