### ISSUE TITLE
주소 검색후 읍,면 정보를 제공하는 필드를 알고싶어요..

### ISSUE THREAD

**Issue by juliusjang** [daumPostcode/QnA#68]
다음주소를 잘 사용하고 있습니다...

이렇게 훌륭한 서비스를 무료로 제공해주셔서 감사해요 ^^

다름이 아니오라.. 

제가 지역별 추가 배송비를 받으려고 하는데,,
주소검색시 시도, 구군, 동리 정보는 받아오는데
읍,면 정보는 따로 필드가 없더라구요..

예) 인천 웅진군 북도면 신도리 라고 검색을 하면
시도 : 인천
구군 : 웅진군
읍면 : 
동리 : 신도리

위와 같이 읍면을 제외한 값 필드( sido, sigungu, bname) 만 있습니다.
읍면에 해당하는 값도 받을 수 없을까요??

**Comment by daumPostcode** [comment]
@juliusjang 
네~ 안녕하세요;;

결론부터 말씀드리면,, 직접 데이터를 분리하여 작업을 하셔야 합니다.
현재 데이터상 의미있는 정보에 해당하는(코드별로 구분 값 등, sigunguCode, bcode 등) 값에 의해서만 분리가 되어 관리되고 있고, 이를 그대로 내리는 것이라 받은 데이터의 주소값을 공백 분리하여 사용하셔야 합니다.

저희도 내부적으로 각 뎁스별로 나눠져 있지 않아. 같은 방식으로 작업을 해야하는데요, API 형식상 데이터를 추가 한 후, 추후에 삭제하기가 매우 어려워서; 일반적으로 사용하는 값만 내릴 수 있는 점 양해 부탁드립니다.

**Comment by daumPostcode** [comment]
@juliusjang 
안녕하세요~ 

말씀해주신 기능이 추가되어 공유드립니다.

기존까지는 읍/면 지역의 경우에는 데이터를 쪼개어 내리지 않고 일반 주소를 split하여 사용하도록 가이드를 했었는데요.
금일(1월 9일) 업데이트된 사항에는
bname1, bname2라는 변수가 추가되었습니다.

bname2는 기존의 bname과 같다고 생각하시면 되며, 읍/면 지역의 경우 읍/면 정보가 bname1에 들어가게 됩니다.
동지역의 경우에는 공백으로 내려갑니다.

자세한 사항은 http://postcode.map.daum.net/guide#attributes를 참고해 주시기 바랍니다.

감사합니다.

**Comment by juliusjang** [comment]
Wow!
So much. very very thanks, daumPostcode.
