### ISSUE TITLE
행정동이 반영되지 않고 있습니다. (hname 출력값이 없슴)

### ISSUE THREAD

**Issue by beomsub** [daumPostcode/QnA#69]
예를 들면 
검색주소가 서울 마포구 동교동 113-29 일 경우 
행정도이 서교동으로 출력되어야 하지만 
hname의 value가 없습니다.
다른 시/도에서 검색하여 확인해봐도 hname value값이 출력되는 곳은 없네요.
행정도 데이타를 업데이트 해주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@beomsub 
안녕하세요~ 답변이 매우 늦어서 죄송합니다.. 신변에 변화가 생겨서 좀 늦었네요 ;;;;

일단 확인해본 결과, 저희 가이드페이지의 안내 문구가 오해를 불러일으킨것 같아요;; 이점 죄송합니다.

현재 "행정동"표시 또는 데이터의 경우에는 
"검색어를 행정동으로 검색을 하고, 검색결과의 법정동과 검색어에 입력한 행정동과 다른 경우에 표시" 를 하고 있으며 이런 경우에만 데이터가 내려갑니다.

즉 말씀하신 것처럼, 해당 주소의 행정동 정보를 내리는게 아니라, 검색어에 따라 안내성으로 표시를 하고 이를 데이터로 내리고 있습니다.
실제 "부평3동"의 경우 행정동인데요.
<img width="498" alt="2016-12-13 7 27 11" src="https://cloud.githubusercontent.com/assets/20675065/21136817/905cfbd0-c16a-11e6-8d96-12cf9b6a228b.png">
부평3동으로 검새하면 아래 결과에 실제 법정동인 "십정동"과 괄호에 행정동이 표시가 되며, 이를 데이터로 내리고 있습니다.

말씀해주신 주소로 예를 들면,
"서울 마포구 동교동 113-29"는 현재 법정동으로 제대로 표시가 되어 있습니다. 이런 경우에는 법정동으로 검색이 되고; 검색 결과도 법정동으로 나오기 때문에 화면에 표시나, 데이터로 내려가는게 없는 것이며;
만약 "서울 마포구 서교동 113-29"과 같이 행정동으로 검색을 하면, 주소는 법정동으로 검색이 되지만 괄호에는 행정동으로 표시가 되고, 내려가는 데이터에도 hname값이 들어가게 됩니다.
<img width="497" alt="2016-12-13 7 32 45" src="https://cloud.githubusercontent.com/assets/20675065/21136928/04c5f936-c16b-11e6-8f22-11176765a938.png">

즉, hname변수는 주소의 행정동 정보를 내리는게 아니라, 사용자가 검색을 했을 때, 검색어에 따라 참고자료로 활용하시라는 의미로 내리는 것입니다.;;

이부분은 맨 처음 말씀드린 것과 같이 가이드 페이지의 설명 오류이며, 이를 수정해 두도록 하겠습니다.

더불어, 말씀해 주신 "주소의 행정동 정보"에 대해서는 내부 논의를 해봐야 되기 때문에, 바로 적용은 힘들구요, 시간이 좀 필요할 듯 합니다;

**Comment by beomsub** [comment]
지자체에서는 행정서비스를 행정동 기준으로 하기 때문에 법정동 검색시 행정동 안내가 반드시 필요합니다.
되도록 빠른시일내에 법정동으로 검색할 시 행정동 안내서비스도 같이 지원되었으면 하는 바램입니다.
위 답변에 감사드리며 앞으로도 많은 개선 지원 부탁드립니다.

**Comment by daumPostcode** [comment]
@beomsub 
네~ 안녕하세요~

금일 행정동 정보를 더 많이 보이게 할 수 있는 옵션이 추가되어 공유드립니다.

해당 기능은 생성자에 showMoreHName:true 라는 형식으로 옵션을 설정하면 활성화 되며,

기존의 행정동 표시로직에 검색결과의 법정동과 행정동이 다른 경우 무조건 표시하고, 이를 데이터로 내리게 됩니다.

다만 현재 지번이 메인주소일대는 문제가 없지만, 도로명이 메인주소 일때는 연관된 지번주소의 행정동이 비어있는 경우가 좀 있습니다. 이는 지속적으로 데이터 체크를 하여 수정해 나갈 예정으로, 저희에게 직접 CS를 주셔도 되며, 점진적으로 개선해 나갈 수 있도록 노력하겠습니다.

그리고 UI상 표기는 지번주소에만 행정동이 표시되는점 참고바랍니다.

자세한 사항은 http://postcode.map.daum.net/guide#attributes <- 가이드 페이지의 속성 부분의 아랫쪽을 참고 하시기 바랍니다.

감사합니다.
