### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by sinnau** [daumPostcode/QnA#7]
우편번호 를  ios 하이드리드 webview 로  embed 하여 사용하고 있습니다.
검색결과에서 지도를 클릭하면 새창이 아닌 앱을 전부 덮어 버립니다.
지도 텍스트를 삭제하거나, 클릭을 막거나, 지도클릭시 이벤트를 알수 없나요? 이벤트발췌 가능시 하이브리드앱에서 별도 호출을 하려고 합니다.

**Comment by daumPostcode** [comment]
@sinnau 
네~ 안녕하세요~

네 현재, 텍스트를 삭제하거나, 클릭을 막거나 하는 기능은 없습니다.

다만 "**지도**" 버튼을 클릭하면 이벤트의 경우에는 **click** 이벤트로 대응하며,
지도서비스를 window.open함수를 통해 팝업의 형태로 띄우게 됩니다.
모바일 환경에서는 m.map.daum.net을 PC환경에서는 map.daum.net을 띄우고 있습니다.

현재로써는 위 정보를 가지고 대응을 하셔야 할 것 같습니다.

UI변경 옵션의 경우에는 저희가 소극적으로 대응하는 편인데, 모바일 + 웹뷰의 경우에는 window.open문제도 있으니, 이부분 참고하여 다음 업데이트때 반영해 보도록 하겠습니다.(의견 반영은 내부 회의를 거쳐야 해서 정확하진 않습니다.. 만약 없앨 수 있는 옵션을 넣는 것으로 결정되면, 이 이슈에 댓글로 남기도록 할께요~)

**Comment by daumPostcode** [comment]
@sinnau 
안녕하세요~

말씀하신 기능이 추가되어 댓글 답니다.

현재 '지도''영문보기' 버튼을 화면에서 감출 수 있는 옵션이 1월 7일부로 추가되었습니다.

옵션명은
hideMapBtn, hideEngBtn 이며 기본값은 false이며 true로 설정하시면 가려집니다.

자세한 사항은 http://postcode.map.daum.net/guide#attributes 의 속성 부분 아래쪽을 참고 바랍니다.
감사합니다.
