### ISSUE TITLE
IE10에서 스크립트 오류

### ISSUE THREAD

**Issue by namyangs** [daumPostcode/QnA#70]
IE10에서 스크립트 오류가 나고 있습니다. ㅠㅠ
그리고 기존 스크립트(spi.maps.daum.net)의 경우는 https를 제공하였는데,
현재는 제공이 안되는지 궁금합니다.
감사합니다 :)

**Comment by daumPostcode** [comment]
@namyangs 
네~ 안녕하세요;; 우선 답변이 늦어 죄송합니다;;

음.. 현재 저희 테스트기기에서 IE10에서 저희 가이드페이지가 정상적으로 동작하고 있습니다.

어떤 스크립트 오류인지 좀 더 확인해 주실 수 있으실까요? 또는 스샷이나, 저희가 접근할 수 있는 URL을 주시면 더욱 감사하겠습니다.
그리고 저희 FAQ도 한번 참고 부탁드립니다. - https://github.com/daumPostcode/QnA/blob/master/README.md

추가로 질문해 주신 내용에 답변을 달면
글 뉘앙스로 보면 기존에 v1을 사용하셨던것 같아요..
v2도 마찬가지로 같은 도메인으로 https를 지원합니다.

HTTP 가이드 : http://postcode.map.daum.net/guide
HTTPS 가이드 : https://spi.maps.daum.net/postcode/guidessl

HTTPS용 가이드 페이지에 들어가 보시면 저희 v2스크립트 URL정보도 다 표시되어 있으니 한번 확인 부탁드립니다.

감사합니다.
