### ISSUE TITLE
도로명 주소 검색 시 문의 사항

### ISSUE THREAD

**Issue by kyeongjin** [daumPostcode/QnA#71]
안녕하세요.
다음 api를 사용하여 쇼핑몰 운영 중에 있습니다.

![1](https://cloud.githubusercontent.com/assets/21231961/21091682/443eb84a-c08b-11e6-8d5e-11761b3664bf.PNG)
![default](https://cloud.githubusercontent.com/assets/21231961/21091683/4443d1fe-c08b-11e6-947a-293db5f57b1a.PNG)

위와 같이 

1. 경기도 부천시 중동로 254번길
2.경기도 부천시 중동로 254

로 검색하였을 경우 
검색 된 주소 목록이 다르게 나오는 것을 확인 할 수 있는데,

위와 같이 검색명을 어떠한 구분으로 구분하는지와
검색 시 꼭 필요한 정보의 대해서도 있다면 알려주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@kyeongjin 
네~ 안녕하세요~ 답변이 늦어 죄송합니다;;;

우선 예시로 올려주신 내용은, 실제 도로명 주소 체계상 완전 다르게 해석이 됩니다. 즉 검색결과가 다른게 맞습니다.

현재 대한민국의 도로명 주소는

시도-시군구-(읍,면)-도로명-건물번호
와 같은 형식으로 되어 있습니다. 이들의 표기상 구분자는 " " 공백이라고 생각하시면 됩니다.
("동" 지역의 경우에는 "구"까지 표시가 되며, "리" 지역의 경우, "읍"이나 "면"까지 표시가 됩니다)

- 중동로 254번길
- 중동로 254

이 둘의 제일 큰 차이는 숫자뒤의 "번길"이라는 것인데요, 저희 검색엔진이 단순하게 공백으로 잘라서 의미를 해석하진 않아요; 기본적으로 공백 위주로 주소가 구성되니 그렇게도 보지만, 숫자뒤 문자에 따라 다르게 해석하여 검색을 하게 됩니다.

즉, "중동로 254번길"의 경우 숫자뒤에 "번길"이 있기 때문에 "하나의 도로명이구나"라고 해석을 하여 검색을 하는 반면,
"중동로 254"의 경우에는 254를 건물번호로 해석하고 "중동로"만 도로명으로 해석을 했기 때문에 검색결과가 달라지는 것입니다.

우리나라 도로명주소체계가 좀 햇갈리실 수도 있으나, 기본적으로 "도로명" 부분은 띄어쓰기가 없습니다.
즉 "중동로 254번길"이 아니라 "중등로254번길"이 정확한 도로명이며, 띄어 쓰기를 할 경우 국내에 워낙 비슷한 형태의 도로명이 많기 때문에 다른 결과가 나올 수 있습니다.

해결 방법으로는.

"주소체계상 도로명 부분은 무조건 공백없이 한 단어로 쓰시고, 그 뒤에 연결되는 건물번호와 같은 정보는 공백을 추가하여 구분하여 검색을 하시면 될것 같습니다"
ex. "중동로254번길 11" 과 같이 검색을 하시는 것을 추천드립니다.
