### ISSUE TITLE
서울 은평구 진관동 87 번지가 검색되지 않습니다.

### ISSUE THREAD

**Issue by kkj4011** [daumPostcode/QnA#72]
서울 은평구 진관동 87 번지 의 주소가 모두 검색이 안됩니다.
87-3 같은 하부주소도 안되네요.

**Comment by daumPostcode** [comment]
@kkj4011 
네~ 안녕하세요~

혹시 행자부 도로명 주소 검색시스템에서 검색해 보셨나요?.
현재 위 사이트에서도 검색이 되지 않는 것으로 보아, 도로명주소가 발급된 주소가 아닙니다. 도로명주소가 발급된 주소가 아니라면 저희 시스템에서 나오지 않습니다.

자세한 사항은 https://github.com/daumPostcode/QnA/blob/master/README.md 를 참고 바랍니다.
