### ISSUE TITLE
submitMode : false일때 ie11이슈

### ISSUE THREAD

**Issue by zebra0303** [daumPostcode/QnA#720]
submitMode: false 를 추가했을때 ie11에서 주소검색시 '원하시는 페이지를 찾을 수가 없습니다.'란 오류가 나네요.
주소 검색어 쿼리를 encode를 안해서 발생하는 문제인듯 한데 혹시 해결 방법이 있을까요?

바벨에서 core-js/modules/es.array.iterator 를 같이 사용하며 옵션 값은 아래와 같습니다.
```
 use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/env',
                {
                  targets: {
                    browsers: ['last 2 versions', 'ie >= 11' ]
                  },
                  useBuiltIns: 'usage',
                  corejs:3,
                  shippedProposals: true,
                  modules: false
                }
              ],
              ['@babel/react']
            ],
            plugins: []
          }
        }
```

**Comment by daumPostcode** [comment]
@zebra0303 
안녕하세요~

바벨 셋팅과는 상관 없을겁니다. 바벨은 코드 빌드시 적용되지, 런타임 문제는 아니니까요;
IE11의 어떤 버전에서 문제가 발생하는지 알 수 있을까요?
submitMode:false의 경우엔 form.submit대신에 location.replace 를 사용하고 있긴합니다.

테스트 케이스를 좀더 정확히 적어주시면 확인해 보도록 하겠습니다.

**Comment by zebra0303** [comment]
주소를 검색하고 검색리스트에서 해당 주소를 선택하면 
'페이지를 찾을 수 없습니다'란 메시지가 나오고 있는 상태입니다.
요청 URL은 아래와 같은 형식이예요.

region_name 파라미터값이 ie에서만 인코딩이 깨어져서 발생하는 문제인거 같습니다.
```
*  https://spi.maps.daum.net/postcode/search?region_name=ìì¸í¹ë³ì ê°ìêµ¬ ë§ê³¡ë &cq=ìì¸í¹ë³ì ê°ìêµ¬ ë§ê³¡ë &cpage=1...
```

**Comment by daumPostcode** [comment]
@zebra0303 
네~ 안녕하세요~

해당 이슈의 경우 현재 확인되었으며, 이번주 목요일에 배포 예정입니다.
불편을 드려 죄송합니다.
감사합니다.

**Comment by daumPostcode** [comment]
@zebra0303 
안녕하세요~ 해당 오류 현재 수정되어 패치되었습니다.
확인 부탁드립니다.
불편을 드려 죄송합니다.
