### ISSUE TITLE
다음api 팝업이 열리지않습니다(익스플로러)

### ISSUE THREAD

**Issue by an4216** [daumPostcode/QnA#725]
구버전 script링크를 쓰고있구요. 링크에는 autoload=false 라는 파라미터 이외에는 전달되지않습니다.
현재 저희프로젝트는 IE7버전을 사용하고있어, 귀사에서 제공하는 console이 정의되어있지않아 오류로그를 확인할 수 없습니다.
관리자도구의 콘솔창을 확인한 결과 허용되지않는 파라미터를 보냈다는 소스부분에서 console에러가 난것으로 보아, 허용되지않는 파라미터를 보냈다는것같은데 소스내에 허용되지않는 파라미터가 포함되어있지 않습니다. 
팝업을 열수있는 방법이 있을까요?

**Comment by daumPostcode** [comment]
@an4216 
안녕하세요~
허용하지 않은 파라미터를 사용하지 않으셨다면, 에러를 발생시키는 해당 로직 자체가 실행되지 않습니다.
구버전 브라우저에는 console 자체가 없는 경우도 있어서 이에 대한 예외처리도 적용되어 배포가 되었습니다.

IE7에도 개발자 도구가 있는 것으로 기억이 되는데, 콘솔쪽에서 에러가 뜨고 있는지 확인 가능 하실까요?

**Comment by an4216** [comment]
해결되었습니다. console이 정의되어있지않는 오류라 변수처리하여 선언해주어서 해결하였습니다

2020년 12월 18일 (금) 오후 2:10, Daum 우편번호서비스 <notifications@github.com>님이 작성:
