### ISSUE TITLE
지도 api에 대해 문의사항이 있습니다.

### ISSUE THREAD

**Issue by dlgkstjd0** [daumPostcode/QnA#726]
안녕하세요.  c#으로 webBrower를 이용하여 다음 주소록을 쓰고있었습니다.
그런데 12월 17일부터 buliding_name과 buliding_code를 못가져오더라고요.

기존 사용했던 주소는 
http://postcode.map.daum.net/search?origin=http%3A%2F%2F&indaum=off&banner=on&mode=transmit&vt=layer&am=on&ani=off&sd=on&plrg=&plrgt=1.5&hmb=off&heb=off&asea=off&smh=off&us=on&msi=10&ahs=off&whas=500&sm=on&a51=off&zn=Y&fullpath=%2Fblank 

개발자 api 사이트를 찾아보니까 js형태로만있고 기존의 웹브라우저 형태의 사이트는 없는것같던데 혹시 방법이 없나요?ㅠㅠ

**Comment by daumPostcode** [comment]
@dlgkstjd0 
안녕하세요~

답변이 늦었습니다.
혹시 제가 확인할 수 있는 테스트케이스가 있을까요?
특정 주소에서 안나오는지 모든 주소에서 안나오는지,

추가로 올려주신 주소는 저희가 JS API내에서 팝업을 열때 사용하는 주소이며,
해당 주소에 직접 접근해서 사용하는 방식에 대해서는 공식 지원이 어렵습니다.

그리고 공식가이드 페이지의 샘플 예제를 통해서는 정상적으로 건물명과 건물코드가 내려가고 있는데,
어떻게 안되시는지 좀더 구체적으로 적어주시면 좋을것 같습니다.
