### ISSUE TITLE
[solved] [우편번호 업데이트] 우편번호가 다른 부분들이 존재 합니다.

### ISSUE THREAD

**Issue by seoch77** [daumPostcode/QnA#727]
검색시 우편번호가 우체국과 다른 부분들이 존재 합니다.

예 ) 경상북도 구미시 산동면 해마루공원로 115 (산동면, 구미호반베르디움엘리트시티)

검색시

다음API 는 39466 이고
우체국 또는 네이버는 39164 로 나오네요

이런 부분들이 다른 주소들도 존재 하는거 같습니다.
우편번호 업데이트를 안한것인지 초기에 잘못 들어 간것인지 수정이 필요 할듯 합니다.

또한 포털 검색시에도 잘못 나오는거 봐서는 반드시 수정이 필요 할듯 보이긴 하는데 업데이트 계획은 어떻게 될까요?

**Comment by daumPostcode** [comment]
@seoch77 
안녕하세요~

도로명 주소와 기초구역번호(5자리 우편번호)의 관리는 행안부가 담당합니다.
저흰 우체국의 데이터가 아니라, 행안부의 데이터를 이용하고 있습니다.

<img width="1283" alt="스크린샷 2020-12-22 오후 1 30 15" src="https://user-images.githubusercontent.com/20675065/102849140-d918ee80-4459-11eb-9d4b-b39935d56e85.png">

행안부엔 39466으로 되어 있으므로, 이 기초구역번호가 맞는 번호입니다.
네이버와 우체국이 업데이트가 안된것으로 보입니다.

이부분 참고 부탁드립니다.

**Comment by seoch77** [comment]
명쾌한 답변 감사합니다.
우체국이 업데이트가 안된 부분인지 몰랐네요
