### ISSUE TITLE
문의드립니다. 

### ISSUE THREAD

**Issue by leekyungjin** [daumPostcode/QnA#73]
홈페이지 개발업체인데요.. 
js파일이 로드되지 않네요..
어제까진 잘사용했었는데..
저희쪽 서버 아이피가 막힌건가요?
다른아이피로는 잘 들어가지고 잘뜨는데.. 
js인클루드된 페이지도 엄청 느리고.. 로드가 안되네요..

**Comment by daumPostcode** [comment]
@leekyungjin 
안녕하세요~

저희가 IP를 블락하거나 하는것은, 매우 지속적으로 접속하고(사람이 테스트 하면서 접속하는 거랑 빈도수가 다릅니다), 정상적인 이용방식이 아닌 다른 방식으로 데이터를 추출해가려는 목적으로 의심가는 것들만 우선적으로 처리를 합니다.(기본적으로 자동 필터링 됩니다) 이는 이와 같이 사용하는 사람들 때문에 무수히 많은 다른 선량한 이용자 분들이 피해를 받기 때문이죠.

만약 leekyungjin님께서 위와 같이 크롤링을 목적으로 하시는게 아닌이상, 저희 가이드 페이지(http://postcode.map.daum.net/guide)에 있는 내용대로 개발을 하고 계신거라면, 저흰 따로 제제를 가하거나 하지 않습니다.

일단 말씀해 주신 상황이 너무 추상적이라 저희가 원인 파악이 어려운데요, 혹시 저희가 접근 할 수 있는 사이트나 소스가 있으면 일부분이라도 알려주시면 감사하겠습니다.

또한 네트워크가 지연되는 것이 <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script> <-- 이 스크립트 때문인지, 아니면 다른 이유인지 확인이 필요한데요. 이를 위해서라도 일부 소스나 접근할 수 있는 URL이 필요합니다.(URL정보가 훨씬 파악하기 좋긴 합니다.)

**Comment by leekyungjin** [comment]
저 위에 스크립트를 넣으면 페이지가 안뜨더라구요.. 늦게 뜨던지.. 로드가 안되는 현상이 발생합니다. 
저 스크립트 주소만 쳤을때도 잘 안들어가지구요..  다른데서는 잘들어가지는데..  115.94.1.91 아이피가 막힌건 아니겠죠?; 다른소스는 문제없습니다. 평소에도 잘뜨구요.. 간혹가다가 안됩니다. 저스크립트 사용하는 홈페이지 다 그렇습니다.

**Comment by daumPostcode** [comment]
@leekyungjin 

네 안녕하세요~

크롬 개발자 도구로 봤을때나 다른 도구로 확인했을때 postcode.v2.js스크립트의 로딩이 매우 늦게 된다는 것이죠?
전사적으로 비정상적인 접근(크롤링이나 다른 목적을 위한 무분별 접근)의 경우 자동으로 필터링에 걸리게 됩니다.

말씀해 주신 IP의 경우 한번 확인해 보도록 하겠습니다.
시간이 좀 걸리기 때문에, 확인이 되면 다시 댓글로 말씀드리도록 할께요.

감사합니다.

**Comment by daumPostcode** [comment]
@leekyungjin 
안녕하세요~

금일 확인해본결과, API를 제공하는 서버는 따로 특정 ip를 필터링 하거나 제한을 하지 않습니다.
api를 제공하는 서버와, core스크립트를 제공하는 cdn서버 모두 이러한 제한을 하지 않는 것으로 확인이 됩니다.

다른 PC에서는 정상이나, 특정 IP에서만 그런다면, 브라우저에 깔려있는 플러그인 문제일 수도 있고, 공유기 문제 일 수도 있습니다(이전에 PC지도 CS중에 지도API가 불러오지 않던 문제를 해결할때, 위 문제들이었습니다. 다만 정확한 해결방법은 못찼았고, 플러그인을 삭제 또는 중지, 공유기 재부팅 등으로 해결이 되었어요;)
아니면 네트워크 인프라를 담당하는 팀에 dmaps.daum.net 도메인에 접근할때 무슨 제한을 걸어 두었는지도 확인 부탁드립니다;;

속시원한 해결책을 드리지 못해 죄송합니다;
