### ISSUE TITLE
서울 마포구 아현동 711-2 검색 시 영문주소를 못가져옵니다.

### ISSUE THREAD

**Issue by gok809** [daumPostcode/QnA#730]
안녕하세요?

서울 마포구 아현동 711-2 주소 검색 시 영문보기로 하면 영문주소가 잘 노출되어지는데
해당 영문주소를 클릭하면 데이터가 없이 나오고 있습니다. 
위 주소 말고도 몇몇 주소도 그런 거 같아 확인부탁드리겠습니다.

감사합니다.

![우편1](https://user-images.githubusercontent.com/33140398/104142507-48ea1b80-53ff-11eb-8e2f-f00be1d3b3f7.PNG)
![우편2](https://user-images.githubusercontent.com/33140398/104142510-4a1b4880-53ff-11eb-9c12-4f4ffd8ce231.PNG)
![우편3](https://user-images.githubusercontent.com/33140398/104142511-4a1b4880-53ff-11eb-8380-cd7f37470f3a.PNG)

**Comment by daumPostcode** [comment]
@gok809 
안녕하세요~

![image](https://user-images.githubusercontent.com/20675065/104168280-28db4c00-5441-11eb-8c75-b6053ebd8cde.png)

우선 저희는 이용하시는 각 사이트의 구조에 맞게 데이터를 각각 가공해서 내리지 않습니다.
저희 공식 가이드 페이지 postcode.map.daum.net/guide 의 "속성" 부분에 설명되어져 있는 데이터에 따라서만 내리고 있습니다.
그래서 이용하시는 사이트의 개발자 분께서 오류가 없이 조합해서 각 사이트의 형식에 맞게 조정해서 쓰셔야 합니다.

일단 올려주신 내용만 봐서는 데이터가 누락되었는지, 어떤 현상인지 알 수 없습니다.
위 스샷은 제가 알려주신 주소로 검색해서 주소를 클릭했을때 내려가는 데이터 입니다.
(해당 데이터는 공식 가이드 페이지에서 실제 테스트 가능합니다)

한번 확인 부탁드립니다.

**Comment by gok809** [comment]
먼저 답변 감사드립니다.
제가 두서없이 글을 작성했네요. 
속성값을 autoJibunAddressEnglish로 받아오고 있어서 영문주소가 제대로 읽혀지지 않고 있었습니다. 
다른 속성값으로 수정하여 가져오도록 했네요.
