### ISSUE TITLE
모바일에서 Daum주소 서비스 사용시 Scripts may close only the windows that were opened by it 경고

### ISSUE THREAD

**Issue by thswnsdud456** [daumPostcode/QnA#731]
PC 버전에서는 조회한 주소를 선택시 데이터바인딩이 문제없이 잘 됩니다.
하지만 Angular ionic 버전에서는 같은 소스인데,
디버깅 콘솔창에 Scripts may close only the windows that were opened by it 경고가 뜨면서 **팝업이 닫히지 않습니다**.

소스입니다
![image](https://user-images.githubusercontent.com/54301605/104541839-b4cdbd80-5665-11eb-8563-b6aeafa20f76.png)

팝업닫기 기능을 함수로 파놓으신게 있을까요?
어떻게 처리해야 좋을까요 ㅠㅠㅠ
참고로 모바일에서 팝업을 띄워서 Daum주소 서비스를 사용하도록 해놓았습니다

**Comment by thswnsdud456** [comment]
![image](https://user-images.githubusercontent.com/54301605/104545493-89e76780-566d-11eb-82dd-84131c0051a4.png)
잘 되네요!

**Comment by daumPostcode** [comment]
@thswnsdud456 
안녕하세요~
대부분의 모바일 환경에서는 embed를 통한 레이어모드를 사용하시는 것을 추천드립니다.
그 이유는 open함수의 경우 window.open 네이티브 함수를 이용하는데, 이 함수가 open으로 팝업이 떠야하는데 모바일 환경에서는
팝업이 뜨는 것처럼 보이지만 부모페이지를 replace해버리는 경우가 있습니다.
그렇다면 opener와의 모든 연결이 끊어지기에 검색까진 되지만 그 이후가 동작되지 않습니다.

그렇기에 되도록이면 layer모드로 직접 DOM을 핸들링 하시는게 훨씬 편하실 거에요.
이부분 참고해 주세요. 

감사합니다.
