### ISSUE TITLE
<공지사항> 가이드 페이지, 팝업, JS API가 https 프로토콜만 사용되도록 변경됩니다. (배포 완료)

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#732]
안녕하세요.
다음우편번호서비스 담당자입니다.

**2021년 1월 21일 목요일** 부터 우편번호 서비스의 모든 URL 접속은 https 프로토콜을 사용하도록 변경 됩니다.

기존에 가이드 페이지, JS API를 http/https 로 구분하여 서비스 하였으나, 시대적 흐름에 맞추고, 기존의 프록시를 제거하고자 **항상 https 프로토콜로만 접속** 되도록 변경됩니다.

이에따라 JS API의 경우,
기존의 (구)로딩 방식(dmaps, ssl.daumcdn.net)을 이용하는 설명은 가이드 페이지에서 삭제되며, "통합 로딩 방식"에 대한 설명만 유지됩니다.
단, 관리는 통합로딩방식, (구)로딩방식 모두 관리됩니다.

추가로 관리는 두 API모두 되지만, 추후 (구)로딩방식은 종료도 고려하고 있기 때문에, JS API를 (구)로딩방식으로 사용하신다면, 가이드 페이지에 있는 통합로딩방식으로 변경을 추천드립니다.
((구)로딩 방식의 종료 일정은 아직 정해진바 없으며, 추후 일정이 정해지면 다시 공유드리도록 하겠습니다.)

<img width="886" alt="스크린샷 2021-01-18 오후 4 45 47" src="https://user-images.githubusercontent.com/20675065/104886186-a86e9b00-59ac-11eb-87b6-3a60dd37ab35.png">

감사합니다.

**Comment by 76069884** [comment]
현재 사용중에 있는 <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>코드도 21일 이전에는 수정완료 해야 하나요? 아니면 일정 기간(1달 이내)에 수정해도 되나요?

**Comment by daumPostcode** [comment]
@76069884 
안녕하세요~
현재 dmaps서버의 경우 노후화가 심해서, 내부적으로 종료관련해서 고려중입니다.
다만 일정이나 이런건 나온 상태는 아닙니다.
그래서 공지에도 따로 일정을 적진 않았습니다.

다만, 기간만 정해지지 않았을뿐, 추후에 없어질 도메인이기 때문에, 지금 시간이 되신다면 통합로딩 방식으로 이번에 변경해 주시면 좋을 것 같아요.

질문에 답변을 드리자면 21일 이전에, 한달 이내 이런 조건은 없습니다. 그냥 가급적 최대한 빠르게 변경을 해주시면 더 좋습니다.

**Comment by juliusjang** [comment]
위에서 http://dmaps.daum.net 관련 추가 질문인데요..

https 프로토콜 사용시 js 호출 url 인
https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js
위의 url도 추후 사용을 못하는 건가요?

https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js
위의 url로 무조건 변경해야 하나요??

**Comment by 76069884** [comment]
> 위에서 http://dmaps.daum.net 관련 추가 질문인데요..
> 
> https 프로토콜 사용시 js 호출 url 인
> https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js
> 위의 url도 추후 사용을 못하는 건가요?
> 
> https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js
> 위의 url로 무조건 변경해야 하나요??

문의결과 추후 t1외에는 전부 사용불가처리 될 예정이라고 합니다.

**Comment by daumPostcode** [comment]
@juliusjang 
안녕하세요~

아뇨 모두 유지 됩니다.

다만, 추후에(아직 일정은 정해지지 않았습니다) 
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

위 도메인을 제외한 다른 도메인은 종료가 될 예정입니다.

햇갈리시면 안되는게 21일을 기점으로 종료가 되는게 아니에요.
운영은 계속 합니다.

다만 추후 종료가 될 가능성이 크기에,
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js
위 도메인으로 변경이 가능하시다면 미리 변경해 두시는게 좋습니다.

감사합니다.
