### ISSUE TITLE
옥련동 602-35 주소 검색이 안됩니다.

### ISSUE THREAD

**Issue by jaewoncheng** [daumPostcode/QnA#734]
옥련동 602-35 주소 검색이 안되네요.
다음 홈페이지에서는 주소 검색이 되는데요..
확인 부탁드려요.
항상 감사합니다.

**Comment by daumPostcode** [comment]
@jaewoncheng 

안녕하세요

![image](https://user-images.githubusercontent.com/20675065/104988727-276edc80-5a5c-11eb-84f0-08bb2010ced0.png)
위 사진은 행안부 도로명검색시스템의 검색결과입니다.
현재 해당 주소는 도로명주소가 발급되어 있지 않습니다. 저희는 다음홈페이지나 지도서비스와 다르게, 모든 주소를 다루지 않습니다.
"도로명 주소"가 발급된 주소 즉, 5자리 기초구역번호(새우편번호)가 발급된 주소만 다룹니다.

자세한 사항은 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고 부탁드립니다.

감사합니다.
