### ISSUE TITLE
주소 입력 후 검색 기능이 이상합니다.

### ISSUE THREAD

**Issue by btckim** [daumPostcode/QnA#735]
안녕하세요. 

지금까지 주소검색 기능을 정상적으로 사용해왔습니다. 
그런데 금일 14시 10분경 부터 갑자기 특정 주소 키워드를 검색하면 조회기능이 안되는 현상이 있습니다.

분명히 항상 조회하던 주소 키워드(중리) 를 검색하였는데 검색기능이 정확히 작동하지 않는 것 같습니다.
화면이 끔뻑하면서 입력했던 단어가 사라지며 리로드 되는 그러한 현상이 나타나며,
주소가 존재하지 않거나 하면 "검색결과가 없습니다" 등의 문구가 나타나지 않습니다.

참 이상한 것은 같은 단어 "중리" 라는 단어를 조회했을 때
크롬, IE, 웨일 등에서는 정상적으로 조회가 가능하며 현재 사용한 브라우저 엣지에서만 위같은 현상이 나타나고
다른 키워드를 입력하면 조회가 되며 이미 한 번 조회된 상태에서 같은 단어 '중리'를 검색하면 조회가 정상적으로 됩니다.

또 다른 PC의 엣지에서 조회를 하면 정상적으로 됩니다...

혹시 이러한 현상 접수된 부분이 있는지... 확인 가능할까요

**Comment by daumPostcode** [comment]
@btckim 
안녕하세요~
이슈를 지금 확인하네요.;;

해당 이슈는 제가 낮에 전체 메세지로 보내긴 했는데요.
우편번호 서비스 이슈는 아니고, 전사 DNS관련된 장애였습니다.
저희도 저희쪽 서버 이슈가 아니라서 대응이 좀 오래 걸렸습니다.

당시 14시 30분쯤에 조치 완료되었던 것으로 알고 있으며, 지금은 정상동작 하실거에요.

아무튼 불편을 드려 죄송합니다.
감사합니다.
