### ISSUE TITLE
군단위 주소 및 군에 속해 있는 시의 주소 입력 시, "시"필드 입력 안됨

### ISSUE THREAD

**Issue by JoonGo0977** [daumPostcode/QnA#736]
안녕하세요,

서울,부산,인천 등 특별시 및 광역시 주소가 아닌 
경상남도 거제시 장목면 송진포리 산77-3 또는 충청북도 진천군 진천읍 상산로 13
도에 속해 있는 시나 군단위의 주소를 입력 시, 아래 이미지처럼 시 field에 정보가 입력되지 않습니다.
혹시 저희가 사용하고 있는 시스템의 문제인지, 아니면 카카오시스템의 문제인지 확인 해주실 수 있을런지요?
![image](https://user-images.githubusercontent.com/77710729/105123928-62d0e000-5b1c-11eb-9485-ceadc41032df.png)

감사합니다.
고중기

**Comment by daumPostcode** [comment]
@JoonGo0977 
안녕하세요~

우선. 
"충청북도 진천군 진천읍 상산로 13" 이 주소로 검색된 결과를 선택하면 나오는 데이터 입니다. (공식 가이드 페이지에서 확인 가능합니다. 속성 부분에 있음)
![image](https://user-images.githubusercontent.com/20675065/105125073-e2f84500-5b1e-11eb-8fc8-81bcfd11c464.png)

시도 값과 시군구 값이 변수에 잘 셋팅되어 있습니다.
저희 서비스의 경우, oncomplete 함수의 파라미터로 내릴 수 있는 데이터를 모두 내리고 있습니다.
이렇게 받은 데이터를 어떻게 가공해서, 실제 홈페이지에 반영을 할지는, 해당 사이트의 개발자의 몫입니다.
한번 "시" 부분에 들어가는 데이터가 어떤 변수를 이용하는지 그걸 한번 체크해 보시면 좋을 것 같습니다.

추가로
"경상남도 거제시 장목면 송진포리 산77-3" 
위 주소의 경우엔 
![image](https://user-images.githubusercontent.com/20675065/105125169-163ad400-5b1f-11eb-88dd-c0a74dd40ce8.png)
행안부 도로명검색시스템에서 검색이 안되는거 보니 도로명주소가 발급되어 있지 않습니다.
이러한 주소는 저희 서비스에서는 검색이 되지 않습니다. 

감사합니다.
