### ISSUE TITLE
<인트라넷에서의 사용 공지> #676에 대한 문의

### ISSUE THREAD

**Issue by sjhong19** [daumPostcode/QnA#737]
안녕하세요?
공공기관 정보화담당자입니다.

저희 기관은 보안정책으로 인해 VPN을 사용 중인데, https://t1.daumcdn.net 해당 도메인의 서버가 CDN 서버인 것으로 알고있습니다.
저희 기관의 VPN 장비가 IP를 필터링 하는 형태에다 필터링 정책을 블랙리스트로 운영 중에 있습니다.
이에 따라 VPN 이용시 해당 우편번호 서비스를 호출할 수 없는 상태여서, 필터링이 가능하도록 해당 CDN 서버의 VIP나 설정된 고정IP 정보를 알 수 있을까 하여 문의드립니다.
바쁘시겠지만 확인부탁드리며, 항상 좋은 서비스 제공을 위해 노력해주시는 점 감사드립니다.

**Comment by daumPostcode** [comment]
@sjhong19 
안녕하세요~

우선 저희 서비스는 t1.daumcdn.net 외에도, 다수의 도메인을 사용하며, 인트라넷에서 사용시에는 t1.daumcdn.net외에도 다른 도메인의 허용도 필요합니다.
그리고 무엇보다 현재 저희 우편번호 서비스는 내부망에서의 사용을 공식적으로 지원해 드리진 않습니다.
가끔 요청에 의해 도메인 리스트를 제공하는 것 외에는 그 이상에 대해서는 제공해 드리기 어렵습니다.

내부망에서 사용하신 다면, 저희 API보다는 행안부에서 제공하는 API나, 저희랑은 시스템이 약간 다르지만 비슷하게 제공하고 있는 Postcodify를 이용하시는게 어떠실까 합니다.

만족스런 답변을 드리지 못해 죄송합니다.

감사합니다.

**Comment by sjhong19** [comment]
빠른답변 주셔서 매우 감사드립니다.

혹시나 도메인 제공 외에 IP 지원이 가능할까 하여 문의드렸는데, 역시 어려운 부분이었네요
안내해 주신 방향처럼 다른 제공자 서비스를 활용하는 방향으로 내부적으로 정리해야할 것 같습니다.

만족스럽다기보다는 원하는 답변은 아니지만 친절히 가이드해주셔서 감사합니다.
