### ISSUE TITLE
주소 검색 시 문제

### ISSUE THREAD

**Issue by ss0098** [daumPostcode/QnA#738]
![에러화면](https://user-images.githubusercontent.com/47581352/105309134-3bebda00-5c00-11eb-976c-fae270b7391a.jpg)

주소 검색 시 원하시는 페이지를 찾을 수 없다고 그러는데
원인이 뭘까요?  

방금 1월 21일자부터 https관련 올리신 이슈를 읽어 봤는데 이와 관련된 문제인거 같기도 한데
그렇다면 script src를 https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js로  수정만한다면
기존 소스에서도 이상없이 돌아가는게 맞나요?

**Comment by Jhuni0123** [comment]
@ss0098 님 저도 같은 문제 겪었었는데 script src 만 변경해서 정상동작 하고 있습니다.

**Comment by daumPostcode** [comment]
@ss0098 
네 안녕하세요~

혹시 spi.maps.daum.net 도메인을 사용하실까요?
해당 도메인은 예~~전부터 캐시관련 이슈가 있어서 가이드페이지에서 내려간지가 좀 됬습니다;;
아직 해당 도메인의 스크립트를 이용하신다면
말씀하신 t1.daumcdn.net으로 변경하시면 문제없이 동작하실거에요.

**Comment by ss0098** [comment]
> @ss0098
> 네 안녕하세요~
> 
> 혹시 spi.maps.daum.net 도메인을 사용하실까요?
> 해당 도메인은 예~~전부터 캐시관련 이슈가 있어서 가이드페이지에서 내려간지가 좀 됬습니다;;
> 아직 해당 도메인의 스크립트를 이용하신다면
> 말씀하신 t1.daumcdn.net으로 변경하시면 문제없이 동작하실거에요.

**Comment by ss0098** [comment]
@daumPostcode  
답변 감사합니다
그렇다면 ssl.daumcdn.net은 지금은 정상작동은 하지만 t1.daumcdn.net으로 변경을 권장하시는 건가요?

**Comment by daumPostcode** [comment]
@ss0098 
네. 금일 패치로 인해 가이드페이지에서 ssl.daumcdn.net도 빠졌습니다.
리소스 자체가 삭제된건 아니지만, 저희가 앞으로 해당 도메인도 삭제할 계획이 있기 때문에 미리 뺀것이거든요.
ssl.daumcdn.net은 서버쪽 이슈가 좀 있습니다.

그렇기에 t1.daumcdn.net으로 해주시는걸 매우 권장합니다.

**Comment by appkorean** [comment]
![image](https://user-images.githubusercontent.com/51770088/105324496-db17ce00-5c0e-11eb-8a08-280d3c96e4c3.png)
PC에서는 문제가 없는데, 모바일디바이스(특히 아이폰)에서
"https://"를 이용하는 경우에만 위와같은 오류가 있습니다.
너무 급한데, 어떻게 해결방안이 없는지요?

**Comment by appkorean** [comment]
https://spi.maps.daum.net/search?region_name=서울특별시+마포구+연남동+&cq=서울특별시+마포구+연남동+&cpage=1&origin=https%3A%2F%2Fwww.realbarrier.co.kr&isp=N&isgr=N&isgj=N&ongr=&ongj=&regionid=&regionname=&roadcode=&roadname=&banner=on&ubl=&indaum=off&vt=layer&am=on&ani=off&mode=transmit&sd=on&fi=&fc=&hmb=off&heb=off&asea=off&smh=off&zo=&theme=&bit=&sit=&sgit=&sbit=&pit=&mit=&lcit=&plrg=&plrgt=1.5&us=on&msi=5&ahs=off&whas=275&zn=Y&sm=on&CWinWidth=316&sptype=&sporgq=&fullpath=%2Fmw%2Feventview.asp%3FUid%3D1232&a51=off


사파리 인스펙트 해본 결과인데,
아이폰에서 https://주소를 이용한 경우, 결과를 누르면 위와같은 링크를 타게 되는데,
이때 not found 에러가 있습니다.

**Comment by daumPostcode** [comment]
@appkorean 

이용하시는 JS API의 최신화를 요청드립니다.
최신 도메인은 https://postcode.map.daum.net/guide 가이드 페이지에 들어가보시면 딱 1개만 존재합니다.
기본 사용법을 참고하시면 되세요. 이걸로 변경하시면 해당 현상 모두 사라지실 거에요.
`https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js`

현재 spi.maps.daum.net은... 몇년전부터 가이드페이지에서 빠진 도메인이고, 변경 요청을 몇번 드리긴 했습니다.
다만 API특성상 한번 이용하면 변경하시는 분들이 적어서;; 아직까지 유지가 되는 것인데요.
이번에 최신(이라긴 하지만 1년 6개월 전부터 운영됨) 버전으로 변경 부탁드립니다.

해당 도메인은 항상 캐싱 문제를 내포하고 있기 때문에 그래서 바꾼것이거든요..
아무튼 최신 도메인으로 변경 부탁드립니다.

**Comment by appkorean** [comment]
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js 를 이용하고 있습니다.

> @appkorean
> 
> 이용하시는 JS API의 최신화를 요청드립니다.
> 최신 도메인은 https://postcode.map.daum.net/guide 가이드 페이지에 들어가보시면 딱 1개만 존재합니다.
> 기본 사용법을 참고하시면 되세요. 이걸로 변경하시면 해당 현상 모두 사라지실 거에요.
> `https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js`
> 
> 현재 spi.maps.daum.net은... 몇년전부터 가이드페이지에서 빠진 도메인이고, 변경 요청을 몇번 드리긴 했습니다.
> 다만 API특성상 한번 이용하면 변경하시는 분들이 적어서;; 아직까지 유지가 되는 것인데요.
> 이번에 최신(이라긴 하지만 1년 6개월 전부터 운영됨) 버전으로 변경 부탁드립니다.
> 
> spi.maps.daum.net 도메인은 항상 캐싱 문제를 내포하고 있기 때문에 그래서 바꾼것이거든요..
> 아무튼 최신 도메인으로 변경 부탁드립니다.

**Comment by appkorean** [comment]
![image](https://user-images.githubusercontent.com/51770088/105327244-018b3880-5c12-11eb-9dc3-698c9dbe8281.png)

**Comment by daumPostcode** [comment]
@Jhuni0123 
음.. 처음 들어온 이슈인데 음...
해당 파일은 금일 14시에 최신화가 됬고, 최신화가 되면 올려주신 spi.maps.daum.net이라는 도메인 자체를 내부적으로 사용하질 않습니다.
아예 빠진것이라 보시면 되요.
그렇다는건 해당 파일이 iOS에서 뭔가 캐싱이 되고 있다는 것으로 보입니다.

웹뷰라면 웹뷰에서 캐시를 처리할 수 있는 방법이나 이런게 있는지 확인 부탁드립니다.

우선 해당 도메인은 5분주기로 캐싱이 플러싱이 되나, 현재 강제로 플러싱 처리를 한번더 했습니다.
한번 확인 부탁드립니다.
