### ISSUE TITLE
주소 > 우편번호 검색 시 오류

### ISSUE THREAD

**Issue by hugefabio** [daumPostcode/QnA#739]
안녕하세요,
[홈페이지](https://www.beanbrothers.co.kr/)에서 어제까지는 잘 작동되다가 오늘부터 주소지 > 우편번호 검색 시 오류창이 뜹니다.

해결 방법 문의드립니다.
감사합니다.

![스크린샷 2021-01-22 오전 10 08 37](https://user-images.githubusercontent.com/77816670/105433266-a5212b00-5c9c-11eb-9d3d-c66f2b15d8cd.png)

**Comment by JYS-git** [comment]
여기에 덧붙여 설명하겠습니다 현재저도 같은증상이며 해당증상이 나오는브라우저는 현재 두종류입니다.
1.IE
2.크롬(일부유저만)

IE같은경우는 신뢰할수있는사이트에 서비스중인 사이트를 등록하면 해결되나
크롬의경우 저오류가나면 어떻게 손쓸방법이없습니다 디버깅해보니 404에러가뜹니다
밑에 오류나는 url정보 첨부해드립니다

https://spi.maps.daum.net/search?region_name=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%95%95%EA%B5%AC%EC%A0%95%EB%8F%99+&cq=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%95%95%EA%B5%AC%EC%A0%95%EB%8F%99+&cpage=1&origin=https%3A%2F%2Fedunet.hanuribook.com&isp=N&isgr=N&isgj=N&ongr=&ongj=&regionid=&regionname=&roadcode=&roadname=&banner=on&ubl=on&indaum=off&vt=popup&am=on&ani=off&mode=transmit&sd=on&fi=on&fc=on&hmb=off&heb=off&asea=off&smh=off&zo=on&theme=&bit=&sit=&sgit=&sbit=&pit=&mit=&lcit=&plrg=&plrgt=1.5&us=on&msi=10&ahs=off&whas=500&zn=Y&sm=on&CWinWidth=500&sptype=&sporgq=&fullpath=%2Fmember%2Finsert_next&a51=off

**Comment by JYS-git** [comment]
- 바로밑에글에 똑같은내용이 있네요 다음 api 스크립트 src를 spi.maps.daum.net에서 t1.daumcdn.net 바꾸라고하네요 ㅎㅎ
