### ISSUE TITLE
도로명 주소 일부가 깨집니다. 

### ISSUE THREAD

**Issue by cocoma123** [daumPostcode/QnA#74]
"대구 달서구 장기로 115"

검색을 하면 도로명 텍스트 일부가 깨집니다.

행자부에서 검색을 하면 도로명 주소가 "대구광역시 달서구 장기로 115 (성당동, 성당동 더 샾)"

다 노출되나 다음API에서 검색을 하면 "대구 달서구 장기로 115 (성당동 더 )" 이런식으로 글씨가

깨집니다.

**Comment by daumPostcode** [comment]
@cocoma123 
넵~ 안녕하세요~

우선 답변이 늦어 죄송합니다;;
해당 오류는 데이터 전처리 문제 같습니다. 조속히 해당 부서에 알려 수정 하도록 하겠습니다.

제보 감사드립니다.

**Comment by daumPostcode** [comment]
@cocoma123 
안녕하세요~

해당 주소는 금요일 오후에 수정조치 하였습니다. 제보 감사드립니다.
이외 다른 주소또한 동일한 현상이 있을 것 같아. 일괄 조치 중입니다.

다시 한번 제보 감사드립니다

즐거운 하루 되세요~
