### ISSUE TITLE
주소 검색 api 서비스 사용제한

### ISSUE THREAD

**Issue by cs90286** [daumPostcode/QnA#740]
안녕하세요..
다음 주소검색 api 공지사항을 읽어보니 다음과 같은 내용이 있어 문의합니다.

2021년 3월 31일 : API 사용 제한(호출은 가능하나 이용이 중지 됩니다.)

올해 3월31일 이후에는 서비스 제공이 아예 안되는건가요?
기존 서비스 중인 경우에는 어떻게 해야 하는지요?

**Comment by daumPostcode** [comment]
@cs90286 
안녕하세요~

해당 공지사항에 들어있는 가이드페이지 링크와, 이전공지사항 부분을 모두 참고해 보시면 어떤 내용인지 아실 수 있습니다.
무조건 사용제한을 거는게 아닙니다.
"허용하지 않는 파라미터를 사용한 경우"에 한해서만 제한을 겁니다.

즉, 정상적으로 사용하신 분들의 경우엔 아무런 제약사항이 없습니다.
가이드 페이지를 참고하시기 바랍니다.

감사합니다.
