### ISSUE TITLE
IE8 에서의 조회 불가.

### ISSUE THREAD

**Issue by dlscjf119** [daumPostcode/QnA#741]
안녕하세요

1/21 일 패치 이후 주소API 가 페이지 없음으로 떠서
가이드대로 t1 으로 시작하는 src 로 변경 하였는데도
IE8 브라우저를 쓰는 ,  XP에서 주소API 가 동작 하고있지 않습니다.

XP 는 서비스가 중단 된 것인지요?

**Comment by daumPostcode** [comment]
@dlscjf119 
안녕하세요~

어떤 오류가 뜨는지 IE8에도 개발자 도구가 있는데 오류 메세지를 보여주시면 좋을 것 같습니다.
오류 메세지와 어떻게 동작이 안되는지 자세한 상황 설명 부탁드립니다 (스크린샷 필요)
현재 XP는 마이크로 소프트가 공식적으로 지원을 중단한 OS고, IE8또한 지원을 중단한 OS라 테스트 환경을 저희가 구성하기가 좀 어려운데요.
자세한 상황 설명 해주시면 최대한 구해서 테스트 해보도록 하겠습니다.

실제 저번 업데이트로 인해 코드가 기능적으로 많이 변하거나 하진 않았습니다. 도메인 통일 외에는 변한게 없는데;
아무튼 한번 자세히 알려주시면 좋을 것 같습니다.

**Comment by dlscjf119** [comment]
> @dlscjf119
> 안녕하세요~
> 
> 어떤 오류가 뜨는지 IE8에도 개발자 도구가 있는데 오류 메세지를 보여주시면 좋을 것 같습니다.
> 오류 메세지와 어떻게 동작이 안되는지 자세한 상황 설명 부탁드립니다 (스크린샷 필요)
> 현재 XP는 마이크로 소프트가 공식적으로 지원을 중단한 OS고, IE8또한 지원을 중단한 OS라 테스트 환경을 저희가 구성하기가 좀 어려운데요.
> 자세한 상황 설명 해주시면 최대한 구해서 테스트 해보도록 하겠습니다.
> 
> 실제 저번 업데이트로 인해 코드가 기능적으로 많이 변하거나 하진 않았습니다. 도메인 통일 외에는 변한게 없는데;
> 아무튼 한번 자세히 알려주시면 좋을 것 같습니다.






증상 XP 에서 API 호출시 아래와 같이 접속이 안되는 증상 입니다.
브라우져에서 https 를 지원안해서 그러는 것 같은데, http 는 이제 중단인건지요?

![Uploading 이미지 032.jpg…]()

**Comment by daumPostcode** [comment]
@dlscjf119 
네~ 안녕하세요~

스크립트 자체는 http 프로토콜로 접근 가능합니다.
http://t1.daumcdn.net/~~~ 이렇게 쓰면 되요.

다만 내부적으로는 모든 통신은 https를 사용합니다.
추가로 올려주신 이미지가 첨부가 제대로 안되서,, 보이지가 않습니다;;

**Comment by dlscjf119** [comment]
> @dlscjf119
> 네~ 안녕하세요~
> 
> 스크립트 자체는 http 프로토콜로 접근 가능합니다.
> http://t1.daumcdn.net/~~~ 이렇게 쓰면 되요.
> 
> 다만 내부적으로는 모든 통신은 https를 사용합니다.
> 추가로 올려주신 이미지가 첨부가 제대로 안되서,, 보이지가 않습니다;;

스크립트는 http 로 사용 하더라도 js 내부 에는 https 로 되어 있어서 XP에서는 아래와 같이 에러가 발생 합니다.

이미지 재첨부드립니다.

![error](https://user-images.githubusercontent.com/77942943/105666196-13275580-5f1c-11eb-8584-3698f5185e55.jpg)

**Comment by daumPostcode** [comment]
@dlscjf119 
네 사진 감사드립니다.
인터넷 문제거나, DNS오류가 아닌이상, 추가정보에 있는 도구-인터넷옵션에서 설정을 변경해 보시는게 어떠실까 합니다.
https 통신은 보안이슈 때문에 요즘은 기본중에 기본으로 가는 프로토콜이라, 이를 제거하긴 어렵습니다.
한번 설정 해보시면 연락 주세요.
감사합니다.

**Comment by dlscjf119** [comment]
> @dlscjf119
> 네 사진 감사드립니다.
> 인터넷 문제거나, DNS오류가 아닌이상, 추가정보에 있는 도구-인터넷옵션에서 설정을 변경해 보시는게 어떠실까 합니다.
> https 통신은 보안이슈 때문에 요즘은 기본중에 기본으로 가는 프로토콜이라, 이를 제거하긴 어렵습니다.
> 한번 설정 해보시면 연락 주세요.
> 감사합니다.

위 가이드데로 전부 하여도 XP IE8 환경에서는 주소검색이 불가능 합니다.
한번 XP 환경에서 해 보시면 명확히 확인이 되실것 같습니다.

**Comment by daumPostcode** [comment]
@dlscjf119 
네 알겠습니다.
회사에서는 해당 환경 재현이 불가능하기에, 제가 퇴근해서 한번 확인해 보도록 할께요.
해당 환경을 구축에 필요한 IOS파일도 요즘은 구하기가 어려워서 시간이 좀 걸릴 수 있습니다.

추가로 정확한 환경 기재 부탁드립니다.
XP는 일반버전이 있고 서비스팩 버전이 있습니다.
이와 관련해서 정확한 버전 부탁드리고,
IE8도 버전값 부탁드립니다.
감사합니다.

**Comment by dlscjf119** [comment]
> @dlscjf119
> 네 알겠습니다.
> 회사에서는 해당 환경 재현이 불가능하기에, 제가 퇴근해서 한번 확인해 보도록 할께요.
> 해당 환경을 구축에 필요한 IOS파일도 요즘은 구하기가 어려워서 시간이 좀 걸릴 수 있습니다.
> 
> 추가로 정확한 환경 기재 부탁드립니다.
> XP는 일반버전이 있고 서비스팩 버전이 있습니다.
> 이와 관련해서 정확한 버전 부탁드리고,
> IE8도 버전값 부탁드립니다.
> 감사합니다.

환경 첨부 드립니다.
아래 스크린샷 참고 부탁드립니다
감사합니다.

![이미지 032](https://user-images.githubusercontent.com/77942943/105668906-9ac39300-5f21-11eb-9ef3-d8e80178fa52.jpg)
![이미지 034](https://user-images.githubusercontent.com/77942943/105668909-9c8d5680-5f21-11eb-80aa-b7b29df400a4.jpg)

**Comment by daumPostcode** [comment]
@dlscjf119 
Windows Embeded라는 버전이네요? 
일단 테스트 하기전에; 해당 OS를 업그레이드 할 수 있는 상황은 안되시나요?

**Comment by dlscjf119** [comment]
> @dlscjf119
> Windows Embeded라는 버전이네요?
> 일단 테스트 하기전에; 해당 OS를 업그레이드 할 수 있는 상황은 안되시나요?

네.. POS 시스템에서 API를 쓰고있는데,  업그레이드를 당장 진행 할수있는 여건이 안됩니다.

**Comment by daumPostcode** [comment]
@dlscjf119 

네 제가 좀 확인을 해보았는데요.
해당 OS에서 저희 서버에 적용된 TLS 1.2 버전 인증서를 지원하지 않는 것으로 확인됩니다.
저희가 이 인증서의 버전을 낮출 수는 없습니다. 그럼 대다수 모든 사이트에서 위험경고가 뜨거든요.

찾아보니 마이크로 소프트에서 
https://support.microsoft.com/en-us/topic/update-to-add-support-for-tls-1-1-and-tls-1-2-in-windows-server-2008-sp2-windows-embedded-posready-2009-and-windows-embedded-standard-2009-b6ab553a-fa8f-3f5e-287c-e752eb3ce5f4

해당 OS에서 TLS 1.2를 지원하게 하는 방법을 업데이트 한것 같은데요. 이 방법으로 한번 시도해 보시는게 어떠실까 합니다.
http://www.catalog.update.microsoft.com/Search.aspx?q=KB4019276
여기서 해당 OS에 맞는 파일 다운로드 후에,

첫번째 링크에서 추가정보란에 있는 설명처럼 레지스트리키를 변경해 주셔야 합니다.
한번 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@dlscjf119 
위 내용 한번 확인해 주시고,
처리가 어려울시, 서버개발자분과 논의해서, HTTP 프로토콜을 지원할 수 있게 수정 배포를 하도록 하겠습니다.
배포 일정이 정해지면 말씀드리도록 하겠습니다.
감사합니다.

**Comment by dlscjf119** [comment]
> @dlscjf119
> 위 내용 한번 확인해 주시고,
> 처리가 어려울시, 서버개발자분과 논의해서, HTTP 프로토콜을 지원할 수 있게 수정 배포를 하도록 하겠습니다.
> 배포 일정이 정해지면 말씀드리도록 하겠습니다.
> 감사합니다.



위 패치적용후, 레지값수정 해서 https 프로토콜 접속은 되나, 주소검색 후 값을 받는부분에서 원활히 받아지지가 않습니다.
개선이 된다면 공지나  relpy 부탁드리겠습니다.

감사합니다.

**Comment by daumPostcode** [comment]
@dlscjf119 

넵 알겠습니다. 수정 후에 말씀드리도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@dlscjf119 
안녕하세요~
금일 테스트 완료하고, 내일 오후 쯤에 서버 배포가 가능할 것 같습니다.
JS API도메인은 

<script src="http://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>

위 주소를 사용하시면 됩니다. 

배포 후에 다시 추가 댓글 드리도록 하겠습니다.
감사합니다.

**Comment by dlscjf119** [comment]
> @dlscjf119
> 안녕하세요~
> 금일 테스트 완료하고, 내일(28일) 오후 쯤에 서버 배포가 가능할 것 같습니다.
> JS API도메인은
> 
> <script src="http://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
> 위 주소를 사용하시면 됩니다.
> 
> 배포 후에 다시 추가 댓글 드리도록 하겠습니다.
> 감사합니다.

넵 기다리고 있겠습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@dlscjf119 
금일 1월 28일 14시에 배포 되었습니다.
한번 확인 부탁드립니다.

감사합니다.

**Comment by dlscjf119** [comment]
@daumPostcode 
캐시삭제 이후 정상적으로 작동 됩니다.
해당 js 는 계속 유지 되는 거죠?

**Comment by daumPostcode** [comment]
@dlscjf119 
네 공식 가이드페이지에 있는 URL만 사용하신다면 계속 유지되십니다.
공식 가이드 페이지에 있는 URL이 제가 위에 댓글에서 알려드린 것과 같은거에요 ㅎㅎ

넵 감사합니다.

다만 현재 한가지 참고하셔야 할것은 IE6,7,8,9,10의 경우엔 Legacy 로 포함된 브라우저라서,
개편할 일은 적지만, 추후에는 UI적으로 특정 부분이 깨지거나 하는 것과 같은 오류가 뜰 수 있습니다.
최대한 잡아 보겠지만, 불가능한 경우도 있기에 이부분은 양해 부탁드립니다.

**Comment by dlscjf119** [comment]
@daumPostcode 지원 감사합니다.
