### ISSUE TITLE
일부주소 클릭시 문제

### ISSUE THREAD

**Issue by rosezone** [daumPostcode/QnA#742]
우편번호 서비스에서 jibunAddress 값만 받아 쓰고있습니다.
일부 주소가 클릭시 해당 지번주소 값을 못가져 오고 있어서 문의 드립니다.
예) 인천 영종도 검색 > [도로명]인천 중구 신도시남로141번길 6 클릭 > jibunAddress값 못받아옴
      인천 영종도 검색 > [지번]인천 중구 운서동 2797-1 클릭 > jibunAddress값 받아옴

**Comment by daumPostcode** [comment]
@rosezone 
안녕하세요~

도로명주소와 지번주소가 1:N인 경우 발생할 수 있습니다.
저희 공식가이드 페이지의 autoJibunAddress 변수에 대한 설명이 있으니 이부분 참고 부탁드립니다.
저희는 검색시 화면에 보이는 정보 중에 내리지 않는 정보는 없습니다.

데이터를 조합해서 사용하는 권한은 저희 API를 이용하시는 개발자분의 몫으로, 가이드 페이지 참고하시어 수정 부탁드립니다.

![image](https://user-images.githubusercontent.com/20675065/105668237-466be380-5f20-11eb-8aab-c801aa061d90.png)

가이드 페이지는 https://postcode.map.daum.net/guide
입니다.
