### ISSUE TITLE
js 파일문의 

### ISSUE THREAD

**Issue by jloveonly** [daumPostcode/QnA#743]
최근에  주소 검색이 안되고  페이지 없음 화면이 노출되는 경우가 있었습니다 

다시 하니 기능이 잘되기도 했고요 혹시 아래 js url 을 사용해서 그런건지요? 

https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js

**Comment by daumPostcode** [comment]
@jloveonly 
네 안녕하세요~
네 맞습니다.
해당 spi.maps.daum.net 도메인에 연결된 JS API는 2017년 1월 경부터 가이드 페이지에서 삭제된 API이고,
당시에 변경요청도 드리긴 했습니다. 다만 서비스 특성상 한번 적용하고 나면 변경을 안하시는 분들이 많아서 이번에 이슈가 발생된 것인데요.
해당 도메인은 캐시정책이 10년입니다.
그렇기에 브라우저가 해당 파일을 한번 받으면, 브라우저의 캐시를 삭제하지 않는 이상, 재 다운로드를 받질 않습니다.
그래서 API스크립트와, 실제 검색페이지와 데이터 불일치가 발생해서 야기된 현상입니다.
예전부터 이현상이 너무 심해서, 2017년도부터 가이드 페이지에서 제거된 이유입니다.

아무튼 공식 가이드 페이지를 참고해서 최신으로 변경해 주시면 해당 이슈 모두 해결됩니다.
추후 기능적인 변경이나, 버그 픽스시에도, 캐시때문에 제대로 적용이 안될 가능성이 있으니 이참에 변경해 주시기 바랍니다.
아직 종료일정은 없으나 추후 종료도 예정중이니 변경 해주시면 감사하겠습니다.

그리고 지금은 다시 되는게, 검색 팝업쪽에 제가 방어코드를 넣어둬서 그러한 것으로, 지금 된다고 놔두시지 마시고, 최신파일로 변경부탁드립니다.
감사합니다.
