### ISSUE TITLE
daum postcode service

### ISSUE THREAD

**Issue by enrike79** [daumPostcode/QnA#744]
경기도 부천시 심곡동 356-5
지번주소로는 검색이 안되고 도로명 주소로는 검색이 됩니다. 
![image](https://user-images.githubusercontent.com/78061757/105935071-abe0e100-6094-11eb-823e-7d92b1801e8d.png)

![image](https://user-images.githubusercontent.com/78061757/105935134-c87d1900-6094-11eb-915b-36893f5e3336.png)
지번주소로도 검색이 되어야 할 것 같은데 확인바랍니다.

**Comment by daumPostcode** [comment]
@enrike79 
넵 안녕하세요~

해당 이슈 주소 및 검색엔진 담당자분께 전달하도록 하겠습니다.
제보해 주셔서 감사드립니다.

**Comment by daumPostcode** [comment]
@enrike79 
안녕하세요~
해당 이슈는 최근에 검색엔진 개편에 따른 버그로 보이며, 현재 우선적으로 질문 주신 것과 비슷한 케이스들이 정상 동작하도록 처리되었습니다.
좀더 수정할게 남았지만 이부분의 경우 좀 더 검토후 빠르게 수정 하도록 하겠습니다.
감사합니다.
