### ISSUE TITLE
부산광역시 연제구 연산동 579-22 지번주소 검색이 되지 않습니다.

### ISSUE THREAD

**Issue by mw-sh** [daumPostcode/QnA#745]
[도로명주소 사이트](https://www.juso.go.kr/support/AddressMainSearch.do?searchKeyword=%EC%97%B0%EC%A0%9C%EA%B5%AC+%EC%97%B0%EC%82%B0%EB%8F%99+579-22&dsgubuntext=&dscity1text=&dscounty1text=&dsemd1text=&dsri1text=&dssan1text=&dsrd_nm1text=)에서 검색시 아래와 같이 검색이 되고 있는데

![image](https://user-images.githubusercontent.com/64456716/106098504-7f07f900-617c-11eb-889b-9b193a602e6c.png)

다음 우편번호 서비스에서는 검색이 되고 있지 않습니다.

확인후 조치 부탁드리겠습니다 :-)

![image](https://user-images.githubusercontent.com/64456716/106098583-9e9f2180-617c-11eb-83df-6d100a49b41b.png)

**Comment by daumPostcode** [comment]
@mw-sh 
네! 안녕하세요~

바로 아래에 있는 주소 관련 CS와 동일한 현상 같습니다.
현재 해당 검색엔진 담당자분께서 확인중에 계십니다. 최대한 빠르게 수정될 수 있게 하겠습니다.
제보 감사드립니다.

**Comment by daumPostcode** [comment]
@mw-sh 
안녕하세요~
해당 이슈는 최근에 검색엔진 개편에 따른 버그로 보이며, 현재 우선적으로 질문 주신 것과 비슷한 케이스들이 정상 동작하도록 처리되었습니다.
좀더 수정할게 남았지만 이부분의 경우 좀 더 검토후 빠르게 수정 하도록 하겠습니다.
감사합니다.

**Comment by mw-sh** [comment]
😄 답변감사합니다. 👍
