### ISSUE TITLE
euc-kr 문제

### ISSUE THREAD

**Issue by ungtaeng** [daumPostcode/QnA#746]
어제까지 되다가 오늘날짜로 주소찾기 누르면 경고창이 뜨면서 한글도 다 깨지면서 보여주던대 현재 서비스하는 페이지 euc-kr 페이지입니다 utf-8만 지원 하는건가요?

**Comment by daumPostcode** [comment]
@ungtaeng 
네 안녕하세요~
우편번호 서비스는 utf-8 만 지원합니다.
euc-kr은 현재로써는 지원해 드리기 어려운점 양해 부탁드립니다.
