### ISSUE TITLE
Window XP  서비스 

### ISSUE THREAD

**Issue by hkib** [daumPostcode/QnA#747]
아래의 #741 번 이슈와 동일합니다.

 XP 환경에서 28일에 업데이트해주신 아래의 스크립트로 불러와도 작동하지 않습니다. 
<script src="http://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" type="text/javascript"></script>
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" type="text/javascript"></script>

![image](https://user-images.githubusercontent.com/78139259/106108338-74a12b80-618b-11eb-9b4d-dc32fffc1188.png)
![image](https://user-images.githubusercontent.com/78139259/106108378-8256b100-618b-11eb-94d8-2092b71b7671.png)

**Comment by daumPostcode** [comment]
@hkib 
안녕하세요.
우선 브라우저의 캐시를 삭제해 주시기 바랍니다.
IE8의 경우 너무 구버전 브라우저라, 브라우저의 특성이 현재 모던 브라우저와 많이 다릅니다.
아무튼 브라우저의 초기화나 캐시를 삭제를 한번 해보시기 바랍니다.

그리고 부모페이지가 http환경일 경우
<script src="http://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" type="text/javascript"></script>
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" type="text/javascript"></script>

이 두가지 모두 동일하게 동작합니다.
감사합니다.
