### ISSUE TITLE
vuejs 에서 다음 주소 api 호출시 화면 안뜨는 현상

### ISSUE THREAD

**Issue by jws3104** [daumPostcode/QnA#748]
안녕하세요..
vuejs-daum-postcode 를 사용해서 앱에서 다음주소 api를 잘 사용하고 있었습니다만..
오늘 [2021년 1월 28일 : error 로그 + alert(경고창)으로 가이드 강화]라는 이슈사항 때문인지 갑자기 앱에서 다음주소 창을 호출하지 못하는 현상이 있습니다.

호출시 로그를 보면 아래와 같이 호출을 하는데 로컬에서 호출하는것처럼 주소가 나옵니다.
/postcode/api/core/210128/1611810131757/210128.js

http://t1.daumcdn.net/postcode/api/core/210128/1611810131757/210128.js
이렇게 접속을 해야 정상적으로 화면이 호출이 되는것 같은데 갑작기 안되는 이유를 잘 모르겠습니다.

vue 컴포넌트에서 
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js?autoload=false
로 주소창을 호출하는데, 같은 증상이 있으신분 없으신지요??
조건 부탁드립니다.

**Comment by daumPostcode** [comment]
@jws3104 

안녕하세요~
https://github.com/daumPostcode/QnA/issues/724
위 공지 확인 부탁드립니다.

우선 현재 제가 사용하시는 
<script src="//ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>
이 JS 파일로 테스트를 했을 경우 정상적으로 실행이 됨이 확인이 됩니다.
내부에서 왜 앞쪽 도메인 부분을 잘라버리는지는 아직 어떤 이유인지는 확인이 되지 않습니다.

만약 가능하시다면, 공식 가이드 페이지에 있는 통합로딩방식으로 변경을 해보시는게 어떠실까 합니다.
