### ISSUE TITLE
샘플소스만 넣어도 에러출력

### ISSUE THREAD

**Issue by jiDoneKeun** [daumPostcode/QnA#749]
다음과 같은 오류가 출력되어서 말씀하신 공지사항을 확인 후 소스를 샘플소스로만 바꿔도 다음과 같은 에러가 발생합니다.
ex) 소스(다른소스는 그대로 존재합니다.)
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
new daum.Postcode({
	        oncomplete: function(data) {
	            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.
	            // 예제를 참고하여 다양한 활용법을 확인해 보세요.
	        }
	    }).open();

ex) 에러 
URL : https://user-images.githubusercontent.com/24326486/106116682-88ea2600-6195-11eb-87a4-b8a22d41f88e.PNG

[우편번호 서비스] API 로딩시 허용되지 않은 파라미터가 감지되었습니다. 서비스 이용에 제약이 생길 수 있으니, 관리자분께서는 확인 부탁드립니다.
자세한 사항은 가이드페이지( https://postcode.map.daum.net/guide )의 기본 사용법을 참고해주세요.
postcode.v2.js?_=1611825150442:1 

확인부탁드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
안녕하세요~

공지사항 https://github.com/daumPostcode/QnA/issues/724
참고 부탁드립니다.

저흰 JS API를 로딩할때 url 뒷부분에 특정 파라미터 붙히는걸 허용하지 않습니다.
현재의 통합로딩 방식의 스크립트에는 허용된 파라미터가 없습니다.

만약 적어주신 것처럼 ?_=1611825150442:1 이라는 파라미터가 붙어 있으면
당연히 위 경고가 뜨게 됩니다.

현재 작년부터 이러한 불필요한 파라미터를 없애기 위해서 여러 공지 및 메세지를 드린 상태입니다.
저희 서비스는 api key를 통해 사용자를 특정하는 서비스가 아니기 때문에, 깃허브 공지, 공식 가이드 페이지, 카카오톡플친 으로 공지를 하고 있는점 참고 부탁드립니다.

자세한 사항은 가이드 페이지 확인 부탁드립니다.
