### ISSUE TITLE
 도로명:지번이 1:N일때 도로명 선택이 되도록 하고 싶어요

### ISSUE THREAD

**Issue by holyajj** [daumPostcode/QnA#75]
아래의 코드가 제가 사용하는 코드입니다
도로명:지번이 1:N 일때 현재는  지번의 더보기를 클릭후 지번을 한번 더 클릭해야 창이 닫힙니다
여기서 처음부터 도로명만 클릭하면 값이 전달되고 창이 닫히게 할 수 없을가요?

===============================================
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수

                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                //if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    fullAddr = data.roadAddress;

                //} else { // 사용자가 지번 주소를 선택했을 경우(J)
                //    fullAddr = data.jibunAddress;
                //}

                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                //if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    //fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                //}
		extraAddr = (extraAddr !== '' ? '('+ extraAddr +')' : ' ');
                // 우편번호와 주소 정보를 해당 필드에 넣는다.
//                document.getElementById("Zip1").value = data.postcode1+data.postcode2;
                document.getElementById("Zip1").value = data.zonecode;
//                document.getElementById("Zip2").value = data.postcode2;
                document.getElementById("Adres").value = fullAddr;
				document.getElementById("DetailAdres").value = ' '+ extraAddr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById("DetailAdres").focus();
            },autoMapping:false
        }).open();

**Comment by daumPostcode** [comment]
@holyajj 
네~ 안녕하세요~

알려주신 코드를 보니 autoMapping기능을 false로 두고 사용하시네요.
기본값이 true인데 false로 둘 경우, 1:N일때 자동 맵핑을 하지 않는 다는 것인데요. 
현재 저희 시스템은 항상 지번과 도로명이 세트로 내려가게 됩니다. 
그런데 autoMapping:false로 이용시에는 1:N 주소의 경우, 메인주소를 선택하면 연관주소를 매핑 시킬 수가 없기 때문에, 저희가 autoMapping:true로 이용시에는 메인주소를 선택하면 더보기가 열리게 되고 열린 연관주소를 선택해야지만 데이터가 내려가도록 하였습니다.

그래서 원하시는 방식으로 이용하시려면 기본 기능인 autoMapping을 true로 두시면 해결이 됩니다.
아마 autoMapping을 했을시에 데이터가 roadAddress, jibunAddress가 아닌 autoXXX로 들어가서 그러실 수 있는데요. 해당 문제는 저희 가이드 페이지의 속성 oncomplete함수 설명 아래부분을 참고하시면 될듯 합니다.
한번 읽어 주시면 고맙겠습니다 (http://postcode.map.daum.net/guide#attributes)

추가적인 질문이 있으시면 댓글 부탁드립니다.
