### ISSUE TITLE
안녕하세요 스크립트 에러 문의드립니다.

### ISSUE THREAD

**Issue by jun02** [daumPostcode/QnA#750]
주소찾기 사용중 
스크립트 에러가 발견되어 확인중 의심가는 부분이 있어 문의 드립니다.

에러 스택은 
TypeError: Cannot read property 'Status' of undefined

functionName : undefined, lineNumber : 341
functionName : undefined, lineNumber : 341
unctionName : Object.oncomplete, lineNumber : 341
functionName : XMLHttpRequest.a.onreadystatechange, lineNumber : 341

위와 같이 쌓였으며 
의심가는 부분이 

var geocorder =new daum.maps.services.Geocoder();
geocorder.addressSearch($("#ID").val(), function(result, status) {
    if (status == daum.maps.services.Status.OK) {
        ....
    } else {
        ....
    }
});

사용하는 소스 일부인데 
좌표를 확인할려고 사용중입니다.

혹시 위 와 같은 유사 사례가 있을까요..?^^:;

**Comment by daumPostcode** [comment]
안녕하세요~

해당 문의는 원래 디벨로퍼 사이트이 포럼쪽으로 가야되는데;
음... 지도API쪽은 api key를 기반으로 움직이며, api key가 잘못 되어 있어서 발생한 오류일 수도 있습니다.

여기보다는
https://devtalk.kakao.com/c/map-api

여기에 올려주시는게 더 좋으세요.

**Comment by jun02** [comment]
아 제가 잘못찾아왔네요 ^^;; 
감사합니다~!
