### ISSUE TITLE
다음 주소 API 사용 하는데 다음과 같은 에러가 뜹니다. 이런 에러는 왜 뜨는 걸까요?

### ISSUE THREAD

**Issue by jungyul-lee** [daumPostcode/QnA#751]
어제까지도 잘 되던 다음 주소 API 가 
갑자기 어제 오후 2시경부터 
클릭을 하면 
아래와 같은 메시지가 출력이 되면서 
다음 주소 API 가이드 페이지로 이동이 됩니다. 

[ì°í¸ë²í¸ ìë¹ì¤] API ë¡ë©ì íì©ëì§ ìì íë¼ë¯¸í°ê° ê°ì§ëììµëë¤. ìë¹ì¤ ì´ì©ì ì ì½ì´ ìê¸¸ ì ìì¼ë, ê´ë¦¬ìë¶ê»ìë íì¸ ë¶íëë¦½ëë¤.
ìì¸í ì¬í­ì ê°ì´ëíì´ì§( https://postcode.map.daum.net/guide )ì ê¸°ë³¸ ì¬ì©ë²ì ì°¸ê³ í´ì£¼ì¸ì.

덕분에 해당 문제가 발견되기 전까지 
저희 몰 결제가 어제 오후부터 오늘 오전까지 펑크가 나버리는 불상사가 터지고 말았습니다.

잘 되던 것이 왜 안되나 하고 
다음 주소 API Update 소식을 클릭해보니 
28일에 이슈가 하나 있긴 한데 
그 내용이 문제가 있어보이지는 않습니다만
어쨌든 어제 느닷없이 발생한 일이다보니 
관련이 없어보이지는 않습니다.

저희와 비슷한 사례를 겪으신 분들이 있는지요.

t1.daumcdn.net/cssjs/postcode/1506320738556/170925.js

여기에 문제가 있는 듯 하여
기존에 연결하던 

dmaps.daum.net/map_js_init/postcode.v2.js 로 다시 연결하였습니다.

![다음API오류](https://user-images.githubusercontent.com/78190976/106230171-40347a80-6232-11eb-91b5-8c7cf8ada18e.jpg)

**Comment by daumPostcode** [comment]
@jungyul-lee 
안녕하세요!

https://github.com/daumPostcode/QnA/issues/724
해당 이슈는 작년부터 공지한 내용에서부터 출발합니다.
어제 1월 28일은 이 공지에 따라 2차 배포가 있었던 날입니다.

깃허브+가이드페이지+카톡 메세지로 계속 알림을 보내왔습니다.
현재 저희 우편번호 서비스는 카카오의 타 API와 다르게 개발자사이트를 통해 배포되지 않습니다.
이말은 사용처를 특정할 수가 없다는 것이고, 저희가 일반 유저분들에게 알릴 방법은 깃헙, 가이드페이지, 카톡 메세지로 최대한 보내는 것이며, 이에 더해서 코드 레벨에서 제한을 두는 것입니다.

현재 문구가 깨지는 것은, 저희 우편번호 서비스에서 지원하는 인코딩(utf-8)과 맞지 않아서 발생한 문제로 보입니다.
아무튼 저희 공식 가이드 페이지의 내용을 참고하시면 해결책이 있으시며, 그걸로 API url을 변경하시면 됩니다.
dmaps의 경우에도 현재 API는 유지하고 있지만 서버 이슈가 있어서 종료가 될 가능성이 있습니다. (종료는 결정이 되면 종료전 몇달 전에 미리 사전 공지를 드립니다. 깃헙+가이드페이지+카톡플친메세지)
그렇기에 최신 URL로 변경 부탁드립니다. 해당 최신 URL은 2019년 9월부터 운영중입니다.

카톡플러스 친구의 경우 가이드 페이지의 제일 하단에 보시면 친추 링크가 있습니다. 이부분 참고 하시기 바랍니다.

감사합니다.
