### ISSUE TITLE
다음주소API 관련 카톡 메시지를 받으려면 어디에 어떻게 등록해야 하나요?

### ISSUE THREAD

**Issue by jungyul-lee** [daumPostcode/QnA#752]
제가 올린 질문에 대해
"깃허브+가이드페이지+카톡 메세지로 계속 알림을 보내왔습니다."라는
답변을 받았습니다.

제가 카톡 메시지로 공지 알림을 받으려면 
어디에 어떻게 등록을 해야 
관련 정보를 받을 수 있는건가요?

답변 부탁드립니다.

**Comment by daumPostcode** [comment]
@jungyul-lee 

안녕하세요.
공식 가이드 페이지 (https://postcode.map.daum.net/guide) 의 제일 하단에 플친 등록 링크가 있습니다.

문구를 적어드리면
업데이트에 대한 소식을 받으시려면 카카오톡 친구찾기에서 ID검색으로 @다음우편번호서비스를 추가해주세요. (http://goto.kakao.com/hj697xoo를 클릭하시면 바로 친구추가를 하실 수 있습니다.)

요렇게 적혀 있습니다.

또는 스맛폰의 카톡 채팅 목록에서 상단의 검색버튼 터치해서 "다음우편번호서비스"라고 검색하면 또 나옵니다.
한번 확인 부탁드립니다.
다만 사칭채널이 있을 수도 있으니, 되도록이면 해당 링크로 들어가시는걸 추천드립니다.

서비스를 이용하시는데 큰 변화가 발생할 경우나, 기능추가, 서비스 장애와 관련된 내용은 플친 메세지로 먼저 나가게 됩니다.
이부분 참고 부탁드립니다.

감사합니다.
