### ISSUE TITLE
통합로딩방식으로 호출하고 있는데 경고창이 뜹니다. 

### ISSUE THREAD

**Issue by banghyeyoung** [daumPostcode/QnA#754]
29일부터 메세지가 뜨기 시작해서 우선 메세지 종료 후 사용하고 있긴 한데, 
통합로딩방식으로 사용중인데 왜 경고창이 뜰까요?

<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script> 

function goZipCode(flag){
     new daum.Postcode({
         oncomplete: function(data) {
            
             var fullAddr = ''; 
             var detailAddr = ''; 
             var extraAddr = ''; 
         
             if (data.userSelectedType === 'R') {
                 fullAddr = data.roadAddress;

             } else { 
                 fullAddr = data.roadAddress;
             }
            
                 if(data.bname !== ''){
                     extraAddr += data.bname;
                 }
                
                 if(data.buildingName !== ''){
                     extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                 }
               
                 detailAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                         
             var zcode = data.zonecode; 
             var fAddr = fullAddr;
             var sido  = data.sido;
             var sigungu = data.sigungu;          
             var roadname = data.bname;
             setAddr(flag, zcode, fAddr, sido, sigungu, roadname ,detailAddr); 
     }
     }).open();
 }

**Comment by daumPostcode** [comment]
@banghyeyoung 
안녕하세요~

위와 같이 사용하시는데 경고창이 뜨면 안됩니다.
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js
이번에 패치된 사항은 통합로딩방식으로 쓰면 안난다가 아니라, postcode.v2.js?123=123 과 같이 파라미터가 있으면 뜨는 것으로,
API는 아무런 파라미터도 지원하지 않고, 오히려 파라미터 때문에 캐시서버에 부하만 가기 때문에, 이걸 없애달라고 한것이였는데요.

postcode.v2.js 파일을 작업하고 계시는 프로젝트 전체 검색하셔서, 다른 파일에서 특정 파라미터를 넣고 있는지 확인 부탁드립니다.

**Comment by banghyeyoung** [comment]
해결됨
