### ISSUE TITLE
아이폰에서 주소 검색 후 어플로 연동이 안됩니다 

### ISSUE THREAD

**Issue by hyolee89** [daumPostcode/QnA#755]
![DE444D55-55EE-45B9-800B-5B5371FA70CB](https://user-images.githubusercontent.com/78372683/106490168-e6190b00-64f8-11eb-9799-5e948de0524a.png)

![027D250B-BD11-4636-9E65-688E0C0E3220](https://user-images.githubusercontent.com/78372683/106490182-e9ac9200-64f8-11eb-896b-82ffb2ee9187.png)

아이폰에서 mini plus 라는 어플을 다운받고 회원가입을 하려구 하는데요 주소검색에서 아무리 기다려도 주소 적용된 어플 화면으로 넘어가지 않습니다. 사파리랑 어플 연동이 안되는 느낌이예요 확인 부탁드립니다

**Comment by daumPostcode** [comment]
@hyolee89 

안녕하세요~
질문주신 내용을 토대로 mini plus 라는 앱을 저도 다운받아서 테스트해봤는데요.
우편번호 서비스는 해당 앱내에서 실행되는 것인데 왜 사파리에서 우편번호서비스를 실행하셨을까요??

![Screenshot_20210202-131956_MINI Plus](https://user-images.githubusercontent.com/20675065/106552985-c2d37780-655b-11eb-9ce1-e2d9626ddc21.png)
![Screenshot_20210202-132003_MINI Plus](https://user-images.githubusercontent.com/20675065/106552996-c5ce6800-655b-11eb-86e5-e49195efaf1d.png)
위 스샷은 제가 직접 찍은 스샷입니다.

회원가입할때의 창이며,  "안드로이드 기기"에서는 정상동작을 하고 있습니다.

아마 제 추측으로는 iOS나 안드로이드나 우편번호서비스를 입력하는 부분의 모듈은 같은데, 같은 방식으로 개발하다 보니,
플랫폼적 차이에서 발생하는 부분을 놓친게 아닐까 싶습니다.
해당 이슈는 제가 해결해 드릴 수 없는 부분입니다.
저희는 해당팝업을 띄울 수 있는 API를 "개발자"분들에게 제공을 하는 것이지, 이 API를 가지고 어떻게 서비스에 붙힐까는 저희가 고려하는 부분이 아닙니다. 전전적으로 API를 가져다가 해당 서비스(또는 앱)을 개발하는 개발자의 몫입니다.

BMW MINI 고객센터에 연락해서 아이폰에서는 주소 입력이 안되서 회원가입을 못한다고 제보를 하셔야 수정될 것 같습니다.

해당 부분 확인 부탁드립니다.
