### ISSUE TITLE
경남 창원시 성산구 원이대로 774 주소지의 buildingCode가 행안부와 상이 확인 요청

### ISSUE THREAD

**Issue by mjchoi83** [daumPostcode/QnA#756]
안녕하세요.

경남 창원시 성산구 원이대로 774 주소지의 검색 결과의 buildingCode가 행안부와 상이하여 문의 드립니다.
DAUM API
buildingCode: "4812312700100450001030595"
행안부 API
buildingCode: "4812312700100450001032701"

해당 주소지의 데이터 업데이트가 진행되지 않은 것인지 확인 및 조치 부탁 드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@mjchoi83 
안녕하세요~

해당건 주소 데이터 담당자 분께 문의하도록 하겠습니다.
제보해 주셔서 감사드립니다.

**Comment by daumPostcode** [comment]
@mjchoi83 
안녕하세요~

해당 이슈는 저희쪽 데이터 단에서 삭제코드에 반영이 잘 되지 않아 발생한 이슈로, 현재 수정 되었습니다.
제보 감사드리며, 불편을 드려 죄송합니다.

감사합니다.
