### ISSUE TITLE
부산광역시 서구 고운들로 181 buildingCode 상이 확인 요청

### ISSUE THREAD

**Issue by mjchoi83** [daumPostcode/QnA#758]
부산광역시 서구 고운들로 181
daum
buildingCode: "2614010500104140001023798"
행안부
buildingCode: "2614010500104140001023799"

위와 같이 상이한 주소가 있습니다. 
확인 부탁 드립니다.

**Comment by daumPostcode** [comment]
@mjchoi83 
네 안녕하세요~

해당 이슈 데이터 담당자 분께 전달하도록 하겠습니다.
제보해 주셔서 감사드립니다.!

**Comment by daumPostcode** [comment]
@mjchoi83 
해당건 수정되었습니다.
명절이 껴있어서 수정이 좀 늦었네요. 불편을 드려서 죄송합니다.

감사합니다.
