### ISSUE TITLE
통합로딩방식 변경

### ISSUE THREAD

**Issue by DoSeongJin** [daumPostcode/QnA#759]
현재 기존로딩방식에서 통합로딩방식으로 변경 하려 하는데
통합로딩방식으로 적용하고 테스트해도 alert창은 기존과 동일하게 나오고 있습니다.

혹시 기존 서비스가 제한될때까지 alert은 계속 뜨는걸까요?

**Comment by daumPostcode** [comment]
@DoSeongJin 

안녕하세요~
스크립트를
![image](https://user-images.githubusercontent.com/20675065/107474181-3c4f1380-6bb5-11eb-9026-47e381337c99.png)

위 스샷과 같이 넣으셨나요? 특정 파라미터를 붙히셨을까요?
또는 우편번호 JS API스크립트를 1개만 부르는게 아닌 다른 파일에서 부르고 있는지도 확인 부탁드립니다.
통합 로딩방식에는 허용하는 파라미터가 없습니다.

크롬의 개발자 도구나 이런걸 통해서 파라미터가 붙어 있는 다른 스크립트를 부르고 있는지 확인 부탁드립니다.
그리고 브라우저 캐시도 한번 삭제 부탁드립니다.
감사합니다
