### ISSUE TITLE
SK브로드밴드 회선에서 다음지도 API에 접근할 수 없습니다.

### ISSUE THREAD

**Issue by milkoo00** [daumPostcode/QnA#76]
안녕하세요.
SK브로드밴드 회선을 사용하고 있는 곳에서는 다음 지도 API에 접근할 수 없습니다.
https://spi.maps.daum.net
SK브로드밴드에 문의한 결과 DNS가 등록되어 있지 않다고 합니다.
KT와 LGU+는 정상적으로 접근이 됩니다.
답변을 부탁드립니다.

**Comment by daumPostcode** [comment]
@milkoo00 

네~ 안녕하세요~

현재 말씀해 주신 이슈는 처음 들어보는 상황인데요.. 현재 저희 우편번호 서비스가 수십만개의 사이트에서 이용중이고, 해당 사이트를 이용하는 고객분들은 모두 다른 인터넷을 이용하리라 생각됩니다. 다만 지금까지 네트워크 밴더사에 따라 접속이 불가능한 경우는 없었는데요.

혹시 개발하실때 발생하는 문제인가요? 좀 더 구체적인 설명이 필요해 보입니다. 현재 말씀해 주신 내용으로는 감을 못잡겠네요;;;;
