### ISSUE TITLE
허용하는 파라미터관련 문의

### ISSUE THREAD

**Issue by yonghwa22** [daumPostcode/QnA#761]
안녕하세요.

웹사이트 유지보수 담당자입니다. 얼마전부터 

[우편번호 서비스] API로딩시 허용되지 않은 파라미터가 감지되었습니다......... 라는 alert가 떠서

확인해보았습니다.

우선 제가 쓰고 있는 방식이 통합로딩방식인지/ 구로딩방식인지 구별하는걸

문의 드립니다.

또한
기존 :
<script src = "http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>

수정 :
<script src = "//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>

로 파라미터 없이 넣은 후 테스트 하여도 똑같이 팝업이 뜨는데, 파라미터를 제거하여도 

팝업이 뜨는 문제에 대해서 문의드립니다.

**Comment by daumPostcode** [comment]
@yonghwa22 
안녕하세요~

개발자 도구를 열어서
//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

이 스크립트말고, 다른 스크립트를 호출하는지 한번 확인 부탁드립니다.
캐시도 삭제 한번 해보시는걸 추천드립니다.

간혹 홈페이지마다 여러 파일이 조합되면서 그려지는데, 이때 우편번호 스크립트가 다른곳에 첨부되어 있어서 발생하는 케이스가 있었습니다.
이때 어떤게 나중에 로딩되는지에 따라 그 결과가 달라지게 됩니다. (덮어 써버리니까요)

추가로 기존 URL(dmaps.daum.net)은 공식 가이드 페이지에서 빠진 도메인으로, 추후 종료 예정입니다. 해당 도메인에 대한 종료는 추후 결정되면 공유드릴 예정입니다.

감사합니다.
