### ISSUE TITLE
일 사용량 상한선 사례 문의

### ISSUE THREAD

**Issue by JayongHur** [daumPostcode/QnA#762]
안녕하세요. FAQ에 명시된 내용과 비슷한 내용의 질문을 드려서 정말 죄송합니다만, 저희에겐 반드시 확인이 필요한 내용이라 이슈를 작성하게 되었습니다.

FAQ 6번 항목에서 일 사용량은 100% 무제한이라고 말씀하셨는데, 혹시 기존 이용 사례 중 최대 어느 정도의 사용량까지 문제 없이 처리된 적이 있는지가 공유가 가능하시다면 답변 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@JayongHur 
안녕하세요~

네 별도의 쿼터 제한은 없습니다.
개발자사이트에서 배포되는 API들처럼 별도의 API키로 인해 관리되는 것이 아니라서, 이용 사례중에 어느정도 사용량까지 버텼는지는 알 수가 없습니다.
일단 현재 저희 API를 사용하는 서비스는 70만개이고, 하루 천만콜 정도의 트래픽은 있습니다.
현재까지 장애가 발생된 케이스는 저희 서버의 이상보다, 저희 서비스도 저희 회사의 여러 인프라를 이용하는데, 그 인프라의 장애로 인해 저희 서비스가 영향을 받은 적은 있습니다.

아무튼 어떤 목적으로 사용하실 계획인지, 하루에 어느정도 트래픽이 유발되는지 알 수 있을까요? 엄청나게 많은 트래픽이 유발된다면 저희도 대비는 해야될 것 같아서요.

**Comment by JayongHur** [comment]
@daumPostcode 
안녕하세요.

인증받은 사용자에게 개인 코드를 발급하는 서비스에서 주소 정보를 입력받기 위하여 API를 사용하고자 합니다.
3/7~3/16 약 2주간 일 10~15만 건의 요청이 예상되는 상황입니다.

혹시 문제가 발생할 여지가 있다면 알려주시면 감사하겠습니다.
감사합니다!!

**Comment by daumPostcode** [comment]
@JayongHur 
안녕하세요
큰 문제는 없을 것 같습니다.
10~15만 콜 정도는 괜찮습니다. 이보다 높은 트래픽처리도 지금도 충분히 가능합니다.
다만 외부 요인으로 인해 장애가 가끔 발생할 수 있습니다.
최대한 장애없이 운영하려 하지만, 개발자시면 아시겠지만 여러 환경적 요인으로 장애가 가끔 발생할 수 있습니다.

저희 공식 가이드 페이지에 있는
카카오톡 채널을 친구추가 해주시면 장애 발생시 좀더 빠르게 피드백을 받아보실 수 있습니다.
또한 현 깃허브에 제가 이슈로 등록을 하는데 이걸로도 확인 가능합니다.

감사합니다.
