### ISSUE TITLE
방화벽 설정 방법 문의

### ISSUE THREAD

**Issue by james-chi** [daumPostcode/QnA#763]
안녕하세요.
개발환경에 방화벽이 설치되어 있습니다.
daumPostcode 이용하려면 방화벽을 어떻게 설정해야 하나요?

감사합니다.

**Comment by daumPostcode** [comment]
@james-chi 
저희쪽 도메인 자체를 접근이 불가능하다면
방화벽에서 풀어주셔야 합니다.
다만, 저희는 IP주소는 제공해 드리지 못합니다. 도메인리스트만 제공이 가능하고, 이를 통해 IP주소를 알아내서 해제하여 사용하셔야 합니다.
인트라넷 환경은 공식적으로 지원해 드리지 않기 때문에, 저희가 해드릴 수 있는 것은 도메인 리스트 제공 외엔 없는 점 양해 부탁드립니다.

HTTP환경
- http://postcode.map.daum.net  
- http://suggest-bar.daum.net
- http://t1.daumcdn.net
- http://stlog1-local.kakao.com


HTTPS 환경 
- https://suggest-bar.daum.net
- https://t1.daumcdn.net
- https://postcode.map.daum.net  
- https://stlog1-local.kakao.com


감사합니다.
