### ISSUE TITLE
검색  후 클릭이 안됩니다. (FAQ 12번 관련)

### ISSUE THREAD

**Issue by ondaa** [daumPostcode/QnA#764]
안녕하세요. 현재 React로 개발중입니다.
여러가지 정보를 찾아서 적용해 봤는데 도저히 클릭도 안되고 oncomplate가 호출되지 않아 이슈를 남깁니다.

``` javascript
// index.html
<script src="//dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>

// Postcode.tsx
window.daum.postcode.load(function () {
  const postcode = new window.daum.Postcode({
    oncomplate: function (data) {
      console.log(data);
    },
    autoMapping: true,
    submitMode: false,
    width: "100%",
    height: "100%",
    maxSuggestItems: 10,
  });

  postcode.embed(postRef.current!);

  postRef.current!.style.display = "block";
});
```

.load도 해보고 여러가지 옵션도 바꿔 봤는데 여전히 클릭하면 outline만 잡히고 동작을 안합니다.
그리고 mouseover를 하면 .mode_view라는 class가 붙던데 이게 text-decoration: none 이 더군요.
어떤 조치를 취해야 할지 조언 부탁드립니다.

**Comment by daumPostcode** [comment]
@ondaa 
안녕하세요~

제목에 적혀둔 것처럼, 우편번호서비스의 팝업이 호스트 정보를 알아야 해당 기능이 동작을 합니다.
즉, 특정 플랫폼에 리소스로 임베딩 되는 경우 웹서버 환경이 아닌 그냥 file로딩식으로 개발이 될 수 있는데 이런 경우엔 저희 API는 사용이 불가능합니다.
웹서버에 연결해서 개발이 되고 있는지 확인 부탁드립니다.
http://~~~~ 라고 브라우저에서 화면에 띄워서 개발하고 계신가요?

추가로, 올려주신 API 도메인은 추후 종료예정입니다.
공식 가이드 페이지를 참고하여 최신버전으로 변경해 주시기 바랍니다.

`<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>`

**Comment by ondaa** [comment]
@daumPostcode 
답변 감사합니다.
우선 http://localhost 환경에서 테스트했으며, script 도 말씀해주신 최신 script 경로를 사용했지만 클릭이 안됐었습니다.
그래서 그냥 라이브러리를 사용하기로 했습니다.

https://github.com/bernard-kms/react-daum-postcode

제 코드랑 별다를게 없는데 이 라이브러리는 되더군요 ...;;;
답변 감사합니다 .!!

**Comment by daumPostcode** [comment]
@ondaa 
그렇군요; 해당 라이브러리는 다른 이용자분께서 만들어 주신거라 ㅎㅎ
아마 개발자도구에 뭐라도 오류가 떴을것 같은데;;;
저희가 리액트나 앵귤러 등 이런 프레임워크 테스트는 별도로 진행하진 않습니다.
아무튼 해결되셨다니 다행이네요.
