### ISSUE TITLE
우편번호 서비스 사용 문의

### ISSUE THREAD

**Issue by onycom1234** [daumPostcode/QnA#765]
안녕하세요. 우편번호 서비스 사용 문의 드립니다.

구우편번호(6자리)와 신우편번호(5자리) 현행화 및 검증이 필요하여 우편번호 서비스를 사용하고자 합니다.

**혹시 API 호출 방식으로 저희가 Request로 우편번호를 보내드리면 Response로 도로명 주소를 결과값으로 받을 수 있는지
문의 드립니다.**

구우편번호(6자리), 신우편번호(5자리) 모두 가능한지 확인 부탁 드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@onycom1234 
안녕하세요~

저희 우편번호서비스 API는, 말씀하신 것처럼 어떤 request를 통해 response를 받는 REST형 API가 아닙니다.
https://postcode.map.daum.net/guide
에 들어가 보시면 그 형태를 아실 수 있습니다.

저희는 바로 사이트에 붙힐 수 있는 뷰를 제공하는 API로, 말씀하신 기능은 제공이 불가합니다.
감사합니다.
