### ISSUE TITLE
해외

### ISSUE THREAD

**Issue by impandaluv** [daumPostcode/QnA#767]
해외 주소를 입력하고 싶은데 입력 방법을 알려주세요.

**Comment by daumPostcode** [comment]
@impandaluv 
안녕하세요~
저희는 검색 팝업을 제공하는 API를 제공하고 있습니다.
실제 저희 API를 적용하고 영문 주소를 이용하시는 사이트에 넣고 싶으신 경우엔, 저희가 내려주는 데이터를 참고하시어 oncomplete 함수를 수정하시면 되십니다.

**Comment by impandaluv** [comment]
아 영문 주소 아니라 외국의 주소 입니다..

**Comment by daumPostcode** [comment]
@impandaluv 
아... 외국의 주소군요;;

아쉽게도 해당 데이터는 현재 저희 서비스에서 지원하지 않습니다.
저희 서비스는 행안부에서 제공하는 국내 도로명 주소 데이터만을 이용하며, 그렇기에 국내(대한민국) 주소만 검색이 가능합니다.
해외 주소는 검색이 불가능 함을 말씀드립니다.

감사합니다.
