### ISSUE TITLE
개인서버에서 호출

### ISSUE THREAD

**Issue by judying** [daumPostcode/QnA#768]
js 호출시에 파라미터가 계속 붙는게 해결이 안되서 js를 개인서버에 옮겨서 호출하니 해결이 되었습니다.
이렇게해도 문제가 없을까요?

**Comment by daumPostcode** [comment]
@judying 
안녕하세요~
저희가 배포하는 스크립트는 내부적으로 파라미터를 붙히는 코드가 없습니다.
전적으로 이용하시는 개발자분의 코드를 확인하셔야 합니다. 개발자도구를 통해서 알아보신 다음에 파일 전체 검색으로 찾아보시는게 좋습니다.

JS를 개인 서버로 옮겨서 사용하실 경우에는, 이용은 가능하십니다만, 제가 기능 추가나 버그 픽스시 사전공지를 하고 배포를 하지 않습니다.
현재 그렇게 할 필요가 없게 배포가 되어 있는 것이기두 하구요.
그렇기에 API 스크립트와 서비스팝업과 연결지점에 변경이 있을 경우, 서로 동기화가 안되어 문제가 발생할 수 있습니다.
이러한 경우에는 정상 동작을 저희가 게런티를 할 수가 없습니다.

이부분 참고 부탁드립니다.
