### ISSUE TITLE
통합로딩방식으로 변경후에도 동일한 오류가 발생합니다.

### ISSUE THREAD

**Issue by didvkjkh** [daumPostcode/QnA#769]
허용하지 않은 파라미터 값이 감지되었다는 alert창이 나옵니다.
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
위와 같이 수정했으며 버튼에 클릭 이벤트를 주어 가이드된 소스 그대로 진행하였으나, 오류가 발생하는데, 
개발자 모드에서 확인시에 파라미터가 뒤에 붙어서 넘어갑니다...
이 부분은 가이드 나와있는데로 개발 진행 했으나, 다른 오류일지요? 확인 부탁 드립니다.

**Comment by daumPostcode** [comment]
@didvkjkh 
안녕하세요~

해당 스크립트를 입력한 파일이 1개만 있으신가요? 아니면 다른 페이지에도 있으신가요?
개발자도구에서 파라미터가 붙어서 날라간다면, 어딘가에서 파라미터가 붙은 스크립트를 호출하고 있는 것입니다.
그부분을 한번 체크 부탁드립니다.
