### ISSUE TITLE
법정동 검색시 행정동도 검색이 되면 좋겠어요.

### ISSUE THREAD

**Issue by beomsub** [daumPostcode/QnA#77]
지자체에서는 행정서비스를 행정동 기준으로 하기 때문에 법정동 검색시 행정동 안내가 반드시 필요합니다.
되도록 빠른시일내에 법정동으로 검색할 시 행정동 안내서비스도 같이 지원되었으면 하는 바램입니다.
위 답변에 감사드리며 앞으로도 많은 개선 지원 부탁드립니다.

**Comment by daumPostcode** [comment]
@beomsub 
네~ 안녕하세요~

일단 이전에 주신 내용을 토대로 내부 논의 중입니다. 진행 결과는 논의가 끝나는 대로 말씀드리도록 하겠습니다.
감사합니다.

**Comment by daumPostcode** [comment]
@beomsub 
네~ 안녕하세요~

금일 행정동 정보를 더 많이 보이게 할 수 있는 옵션이 추가되어 공유드립니다.

해당 기능은 생성자에 showMoreHName:true 라는 형식으로 옵션을 설정하면 활성화 되며,

기존의 행정동 표시로직에 검색결과의 법정동과 행정동이 다른 경우 무조건 표시하고, 이를 데이터로 내리게 됩니다.

다만 현재 지번이 메인주소일대는 문제가 없지만, 도로명이 메인주소 일때는 연관된 지번주소의 행정동이 비어있는 경우가 좀 있습니다. 이는 지속적으로 데이터 체크를 하여 수정해 나갈 예정으로, 저희에게 직접 CS를 주셔도 되며, 점진적으로 개선해 나갈 수 있도록 노력하겠습니다.

그리고 UI상 표기는 지번주소에만 행정동이 표시되는점 참고바랍니다.

자세한 사항은 http://postcode.map.daum.net/guide#attributes <- 가이드 페이지의 속성 부분의 아랫쪽을 참고 하시기 바랍니다.

감사합니다.

<같은 분이시나 이슈가 따로 등록되어 댓글 답니다>

**Comment by beomsub** [comment]
적용하니 아주 잘되고 있습니다.감사합니다.수고하십시오.
--------- 원본 메일 ---------

    
        보낸사람: Daum 우편번호서비스 <notifications@github.com>
        받는사람: daumPostcode/QnA <QnA@noreply.github.com>
        
            참조: beomsub <bslee007@hanmail.net>, Mention <mention@noreply.github.com>
        
        날짜: 2017년 1월 9일 월요일, 00시 02분 02초 +0900
        제목: Re: [daumPostcode/QnA] 법정동 검색시 행정동도 검색이 되면 좋겠어요. (#77)
        
        
    
    
        Closed #77.
