### ISSUE TITLE
우편번호가 표시된 상태에서 지도클릭 하면 

### ISSUE THREAD

**Issue by magicact** [daumPostcode/QnA#770]
1. 우편번호가 표시되면  영문보기/지도 가 있습니다. 
2. 지도를 클릭하면 지도가 표시되고, 찾아진 주소 위치에 길찾기 링크가 표시 됩니다. 
3. 길찾기를 누르면 경유나 도착을 클릭하면 길찾기가 시작됩니다. 
4. 이때 PC는 시작위치를 넣을 수 있습니다. 
5. 모발일 일때는 내위치 버튼으로 시작위치  지정하여 길찾기 하면 네비로 연결되야 하는데
6. 안드로이드 폰에서 권한 요청이 안된 문제로 내위치 버튼이 눌리지 않습니다. 
7. 위치 권한 요청 방법을 알려 주시면 감사겠습니다,.

**Comment by daumPostcode** [comment]
@magicact 
안녕하세요~

해당 이슈는 우편번호서비스에 관련된 이슈가 아닙니다.
안드로이드 지도앱에 관련된 사항으로 제가 답변을 드리기는 어렵습니다.
(지도앱이 열린 이상 우편번호 서비스 이슈가 아닙니다)

권한이라하면, 위치정보를 받아오는 권한을 앱을 설치 또는 실행시에 허용을 안하셔서 그런것 같으신데요.
안드로이드폰의 설정에서, 애플리케이션 -> 카카오맵 (검색 및 스크롤 해서 선택) -> 권한 부분에서 "위치" 부분에서 설정 변경
을 해주시면 될것 같습니다.

다만 안드로이드폰은 벤더사별로 설정 화면이 다를 수 있으니, 단순참고만 하시기 바랍니다.
결론적으로 앱의 설정을 변경하시면 되십니다.
