### ISSUE TITLE
버젼 오류 문제

### ISSUE THREAD

**Issue by kyuwan-dev** [daumPostcode/QnA#771]
안녕하세요.
http://dmaps.daum.net/map_js_init/postcode.v2.js 버젼으로 로컬 테스트시 문제 없어서
운영서버에 올리니 v1X 버젼은 서비스가 종료 되었으니 v2 버젼으로 변경해달라는 문구가 나옵니다.
저희 네트워크 문제인지 아님 다른 문제인지 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@kyuwan-dev 
안녕하세요~
크롬에서 해당 오류가 뜨는 페이지를 접속할때 개발자 도구로, 네트워크탭에서 어떤 파일을 받는지 확인 부탁드립니다.
간혹 실제 렌더링 되는 페이지가 조합이 되는 경우에 우편번호 서비스 스크립트를 여러 군데에서 로딩하는 경우가 있는데, 그에 따라 발생하는 것같이 보입니다.

현재 말씀하신 주소로 테스트 해본결과 해당 오류는 뜨지 않습니다.

그리고 추가로, 해당 주소의 경우엔 추후 스크립트 접근이 안될 수 있습니다. 이는 아직 확정된 사안은 아니나, 현재 공식가이드페이지에서 제공하고 있는 스크립트 도메인 외에 다른 도메인들은 제거할 계획을 가지고 있기 때문에
공식 가이드 페이지에 있는 스크립트 주소를 이용해 주시기 바랍니다.

//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

감사합니다.
