### ISSUE TITLE
주소 정보 문제

### ISSUE THREAD

**Issue by khj68** [daumPostcode/QnA#772]
![image](https://user-images.githubusercontent.com/43369570/111244109-9ecc8100-8645-11eb-8db5-28c563e9a257.png)

![image](https://user-images.githubusercontent.com/43369570/111244119-a4c26200-8645-11eb-8d6e-998b96336660.png)

안녕하세요.
보통의 다른 주소들은 기본적으로 R type 변환이 진행되는데,
신림동 주소와 같은 간혹 특정 주소들에 대해서 J type 변환이 진행되는 상황이 발생합니다.

확인 부탁드려도 될까요?

**Comment by daumPostcode** [comment]
@khj68 
안녕하세요~
내려가는 변수의 addressType을 말씀하시는 것일까요?

해당 addressType은 검색결과의 주소중에서
셀마다 도로명-지번, 또는 지번-도로명 순으로 매핑되어 있을겁니다.
이때 도로명-지번 순으로 매핑되어 있으면 첫째줄 주소가 도로명주소이고, 두번째줄 주소가 지번주소라는 것이죠
첫째줄 주소가 메인주소, 두번째 줄이 연관주소인데,
addressType은 첫째줄 메인주의 타입으로 나오게 됩니다.

이때 검색쿼리가, 지번주소 타입으로 검색을 하게 되면 거의 대부분 지번주소가 메인주소가 되고, 도로명주소 타입으로 검색하게 되면 메인주소가 도로명 타입으로 나오게 됩니다. 

그래서 서울 관악구 신림동 531-2는 지번타입 주소로 addressType이 J로 나오는 것이고
서울 강남구 가로수길 5는 도로명 주소 타입 주소로 addressType이 R로 나오는 것입니다.

한번 확인 부탁드립니다.

**Comment by khj68** [comment]
확인했습니다. 감사합니다~!
