### ISSUE TITLE
카카오맵에서는 검색되는데 우편번호서비스에서는 안나오네요

### ISSUE THREAD

**Issue by iamjunghak** [daumPostcode/QnA#774]
풍천리 310이라고 
http://kko.to/Y3wlj2JYp
카카오맵에서는 되는데 

우편번호 서비스에서는 풍천리 310이라고 검색하니까 없는주소라고 나오네요.

확인가능할까요?

**Comment by daumPostcode** [comment]
@iamjunghak 
안녕하세요~

<img width="1431" alt="스크린샷 2021-03-23 오후 2 40 40" src="https://user-images.githubusercontent.com/20675065/112098835-cbecd680-8be5-11eb-9886-5413bc0e8e66.png">


[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 참고 부탁드립니다.

저희는 모든주소검색시스템이 아닌, 도로명주소 검색시스템으로, 검색되는 데이터의 기반은 행정안전부의 도로명주소검색시스템을 따릅니다.
말씀하신 주소는 도로명주소가 발급되지 않은 주소라서 저희 시스템에서는 검색되지 않습니다.

위 스샷은 행안부 도로명주소 시스템의 검색결과입니다. 저기에 나오지 않으면 저희 시스템에도 나오지 않습니다.
FAQ1번을 참고하여 행안부에 직접 주소 등록 요청해 주시기 바랍니다.

감사합니다.
