### ISSUE TITLE
English version of postcode guideline (http://postcode.map.daum.net/guide )

### ISSUE THREAD

**Issue by thsuglgl94** [daumPostcode/QnA#775]
Hi team,
this is Jungwon from BMW Korea Group IT team and I am responsible for Online Sales KR.
We are planning to add "find my address" in our website and would like to use the postcode map API provided by daum.
I found this domain (http://postcode.map.daum.net/guide) however it is only provided in Korean.
Since our development team is in South Africa, could you please provide in English version?

Thank you and regards,
Jungwon.

**Comment by daumPostcode** [comment]
@thsuglgl94 

Hello

There is no English guide.

Because API is not difficult,
Please refer to Google Translator or Sample Code.

Additionally, the description of the road name address in Korea is
https://www.juso.go.kr/openEngPage.do
Please refer to the above site.

Thank you.
