### ISSUE TITLE
누락된 주소지가 있습니다.

### ISSUE THREAD

**Issue by whiteday910** [daumPostcode/QnA#776]
검색 시 아래 주소지가 표시되지 않습니다.

대전광역시 서구 관저동 1953-11

이에 해당 주소지의 고객님들이 물건을 받지 못하는 일들이 발생하고 있습니다.
확인부탁드립니다.

고맙습니다.

**Comment by daumPostcode** [comment]
@whiteday910 

안녕하세요.

저희는 도로명주소 검색시스템이며, 데이터는 행안부 도로명검색 시스템에서 나오는 도로명주소에 기반을 두고 있습니다.
그렇기 때문에 도로명 주소가 발급되지 않은 지번주소는 검색이 되지 않습니다.

현재 말씀해 주신 주소는 도로명 주소가 발급되지 않은 주소입니다.

<img width="1424" alt="스크린샷 2021-03-24 오후 6 44 06" src="https://user-images.githubusercontent.com/20675065/112288904-2a42b380-8cd1-11eb-8674-b7288dfd04da.png">

[FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)에 따라 행안부에 직접 도로명 주소 발급 요청을 하셔야 합니다.
이부분 참고 부탁드립니다.
