### ISSUE TITLE
아이폰에서 스크롤이 작동하지 않습니다.

### ISSUE THREAD

**Issue by pumdi** [daumPostcode/QnA#78]
iframe으로 끼워넣기 형식으로 넣어서 height 를 300px로 고정시킨 후
iframe안에 스크롤이 생겨서 작동하는 것으로 하였는데,
pc, 안드로이드는 정상 작동되지만 ios에서만 작동이 안되더라구요. (스크롤이 아예 생기지 않음)

이것도 혹시 modal형식으로 띄우는 것에서 ios에서 버그가 나는 것과 연관이 있는건가요?ㅠㅠ

**Comment by daumPostcode** [comment]
@pumdi 
네~ 안녕하세요.

혹시 상위 DOM노드에 overflow:hidden 속성이 있는지, 또는 우편번호서비스가 들어가는 최상위 노드(샘플에서는 보통 id="layer" 인 노드)에  -webkit-overflow-scrolling: touch; 속성이 있는지 확인 부탁드립니다.

그리고 만약 mac을 쓰고 계신다면 저희 가이드 페이지 (http://postocde.map.daum.net/guide)를 아이폰 사파리에서 들어가셔서 iframe으로 레이어 띄우기(페이지에 끼워넣기랑 코드는 동일하며, with,height를 조정하는 기능만 제거된 버전입니다.)를 inspecting하시면 확인 가능하십니다.

현재 제가 가진 아이폰 사파리에서 가이드페이지 샘플이 오류가 나지 않고, pumdi님의 코드나 개발 및 테스트 환경, 제가 접근가능한 URL정보가 없어서 정확한 진단을 드리기 어려운점 말씀드립니다.

또한 구글에서 ios inner scroll관련해서 검색해 보시면 좀더 힌트를 얻으실 수도 있을것 같으니 확인 부탁드립니다.
