### ISSUE TITLE
특정 환경에서 iframe의 위치와 크기가 정상적으로 잡히지 않는 이슈

### ISSUE THREAD

**Issue by Normaltic** [daumPostcode/QnA#785]
안녕하세요! 특정 환경에서, 내부 iframe이 정상적인 사이즈를 잡지 못하는 증상이 있어 이슈 남깁니다.

파악하기로는 너비가 375px인 아이폰 계열에서 발생하고 있으며, iframe을 감싸는 `div#__daum__layer_1`의 스타일에 `position: relative`가 누락되어, 의도와 다르게 iframe의 크기가 커지거나, 다른곳으로 위치됩니다. 현재 [공식 문서](https://postcode.map.daum.net/guide) 쪽에도, 최상단 타이틀과 같이 있는 예제가 같은 환경에서 같은 증상이 발생하여, 비정상적으로 큰 높이를 가지고 있습니다. 

https://github.com/bernard-kms/react-daum-postcode/pull/32

**Comment by daumPostcode** [comment]
@Normaltic 
네! 안녕하세요~

해당 현상 한번 확인해보도록 하겠습니다.
현재 재택중이라 단말기 수급에 문제가 있어서, 시간이 좀 걸릴 것 같아요 ㅜ.ㅜ 양해 부탁드립니다.

**Comment by Normaltic** [comment]
![image](https://user-images.githubusercontent.com/24601577/113821386-ff6b5b80-97b6-11eb-84d5-63b8f887f4bf.png)

페이지 최상단에 있는 예제(판교역로 235 가 입력되어 있는)입니다.

![image](https://user-images.githubusercontent.com/24601577/113821362-f9757a80-97b6-11eb-8af4-51be750a33e5.png)

사진과 같이, iframe의 크기가 `__daum__layer_1` 의 영역을 넘어갑니다.

**Comment by daumPostcode** [comment]
@Normaltic 
아 넵 확인 감사합니다.

지금까지 예제 동작 확인은 가이드페이지 하단의 코드와 같이 설명되는 예제 5개만 확인했었는데;
해당 프리뷰 샘플이였군요 ㅎㅎ

넵 확인하였습니다. 프리뷰샘플과 비슷한 방식으로 구현해서 사용하시는 분들께는 문제가 될 수 있겠군요.
이슈 확인하였고, 수정 해서 테스트하여 배포하도록 하겠습니다. 이번주 중에는 배포 가능할 것 같습니다. (내일 실제 단말기 빌려서 테스트)
감사합니다.

**Comment by daumPostcode** [comment]
@Normaltic 
안녕하세요~
현재 해당 이슈 수정되어 패치되었습니다.
한번 확인 부탁드립니다~

**Comment by Normaltic** [comment]
@daumPostcode 
안녕하세요! 정상 작동 확인하였습니다 감사합니다!
