### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by itahyun** [daumPostcode/QnA#79]
주소 검색 후 나오는 우편번호 우측 영역인 [영문주소],[지도] 부분만 숨기고 싶습니다.

따로 숨길 수 있는 방법은 없나요?

**Comment by daumPostcode** [comment]
@itahyun 
네~ 안녕하세요~

현재 UI를 숨길 수 있는 옵션은 따로 제공하고 있지 않습니다.

따로 숨겨야 되는 이유가 있으실까요??

**Comment by daumPostcode** [comment]
@itahyun 
안녕하세요~

말씀하신 기능이 추가되어 댓글 답니다.

현재 '지도''영문보기' 버튼을 화면에서 감출 수 있는 옵션이 1월 7일부로 추가되었습니다.

옵션명은
hideMapBtn, hideEngBtn 이며 기본값은 false이며 true로 설정하시면 가려집니다.

자세한 사항은 http://postcode.map.daum.net/guide#attributes 의 속성 부분 아래쪽을 참고 바랍니다.
감사합니다.

**Comment by itahyun** [comment]
기능 추가 안내 메일도 보내주시고 감사해요~~ ^^

**Comment by daumPostcode** [comment]
@itahyun 
네~ 아닙니다. 다만 제가 이번에 기능추가를 하고 보니, 1:N 구조의 주소에서 연관주소의 '지도' 버튼이 살아 있더라구요 ;;;;;
이 부분은 수정되어 다음 주에 배포나갈 수 있을 것 같습니다.

배포 나가면 다시 이 이슈에 댓글 남겨드리겠습니다~

**Comment by daumPostcode** [comment]
@itahyun 
안녕하세요~

이전에 기능 추가후, 연관주소의 버튼이 사라지지 않던 버그가 수정되어 배포되었습니다.

추후 다른 질문이 있으시면 언제든 이슈 등록해 주세요~

감사합니다~

**Comment by itahyun** [comment]
빠른 수정 감사합니다~ ^^
