### ISSUE TITLE
동까지 검색 또는 길까지 검색시에 검색 결과가 나오지 않습니다.

### ISSUE THREAD

**Issue by zbdulee** [daumPostcode/QnA#799]
ex) 경기도 남양주시 미금로19번길

 이 경우 데이터가 나오지 않네요.

원래는 나왔던 것으로 알고 있는데요.(1시간 전에는 나왔습니다.ㅠㅠ)

확인 부탁 드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@zbdulee 
네 안녕하세요. 현재 장애 확인하였고,
현재 원인 파악중입니다. ㅜ.ㅜ 검색엔진 이슈인 것까지만 확인이 되며 아직 정확한 원인은 나오지 않았습니다.
최대한 빨리 수정될 수 있도록 하겠습니다.
불편을 드려 죄송합니다.

(저도 1시간 전에 추가 개발할 사항 있어서 테스트 할땐 잘 나왔는데... 갑자기 그러네요 ㅜ.ㅜ)

**Comment by daumPostcode** [comment]
16시 40분 부로 수정 조치 완료되었습니다.
불편을 드려 죄송합니다.

감사합니다.

**Comment by zbdulee** [comment]
넵 감사합니다.
