### ISSUE TITLE
재문의 드립니다.

### ISSUE THREAD

**Issue by han3388** [daumPostcode/QnA#8]
안녕하세요.
어제 아래와 같은 오류로 문의드린 사람입니다.
![111](https://cloud.githubusercontent.com/assets/21211371/17957932/e0110360-6ad0-11e6-92a6-78bf1115dbdd.JPG)

소스 첨부하니 체크부탁드립니다.
pleaseReadGuide : 4, 
		pleaseReadGuideTimer : 10 부분도 같이 체크부탁드립니다.

-------------------------------------------------------------------------------------

var win_zip = function(href) {
    if(typeof daum === 'undefined'){
        alert("다음 juso.js 파일이 로드되지 않았습니다.");
        return false;
    }
 
//alert(href);
 
    var url_to_array = function(url) {
        var request = [];
        var pairs = url.substring(url.indexOf('?') + 1).split('&');
        for (var i = 0; i < pairs.length; i++) {
            var pair = pairs[i].split('=');
            request[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1]);
        }
        return request;
    }
 
    var param = url_to_array(href),
        frm_name = param['frm_name'],
        frm_addr1 = param['frm_addr1'],
        frm_addr2 = param['frm_addr2'],
        frm_addr3 = param['frm_addr3'],
        frm_zip1 = param['frm_zip1'],
        frm_zip2 = param['frm_zip2'],
        frm_jibeon = param['frm_jibeon'],
        of = document[frm_name];
 
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
 
                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수
var postcode1 = '';
var postcode2 = '';
 
                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    fullAddr = data.roadAddress;
 
                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    fullAddr = data.jibunAddress;
                }
 
                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

 
if(href == "aorderform1") {
                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('od_zipall').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('od_zip1').value = data.postcode1; // 기존 우편번호 앞자리
                document.getElementById('od_zip2').value = data.postcode2; // 기존 우편번호 뒷자리
document.getElementById('od_addr1').value = fullAddr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('od_addr2').focus();
} else if(href == "aorderform2") {
                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('od_b_zipall').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('od_b_zip1').value = data.postcode1; // 기존 우편번호 앞자리
                document.getElementById('od_b_zip2').value = data.postcode2; // 기존 우편번호 뒷자리
document.getElementById('od_b_addr1').value = fullAddr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('od_b_addr2').focus();
} else if(href == "amember") {
                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('mb_zipall').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('mb_zip1').value = data.postcode1; // 기존 우편번호 앞자리
                document.getElementById('mb_zip2').value = data.postcode2; // 기존 우편번호 뒷자리
document.getElementById('mb_addr1').value = fullAddr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('mb_addr2').focus();

} else {

                //document.getElementById('reg_mb_zipall').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('reg_mb_zip1').value = data.postcode1; // 기존 우편번호 앞자리
                document.getElementById('reg_mb_zip2').value = data.postcode2; // 기존 우편번호 뒷자리
document.getElementById('reg_mb_addr1').value = fullAddr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('reg_mb_addr2').focus();
}
            },
pleaseReadGuide : 4, 
pleaseReadGuideTimer : 10
 
        }).open();
} 

-------------------------------------------------------------------------------------------

작업해주시는 분 말씀으로는 "보시다시피 소스에 reg_mb_addr3 부분에 내용이 들어가는데 소스상에는 그부분에
데이터를 넣은 부분은 없습니다. " 라고 하네요.

하여튼 정말로 이상한 것은 이렇게 했을때 같은 os에 같은 브라우저 인데도 정상으로 되는 컴이 있고 안되는 컴이 있고 휴대폰에서는 특정브라우저에서만 안되네요. 보트브라우져 안됩니다.)
pleaseReadGuide 부분도요. (특정주소 하고는 상관 없으며 아무주소나 결과가 많은 것은 마찬가지 입니다.   주소를 검색하여 선택해서 적용이 정상적으로 되는 컴에서는 pleaseReadGuide  기능도 정상으로 작동을 하고 주소를 검색하여 선택해서 적용시 위와 같은 에러가 생기는 컴퓨터의 경우에는 pleaseReadGuide  기능도 작동을 안합니다.)

**Comment by daumPostcode** [comment]
@han3388 
일단 코드에 관한 부분은 시간이 조금 걸릴것 같아, 조금있다가 답변 다시 달겠습니다.

일단 아랫부분에 쓰신 것처럼, 같은 코드인데 되는 컴이 있고 안되는 컴이 있다면, 현재 저희로써는 PC의 경우에는 Safari, FF, Chrome, IE6-11, Edge까지 대응을 합니다. 모바일은 핸드폰의 기본 브라우저 및 Chrome, 그리고 웹뷰까지 추가로 합니다. 만약 위 브라우저에서 오류가 발생하는 오류의 경우에는 저희쪽에서 리스트업 해놓고 있으며, 기술적으로 가능한 부분 불가능한 부분을 설명하고 있습니다.

다만 현재 적어주신 내용을 보면, 일단 저희가 알수 있는 것은 **보트브라우저** 라는 약간 생소한 브라우저 이름 밖에 없구요. 이 브라우저가 실행되는 환경(OS정보, 브라우저의 버전) 등이 명시가 되지 않는 이상 저희가 테스트 환경을 구축하기 힘든점을 양해 바랍니다.

기본 테스트 환경이 구축이 되면, 저희가 외부 코드의 영향이 거의 없는 순수 저희 우편번호 서비스를 작동시킬 수 있는 코드로만 테스트를 먼저 진행합니다. 그리고 오류가 발견되면 즉시 수정하며, 그렇지 않다면 고객님의 코드와 연동되는 부분의 오류를 짐작해 볼 수 있기 때문에 이부분 또한 참고하게 됩니다.

즉, 현재는 코드를 알려주셨으니 코드 연동부분을 눈으로 확인은 가능하나, 테스트 환경이 구축이 되어 있지 않기 때문에 오류를 찾는데 시간이 걸리는 것을 양해 부탁드립니다.

**Comment by daumPostcode** [comment]
@han3388 

네~ 코드를 확인해 보았는데요.

음, 일단 oncomplete부분은 저희 예제 샘플의 내용과 거의 비슷하고, 그부분만 때어내서 동작시켜보니 데이터는 잘 내려오네요. 
그리고 문의글과 코드를 계속 보다보니, 적어주신 내용중에 **reg_mb_addr3**에 데이터를 넣는다고 하신것 같은데, 제공해 주신 소스상에서는 해당 reg_mb_addr3을 접근하는 코드가 없습니다.

오히려 완성된 주소 데이터를 넣는 부분은
```
document.getElementById('od_addr1')
document.getElementById('od_b_addr1')
document.getElementById('mb_addr1')
document.getElementById('reg_mb_addr1')
```
입니다. (저 위 4개중 1개에 데이터가 들어가도록 되어 있네요.)
즉, 말씀하신 reg_mb_addr3가 어떤 것인지는 제쪽에서는 확인이 안되나, 아마 input필드를 말씀하신 것 같은데요.
일단 해당 사이트 개발자님께서 말씀하신 것처럼 reg_mb_addr3에는 데이터를 할당하지 않습니다.

일단 알려주신 소스에는 딱히 이상한 점은 찾지 못했습니다. undefined가 들어간다는 것은, 올려주신 저 코드가 아닌 사이트의 다른 코드에서 없는 변수를 할당하는 것 같고, 올려주신 코드로는 저 input박스들의 id값들을 제가 알 수 없기 때문에 정확히 결론 내리기도 어렵네요;


그리고 우편번호 서비스 실행코드 외에 한가지 궁금한 코드가 눈에 보이더군요.
```
if (typeof daum === 'undefined') {
        alert("다음 juso.js 파일이 로드되지 않았습니다.");
        return false;
    }
```
여기서 의심되는 것은 **"다음 juso.js"**라는 부분입니다. 저희는 postcode.v2.js라는 이름으로 서비스를 하고 있지 juso.js라는 이름은 사용하지 않습니다. 제가 사이트에 접근하지 못하니 불러오는 스크립트를 알순 없지만, 혹시나 저희 postcode.v2.js 파일을 다운로드 받아서 juso.js라는 파일로 만들어서 사용하시는 것인가요? (이 파일을 만들때 소스코드에 변형을 가할 수도 있는데, 만약 이런 경우라면 저흰 더이상 지원을 해드릴 수 없습니다.) [FAQ 15번 참고](https://github.com/daumPostcode/QnA#15-javascript-api-코드를-복사해서-사용해도-되나요)

제일 좋은 방법은 작동환경에 대한 정보와, 저희가 접근할 수 있는 URL을 주시는게 좋아 보입니다.
