### ISSUE TITLE
사설ip 문의드립니다.

### ISSUE THREAD

**Issue by bjh0226** [daumPostcode/QnA#80]
사설ip인데 사용 가능한가요?_

**Comment by daumPostcode** [comment]
@bjh0226 
안녕하세요~

사설ip라는게 사내 인트라넷이라는 말씀인가요?

저희 서비스는 기본적으로 인터넷환경에서만 이용가능합니다. 그렇기 때문에 내부방에서 이용하실려면, 사내 네트워크 팀이나 인프라팀에 방화벽에 저희가 사용하는 도메인의 ip를 열어둬야 합니다.

도메인 리스트의 경우 필요하시면 댓글로 알려드리도록 하겠습니다.

감사합니다.
