### ISSUE TITLE
도로명 주소 검색이 안됩니다.

### ISSUE THREAD

**Issue by battlewolf81** [daumPostcode/QnA#800]
도로명 주소는 검색되지 않고, 지번 주소도 번지수까지 정확하게 입력해야 검색 가능하네요.

**Comment by daumPostcode** [comment]
@battlewolf81 
네 안녕하세요. 현재 장애 확인하였고,
현재 원인 파악중입니다. ㅜ.ㅜ 검색엔진 이슈인 것까지만 확인이 되며 아직 정확한 원인은 나오지 않았습니다.
최대한 빨리 수정될 수 있도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
16시 40분 부로 수정 조치 완료되었습니다.
불편을 드려 죄송합니다.

감사합니다.
