### ISSUE TITLE
일부주소가 검색이 되지 않습니다.

### ISSUE THREAD

**Issue by jh99983** [daumPostcode/QnA#801]
안녕하세요.

현재 일부주소가 검색이 되지 않아서 확인 요청 드립니다.
ex)구좌읍(제주도 제주시 구좌읍)

![KakaoTalk_20210602_143749763](https://user-images.githubusercontent.com/85215609/120432702-45a6fa80-c3b5-11eb-9712-a7f996914c97.png)

그외의 주소도 검색이 안되고 있습니다.

감사합니다.

**Comment by daumPostcode** [comment]
네 안녕하세요. 현재 장애 확인하였고,
현재 원인 파악중입니다. ㅜ.ㅜ 검색엔진 이슈인 것까지만 확인이 되며 아직 정확한 원인은 나오지 않았습니다.
최대한 빨리 수정될 수 있도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
16시 40분 부로 수정 조치 완료되었습니다.
불편을 드려 죄송합니다.

감사합니다.
