### ISSUE TITLE
주소검색 불가

### ISSUE THREAD

**Issue by KIMFE** [daumPostcode/QnA#802]
안녕하세요

충청남도 천안시 동남구 로 조회 시 데이터가 조회되지 않음 확인하였습니다.
행정자치부 사이트에서는 정상적으로 조회가 됩니다.

구 하위의 두정동 등 동단위로만 검색 시에는 가능하나,
앞의 구 단위의 주소를 입력 시에는 조회 불가능한 부분이 있습니다.

실제 조회된 데이터에는 "충남 천안시 ~~~"로 나타나지만 행정자치부 사이트에서는 "충청남도 천안시 ~~~"로 표기되네요
다만, 행정자치부는 충남이라고 검색해도 조회가 되는데...

풀네임 조회 시 검색이 정상적으로 되지 않는 이슈가 있는 것 같아 문의드립니다.
(서울특별시는 가능합니다. 기타 주소는 검색해보지 않았구요)

확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@KIMFE 

네 안녕하세요. 현재 장애 확인하였고,
현재 원인 파악중입니다. ㅜ.ㅜ 검색엔진 이슈인 것까지만 확인이 되며 아직 정확한 원인은 나오지 않았습니다.
최대한 빨리 수정될 수 있도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
16시 40분 부로 수정 조치 완료되었습니다.
불편을 드려 죄송합니다.

감사합니다.
