### ISSUE TITLE
자동완성 기능 문의

### ISSUE THREAD

**Issue by opendeskproject** [daumPostcode/QnA#805]
최신 버전의 IE 웹화면에서 다음 우편번호 API를 사용중에 있습니다.

도로명이나 지명을 입력 시에 자동완성 ( 유사주소지 ) 기능이 원래 없었나요?

원래 제공이 되었던 걸로 기억을 하는데 
혹시 중단되었다면 이유를 알 수 있을까요?

**Comment by daumPostcode** [comment]
@opendeskproject 
안녕하세요~

아뇨 존재합니다.
어제부로 해당 자동완성기능(이하 서제스트)의 전사API가 변경되어 도메인이 변경되었습니다.
혹시 인트라넷 환경에서 사용중이실까요?

**Comment by daumPostcode** [comment]
@opendeskproject 
안녕하세요~
현재 해당 기능은 외부망에서 문제가 있어서 기존버전으로 롤백되었습니다. 불편을 드려 죄송합니다.
지금은 정상 동작하실거에요~

**Comment by opendeskproject** [comment]
네 정상작동되는 거 확인했습니다.
확인 감사합니다~
