### ISSUE TITLE
자사몰_자동완성 기능 오류 

### ISSUE THREAD

**Issue by Samsonitekr** [daumPostcode/QnA#807]
안녕하세요.

쌤소나이트 코리아 자사몰 담당자 이승민 대리라고 합니다. 
저희 베트남 개발사로부터 다음 우편번호 서비스 자동완성 기능이 현재 제대로 작동하고 있지 않는다는 연락을 하기처럼 받았습니다. 
체크아웃 단계에서 우편번호를 클릭시 검색이 불가능하며, '주소찾기'를 눌러야 가능합니다.
확인 후 회신 요청 드리며, 제 메일은 다음과 같습니다. Emma.Lee@samsonite.com
감사합니다.

===============================
Dear Emma, 

While checking the checkout on the live site of Mono site. My team found that the Daum postcode doesn't show the suggestion list on the popup while typing words. It still works by submitting the search form.

I took a screenshot of it. Could you please help me check with Daum team about this? 
===============================

**Comment by daumPostcode** [comment]
@Samsonitekr 
안녕하세요~

현재 어떤 이슈이신지 정확한 설명 부탁드립니다.
https://www.samsonite.co.kr/
에서 현재 테스트 해보니, 정상적으로 동작되고 있습니다.

1. 검색어 자동완성(서제스트) 정상 동작
<img width="1187" alt="스크린샷 2021-06-04 오후 7 03 04" src="https://user-images.githubusercontent.com/20675065/120784915-8e9eb080-c567-11eb-8164-854be47b5a9b.png">

2. 검색 기능 정상 동작
<img width="1218" alt="스크린샷 2021-06-04 오후 7 02 50" src="https://user-images.githubusercontent.com/20675065/120784924-9199a100-c567-11eb-8393-a7bceeeb1c94.png">

3. 검색결과 클릭시 배송정보란에 데이터 입력 이상 없음
<img width="761" alt="스크린샷 2021-06-04 오후 7 02 34" src="https://user-images.githubusercontent.com/20675065/120784941-952d2800-c567-11eb-90c9-909d775e0e45.png">

어떤 이슈인지 확인 부탁드립니다.
제가 확인해봤을때는 오류는 보이지 않네요.

**Comment by Samsonitekr** [comment]
다음 우편번호 서비스 담당자님,

안녕하세요.
쌤소나이트 코리아 이커머스 팀 이승민 대리 입니다.
우선 빠르게 답변해 주셔서 감사합니다.
제가 아무래도 못 찾는 것 같은데 고객 Q&A 부분에 이미지 첨부를 어떻게 하나요? ;;
우선 메일 상에 첨부드린 것처럼 ‘주소찾기’를 클릭 후 우편번호나 주소는 검색이 가능한데,
붉은색으로 박스친 주소 부분에 바로 주소지를 입력하려고 하면 작동이 제대로 되지 않고 있습니다.
검색이 아예 불가능 하며, 따라서 주소 자동완성도 되지 않고 있습니다. 이 부분 재확인 부탁 드립니다.
감사합니다.


Best regards,

Emma Lee (이승민 대리)
E-Commerce Specialist
Samsonite Korea Limited
12F(Hongwoo Bldg.) #522, Teheran-ro Gangnam-gu, Seoul, 06181, Korea
Tel : 82-2-2007-2947(Dir)
Tel : +82 2 539 7770(Rep)
Fax : +82 2 539 7771

E-mail : ***@***.******@***.***>
http://www.samsonite.co.kr<http://www.samsonite.co.kr/>
NOTICE:
본 메일은 위에 기재된 수신인만을 위해 발송된 것입니다. 만약 본 메일이 잘 못 수신된 경우에는 발송인에게 알려주시기 바라며, 메세지를 즉시 삭제하여 주시기 바랍니다. 협조하여 주셔서 감사합니다.
This message is intended for the addressee only. If you have received this message in error, please notify the author by replying to this message and then delete the message. Thank you.

***@***.***D30BCA.523216B0]

**Comment by Samsonitekr** [comment]
안녕하세요. 
이미지 첨부가 되지 않아 메일로 회신 드렸습니다. 확인 요청 드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@Samsonitekr 
안녕하세요~
답변이 늦었습니다.

메일로 보내주셨다고 하셨는데 메일주소를 goni.r@kakaocorp.com으로 보내주신것 맞으시죠?
현재 메일이 온게 없어가지구요.

그리고 깃허브에 이미지 올리는 것은, 저같은 경우엔 github.com에 직접 들어와서 작성을 하기 때문에 drag&drop 기능으로 바로 업로드가 됩니다.
메일로 보낼때는 잘 모르겠네요;;

**Comment by Samsonitekr** [comment]
안녕하세요. 
보내주신 메일에 회신하기로 보냈는데.. 메일이 안 간 것 같네요ㅠ 
말씀하신 하기 메일로 다시 회신 드렸습니다. 확인 요청 드립니다. 
goni.r@kakaocorp.com

감사합니다.

**Comment by daumPostcode** [comment]
@Samsonitekr 
넵,. 메일 확인하였습니다.

말씀하신 오류는, 저희 사내 공통 서제스트(자동완성) 모듈 문제였고, 그래서 현재 정상동작하는 이전버전으로 롤백진행되었습니다.
지금은 오류 없으실 거에요.

추가로 나중에 모듈업데이트가 되면, 내부 데이터도 좀 변할 수 있어서 자동완성으로 나오는 결과가 조금은 달라질 수 있는 점 참고 부탁드립니다.

**Comment by Samsonitekr** [comment]
다음 우편번호 서비스 담당자님,

안녕하세요.
쌤소나이트 코리아 이커머스 팀 이승민 대리 입니다.
회신 주신 내용 바탕으로 제가 PC와 MO에서 모두 구매하기 단계까지 가봤는데요.
하기처럼 신규주소를 등록하기 위해 ‘우편번호’ 줄에 입력을 하려고 보니 여전히 작동을 하지 않고 있습니다. (입력 불가)
이 부분이 수정이 된 걸까요? 바쁘시겠지만 재확인 부탁 드립니다.
감사합니다.

https://www.samsonite.co.kr/checkout?stage=shipping#shipping


[오류 화면: PC / MO]
***@***.******@***.***D75DDF.74FBFB00]


Best regards,

Emma Lee (이승민 대리)
E-Commerce Specialist
Samsonite Korea Limited
12F(Hongwoo Bldg.) #522, Teheran-ro Gangnam-gu, Seoul, 06181, Korea
Tel : 82-2-2007-2947(Dir)
Tel : +82 2 539 7770(Rep)
Fax : +82 2 539 7771

E-mail : ***@***.******@***.***>
http://www.samsonite.co.kr<http://www.samsonite.co.kr/>
NOTICE:
본 메일은 위에 기재된 수신인만을 위해 발송된 것입니다. 만약 본 메일이 잘 못 수신된 경우에는 발송인에게 알려주시기 바라며, 메세지를 즉시 삭제하여 주시기 바랍니다. 협조하여 주셔서 감사합니다.
This message is intended for the addressee only. If you have received this message in error, please notify the author by replying to this message and then delete the message. Thank you.

***@***.***D30BCA.523216B0]

**Comment by Samsonitekr** [comment]
안녕하세요.
금일 오전 결제페이지까지 해봤는데 동일 이슈 발견되어 메일로 다시 회신 드렸습니다.
확인 요청 드립니다. 감사합니다.

**Comment by daumPostcode** [comment]
@Samsonitekr 
안녕하세요~

제가 현 이슈에 처음 단 댓글처럼, 현재 저희 서비스는 정상적으로 동작하고 있습니다.
메일로 주신 것처럼 "우편번호" 란에 입력이 불가능 하다는게 어떤 뜻인가요?
"우측 우편번호 검은색 버튼"을 누르면 저희 검색팝업이 뜨고, 주소 검색 후 결과를 클릭하면 우편번호가 현재 제대로 들어가고 있습니다.
이렇게 동작되게끔 적용한 것은 저희가 아닌, 샘소나이트 사이트의 개발자 권한이며,
말씀하신 "우편번호 입력란"에 직접 입력을 막아둔 것도 샘소나이트 사이트의 개발자 권한입니다.

저희는 검색 화면과, 주소 데이터만 제공만 합니다.
이부분 확인 부탁드립니다.

**Comment by Samsonitekr** [comment]
다음 우편번호 서비스 담당자님,

안녕하세요.
쌤소나이트 코리아 이커머스 팀 이승민 대리 입니다.
하기 내용 개발팀과 재확인하여 이슈 해결된 것 최종 확인했습니다.
‘직접입력’ 부분은 제가 혼선을 드린 것 같습니다. 죄송합니다.

현재 하기 Q&A 가 일시 오류인지 계속 접속이 안되어 메일로 회신 드립니다.
이슈 해결되어 본 건 종료해도 될 것 같습니다.
모쪼록 도움 주셔서 감사합니다. 😊

https://github.com/daumPostcode/QnA/issues/807



Best regards,

Emma Lee (이승민 대리)
E-Commerce Specialist
Samsonite Korea Limited
12F(Hongwoo Bldg.) #522, Teheran-ro Gangnam-gu, Seoul, 06181, Korea
Tel : 82-2-2007-2947(Dir)
Tel : +82 2 539 7770(Rep)
Fax : +82 2 539 7771

E-mail : ***@***.******@***.***>
http://www.samsonite.co.kr<http://www.samsonite.co.kr/>
NOTICE:
본 메일은 위에 기재된 수신인만을 위해 발송된 것입니다. 만약 본 메일이 잘 못 수신된 경우에는 발송인에게 알려주시기 바라며, 메세지를 즉시 삭제하여 주시기 바랍니다. 협조하여 주셔서 감사합니다.
This message is intended for the addressee only. If you have received this message in error, please notify the author by replying to this message and then delete the message. Thank you.

***@***.***D30BCA.523216B0]

**Comment by daumPostcode** [comment]
@Samsonitekr 
넵~ 확인 감사합니다~ 좋은 하루 보내세요~
