### ISSUE TITLE
about:blank

### ISSUE THREAD

**Issue by Leo-SingleDay** [daumPostcode/QnA#809]
어제까지만 해도 잘됐었는데 갑자기 팝업창이 about:blank로 뜹니다

**Comment by daumPostcode** [comment]
@Leo-SingleDay 
안녕하세요.

말씀하신 결과만 보면 어떤 오류인지 알 수 있는 방법이 없습니다.
좀 더 구체적인 정보를 제공해 주시면 감사하겠습니다.
테스트 환경, 브라우저 정보, 모바일이라면 단말기 정보, 그리고 오류가 나는 사이트 URL및 오류가 나는 페이지 등
자세한 정보를 주시면 좋을 것 같습니다.
