### ISSUE TITLE
react에서도 사용할 수 있나요?

### ISSUE THREAD

**Issue by bjh0226** [daumPostcode/QnA#82]
javascript 말고 react 를 사용하여 화면을 구현하려고 합니다.
react에서도 사용할 수 있나요?

**Comment by daumPostcode** [comment]
@bjh0226 
안녕하세요~

네 제가 react를 자세히 몰라서 정확한 설명을 드리긴 어려운데요,
저희 서비스가 commonJS나 AMD스펙을 따르진 않기 때문에 모듈로 불러와서 사용은 힘드시구,
일반 자바스크립트 라이브러리를 사용하는 것처럼 html파일에 임포트 해주신 후에 사용하시면 될 것 같아요.

아무튼 정확한 코드 설명은 어려운데요, 예전 앵귤러JS에서도 문제가 된, 정적로딩 보다, 동적로딩(저희 [가이드 페이지](http://postcode.map.daum.net/guide)에 보시면 설명이 있습니다.) 방식을 이용하시는 것을 추천드리며,

만드시다가 화면이 안뜨거나 하면 소스코드나 URL등 저희가 확인할 수 있는 무언가를 제공해 주시면 확인해 드리도록 하겠습니다.

일단 못할 것 없을 것 같아요~
