### ISSUE TITLE
우편 서비스 팝업 문의

### ISSUE THREAD

**Issue by RuleTheMoments** [daumPostcode/QnA#824]
다음 우편 서비스 이용중에 2가지 문의 드립니다

1.
`<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>`
 스크립트 참조시 위와 같이 할 경우,
`GET file://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js net::ERR_INVALID_URL`
크롬 브라우저에서 스크립트를 가져오지 못합니다
https 스킴을 붙여서 사용하는게 올바른 사용법인가요?

2.
`<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
$('.findAddressPopup').on('click',function(e){
			// e.preventDefault();
			new daum.Postcode({
				oncomplete: function(data) {
                                 ...
                                 ...
                                 }
			}).open();
		});
	});
`
위 코드로 특정 버튼이 클릭 되었을때, 우편서비스 팝업은 되지만, file 로 열지 않아서 오류가 발생합니다
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').`
그래서, 해당 팝업에서 주소 검색후
- 특정 주소를 선택해도 팝업이 닫히지 않고
- oncomplete 콜백이 호출되지 않습니다

어떤 부분을 살펴봐야할까요?

**Comment by dekim1028** [comment]
저도 동일한 이슈가 발생합니다. 혹시 해결하셨나요?
