### ISSUE TITLE
'대구광역시 동구 매여로 14' 주소 확인 부탁드립니다.

### ISSUE THREAD

**Issue by jieun0o0** [daumPostcode/QnA#84]
대구광역시 동구 매여로 14 가 도로명 주소 사이트에서는 검색이 되어지는데
다음에서는 검색돼지 않습니다.

해당 주소 확인 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@jieun0o0 
네~ 안녕하세요~

해당 주소를 juso.go.kr에서 검색해 보시면, 주소 옆에 지도 마크가 없는 것을 확인하실 수 있습니다.
![2017-01-03 5 01 01](https://cloud.githubusercontent.com/assets/20675065/21602334/3a4bcd12-d1d6-11e6-9342-82d3a713939d.png)

이는 저희쪽으로 데이터가 넘어올때 좌표가 없다는 것으로, 여러가지 케이스가 있지만, 
일반적으로!! 보안이 필요한 장소의 경우 좌표를 넘겨주지 않습니다. (이는 저희가 행자부에 요청을해도 보내주지 않습니다)

현재 저희 우편번호 서비스에서 검색되는 모든 주소는 좌표를 가진 주소들이며, 해당 주소들을 모두 지도에 표기가 가능한 주소들입니다.

그래서 현재 말씀하신 주소 정보는 가지고 있지만, 보안 정책상 노출을 할 수가 없습니다.
해당 주소의 표시 유무에 관련해서는 행자부 측에 별도 요청을 해서 받아들여질시, 노출을 할 수는 있지만, 거의 안되기 때문에,, 일단 보여드릴 수가 없는점 양해 부탁드립니다;;
