### ISSUE TITLE
touchGuideBox에 대해서..

### ISSUE THREAD

**Issue by eebbni** [daumPostcode/QnA#849]
touchGuideBox 라는 id값을 가진 div가 자동으로 계속 생겨나는데, 메뉴얼 어디에도 저렇게 뜨는 예제가 없는데 왜 뜨는지 도대체 모르겠어서 질문드립니다, ㅠ 현재 사용하고자 하는 페이지에서 해당 div가 css가 깨지는 터라 지워버리고 싶은데 방법을 알려주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/51107860/130205907-28b01816-2788-4174-b689-edfee8dbfee4.png)

**Comment by eebbni** [comment]
엔터를 눌렀더니 갑자기 등록되네요, 본문에 적으려 했던 질문은, touchGuideBox  라는 id값을 가진 div가 자동으로 계속 생겨나는데, 메뉴얼 어디에도 저렇게 뜨는 예제가 없는데 왜 뜨는지 도대체 모르겠어서 질문드립니다, ㅠ 
![image](https://user-images.githubusercontent.com/51107860/130205907-28b01816-2788-4174-b689-edfee8dbfee4.png)

**Comment by daumPostcode** [comment]
@eebbni 
안녕하세요~

해당 박스는 IOS에서만 뜹니다.
iOS는 이용자의 input(터치)이 없는 상태에서 스크립트로 inputbox나 이런 컨트롤패널에 스크립트로 제어가 불가능합니다.
그래서 iOS에 한해서 터치를 직접해서 검색하라는 가이드 박스가 뜨는 것입니다.

이는 6년전에 추가된 기능으로, iOS사용자분께서 검색하는 곳이 어딘지 모르겠다고 하셔서 추가된 기능일 거에요.
현재 삭제할 수 있는 옵션은 없습니다. 해당 기능은 추가하더라도 현재 제가 바로 수정할 수 있지가 않아서 시간이 좀 걸립니다.

아무튼 안드로이드나, PC에서는 뜨지 않습니다.

추가로 현재 제가 테스트 했을때는 css가 깨지지 않는데,
현재 개발하시는 사이트의 css가 저희 서비스에 침범한거 보니, 전역 css설정을 하시는게 아닐까 싶습니다.
개발자 도구로 찍으셔서 개발하시는 사이트의 어떤 css코드가 저희 css에 영향을 주는지 파악하셔서 그걸 회피하게 하시는게 어떠실까 합니다.

![image](https://user-images.githubusercontent.com/20675065/130411386-15eebd74-0094-4069-bc27-61d93d396f7d.png)

**Comment by eebbni** [comment]
실제 라이브에 적용해서 확인해보니 안깨지고 잘보이네요 ㅎ pc 개발자도구 > 모바일 적용 후에 본 화면에서는 질문사진과 같이 깨졌는데 실제 라이브 적용 후에는 아이폰 여러 기기 모두 잘 보이는 것으로 확인 되었습니다 감사합니다 :)
