### ISSUE TITLE
도로명주소/ 지번주소 1:N 관련 지원 여부

### ISSUE THREAD

**Issue by eebbni** [daumPostcode/QnA#852]
현재 지번주소:도로명주소 = 1:N 인 경우에 '선택안함'을 제공 하지 않고 
최대한 정확한 도로명 주소입력을 위해 autoMapping값을 false로 두고 사용하고 있습니다. 
근데 문제는 도로명주소:지번주소=1:N 인 경우인데요.. 
도로명주소를 알고있음에도 지번주소가 여러개다 보니 꼭 도로명주소 선택 후 지번주소를 눌러야하더라구요.
지번주소:도로명주소 = 1:N인 경우와 도로명주소:지번주소=1:N 경우를 나눌 수 있는 변수가 따로 없는거 같은데
혹시 있다면 알려주실 수 있는지 없다면 지원의사가 있으신지 여쭤보고 싶습니다 ㅠ

**Comment by eebbni** [comment]
우선 현재 제가 사용하고 있는 상황은 autoMapping값을 false로 두고 사용하고있습니다.
_이유는 **도로명 주소**를 정확하게 제공하고 싶기 때문입니다._ 
1:N의 경우에서 선택하지 않음 버튼을 제공하게 되면 
지번 주소나 임의의 도로명주소의 값을 제공해주어야해서.. 
사용자에게 정확한 도로명 주소값을 전달받기 위해 autoMapping값을 false로 두고 사용하고 있습니다.

문제는 autoMapping값을 false로 해두고 쓰면
도로명-지번이던, 지번-도로명이던 1:N인 경우는 더보기를 통해 두번 클릭을 해야 하는 상황이 발생합니다.
1. 지번-도로명이 1:N인 경우는 제가 원하는대로 지번주소 검색 > 정확한 도로명 주소를 선택하게 유도하기 때문에 상관이 없습니다.
2. 도로명-지번이 1:N인 경우는 도로명 주소 검색 > 정확한 지번 주소를 선택해야 하기 떄문에 여기서 오는 불편함(?) 괴리감..? 이라고 해야할까요.. 이미 본인의 정확한 도로명 주소를 알고 있음에도 지번주소까지 선택해야하는 점이 불편하다고 생각합니다.

2번의 사항을 처리해줄 수 있는 관련 변수나 방법이 궁금했습니다.. 이해가 잘 되셨을지 모르겠네요 ㅠㅠ

**Comment by daumPostcode** [comment]
@eebbni 
넵~ 안녕하세요~

네 정확한 도로명주소를 제공하고 싶어하시는 부분 공감합니다.
그리고 말씀하신 사용법도 이해하였습니다.

1번의 경우엔 목적에 부합하므로 상관이 없으나,
2번의 경우엔 목적에 부합하기보다는 강제?선택의 뉘앙스가 더 느껴지기에 (도로명주소를 아는데 왜 지번주소를 선택하라 하는가에 대한 의문?)
이를 해결할 방법을 찾으시려는 것이군요.

일단 API를 이용하시는 사용자나, 개발자 단에서는 현재 말씀하신 부분을 처리할 수는 없습니다.
즉, 서비스를 제공하는 입장인 저희쪽에서 특정 옵션이나 해결책을 제공해야하는데요.

현재 autoMapping이라는 변수는 지번-도로명, 도로명-지번 매핑관계에 상관없이
1:N 인 상황에서 모두 동작하게 됩니다.

저도 좀 확인해 봐야 되겠지만, 이를 
도로명-지번 1:N 인 상황과
지번-도로명 1:N 인 상황을 구분하여 옵션설정을 하게 하면 해결책이 될 것 같기도 한데.

즉 도로명-지번 1:N인 주소는 autoMapping이 false인 상태로 결과가 나오게 하고
지번-도로명이 1:N인 주소는 autoMapping이 true인 상태로 결과가 나오게끔 하면 될것 같긴 합니다.

이 부분에 대해서는 내부 로직의 연관관계나, 사이드 이펙트 고려해서 적용해 보도록 하겠습니다. 
개발이 완료되면, 추가 댓글과 가이드 페이지(postcode.map.daum.net/guide)가 업데이트 될거에요.

다만, 현재 제가 시간이 좀 나지 않아서, 다음주 이후로나 좀 볼 수 있을 것 같습니다. 이부분 참고해 주시면 감사하겠습니다.

**Comment by daumPostcode** [comment]
@eebbni 
안녕하세요~

매우 늦어서 죄송합니다. 업무 및 개인적인 일이 있어가지고;; 좀 늦었습니다 ㅜ.ㅜ
현재 말씀하신 기능 개선해서 최종 실서버에 배포 되었습니다.

기존의 autoMapping을 쓰면 동시에 다 적용되고
autoMappingRoad : false 연관주소가 도로명일때 도로명 주소 자동매핑을 막음
autoMappingJibun : false 연관주소가 지번일때 지번 주소 자동매핑을 막음

으로 적용되게 하였습니다.

한번 확인 부탁드립니다~
늦게 공유해 드려 죄송합니다.

**Comment by eebbni** [comment]
바쁘실텐데 감사합니다 😊😊😊덕분에 잘 적용하여 사용하고 있습니다.!
