### ISSUE TITLE
oncomplete 반환데이터 중 fullAddress값에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by rktkaktk** [daumPostcode/QnA#855]
1. 주소에 따라 fullAddress값이 있는 주소와 없는 주소가 있던데 차이점이 무엇인가요?
2.문서에는 oncomplete반환데이터 설명에 fullAddress이 없던데 앞으로 없어질 계획인가요?

**Comment by daumPostcode** [comment]
@rktkaktk 

안녕하세요~ 답변이 늦었네요;;

1. fullAddress 라는 변수는 원래 존재하지 않았습니다. 어떤 부분을 보고 말씀하시는지 구체적으로 적어주시면 좋을 것 같습니다.
2. 1번에 이어서 원래 존재하지 않은 데이터이기 때문에 앞으로 없어질 계획이 없지요.(반대로 추가될 계획도 없습니다)

**Comment by rktkaktk** [comment]
넵 감사합니다. 확인했습니다.
