### ISSUE TITLE
시/도 정보를 분리해서 받거나 분리하는 방법이 있을까요?

### ISSUE THREAD

**Issue by ESnark** [daumPostcode/QnA#857]
clayful.io를 사용하면서 이쪽 주소체계에 daumPostcode 결과값을 대응시키려고 하고 있습니다.

그런데 clayful이 해외 주소에도 대응하기 위해서인지 state와 city를 별도로 입력받고 있더군요.

문제는 daumPostcode의 sido가 주소에 따라서 도시이름이 나올때도 있고 도이름이 나올때도 있어서 어떻게 매치시켜야 할지 잘 모르겠습니다.

관련 기능이나 방안이 있으시다면 도움을 얻고 싶습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@ESnark 
안녕하세요

우리나라 주소는

도 - 시 - 구 - 동
도 - 시 - 읍(면) - 리
도 - 시 - 구 - 읍(면) - 리
시 - 구 - 동
시 - 읍(면) - 리

이처럼,  지역 Depth 정보가 그 깊이가 제각각 입니다.
3단으로 이루어진 주소도 있으나 5단으로 이루어진 주소도 있으며,
이를 최대한 묶어서, 신경쓰지 않고도 해당 변수만 모으면 3~5단계 뎁스의 주소가 만들어지게 하려고
sido, sigungu, bname(1/2) 와 같은 변수로 내리고 있습니다.

외국 도로명과 매칭시킬려면, 솔직히, 내려오는 주소 타입을 고려해서 모두 IF-ELSE 분기 처리 해주셔야 합니다.
저도 내부적으로 조합시 그렇게 처리하고 있습니다.

한번 확인 부탁드립니다.

**Comment by ESnark** [comment]
If else 처리하면 될것 같긴 하군요 감사합니다
