### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by chd3wkd** [daumPostcode/QnA#86]
http://postcode.map.daum.net/guide에 접속했을때, 

![2](https://cloud.githubusercontent.com/assets/24926556/21664844/7a781416-d32c-11e6-8328-ab2b42d10d2e.png)
로 나오는게 정상인데 

특정 PC에서만 새로고침을 해봐도

![1](https://cloud.githubusercontent.com/assets/24926556/21664862/8d9872e8-d32c-11e6-98bd-7b988190f8b6.png)

처럼 공백으로 나옵니다. 팝업 우편번호 찾기 눌러도 반응이없고...

크롬,파이어폭스도 안되고 익스플로러 자체문제가 생각되어

액티브X도 삭제해보고 익스플로러를 기본설정으로 바꾸고, 재설치 및 다운그레이드를 해봐도 그대로네요 ㅠㅠ

이럴경우 봐줘야 하는 부분이 있을까요?

**Comment by daumPostcode** [comment]
@chd3wkd 
네~ 안녕하세요;;

특정 PC에서 모든 브라우저에서 동작하지 않는 것이라면,,,
예전에 비슷한 CS가 들어온 경우에서는 공유기 문제가 있긴 했었습니다. (해결은 단순하게도 공유지 재부팅으로 해결하였습니다)

다만, 정상PC와 문제가되는 PC가 같은 공유기에 물려있거나 할시에도 안되는 것이면, 이건 공유기 문제라기 보다, PC방화벽이나 다른 프로그램이 스크립트 로딩을 막고 있는 것 같은데요;;

일단 저희 서비스 팝업이 뜨지 않는다는 것은 저희 우편번호 서비스 JS API가 로딩이 되지 않았다는 것이고,
이 JS API의 도메인이 가이드 페이지와 다릅니다.

API주소는 가이드 페이지에도 나와있지만
http 환경일 경우 http://dmaps.daum.net/map_js_init/postcode.v2.js 입니다.
즉 dmaps.daum.net을 어디서 블락을 하고 있는 것인지, 그걸 찾아서 봐야 될것 같아요. 

네;; 저도 아직 이런 문제를 겪어보지 못해서 정확한 해결책을 말씀드리긴 어려우나, PC와 더불어 PC가 연결되어 있는 인터넷 망도 포함하여 확인해 보셔야 할 것 같아요;;

더 도움이 되지 못해 죄송합니다 ㅜ.ㅜ
