### ISSUE TITLE
모바일기기 (아이폰) 에서 사용시 간섭? 이 발생하는거 같아요

### ISSUE THREAD

**Issue by roammaor** [daumPostcode/QnA#87]
안녕하세요
아이프레임으로 위치삽입하는 방법으로
사용하고자 해서 
삽입하였습니다.
피씨환경에서는 문제 없이 작동하고
모바일기기에서도 잘 되는데
문젠 모바일기기 (현재 아이폰에서만 테스트했습니다만) 에서
검색화면이 호출되고 입력란에 글씨를 입력하면서
관련검색결과?라고 해야 하나요 ,,아무튼 그게 밑으로 쭈욱 뜨는데
그게 입력창을 가려버리게 됩니다.
삽입이 잘못되었거나 스타일문제인가 하고 확인했지만 별다른 이상한것은 없구요
공식사이트인
https://spi.maps.daum.net/postcode/guidessl
를 모바일기기에서 열어서 테스트해도 같은 증상이 있습니다.
정확하게는..타이핑중에 주소검색부분의 위치가 올라가버리는것 같습니다..
확인해봐주실 수 있을까요..
그럼 수고하세요~

**Comment by daumPostcode** [comment]
@roammaor 

네~ 안녕하세요~ 답변이 늦어 죄송합니다;;

먼저, 저희 샘플의 경우에는 이렇게 활용할수 있다~ 라는 것을 말씀드릴려고 작성해 둔 것이며, 실제 태그들이나 styling, javascript로 제어하는 로직은 이용자의 사이트에 맞게 직접 작업을 해주셔야 합니다.

저희가 제공하는 샘플중에 embed(iframe을 이용하는 방법) 하는 샘플은 2가지가 있습니다.
1. iframe을 이용하여 레이어 띄우기
2.iframe을 이용하여 페이지 끼워넣기

이중, 모바일에서 이를 이용할때는 몇가지 문제가 있습니다. 엄밀히 따지면 아이폰(iOS)에서 문제가 있습니다.
다만 이런 문제점이 샘플에 추가가 안되어 있는 것은, 저희 샘플을 위에 말씀드린 것처럼, 활용예제 겸, 대다수의 플랫폼에서 볼 수 있는 최소한의 코드로만 되어 있어서 그렇습니다.

일단 문제점과 해결방법을 설명드리면,
1번의 경우에는 저희 가이드페이지에 빨간색 글씨로 써 있을 거에요; 현재 9.x까지 라고 되어 있지만 현재 10에서도 그대로 재현됩니다. position:fixed를 이용할시 키보드가 올라올때 레이어가 튕겨버리는 문제가 있으며, 이는 이용자께서 적절히 absolute나 기타 방법을 이용하여 제어하셔야 합니다.

2번의 경우에는 1번과 다르게 onresize콜백이 구현된 경우로써, 생성자 옵션에 height값을 넣어 두어도, onresize콜백함수의 구현에 따라 layer의 크기를 변경해 버리게 됩니다. 이때 검색할때 나오는 서제스트(질문자 님의 관련 검색결과)가 본문보다 길어질 경우, iOS에서는 위로 올라가 버리는 현상이 있습니다.
이 또한 해결을 하실려면, onresize콜백이 굳이 필요가 없으시다면, 콜백을 제거하시고, 생성자에 height값을 적당히 조금 넓게 주시면 해결이 되실거라 생각이 됩니다. 또는 embeding target이 되는 layer DOM을 크게 만들고 생성자의 height값을 100%로 입력해 두셔도 됩니다. 만약 onresize콜백함수가 필요하다면 적정 height값 밑으로는 사이즈 조정이 안되도록 방어코드를 onresize콜백에 구현하시면 됩니다.

개인적으로 모바일에서 사이드이펙트가 적어서 추천하는 방법으로는
2번과 1번을 섞어서 쓰는 방법으로, 페이지 끼워넣기 처럼 이용을 하지만 onresize콜백을 구현하지 않는 것을 추천드립니다.

추가적인 질문 사항이 있으시면 언제듯 댓글 부탁드립니다~~
