### ISSUE TITLE
도로명 주소DB에서 검색되지 않는 주소가 카카오 주소 결과에 노출

### ISSUE THREAD

**Issue by susanisgood** [daumPostcode/QnA#874]
도로명 주소(https://www.juso.go.kr/openIndexPage.do)에서 노출되지 않는 주소가 카카오 주소 검색 결과에 노출되고 있는데 확인 부탁드립니다.

도로명 주소에 검색되지 않는 주소명 : 경남 창원시 진해구 사서함 88 (51704)
실제 주소명 : 경남 창원시 진해구 중원로 1 (51698)

**Comment by daumPostcode** [comment]
@susanisgood 

안녕하세요~

사서함의 경우엔, 저희내 내부적으로 매핑을 하여 제공하는 정보이긴 합니다.
말씀하신 주소의 경우엔 "보안주소"에 해당되는 주소이긴 해요.
행안부 도로명검색 시스템에서나, 저희 시스템에서나 검색을 해보면, "지도"를 볼 수 있는 버튼이 막혀있는 것을 확인하실 수 있습니다.
다만 주소 텍스트 자체로는 의미가 있어서 내리는 것인데, 작년에는 이런 데이터는 저희는 내릴 수가 없기도 했어요; 중요 매핑데이터를 빼고 주거든요.

아무튼 사서함의 경우엔 저희가 내부적으로 별도로 매핑해서 제공하는 정보라 보시면 되십니다.

**Comment by susanisgood** [comment]
@daumPostcode 
안녕하세요! 위
에 공유드린 주소 정보(사서함 88)로 인해 물류센터 쪽에서 오류가 발생되고 있는데,
카카오 주소 결과에 노출되지 않게끔 하는 방법은 없을까요?

**Comment by daumPostcode** [comment]
@susanisgood 
아 넵 알겠습니다.
해당건의 경우엔 제가 주소데이터 담당자 분게 전달하도록 하겠습니다.
피드백 오면 바로 댓글 드릴께요~

**Comment by susanisgood** [comment]
@daumPostcode 
도움 감사합니다.
물류센터에서 해당 주소지(사서함 88)의 출고 건에 대해 자동피킹이 불가하여, VOC가 지속 인입되고 있습니다.
바쁘시겠지만 신속한 확인 부탁드립니다!

**Comment by susanisgood** [comment]
@daumPostcode 
안녕하세요,
혹시 추가로 확인된 내용이 있을까요?

**Comment by daumPostcode** [comment]
@daumPostcode 
안녕하세요~ 
주소데이터 담당자분께 답변온 내용 전달드립니다.
현재 사서함 데이터의 경우 행안부에서 데이터를 내려주는게 아닌, 저희가 내부적으로 2달이라는 주기를 가지고 수동갱신을 하게 되는데요.
지금 이 수동갱신이 잘 되지 않아 문제가 발생한 것으로 확인이 됩니다.
그래서 우선은 진해구 내 사서함 데이터를 삭제를 진행하였다고 합니다 (갱신이 너무 오래전에 된 데이터라 삭제)

불편을 드려 죄송합니다.
추후 사서함 데이터의 최신화 관련해선 주소데이터 담당부서에서 프로세스 검토가 진행될 예정이며, 이부분은 추후 결정이 되면 말씀드리도록 하겠습니다.
감사합니다.

**Comment by susanisgood** [comment]
@daumPostcode 
안녕하세요. 빠른 피드백 주셔서 감사드립니다.
유관 부서에 공유하여 처리 완료하였습니다. 다시 한번 감사드립니다~!
