### ISSUE TITLE
주소 검색 값을 창 띄우기전에 보내는방법

### ISSUE THREAD

**Issue by vudrkd34** [daumPostcode/QnA#875]
주소 검색 값을 input 에 미리 적어놓고
주소 모달 창이 열릴때 미리 적어 놓은 값으로 미리 검색해서 창을 띄울수 있는 방법이 있나요?

**Comment by daumPostcode** [comment]
@vudrkd34 
안녕하세요~

https://postcode.map.daum.net/guide#methods

공식 가이드페이지의 함수 부분 참고하시면 되십니다.
open / embed 함수의 매개변수로 전달 가능합니다.

**Comment by vudrkd34** [comment]
와 감사합니다 메뉴얼 좀더 꼼꼼히 봣어야했는데 제가 못봣네요 
알려주셔서 감사합니다 :)
