### ISSUE TITLE
502 Bad Gateway 오류가 발생하고 있습니다.

### ISSUE THREAD

**Issue by ambaigos** [daumPostcode/QnA#877]
오류 원인과 정상화 시점을 알고 싶습니다.

**Comment by daumPostcode** [comment]
@ambaigos 
안녕하세요~

현재 장애는 14시 32분 이후에 발생한 것으로 보이며, 서버 배포 이후 트래픽 관련된 이슈로 서버가 다운이 되서 발생한 이슈로 보입니다.
기능변경건 배포때문에 배포가 진행됬었고, 이후에 발생한 장애이며, 자세한 원인을 현재 파악중입니다.
현재 14시 45분경에 서비스 정상화 되었습니다.
불편을 드려 죄송합니다.
