### ISSUE TITLE
https://postcode.map.daum.net/ 해당 서비스 자체가 너무 느립니다

### ISSUE THREAD

**Issue by ksy84** [daumPostcode/QnA#878]
2021년 12월 06일 14:30분 부터 

현재 35분까지 

https://postcode.map.daum.net/

해당 페이지를 호출하는 주소 검색창이

"502 Bad Gateway"가 뜨거나

너무 느리게 뜹니다.

이 피드를 확인하실 때 쯤에는 해결되었을거 같긴한데

그래도 혹시나 싶어  피드 남겨 드립니다

**Comment by daumPostcode** [comment]
@ksy84 
네 안녕하세요~

네 말씀해 주셔서 감사합니다.
현 깃허브 이슈탭에 이슈 적어주시면 저희도 도움이 되기에 좋습니다.
다만 장애발생시에는 이슈보다는 제가 카카오톡 채널을 더 많이 확인을 해서(깃헙 이슈보다 접근성이 좋아서 훨씬 많이 들어옵니다 ㅜ.ㅜ)
그래서 깃헙으로는 피드백을 바로바로 드릴 수가 없네요 ㅜ.ㅜ

아무튼 현재 해당 장애는 14시 45분에 정상화되었습니다. 불편을 드려 죄송합니다.

**Comment by ksy84** [comment]
다음이 언제될지는 모르겠지만
다음에는 꼭 채널로 남기겠습니다.
빠른 답변, 해결에 감사드립니다.
