### ISSUE TITLE
주소API에 행정동 확인 가능 여부 문의

### ISSUE THREAD

**Issue by goodks** [daumPostcode/QnA#88]
현재 다음에서 제공되는 주소API에서 행정동을 확인 할 수 있는 방법이 있는지 문의드립니다.

예로 도로명주소를 넣었을 때 그 도로명주소에 해당하는
행정동-관할주민센터가 어디인지 보여주는 것입니다.
현재 API에서는 아래와 같이 행정동을 넣어야지만 보이는 것으로 압니다. 

구월1동 000 = 행정동 출력 가능 
구월동 000 = 행정동 출력 불가능 
구월남로 000 = 행정동 출력 불가능

구월남로 000 이런식으로 도로명을 넣었을 경우 행정동(관할주민센터)이 보여질 수 있는 방법이 있는지 문의드립니다.

**Comment by daumPostcode** [comment]
@goodks 
네~ 안녕하세요;;

네 맞습니다. 현재 행정동 출력의 경우에는
검색어를 "행정동명 XX"으로 검색을 할시, 검색어와 검색결과의 법정동과 다른 경우에는 출력을 하고, 데이터를 내리게 됩니다.

즉 적어주신 것처럼 첫번째 케이스에서만 행정동 정보를 가져올 수 있습니다.

다만.. 음 이게 다음주 업데이트 사항이긴 한데요.
행정동 정보를 좀 더 많은 경우에 보여줄 수 있는 옵션을 추가하였습니다.

새로 추가되는 옵션을 설명 드리면,
- 입력되는 검색어와 상관이 없어지고
- 검색결과의 주소들 중, 행정동과 법정동이 다른 케이스는 모두 표시를 하며, 데이터도 내립니다.
- 그래서 별도의 표시가 없는 주소는 행정동과 법정동이 같기 때문에 이때는 데이터를 내리지 않으며, hname이 공백일 경우 bname데이터를 써도 무방합니다.

즉, 위와 같은 방식으로 기능 변경이 되었습니다.
다만 행정동 표시 및 데이터화에 관한 건은, 이 정보를 필요하신 분들에게만 제공하는 것이 좋다고 판단되어, 추가적인 옵션을 활성화 해야지만 동작하도록 하였습니다. (기본값은 false로 현행 동일)

다만 현재 도로명 주소로 검색시, 연관된 지번주소에 행정동 정보가 매핑이 안되어 있는 경우도 있는데요, 이는 CS 인입 또는 별도 확인이 될 경우에 수정하고 있습니다. 반대로 지번주소로 검색을 할경우에는 정상 매핑이 되어 있는 점 참고 바랍니다.

해당 기능은 다음주 월요일 오후 3시 이후에 업데이트가 되며, 이때 한번 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@goodks 
추가적으로, 모든 행정동 정보는 UI상 지번 주소에만 표시되는점 말씀드립니다.

**Comment by daumPostcode** [comment]
@goodks 
안녕하세요. 이전에 안내해 드린바와 같이.
금일 1월 9일 해당 기능이 추가되어 공유드립니다.

기능활성화 옵션은 생성자에 showMoreHName:true로 설정하시면 확인 가능하십니다.

자세한 사항은 http://postcode.map.daum.net/guide#attributes 가이드 페이지 속성부분의 아랫쪽을 참고하시기 바랍니다. 

감사합니다.
