### ISSUE TITLE
http://t1.daumcdn.net/postcode/cssjs/service/1639009145201/service.v2.min.js 오류가 발생합니다.

### ISSUE THREAD

**Issue by svcreate** [daumPostcode/QnA#884]
주소검색부분에 자음하나를 입력하면 
http://t1.daumcdn.net/postcode/cssjs/service/1639009145201/service.v2.min.js 에서 오류가 발생합니다.

사용환경은 C# 에서 webBrowser 를 임베디드하여 사용하고 있습니다.

지금까지 잘 사용해왔는데 최근에 해당오류가 발생합니다.
해결방법 알려주시면 좋겠습니다.

감사합니다.

![20211214_172255](https://user-images.githubusercontent.com/35822823/145960365-8508707e-3f77-4c50-8c56-4cab634dbd8f.png)

**Comment by camomilekr** [comment]
Delphi TWebBrowser 에서도 동일한 상황이 발생하고 있습니다~

**Comment by leo99k** [comment]
Miplatform 내장 브라우저에서도 동일하게 에러가 발생하고 있습니다. 확인 부탁 드립니다.

**Comment by daumPostcode** [comment]
@leo99k 
@camomilekr 
@svcreate 
네 안녕하세요~

현재 순수 IE, 크롬등 일반 브라우저에서는 이슈가 없습니다.
다만 현재 내장 브라우저에서 이슈가 발생하고 있는데요.
1차적으로 파악된 이유로는 내장브라우저들이 reduce, forEach와 같은 JS Array Function을 지원하지 못해서 식별자 오류가 떠서 발생한 이슈였습니다.
현재 이부분 수정되었고, 현재 배포진행 중입니다. 18시 05분 이후에 한번 확인 부탁드립니다.

**Comment by leo99k** [comment]
@daumPostcode 현재 테스트 결과 동일한 오류가 발생합니다.

**Comment by camomilekr** [comment]
네 델파이도 동일합니다~ 몇글자 입력하면 바로 오류가 발생하네요~

**Comment by cgnam01** [comment]
안녕하세요 저희도 현재 같은 증상이 나오고 있습니다 

파워빌더에서 웹뷰 띄운 후 주소 검색시 스크립트 오류가 발생하고 있습니다

**Comment by cubetech2014** [comment]
![image](https://user-images.githubusercontent.com/78395740/145969208-1655e166-676e-474c-be3a-8794dc535f67.png)

**Comment by daumPostcode** [comment]
@leo99k @camomilekr @svcreate @cgnam01
네. 현재 저한테 CS들어온 여러건중에, VB으로 개발을 하신 분은 Array Function제거로 해결이 되었습니다.
그런데 그외 다른 분들은 처리가 안되고 있는데요. 현재 다시 코드를 보고 있습니다.
일반 IE, 크롬 상관없이 네이티브 브라우저는 모두 지원하는 기능인데;; 툴에 들어간 인앱브라우저만 이슈고, 문젠 이 툴들은 제가 한번도 사용해본 적이 없는 툴들이라;; 테스트도 어렵네요;;

일단 원인이 될만한 코드들은 치환작업 하고 있고, 추후 배포 예정 시간이 나오면 말씀드리겠습니다.

**Comment by KIMSANGYEOB** [comment]
@daumPostcode 

고생많으십니다.

Delphi의 경우 내부적으로 IE7버전으로 호환되고 있는데 해당 오류가 발생하네요.

주소검색쪽에 클릭할 때 해당 오류가 발생하네요.

주소검색창에 완전히 비워져있을땐 해당현상이 없는데 검색창에 글자 입력되면 초기화 버튼이 2개 생기는데 해당 관련해서 발생하는 오류로 예상됩니다.

똑같은 코드로 사용했는데 오늘갑자기 위에분들과 같은 에러가 발생했습니다.

![image](https://user-images.githubusercontent.com/30685151/145975205-a86dced8-7b2a-48d8-9b0b-eb3702ef7d75.png)

**Comment by daumPostcode** [comment]
@KIMSANGYEOB 
네. IE7이라면.. 이 브라우저는 제가 10여년전에 개발할때나 보던 브라우저인데;; 지금도 툴에서 쓰이고 있다니....
IE7의 일반사용자는 거의 없다 보셔도 되거든요. 

아무튼 너무 구버전을 이용하는 것 같습니다. 지금 몇몇 분들이 CS를 넣어 주시는데; 대부분 특정 툴위에서 동작하는 브라우저들에서 발생하는 이슈고, 방금도 한분한데 UXStudio라는 툴을 보니 이 툴도 IE7을 부른다고 하네요;; 
IE7은 저희 서비스의 동작방식중에 CORS통신도 우회 모듈을 통해 동작합니다.(꼼수로직으로 돌아가게 됩니다.)
아무튼;; UI가 안깨지는게 신기하긴한데;;(IE6,7,8,9,10은 저도 보장하기가 어렵거든요;;) 의심되는 부분을 하나더 찾아서; 곧 배포할 예정입니다.

**Comment by daumPostcode** [comment]
@leo99k @camomilekr @svcreate @cgnam01 @KIMSANGYEOB 
현재 서비스 배포가 되었습니다. 한번 확인 부탁드립니다.

**Comment by leo99k** [comment]
@daumPostcode 지금 수행해본 결과 동일합니다. 아래 로그가 도움이 될지 모르겠습니다.
![image](https://user-images.githubusercontent.com/18524113/145980383-75ac7526-e2dc-4d37-bb28-da9434af7f25.png)

**Comment by ehdtlrdla** [comment]
저도 확인해보니 키워드 자동완성에서 문제인듯 합니다.
강남을 입력하면 강남관련 주소들이 미리보기처럼 나오는 기능에서 오류입니다

**Comment by daumPostcode** [comment]
@leo99k @ehdtlrdla 
네 그 문제인 것은 알고 있는 내용입니다.
다만, 현재 브라우저 타겟을 IE11 을 비롯한 모던 브라우저에 맞춰서 개발을 진행하는데;
지금 일반 사용자분들의 CS는 전무합니다.

모두 툴을 이용하는 분들의 CS만 있는데; 이 툴들이 현 이슈의 @KIMSANGYEOB 님 말씀처럼 IE7을 불러오는 경우가 있고,
이외 플친으로 대화중인 UXStudio를 이용하시는 분도 IE7을 쓴다고 합니다.
다만 이분은 설정으로 IE11을 부르도록 호출해서 수정하였습니다.

해당 툴들이 너무 오래된 버전의 브라우저를 부르고 있는데, IE7을 위한 폴리픽 작성을 해야해서; 해당 이슈는 시간이 좀 소요될것 같습니다.

그래서 가능하시다면, 유저들이 적어도 IE11(요즘은 윈도우11 때문에 Edge비율이 엄청 상승함)로 맞춰주시는게 어떨까 합니다.

**Comment by leo99k** [comment]
@daumPostcode 고생이 많으십니다. ㅠㅠ
저희가 사용하는 Miplatform 도 내장 브라우저는 IE7 을 사용중이며 이부분은 변경이 안되는 것으로 알고 있습니다.
10년도 더된 시스템이다보니 지원이 안되는게 많네요.

**Comment by KIMSANGYEOB** [comment]
@daumPostcode 

웹뷰 환경에서 각 클라이언트에서 IE 최신버전을 사용하도록 변경하고 사용해보니 문제없이 작동합니다.
(저희 환경의 경우 델파이라 Window OS쪽 웹뷰 환경이 최신 IE로 동작하도록 변경하였습니다.)

다른분들에게도 도움이 되셨으면 좋겠습니다. ㅠㅠ

**Comment by leo99k** [comment]
저희의 경우 로컬 PC에서 레지스트리를 강제로 변경해서 IE11 버전으로 구동은 시켜보긴 했는데요.
그렇게 구동 시키니 이제는 검색으로 나온 결과를 받아오는 부분이 또 문제가 발생하네요. 흠...

**Comment by ehdtlrdla** [comment]
@leo99k  레지스트리 어디부분 작업하셨는지 알려주실 수 있으실까요?

**Comment by leo99k** [comment]
@ehdtlrdla 
저희는 프로그램에서 명령을 통해 생성하였는데요.
결론적으로 위치는 
컴퓨터\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION
위치에 이름 : 실행파일명(저희는 MiPlatform320U.exe) 이고 REG_DWORD 값으로 11001 이 들어가니까 동작을 하긴 합니다.
참고로 IE11 : 11001 / IE10 : 10001 / IE9 : 9999 / IE8 : 8888 / IE7 : 7000 이라고 하네요.

**Comment by ehdtlrdla** [comment]
@leo99k 답변 감사합니다. 한번 해봐야겠어요

**Comment by ehdtlrdla** [comment]
@leo99k 방금 해보았더니 제대로 동작하네요... 사용자 모든 피씨에 레지스트리 추가 할 수가 없는게 문제네요...

**Comment by ehdtlrdla** [comment]
@leo99k  해보니 제대로 동작하는것 확인했습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@leo99k 그 검색을 해서 데이터를 받아오는 부분은 oncomplete부분인데,
이 함수가 호출될때의 데이터 전달은 IE8,9,10,11 other 모두 동일한 postMessage를 이용합니다. 이게 더 안정적이고,
IE6,7은 보안허점을 이용하기 때문에(위 API없음) 더 안좋습니다; (대신 클라이언트의 영향을 없애기위해서 지금처럼 구조가 이상하게 된거긴 합니다)

아마 데이터 전달은 보통 이상없이 될건데 oncomplete함수 내부에서 오류가 나는 경우가 많으니 이부분 한번 체크해 보시는게 어떠실까 합니다.

**Comment by camomilekr** [comment]
저희는 고객 pc가 아직도 xp 운영체제 쓰시는 분들도 많아서 레지스트리로 해결을 보기엔 좀 무리라고 판단하고 내장 웹브라우저의 스크립트 오류를 무시하는 옵션을 줘서 일단 임시 해결을 했는데요. 가능하시다면 ie7 에서도 동작할 수 있도록 잘 처리를 해주시면 감사드리겠습니다. ㅠ

**Comment by daumPostcode** [comment]
@ehdtlrdla @leo99k @camomilekr @KIMSANGYEOB 
안녕하세요. 폴리필 작성에는 시간이 좀걸려서, 임시적인 오류 회피방법을 제안드립니다.

저희 API 생성자 옵션에는, 제가 가이드페이지에 오픈을 하진 않았으나,
useSuggest 라는 옵션이 있습니다. 이 값은 기본적으로 true인데, 이값을 false로 설정하여 일단 오류를 회피해 주셨으면 합니다.

한번 확인 부탁드립니다.

**Comment by leo99k** [comment]
@daumPostcode 생성자가 어느 부분을 얘기하시는건지요?

**Comment by daumPostcode** [comment]
@leo99k 
저희 API생성자입니다.

new daum.Postcode({/* 이부분이 생성자 옵션*/});

즉
new daum.Postcode({ 
      oncomplete: function(data){ .......},
      useSuggest: false
}).open() //or embed()

이런식으로 oncomplete 함수와 같은 위치에 넣어주시면 됩니다.

**Comment by vvoosuki** [comment]
감사합니다.. useSuggest 옵션으로 임시조치 해결 완료되었습니다 (파워빌더 내장 웹브라우저)

**Comment by leo99k** [comment]
@daumPostcode 저희도 해당 옵션 넣어서 일단 조치는 완료하였습니다. 감사합니다. 고생 많으세요.

**Comment by welcom2choi** [comment]
감사합니다.. useSuggest 옵션으로 임시조치 완료되었습니다 
XPlatform 9.2.2 런타임

**Comment by daumPostcode** [comment]
@ehdtlrdla @leo99k @camomilekr @KIMSANGYEOB @svcreate @vvoosuki @welcom2choi 

안녕하세요~
지금 IE7관련된 폴리필 작성 및, IE7에서만 동작하지 않는 몇몇 코드들 확인해서 수정작업을 완료하였습니다.
재택이라 테스트 환경 구축이 쪼오끔 어려워서 확인이 늦었네요;;

현재 코드 수정은 완료됬고, 배포는 16일 오전에 진행하도록 하겠습니다. 제가 배포하고 다시 답글 남기도록 할께요.
감사합니다.

**Comment by hoya5325** [comment]
파워빌더 웹뷰 환경에서 스크립트 에러가 갑자기 떠서 어제 하루 종일 원인 파악하고 당황스러웠는데, 
위에 알려주신 useSuggest 옵션 적용하여 우선 해결했습니다. 고맙습니다.

**Comment by daumPostcode** [comment]
@ehdtlrdla @leo99k @camomilekr @KIMSANGYEOB @svcreate @vvoosuki @welcom2choi @hoya5325 
안녕하세요. IE7대응 관련된 수정로직이 적용 배포되었습니다.
배포시에 다른 문제가 있어서 배포가 좀 늦었네요;;
한번 확인 부탁드립니다. 감사합니다.

**Comment by welcom2choi** [comment]
정상동작 확인했습니다. 그런데 useSuggest 옵션은 어떻게 할가요? false로 두고 있는데..

**Comment by ehdtlrdla** [comment]
@daumPostcode  정상작동 확인했습니다. 감사합니다.

**Comment by daumPostcode** [comment]
@welcom2choi 
네 그 옵션은, 공식적으로 가이드페이지에 노출한 기능은 아니지만, 간혹가다 필요하신 분들이 있어서 만들어둔 기능으로,
없애거나 그러진 않을거에요. 필요에 의해서 셋팅해서 사용하시면 될것 같습니다.

@ehdtlrdla 
넵 확인 감사드립니다 %%

**Comment by leo99k** [comment]
@daumPostcode 
정상 작동 확인하였습니다. 감사합니다. 수고많으셨습니다.
