### ISSUE TITLE
스크립트 오류 문의 http://t1.daumcdn.net/postcode/cssjs/service/1639475785179/service.v2.min.js 

### ISSUE THREAD

**Issue by arimakty** [daumPostcode/QnA#885]
자동완성 기능시 스크립트 오류가 발생하고 있습니다.

저희는 IE, 크롬으로 이용하지 않고 넥사크로라는 UI프레임워크를 이용하고 있습니다.

다른 문의사항에 저희와 동일한 UI프레임워크는 없던데 혹시 다른 창구를 통해서 문의받의신 내역이 있으신지 문의드립니다.

아울러 조치전까지 저희 쪽에서 어떤 방법으로 스크립트 오류 발생이 안나게 할 수 있을지 가이드를 받을 수 있을까요...?

**Comment by daumPostcode** [comment]
@arimakty 
네 안녕하세요.
바로 아래의 이슈에서 확인하실 수 있는 것처럼, 저는 일반 사용자를 대상으로 일반 브라우저를 대상으로만 테스트를 진행합니다.
어제 처음으로, 이렇게 많은 작업툴들이 있다는 것을 알게됬고, 또한 이 툴들이 브라우저를 에뮬레이션 할때 IE7을 이용한다는 것도 알았습니다;;;

IE7은.... 정말 너무 구브라우저라;;(실제 이용하는 고객은 저희 kakao 인입 서비스 대비해서 0에 가깝다고 보심됩니다.)
아무튼, 이 부분은 어제 배포후에 판단된 것으로써, 현재 결론은 폴리필을 작성해야 해결이 될것으로 보입니다.
처음에는 Array Function 이슈인줄 알았는데, 이걸로는 한분만 해결됬고, 나머지 분들은 안되더라구요.

그래서 일단 제가 폴리필을 작성하고 테스트하는데 시간이 걸리기 때문에,
검색에는 영향이 없는 서제스트를 일시적으로 사용을 막아주시기 바랍니다.

useSuggest : false

로 생성자에 추가를 하면 서제스트가 사용되지 않습니다. 이는 비공식 옵션이긴 하나, 구현되어 있는 기능인지라(CS대응용)
한번 이걸 추가해서 회피해 주시기 바랍니다.

**Comment by daumPostcode** [comment]
@arimakty 
안녕하세요~
지금 IE7관련된 폴리필 작성 및, IE7에서만 동작하지 않는 몇몇 코드들 확인해서 수정작업을 완료하였습니다.
재택이라 테스트 환경 구축이 쪼오끔 어려워서 확인이 늦었네요;;

현재 코드 수정은 완료됬고, 배포는 16일 오전에 진행하도록 하겠습니다. 제가 배포하고 다시 답글 남기도록 할께요.
감사합니다.

**Comment by daumPostcode** [comment]
@arimakty 
안녕하세요. IE7대응 관련된 수정로직이 적용 배포되었습니다.
배포시에 다른 문제가 있어서 배포가 좀 늦었네요;;
한번 확인 부탁드립니다. 감사합니다.
