### ISSUE TITLE
팝업창에서 위에있는 주소표시줄

### ISSUE THREAD

**Issue by PrimeCrice** [daumPostcode/QnA#89]
about:blank이라고 뜨는데 아예 주소표시줄을 안보이게 할수없나요??

**Comment by daumPostcode** [comment]
@PrimeCrice 
네~ 안녕하세요; 답변이 늦어 죄송합니다.

네; 현재 저희가 제공하는 open()함수를 이용한 방법으로는 제거가 불가능합니다.

제거를 하고 싶으시다면, 팝업을 직접 만드시고, 그 팝업안에 embed함수를 통해 레이어로 꽉차게 띄우시는 방법이 있습니다. 한번 참고 부탁드립니다.
