### ISSUE TITLE
<완료 - 장애 공유> 현재 11시 30분경 부터 전사 서비스 장애가 있습니다.

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#898]
안녕하세요. 

우편번호 서비스 담당자입니다.

현재 11시 30분부터 전사 서비스 장애가 있어서,

현재 담당자 분들께서 확인중에 있습니다.

이로 인한 여파로 저희 서비스까지 문제가 발생했고, 전체 알림을 보내는 서비스또한 접속이 어려워서; 이렇게 깃허브에 기록으로 남겨둡니다.

불편을 드려 죄송합니다.

**Comment by chrisKILee** [comment]
복구가 완료 된것일까요? 아니라면 언제 복구 예상되는지요?

**Comment by raidyth** [comment]
복구 예상 시간은 알기어렵나요?

**Comment by hmmhmmhm** [comment]
고생하십니다! 복구 얼른 성공하시길!

**Comment by lemondkel** [comment]
https://careers.kakao.com/index 여기도 안되네요

**Comment by daumPostcode** [comment]
@lemondkel @chrisKILee @raidyth @hmmhmmhm 

이게 저희쪽 서비스 서버 이슈라기 보다,
전사 네트워크 인프라쪽 이슈라서, 저희가 어떻게 조치할 방법이 없네요;;;

해당 네트워크 관련 부서에서 현재 조치중이고 저희도 상황을 지켜보고 있습니다 ㅜ.ㅜ

**Comment by Youngking0914** [comment]
카카오 서버를 통하는 서비스는 전부다 먹통인것같네요 카카오맵도 안되는걸보니.. 화이팅입니다!

**Comment by daumPostcode** [comment]
@lemondkel @chrisKILee @raidyth @hmmhmmhm @Youngking0914 

안녕하세요. 우편번호 서비스 담당자입니다.

현재 일부 대역은 복구가 된것으로 보입니다.
다시 재발할 가능성은 확실히 알 수는 없으나, 

현재 우편번호 서비스는 정상 접근 가능하십니다.

이후 추가적인 이슈가 있으면 댓글 드리도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by BitYoungjae** [comment]
화이팅!

**Comment by JRevirthuum** [comment]
고생하셨습니다!

**Comment by daumPostcode** [comment]
@lemondkel @chrisKILee @raidyth @hmmhmmhm @Youngking0914 @BitYoungjae @JRevirthuum

현재 KT망에서 접근이 안된다는 제보가 많습니다.
담당부서에서 확인중인데요; 

처리가 되는데로 말씀드리도록 하겠습니다.

**Comment by seohyosang** [comment]
세상에...

**Comment by norn00** [comment]
고생 많으십니다.  'KT망 별도로 점검해 봐야한다.' 로 받아드리면 될까요?

**Comment by daumPostcode** [comment]
@lemondkel @chrisKILee @raidyth @hmmhmmhm @Youngking0914 @BitYoungjae @JRevirthuum @seohyosang @norn00

안녕하세요 우편번호 서비스 담당자입니다.

현재 복구가 거의 된 것으로 확인이 됩니다.
문제가 있는 대역이 모두 조치가 된 것은 아니라, 현재 우편번호 서비스가 물려있는 대역은 복구가 된것 같아요.

혹시 아직도 문제가 발생한다면 공유해 주시면 담당 부서에 공유하도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by raidyth** [comment]
고생하셨습니다.

**Comment by moosongsong** [comment]
고생하셨습니다!!

**Comment by edoko** [comment]
고생하셨습니다 :)

**Comment by mz-ycg** [comment]
👍

**Comment by hubeen** [comment]
👍

**Comment by yoon6763** [comment]
👍
