### ISSUE TITLE
잠원동 클릭시 지번이 안나옵니다.

### ISSUE THREAD

**Issue by youngju-mool** [daumPostcode/QnA#9]
잠원동을 검색시

06531 (137-905)
도로명 서울 서초구 강남대로 557 (성한빌딩)
지 번  서울 서초구 잠원동 37-7

위에 처럼 나오는데요. 여기서 도로명을 선택하면 
data.jibunAddress  의 값이 공백으로 나옵니다.

![Uploading jam.gif…]()

**Comment by youngju-mool** [comment]
도로명과 지번이 1=1 매핑이 안되는건 지번이 안나오는거군요. ^^ 
제가 잘 몰랐습니다.

**Comment by daumPostcode** [comment]
@youngju-mool

ㅎㅎ 넵^^
추가적으로 jibunAddress변수에는 값이 안들어 가더라도 autoJibunAddress 부분도 확인 부탁드려요. 이부분은 저희 가이드 페이지의 속성 부분을 쭉 읽어보시면 아실 수 있습니다 ~

그럼 즐거운 하루 보내세요~
