### ISSUE TITLE
도로명 주소 검색 결과에 대한 문의입니다.

### ISSUE THREAD

**Issue by singha12** [daumPostcode/QnA#90]
안녕하세요.
도로명 주소 도입과 관련해서 다음에서 제공하는 API를 분석하고 있는 중입니다.
검색결과에 도로명 주소, 지번 주소가 함께 검색이 되는데,
도로명 주소만 결과 출력이 가능한지 궁금해서 문의 드립니다.
답변 부탁 드립니다.
감사합니다.

**Comment by daumPostcode** [comment]
@singha12 
안녕하세요~

아쉽지만, 현재 도로명 주소만 표시하는 기능은 없습니다.
항상 도로명-지번 또는 지번-도로명 주소로 매핑이 되어 표시되며, 검색어에 따라 연관관계가 자동 설정되어 검색이 되기 때문에, 현재로써는 제공하기 어려운 점 양해 부탁드립니다.
