### ISSUE TITLE
페이지에 끼워 넣기 방식 사용 시 모바일에서의 스크롤 문제

### ISSUE THREAD

**Issue by cheonmux** [daumPostcode/QnA#909]
안녕하세요.

아이프레임을 이용한 끼워 넣기에 관해 문의 사항이 있습니다.

아래와 같이 예시로 나와있는 코드를 거의 그대로 사용하되, 워드프레스에 맞춰서 조금만 수정했습니다.

```
<script>
	// 빌링 우편번호 검색 스크립트임.
    // 우편번호 찾기 찾기 화면을 넣을 element
    var element_wrap = document.getElementById('wrap');

    function foldDaumPostcode() {
        // iframe을 넣은 element를 안보이게 한다.
        element_wrap.style.display = 'none';
    }

    function sample3_execDaumPostcode() {
        // 현재 scroll 위치를 저장해놓는다.
        var currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);
        new daum.Postcode({
			  oncomplete: function (data) {
                    document.getElementById('billing_postcode').value = data.zonecode;
                    document.getElementById('billing_address_1').value = data.address;
                    document.getElementById('billing_address_2').focus();
                
                element_wrap.style.display = 'none';

                // 우편번호 찾기 화면이 보이기 이전으로 scroll 위치를 되돌린다.
                document.body.scrollTop = currentScroll;
            },
            // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분. iframe을 넣은 element의 높이값을 조정한다.
            onresize : function(size) {
                element_wrap.style.height = size.height+'px';
            },
            width : '100%',
            height : '100%'
        }).embed(element_wrap);

        // iframe을 넣은 element를 보이게 한다.
        element_wrap.style.display = 'block';
    }
</script>

```

그리고 아이프레임으로 표시될 위치를 아래와 같이 wrap 엘리멘트를 추가 했습니다.

```
<script>
	//빌링에 wrap 엘리멘트 추가
    const parent = document.querySelector('#billing_postcode_find_field');
    const billingField1 = document.querySelector('#woocommerce-input-wrapper');

    const newDiv = document.createElement('div');
    newDiv.setAttribute('id', 'wrap');
   newDiv.style.cssText = 'display:none;width:100%;margin:5px 0;position:relative;overflow:hidden;';

       parent.insertBefore(newDiv, billingField1);
</script>
```

우선, 작동은 잘 됩니다만... 모바일에서 주소를 선택 시 스크롤이 내려가버리는 문제가 있습니다 ;;  ([gif링크](https://imgur.com/a/T76ysg7))

원인이  `document.getElementById('billing_address_2').focus();` 의 focus 인걸 알고 있습니다만... 해결 방안을 대체 모르겠습니다...

혹시 해결방법이 있다면 알려주실 수 있으신지요?

감사합니다

**Comment by daumPostcode** [comment]
@cheonmux 
안녕하세요~

음.... 해당 페이지에 우편번호서비스가 삽입되고 검색되고 선택할때의 스크롤 위치가, 
우편번호서비스페이지가 사라진 다음의 위치값과 같아서 이동되는 것일 수 있습니다.

보통 이럴때는 제가 서비스 개발할때 종종 트러블슈팅으로 하는 방법인데

setTimeout을 이용해서 약간 딜레이를 주면서 포커스를 주던가, 아니면 setTimeout을 이용하되 스크롤의 위치를 다시 상단으로 이동시키는 방법도 있을 것 같습니다. 우편번호 검색팝업이 뜨기전의 scrollTOP의 위치를 뽑아낸 다음에, 닫힌 후에 일정 시간 후에 다시 해당 스크롤 위치로 올리는 방법도 있을 것 같긴 합니다;;

한번 참고해 보세요;

**Comment by cheonmux** [comment]
@daumPostcode 님 안녕하세요.

답변 정말 감사합니다. 

알려 주신 내용을 보고 몇 번 테스트를 다시 해보았습니다. 

테스트를 해보니 근본 원인이 포커스가 아니라,  주소를 입력 후 세부 주소를 선택하는 부분 ([스크린샷](https://i.imgur.com/0CTjDWT.jpg))에서 해당 주소를 클릭하면 그 클릭한 위치로 스크롤이 이동되어 버립니다. 

예를 들어 
검색 시 제일 위에 나타나는 세부 주소를 클릭하면 스크롤이 변화가 없습니다.
반면 제일 아래에 나타나는 세부 주소를 클릭하면 아이프레임이 접히면서 마지막 클릭 위치로 이동하는 것 같습니다..

혹시 이런 경우에도 답변 해 주신것처럼 "scrollTOP의 위치를 뽑아낸 다음에, 닫힌 후에 일정 시간 후에 다시 해당 스크롤 위치로 올리는 방법도 있을 것 같긴 합니다" 방법 밖에 없을까요? ;;

감사합니다.

**Comment by daumPostcode** [comment]
@cheonmux 
음.. 해당 스크롤 문제는 알고 있던 이슈여서,
저희가 샘플을 제작할때도, 다시 스크롤을 원위치 시키는 로직이 들어가 있긴 합니다.
다만 현재 샘플의 코드가 제대로 동작하진 않네요 ㅎ;;(이건 수정하면 될것 같고;;)
즉, 당시에 서비스 배포를 할때도 스크롤 이슈 때문에 스크롤 위치를 원래대로 돌리는 부분이 필요하다 느꼈고, 이를 스크롤 자체를 제어하는 방식으로 해결을 봤던 것 같습니다.

어찌됬던 본문자체의 스크롤을 조작하는 것이기 때문에, 스크롤이 내려가 있다면, 해당 값으로 유지가 되는건 맞습니다.
다만 유지가 안되는 경우도 있는데, 우편번호 서비스가 삽입된 후 맨 아래로 내렸을때 스크롤값이 1000이라 한다면, 우편번호서비스가 삭제된 후에 본문 자체의 스크롤 값이 1000보다 작을경우, 스크롤 위치값이 안맞기 때문에 초기값으로 들어가 버릴겁니다. 아마 최상단으로 올라갈거에요. 즉 이러한 경우가 아니라면 스크롤이 유지가 될 수밖에 없습니다.
body를 건드는 것이라;; 

아무튼 스크롤 값을 변경해 주는게 개인적으론 최선같아 보이긴 합니다. 끼워넣기 예제로는 이게 한계일 수 있습니다.
https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll 네이티브 함수로는 이러한 함수가 있으니 참고해 보세요. 공식가이드의 예제는 잘못되었습니다.

**Comment by cheonmux** [comment]
@daumPostcode 님 안녕하세요.

도와주셔서 정말 감사합니다. 

처음과 끝의 `document.body.scrollTop = currentScroll;` 부분 대신에                 `document.getElementById('billing_address_2').scrollIntoView();`
를 사용하여 해결하였습니다.

감사합니다!
