### ISSUE TITLE
결과 값 전체 받기

### ISSUE THREAD

**Issue by EUNGB** [daumPostcode/QnA#911]
안녕하세요.

안드로이드에서 우편번호 검색 API를 사용하고 있는데,
  oncomplete: function(data) 에서 받는 data 전체를 안드로이드에 넘기고 싶은데
  어떤식으로 넘겨받아야 하나요?
  
  window.Android.processDATA(data);
  
  를 하면 안드로이드에서 Object 타입으로 변환하는 방법이 따로 있을까요?

**Comment by daumPostcode** [comment]
@EUNGB 

안녕하세요~
해당 부분은 저희가 제공하는 API의 영역이 아닙니다.
데이터를 받은 이후의 처리는 개발자님의 몫으로, 제가 안드로이드 개발자가 아니라서;; 방법은 잘 모르겠습니다;;;
