### ISSUE TITLE
placeholder 문자열 사용자지정 안되서 일어나는 현상

### ISSUE THREAD

**Issue by codi-dev** [daumPostcode/QnA#915]
마우스 오른쪽 버튼을 눌러 붙여넣기를 하면 placeholder 문자열이 사라지지 않고
붙여넣은 문자열이 함께 보여저서 판독이 어려워지는 현상이 일어남.

**Comment by daumPostcode** [comment]
@codi-dev 
제보 감사드립니다.
마우스 오른쪽버튼까진 고려하지 못했네요.
참고해서 수정하도록 하겠습니다.

**Comment by daumPostcode** [comment]
@codi-dev 

안녕하세요~ 늦었네요;;
금일 해당 버그 수정되어 배포되었습니다.
확인 부탁드립니다. 감사합니다.

**Comment by codi-dev** [comment]
확인했습니다 감사합니다 :)
