### ISSUE TITLE
Http와 Https 에서 주소 표시 방식이 다릅니다

### ISSUE THREAD

**Issue by DevSusu** [daumPostcode/QnA#92]
API 만들어 주셔서 정말 만족스럽게 잘 쓰고 있습니다! 그러나 최근에 http와 https에서 차이가 나는 점이 생긴 것 같아 문의합니다

일단 아래 화면은 [https://spi.maps.daum.net/postcode/guidessl#attributes](https://spi.maps.daum.net/postcode/guidessl#attributes) https 화면이구요

<img width="414" alt="screen shot 2017-01-09 at 18 00 37" src="https://cloud.githubusercontent.com/assets/5153025/21761358/c0fb93ec-d695-11e6-8058-16d6851ce71a.png">

여기에서는 경기'도' 라고 붙어서 나오는데,

아래 화면은 [http://postcode.map.daum.net/guide#upgrade](http://postcode.map.daum.net/guide#upgrade) http 입니다

<img width="411" alt="screen shot 2017-01-09 at 18 00 43" src="https://cloud.githubusercontent.com/assets/5153025/21761377/dd26a908-d695-11e6-92b4-d275ef6fa869.png">

여기에는 경기 라고만 나옵니다..!
콜백으로 반환되는 데이터의 `sido` 속성에도 '도' 가 붙어서 나옵니다

<img width="101" alt="screen shot 2017-01-09 at 18 08 50" src="https://cloud.githubusercontent.com/assets/5153025/21761495/b6ec4bca-d696-11e6-9f94-a3083b01bf4a.png">

최근에 https 쪽의 반환 형식이 달라진 것 같은데, 둘 중 하나로 통일이 되어야 하지 않을까 하는 생각에 이슈 올립니다.

**Comment by daumPostcode** [comment]
@DevSusu 
네~ 안녕하세요~

일단, 경기도 와 경기 로 표시가 되는 것은 shorthand 옵션 설정에 따른 표출 방식이 달라져서 그렇습니다.

기본값으로 shorthand가 true이며, 그래서 축약형(서울특별시 -> 서울, 경기도 -> 경기, 단 세종특별자치시, 제주특별자치도 제외)으로 표시가 됩니다.

일단 저희 가이드페이지에는 생성자에 넣는 추가옵션이 들어가 있는 샘플은 없습니다. 즉 shorthand또한 true로 기본값으로 셋팅되어 있을 건데;; 이거 이상하네요;;

현재 제가 확인가능한 PC에서는 정상으로 보입니다만, 아까전에 서비스 실서비스 배포가 있었는데, 그 타이밍에 서로 다른 서버를 바라봐서 그럴 수도 있겠네요; 

일단 WIndows10 + Edge, Mac + Chrome or Safari에서는 재현이 안되어서요;; 혹시 지금도 그러실까요??

**Comment by DevSusu** [comment]
앗 그렇네요 지금은 그 현상이 사라진 것 같습니다..

제가 테스트했던 환경은 Mac + Chrome 이었구요 El Captian(10.11.6)에 Chrome(55.0.2883.95) 이었습니다

그 당시 실서버 배포가 있었다면 그렇게 다르게 보일수도 있었겠군요.. 우선 혹시나 이런 점을 다시 발견한다면 알려드리도록 하겠습니다! 지금은 괜찮아졌습니다 ㅎㅎ 친절한 답변 정말 감사합니다
