### ISSUE TITLE
안녕하세요. 구글에서 검색링크 들어가면 에러 나네요. 경로 수정 하셔야 될 것 같아요!

### ISSUE THREAD

**Issue by seokho7** [daumPostcode/QnA#921]
<img width="579" alt="캡처" src="https://user-images.githubusercontent.com/82761546/169457767-6fe5142d-5ad0-412d-8c0a-2d1c091c2281.PNG">
'다음 우편번호' 검색해서 들어가면

<img width="839" alt="캡처2" src="https://user-images.githubusercontent.com/82761546/169457804-26404a5c-82bf-43e1-9c2a-dcc6394c590a.PNG">

이런 화면이 뜨고 눌러야 홈으로 이동해요!

**Comment by daumPostcode** [comment]
@seokho7 
네~ 안녕하세요~

해당 동작은 정상적인 동작이긴 합니다.
저희 서비스 API는, 단순하게 주소를 검색하고 화면을 확인하는 서비스가 아니라,
API를 제공하는거라, 검색뷰를 바로 접근하게 되면 저런 메세지를 띄우긴해요 ㅎㅎ

구글에서 저희 URL을 기본페이지만 크롤링한것 같은데; 한번 해당 부분은 확인해 보겠습니다.
