### ISSUE TITLE
웹취약점 SRI 적용 postcode.v2.js

### ISSUE THREAD

**Issue by PaltanRoad** [daumPostcode/QnA#928]
웹 취약점 점검에서 발생하는 아래 스크립트의 SRI 적용에 대한 문의 드립니다.
<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
관련 이슈 검색을 해보니 과거 2018년에 (#332) 지원하지 못한다는 답변이 있었습니다. 그 이후 현재에도 이 부분은 동일한 것인지, 해당 취약점에 대한 보완을 제공하고 있으신지 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@PaltanRoad 
안녕하세요~

네 현재의 API제공 정책의 경우 Latest 버전을 자동으로 배포 및 적용되는 방식으로 되어 있어서, 현재 SRI를 적용하기 어렵습니다.
이를 적용하려면, 현재의 Latest 배포가 아닌, 각 버전별로 제공이 필요하며, 업데이트가 된경우 모든 사용자에게 PUSH를 해야 합니다.
다만 현재 우편번호 서비스 API는 사용자를 특정할 수 없습니다. 그 누구나 이용할 수 있기 때문에, 현재 적용을 할경우 사용자에게 알릴 방법이 없습니다.(공지 및 카카오톡채널을 통한 알림의 경우에도 모든 사용자가 등록되어 있지 않습니다)

즉 이 건은 우편번호서비스 API가 카카오 Developers에 정식 등록이 되고, 사용자를 특정할 수 있을때,
그리고 정책이 Latest가 아닌 버전별 배포가 가능할때, 지원이 될 수도 있는데요. 문젠 저희 서비스는 JS API외에도, 실제 겁색뷰의 경우 저희쪽 도메인의 서비스가 동작되기 때문에 이와 연결되는 인터페이스의 변경에도 제약이 생기기 때문에, 현재로써는 좀 고민해야할게 많습니다.
API가 완전히 바뀔 수도 있거든요. 

아무튼 그때와 마찬가지로 현재도 SRI적용은 좀 어렵습니다.
현재 SRI적용을 무조건 하셔야 한다면, 직접 JS파일을 다운로드 받으셔서 직접 서버에 올리신 후에, 해시값을 뽑은후에 직접 운영하는 방식은 있습니다. 다만 이렇게 될경우 저희가 업데이트를 진행하면 직접 다시 이 작업을 반복해 주셔야 합니다. 현재 몇몇 사이트에서 이렇게 이용하시는 분들이 계시는데; 이전의 삼성닷컴 이슈처럼, 저희쪽 서비스페이지가 업데이트 될때, 인터페이스 상이함으로 인해, 서비스 자체가 먹통이 되는 경우가 발생할 수 있습니다.
이는 맨 위에 적은, 사용자 특정이 안되기 때문에 발생하는 이슈입니다. (이렇게 쓰고 있다는 것을 알게된 것도, 업데이트 후 장애가 발생한다는 것을 역추적해보니 알아낸 것이지요.)

아무튼 현재로 해당건 지원은 어렵습니다. 

현재 우편번호 서비스는 저희 카카오에서 제공하는 Open API와 들과 다르게 완전 독립적으로 제공을 하고 있는데요.
현재 내부적으로 이렇게 제공하는게 운영이슈가 크고, 장애발생시 대응이나 알림이 어려워서, 그해서 운영 획일화를 생각하고 있긴 합니다.
즉 적용이 되더라도 시간이 좀 소요될 것 같습니다.
