### ISSUE TITLE
다음 우편번호 서비스 이용시 로컬 저장에러

### ISSUE THREAD

**Issue by williamkorean** [daumPostcode/QnA#93]
이렇게 사용중입니다. 그런데 
<script src="https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js"></script>
위 소스를 로컬에 저장해서 사용할수 없나요? 로컬에 저장하니 에러가 발생하고 
캐릭터셋이 euc-kr 인데 위 소스에는 utf-8 이더군요. 
캐릭터셋 바꾸니 아예 작동도 안되고. ㅠㅠ
 프로그램 초보인지라 어떻게 손을 대야 할지 막막합니다. 

<script src="https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js"></script>

<script>

 function openDaumPostcode1() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수

                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    fullAddr = data.roadAddress;

                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    fullAddr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('bzip').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('baddress1').value = fullAddr;

                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('baddress2').focus();
            }
        }).open();
    }
</script>

<script>
  function openDaumPostcode2() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수

                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    fullAddr = data.roadAddress;

                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    fullAddr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('rzip').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('raddress1').value = fullAddr;

                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('raddress2').focus();
            }
        }).open();
    }
</script>

<script>
  function openDaumPostcode3() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수

                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    fullAddr = data.roadAddress;

                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    fullAddr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('zip').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('address1').value = fullAddr;

                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('address2').focus();
            }
        }).open();
    }
</script>

**Comment by daumPostcode** [comment]
@williamkorean 
네~ 안녕하세요~

일단 openDaumPostcode1 <- 이 함수의 안에 있는 내용은, 내려받은 데이터를 조합하는 부분이기 때문에 저희 가이드 페이지의 속성 부분을 참고하셔서 (http://postcode.map.daum.net/guide#attributes) 어떤 어떤 데이터를 내리는지 확인하시고 개발하시면 될 듯 합니다.

그리고 JS API코드를 로컬에 저장해서 이용해야하는 이유가 있으실까요?
저희 API는 postcode.v2.js코드 말고도 추가적으로 더 호출하며, 해당 코드를 로컬에 저장하여 이용할시, 저희의 업데이트나 기타 서비스 지원을 받으실 수 없습니다.

단순하게 이용하실 때에는 저희 가이드페이지의 예제 부분만 참고하셔서 개발하셔도 충분합니다. 
또한 저희 FAQ (https://github.com/daumPostcode/QnA)를 한번 읽어보시면 더욱 도움이 되실 것 같습니다.

**Comment by williamkorean** [comment]
빠른 답변 감사합니다. 저희가 ssl 통신을 하는데요.. 크롬에서 교차 스크립트로 인한 외부 url이 감지가 되어 일단 경고 문구가 뜨고요.. 캐릭터셋이 utf-8 이더라구요. 저희 서버는 euc-kr 이라 js 파일을 로컬에 저장해서 소스의 utf-8 부분을 euc-kr 로 바꾸니 아예 작동을 않합니다. ㅠㅠ 프로그램 초보인지라... 어딜 수정해야 할지..
------ Original Message ------
Date: Monday, Jan 9, 2017 07:21:59 PM

**Comment by daumPostcode** [comment]
@williamkorean 
ssl 통신이라면

https://spi.maps.daum.net/postcode/guidessl <- https용 API를 쓰시면 되실 거에요~, 저흰 http와 https용이 도메인이 서로 달라서 ㅎㅎ, 다만 API사용방법은 동일하기 때문에 저 가이드 페이지 들어가서 호출하는 JS API의 주소만 바꿔주시면 됩니다. 그리고 현재까지 케릭터셋이 다를때의 문제는 현재까진 없었습니다. 저희가 제공하는 모든 API는 기본적으로 UTF-8 인코딩을 사용하고 있기도 하구요.

한번 확인해 보시겠어요?

**Comment by williamkorean** [comment]
빠른 답변 진심으로 감사합니다.  이거 하나만 더 체크 부탁드립니다. 크롬에서 개발자 모드로 처리 과정을 보면 이런 경고 문구가 발생합니다.이 경고 문구 때문에 js소스를 로컬에 저장하려고 했던 것입니다.  어떻게 회피해야 할지..  postcode.v2.js:1 A Parser-blocking, cross-origin script, https://s1.daumcdn.net/svc/attach/U03/cssjs/postcode/1483947597955/170109.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details. 
------ Original Message ------
Date: Monday, Jan 9, 2017 07:32:08 PM

**Comment by daumPostcode** [comment]
@williamkorean 
네~ 해당 경고성 문구는, 크롬에서만 발생하는 것으로 API로딩시 API를 사용하는 로직과 불러오는 core스크립트와 실행 순서를 보장하기 위해 일부러 document.write를 통해 스크립트를 불러와서 그렇습니다.
해당 문구는 속도가 느린 환경에서 페이지의 렌더링을 블락할 수 있다는 뜻에서 크롬에서 띄워주는 것인데요.
실제 현재까지 위 이슈로 인해 오류가 발생한 점은 없습니다.

다만 어느정도 완화를 할 수는 있는데요.
1. 오류메세지는 없어지지 않지만, postcode.v2.js스크립트를 body맨 아랫부분에서 호출하시면 중간에 페이지가 블락당하는 일을 막으실 수 있습니다. 다만, body맨 아랫부분까지 실행되기 전에 윗부분에서 new daum.Postcode라는 코드가 실행이 되면, 객체가 없다는 오류가 발생합니다. 다만 보통 만드실때 우편번호 찾기 버튼을 눌렀을때 new daum.Postcode가 실행되기 때문에 큰 문제는 없으실 거에요(저희 샘플대로 하셨다면.) 그게 아닌 즉시실행의 경우에는 문제가 될 수 있습니다.;

2. 저희 가이드페이지의 상단에 '기본 사용법'에 있는 동적로딩 기능을 사용하시면 해결이 됩니다.
해당 기능은 document.write를 사용하지 않고 script태그를 통해 동적으로 불러오기 때문에, 현재 코드로는 바로 사용하지 못하며, 가이드 페이지에 있는 것처럼 daum.postcode.load함수로 wrapping해주셔야 합니다. daum.postcode.load함수가 호출될때 core 스크립트를 로딩하고 실제 비지니스 로직을 콜백으로 실행하는 것으로 생각하시면 됩니다. 이와 같은 방식은 앵귤러나 리액트 같은 동적 렌더링을 위주로한 SPA어플을 만들때 이용하시면 좋으나, 질문 주신 오류를 해결하는 방법에도 충분히 적용가능 하니 한번 확인 부탁드립니다.

이외 다른 질문 사항이 있으시면 언제든 이슈나 댓글 부탁드립니다~
감사합니다.
