### ISSUE TITLE
Uncaught TypeError : Cannot read property 'action' of null

### ISSUE THREAD

**Issue by egaoneko** [daumPostcode/QnA#937]
안녕하세요. 이전에도 올라왔던 이슈와 유사한 이슈가 발생하고 있어서 문의차 이슈를 등록했습니다.

다름이 아니라 모니터링 도구에서 지속적으로 Duam 주소 API 스크립트에서 다음과 같은 오류가 발생하고 있어서요.

```js
Uncaught TypeError: Cannot read properties of null (reading 'action')
    at c.postMessage.c.postMessage.c.postMessage.a.customMessageHandler (postcode.v2.js:1:13726)
```

[이전 이슈](https://github.com/daumPostcode/QnA/issues/547)로는 adblock 으로 인한 이슈로 발생했던 것 같았는데, 제 경우에는 [특정 플러그인](https://chrome.google.com/webstore/detail/awesome-screenshot-and-sc/nlipoenfbbikpbjkfpfillcgkoblgpmj?hl=ko)에서 이슈가 발생하고 있음을 확인할 수 있었습니다.

다만 모니터링 도구에서는 iOS, Android, OSX, Window 각기 다른 디바이스에서 해당 오류가 수집되고 있네요.

![image](https://user-images.githubusercontent.com/6583941/179460959-5d66612a-dcf7-432e-bf63-46d1a1d0e9c5.png)

Post Message로 받은 값이 충돌하는 것으로 보이는데, 혹시 이 부분에 대해서 방어 로직 추가될 수 있을까요?

![image](https://user-images.githubusercontent.com/6583941/179461049-220da210-4a85-4693-87ee-6419e951ca43.png)

**Comment by daumPostcode** [comment]
@egaoneko 
안녕하세요~

방어로직 추가를 검토하려면 제가 재현을 해봐야 합니다.
해당 현상이 발생하는 재현조건을 구체적으로 알려주시기 바랍니다.

스샷으로는 방어로직 추가를 감으로 해야하는데; 현재 수십만 사이트에서 이용하고 있는 서비스라 잘못하면 장애로 이어질 수 있습니다.
즉 구체적인 재현환경을 알려주시면 확인후 조치하도록 하겠습니다.

**Comment by daumPostcode** [comment]
@egaoneko 
안녕하세요~

네 해당 플러그인 알려주셔서; 설치해서 테스트해보았습니다.
해당 플러그인이 권한이 좀 강력한것 같은데, 브라우저의 현재 페이지에 postMessage관련 콜백을 등록하는 것 같습니다.

그래서 shortcut관련된 메세지를 계속 보내는 것으로 보이는데요.
그래서 해당 메세지가 저희 우편번호 서비스에서 사용하는 데이터 포맷과 달라서 발생한 이슈로 보입니다.
일단 방어코드는 추가 가능하고, 다행이라면 다행으로 저희는 IE6 부터 대응을 한 서비스라서........ postMessage(IE8이상)를 통해 전달할 수 있는 데이터 중에 제일 낮은 버전에 맞게 개발되어 있어서 쉽게 구분이 가능합니다.

아무튼 테스트를 좀더 해보고, 배포는 다음주 월요일날 가능할 것 같습니다.
이부분 참고 부탁드립니다.

제보해 주셔서 감사합니다.

**Comment by daumPostcode** [comment]
@egaoneko 
안녕하세요~

개발하고 테스트해본 결과, API로직에서만 수정이 되면 되기에;
금일 20시 20분에 실서버 배포되었습니다.

현재 말씀하신 테스트 방식으로는 오류가 뜨지 않는데, 한번 확인 부탁드립니다.

**Comment by egaoneko** [comment]
@daumPostcode 

너무나도 빨리 수정해주셔서 감사합니다! 제 PC에서 바로 확인이 가능했던, 오류는 바로 사라진 것은 확인하였습니다. 🙏

로그를 통해 수집되는 iOS 15.5의 Chrome 브라우저도 발생하던 페이지에서 오류가 수집되지 않고 있는 것으로 보입니다. 요 부분은 좀 더 테스트를 해보고 사용량이 많은 시간에도 모니터링 해보겠습니다.

다시 한번 감사드립니다! 🙇‍♂️

**Comment by egaoneko** [comment]
@daumPostcode 

지난 주말간 모니터링 해봤을 때 추가적인 오류 알림이 더 이상 오지않아서 공유드립니다~ 생성한 이슈는 종료하겠습니다.

빠르게 대응해주셔서 감사합니다. 🙇‍♂️
