### ISSUE TITLE
다음 우편번호 검색 시 undefined 가 뜹니다.

### ISSUE THREAD

**Issue by cho6988** [daumPostcode/QnA#94]
사이트에서 회원가입시 주소 입력란에 다음 우편번호 검색기능을 사용하고 있습니다.

http://www.moa-ba.com/register.php?action=register

 

업그레이드가 되고 난 뒤에 아래 링크 가이드에 따라 파일 수정했는데,

 http://postcode.map.daum.net/guide#upgrade 

주소검색을 하고, 해당 주소를 선택하면 주소란에 undefined 라는 문구가 뜹니다.

아래는 회원가입form  php파일 주소 부분 소스입니다.

--------------------------------------------------소스-----------------------------------------------------------

        <? //if ($config[cf_use_addr]) { ?>
        <TR bgcolor="#FFFFFF">
            <TD >주소</TD>
            <TD valign="middle" class=m_padding>
                <table width="330" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td height="25"><input class=m_text type=text name='zip1' size=4 maxlength=3 readonly <?=$config[cf_req_addr]?'required':'';?> itemname='우편번호 앞자리' value='<?=$this->UserInfo[mb_zip1]?>'>
                         - 
                        <input class=m_text type=text name='zip2' size=4 maxlength=3 readonly <?=$config[cf_req_addr]?'required':'';?> itemname='우편번호 뒷자리' value='<?=$this->UserInfo[mb_zip2]?>'>
                        &nbsp;<a href="javascript:;" onclick="win_zip('memberform', 'zip1', 'zip2', 'addr1', 'addr2', 'addr_jibeon');" align=absmiddle><img  src="<?=$gConf['TEMPLATE_URL']?>/image/post_search_btn.gif" border=0 align=absmiddle></a></td>
                </tr>

                <tr>
                    <td height="25" colspan="2"><input class=m_text type=text name='addr1' size=60 readonly <?=$config[cf_req_addr]?'required':'';?> itemname='주소' value='<?=$this->UserInfo[mb_addr1]?>'></td>
                </tr>

                <tr>
                    <td height="25" colspan="2"><input class=m_text type=text name='addr2' size=60 <?=$config[cf_req_addr]?'required':'';?> itemname='상세주소' value='<?=$this->UserInfo[mb_addr2]?>'></td>
                </tr>

				<tr>
				<td height="25" colspan="2">
				<input type="hidden" name="addr_jibeon" value="<?=$this->UserInfo['addr_jibeon']; ?>">
				<span id="addr_jibeon"><?=($this->UserInfo['addr_jibeon'] ? '지번주소 : '.$this->UserInfo['addr_jibeon'] : ''); ?></span>
				</td>
				</tr>

                </table>
            </TD>
        </TR>
        <? //} ?>

**Comment by daumPostcode** [comment]
@cho6988 
네~ 안녕하세요~

php부분소스만 가지고는 오류를 확인하기가 힘듭니다. undefinded가 뜬다는 것은 oncomplete콜백함수의 인자로 넘겨주는 데이터 중 존재하지 않은 변수를 이용했다는 것인데요. 

원인을 파악하려면 javascript코드가 필요합니다;;;

그리고 본문에 적어주신 사이트에서는 정상적으로 추소가 표출이 되기도 하네요;;;

다시 댓글 주실 수 있으실까요?
