### ISSUE TITLE
Daum Postcode Service가 먹통입니다.

### ISSUE THREAD

**Issue by HeavyRotdung** [daumPostcode/QnA#947]
일부 사이트에서 Daum Postcode Service를 사용 주소검색을 하게 하는데요..
주소검색버튼을 클릭한 후 팝업창이 뜨고 나서 주소검색을 해야 하는 팝업창 화면이 그냥 화이트스크린 상태로
정지된 상태입니다. 사용 브라우져는 Microsoft Edge 최신 버전이고 운영체계는 Window 10입니다.

**Comment by HeavyRotdung** [comment]
www.manello.co.kr<http://www.manello.co.kr>
www.tradelab.co.kr<http://www.tradelab.co.kr>

두 곳 모두 안 되는 대표적인 곳입니다. 비회원 구매 한번 진행해서 주소 입력 시 우편검색 해보시죠

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by daumPostcode** [comment]
@HeavyRotdung 
음 혹시 Edge에서 특수한 익스텐션을 이용하실까요?
또는 엣지 브라우저가 최신의 크로미움을 이용한 버전일까요? 아니면 Windows10의 초창기 Edge전용 엔진을 탑재한 초창기 버전일까요?

일단 제가 가진 Windows 10 최신버전(최신 업데이트) Edge최신에서는 정상으로 나옵니다.
제가 개발환경이 Mac이라서, 별도의 Windows PC에서 테스트 하였습니다.
![20220907_093803](https://user-images.githubusercontent.com/20675065/188807646-1e64f320-b53f-4ba7-9e52-786581d21ba9.jpg)
![20220907_093818](https://user-images.githubusercontent.com/20675065/188807696-25e2bd26-32b2-453a-887c-2d57a7efc302.jpg)

둘다 모두 검색화면이 정상적으로 뜨고 있고, 검색도 잘되며, 주소 삽입도 정상적으로 되고 있습니다.

참고로 올려주신 문의 외에;
현재 저희가 공식적으로 가이드하지 않는 방식의 스크립트 로딩방식을 이용하고 있습니다.
해당 방식은 이전에는 지원했으나, 현재 deprecated됬고, 추후에 삭제할 계획이므로

https://postcode.map.daum.net/guide 공식 가이드 페이지에 있는

//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

이 스크립트를 이용해 주시면 감사하겠습니다.

아무튼 해당 문의에 대해서는 조금더 구체적인 정보가 필요합니다. 특정 익스텐션이 구동중이라면 한번 삭제를 해보시고,
아니면 우편번호 버튼 누르는 화면에서 개발자도구를 띄운 상태에서, 우편번호검색 버튼 눌렀을때 개발자도구의 콘솔에 뜨는 경고나 오류메세지를 캡쳐해 주시기 바랍니다.

또한 팝업창에 포커스를 두고 개발자도구를 띄워서 거기에도 떠있는 오류메세지를 한번 캡쳐해서 올려주시기 바랍니다.
재현이 안되기 때문에 원인 파악이 어렵네요;;

일단 현재 저희 우편번호서비스는 7월 21일 이후로 패치를 한적이 없기 때문에; 이 시기 이후에 동작하다가 최근에 안된것이면, 저희 서비스를 띄우는 페이지나, local 이슈일 가능성이 큽니다.

참고 부탁드립니다.

**Comment by HeavyRotdung** [comment]
adBloc이라는 광고차단 익스텐션을 사용했는데, 알려주신 사이트주소를 차단금지로 처리하니까 제대로 뜹니다. 감사합니다.  보낸 사람: Daum 우편번호서비스보낸 날짜: 2022년 9월 7일 수요일 오후 3:49받는 사람: daumPostcode/QnA참조: HeavyRotdung; Mention제목: Re: [daumPostcode/QnA] Daum Postcode Service가 먹통입니다. (Issue ***@***.***음 혹시 Edge에서 특수한 익스텐션을 이용하실까요?또는 엣지 브라우저가 최신의 크로미움을 이용한 버전일까요? 아니면 Windows10의 초창기 Edge전용 엔진을 탑재한 초창기 버전일까요?일단 제가 가진 Windows 10 최신버전(최신 업데이트) Edge최신에서는 정상으로 나옵니다.제가 개발환경이 Mac이라서, 별도의 Windows PC에서 테스트 하였습니다.둘다 모두 검색화면이 정상적으로 뜨고 있고, 검색도 잘되며, 주소 삽입도 정상적으로 되고 있습니다.참고로 올려주신 문의 외에;현재 저희가 공식적으로 가이드하지 않는 방식의 스크립트 로딩방식을 이용하고 있습니다.해당 방식은 이전에는 지원했으나, 현재 deprecated됬고, 추후에 삭제할 계획이므로https://postcode.map.daum.net/guide 공식 가이드 페이지에 있는//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js이 스크립트를 이용해 주시면 감사하겠습니다.아무튼 해당 문의에 대해서는 조금더 구체적인 정보가 필요합니다. 특정 익스텐션이 구동중이라면 한번 삭제를 해보시고,아니면 우편번호 버튼 누르는 화면에서 개발자도구를 띄운 상태에서, 우편번호검색 버튼 눌렀을때 개발자도구의 콘솔에 뜨는 경고나 오류메세지를 캡쳐해 주시기 바랍니다.또한 팝업창에 포커스를 두고 개발자도구를 띄워서 거기에도 떠있는 오류메세지를 한번 캡쳐해서 올려주시기 바랍니다.재현이 안되기 때문에 원인 파악이 어렵네요;;일단 현재 저희 우편번호서비스는 7월 21일 이후로 패치를 한적이 없기 때문에; 이 시기 이후에 동작하다가 최근에 안된것이면, 저희 서비스를 띄우는 페이지나, local 이슈일 가능성이 큽니다.참고 부탁드립니다.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
