### ISSUE TITLE
주소 검색 결과 정보가 없어 문의합니다.

### ISSUE THREAD

**Issue by syschangs** [daumPostcode/QnA#95]
안녕하세요
행정자치부 도로명주소 검색시스템에서는 아래 주소가 검색되는데
다음주소에서는 검색결과 정보가 없습니다.
답변 확인 부탁드립니다.

주소검색
충남 당진시 채운동 363-23

**Comment by daumPostcode** [comment]
@syschangs 
네~ 안녕하세요;

해당주소의 경우 행자부도로명시스템에서는 검색이 되는데, 검색 결과를 보시면 지도 마크가 없습니다.
행자부에서 검색이 되는데 지도마크가 없는 경우는
'보안 주소'라고 저희는 관리를 하고 있는데요, 해당 주소는 기본적으로 좌표를 가지고 있지 않습니다. 행자부에서는 가지고 있을지 몰라도, 저희에게는 내려주지 않아요.

저희 시스템이 주소정보를 관리하는 주요키로 좌표값을 이용하기 때문에, 해당 주소는 좌표값이 없으니 나오지 않는 것이에요;

다만 이는 내부적으로 '우편번호를 검색하는 시스템'이니 좌표가 없는 주소라도 표시하는게 맞다, 아니다 기존의 정책대로 유지하는게 맞다 라는 의견이 갈리고 있어서, 논의가 진행 중입니다.

현재 언제 표시를 하게될지, 계속 못하게 될지는 알 수 없는데요;; 

지금은 검색결과를 내릴 수 없는 점 양해 부탁드립니다;;
