### ISSUE TITLE
주소지 관련 문의입니다.

### ISSUE THREAD

**Issue by hongjiyoon** [daumPostcode/QnA#950]
안녕하세요.

찰스앤키스 e커머스 담당자 입니다.
현재 찰스앤키스 온라인스토어 주문 시 카카오 API통해서 주소지를 기입하고 있습니다. 
최근에 "세종시" 주소지에서의 주문이 되지 않는 건으로 인해 카카오 담당자분과 싱가포르 본사 담당자분이 연락을 취하신 것으로 알고 있습니다만, 한국 지사에서 직접적인 컨택을 희망합니다.

문의 확인되시면 jiyun.hong@charleskeith.com으로 메일 부탁드립니다.
전화드리겠습니다.

**Comment by daumPostcode** [comment]
@hongjiyoon 

안녕하세요~
이 깃헙 이슈로 소통을 해도 담당자와 직접 컨택하는 것과 같습니다.
어떤 부분 때문일까요?

만약 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)과 같은 이슈라면, 행안부 도로명주소검색사이트를 통해 조치하셔야 함을 공유 드립니다.

참고 부탁드립니다.

**Comment by hongjiyoon** [comment]
도로명 주소 검색 사이트에서 검색시 나오는 주소지 (세종특별자치시) 입니다만, 
고객이 해당 주소지를 선택하셨을 때 주소지 저장이 되지 않아, 결제 화면이 넘어가지 않는 이슈가 발생하고 있습니다. 

세종시는 주소지가 "세종특별자치시"이고 이 보다 더 상위 주소가 없는데, 
상위 주소부분이 공란이라서 주소 저장이 되지 않는다는 답변을 받았습니다. 
이 것은 카카오 API측과 확인을 해야 한다고 들었는데, 해결이 가능한 부분일까요? 

![image](https://user-images.githubusercontent.com/115678179/195506438-cf351660-5137-4c4c-ae28-2a25cecc608d.png)

**Comment by daumPostcode** [comment]
@hongjiyoon 
안녕하세요~

올려주신 데이터의 경우 저희가 내리는 데이터가 아닙니다.
<img width="697" alt="스크린샷 2022-10-13 오후 3 58 07" src="https://user-images.githubusercontent.com/20675065/195524410-18a753bb-8b07-4364-ba07-8e67c55e7aff.png">

<img width="536" alt="스크린샷 2022-10-13 오후 3 57 32" src="https://user-images.githubusercontent.com/20675065/195524390-5c5ddc65-0c82-4229-b94c-557466feecfd.png">

위 스샷을 보시면 아시겠지만; 말씀하신 것처럼 세종시의 경우 이보다 상위 뎁스는 korea말곤 없습니다.
그래서 저희 데이터에도 sido 부분에 해당 데이터를 넣고 있습니다.

경기도 검색결과를 보면 뎁스별로 매칭은 동일하게 되어 있습니다.

대한민국 주소의 경우 이 depth가 3단계부터 5단계까지 좀 다양합니다.
모든 주소지가 동일하지 않습니다. 
주소에따라 
시+도로명 도 있고(세종시의 경우)
시+구+도로명
도+시+구+도로명
도+시+구+읍/면+도로명 등 여러가지 케이스가 있습니다.

즉 저희가 내린 데이터에서 각 필드별로 데이터를 나눠서 해당 홈페이지에 삽입을 하는 것은 저희가 해결해드릴 이슈는 아닙니다.
한번 홈페이지 담당자 분께 문의를 해보셔야 될것 같습니다.

**Comment by hongjiyoon** [comment]
감사합니다. 내부적으로 다시 담당자 찾아서 검토해보겠습니다.
