### ISSUE TITLE
<서비스장애공유> 서비스 장애 알림 드립니다. 

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#951]
안녕하세요.
우편번호서비스 담당자입니다.

현재 판교데이터센터에 화재발생으로 인해 우편번호서비스,카톡, 지도등을 비롯한 여러 서비스의 접속 장애가 지속되고 있습니다.
(정확한 사유가 나오면 추후 공유 드리겠습니다)

현재 내부적으로 복구에 힘쓰고 있으며 최대한 빠르게 복구될 수 있도록 하겠습니다.

서비스 이용에 불편을 드려 죄송합니다

**Comment by daumPostcode** [comment]
<중간 공유>
안녕하세요 우편번호 서비스 담당자 입니다.

현재 전사 서비스들이 복구에 최대한 노력중이긴 합니다만, 모든 서비스가 복구되는데 시간이 걸리고 있습니다.

현재 우편번호 서비스는 별도의 서버에 서버구동은 성공하였지만, 전사 CDN서버의 복구가 아직 진행 중이라 우편번호 서비스는 아직 동작하지 않습니다.

불편하시겠지만 조금만 더 기다려 주시면 감사하겠습니다.

**Comment by kkak10** [comment]
@daumPostcode 혹시 복구 된걸까요?

**Comment by daumPostcode** [comment]
@kkak10 
안녕하세요~

답변이 늦어서 죄송합니다. 현재 중요 서비스들은 최대한 복구를 하고 있는 상태입니다.
다만 몇몇 리소스들이 누락된 경우가 있어서 이를 포함하여 다시 전체적으로 체크하고 있습니다.

다시 한번 불편을 드려 죄송합니다.

**Comment by kkak10** [comment]
@daumPostcode 괜찮습니다. 장애로 다들 밤낮으로 노력해주시는 노고에 감사드립니다 🙏

**Comment by daumPostcode** [comment]
<중간공유>

안녕하세요 우편번호서비스 담당자입니다.
현재 우편번호서비스의 오류가 나던 현상은 대부분 복구가 되었습니다.
이용을 하는데에는 큰 문제가 없으나, 현재 몇몇 리소스들의 500에러가 발생하고 있어서

이 부분을 잡는데 시간이 좀 소요될것으로 보입니다.

우편번호 서비스는 불특정 다수의 사용자분들이 사용하시는 서비스라 최대한 빨리 복구를 하고 공지를 해드리고 싶었으나,
이 서비스와 더불어 여러 연관된 서비스들이 엮여있어서 좀 늦은점 진심으로 사과드립니다.

현재 동작이 가능하게끔 hotfix 버전을 배포해 두었으며, 추후 이러한 작은 오류 또한 모두 해결이 된다면 새로운 공지 이슈글로 말씀드리도록 하겠습니다.

한가지 추가로 말씀드리고 싶은점은
저희가  21년도 초부터 "t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" 로 JS API를 하나로 일원화를 하였는데,
기존의 legacy도 같이 유지하고 있었습니다. 

기존의 legacy라 함은 ssl.daumcdn.net, dmaps.daum.net 도메인을 사용하는 API로,
현재 위 도메인으로 시작하는 JS API를 사용하신다면, t1.daumcdn.net으로 시작하는 도메인으로 변경해 주시기 바랍니다.
이는 공식 가이드페이지에도 설명이 되어 있으며, migration 방법도 특별한게 아닌 URL만 바꿔주시고 테스트 해주시면 되는 것이라 꼭 변경해 주시면 감사하겠습니다.

아무튼 최대한 빠른 복구를 위해 노력하겠습니다. 
감사합니다.
