### ISSUE TITLE
주소검색이 안됩니다.

### ISSUE THREAD

**Issue by gidammam** [daumPostcode/QnA#952]
josoro에서도 검새이 되는데 안되네요.

행정중앙1로 95입니다.
![Screenshot_20221015_211219](https://user-images.githubusercontent.com/115878304/195986245-63f1ad5d-df76-4bc4-bd2c-80edfcacba2e.jpg)

**Comment by daumPostcode** [comment]
@gidammam 
안녕하세요~

현재 판교데이터선테 화재로 인해, 카카오의 많은 서비스에 장애가 발생하고 있습니다.
우편번호 서비스의 경우, 저희 단독으로 구성된 서비스라기 보다, 여러 API를 이용하고 있는 서비스라, 현재 모든 서비스가 복구되기 전까지는 서비스 장애가 있을 것 같습니다.

서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
