### ISSUE TITLE
주소검색안됩니다.

### ISSUE THREAD

**Issue by Kim-Ha-jung** [daumPostcode/QnA#953]
경기도 광주시 초월읍 현산로 119 행정안전부 도로명주소 검색하면 나오는데 여기서는
검색이 안됩니다.
![화면 캡처 2022-10-15 214249](https://user-images.githubusercontent.com/115879469/195987472-5fbc4848-5009-4754-88c2-522ec39af8bb.png)

**Comment by daumPostcode** [comment]
@Kim-Ha-jung 

안녕하세요~

현재 판교데이터선테 화재로 인해, 카카오의 많은 서비스에 장애가 발생하고 있습니다.
우편번호 서비스의 경우, 저희 단독으로 구성된 서비스라기 보다, 여러 API를 이용하고 있는 서비스라, 현재 모든 서비스가 복구되기 전까지는 서비스 장애가 있을 것 같습니다.

서비스 이용에 불편을 드려 죄송합니다 ㅜ.ㅜ
