### ISSUE TITLE
주소가 검색이 안되네요 

### ISSUE THREAD

**Issue by jiwonder16** [daumPostcode/QnA#954]
아래 주소인데, 행정 시스템에는 검색 결과가 나옵니다.
다음 주소시스템에서는 검색이 안되네요 . 등록해주세요. 

경기도 포천시 군내면 반월산성로 193-6

**Comment by daumPostcode** [comment]
@jiwonder16 

안녕하세요~
현재 판교데이터센터 화재로 인해 현재 전사 서비스가 원할하지 않습니다.
오늘 새벽은 지나야 가능할 것 같습니다 ㅜ.ㅜ
현재 검색이 안되는 것은 주소데이터 이슈라기보다는 화재로 인한 전사 서비스 장애라. 이 문제가 해결이 되면 자동적으로 복구가 될것으로 보입니다.

https://github.com/daumPostcode/QnA/issues/951
공지사항 참고 부탁드립니다.

불편을 드려 죄송합니다.
