### ISSUE TITLE
광역단체(시,도) 축약 옵션 문의

### ISSUE THREAD

**Issue by iamytg** [daumPostcode/QnA#96]
v2를 반년 전 정도부터 사용중인데요. 저희는 shorthand 옵션의 존재여부도 몰랐습니다.
지금도 지정하지 않고 있는데요.

개발자가 여러 플랫폼에서 테스트했을 때나, 이제껏 거의 1년 동안
광역단체 명칭이 2글자를 넘는 경우가 없었는데, (서울, 경기, 전북, 제주 등)
오늘 회사 직원 중 한 분의 컴퓨터에서 2글자를 초과하는 케이스가 발견됐습니다. (경기도)

아시다시피 shorthand 옵션은 기본값이 true 잖아요.
근데 false에 해당하는 결과가 나오는 경우가 발견된 것으로 보여요.
확인 부탁드립니다.

**Comment by HelloSolsol** [comment]
저희서비스에서도 위와 같은 동일한 현상이 나와서 이렇게 댓글을 남깁니다.
shorthand 기본값 사용중인데 광역시가 저장되는 경우가 발생했습니다.
확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@iamytg @HelloSolsol 
네~ 안녕하세요!

불편을 드려 죄송합니다.
해당 문제는 이번 기능 추가로 인해 몇몇 파라미터가 변경되었습니다. 다만 이게 100%재현이 아니라 특정 PC에서 발생하는 것은 JS API가 캐쉬가 먹어서 아마 최신 core스크립트가 로딩이 안되서 발생한 것으로 확인이 됩니다.

문제가 발생한 PC의 브라우저의 캐쉬를 지워보시면 해결이 되실 것 같으며, 
또한 170111버전으로 방금 재배포를 했습니다.

다시 확인해 주실 수 있으실까요?

**Comment by HelloSolsol** [comment]
@daumPostcode 빠른 답변 잘받았습니다. 
특정 PC의 상황이 저희쪽에서도 확인이 안되는데

@iamytg 님께서 해당 직원PC로 한번 테스트 한번 해봐주시면 감사하겠습니다.

저희쪽 몇몇 PC는 20170109버전에서도 축약형관련 이상없이 이용가능했습니다.

**Comment by daumPostcode** [comment]
@HelloSolsol 
네~ 맞습니다 이는 저희쪽 서버 캐싱도 영향이 있구요, 파라미터가 변경되기전 버전이 170109버전으로 나간적이 있으며, 파라미터가 수정된 버전이 같은 이름으로 나갔었습니다. 내부 테스트시 큰 문제가 없어서 실서버 테스트만 하였는데요, 배포 직후부터 몇몇 분들께 CS가 들어왔었습니다. 다만 새로고침 후, 재부팅 후 정상동작하는 경우가 많았는데.

금일 해당 이슈가 지속적으로 발생하는 것 같아, 버전을 변경하여 재배포 하였습니다.
최신버전은 170111버전으로 해당 버전의 JS가 로딩이 된다면 오류없이 이용가능 하실 거에요;

아무튼 불편을 드려 죄송합니다 ㅜ.ㅜ

**Comment by daumPostcode** [comment]
@iamytg @HelloSolsol 

추가적으로 다시 답변 드립니다.

현재 문제는 spi.maps.daum.net 의 캐싱 문제로 확인이 되는데요, 브라우저에서 전체 케시를 지우시면 해결이 되긴 합니다. 다만 이는 캐시를 지운 사용자에게 해당되는 내용이고, 일반적인 고객분들은 지속적으로 문제가 발생할 수 있어서,
새로운 도메인으로 알려드리도록 하겠습니다.
새로운 도메인은 해당 이슈를 해결하기 위해 급하게 만들어진 도메인은 아니구요, 이전부터 사용되어온 것이고, 저희 지도 v3 API에서 사용하고 있는 도메인입니다.


```
현재 캐시문제가 발생하는 도메인
https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js

캐싱 문제가 없는 도메인
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js
```

위와 같이 ssl.daumcdn.net 도메인으로 바꾸시면, 질문자님, 그리고 질문자님 사이트에 접속하시는 다른 모든 분들도 문제가 해결될거라 생각됩니다.

다시한번 불편을 드려 죄송합니다 ;;

추가적으로 해당 도메인의 경우 다음주 업데이트때, 가이드 페이지에 반영될 예정이니 걱정하지 않으셔도 됩니다. 감사합니다.
