### ISSUE TITLE
주소등록 해주세요

### ISSUE THREAD

**Issue by park10000jung** [daumPostcode/QnA#961]
대구시 수성구 들안로300

**Comment by daumPostcode** [comment]
@park10000jung 

안녕하세요. 바로바로 답변을 드리지 못해 죄송합니다.

해당 이슈는 판교IDC 화재로 인한 서버의 셧다운 이슈로 시작된 문제이며 현재 정상화 되었습니다.

여러가지 서비스가 물려있어서, 복구가 느려진점 죄송합니다.
자세한 사항은 https://github.com/daumPostcode/QnA/issues/973 해당 공지 참고 부탁드립니다.

감사합니다.
