### ISSUE TITLE
service.v2.min.js:4 Uncaught SyntaxError: An invalid or illegal string was specified. 

### ISSUE THREAD

**Issue by kumquat0601** [daumPostcode/QnA#97]
안녕하세요. 다음 주소 api를 phonegap / jquery mobile 환경에 적용해서 사용하려고 하는데.

콘솔 로그에 위와 같은 오류가 기록 되고 정확한 에러 위치는 

`&&parent.postMessage(j.encodeData(b),j.param.origin)}function c(a){var c=$.extend(a,{action:"done"}`

에서 발생하고 있습니다. service.v2.js 파일을 확인하고 싶은데 min 버전 밖에 확인할 수 없는건가요?

**Comment by daumPostcode** [comment]
@kumquat0601 

네~ 안녕하세요~

현재 팝업페이지에 들어가는 service.v2.min.js의 원본은 제공이 불가능합니다.

일단 저희 서비스는 기본적으로 웹서비스이며, 폰갭으로 실행시에는 정적으로 js/css 파일을 로딩해서 이용하는 방식으로 알고 있습니다. 위와 같이 이용하실 경우, 저희 서비스는 팝업은 뜰지 몰라도 데이터 전송은 안됩니다. 기본적으로 도메인값 확인을 통해 이종도메인 통신 방법을 이용하고 있으며, 해당 내용은

저희 [FAQ 10번](https://github.com/daumPostcode/QnA/blob/master/README.md#10-iosandroid에서-webview를-이용하여-사용할-수-있나요)을 확인해 주시기 바랍니다.

감사합니다.

**Comment by kumquat0601** [comment]
#63 
을 못 읽어봤네요. 해결되면 해결점 올려드릴게요.

**Comment by kumquat0601** [comment]
해결책을 찾았습니다.

`<html>
<head>
	<script type="text/javascript" src="jquery-3.1.1.min.js"></script>
</head>
<body>

    <div id="wrap" style="display:block;border:1px solid;width:100%;height: 600px;margin:0;position:relative;font-size: .9em;">
    </div>

    <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false"></script>
    <script type="text/javascript">
		var element_wrap = document.getElementById('wrap');
		var address_search=function(){
		daum.postcode.load(function(){
			new daum.Postcode({
		            oncomplete: function(data) {
		                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
		                console.log('주소 눌림');
		                 // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.
		                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
		                var fullRoadAddr = data.roadAddress; // 도로명 주소 변수
		                var extraRoadAddr = ''; // 도로명 조합형 주소 변수

		                // 법정동명이 있을 경우 추가한다. (법정리는 제외)
		                // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
		                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
		                    extraRoadAddr += data.bname;
		                }
		                // 건물명이 있고, 공동주택일 경우 추가한다.
		                if(data.buildingName !== '' && data.apartment === 'Y'){
		                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
		                }
		                // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
		                if(extraRoadAddr !== ''){
		                    extraRoadAddr = ' (' + extraRoadAddr + ')';
		                }
		                // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.
		                if(fullRoadAddr !== ''){
		                    fullRoadAddr += extraRoadAddr;
		                }

		                window.parent.postMessage({ roadAddress: ''+fullRoadAddr, jibunAddress: ''+data.jibunAddress}, "file://");

		                address_search();
		            },
		            // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분. iframe을 넣은 element의 높이값을 조정한다.
		            onresize : function(size) {
		            	$('#wrap').trigger('refresh');
		            },
		            width : '100%',
		            height : '100%'
		        	}).embed(element_wrap);
		});
		}
		address_search();
	</script>
</body>
</html>`

위 페이지를 호스팅 서버에 놓고
폰갭측에서 iframe 태그를 이용해 불러온 뒤 window.parent.postMessage 함수를 통해 폰갭측 html파일에 데이터를 넘겨주고 폰갭측에선 window.addEventListener('message', function(event){ console.log(event);}); 이 리스너를 통해서 데이터를 받아서 주소를 처리할 수 있었습니다.

참고 자료는 [여기](https://hackerluddite.wordpress.com/2012/04/15/getting-access-to-a-phones-camera-from-a-web-page/)  였습니다.

**Comment by daumPostcode** [comment]
@kumquat0601 
해결책을 찾아 주셔서 감사드립니다.

기본적으로 저희 우편번호 서비스는 검색팝업에서 postMessage를 보낼때 host정보를 수정할 수 없게 되어 있다보니, 문의 주신 것처럼 위와 같은 환경에서는 데이터 전송이 어려운데, 이를 두번 라우팅 하셔서 받는 방법으로 해결을 하셨군요.

추가적으로 이와 더불어, 
PC에서 팝업으로 띄울때도 팝업 title값이나 기타 팝업을 좀더 커스터마이징 하고 싶을때도, 위와 같은 방법으로 이용하실 수도 있습니다. 실제 해당 방법은 저희 API를 거치지 않고 팝업페이지에 직접 접근하거나, 정적으로 다운받아 이용하는 방법이 아니기 때문에 상황에 따라 권장되는 방법이기도 합니다.

아무튼, 도움을 주셔서 감사드립니다 ^^

즐거운 한주 되세요~~

**Comment by kumquat0601** [comment]
서비스 구현에 도로명 주소 때문에 골치 아팠는데 이런 좋은 api를 공유해주시니 감삿할 따름입니다. 즐거운 한 주 되세요~
