### ISSUE TITLE
우편번호 서비스 호출시 무응답

### ISSUE THREAD

**Issue by Dongho0613** [daumPostcode/QnA#971]
안녕하세요.

우편번호 검색을 위해 서비스 호출시 주소검색을 위한 팝업이 오늘부터 발생되지 않습니다. (호출 시도하면 아무 응답이 없습니다)
어제까지는 주소찾기 팝업은 발생되었습니다. (검색은 불가함 - 데이터 센터 화재로 인한)

무엇을 확인해야할까요?

**Comment by daumPostcode** [comment]
@Dongho0613 
안녕하세요. 바로바로 답변을 드리지 못해 죄송합니다.

여러가지 서비스가 물려있어서, 복구가 느려진점 죄송합니다.
자세한 사항은 https://github.com/daumPostcode/QnA/issues/973 해당 공지 참고 부탁드립니다.

감사합니다.

**Comment by Dongho0613** [comment]
안녕하세요. 답변 감사드립니다.

말씀하신 #973 공지 확인하였습니다. 당사는 spi.maps.daum.net 도메인을 사용하고 있습니다. 

따라서 해당 공지에서 언급된 것과 같이 해당 서버의 직접 관리가 어려워 복구가 지연되면서 당사에서 우편번호 서비스를 호출하였을 때 아래와 같이 응답이 없는 것으로 판단됩니다.

https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js net::ERR_CONNECTION_TIMED_OUT

그렇다면 당사에서는 해당 공지에서 안내하는 것 처럼 API주소를  t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js  로
변경만 하면 되는지요? 별도의 다른 조치는 필요없는지요?

그리고 해당 공지에서 동작이 가능하게끔 hotfix 버전을 배포해두었다는 내용을 확인하였습니다. hotfix버전은 어디서 찾을 수 있으며 이는 정확히 무엇을 의미하는지도 알고 싶습니다.

**Comment by daumPostcode** [comment]
@Dongho0613 

네 일단은 JS API의 도메인을 변경해 주시는게 최우선입니다.

spi.maps 도메인의 경우 현재 매우 불안정한 상태로.. 데이터 딜리버리 측면에서 안좋은 점이 너무 많아서 쓰지 않게 되었습니다.

현재 전사에서 제일 중요한 서버는 t1.daumcdn.net 과 같은 CDN서버라 할 수 있기에;
본문에 적으신 그 URL, 가이드페이지에서 제공하는 그 URL을 이용을 먼저 해주시기 바랍니다.

그 이후의 오류는 다른 문제이므로, 다르게 접근을 해야합니다.

일반 변경을 하신 후에도 발생한다면, 브라우저 캐시를 한번 삭제해 주시고,
그래도 발생한다면 스샷과 함께 말씀해 주시면 감사하겠습니다.
