### ISSUE TITLE
주소검색후 선택히 OnComplte 응답이 오지 않습니다.

### ISSUE THREAD

**Issue by ChoByoungHwan** [daumPostcode/QnA#972]
IDC화재전까지 정상 사용하던 스크립트인데 IDC화재후 정상화되어 주소검색시 정상적으로 주소를 가져오지만
선택했을때 Oncomplte 응답이 오지않습니다.  

이상한점은 브라우저에서 디버깅시 정상적으로 응답이 오지만 C#의 Webbrwer(Webview) 컨트롤러에서 호출시 OnComplte가 오지 않는다는 점입니다.
브라우저 지원문제로 발생했다면 한참전에 발생해야했지만. IDC화재후 정상화 후부터 정상적으로 동작하지가 않습니다.

제가 여러방면으로 테스트해봤을때. Oncomplte CallBack이 안오기보다는 선택하는 액션자체가 전달되지 않는거 같습니다.

아래 현재 사용중인 스크립트입니다.

<html>

<body onload=sample2_execDaumPostcode()>
    <div id='layer' style='position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;'></div>
    <script src='https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js'></script>
    <script type='text/javaScript'>
        // 우편번호 찾기 화면을 넣을 element
        var element_layer = document.getElementById('layer');
        //창열기
        function sample2_execDaumPostcode() {
            new daum.Postcode({
                //strhtml += "onresize:function(size) {";
                //initLayerPosition(size.width,size.height);
                //strhtml += "},
                oncomplete: function (data) {    
                        WEB_Cshap_Script2(data.zonecode , addr, extraAddr);
                   
                },
                width: '100%',
                height: '100%',
                maxSuggestItems: 5
            }).embed(element_layer);
            // iframe을 넣은 element를 보이게 한다.
            element_layer.style.display = 'block';
            // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.
            initLayerPosition(600, 520);
        }
        // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는
        // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,
        // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.
        function initLayerPosition(w, h) {
            var width = w;//우편번호서비스가 들어갈 element의 width
            var height = h;//우편번호서비스가 들어갈 element의 height
            var borderWidth = 1;//샘플에서 사용하는 border의 두께
            // 위에서 선언한 값들을 실제 element에 넣는다.
            element_layer.style.width = width + 'px';
            element_layer.style.height = height + 'px';
            element_layer.style.border = borderWidth + 'px solid';
            // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.
            element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width) / 2 - borderWidth) + 'px';
            element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height) / 2 - borderWidth) + 'px';
        }
        // ************************************************************************
        //	추가한 스크립트
        // ************************************************************************
        //C# -> WEB 전달
        //strhtml += "function Cshap_WEB_Script2(val1,val2) { alert(val1 + ' ' + val2); }";
        // WEB -> C# 전달
        function WEB_Cshap_Script2(val1, val2, val3) {
            if (window.external) {
                window.external.lfn_WEB_Cshap_Script2(val1, val2, val3);
            }
        }
// ************************************************************************
    </script>
</body>

</html>

**Comment by daumPostcode** [comment]
@ChoByoungHwan 

안녕하세요~
아마 당시의 내부 라이브러리 500에러 이슈가 있어서 발생했을 가능성이 있습니다.
현재 해당 이슈도 처리되어 배포되었습니다.

여러가지 서비스가 물려있어서, 복구가 느려진점 죄송합니다.
자세한 사항은 https://github.com/daumPostcode/QnA/issues/973 해당 공지 참고 부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@ChoByoungHwan 
넵 해당 이슈 또한

https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904

이 이슈와 동일한 것 같습니다.
윈도우즈 특정 프로그램의 웹뷰가, 현재 CS들어오는 프로그램들의 경우 브라우저 호환성모드가 IE7경우가 대부분이더라구요..

그래서 현재 그 내장 브라우저 자체에서 파싱 오류가 나는 것인데;
제가 링크 달아둔거 한번 확인해 주시면 감사하겠습니다.

검색뷰까지 배포가 완료되면 다시 공유해 드리겠습니다.

**Comment by daumPostcode** [comment]
@ChoByoungHwan 

안녕하세요~
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835

현재 검색뷰까지 최신 수정본 배포되었습니다.
위 공지 참고해 주시고 한번 확인 부탁드립니다.
