### ISSUE TITLE
<장애복구 공지> 우편번호서비스 장애 복구 알림 및 안정화 작업 진행사항 공지합니다.

### ISSUE THREAD

**Issue by daumPostcode** [daumPostcode/QnA#973]
안녕하세요 우편번호서비스 담당자입니다.

현재 우편번호서비스의 오류가 나던 현상은 대부분 복구가 되었습니다.
이용을 하시는데에는 큰 문제는 없습니다.

다만 몇몇 리소스들에서 500에러가 발생하고 있어서 이 부분을 잡는데 시간이 좀 소요될것으로 보입니다.
즉 API의 동작에 관해서는 정상화가 되었으며, 오류가 발생하더라도 서비스 이용에 불편함이 없는 수준까지는 복구가 완료되었습니다.
(대략 90% 정도라고 보시면 되실것 같습니다)

우편번호 서비스는 불특정 다수의 사용자분들이 사용하시는 서비스라 최대한 빨리 복구를 하고 공지를 해드리고 싶었으나,
이 서비스와 더불어 여러 연관된 서비스들이 엮여있어서 좀 늦은점 진심으로 사과드립니다.

현재 동작이 가능하게끔 hotfix 버전을 배포해 두었으며, 추후 이러한 작은 오류 또한 모두 해결이 된다면 새로운 공지 이슈글로 말씀드리도록 하겠습니다.

한가지 추가로 말씀드리고 싶은점은
저희가 21년도 초부터 "t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" 로 JS API를 하나로 일원화를 하였는데,
기존의 legacy도 같이 유지하고 있었습니다.

기존의 legacy라 함은 ssl.daumcdn.net, dmaps.daum.net, spi.maps.daum.net 도메인을 사용하는 API로,
현재 위 도메인으로 시작하는 JS API를 사용하신다면, t1.daumcdn.net으로 시작하는 도메인으로 변경해 주시기 바랍니다.
위 서버들은 저희가 직접 관리를 하기가 어렵기에 복구가 되는데 시간이 소요될 수 있습니다.

아무튼 최신 JS API의 경우 공식 가이드페이지에도 설명이 되어 있으며, migration 방법도 특별한게 아닌 URL만 바꿔주시고 테스트 해주시면 되는 것이라 꼭 변경해 주시면 감사하겠습니다. (https://postcode.map.daum.net/guide - 공식가이드페이지 기본사용법 참고)

아무튼 최대한 빠른 복구를 위해 노력하겠습니다.
감사합니다.

**Comment by ibin79** [comment]
주말동안 노고에 감사드립니다.

알려주신 21년도부터 바뀐 API 주소로 변경하니, 서비스들이 바로 정상화되네요.

참고) 제 경우 `iframe을 이용하여 레이어 띄우기`로 사용중이라 다음처럼 주소 수정했습니다.

```html
-<img src="//t1.daumcdn.net/localimg/localimages/07/postcode/320/close.png"
+<img src="//t1.daumcdn.net/postcode/resource/images/close.png"

-<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>
+<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
```

---

추신) 공지 이슈를  상단 고정(Pin issue) 해주시면, 반복될 신규 이슈를 줄이는데 도움이 될 것 같습니다.

**Comment by TaeSeungKim2** [comment]
안녕하세요. 장애 대응하시느라 고생 많으십니다.

저희 사이트에서는 기존부터 호환성 보기 설정 환경에서 t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js 주소를 사용 중이었으며 장애 이전 시점에는 정상 동작하였습니다.

하지만 장애 복구 이후 시점부터 스크립트 에러가 발생하고 있습니다. 

- 스크립트 에러 내용
SCRIPT5007: 개체가 필요합니다.
221016hotfix.js (1,18392)

- 에러 발생 소스코드
d.document.write(a(c))

해당 부분 확인 문의 드리고자 합니다!

감사합니다.

**Comment by HwiI** [comment]
#973 확인 후 
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
이렇게 수정하였습니다
c#에서 WebBrowser를 이용하여 사용중인데 우편번호검색 화면 호출 시 스크립트 오류가 발생합니다

오류 : Script error
URL : http://t1.daumcdn.net/postcode/cssjs/service/1665878072553/service.v2.min.js

계속 실행하시겠습니까? 에서 예를 눌러 다음 화면으로 넘어가면 

줄 : 107
문자 : 9
오류 : 'postcodeV2'이(가) 정의되지 않았습니다.
URL : http://postcode.map.daum.net/search?origin=http%3A%2F%2Fwas.mjsoft.co&indaum=off&banner=on&ubl=on&mode=transmit&vt=layer&amr=on&amj=on&ani=off&sd=on&fi=on&fc=on

이렇게 뜹니다

예를 계속 눌러 주소검색을 하더라도 
oncomplete가 동작하지 않는 것 같습니다

확인 문의차 글 남깁니다~

**Comment by javamochakor** [comment]
안녕하세요. 장애 대응에 수고 많으십니다.

장애복구 싯점부터 서비스 점검 중 오류 사항 공유드립니다.

서비스 점검시 SPEC은 마이플랫폼 내 내장브라우져 사용하여 API 우편번호검색 팝업 사용하고 있습니다.

증상은 작년 12월에 발생했던 건과 유사한걸로 예상됩니다.
https://github.com/daumPostcode/QnA/issues/884

내용 확인부탁드립니다.

감사합니다.

**Comment by daumPostcode** [comment]
@HwiI @javamochakor  @TaeSeungKim2 

안녕하세요. 우편번호 서비스 담당자입니다.
공통적으로 내장브라우저에서 뭔가 문제가 발생하는 것으로 보입니다.
해당 부분 확인해 보겠습니다. 장애복구 관련해서는 코드의 수정보다 자동복구가 느려져서 파일을 새로 빌드해서 올린 것인데.

변경점이 있는지 한번 확인해 보도록 하겠습니다.
불편을 드려 죄송합니다.

**Comment by junghun133** [comment]
> #973 확인 후
> 
> <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
> 이렇게 수정하였습니다 c#에서 WebBrowser를 이용하여 사용중인데 우편번호검색 화면 호출 시 스크립트 오류가 발생합니다
> 
> 오류 : Script error URL : http://t1.daumcdn.net/postcode/cssjs/service/1665878072553/service.v2.min.js
> 
> 계속 실행하시겠습니까? 에서 예를 눌러 다음 화면으로 넘어가면
> 
> 줄 : 107 문자 : 9 오류 : 'postcodeV2'이(가) 정의되지 않았습니다. URL : http://postcode.map.daum.net/search?origin=http%3A%2F%2Fwas.mjsoft.co&indaum=off&banner=on&ubl=on&mode=transmit&vt=layer&amr=on&amj=on&ani=off&sd=on&fi=on&fc=on
> 
> 이렇게 뜹니다
> 
> 예를 계속 눌러 주소검색을 하더라도 oncomplete가 동작하지 않는 것 같습니다
> 
> 확인 문의차 글 남깁니다~

@daumPostcode 
안녕하세요.
장애대응에 고생 많으십니다 ㅠ
제가 담당하는 서비스의 C# 에서의 web browser 에서도 동일한 오류가 발생하고 있습니다.
혹시 해당 이슈 조치 중이신 내용이 있을까요?

**Comment by daumPostcode** [comment]
@junghun133 

https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904
넵 현재 정확한 재현환경 구측은 어렵지만 IE7호환성 보기를 통해 보여지는 오류는 잡았습니다.
내일(18일)_ 검색뷰까지 배포가 되면 다시 공유 드리겠습니다.

**Comment by berryzed** [comment]
수고 많으십니다.
180326 버전의 js 파일을 내려받아서 사용 중인데요.
https로 접근 시 `https://spi.maps.daum.net/postcode/search`로 접근이 되면서 404 응답이 발생하고
http로 접근 시 `https://postcode.map.daum.net/search`로 접근이 되면서 동작하고 있습니다.

혹시 해당 이슈를 조치하기 위한 방법이 어떤게 있을까요?

**Comment by junghun133** [comment]
@daumPostcode 검색뷰 배포가 완료된거죠? 저희 서비스에서는 잘 동작하고 있습니다~! 감사합니다
수고많으셨습니다.

**Comment by daumPostcode** [comment]
@HwiI @ibin79 @berryzed @junghun133

안녕하세요~

https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
위 공지 참고 부탁드립니다.
현재 JS API, 검색뷰 모두 최신수정본 반영되었습니다.


@berryzed 
JS API를 복사해서 이용하신다면 최신본으로 갈아껴주셔야 합니다. 현재 legacy 서버들은 완벽한 동작을 보장하기 어렵습니다.
해당 내용은 이 댓글에 링크건 공지사항 보시면 확인 가능하십니다. 원래 이 legacy서버들에 있는 리소스 또한 내년 초쯤에 삭제할 예정이긴 했습니다 (가이드페이지에서 내려간건 21년도 3월달입니다) 
다만 이번장애로 빠른 교체를 권장하고 있습니다.
추가로 복사해서 이용하신다면 추후 추가적인 패치로 인해 문제가 또 발생할 수 있는점 참고 바랍니다.(복사해서 이용하는 경우엔 지원대상이 아닙니다.)
