### ISSUE TITLE
주소검색이 cs에서 웹으로 호출할 경우 작동하지 않습니다.

### ISSUE THREAD

**Issue by HanYeongJong** [daumPostcode/QnA#974]
안녕하세요 포인트뱅크 회사의 웹담당자 한영종 사원입니다.

주말간에 다음주소창이 안되었다가 복구되었다는 소식에 복구가 잘 된 것을 확인하였는데요,

웹페이지 상에서는 정상작동하는데 cs상에서 해당 웹페이지를 호출하는 경우 스크립트 오류가 나타나는 현상이 있습니다.

![image](https://user-images.githubusercontent.com/115960213/196070905-826eb92e-961a-4f05-977b-915257aaeb24.png)

위 이미지를 보시면 cs에서 웹페이지를 호출할 경우 공지사항에 호출하라고 지시되어있던 t1.daumcdn.net의 js파일이 오류가 나고 있는 것이 확인됩니다.

해당 이미지에서 호출한 주소호출 사이트는 http://coceuco.co.kr/cs/zipsearch.asp

해당 경로이며, 크롬,엣지,익스플로러에서 전부 실행 시 정상작동합니다.

해당 문제는 하나의 cs프로그램에서만 발생하지 않고, 모든 cs에서 웹에 호출할때 동일하게 나타나고 있습니다.

![image](https://user-images.githubusercontent.com/115960213/196070503-2ff14f0a-ae2c-463a-949b-bdcfade7fcb9.png)

혹시 해당 스크립트에 한글깨짐이있어 복사하여 내부에 넣은뒤에 한글깨진 것들을 빼고 돌려보았는데도 동일하게 나타나고있습니다.

저희도 개발사여서 해당 문제가 나는 원인을 업체에 전달드려야해서 내부적으로 확인 후 답변해주시면 감사하겠습니다.

답변부탁드립니다.

감사합니다.

포인트뱅크 개발팀 한영종 사원
yjhan@netra21.ent
010-4522-9181

**Comment by yangjaehee** [comment]
하~ 저희도 같은문제에 직면했네요.. 해결방법좀알려주세요

**Comment by daumPostcode** [comment]
@HanYeongJong @yangjaehee 
넵 한번 확인해 보도록 하겠습니다.

보통 오류메세지에 줄번호나 문자번호가 나오긴 하는데; 모두 0이군요.
hotfix가 어제 배포되긴 햇으나, 변화는 없고, 기존파일이 자동복구가 늦어져서 강제로 새로 올린것이긴 한데,

이 부분은 제가 코드 다시 봐보고 재빌드 해서 올려보도록 하겠습니다.

**Comment by daumPostcode** [comment]
@HanYeongJong @yangjaehee 
아 지금 봐보니, legacy모듈을 사용하고 계신데;

현재 우편번호서비스는 21년도 3월달부터 공식가이드페이지에서 스크립트가 변경되었습니다.

https://postcode.map.daum.net/guide

위 사이트에 접속하셔서 기본사용법에 있는 JS파일로 변경해 보시는걸 추천드립니다.
아마 기존에 dmaps.daum.net, ssl.daumcdn, spi.maps.daum.net 등의 도메인에 연결된 파일을 이용중이신것 같습니다.

이는 제가 어제 올린 최신 공지에도 있는 내용으로 한번 JS API 스크립트를 먼저 한번 바꿔보시는걸 권장합니다.

**Comment by HanYeongJong** [comment]
> @daumPostcode 

하단에 있던 캡처본은 그런것같은데 지금 주요하게 보고있는 스크립트에서는

https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

해당 경로를 사용하고있습니다. (위 캡처본 및 공유해드린 링크, http://coceuco.co.kr/cs/zipsearch.asp)

해당 버전이 legacy버전이 아닌 최신버전이 맞는것이죠?

아래 캡처본은 여러군데에서 발생한다라고 공유하고자 한 것인데 저부분에는 과거버전을 사용하고있었나봅니다.

아래 캡처본 링크는 변경해두도록 하겠습니다.

현재 최신경로도 동일한 현상이 발생하고있어 확인 한번 부탁드립니다.

장애 대응하시느라 고생이 많으십니다.

감사합니다.

**Comment by gjwlsgud** [comment]
@daumPostcode

**Comment by daumPostcode** [comment]
@yangjaehee @gjwlsgud @HanYeongJong 

안녕하세요
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835

위 공지 확인 부탁드립니다.

현재 검색뷰와 JS API모두 최신 수정본 반영된 상태입니다. 현재 정상화 소식이 들려오고 있는데 한번 확인 부탁드려요!

**Comment by gjwlsgud** [comment]
@daumPostcode  고생 많으셨습니다. 건강 챙기세요~
