### ISSUE TITLE
오류: 'postcodeV2'이(가) 정의되지 않았습니다.

### ISSUE THREAD

**Issue by ChoiSeongHyun** [daumPostcode/QnA#975]
<div class="popup_foot">     <span class="inner_footer">
    <span class="txt_by">Powered by </span><strong class="img_post tit_kakao">kakao</strong>
    <span class="txt_bar"></span>
        <a href="//postcode.map.daum.net/guide" class="link_infomation" target="_blank">우편번호 서비스 안내</a>
    </span></div>
<script type="text/javascript" src="//t1.daumcdn.net/postcode/cssjs/lib/jquery-1.11.0.min.js"></script>

        <script type="text/javascript" src="//t1.daumcdn.net/postcode/cssjs/service/1665878072553/service.v2.min.js"></script>
    

 <script type="text/javascript">
            $(function(){
        var url = '//postcode.map.daum.net/guide';
        **postcodeV2.setEnvironmentVariables('false', 'PROD');**
        postcodeV2.viewInit(url);
    });
</script>
</body>
</html>

검색까진 가능한데, 검색결과가 부모창으로 내려오지는 않습니다.

오류는         **postcodeV2.setEnvironmentVariables('false', 'PROD');**

에서 뜬다고 나왔습니다.

확인부탁드립니다.

**Comment by crud-stack** [comment]
카카오 서버 화재 이후, 저희도 동일한 현상이 발생하고 있습니다.  확인부탁드립니다.

**Comment by daumPostcode** [comment]
@ChoiSeongHyun @crud-stack 
안녕하세요~ 혹시 웹브라우저 서비스일까요?
아니면 특정 프로그램에서 동작하는 웹뷰이실까요?

그리고 javascript API가 공식 가이드페이지에서 제공하는 t1.daumcdn.net 으로 시작하는 도메인일까요?

**Comment by ChoiSeongHyun** [comment]
@daumPostcode 
웹브라우저 서비스입니다.

		
		<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>

기존에 ssl.~~~~에서

t1.~~~으로 변경했는데도 동일하게 발생됩니다.

**Comment by daumPostcode** [comment]
@ChoiSeongHyun  @crud-stack 

해당 이슈도 https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904
이 이슈와 비슷한 것일 수도 있을 것 같습니다.

setEnviroment~~함수가 없다는건, 이미 그 윗쪽 코드에서 문법오류가 발생해서 파싱에 실패했다는 것이라서, 비슷한 이슈와 같아 보입니다.

혹시 다르다면 해당 오류가 뜨는 OS플랫폼 종류 및 버전, 브라우저 종류 및 버전을 알려주시면 도움이 될것 같습니다.

**Comment by ChoiSeongHyun** [comment]
@daumPostcode 
현재 정상작동하는것 확인했습니다.

배포하신게 잘 작동하는 것 같습니다.

**Comment by daumPostcode** [comment]
@ChoiSeongHyun @crud-stack 

넵 확인 감사합니다.
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
해당 내용은 위 공지에서 확인가능합니다.

검색뷰 또한 금일 오전에 실서버 반영되었습니다.
오류가 수정되서 다행이네요 ㅜ.ㅜ
