### ISSUE TITLE
221016 js 핫픽스 후 IE 8에서 동작하지 않습니다

### ISSUE THREAD

**Issue by delete-null** [daumPostcode/QnA#976]
여건상 당사는 아직도 IE 8 을 사용하는 PC환경이 존재합니다

지난주까지는 IE 8에서도 동작했으나
복구된 js 버전은 최신 브라우저에서만 동작합니다

구 브라우저를 지원해주실 예정이 있으신지 문의드립니다

**Comment by daumPostcode** [comment]
@delete-null 

안녕하세요~

별다른 수정사항은 없는데, 혹시 오류메세지 캡쳐 부탁드립니다.

**Comment by delete-null** [comment]
IE 8 이하에서는 a(c) 부분을 식별하지 못합니다

![image](https://user-images.githubusercontent.com/55178724/196105581-34aafd6d-e25a-4d30-8698-2e02f2fb3516.png)

**Comment by daumPostcode** [comment]
@delete-null 

넵 해당 이슈는 현재 수정은 되었는데 (IE7 호환성 보기 모드로 테스트)
API는 배포되었으나 검색뷰의 경우 내일(18일) 오전에 배포가 가능할 것 같습니다.

한번 이 이후로 확인 부탁드립니다. 제가 배포되면 답글 드리도록 하겠습니다.
https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904

**Comment by daumPostcode** [comment]
@delete-null 

안녕하세요~
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
위 공지 참고 부탁드립니다.

검색뷰 또한 금일 오전 실서버 반영되었습니다.
확인 부탁드립니다!

**Comment by delete-null** [comment]
IE 8 에서 정상동작됩니다
빠른 지원 감사합니다
