### ISSUE TITLE
구형 플랫폼 호환성으로 사용하고 있는 경우 주소 웹페이지 오류가 발생합니다.

### ISSUE THREAD

**Issue by crud-stack** [daumPostcode/QnA#977]
현재 edge 호환성으로 사용하고 있으며, iframe으로 사용하고 있습니다. 
바인딩하는 부분의 콜백을 호출하지 못하고 묵묵무답상태라 확인해보니 오류시점이 다음 주소 웹화면에서 오류가 발생합니다. 

최신 소스코드를 반영한 브라우저에서는 문제가 없으나 구형 플랫폼을 호환성하여 사용중인 사이트에서는 현재 문제입니다. 

현재 복구가 90프로 복구가 되었다고 하신 부분에 대해 이에 해당하는 부분도 포함이 된 건지 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@crud-stack 

안녕하세요~

네 맞습니다. 실제 빌드가 되서 나간 JS파일은 내부적으로는 수정된 부분이 없다고 보셔도 됩니다.
다만 몇몇 라이브러리가 복구가 안되서, 동일한 버전으로 바꾼게 있는데; 이게 당시 업로드 버전과 현재 버전이 달라서 발생하는 문제일 수도 있습니다.

이러한 것들을 하나씩 찾아서 수정작업을 하고 있는데;

현재 14시 쯤에 배포가 한번 되었는데 지금도 안될까요?

혹시 제가 접근할 수 있는 사이트가 있으면 공유 부탁드립니다.
사이트 공개가 어렵다면 (goni.r@kakaocorp.com)으로 메일로 주셔도 됩니다.

**Comment by HanYeongJong** [comment]
@daumPostcode
안녕하세요
해당 글 확인 이후에 오전에 올렸던 문의글 여전히 문제가 있어 cs프로그램파일 메일로 공유하였습니다.
시간되실때 확인 부탁드립니다.  감사합니다.

**Comment by crud-stack** [comment]
현재도 저희는 동일한현상입니다. 내부 업무 프로그램이라 사이트접근을 허용해서 공유드리기는 힘들거 같습니다.

**Comment by daumPostcode** [comment]
@crud-stack @HanYeongJong 

넵 해당이슈도 https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904
이 이슈와 동일한 이슈로 보입니다.

한번 내용 확인해 주시면 좋을 것 같아요.

내일 오전에 검색뷰까지 배포가 되면 다시 공유 드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@crud-stack @HanYeongJong 

안녕하세요
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
위 공지 참고 부탁드립니다.

현재 검색뷰도 수정본 반영되었습니다. 한번 확인 부탁드려요!
