### ISSUE TITLE
다음 api 스크립트 오류..

### ISSUE THREAD

**Issue by junghanK** [daumPostcode/QnA#978]
다음 api 를 이용해서 서비스 되던 주소 검색 기능이 현재 스크립트 오류가 발생하며 동작이 안되고 있습니다.
'이 페이지의 스크립트에서 오류가 발생하였습니다.'
'daum'이 (가) 정의되지 않았습니다. 
라는 오류와 함께 api 실행이 안되는데... 이 부분은 복구가 되고 있는 건가요??

**Comment by daumPostcode** [comment]
@junghanK 

안녕하세요~

어떤 JS API를 사용하고 있는지 알려주시기 바랍니다.

현재 공식가이드 페이지 (https://postcode.map.daum.net/guide)에서 가이드하는 JS API 주소가 아니라면,
발생할 수 있습니다. 이는 20년도 12월부터 21년도 3월가지 변경 가이드를 계속 공지한 부분으로....
바꾸지 못하셨다면 이참에 바꿔주시는걸 추천드립니다.

**Comment by daumPostcode** [comment]
@junghanK 
해당 이슈도
https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904

이 이슈와 비슷할 것으로 추측됩니다.
한번 내용 확인해 주시고,

내일 검색뷰도 배포되면 다시 공유해 드리겠습니다.

**Comment by junghanK** [comment]
@daumPostcode 
저희가 웹과 cs 프로그램 두곳에서 쓰고 있는데 웹은 정상적으로 작동이 되고 문제가 없는데 ....cs 쪽은 현재 검색 창은 뜨는데 검색을 한 주소 내용을 클릭하면 값이 전달되지 않고 반응이 없는 문제점이 있습니다. onComplete: function(data) {
안에 불러오는 값이 뭔가 문제가 있는 듯 합니다..

**Comment by junghanK** [comment]
@daumPostcode 참고로 cs 는 daum.postcode.load(function(){ ..... .open() 방식으로 불러오고 있습니다..

**Comment by junghanK** [comment]
@daumPostcode 아 지금은 정상적으로 잘됩니다!!

**Comment by daumPostcode** [comment]
@junghanK 

넵 다행입니다.
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
위 공지에 적힌 것처럼 금일 오전에 패치본이 나갔습니다.

정상동작한다니 다행입니다!
