### ISSUE TITLE
우편번호 api가 간혈적으로 동작하지않습니다

### ISSUE THREAD

**Issue by manjee-official** [daumPostcode/QnA#979]
현재 앱내의 웹뷰로 보여주는 형식이고 화재전까진 잘 사용했으나 화재이후 많은 빈도로 타임아웃 에러가 나고 있습니다

뭔가 해결이 덜 된걸까요?

**Comment by daumPostcode** [comment]
@manjee-official 
안녕하세요~

현재 일반적인 웹브라우저 환경에서는 CS가 거의 인입이 안되고 있습니다.
다만 특정 프로그램에서 웹뷰로 동작하는 곳에서 이슈가 발생되고 있는데

현재 내부 파일적으로 보면 변경된 부분은 거의 없습니다.
다만 몇몇 라이브러리가 누락되어 이를 같은 버전으로 교체한게 있는데, 지금버전과 당시(몇년전)버전이 소폭 달라서 발생하는 이슈일 수도 있습니다.

보통 특정 프로그램의 웹뷰형식일경우 브라우저의 버전이 낮은 경우가 많아서 문제가 생기는 것으로 판단됩니다.
다만 이게 제가 테스트 환경 구축이 안되는 부분이라, 혹시 제가 확인할 수 있는 방법이 있을까요?

**Comment by manjee-study** [comment]
@daumPostcode 
안녕하세요
현재 웹뷰에서 호출하는 url은 https://temp-cdn.s3.ap-northeast-2.amazonaws.com/html/kakao_address_aos.html 이고

사용하는 postcode url 은 t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js 입니다

**Comment by daumPostcode** [comment]
@manjee-study 

안녕하세요~

현재
https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904

이 이슈에서 발생하는 버그를 수정하였습니다.
API는 배포가 되었으나, 검색화면의 경우 내일(18) 오전중에 배포가 가능할 것으로 보입니다.

한번 이 배포 이후에 다시 한번 확인 부탁드립니다. 현재 플랫폼이 달라보이는데 원인자체가 비슷할 수 있거든요.

**Comment by daumPostcode** [comment]
@manjee-study @manjee-official 

안녕하세요
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
해당 공지 참고해 주시기 바랍니다.

현재 실서버에 검색뷰도 최신 패치본 반영되었습니다.
확인 부탁드립니다.

**Comment by manjee-official** [comment]
확인 했습니다 정상 동작 하는거 같아 close 하겠습니다

감사합니다.
