### ISSUE TITLE
우편번호 확인 요청

### ISSUE THREAD

**Issue by bird3325** [daumPostcode/QnA#98]
안녕하세요.

"경기도 남양주시 진접읍 팔야리 829-4" 의 주소를 검색하면 

http에서는 sido 가 "경기"로 노출이 되고 https 에서는 sido 가 "경기도"로 노출되고 있습니다.

확인 바랍니다.

**Comment by daumPostcode** [comment]
@bird3325 
네~ 안녕하세요.

해당 문제는 캐시문제로, 저희 JS API를 복사해서 사용하는게 아닌 정상 방법으로 이용하신다면, 
브라우저의 캐시를 한번 지워보신 후, 다시 한번 확인 부탁드립니다.

**Comment by bird3325** [comment]
아래의 파일과 같이 다르게 보이고 있습니다. 물론 적용도 마차가지구요.

![2](https://cloud.githubusercontent.com/assets/25072094/21882854/ae4871c8-d8ef-11e6-952d-731317bdbff2.png)
![4](https://cloud.githubusercontent.com/assets/25072094/21882853/ae47dbbe-d8ef-11e6-8e62-9ab4c7553d1b.png)

**Comment by daumPostcode** [comment]
@bird3325 
네;; 혹시 전체 캐쉬를 삭제해 보셨나요??

그리고 가능하시다면 크롬 개발자 도구를 열어서 Network탭에서 170111.js 파일이 불러와지는지 확인 부탁드립니다.

일단 저희 개발 및 테스트 PC/Mac에서 재현이 안되고 있어 확인 부탁드립니다.
![2017-01-12 6 01 24](https://cloud.githubusercontent.com/assets/20675065/21883234/74a701c6-d8f1-11e6-8758-208b0099b2fd.png)
![2017-01-12 6 01 39](https://cloud.githubusercontent.com/assets/20675065/21883241/7ab1612e-d8f1-11e6-9446-edf1e6e0b4c7.png)

**Comment by daumPostcode** [comment]
@bird3325 

다시 답변 드리도록 하겠습니다.
현재 문제는 spi.maps.daum.net 의 캐싱 문제로 확인이 되는데요, 브라우저에서 전체 케시를 지우시면 해결이 되긴 합니다. 다만 이는 캐시를 지운 사용자에게 해당되는 내용이고, 일반적인 고객분들은 지속적으로 문제가 발생할 수 있어서,
새로운 도메인으로 알려드리도록 하겠습니다.
새로운 도메인은 해당 이슈를 해결하기 위해 급하게 만들어진 도메인은 아니구요, 이전부터 사용되어온 것이고, 저희 지도 v3 API에서 사용하고 있는 도메인입니다.


```
현재 캐시문제가 발생하는 도메인
https://spi.maps.daum.net/imap/map_js_init/postcode.v2.js

캐싱 문제가 없는 도메인
https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js
```

위와 같이 ssl.daumcdn.net 도메인으로 바꾸시면, 질문자님, 그리고 질문자님 사이트에 접속하시는 다른 모든 분들도 문제가 해결될거라 생각됩니다.

다시한번 불편을 드려 죄송합니다 ;;

추가적으로 해당 도메인의 경우 다음주 업데이트때, 가이드 페이지에 반영될 예정이니 걱정하지 않으셔도 됩니다. 감사합니다.
