### ISSUE TITLE
익스플로러에서 우편번호 api 빈창

### ISSUE THREAD

**Issue by awesomeini92** [daumPostcode/QnA#980]
안녕하세요.
익스플로러에서 우편번호 찾기를 누르면 빈 창으로 뜨는데 현재 오류와 상관이 있나요? (엣지에선 정상작동됩니다)
postcode.v2.js 예제소스 그대로 가져와서 해봤는데 똑같이 빈 창이 뜹니다. 
아 그런데 https://postcode.map.daum.net/guide에 예제 버튼에서는 읽어옵니다.
제 생각엔 주소를 못 넘겨주는 것 같은데...
이번 사태 전에는 잘 사용했는데 좀더 기다려 봐야 하는지 저희 페이지의 특수한 상황인지 궁금합니다.

**Comment by daumPostcode** [comment]
@awesomeini92 
안녕하세요~

혹시 IE의 버전이 어떻게 될까요?

현재 IE7,8 버전에서의 난독화 버그 이슈로 인해 문제가 발생하고 있습니다.

만약 이게 아닌 IE11이라면, 현재 IE에서도 별문제 없어야 합니다.
만약 현재 테스트 개발중이시라면

https://github.com/daumPostcode/QnA
이 화면의 하단부 Q&A부분을 한번 참고해 주시기 바랍니다. 데이터를 전달하지 못하는 경우, 화면이 하얗게 뜨는 경우에 대한 설명이 있으니 참고부탁드립니다.

**Comment by awesomeini92** [comment]
안녕하세요.
IE11로 확인해보니 잘 됩니다. 감사합니다.
그런데 사용자들의 IE 버전을 다 알지 못하여 아직은 사용을 막아둔 상태입니다.
IE7,8버전에서의 버그는 언제쯤 고쳐질까요?

**Comment by daumPostcode** [comment]
@awesomeini92 

안녕하세요~
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
위 공지 참고해 주시기 바랍니다.

IE7,8 과 관련된 버그 수정본 패치이고, 현재 실서버에 반영되었습니다! 확인 부탁드립니다.
