### ISSUE TITLE
CS 프로그램에서 주소찾기 api 호출 시

### ISSUE THREAD

**Issue by seonJaeKim1** [daumPostcode/QnA#981]
CS 프로그램에서 주소찾기 api 호출 시 스크립트 에러나면서 안되는 분들이 다수 있는 것 같습니다.

확실히 문제가 있어보입니다..

저도 마찬가지구요.

**Comment by daumPostcode** [comment]
@seonJaeKim1 

안녕하세요.
CS프로그램들의 웹뷰가 보통 IE7을 사용하는 것으로 파악됩니다. 이전에도 비슷한 케이스의 오류가 있었는데, 지금 또 발생한 것으로 생각됩니다.

우선 현재 IE7 호환성 보기로 테스트 하여 해당 이슈들 수정하였습니다.
IE개발자 도구가 오류메세지를 명확히 표현해 주지 않고, 제가 테스트하는 환경이 정확히 실환경과 일치하지 않으나,
비슷한 오류가 발생한걸 확인했고 해당 오류들이 뜨지 않도록 수정하였습니다.

코드수정이 없는데 다른 곳에서 발생하였는데; 난독화 모듈의 버그로 의심되고 있습니다(3개의 이슈는 확실히 두가지는 난독화, 한가지는 해결한 시점이 달라서 정확한 인과관계는 알 수 없음)

일단 JS API와 검색화면에서 발생하는 버그는 수정된 것을 확인하였고,
JS API는 배포가 되었지만(221018) 검색화면의 경우엔 내일(18일) 오전중에 배포가 진행될 것 같습니다.

내일 배포가 완료되면 다시 답글 드리도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@seonJaeKim1 

안녕하세요
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835

위 공지 참고 부탁드립니다.

현재 수정본 실서버에 반영되었습니다. 확인 부탁드립니다.
