### ISSUE TITLE
스크립트오류 발생

### ISSUE THREAD

**Issue by cubetech2014** [daumPostcode/QnA#983]
![image](https://user-images.githubusercontent.com/78395740/196110071-53595ee6-9c00-4bd0-bc90-69a122b5d5f7.png)

예 클릭 후 

![image](https://user-images.githubusercontent.com/78395740/196110127-320f6380-c8cd-4c5e-b387-cc4d5c321171.png)

다시 예 클릭 후 

![image](https://user-images.githubusercontent.com/78395740/196110200-29ebc874-3141-4b8a-8838-27265ee56cc8.png)

![image](https://user-images.githubusercontent.com/78395740/196110235-5ea4ad8a-4071-460e-a34b-8a0d569a5eeb.png)

그 이후 주소 선택이 안됩니다.

**Comment by daumPostcode** [comment]
@cubetech2014 
안녕하세요~

해당 이슈또한
https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904

이 이슈와 비슷해 보입니다.

내용 한번 확인해 주시고, 내일(18일) 검색뷰까지 배포가 완료되면 다시 공유해 드리도록 하겠습니다.

**Comment by daumPostcode** [comment]
@cubetech2014 

안녕하세요~
https://github.com/daumPostcode/QnA/issues/987#issue-1412464835
한번 위 공지 참고해 주시기 바랍니다.

해당건 수정본 실서버에 반영되었습니다. 확인요청 드립니다!
