### ISSUE TITLE
넥사크로 플러그인 방식에서 다음 우편번호 검색 API 호출시 스크립트 오류

### ISSUE THREAD

**Issue by leeeun20** [daumPostcode/QnA#984]
안녕하십니까?

현재 다음 우편번호 검색 API를 이용해서 서비스하고 있습니다.

이번 화재 이후, 다음 우편번호 검색 API 호출시 스크립트 오류가 발생하고 있습니다.
기본적으로 웹페이지에서 호출할 경우에는 정상 작동하나,
넥사크로 플러그인 방식에서 해당 서비스를 호출할 경우에는 스크립트 오류가 발생하여 문의드립니다.

해당 오류가 저희뿐아니라 다수 업체에서도 동일 증상이 있는것 같은데 혹시 언제쯤 복구가 가능한지 궁금합니다.

**Comment by daumPostcode** [comment]
@leeeun20 

안녕하세요.

네 해당 이슈또한 
https://github.com/daumPostcode/QnA/issues/974#issuecomment-1280896904

이 이슈와 비슷한 이슈인것 같습니다.

일단 JS API는 배포됬고, 검색뷰는 내일(18일) 오전 중에 배포가 나갈 수 있을 것 같습니다.

검색뷰 배포후에 다시 공유해 드리겠습니다. 그때 한번 캐시 삭제 하시고 확인 부탁드립니다.

**Comment by daumPostcode** [comment]
@leeeun20 

안녕하세요
https://github.com/daumPostcode/QnA/issues/987

한번 위 공지 확인 부탁드립니다.

현재 비슷한 이슈의 해당건 실서버에 반영되었습니다. 확인 부탁드립니다.
