### ISSUE TITLE
주소 검색 오류 문의 드립니다

### ISSUE THREAD

**Issue by Arena-RECO** [daumPostcode/QnA#988]
경기 파주시 다율동 산107-2

위 주소가 카카오맵에서는 검색이 가능한데
( https://map.kakao.com/ )

다음 우편주소 검색 서비스 팝업에서는 없는 검색결과로 나옵니다.
tip 에 적힌 '여기 주소 보기' 를 선택해도 '경기 파주시 다율동 산107-2' 로 표시됩니다.
![image](https://user-images.githubusercontent.com/68100825/196353074-8a33519e-81b4-4ec5-bc22-9dca2a3cb170.png)

**Comment by daumPostcode** [comment]
@Arena-RECO 

안녕하세요~
먼저 저희 데이터의 기반데이터인 행안부 도로명검색시스템의 검색 결과 공유드립니다.
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/20675065/196354757-b8c1520f-d2f5-4b27-b714-6d4d58ce7514.png">

저희희는 기초구역번호(5자리 우편번호)가 발급된 주소만 검색이 되며, 이 기초구역번호가 발급이 될려면 무조건 "도로명 주소"가 발급이 되어야지만 됩니다.

그렇기에 도로명검색 시스템으로 생각하시면 됩니다.

이는 [FAQ 1번](https://github.com/daumPostcode/QnA#1-%EC%A3%BC%EC%86%8C%EA%B0%80-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4--%EA%B2%80%EC%83%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4) 을 참고하시면 아실 수 있습니다.

주소 등록의 경우 행안부 도로명검색시스템에 직접 문의하셔서 발급을 받을 수 있다면 발급을 받으시면 저희도 자동으로 등록됩니다.
(주소는 공공재라 사기업의 임의적인 추가는 불가능 합니다)

PC지도에서 나오는 것은 PC지도는 
- 장소에 매핑된 주소
- 지번주소
- 도로명주소

이 3개를 모두 표시합니다. 즉 "기초구역번호"와 관련이 없습니다.

저흰 시작이 "우편번호"서비스였고, 초기에는 6자리 우편번호를, 그 이후 국가적으로 기본 우편번호가 기초구역번호가 된 이후부터는 5자리 기초구역번호가 발급된 주소만 나오게 됩니다. 이는 행안부 도로명주소검색시스템과 동일한 결과값입니다.

한번 확인 부탁드립니다.
