### ISSUE TITLE
우편번호 찾기 오류 관련 문의드립니다. 

### ISSUE THREAD

**Issue by kohrica** [daumPostcode/QnA#99]
안녕하세요.
현재 우편번호 서비스 사용중입니다만, 
간혹 우편번호 검색창에서 오류가 뜬다는 사용자들이 발생하고 있습니다. 

이러한 사용자들에게 권장할 수 있는  인터넷 설정 등을 안내해주시면 감사하겠습니다. 
(크롬, 인터넷 익스플로러, 사파리 사용 및 인터넷 버전 등을 안내바랍니다.)

**Comment by daumPostcode** [comment]
@kohrica 
네~ 안녕하세요~

현재 우편번호 서비스는 Chrome, Safari, FF, IE 모두 대응하나, 최신버전의 모든 브라우저에서는 정상 동작합니다.
다만 IE의 경우 6-7은 기능적 대응은 하지만 UI가 검색결과에 따라 깨지는 경우가 생길 수 있습니다.

일반적으로 테스트시 모든 브라우저에서 정상 동작을 확인하고 배포를 하긴 합니다.(다만 모든 케이스에 대해서 확인은 조금 어려워, 가끔 버그가 생길 수는 있습니다만, 말씀해 주시면 버그성은 최대한 빠르게 처리하고 있습니다.)

추가적으로 IE의 툴바나 크롬의 익스텐션에 따라 오류가 발생할 수도 있는데요, 이는 유저마다 사용방법이 너무 다르기 때문에 저희가 확인이 거의 불가능하기 때문에, 오류 보고 후, 재현 확인 후에 수정 조치 또는 해결 방법을 안내해 드리고 있습니다.

이 외에 저희 서비스가 저희가 직접 제공을 하는게 아니라, 외부 서비스에 임베딩되어 동작을 하고, Javascript특성상 외부 코드에 영향을 받을 소지가 있기 때문에, 지속적으로 오류가 발생한다면, 사용브라우저와 OS정보, 그리고 웹사이트 정보를 알려주시면 확인 및 처리 가능합니다.(실제로 이런 오류가 많이 들어옵니다.)

마지막으로 모바일서비스의 경우에는, 각 스마트폰의 공식 브라우저의 경우 open(), embed()사용에 관계없이 정상 동작을 하지만, 웹뷰(페이스북, 트위터, 네이버앱, 다음앱, 카카오톡, 라인등의 모든 앱안의 내장브라우저)에서는 open()함수 대응이 상이하여 정상 대응이 안되기 때문에, 모바일 지향 서비스라면 embed함수를 통해 레이어 방식을 사용하시길 권장합니다.
