### ISSUE TITLE
우편번호로 주소 불러오는 기능이 있을까요??

### ISSUE THREAD

**Issue by San-Goon** [daumPostcode/QnA#991]
현재 구축중인 커머스앱의 API형식이 우편번호 / 상세주소 형식으로 되어있어서요!

주문정보 수정을 할 때 우편번호를 기반으로 기본값을 갖고와야하는데, 혹시 방법이 없다면 협업 하시는 분께 수정을 요청하려합니다! 혹시 방법이 있을까요 ㅎㅎ?

**Comment by daumPostcode** [comment]
@San-Goon 
안녕하세요~

아뇨 우편번호 서비스 API자체로는 해당 기능은 없습니다.
이외에도 developers.kakao.com 에서 제공하는 로컬API에도 우편번호 자체로 주소를 검색하는 API는 없는 것으로 알고 있습니다;;

**Comment by San-Goon** [comment]
바쁘실텐데 답변 감사드립니다! ㅎㅎㅎ
