### ISSUE TITLE
주소검색이 안됩니다.

### ISSUE THREAD

**Issue by nextground3** [daumPostcode/QnA#996]
안녕하세요, 오류문의 드립니다. 
get fetch를 통해 api를 호출하고 있습니다. 
https://dapi.kakao.com/v2/local/search/address.json?query=경기 고양시 덕양구 백운길 27-41

행안부에서 검색가능한 주소인데, kakao API에서는 데이터 확인이 불가합니다.
카카오 맵에서도 검색해보니 해당 주소(아파트)를 제대로 가르키지 않고 있네요. 확인 한번 부탁드립니다! 

감사합니다.

주소: **경기 고양시 덕양구 백운길 27-41**

https://www.juso.go.kr/support/AddressMainSearch.do?searchKeyword=%EA%B2%BD%EA%B8%B0+%EA%B3%A0%EC%96%91%EC%8B%9C+%EB%8D%95%EC%96%91%EA%B5%AC+%EB%B0%B1%EC%9A%B4%EA%B8%B8+27-41

**Comment by daumPostcode** [comment]
@nextground3 

안녕하세요~
해당 API는 담당자가 다릅니다.

해당 깃허브 이슈는 postcode.map.daum.net/guide 에 명시되어 있는 JS API에 대한 이슈를 다루고 있습니다.
REST API의 경우에는 제가 담당하는 부분이 아니라 답변이 어렵습니다.

번거로우시겠지만
https://devtalk.kakao.com/c/map-api/101

위 데브톡에 문의 부탁드립니다.

**Comment by nextground3** [comment]
네 @daumPostcode 님, 

확인 감사합니다.
