### ISSUE TITLE
아이폰 리스트 선택 이슈 관련 문의

### ISSUE THREAD

**Issue by Hyunwoo4459** [daumPostcode/QnA#998]
안녕하세요 

다름이아니라 아이폰에서 영상과 같은 현상이 있어서 문의드립니다

https://youtube.com/shorts/haugkFVmWF0?feature=share

검색후 추천검색어 리스트에서 터치해도 반응이 없는 상태입니다 ㅠㅠ

안드, 크롬, 사파리 에서는 정상확인되었는데
아이폰 인앱에서만 이러네요..

네이티브 개발자가 아니여서 잘은 모르겟지만 웹뷰 쪽 문제 일까 싶기도 한데 ..

이슈 클로즈된거까지 아이폰관련 문의는 다 읽어봤는데 비슷한 증상이 없었던거 같아서.. 이렇게 문의드리게 되었습니다

소스는 끼워넣기 예시코드 가져와서 사용중이고 oncomplete에 json 타입으로 데이터를 보내는것 말고는 기본 베이스는 같습니다
Embed, autoclose:false  사용중입니다

환경은
ios 13.3.1 , 16.1 동일하게 발생중이고
아이폰 8, 13미니 에서 확인했습니다..

script type=“text/javascript” src=“http://dmaps.daum.net/map_js_init/postcode.v2.js”

div id =“content_wrap” style=“display:block; width:400px; height:600px;position:relative;overflow:hidden;z-index:q;-webkit-overflow-scrolling:touch;”

답변주시면 감사하겠습니다 !

**Comment by daumPostcode** [comment]
@Hyunwoo4459 
안녕하세요~

네 해당 이슈 확인해 보도록 하겠습니다. 터치 이벤트가 뭔가 이상하게 동작하는 것 같은데; 이 부분은 확인해 봐야 될것 같습니다.

그리고 이 이슈와는 연관이 없지만;
저희 스크립트를 이용하실때 dmaps는 현재 가이드페이지에서 가이드하는 스크립트주소가 아니며, 예전 레거시를 이용하시는 분들을 위해 서빙만 하고 있는 도메인 입니다. 내년쯤에 서버에서 내릴 계획을 가지고 있으니,
현재 공식 가이드페이지(postcode.map.daum.net/guide)를 참고하시어 t1.daumcdn.net 으로 된 스크립트 주소를 이용해 주시기 바랍니다.

**Comment by Hyunwoo4459** [comment]
안녕하세요

답변감사합니다

방금전에 끼워넣기 소스코드로 재확인해봤는데 동일합니다 ㅠㅠ
마찬가지로 크롬, 사파리, 안드인앱에선 정상이지만 아이폰만 안되고있네요 ..

**Comment by daumPostcode** [comment]
@Hyunwoo4459 

네~
제가 말씀하신 단말기가 없어서 
시뮬레이터로, 공식가이드페이지의 끼워넣기 예제로 확인중에 있는데 재현이 안됩니다.

지금 공식가이드페이지에서 소스코드를 가져다가 만드신 페이지 말고,
저희 공식 가이드페이지의 끼워넣기 샘플을 가이드페이지 자체에서 실행해 볼 수 있는데; 그렇게 실행을 해서 되는지 확인 부탁드립니다.

개발하시는 환경이나, 소스코드를 어떻게 적용하셨는지 부모페이지의 코드를 제가 알 수가 없는 환경이기 때문에, 최대한 케이스를 줄여야 합니다.
공식 가이드페이지 자체에서 테스트를 부탁드립니다.

그리고 만약 시뮬레이터에서 확인해 보셨을때 정상으로 된다면;; 실물폰에서의 문제라 볼 수 있기에 제가 해당 단말기를 빌려서 확인해 보면 될것 같습니다.

추가로 공식 가이드페이지에서는 정상이나, 코드를 가져다가 적용하는 페이지에서만 문제가 발생한다면, 해당 환경을 제가 재현할 수 있게 소스코드를 제공해 주시거나, 제가 접속할 수 있는 환경을 알려 주셔야 합니다.
이부분 확인 부탁드립니다.

**Comment by Hyunwoo4459** [comment]
방금 확인해 봤는데 샘플 가이드는 정상이더라구요 ..

소스코드는 여건상 제가 따로 제공해 드리는게 힘들거같습니다;; 부탁하는입장에서 죄송할따름입니다ㅠ

끼워넣기 소스 통째로 테스트페이지 생성해서  html 실행해도 동일한현상이 일어나는데 샘플가이드 통해서 실행했을때는 정상적으로 작동하는거보면, 기기나 스크립트 상의 문제는 아닌거같네요 ㅠㅠ

혹시 영상과 비슷한 사례가 있었던적은 없겠죠..??

**Comment by daumPostcode** [comment]
@Hyunwoo4459 

네. 음.. 가상키보드 관련된 이슈와 연결될 수도 있고, 아니면 다른 이슈일 수도 있는데;
개발자도구를 통해서, 해당 터치가 안되는 부분에 무언가 투명한 레이어가 위치해 있거나 등등 이런거 한번 확인해 보시겠어요?

그리고 만약에 최소한의 코드로 단일 페이지를 만들어서 테스트를 하셨을때 재현환경을 찾으셨다면,

goni.r@kakaocorp.com
으로 메일로 별도로 보내주셔도 됩니다.

**Comment by Hyunwoo4459** [comment]
@daumPostcode 
안녕하세요~

가상키보드 이슈였습니다 ㅜㅠ
웹뷰쪽에서 키보드 내려주는 처리가 잘못되어서 발생한것같습니다

빠르고 친절한 대응 감사합니다 !
